
	<form name="<?php echo $this->form->getName(); ?>" id='frmCabecera' action="<?php echo $this->form->getAction(); ?>" method="post" enctype="multipart/form-data">
 	<div class="accordion" id="accordion2" style="margin: 0px 80px 0px 80px">
	 	<div class="panel panel-default">
		        	<div class="panel-heading">
		        		<h6 class="panel-title" style="font-size:14px">
			             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse5">
			                	<?php echo $rom?>Inserte su Logo
			                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
			              	</a>
		        		</h6>
		        	</div>
		        	<div id="collapse5" class="panel-collapse collapse">
		              	<div class="panel-body">
				        	<?php echo $this->form->header?>
				        	<?php echo $this->form->save?>
		              	</div>
		         	</div>
		</div>
	</div>
		<script>
		(function($) {
		  $(document).ready(function() {
		    $('#header').wysiwyg();
		  });
		})(jQuery);
		</script>
	</form>

