<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">

<table class="table span8">
		<th style="font-size: 20px" class="span8">Modificar Sede</th>
       		<td><a><?php print $this->form->update;?></a></td>
      	   	<td><br><a href="/soporte/subsidiary"  class="btn btn-info" >Cancelar</a></td>	
</table>

<table class="table span6 table-striped table-bordered">
	<tr>
        <div class="control-group">
          <td class="span4"><label class="control-label">Codigo:</label></td>
          <td class="span4"><div class="controls">
            <?php print $this->form->subid;?>
          </div></td>
        </div>
    </tr>

    <tr>
        <div class="control-group">
          <td><label class="control-label">Nombre Sede:</label></td>
          <td><div class="controls">
            <?php print $this->form->name;?>
          </div></td>
        </div>
    </tr>

    <tr>
        <div class="control-group">
          <td><label class="control-label">Estado:</label></td>
          <td><div class="controls">
            <?php print $this->form->state;?>
          </div></td>
        </div>
    </tr>
</table>

</form>