<?php
if ($this->lper ){ ?>
	 <option value="">- Seleccione -</option>
    <?php 
    foreach ($this->lper  as $perio){ ?>
        <option value="<?php echo $perio['perid']?>"><?php echo $perio['perid']." | ".$perio['name']?></option>
        <?php
    }
}else{ ?>    
    <script>
       alert("Crear periodo para el año elegido");
    </script>
        <option value="">No tienen ningun periodo</option>
    <?php
} ?> 