<?php 
	$dataView       = $this->dataView;
	$dataCurriculum = $dataView['dataCurriculum'];
	$dataCourses    = $dataView['dataCourses'];
	$form_course    = $dataView['form_course'];
 ?>

<div class="modal_admin_courses">
	<header>
		<p><?php echo $dataCurriculum['name'] ?> <small><?php echo $dataCurriculum['curid'] ?></small></p>
		<div>
			<a id="btn_add_course" href="##">Agregar Curso</a>
		</div>
	</header>
	<section id="id_add_new_course" class="new_course">
		
	</section>
	<article>
		<?php if ($dataCourses): ?>
			<?php foreach ($dataCourses as $semester): ?>
				<section class="semester">
					<header>
						<span class="glyphicon glyphicon-flag"></span> Semestre <?php echo $semester['semid'] ?>
					</header>
					<section id="id_section_semester<?php echo $semester['semid'] ?>">
						<article class="title">
							<span>#</span>	
							<span>Código</span>
							<span>Nombre</span>
							<span>Créditos</span>
							<span>Tipo</span>
							<span>Requisíto</span>
							<span>Estado</span>
							<span></span>
						</article>
					<?php foreach ($semester['courses'] as $c => $course): ?>
						<div id="id_course_<?php echo $course['id'] ?>" class="all_course_data" idactivatejs="<?php echo $course['id'] ?>">
							<article class="data_course">
								<span><?php echo $c + 1 ?></span>	
								<span><?php echo $course['id'] ?></span>
								<span><?php echo $course['name'] ?></span>
								<span><?php echo $course['credits'] ?></span>
								<span><?php echo $course['name_type'] ?></span>
								<span><?php echo $course['req_1'] ?></span>
								<?php if ($course['state'] == 'A'): ?>
									<span class="stateA"><?php echo $course['state'] ?></span>
								<?php else: ?>
									<span class="stateB"><?php echo $course['state'] ?></span>
								<?php endif ?>
								<a href="##" class="btn_edit_course" code="<?php print $course['idget'] ?>">Editar</a>
							</article>
							<article class="edit_course">

							</article>
						</div>
							
					<?php endforeach ?>
					</section>
				</section>
			<?php endforeach ?>
		<?php else: ?>
			<br><br><br><br><br><br><br>
			<p><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> Esta currícula no tiene cursos...</p>
		<?php endif ?>
	</article>
</div>