<?php 
	$dataView = $this->dataView;
 ?>

<header class="modal_header">
	<p>Detalle de Currícula </p>
	<div>
		<p><span>Facultad de </span><?php echo $dataView['nameFac'] ?></p>
		<p><span>Escuela de </span><?php echo $dataView['nameEsc'] ?> 
			<?php if ($dataView['isEsp'] == 'yes'): ?>
				- <?php echo $dataView['nameEsp'] ?>
			<?php endif ?>
		</p>
	</div>
	<div>
		<a class="btn btn-default form-control" href="##" data-dismiss="modal">Cerrar</a>
	</div>
</header>
<div class="header_body">
	<div id="idHeaderDetail">
		<?php if ($dataView['rid'] == 'RC'): ?>
			<?php if ($dataView['state'] == 'B' or $dataView['state'] == 'A'): ?>
				<p><span class="glyphicon glyphicon-info-sign"></span> Administre desde aqui la curricula...</p>
				<div>
					<a href="##" id="detailCur_btnAdminCourses">Cursos</a>
				</div>
				<div>
					<a href="##" id="detailCur_btnEditCur">Editar</a>
				</div>
				<div>
					<a href="/curricula/curricula/print/id/<?php echo $dataView['id_cur'] ?>" id="detailCur_btnPrintCur">Imprimir</a>
				</div>
			<?php elseif ($dataView['state'] == 'C' or $dataView['state'] == 'T'): ?>
				<p><span class="glyphicon glyphicon-info-sign"></span> Visualice los detalles de la currícula...</p>
				<div></div>
				<div>
					<a href="##" id="detailCur_btnAdminCourses">Cursos</a>
				</div>
				<div>
					<a href="/curricula/curricula/print/id/<?php echo $dataView['id_cur'] ?>" id="detailCur_btnPrintCur">Imprimir</a>
				</div>
			<?php endif ?>
		<?php elseif ($dataView['rid'] == 'DR'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Visualice los detalles de la currícula...</p>
			<div>
				<a href="##" id="detailCur_btnAdminCourses">Cursos</a>
			</div>
			<div>
				<a href="##" id="detailCur_btnEditCur">Editar</a>
			</div>
			<div>
				<a href="/curricula/curricula/print/id/<?php echo $dataView['id_cur'] ?>" id="detailCur_btnPrintCur">Imprimir</a>
			</div>
		<?php elseif ($dataView['rid'] == 'RF' or $dataView['rid'] == 'CU'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Visualice los detalles de la currícula...</p>
			<div></div>
			<div>
				<a href="##" id="detailCur_btnAdminCourses">Cursos</a>
			</div>
			<div>
				<a href="/curricula/curricula/print/id/<?php echo $dataView['id_cur'] ?>" id="detailCur_btnPrintCur">Imprimir</a>
			</div>
		<?php endif ?>
	</div>
	<div id="idHeaderEdit" class="headerEdit">
		<p><span class="glyphicon glyphicon-info-sign"></span> Edite los cámpos necesarios...</p>
		<div>
			<a href="##" id="detailCur_edit_btnBackToDetail">Regresar</a>
		</div>
	</div>
	<div id="idHeaderAdmin" class="headerEdit">
		<?php if ($dataView['rid'] == 'RC'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Administre los cursos de esta currícula...</p>
			
		<?php elseif ($dataView['rid'] == 'RF' or $dataView['rid'] == 'DR' or $dataView['rid'] == 'CU'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Visualice los cursos de esta currícula...</p>
		<?php endif ?>
		<div>
			<a href="##" id="detailCur_courses_btnBackToDetail">Regresar</a>
		</div>
	</div>
</div>

<!-- Detalle de Curricula -->
<div id="idDivDetailCurricula" class="detail_curricula">
	
</div>

<!-- Editar Curricula -->
<div id="idDivEditCurriculum" class="edit_curriculum">

</div>

<!-- Admin Cursos -->
<div id="idDivAdminCourses" class="admin_courses">
	
</div>
