<div>
	<h4>
		<span class="glyphicon glyphicon-th-list"></span> 
		GESTIÓN CURRÍCULA
	</h4>
</div>
<div>
	<table class="table table-hover span10">
		<tr>
			<th>Facultad:</th>
			<td>
				<select id="facid" class="form-control" style="width:280px">
					<option value="">- Seleccione -</option>
					<?php
					if ($this->facultad) { 
						foreach ($this->facultad as $facultad) { ?>
							<option value="<?php echo $facultad['facid']?>"><?php echo $facultad['name']?></option>
						<?php
						}
					}?>
				</select>
			</td>
			<th>Escuela:</th>
			<td>
				<select id="escid" class="form-control" style="width:280px">
					<option value="">- Seleccione -</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div id="curriculas"></div>

<script type="text/javascript">
	$("#facid").change(function(){
		$("#facid option:selected").each(function(){
			var facid=$.base64.encode($(this).val());
			$.get('/curricula/curricula/schools',{facid:facid},function(data){
				$("#escid").html(data);
			});
		})
	});
	$("#escid").change(function(){
		$("#escid option:selected").each(function(){
			var tmp=$.base64.encode($(this).val());
			if (tmp=="") {
				alert("Seleccione una Escuela.");
				return false;
			};
			$("#curriculas").html("<img src='/img/spinner.gif'>Cargando...");
			$.get('/curricula/curricula/curriculas',{escid:tmp},function(data){
				$("#curriculas").html(data);
			});
		})
	});

	var facid = "<?php echo $this->facid?>";
	if (facid!="") {
		$("#facid").val(facid);
		$("#facid").attr('disabled',true);
		$.get('/curricula/curricula/schools',{facid:$.base64.encode(facid)},function(data){
				$("#escid").html(data);
		});
	};

	var isdirector = "<?php echo $this->isdirector?>";
	if (isdirector=="S") {
		var escid = "<?php echo $this->escid?>";
		var subid = "<?php echo $this->subid?>";
		$("#escid").attr('disabled',true);
		$.get('/curricula/curricula/curriculas',{escid:$.base64.encode(escid+"--"+subid)},function(data){
				$("#curriculas").html(data);
		});
	};
</script>