<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-th-list"></span> Gestión Currícula');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<div class='row'>
	<div class='col-md-12 col-md-offset-2'>
		<div class='col-md-1'>Facultad:</div>
		<div class='col-md-3'>
			<select id="facid" class="form-control" style="width:280px">
				<option value="">- Seleccione -</option>
				<?php
				if ($this->facultad) { 
					foreach ($this->facultad as $facultad) { ?>
						<option value="<?php echo $facultad['facid']?>"><?php echo $facultad['name']?></option>
					<?php
					}
				}?>
			</select>
		</div>
		<div class='col-md-1'>Escuela:</div>
		<div class='col-md-3'>
			<select id="escid" class="form-control" style="width:280px">
				<option value="">- Primero seleccione una Facultad -</option>
			</select>

		</div>
	</div>
</div><br><hr><br>

<div id="curriculas"></div>

<script type="text/javascript">
	$("#facid").change(function(){
		$("#facid option:selected").each(function(){
			var facid=$.base64.encode($(this).val());
			$.get('/curricula/curricula/schools',{facid:facid},function(data){
				$("#escid").html(data);
			});
		})
	});
	$("#escid").change(function(){
		$("#escid option:selected").each(function(){
			var tmp=$.base64.encode($(this).val());
			if (tmp=="") {
				alert("Seleccione una Escuela.");
				return false;
			};
			$("#curriculas").html("<img src='/img/spinner.gif'>Cargando...");
			$.get('/curricula/curricula/curriculas',{escid:tmp},function(data){
				$("#curriculas").html(data);
			});
		})
	});

	var facid = "<?php echo $this->facid?>";
	if (facid!="") {
		$("#facid").val(facid);
		$("#facid").attr('disabled',true);
		$.get('/curricula/curricula/schools',{facid:$.base64.encode(facid)},function(data){
				$("#escid").html(data);
		});
	};

	var isdirector = "<?php echo $this->isdirector?>";
	if (isdirector=="S") {
		var escid = "<?php echo $this->escid?>";
		var subid = "<?php echo $this->subid?>";
		$("#escid").attr('disabled',true);
		$.get('/curricula/curricula/curriculas',{escid:$.base64.encode(escid+"--"+subid)},function(data){
				$("#curriculas").html(data);
		});
	};
</script>