<?php $dataView = $this->dataView ?>
<?php if ($dataView['specialities']): ?>
	<header class="select_speciality">
		<p><span class="glyphicon glyphicon-flag"></span> Esta escuela tiene especialidades, filtre entre ellas.</p>
		<div>
			<select class="form-control" name="speciality" id="selectSpeciality">
				<?php foreach ($dataView['specialities'] as $speciality): ?>
					<option value="<?php echo $speciality['escid'].'_'.$speciality['subid'] ?>"><?php echo $speciality['name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>
	</header>
	<?php if ($dataView['rid'] == 'RC'): ?>
		<header class="plusnew">
			<p><span class="glyphicon glyphicon-info-sign"></span> Administre todas las curriculas pertenecientes a esta especialidad...</p>
			<a href="##" id="btnNewModal" class="btn btn-success" data-toggle="modal" data-target="#modalNewCur">Nueva Currícula</a>
		</header>
	<?php endif ?>
<?php else: ?>
	<input type="hidden" id="selectSpeciality" value="<?php echo $dataView['dataCurriculums'][0]['code'] ?>">
	<header class="plusnew">
		<?php if ($dataView['rid'] == 'RC'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Administre todas las curriculas pertenecientes a esta escuela...</p>
			<a href="##" id="btnNewModal" class="btn btn-success" data-toggle="modal" data-target="#modalNewCur">Nueva Currícula</a>
		<?php elseif ($dataView['rid'] == 'RF' or $dataView['rid'] == 'CU'): ?>
			<p><span class="glyphicon glyphicon-info-sign"></span> Estas son las curriculas de la escuela...</p>
		<?php endif ?>
	</header>
<?php endif ?>

<?php if ($dataView['dataCurriculums']): ?>
	<?php foreach ($dataView['dataCurriculums'] as $cS => $school): ?>
		<div id="curriculums<?php echo $school['code'] ?>" class="curriculums" hidden>
			<span hidden><?php echo $school['code'] ?></span>
			<!-- Curriculas en Borrador -->
			<?php if ($school['draft'] and $dataView['rid'] == 'RC'): ?>
				<?php $curriculumDrafts = $school['draft'] ?>
				<div class="main main_draft">
					<p class="draftP"><span class="glyphicon glyphicon-exclamation-sign"></span> Tiene Currículas en Borrador, haga algo con estos...</p>
					<div id="divDraft<?php echo $school['code'] ?>" class="div_draft">
						<?php foreach ($curriculumDrafts as $c => $curriculum): ?>
							<div class="curriculum" id="curriculum<?php print $curriculum['idjs'] ?>" idactivatejs="<?php print $curriculum['idjs'] ?>" state="B">
								<span><?php echo $c + 1 ?></span>
								<span><span class="nameChangeEdit"><?php echo $curriculum['name'] ?></span> <small><?php echo $curriculum['curid'] ?></small></span>
								<span>Año <?php echo $curriculum['year'] ?></span>

								<!-- Botonera Olimpica lml!!! -->
								<div class="modify draftModify">
									<?php $ulrAdminCourses = '/curricula/curricula/listcourses/id/'.$curriculum['id'] ?>
									<a href="##" ide="<?php echo $curriculum['id'] ?>" idjs="<?php print $curriculum['idjs'] ?>" class="btnDetailCur" data-toggle="modal" data-target="#modalDetailCur" title="Mire los detalles de esta currícula...">Administrar Curricula</a>
									<a href="##" class="btn_derive" ide="<?php echo $curriculum['id'] ?>" goto="<?php print $curriculum['idjs'] ?>">Derivar</a>
									<a href="##" class="btn_delete" ide="<?php echo $curriculum['id'] ?>" type="delete" goto="<?php print $curriculum['idjs'] ?>">Eliminar</a>

									<div class="derive_from_draft" fromto="<?php print $curriculum['idjs'] ?>">
										<a href="##" type="active">Activar Curricula</a>
										<a href="##" type="temporary">Mover a Temporales</a>
										<a href="##" type="close">Cerrar Curricula</a>
									</div>
								</div>
							</div>

							<!--Alertas Curricula en Borrador-->
							<div id="curriculum_confirm<?php print $curriculum['idjs'] ?>" fromto="<?php print $curriculum['idjs'] ?>" class="confirms_side">
								<div class="confirm_side delete_curriculum" type="delete">
									<p>Confírme si desea eliminar esta currícula...</p>
									<a href="##" whycallme="D">Si, quiero eliminarla</a>
									<a href="##">Cancelar</a>
								</div>
								<div class="confirm_side active_curriculum" type="active">
									<p>Confírme si desea activar esta currícula, si hay otra activa ésta la remplazara...</p>
									<a href="##" whycallme="A">Si, quiero activarla</a>
									<a href="##">Cancelar</a>
								</div>
								<div class="confirm_side temporary_curriculum" type="temporary">
									<p>Confírme si desea mover esta currícula a temporales...</p>
									<a href="##" whycallme="T">Si, quiero moverla a temporales</a>
									<a href="##">Cancelar</a>
								</div>
								<div class="confirm_side close_curriculum" type="close">
									<p>Confírme si desea cerrar esta currícula...</p>
									<a href="##" whycallme="C">Si, quiero cerrarla</a>
									<a href="##">Cancelar</a>
								</div>
							</div>
						<?php endforeach ?>
						<div class="empty empty_message successClose">
							<p><span class="glyphicon glyphicon-ok"></span> Ya no tiene nada en borradores, buen trabajo...</p>
						</div>
					</div>
				</div>
			<?php else: ?>
				<div class="main main_draft main_hide">
					<p class="draftP"><span class="glyphicon glyphicon-exclamation-sign"></span> Tiene Currículas en Borrador, haga algo con estos...</p>
					<div id="divDraft<?php echo $school['code'] ?>" class="div_draft">
						
						<div class="empty empty_message successClose">
							<p><span class="glyphicon glyphicon-ok"></span> Ya no tiene nada en borradores, buen trabajo...</p>
						</div>
					</div>
				</div>
			<?php endif ?>
				

			<!-- Curricula Activa -->
			<?php if ($school['active']): ?>
				<?php $curriculumActive = $school['active'] ?>
				<div class="main main_active">
					<p class="activeP"><span class="glyphicon glyphicon-ok"></span> Curricula Activa</p>
					<div class="div_active">
						<div id="curriculum<?php print $curriculumActive['idjs'] ?>" class="curriculum" idactivatejs="<?php print $curriculumActive['idjs'] ?>" idget="<?php echo $curriculumActive['id'] ?>" state="A">
							<span><span class="glyphicon glyphicon-ok"></span></span>
							<span><?php echo $curriculumActive['name'] ?> <small><?php echo $curriculumActive['curid'] ?></small></span>
							<span>Año <?php echo $curriculumActive['year'] ?></span>
							<!-- Botonera Olimpica lml!!! -->
							<div class="modify active_modify">
								<a href="##" ide="<?php echo $curriculumActive['id'] ?>" idjs="<?php print $curriculumActive['idjs'] ?>" class="btnDetailCur" data-toggle="modal" data-target="#modalDetailCur" title="Mire los detalles de esta currícula...">Detalles</a>
								<a href="/curricula/curricula/print/id/<?php echo $curriculumActive['id'] ?>">Imprimir</a>
							</div>
						</div>
					</div>
				</div>
			<?php else: ?>
				<div class="main main_active">
					<p class="activeP"><span class="glyphicon glyphicon-remove"></span> Curricula Activa</p>
					<div class="curriculum empty">
						<p><span class="glyphicon glyphicon-exclamation-sign"></span> No hay curricula activa...</p>
					</div>
					<div class="div_active">
						
					</div>
				</div>
			<?php endif ?>

			<!-- Curriculas Temporales -->
			<?php if ($school['temporary']): ?>
				<?php $curriculumTemporaries = $school['temporary'] ?>
				<div class="main main_temporary">
					<p class="temporaryP"><span class="glyphicon glyphicon-time"></span> Curriculas Temporales</p>
					<div class="div_temporary">
						<?php foreach ($curriculumTemporaries as $c => $curriculum): ?>
							<div id="curriculum<?php print $curriculum['idjs'] ?>" class="curriculum" idactivatejs="<?php print $curriculum['idjs'] ?>" state="T">
								<span><?php echo $c + 1 ?></span>
								<span><?php echo $curriculum['name'] ?> <small><?php echo $curriculum['curid'] ?></small></span>
								<span>Año <?php echo $curriculum['year'] ?></span>
								<?php if ($dataView['rid'] == 'RC'): ?>
									<div class="modify temporary_modify">
										<a href="##" ide="<?php echo $curriculum['id'] ?>" idjs="<?php print $curriculum['idjs'] ?>" class="btnDetailCur" data-toggle="modal" data-target="#modalDetailCur" title="Mire los detalles de esta currícula...">Detalles</a>
										<a href="##" class="btn_derive" ide="<?php echo $curriculum['id'] ?>" goto="<?php print $curriculum['idjs'] ?>">Derivar</a>
										<a href="/curricula/curricula/print/id/<?php echo $curriculum['id'] ?>">Imprimir</a>

										<div class="derive_from_draft" fromto="<?php print $curriculum['idjs'] ?>">
											<a href="##" type="active">Activar Curricula</a>
											<a href="##" type="close">Cerrar Curricula</a>
										</div>
									</div>
								<?php elseif ($dataView['rid'] == 'DR' or $dataView['rid'] == 'RF' or $dataView['rid'] == 'CU'): ?>
									<div class="modify active_modify">
										<a href="##" ide="<?php echo $curriculum['id'] ?>" idjs="<?php print $curriculum['idjs'] ?>" class="btnDetailCur" data-toggle="modal" data-target="#modalDetailCur" title="Mire los detalles de esta currícula...">Detalles</a>
										<a href="/curricula/curricula/print/id/<?php print $curriculum['id'] ?>">Imprimir</a>
									</div>
								<?php endif ?>
							</div>
							
							<?php if ($dataView['rid'] == 'RC'): ?>
								<!--Alertas Curricula Temporales-->
								<div id="curriculum_confirm<?php print $curriculum['idjs'] ?>" fromto="<?php print $curriculum['idjs'] ?>" class="confirms_side">
									<div class="confirm_side delete_curriculum" type="delete">
										<p>Confírme si desea eliminar esta currícula...</p>
										<a href="##" whycallme="D">Si, quiero eliminarla</a>
										<a href="##">Cancelar</a>
									</div>
									<div class="confirm_side active_curriculum" type="active">
										<p>Confírme si desea activar esta currícula, si hay otra activa ésta la remplazara...</p>
										<a href="##" whycallme="A">Si, quiero activarla</a>
										<a href="##">Cancelar</a>
									</div>
									<div class="confirm_side temporary_curriculum" type="temporary">
										<p>Confírme si desea mover esta currícula a temporales...</p>
										<a href="##" whycallme="T">Si, quiero moverla a temporales</a>
										<a href="##">Cancelar</a>
									</div>
									<div class="confirm_side close_curriculum" type="close">
										<p>Confírme si desea cerrar esta currícula...</p>
										<a href="##" whycallme="C">Si, quiero cerrarla</a>
										<a href="##">Cancelar</a>
									</div>
								</div>
							<?php endif ?>
						<?php endforeach ?>
						<div class="empty empty_message elseClose">
							<p><span class="glyphicon glyphicon-exclamation-sign"></span> No hay curriculas temporales...</p>
						</div>
					</div>
				</div>
			<?php else: ?>
				<div class="main main_temporary main_hide">
					<p class="temporaryP"><span class="glyphicon glyphicon-time"></span> Curriculas Temporales</p>
					<div class="div_temporary">

						<div class="empty empty_message elseClose">
							<p><span class="glyphicon glyphicon-exclamation-sign"></span> No hay curriculas temporales...</p>
						</div>
					</div>
				</div>
			<?php endif ?>
			
			<!-- Curriculas Cerradas -->
			<?php if ($school['close']): ?>
				<?php $curriculumClose = $school['close'] ?>
				<div class="main main_close">
					<p class="closeP"><span class="glyphicon glyphicon-lock"></span> Curriculas Cerradas</p>
					<div class="div_close">
						<?php foreach ($curriculumClose as $c => $curriculum): ?>
							<?php $idJS = base64_decode($curriculum['id']) ?>
							<div id="curriculum<?php print $curriculum['idjs'] ?>" class="curriculum" idactivatejs="<?php print $curriculum['idjs'] ?>" state="C">
								<span><?php echo $c + 1 ?></span>
								<span><?php echo $curriculum['name'] ?> <small><?php echo $curriculum['curid'] ?></small></span>
								<span>Año <?php echo $curriculum['year'] ?></span>
								<div class="modify close_modify">
									<a href="##" ide="<?php echo $curriculum['id'] ?>" idjs="<?php print $curriculum['idjs'] ?>" class="btnDetailCur" data-toggle="modal" data-target="#modalDetailCur" title="Mire los detalles de esta currícula...">Detalles</a>
									<a href="/curricula/curricula/print/id/<?php echo $curriculum['id'] ?>">Imprimir</a>
								</div>
							</div>
						<?php endforeach ?>
					</div>
				</div>
			<?php else: ?>
				<div class="main main_close">
					<p class="closeP"><span class="glyphicon glyphicon-lock"></span> Curriculas Cerradas</p>
					<div class="curriculum empty temporary">
						<p><span class="glyphicon glyphicon-exclamation-sign"></span> No hay curriculas cerradas...</p>
					</div>
					<div class="div_close"></div>
				</div>
			<?php endif ?>

			<!-- No temporales (no importante en pantalla) -->
			<?php if (!$school['temporary']): ?>
				<div class="main main_temporary for_message">
					<p class="temporaryP"><span class="glyphicon glyphicon-time"></span> Curriculas Temporales</p>
					<div class="curriculum empty temporary">
						<p><span class="glyphicon glyphicon-exclamation-sign"></span> No hay curriculas temporales...</p>
					</div>
				</div>
			<?php endif ?>
		</div>
	<?php endforeach ?>
<?php endif ?>

<!-- Modal para nueva curricula -->
<div id="modalNewCur" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal_medium">
		<div id="dataFormNewCur" class="modal-content new">
		
		</div>
	</div>
</div>


<!-- Modal para detalle de curricula -->
<div id="modalDetailCur" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal_medium modal_detailCur">
		<div id="dataDetailCur" class="modal-content edit">

		</div>
	</div>
</div>
