<?php 
if ($this->option=="V") { ?>
	<table class="table">
		<tr>
			<th><center>Codigo Generado</center></th>
			<th><center>Año</center></th>
			<th><center>Periodo</center></th>
			<th><center>Tipo Curricula</center></th>
			<th><center>Estado</center></th>
		</tr>
		<tr>
			<td style="width:100px">
				<center><?php echo $this->curricula['curid']?></center>
			</td>
			<td>
				<center><?php echo $this->curricula['year']?></center>
			</td>
			<td style="width:80px">
				<center>
					<?php 
					echo $this->curricula['cur_per_ant']?>
				</center>
			</td>
			<td>
				<center>
					<?php 
					echo ($this->curricula['type']=="A")? "Anual":"Semestral";?>
				</center>
			</td>
			<td style="width:110px">
				<center>
					<?php 
					switch ($this->curricula['state']) {
						case 'A': echo "Activa"; break;
						case 'T': echo "Temporal"; break;
						case 'B': echo "Borrador"; break;
						case 'C': echo "Cerrada"; break;
					} ?>
				</center>
			</td>
		</tr>
		<tr>
			<th colspan="3"><center>Nombre de Plan Curricular</center></th>
			<th colspan="2"><center>Alias de Plan Curricular</center></th>
		</tr>
		<tr>
			<td colspan="3">
				<center><?php echo $this->curricula['name']?></center>
			</td>
			<td colspan="2">
				<center><?php echo $this->curricula['alias']?></center>
			</td>
		</tr>
		<tr>
			<th><center>N° Periodos</center></th>
			<th><center>N° Cursos Obligatorios</center></th>
			<th><center>N° Cursos Electivos</center></th>
			<th><center>N° Créditos Obligatorios</center></th>
			<th><center>N° Créditos Electivos</center></th>
		</tr>
		<tr>
			<td>
				<center><?php echo $this->curricula['number_periods']?></center>
			</td>
			<td>
				<center><?php echo $this->curricula['mandatory_course']?></center>
			</td>
			<td>
				<center><?php echo $this->curricula['elective_course']?></center>
			</td>
			<td>
				<center><?php echo $this->curricula['mandatory_credits']?></center>
			</td>
			<td>
				<center><?php echo $this->curricula['elective_credits']?></center>
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<a href="#" id="close_mod_cur" class="btn btn-danger" data-dismiss="modal" style="float:right; margin-right:10px">Cerrar</a>
			</td>
		</tr>
	</table>
	<?php
}else{
	if ($this->form) { ?>
	<form role='form' method='post' action='/curricula/curricula/modifycurricula' id='form_mod_cur'>
	<?php echo $this->form->subid ?>
	<?php echo $this->form->escid_cur ?>

	<table class="table">
		<tr>
			<th><center>Codigo Generado</center></th>
			<th><center>Año</center></th>
			<th><center>Periodo</center></th>
			<th><center>Tipo Curricula</center></th>
			<th><center>Estado</center></th>
		</tr>
		<tr>
			<td style="width:100px">
				<?php echo $this->form->curid?>
			</td>
			<td>
				<?php echo $this->form->year?>
			</td>
			<td style="width:80px">
				<?php echo $this->form->cur_per_ant?>
			</td>
			<td>
				<?php echo $this->form->type?>
			</td>
			<td style="width:110px">
				<?php echo $this->form->state?>
			</td>
		</tr>
		<tr>
			<th colspan="3"><center>Nombre de Plan Curricular</center></th>
			<th colspan="2"><center>Alias de Plan Curricular</center></th>
		</tr>
		<tr>
			<td colspan="3">
				<?php echo $this->form->name?>
			</td>
			<td colspan="2">
				<?php echo $this->form->alias?>
			</td>
		</tr>
		<tr>
			<th><center>N° Periodos</center></th>
			<th><center>N° Cursos Obligatorios</center></th>
			<th><center>N° Cursos Electivos</center></th>
			<th><center>N° Créditos Obligatorios</center></th>
			<th><center>N° Créditos Electivos</center></th>
		</tr>
		<tr>
			<td>
				<?php echo $this->form->number_periods?>
			</td>
			<td>
				<?php echo $this->form->mandatory_course?>
			</td>
			<td>
				<?php echo $this->form->elective_course?>
			</td>
			<td>
				<?php echo $this->form->mandatory_credits?>
			</td>
			<td>
				<?php echo $this->form->elective_credits?>
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<a href="#" id="btn_modifyc_curr" class="btn btn-success" style="float:right">
					<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
			 	</a>
				<a href="#" id="close_mod_cur" class="btn btn-danger" data-dismiss="modal" style="float:right; margin-right:10px">Cancelar</a>
			</td>
		</tr>
	</table>
</form>
<div id="loaddatamod"></div>
<?php 
	} 
}?>

<script>
	var act="<?php echo $this->act?>";
	if (act==1) {
		window.location.reload();
		var escu="<?php echo $this->escid?>--<?php echo $this->subid?>";
		$("#curriculass").load("/curricula/curricula/curriculas/escid/"+$.base64.encode(escu));
	};

	$("#btn_modifyc_curr").click(function(){
		$("#form_mod_cur").submit();
	});

	$("#form_mod_cur").submit(function(){
		$.ajax({
           	type: 'POST',
	        url: $(this).attr('action'),
	        data: $(this).serialize(),
           	success: function(data) { 
        		$("#loaddatamod").html(data);
       			// $('#modifyc_curricula').modal('hide');
            }
        }); 
        return false;
    });
</script>