<?php 
	$dataView          = $this->dataView;
	$form              = $dataView['curriculumForm'];
	$curriculumsBefore = $dataView['curriculumsBefore'];
 ?>

<header class="modal_header">
	<p class="title">Nueva Currícula </p>
	<div>
		<p><span>Facultad de </span><?php echo $dataView['nameFac'] ?></p>
		<p><span>Escuela de </span><?php echo $dataView['nameEsc'] ?> 
			<?php if ($dataView['isEsp'] == 'yes'): ?>
				- <?php echo $dataView['nameEsp'] ?>
			<?php endif ?>
		</p>
	</div>
	<div>
		<a class="btn btn-default form-control" href="##" data-dismiss="modal">Cerrar</a>
	</div>
</header>
<section class="modal_body curriculum">
	<p><span class="glyphicon glyphicon-info-sign"></span> Llene todos los campos necesarios...</p>
	<form id="formCurriculum">
		<?php if ($dataView['isEsp'] == 'yes'): ?>
			<input type="hidden" name="id" value="<?php echo base64_encode($dataView['espid'].'|'.$dataView['subid']) ?>">
		<?php else: ?>
			<input type="hidden" name="id" value="<?php echo base64_encode($dataView['escid'].'|'.$dataView['subid']) ?>">
		<?php endif ?>

		<div class="inputs-type">
			<div>
				<?php echo $form->type_periods  ?>
			</div>
			<div>
				<?php echo $form->year  ?>
			</div>
			<div>
				<?php echo $form->type  ?>
			</div>
		</div>

		<div class="inputs-name">
			<div>
				<p>Nombre</p>
				<?php echo $form->name  ?>
			</div>
			<div>
				<p>Alias</p>
				<?php echo $form->alias  ?>
			</div>
		</div>
		<div class="inputs-amounts">
			<div>
				<p>N° Periódos</p>
				<?php echo $form->number_periods  ?>
			</div>
			<div>
				<p>N° Créditos Obligatorios</p>
				<?php echo $form->mandatory_credits  ?>
			</div>
			<div>
				<p>N° Créditos Electivos</p>
				<?php echo $form->elective_credits  ?>
			</div>
			<div>
				<p>N° Cursos Obligatorios</p>
				<?php echo $form->mandatory_course  ?>
			</div>
			<div>
				<p>N° Cursos Electivos</p>
				<?php echo $form->elective_course ?>
			</div>
		</div>

		<div class="input-curBefore">
			<div>
				<p>Curricula Anterior (para equivalencia)</p>
				<?php if ($curriculumsBefore): ?>
					<?php $form->cur_per_ant->addMultioption('', 'Elija una currícula') ?>
					<?php foreach ($curriculumsBefore as $curriculum): ?>
						<?php $form->cur_per_ant->addMultioption($curriculum['id'], $curriculum['name']) ?>
					<?php endforeach ?>
				<?php else: ?>
					<?php $form->cur_per_ant->addMultioption('', 'No existen curriculas anteriores...')
											->setAttrib('disabled', 'true')
											->setRequired(false) ?>
				<?php endif ?>
				<?php echo $form->cur_per_ant ?>
			</div>
		</div>

		<div class="sendButtom">
			<?php echo $form->save ?>
		</div>
	</form>
	<div class="msg_side">
		<div class="msg warning">
			<!-- <p><span class="glyphicon glyphicon-exclamation-sign"></span> Error en algunos campos...</p> -->
		</div>
		<div class="msg success">
			<p><span class="glyphicon glyphicon-ok"></span> Guardado satisfactoriamente!</p>
		</div>
	</div>
</section>
