<?php if ($this->form) { ?>
	<form role='form' method='post' action='/curricula/curricula/newcurricula' id='form_new_cur'>
	<?php echo $this->form->subid?>
	<?php echo $this->form->escid_cur?>

	<table class="table">
		<tr>
			<th colspan="6"><center>Código Generado</center></th>
		</tr>
		<tr>
			<td colspan="6">
				<center>
					<div style="width:100px"><?php echo $this->form->curid?></div>
				</center>
			</td>
		</tr>
		<tr>
			<th><center>Año</center></th>
			<th><center>Tipo Periodo</center></th>
			<th><center>Periodo</center></th>
			<th><center>Tipo Curricula</center></th>
			<th><center>Estado</center></th>
		</tr>
		<tr>
			<td style="width:100px">
				<?php echo $this->form->year?>
			</td>
			<td>
				<?php echo $this->form->type_periods?>
			</td>
			<td style="width:80px">
				<?php echo $this->form->cur_per_ant?>
			</td>
			<td>
				<?php echo $this->form->type?>
			</td>
			<td style="width:110px">
				<?php echo $this->form->state?>
			</td>
		</tr>
		<tr>
			<th colspan="3"><center>Nombre de Plan Curricular</center></th>
			<th colspan="2"><center>Alias de Plan Curricular</center></th>
		</tr>
		<tr>
			<td colspan="3">
				<?php echo $this->form->name?>
			</td>
			<td colspan="2">
				<?php echo $this->form->alias?>
			</td>
		</tr>
		<tr>
			<th><center>N° Periodos</center></th>
			<th><center>N° Cursos Obligatorios</center></th>
			<th><center>N° Cursos Electivos</center></th>
			<th><center>N° Créditos Obligatorios</center></th>
			<th><center>N° Créditos Electivos</center></th>
		</tr>
		<tr>
			<td>
				<?php echo $this->form->number_periods?>
			</td>
			<td>
				<?php echo $this->form->mandatory_course?>
			</td>
			<td>
				<?php echo $this->form->elective_course?>
			</td>
			<td>
				<?php echo $this->form->mandatory_credits?>
			</td>
			<td>
				<?php echo $this->form->elective_credits?>
			</td>
		</tr>
	</table>
	</form>
<?php }
?>
<div id="loadnewcurr"></div>

<script>
	var act="<?php echo $this->act?>";
	if (act==1) {
		window.location.reload();
		var escu="<?php echo $this->escid?>--<?php echo $this->subid?>";
		$("#curriculass").load("/curricula/curricula/curriculas/escid/"+$.base64.encode(escu));
	};

	var escid=$('#escid_cur').val();
	$("#year").change(function(){
		$("#year option:selected").each(function(){
			var type=$("#type_periods").val();
			var year=$(this).val();
			if (year!='')
				$('#curid').val(year+type+escid);
	            $("#cur_per_ant").val(year+type);

		});
	});

	$("#type_periods").change(function(){
		$("#type_periods option:selected").each(function(){
			var type=$(this).val();
			var year=$("#year").val();
			if (type!='')
				$('#curid').val(year+type+escid);
	            $("#cur_per_ant").val(year+type);

		});
	});

	$("#save_curri").click(function(){
			$("#form_new_cur").submit();
	});

	$("#form_new_cur").submit(function(){
			$.ajax({
            	type: 'POST',
	            url: $(this).attr('action'),
	            data: $(this).serialize(),
            	success: function(data) { 
					// $('#curr_new').modal('hide');
        			$("#loadnewcurr").html(data);
                }
	        }); 
	        return false;
    });
</script>