<?php 
	$dataView     = $this->dataView;
	$form         = $dataView['form_course'];
	$data_courses = $dataView['data_courses'];
 ?>

<header>
	<p><span class="glyphicon glyphicon-info-sign"></span> Complete los campos necesarios para agregar el curso...</p>
</header>
<section>
	<form id="form_add_new_course">
		<input type="hidden" name="id" value="<?php echo $dataView['id'] ?>">
		<div class="thre_input">
			<div>
				<?php echo $form->courseid ?>
			</div>
			<div>
				<?php echo $form->name ?>
			</div>
			<div>
				<?php echo $form->abbreviation ?>
			</div>
		</div>
		
		<div class="two_sides">
			<div class="side_one">
				<div class="two_inputs">
					<div>
						<p>Tipo de Curso</p>
						<?php echo $form->type ?>
					</div>
					<div>
						<p>Créditos</p>
						<?php echo $form->credits ?>
					</div>
				</div>

				<div class="two_inputs">
					<div class="two_inputs_min">
						<div>
							<p>Horas Teoricas</p>
							<?php echo $form->hours_theoretical ?>
						</div>
						<div>
							<p>Horas Practicas</p>
							<?php echo $form->hours_practical ?>
						</div>
					</div>
					<div>
						<?php if ($dataView['type'] == 'S'): ?>
							<p>Semestre</p>
						<?php elseif ($dataView['type'] == 'A'): ?>
							<p>Ciclo</p>
						<?php endif ?>

						<?php if ($dataView['periods']): ?>
							<?php for($c=1; $c<=$dataView['periods']; $c++): ?>
								<?php $form->semid->addMultiOption($c, $c) ?>
							<?php endfor ?>
						<?php else: ?>
							<?php $form->semid->addMultiOption('', 'Agregue una cantidad de periódos a esta curricula...') ?>
						<?php endif ?>
						<?php echo $form->semid ?>
					</div>
				</div>		
			</div>
			<div class="side_two">
				<header>
					<p>Prerequisitos</p>
				</header>
				<section class="select_pre">
					<select id="id_select_pre" class="form-control">
						<?php if ($dataView['periods']): ?>
							<option semester="0" value="">No hay prerequisitos para el primer semestre...</option>
							<?php foreach ($data_courses as $course): ?>
								<option semester="<?php echo $course['semid'] ?>" code-course="<?php print $course['courseid'] ?>" value="<?php echo base64_encode($course['courseid']) ?>" hidden><?php echo $course['courseid'].' | '.$course['name'] ?></option>
							<?php endforeach ?>
						<?php else: ?>
							<option value="">Elija un semestre...</option>
						<?php endif ?>
					</select>
					<a href="##"><span class="glyphicon glyphicon-plus"></span></a>
				</section>
				<section class="prerequisites">
					<!-- <article>
						<p>Curso 1</p>
						<input type="hidden" name="pre_1" value="">
						<a href="##"><span class="glyphicon glyphicon-remove"></span></a>
					</article> -->
					<p><span class="glyphicon glyphicon-exclamation-sign"></span> Agregue requisitos para este curso si desea...</p>
					<input type="hidden" name="pre_1" value="">
					<input type="hidden" name="pre_2" value="">
					<input type="hidden" name="pre_3" value="">
				</section>
			</div>
		</div>

		<div class="submit_side">
			<input type="submit" class="btn btn-success form-control" value="Agregar Curso">
		</div>
	</form>
	<div class="msg_side">
		<div class="msg success">
			<p><span class="glyphicon glyphicon-exclamation-sign"></span> Curso guardado satisfactoriamente!</p>
		</div>
		<div class="msg warning">
			<!-- Errores aqui desde JavaScript -->
		</div>
	</div>
</section>