<?php
if ($this->escuelas) { ?>
	<option value="">- Seleccione -</option>
	<?php
	foreach ($this->escuelas as $escuelas) { 
		$selected=($this->escid==$escuelas['escid'])? "selected":"";?>
		<option value="<?php echo $escuelas['escid'].'--'.$escuelas['subid']?>" <?php echo $selected?>><?php echo $escuelas['name']?></option>
	<?php
	}
}else{ ?>
	<option value="">No hay Ninguna Escuela.</option>
<?php
}?>