<table class="table span10">
	
	<?php if ($this->packdatat){?>
	    <tr>
	        <th><center>Num</center></th>
	        <th><center>Codigo</center></th>
	        <th >Docente</th>
	        <th ><center>Imprimir</center></th>	        
	    </tr>
	<?php $c=0; 
		foreach ($this->packdatat as $pdt) {?>
			<tr>
				<td><center><?php echo $c+1 ?></center></td>
				<td><center><?php echo $pdt['uid'] ?></center></td>
				<td><center><?php echo $pdt['pid'] ?></center></td>
				<td><center><?php echo $pdt['escid'] ?></center></td>
				<td><?php echo $pdt['nombrecompleto'] ?></td>
	
				<td><center><a href="listacademicreport/print/pid/<?php echo base64_encode($pdt['pid'])?>/uid/<?php echo base64_encode($pdt['uid'])?>/escid/<?php echo base64_encode($pdt['escid'])?>/subid/<?php echo base64_encode($pdt['subid'])?>/perid/<?php echo base64_encode($this->perid)?>/nombre/<?php echo base64_encode($pdt['nombrecompleto'])?>"><span class="glyphicon glyphicon-print"></span></a></center></td>
			</tr>
		<?php $c++;
		}
	}else{?>
		<center>No Existen Datos</center>
	<?php } ?>
</table>