<table class="table span10">
	<?php if ($this->packdatat){?>
	    <tr>
	        <th><center>Num</center></th>
	        <th><center>Codigo</center></th>
	        <th ><center>Docente</center></th>
	    </tr>
	<?php $c=0; 
	foreach ($this->packdatat as $pdt) {?>
		<tr>
			<td><center><?php echo $c+1 ?></center></td>
			<td><center><?php echo $this->packdatat[$c][0]['uid']?></center></td>
			<td><center><?php echo $this->packdatat[$c][0]['last_name0']." ".$this->packdatat[$c][0]['last_name1']." ".$this->packdatat[$c][0]['first_name'];?></center></td>
		</tr>
	<?php $c++;
	}?>    
	<?php } ?>
</table>