
<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$perid=$this->perid;

?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align:center;" ><b>INFORME DOCENTES - PERIODO <?php echo $perid ?></b></div>
<table style="width:100%; margin-top:3%" border="1px">

	<?php if ($this->packdatat){?>
	    <tr>
	        <th><center>#</center></th>
	        <th><center>Codigo</center></th>
	        <th >Docente</th>
	        <th >Estado</th>
        
	    </tr>
	<?php $c=0; 
		foreach ($this->packdatat as $pdt) {?>
			<tr>
				<td><center><?php echo $c+1 ?></center></td>
				<td><center><?php echo $pdt['uid'] ?></center></td>			

				<?php 
				$pk=array('uid'=>$pdt['uid'],'pid'=>$pdt['pid'],'escid'=>$pdt['escid'],'subid'=>$pdt['subid'],'eid'=>$this->eid,'oid'=>$this->oid,'perid'=>$this->perid);
		      	$dbteachers= new Api_Model_DbTable_Addreportacadadm();        
				$teacher=$dbteachers->_getOne($pk);
				//print_r($teacher);
				$stinfo=$teacher['state'];

				?>
				<td><?php echo $pdt['nombrecompleto'] ?></td>
				<td><?php 
					if($stinfo=='C')
					{
						?>
						<center><span class="glyphicon glyphicon-ok">SI</span></center>				
						<?php 
					}
					else
					{
						?>
						<center><span class="glyphicon glyphicon-remove">NO</span></center>	
						<?php	
					}
				 ?></td>
			</tr>
		<?php $c++;
		}
	}else{?>
		<center>No Existen Datos</center>
	<?php } ?>
</table>
<?php 
	$html = ob_get_contents();
	$mpdf=new mPDF('win-1252','A4','','',15,15,40,18,5,5);
	$mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');
	ob_end_clean();
	$mpdf -> WriteHTML($html);
	$mpdf->Output('Reporte - '.$perid.'.pdf','D');
	// $mpdf->Output();
 
?>