<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$speciality = $this->info_speciality;
if ($speciality['parent']!= '') {
	$name_esc = $speciality['speciality'];
	$name_speciality='ESPECIALIDAD'.$speciality['name'];
}
else{
	$name_esc=$speciality['name'];
}
$perid=$this->perid;

$header='
<table width="100%" style="border: 1px solid #000;font-family: serif;  color: #000; ">
	<tr style="text-align:center; padding-left: 100px; ">
    	<td  rowspan="2" width="340px" style="border: 1px solid #000 "><img src="/img/header_imprimir.jpg">
    	</td>
    	<td style="text-align:center; font-size:10px; border: 1px solid #000 ">
    		FACULTAD '.strtoupper($this->faculty).'<br/>
    		ESCUELA '.strtoupper($name_esc).'<br/>
            '.strtoupper($name_speciality).'<br/>   		
    		
    	</td>   
	</tr>
	<tr>
		<td style="text-align:center; font-size:10px; border: 1px solid #000 " >INFORME DOCENTES - PERIODO '.$perid.' </td>
	</tr>
</table>'
?>
<table style="width:100%; font-size: 9px;" border="1">

	<?php if ($this->packdatat){?>
	    <tr>
	        <th><center>Num</center></th>
	        <th><center>Codigo</center></th>
	        <th >Docente</th>
	        <th >Estado</th>
        
	    </tr>
	<?php $c=0; 
		foreach ($this->packdatat as $pdt) {?>
			<tr>
				<td><center><?php echo $c+1 ?></center></td>
				<td><center><?php echo $pdt['uid'] ?></center></td>			

				<?php 
				$pk=array('uid'=>$pdt['uid'],'pid'=>$pdt['pid'],'escid'=>$pdt['escid'],'subid'=>$pdt['subid'],'eid'=>$this->eid,'oid'=>$this->oid,'perid'=>$this->perid);
		      	$dbteachers= new Api_Model_DbTable_Addreportacadadm();        
				$teacher=$dbteachers->_getOne($pk);
				//print_r($teacher);
				$stinfo=$teacher['state'];

				?>
				<td><?php echo $pdt['nombrecompleto'] ?></td>
				<td><?php 
					if($stinfo=='C')
					{
						?>
						<center><span class="glyphicon glyphicon-ok">SI</span></center>				
						<?php 
					}
					else
					{
						?>
						<center><span class="glyphicon glyphicon-remove">NO</span></center>	
						<?php	
					}
				 ?></td>
			</tr>
		<?php $c++;
		}
	}else{?>
		<center>No Existen Datos</center>
	<?php } ?>
</table>
<?php 
$html = ob_get_contents();
$mpdf=new mPDF('win-1252','A4-L','','',10,10,44);
$mpdf->SetHTMLHeader($header);
$mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
$mpdf->SetFooter($this->footer);
ob_end_clean();
$mpdf -> WriteHTML($html);
$mpdf->Output('Reporte-'.$course['name'].'-'.$this->turno.'.pdf','D');
 
?>