<?php //print_r($this->cursos);
$numcurso=count($this->cursos);

//print_r($this->preguntas);
?>

<body>
<div class="container">
<div id="contenedor-encuesta" style='' >
    <div class="alert alert-info">
        <p style="font-size: 14px;font-weight: bold"><?php echo $this->encuesta['title']?></p>
        <p><?php echo "Objetivo: ".$this->encuesta['objective']?><b style="color: red">
        LA ENCUESTA ES PERSONAL Y ANONIMA</b></p>
        <div style="clear:both"></div>
    </div>
    
        <form class="form-vertical" name="formEncuesta" action="/alumno/index/guardar/" method="post">
            <table class="table table-hover table-bordered table-condensed span10" style="margin-left: 80px;padding: 0px">            
                <thead>
                    <tr>
                        <th colspan="2">Preguntas</th>
                        <?php
                        foreach ($this->cursos as $curso){
                            print("<th>".$curso['name']."</th>");
                        }                        
                        ?>
                 
            </tr>
                </thead>
                <tbody>
                <?php 
                //print_r($this->preguntas);
                $ff_=0;
                foreach ($this->preguntas as $pregunta){
                    $ff_++;
                    ?>
                    <tr>
                        <td><?php echo $ff_?></td>
                        <td><?php echo $pregunta['question'];?></td>                        
                        <?php                         
                        $eid = $pregunta['eid'];
                        $oid = $pregunta['oid'];
                        $qid = $pregunta['qid'];

                        $alternativas = new Api_Model_DbTable_PollAlternatives();
                        foreach ($this->cursos as $curso){
                        
                       
            			$where=array('eid'=>$eid,'oid'=>$oid,'qid'=>$qid);

                        $regalternativas = $alternativas->_getAll($where);
                        //print_r($regalternativas);

                        $f++;
                        ?>
            	
                        <td>
                            <div class="control-group">             
                                <div class="controls">
                                    <?php 
                                    $g=0;
                                    foreach ($regalternativas as $alternativa){
                                        $ff = ($g=='0')?"":"";
                                    ?>
                                        <label class="radio"> <input <?php echo $ff; ?> type="radio" name="registro_<?php echo $f?>" value="<?php echo $pregunta['qid']."-".$alternativa['altid'].";--;curid:".$curso['curid']."-courseid:".$curso['cursoid']."-turno:".$curso['turno'];?>" ><?php echo $alternativa['alternative']?></label>
                                    <?php 
                                    $g++;
                                    } 
                                    ?>
                                </div>
                            </div>
                        </td>
                        <?php
                        }
                        ?>
                    </tr>  
                    <?php 
                }
                ?>
                </tbody>    
            </table>
            <div class="enviarencuesta span9">
                <input type="submit" value="REGISTRAR ENCUESTA" class="btn btn-primary" id="enviarencuesta">
                <a href="/index/salir/" class="btn btn-danger">SALIR SISTEMA</a>
            </div>
        </form>
    <div style="clear:both"></div>
    
</div>
</div>
</body>