 <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">
      function drawVisualization() {
        var data = google.visualization.arrayToDataTable([
          ['ENCUESTA', 'FALTAS', 'ASISTIO', 'TOTAL'],
           <?php  foreach ($this->assistence as $datos) {
           $course=$datos['name'];
           $falto=$datos['falto'];
           $asistio=$datos['asistio'];
          
          ?>
           ['<?php print $course?>' , <?php print $falto?> ,<?php print $asistio?> ,17,
         <?php  }?>
 
        ]);

        var options = {
          title : 'ASISTENCIA',
          vAxis: {title: "CANTIDAD CLASES"},
          hAxis: {title: "CURSOS"},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
      google.setOnLoadCallback(drawVisualization);
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 95%; height: 100%;"></div>
  </body>

 
