        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        <link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<div class="alert alert-success"><center>"SE CONSIDERA EL 30 % DE FALTA COMO RETIRADO A CADA CURSO CORRESPONDIENTE EN EL PRESENTE PERIODO"</center></div> 
 <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">
      function drawVisualization() {
        var data = google.visualization.arrayToDataTable([
          ['ASISTENCIA', 'TARDE','ASISTIO', 'FALTAS', 'TOTAL CLASES','RETIRADO','30% INASISTENCIA'],
           <?php  foreach ($this->assistence as $datos) {
           $course=$datos['name'];
           $retirado=$datos['coment'];
           if ($retirado=='R') {
            $ret=17;
            $tarde=0;
            $asistio=0;
            $falto=0;
            $total=0;
            $ret=17;
           };
           if ($retirado=='N') {
            $ret=0;
            $tarde=$datos['tarde'];
            $asistio=$datos['asistio'];
            $falto=$datos['falto'];
            $total=17;
            $ret=0;
           };   ?>
           ['<?php print $course?>' , <?php print $tarde?>,<?php print $asistio?> , <?php print $falto?> , <?php print $total?> ,<?php print $ret?>, <?php print $ret?>],
         <?php  }?>
        ]);
          var options = {
          title: 'ASISTENCIA',
          titleTextStyle: {color: '#0567B1'},
          hAxis: {title: ' CURSOS',  titleTextStyle: {color: '#FA1707'}},
          vAxis: {title: "CLASES",  titleTextStyle: {color: '#FA1707'}},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };
        var chart = new google.visualization.ComboChart(document.getElementById('chart_div1'));
        chart.draw(data, options);
      }
      google.setOnLoadCallback(drawVisualization);
    </script>
  </head>
  <body>
    <div id="chart_div1" style="width: 100%; height: 90%;"></div>
  </body>