        <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/jquery/external/base64/jquery.base64.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">      
        <link rel="stylesheet" type="text/css" href="/external/jwysiwyg/jquery.wysiwyg.css">
        <script type="text/javascript" src="/external/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.image.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.link.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.table.js"></script>
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        <link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<div class="alert alert-success"><center>"PARA LOGRAR UN RENDIMIENTO AL 100% DEBEN COINCIDIR LA CANTIDAD DE CURSOS POR SEMESTRE Y LA CANTIDAD DE CURSOS APROBADOS"</center></div> 
    <center><table class="table  table-bordered table-striped table-condensed" style="float:left; margin-left:200px;font-size:11px; width:800px">
      <tr>
         <th style='color:'>Semestres</th>
            <?php $cont=1;  
            while ( $cont<= 12) {
            foreach ($this->data as $datos) {           
             $nombre=$datos['semid']; 
              if ($nombre==$cont){
             $total=$datos['cantidad_cursos']; 
                          $a=0;                     
                          foreach ($this->cursos as $datos1) {                         
                              if($datos1['semid']==$cont){
                              $cant=$datos1['cantidad_cursos'];
                              $a = $a+1;  
                              }                            
                          }
                           if($a==0)
                          {
                            $cant=0;
                          }                    
                    ?>  


             <td><center><span class="label label-info" id="mostrartexto" rel="popover" data-placement="bottom" style="float:left;font-size:11px;">
        <?php print $nombre?> </span></center></td>        
           <?php  }}
           $cont=$cont +1; }?>
           </tr>
           <tr>
         <th>Cant.Cursos Pendientes</th>
         <?php $cont=1;  
            while ( $cont<= 12) {
            foreach ($this->data as $datos) {           
             $nombre=$datos['semid']; 
              if ($nombre==$cont){
             $total=$datos['cantidad_cursos']; 
                          $a=0;                     
                          foreach ($this->cursos as $datos1) {                         
                              if($datos1['semid']==$cont){
                              $cant=$datos1['cantidad_cursos'];
                              $a = $a+1;  
                              }                            
                          }
                           if($a==0)
                          {
                            $cant=0;
                          }                    
                    ?>
         <td><font color="red"><b><?php print ($total-$cant)?></b></font></td>
         <?php  }}
           $cont=$cont +1; }?>
        </tr> 
      </table></center>
      <br>
      <br>
      <br>
      <br>
  <html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['SEMESTRE', 'CANTIDAD DE CURSOS POR SEMESTRE', 'CANTIDAD CURSOS APROBADOS'],
         <?php $cont=1;  
          while ( $cont<= 12) {
          foreach ($this->data as $datos) {           
           $nombre=$datos['semid'];
            if ($nombre==$cont){
           $total=$datos['cantidad_cursos']; 
                        $a=0;                     
                        foreach ($this->cursos as $datos1) {                         
                            if($datos1['semid']==$cont){
                            $cant=$datos1['cantidad_cursos'];
                            $a = $a+1;  
                            }                            
                        }
                         if($a==0)
                        {
                          $cant=0;
                        }                    
                  ?>
           ['<?php print $nombre."º"?>' ,<?php print $total?> ,<?php print $cant?>],
         <?php  }}
         $cont=$cont +1; }?>
        ]);
        var options = {
          title: 'GRAFICA DE RENDIMIENTO ACADEMICO HASTA LA ACTUALIDAD',
          hAxis: {title: 'SEMESTRES',  titleTextStyle: {color: 'red'}},
          vAxis: {title: "CANTIDAD DE CURSOS",  titleTextStyle: {color: 'red'}}
        };
        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>   
  </head>
  <body>
    <div id="chart_div" style="width: 100%; height: 85%;"></div>
  </body>
</html>

