<!--<div class="row">
	<div class="col-md-5 col-md-offset-1">
		<img src="/img/dash_1.jpg" class="img-responsive" alt="Imagen 1" id="img_1">
		
	</div>
	<div class="col-md-5" id="img_1_Info">
		<div class="panel panel-info">
			<div class="row">
				<div class="col-md-1">
					<h3><span class="glyphicon glyphicon-bullhorn text-primary"></span></h3>
				</div>
				<div class="col-md-11">
				<blockquote>
					<h3 class="text-muted">Ya Inicio el Proceso Matricula</h3>
				</blockquote>
				</div>
			</div>
			<hr clas="featurette-divider">
			
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, ducimus, doloremque, deleniti amet magnam quas illo error dolorum voluptatibus maiores hic autem delectus quibusdam adipisci modi! Ad, deleniti repellendus quam.</p>
			
		</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-5 col-md-offset-1" id="img_2_Info">
		<div class="panel panel-info">
			<div class="row">
				<div class="col-md-1">
					<h3><span class="glyphicon glyphicon-bullhorn text-primary"></span></h3>
				</div>
				<div class="col-md-11">
				<blockquote>
					<h3 class="text-muted">Saca ya tu Carnet de Biblioteca</h3>
				</blockquote>
				</div>
			</div>
			<hr clas="featurette-divider">
			
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, ducimus, doloremque, deleniti amet magnam quas illo error dolorum voluptatibus maiores hic autem delectus quibusdam adipisci modi! Ad, deleniti repellendus quam.</p>
			
		</div>
	</div>
	<div class="col-md-5">
		<img src="/img/dash_2.jpg" class="img-responsive" alt="Imagen 1" id="img_2">
	</div>
</div>
	


<script>
	$('#img_1_Info').fadeTo('fast', '0');
	
	$('#img_2_Info').fadeTo('fast', '0');

	$('#img_1').mouseenter(function(){
		$('#img_1_Info').fadeTo('fast', '1');
		$('#img_1').mouseleave(function(){
			$('#img_1_Info').fadeTo('fast', '0');
		});
	});

	$('#img_2').mouseenter(function(){
		$('#img_2_Info').fadeTo('fast', '1');
		$('#img_2').mouseleave(function(){
			('#img_2_Info').fadeTo('fast', '0');
		});
	});
</script>-->





<div class="row">
	<div class="col-md-4 col-md-push-1 boxbody sombras">
		<h5 class="titlebox">
			<span class="glyphicon glyphicon-th-list"></span> - OFERTAS LABORALES
			<a href="http://laboral.undac.edu.pe/" TARGET="_blank" rel="tooltip" title="Ver Detalle de Ofertas Laborales" style="float:right;color:white"><span class="glyphicon glyphicon-comment"></span></a>
		</h5>
		<div id="laboral" class="boxcontent"></div>
	</div>

	<div class="col-md-4 col-md-push-3 boxbody sombras">
		<h5 class="titlebox">
			<span class="glyphicon glyphicon-user"></span> - ULTIMOS ACCESOS
			<a href="/default/logaccess/detalleaccess" TARGET="_blank" rel="tooltip" title="Ver Detalle de Accesos al Sistema" style="float:right;color:white"><span class="glyphicon glyphicon-comment"></span></a>
		</h5>
		<div id="access" class="boxcontent"></div>
	</div>

		<div class="col-md-10 col-md-offset-1 boxbody sombras">
		<h5 class="titlebox">
			<span class="glyphicon glyphicon-random"></span> - GRAFICA ASISTENCIA ACADEMICA
			<a href="#" style="float:right; color:white"><span class="glyphicon glyphicon-comment"></span></a>
		</h5>
		<div class="boxcontent">
            <iframe width="99.5%" height="97.3%" src="alumno/index/graphicsassistance"></iframe>
        </div><br>
	</div>

	<div class="col-md-10 col-md-offset-1 boxbody sombras">
		<h5 class="titlebox">
			<span class="glyphicon glyphicon-random"></span> - GRAFICA RENDIMIENTO ACADEMICO
			<a href="#" style="float:right; color:white"><span class="glyphicon glyphicon-comment"></span></a>
		</h5>
		<div class="boxcontent">
            <iframe width="99.5%" height="97.3%" src="alumno/index/graphicsperformance"></iframe>
        </div><br>
	</div>
</div>
<script type="text/javascript">
	var pid = "<?php echo $this->pid?>";
	$("#access").html("<center><img src='/img/carga.gif' width='340'></center>");
	$("#access").load("/logaccess/index");
	$("#laboral").html("<center><img src='/img/carga.gif' width='340'></center>");
	$("#laboral").load("/rss/laboral/");

	$('a[rel=tooltip]').tooltip();
</script>
