<?php
if ($this->datalog) { ?>
	<div class="panel panel-default">
		<h4><center><b>DETALLE ACCESOS AL SISTEMA</b></center></h4>
	</div>
	<table class="table table-hover table-striped">
		<tr>
			<th style='width: 20px' class="center">#</th>
			<th class=" center">Lugar</th>
			<th class=" center">Navegador</th>
			<th class="center">Ingreso</th>
			<th class="center">Salida</th>
			<th style='width: 20px'  class=" center">Est.</th>
		</tr>
		<?php
		$c=1;
		$datalog=$this->datalog;
		for ($i=0; $i < 50; $i++) { 
			$f_ini = $datalog[$i]['datestart'];
			$f_fin = $datalog[$i]['dateend'];
			if ($datalog[$i]['state']=="A") $img="<img src='/img/circulo-verde.png' width='20' rel='tooltip' title='Sesión Activa'>";
			else $img="<img src='/img/circulo-rojo.png' width='20' rel='tooltip' title='Sesión Cerrada'>";?>
			<tr>
				
				<td><?php echo $c?></td>
				<td><?php echo $datalog[$i]['ip']?></td>
				<td><?php echo $datalog[$i]['browserinfo']?></td>
				<td><?php echo $f_ini?></td>
				<td><?php echo $f_fin?></td>
				<td><?php echo $img?></td>
			</tr>
			<?php
			$c++;
		}?>
	</table>
	<?php
}?>

<script type="text/javascript">
$('img[rel=tooltip]').tooltip();
</script>