<?php
if ($this->datalog) { ?>
	<table class="table table-hover" style="font-size: 10px">
		<tr>
			<th style='width: 20px' class="center">#</th>
			<th class="small center">Lugar</th>
			<th class="small center">Ingreso</th>
			<th class="small center">Salida</th>
			<th style='width: 20px'  class=" center">Est.</th>
		</tr>
		<?php
		$c=1;
		$datalog=$this->datalog;
		for ($i=0; $i < 10; $i++) { 
			//$f_ini = split('[-./]', substr($datalog[$i]['datestart'], 0,10));
			$f_ini = $datalog[$i]['datestart'];
			$f_fin = $datalog[$i]['dateend'];
			//$f_fin = split('[-./]', substr($datalog[$i]['dateend'], 0,10));
			if ($datalog[$i]['state']=="A") $img="<img src='/img/circulo-verde.png' width='20' rel='tooltip' title='Sesión Activa'>";
			else $img="<img src='/img/circulo-rojo.png' width='20' rel='tooltip' title='Sesión Cerrada'>";?>
			<tr>
				<td class="center"><?php echo $c?></td>
				<td class="center"><?php echo $datalog[$i]['ip']?></td>
				<td class="center"><?php echo $f_ini?></td>
				<td class="center"><?php echo $f_fin?></td>
				<td class="center"><?php echo $img?></td>
			</tr>
			<?php
			$c++;
		}?>
	</table>
	<?php
}?>

<script type="text/javascript">
$('img[rel=tooltip]').tooltip();
</script>