<script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
<form name="<?php echo $this->fm->getName(); ?>" action="/register/changerates/asignationrate/" method="post" enctype="application/x-www-form-urlencoded">
                <br>
                <table class="table span9 table-striped table-bordered table-condensed">
                    <tbody >
                        <tr>                      
                            <td>   
                                <div class="control-group">
                                    <center><label class="control-label">Seleccione la Tasa :</label></center>
                                    <center><div style='width: 400px'><?php echo $this->fm->ratid?></center></div>
                                </div>
                            </td>
                        </tr> 
                        <tr>       
                            <td>
                                <div class="control-group">
                                    <div><center><label class="control-label">Documento de Autorizacion:</label></center></div>
                                    <div ><center><div style='width: 300px'><?php echo $this->fm->document_auth;?></center></div>
                                </div>
                            </td>
                        </tr>    
                        <tr>
                            <td><center><?php echo $this->fm->guardar?></center></td>
                          
                        </tr>
                        <input type="hidden" name='eid' value='<?php echo $this->eid?>'>
                        <input type="hidden" name='oid' value='<?php echo $this->oid?>'>
                        <input type="hidden" name='uid' value='<?php echo $this->uid?>'>
                        <input type="hidden" name='pid' value='<?php echo $this->pid?>'>
                        <input type="hidden" name='escid' value='<?php echo $this->escid?>'>
                        <input type="hidden" name='subid' value='<?php echo $this->subid?>'>
                        <input type="hidden" name='perid' value='<?php echo $this->perid?>'>
                    </tbody>
                </table>
            <div style="clear:both"></div>
    </form>