<!-- <script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css"> -->
    <form name="frmchangerate" id='frmchangerate' action="/register/changerates/asignationrate/" method="post" enctype="application/x-www-form-urlencoded">
        <div class="row">       
            <div class="col-md-12">
                <div class="col-md-4"><label>Seleccione la Tasa: </label></div>
                <div class="col-md-8"><?php echo $this->fm->ratid?></div>
            </div>         
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4"><label>Documento de Autorización: </label></div>
                <div class="col-md-8"><?php echo $this->fm->document_auth?></div>
            </div>
        </div>
        <input type="hidden" name='eid' value='<?php echo $this->eid?>'>
        <input type="hidden" name='oid' value='<?php echo $this->oid?>'>
        <input type="hidden" name='uid' value='<?php echo $this->uid?>'>
        <input type="hidden" name='pid' value='<?php echo $this->pid?>'>
        <input type="hidden" name='escid' value='<?php echo $this->escid?>'>
        <input type="hidden" name='subid' value='<?php echo $this->subid?>'>
        <input type="hidden" name='perid' value='<?php echo $this->perid?>'>
    </form>
    <div class="modal-footer">
        <button id="saveasignation" type="button" class="btn btn-success"><span class="glyphicon glyphicon-save"></span>Guardar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
    </div>
<script type="text/javascript">
    $("#saveasignation").click(function(){
        var url="/register/changerates/asignationrate/";
        $.ajax({
            url:url,
            type:'POST',
            data:$("#frmchangerate").serialize(),
            success:function (data){
                $("#change").html(data);
            }
        });        
    });

    var clave="<?php echo $this->clave?>";

    if (clave=="1") {
        $('#Modal').modal('hide');
        $('#Modal').on('hidden.bs.modal', function (e) {
            var uid="<?php echo $this->uidc?>";
            var url1="/register/changerates/getuser/uid/"+uid;
            $('#cargadata').html("<center><img src='/img/spinner.gif'> Cargando....</center>");
            $("#cargadata").load(url1);      
        });
    };
</script>    