<!-- <script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css"> -->
    <form name="frmchangerate" id="frmchangerate" action="/register/changerates/changerate/" method="post" enctype="application/x-www-form-urlencoded">
        <table class="table table-striped table-bordered table-condensed">
            <tbody>
                <tr>                      
                    <td colspan="2">   
                        <div class="control-group">
                        <div><label class="control-label">Tasa para Asignar:</label>
                        </div><div style='width: 500px'><?php echo $this->fm->ratid?></div>
                        </div>
                    </td>
                </tr> 
                <tr>       
                    <td>
                        <div class="control-group">
                            <div><label class="control-label">Documento de Autorización:</label></div>
                            <div ><?php echo $this->fm->document_auth;?></div>
                        </div>
                    </td>
                    <td>                           
                        <div class="control-group">
                            <div><label class="control-label">Fecha de Pago:</label></div>
                            <div><?php echo $this->fm->date_payment;?></div>
                        </div>
                    </td> 
                </tr>    
                <!-- <tr>
                    <td colspan="2"><center><?php echo $this->fm->guardar?></center></td>
                  
                </tr> -->
                <input type="hidden" name='eid' value='<?php echo $this->eid?>'>
                <input type="hidden" name='oid' value='<?php echo $this->oid?>'>
                <input type="hidden" name='uid' value='<?php echo $this->uid?>'>
                <input type="hidden" name='pid' value='<?php echo $this->pid?>'>
                <input type="hidden" name='escid' value='<?php echo $this->escid?>'>
                <input type="hidden" name='subid' value='<?php echo $this->subid?>'>
                <input type="hidden" name='perid' value='<?php echo $this->perid?>'>
            </tbody>
        </table>
    </form>
    <div class="modal-footer">
        <button id="savechangerate" type="button" class="btn btn-success"><span class="glyphicon glyphicon-save"></span>Guardar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
    </div>

<script type="text/javascript">
    $("#savechangerate").click(function(){
        var url="/register/changerates/changerate/";
        $.ajax({
            url:url,
            type:'POST',
            data:$("#frmchangerate").serialize(),
            success:function (data){
                $("#list").html(data);
            }
        });        
    });

    var clave="<?php echo $this->clave?>";

    if (clave=="1") {
        $('#myModal').modal('hide');
        $('#myModal').on('hidden.bs.modal', function (e) {
            var uid="<?php echo $this->uidc?>";
            var url1="/register/changerates/getuser/uid/"+uid;
            $('#cargadata').html("<center><img src='/img/spinner.gif'> Cargando....</center>");
            $("#cargadata").load(url1);      
        });
    };
</script>


