<div id="data">
    <table class="table span9 table-bordered">
        <thead>
        <tr>
                <th >#</th>
                <th >Código</th>
                <th >Apellidos y Nombres</th>
                <th >Escuela</th>
                <th >Tasa Actual</th>
                <th >Fecha de Pago</th>
                <th >Monto  S/.</th>
                <th >Doc. Reg. Autorización</th>
                <th >Operación</th>
        </tr>
        </thead>

    <?php
    if ($this->data)
    {
        $c=0;
        $a=0;
       foreach ($this->data as $info)    
        {
            $c++;      
            ?>
            <tr>
                <td><?php echo $c?></td>
                <td><?php echo $info['uid'];?></td>
                <td><?php echo $info['last_name0']." ".$info['last_name1'].", ".$info['first_name'];?></td>
                <td><?php echo $this->rfacaulm['name']?></td>
                <td><?php echo $this->dblist['name']?></td>
                <td><?php echo $this->dlist[$a]['date_payment']?></td>
                <td><?php echo $this->dlist[$a]['amount']?></td>
                <td><?php echo $this->dlist[$a]['document_auth']?></td>
                <td>
                    <center><a href="#" onclick="javascript: window.open('/register/changerates/changerate/','changerate','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=600,height=400')" ><span class="glyphicon glyphicon-pencil"></span></a></center></td>
                    
            </tr>
          <?php 
            
        }    
    }
    ?>
    </table>
        <div style="clear:both"></div>  
</div>