<div id="data">
    <table class="table span9 table-bordered">
        <thead>
        <tr>
                <th >#</th>
                <th >Código</th>
                <th >Apellidos y Nombres</th>
                <th >Escuela</th>
                <th >Tasa Actual</th>
                <th >Fecha de Pago</th>
                <th >Monto  S/.</th>
                <th >Doc. Reg. Autorización</th>
                <th >Operación</th>
        </tr>
        </thead>

    <?php
    if ($this->data)
    {
        $c=0;
       foreach ($this->data as $info)    
        {
            $c++;
            $data=null;
            $facid=$this->facid;
            $facaulm = new Api_Model_DbTable_Speciality();
            $data['eid'] = $info['eid'];
            $data['oid'] = $info['oid'];
            $data['escid'] = $info['escid'];
            $data['subid'] = $info['subid'];
            $rfacaulm = $facaulm->_getOne($data);
            // print_r($rfacaulm);            
            ?>
            <tr>
                <td><?php echo $c?></td>
                <td><?php echo $info['uid'];?></td>
                <td><?php echo $info['last_name0']." ".$info['last_name1'].", ".$info['first_name'];?></td>
                <td><?php echo $rfacaulm['name']?></td>
                <td><?php echo $info['uid'];?></td>
                <td>
                    <?php 
                    if ($facid==$vfacalum || $facid=="TODO"){
                        ?>
                    <center><a href="/report/recordnotas/print/uid/<?php echo base64_encode($info['uid'])?>/escid/<?php echo base64_encode($info['escid'])?>"><img src="/img/pdf.png"></a></center></td>
                    <?php 
                    }
                    ?>
                    
            </tr>
          <?php 
            
        }    
    }
    ?>
    </table>
        <div style="clear:both"></div>  
</div>
