<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-transfer"></span> Cambio de Tasas - Periodo');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/ " class="form-control btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>
<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltro" action="/register/changerates/getuser/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default" style='padding:20px;'>
                <br>
                    <p class="text-muted"><span class="glyphicon glyphicon-user"></span> Código del Alumno</p>
                    <?php echo $this->fm->uid ?>
                <br>
            </div>
        </div>
        <!--<div class="col-md-6 col-md-offset-3">
        </div>-->
    </div>
</form>
<div id="cargadata"></div>

<script>
    $("#uid").keypress(function (e) {
    	    var codi =  $(this).val();
    	    // alert(codi);
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#uid').val();
            // var nom =  $('#last_name0').val();
            count=codi.length;
            if (count==10 || count==0)
            {
                $('#cargadata').html("<img src='/img/spinner.gif'> Cargando....");
                $("#frmFiltro").submit();
            }
            else
            {
                alert("Ingrese un codigo valido");
                $('#uid').val('');
            }
        }
    });
    
    $("#frmFiltro").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#cargadata').html(data);                                 
            }
        }); 
        return false;
    });

function validNumber(e) {
    var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
    }    
</script>