<link rel="stylesheet" href="/css/tutorship.css">

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Tutoria');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/docente/" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>


<div class="cuerpo">
	<p><span class="glyphicon glyphicon-info-sign"></span> Asigne a los tutores por semestre</p>
	<a href="##" id="btnDocentesAsignados" class="btn btn-success btnDocentesRegistrados">Docentes Asignados</a>
</div>

<div id="docentesData" class="docentes">

</div>

<script>
	$('#docentesData').html('<br><center><img src="/img/spinner.gif" alt="Loading.." /></center><br>');
	$('#docentesData').load('/acreditacion/tutorship/listteachers/');
</script>