<?php
if ($this->sendDataTutoring) {
	$dataTeacher=$this->sendDataTutoring;
	?>
	<div class="modal-header">
    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    	<h4 class="modal-title" id="myModalLabel"><center><span class='glyphicon glyphicon-briefcase text-info'></span><b class='text-primary'> INFORME DE TUTORÍA</b></center></h4><br>
		<div style='font-size:15px'><b>DNI: </b><?php echo $this->pid?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Docente: </b><?php echo $dataTeacher['tutor_name']?></div>
  	</div>

<?php
	if ($this->sendDataStudents) {
			?>
		<br>
		<div class="panel panel-primary">
			<table class='table table-hover table-striped'>
				<tr>
					<th class='text-center'>#</th>
					<th class='text-center'>Código</th>
					<th class='text-center'>Apellidos y Nombres</th>
					<th class='text-center'>fecha de Atención</th>
					<th class='text-center'>Motivo</th>
					<th class='text-center'>Resumen</th>
				</tr>
			<?php
			foreach ($this->sendDataStudents as $key => $dataS) {
				$uid		=	$dataS['uid'];
				$full_name  =	$dataS['full_name'];
				$f_atention	=	$dataS['f_atention'];
				$motivo		=	$dataS['motivo'];
				$resumen	=	$dataS['resumen'];
			?>
				<tr>
					<td class='text-center'><?php echo $key+1?></td>
					<td class='text-center'><?php echo $uid?></td>
					<td><?php echo $full_name?></td>
					<td class='text-center'>
						<?php 
							if ($f_atention) {
								echo $f_atention;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger' data-toggle="tooltip" data-placement="top" title="No tiene fecha"></span>
							<?php	
							}
						?>
					</td>
					<td class='text-center'>
						<?php 
							if ($motivo) {
								echo $motivo;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger' data-toggle="tooltip" data-placement="top" title="No tiene un motivo"></span>
							<?php	
							}
						?>
					</td>
					<td class='text-center'>
						<?php 
							if ($resumen) {
								echo $resumen;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger' data-toggle="tooltip" data-placement="top" title="No tiene un resumen"></span>
							<?php	
							}
						?>
					</td>
				</tr>
			<?php	
			}
			?>
			</table>
		</div>	
			<?php
		} else {	?>
			<div class='panel panel-primary'>
				<h5><center><b class='text-info'><span class='glyphicon glyphicon-info-sign'></span> Aún no existe alumnos registrados</b></center></h5>
			</div>
		<?php	
		}
		?>	
	<div class="modal-footer">
		<a id='print_informe' href="/acreditacion/tutorship/printinfotutoria/pid/<?php echo base64_encode($this->pid)?>/perid/<?php echo base64_encode($this->perid)?>" class="btn btn-success"><span class='glyphicon glyphicon-print'></span> Imprimir</a>
    	<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
  	</div>
<?php  	
} else {	?>
	<div class='panel panel-primary'>
		<h5><center><b class='text-danger'><span class='glyphicon glyphicon-info-sign'></span> No hay ningun informe</b></center></h5>
	</div>
<?php	
}

?>
<div id='load_print'></div>
<script type="text/javascript">
	$(".glyphicon").tooltip();

	$("#print_informe").click(function(){
		var pid="<?php echo $this->pid?>";
		var perid="<?php echo $this->perid?>";

		var url=("/acreditacion/tutorship/printinfotutoria/pid/"+pid+"/perid/"+perid);
		$("#load_print").load();
		
	});	
</script>