<?php
if ($this->sendDataTutoring) {
	$dataTeacher=$this->sendDataTutoring;
	?>
	<div class="modal-header">
    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    	<h4 class="modal-title" id="myModalLabel"><center><span class='glyphicon glyphicon-file text-info'></span><b class='text-primary'> INFORME DE TUTORIA</b></center></h4><br>
		<div style='font-size:15px'><b>Docente: </b><?php echo $dataTeacher['tutor_name']?></div>
  	</div>

<?php
	if ($this->sendDataStudents) {
			?>
		<br>
		<div class="panel panel-primary">
			<table class='table table-hover table-striped'>
				<tr>
					<th class='text-center'>#</th>
					<th class='text-center'>Código</th>
					<th class='text-center'>Apellidos y Nombres</th>
					<th class='text-center'>fecha de Atención</th>
					<th class='text-center'>Motivo</th>
					<th class='text-center'>Resumen</th>
				</tr>
			<?php
			foreach ($this->sendDataStudents as $key => $dataS) {
				$uid		=	$dataS['uid'];
				$full_name  =	$dataS['full_name'];
				$f_atention	=	$dataS['f_atention'];
				$motivo		=	$dataS['motivo'];
				$resumen	=	$dataS['resumen'];
			?>
				<tr>
					<td class='text-center'><?php echo $key+1?></td>
					<td class='text-center'><?php echo $uid?></td>
					<td><?php echo $full_name?></td>
					<td class='text-center'>
						<?php 
							if ($f_atention) {
								echo $f_atention;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger' data-toggle="tooltip" data-placement="top" title="No hay data"></span>
							<?php	
							}
						?>
					</td>
					<td class='text-center'>
						<?php 
							if ($motivo) {
								echo $motivo;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger'></span>
							<?php	
							}
						?>
					</td>
					<td class='text-center'>
						<?php 
							if ($resumen) {
								echo $resumen;
							} else {	?>
								<span class='glyphicon glyphicon-ban-circle text-danger'></span>
							<?php	
							}
						?>
					</td>
				</tr>
			<?php	
			}
			?>
			</table>
		</div>	
			<?php
		} else {	?>
			<div class='panel panel-primary'>
				<h5><center><b class='text-info'><span class='glyphicon glyphicon-info-sign'></span> Aún no existe alumnos registrados</b></center></h5>
			</div>
		<?php	
		}

} else {	?>
	<div class='panel panel-primary'>
		<h5><center><b class='text-danger'><span class='glyphicon glyphicon-info-sign'></span> Aún no existe alumnos registrados</b></center></h5>
	</div>
<?php	
}

?>

<script type="text/javascript">
	
</script>