<div id="bloquearDocentes" class="docentesCapaProtectora" hidden></div>

<table class="table table-hover">
	<tr class="active">
		<th class="text-center">#</th>
		<th>Docente</th>
		<th class="text-center">Codigo</th>
		<th class="btnAsignar text-center">Estado</th>
		<th></th>
	</tr>
	<?php foreach ($this->teachers as $c => $teacher): ?>
		<tr id="trDocente<?php echo $teacher['uid'] ?>" class="trDocente">
			<td class="text-center"><?php echo $c + 1 ?></td>
			<td><?php echo $teacher['full_name'] ?></td>
			<td class="text-center"><?php echo $teacher['uid'] ?></td>
			<td class="estado text-center">
				<span id="tdSuccess<?php echo $teacher['uid'] ?>">
				<?php if ($teacher['asigned'] == 'yes'):?>
					<strong class="text-success">Asignado</strong>
				<?php else: ?>
					No Asignado
				<?php endif ?>
				</span>

				<div id="asignarDocente<?php echo $teacher['uid'] ?>" uid="<?php echo $teacher['uid'] ?>" class="asignarDocente">
					<div id="loading<?php echo $teacher['uid'] ?>" hidden>
						<img src="/img/spinner.gif" alt="Loading">
					</div>
					<?php if ($teacher['asigned'] == 'no'):
						$formNew         = '';
						$divAsignado     = 'hidden';
						$cantStudent     = '';
						$semesterAsigned = '';
						$tutoringId      = '';
						$existEdit       = '';
					else:
						$formNew         = 'hidden';
						$divAsignado     = '';
						$cantStudent     = $teacher['number'];
						$semesterAsigned = $teacher['semid'];
						$tutoringId      = $teacher['tutoringId'];
						$existEdit       = 'existEdit';
					endif ?>
					<!--Nuevo-->
					<form id="form<?php echo $teacher['uid'] ?>" uid="<?php echo $teacher['uid'] ?>" class="form" <?php echo $formNew ?>>
						<input type="hidden" name="uid" value="<?php echo $teacher['uid'] ?>" />
						<input type="hidden" name="pid" value="<?php echo $teacher['pid'] ?>" />
						<select id="semid<?php echo $teacher['uid'] ?>" name="semid" class="semestre form-control">
							<option value="">Semestre</option>
							<?php foreach ($this->semesters as $semester): ?>
								<option value="<?php echo $semester['semid'] ?>"><?php echo $semester['name'] ?></option>
							<?php endforeach ?>
						</select>
						<div class="cantStudent">
							<span title="Cantidad de Estudiantes Matriculados">
								<span class="cantStudents<?php echo $teacher['uid'] ?> cantStudentsNum">-</span>
								<div id="messageRefernecial<?php echo $teacher['uid'] ?>" class="messageSemesterReferencial" hidden>
									<span class="glyphicon glyphicon-exclamation-sign"></span> La cantidad de matriculados hace referencia al semestre anterior...
								</div>
							</span>
							<input type="text" class="form-control inputCantStudent" id="inputCantStudent<?php echo $teacher['uid'] ?>" name="cantStudents" placeholder="# Estudiantes" />
						</div>
						<input type="submit" class="btn btn-success btnAsignar form-control" value="Asignar" />
					</form>

					<!--Editar-->
					<form id="formEdit<?php echo $teacher['uid'] ?>" class="formEdit" hidden>
						<input type="hidden" id="inputTutoring<?php echo $teacher['uid'] ?>" name="tutoringId" value="<?php echo $tutoringId ?>" />
						<?php if ($teacher['alreadyStudents'] == 'yes'): 
							$stateSelect = 'disabled';
						else:
							$stateSelect = '';
						endif ?>
						<select id="semidEdit<?php echo $teacher['uid'] ?>" uid="<?php echo $teacher['uid'] ?>" name="semid" class="semestre form-control" value="<?php echo $semester ?>" <?php echo $stateSelect ?>>
							<option value="">Semestre</option>
							<?php foreach ($this->semesters as $semester): ?>
								<option value="<?php echo $semester['semid'] ?>"><?php echo $semester['name'] ?></option>
							<?php endforeach ?>
						</select>
						<div class="cantStudent "><span class="cantStudentsNum cantStudents<?php echo $teacher['uid'] ?>" title="Cantidad de Estudiantes Matriculados">-</span>
							<input type="text" class="form-control inputCantStudent" id="inputCantStudentEdit<?php echo $teacher['uid'] ?>" name="cantStudents" placeholder="# Estudiantes" value="<?php echo $cantStudent ?>"/>
						</div>
						<input type="submit" class="btn btn-success btnAsignar form-control" value="Guardar" />
						<a href="##" class="cancelEditAsignacion btn btn-danger form-control" uid="<?php echo $teacher['uid'] ?>">Cancelar</a>
						<script>
							$("#semidEdit<?php echo $teacher['uid'] ?>").val("<?php echo $semesterAsigned ?>");
						</script>
					</form>				
	
					<!--Div de Asignación-->
					<div id="divAsignado<?php echo $teacher['uid'] ?>" class="divAsignado <?php echo $existEdit ?>" <?php echo $divAsignado ?>>
						<p class="text-success text-center">Asignado al <strong id="semestreStrong<?php echo $teacher['uid'] ?>"> <?php echo $semesterAsigned ?> Semestre</strong></p>
						<a href="##" class="btnEditAsignacion btn btn-info form-control" uid="<?php echo $teacher['uid'] ?>">Editar</a>
						<a href="##" id="btnDelete<?php echo $teacher['uid'] ?>" class="btnDeleteAsignacion btn btn-danger form-control">Desasignar</a>
					</div>
				</div>
			</td>
			<td class="tdAsignar text-center">
				<a href="##" uid="<?php echo $teacher['uid'] ?>" title="Asignar" class="text-success showAsignar"><span class="glyphicon glyphicon-ok"></span></a>
			</td>
		</tr>
	<?php endforeach ?>
</table>
<div id="dataDocentesAsignados" class="docentesAsignados docentesAsignadosClose hidden">
	<div class="title">
		<p><span class="glyphicon glyphicon-bookmark"></span> Docentes Asignados como Tutores</p>
	</div>
	<div id="idListDocentesAsignados" class="listDocentesAsignados">
		
	</div>
</div>

<script>
	$(function(){
		//BackEnd y Carga de Datos
		$('.cantStudentsNum').hover(function(){
			$(this).tooltip('toggle');
		});

		$('#idListDocentesAsignados').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center>');
		$('#idListDocentesAsignados').load('/acreditacion/tutorship/listasignedteacher/');

		//Navegación UX
		var uid        = '';
		var uidElement = '';
		var semid      = '';
		var tutoringId = '';

		$('#btnDocentesAsignados').on('click', function(){
			$('#bloquearDocentes').fadeToggle(1000);
			$('#dataDocentesAsignados').removeClass('hidden');
			$(this).addClass('disabled');
			$('#dataDocentesAsignados').toggleClass('docentesAsignadosOpen');
			$('#dataDocentesAsignados').toggleClass('docentesAsignadosClose');
			setTimeout(function(){$('#btnDocentesAsignados').removeClass('disabled')}, 1500);
		});

		$('.showAsignar').on('click', function(){
			uid = $(this).attr('uid');

			$('.asignarDocente').each(function(index, element){
				uidElement = $(element).attr('uid');
				if (uidElement != uid ) {
					$(element).slideUp('fast');
					$('#trDocente' + uidElement).removeClass('success');
				};
			});

			$('.formEdit').slideUp();
			$('.existEdit').slideDown();

			$('#asignarDocente' + uid).slideToggle('fast');
			$('#trDocente' + uid).toggleClass('success');
		});

		$('.btnEditAsignacion').on('click', function(){
			$('#divAsignado' + uid).slideUp();
			$('#formEdit' + uid).slideDown();
		});
		
		$('.cancelEditAsignacion').on('click', function(){
			$('#formEdit' + uid).slideUp();
			$('#divAsignado' + uid).slideDown();
		});


		$('.semestre').on('change', function(){
			semid = $(this).val();
			$('.cantStudents' + uid).html('<img src="/img/spinner.gif" alt="C" />')
									.load('/acreditacion/tutorship/cantstudentsxsem/semid/' + semid);

			$('#messageRefernecial' + uid).fadeIn('fast');
			setTimeout(function(){
				$('#messageRefernecial' + uid).fadeOut('fast');
			}, 5000);
		});


		$('.semestre').each(function(){
			semid = $(this).val();
			uid   = $(this).attr('uid');
			if (semid) {
				$('.cantStudents' + uid).html('<img src="/img/spinner.gif" alt="C" />')
										.load('/acreditacion/tutorship/cantstudentsxsem/semid/' + semid);
			};
		});

		//Interaccion con Base De Datos

		//Guardar
		$('.form').submit(function(e){
			e.preventDefault();
			$(this).slideUp();
			semid = $('#semid' + uid).val();
			cantStudents = $('#inputCantStudent' + uid).val();
			$('#loading' + uid ).slideDown();
			$.ajax({
				type : 'post',
				url : '/acreditacion/tutorship/asignardocente/',
				data : $(this).serialize(),
				dataType : 'json',
				success : function(data){
					if (data.success === 1) {
						$('#form' + uid).slideDown();
					}else if(data.success === 2){
						$('#divAsignado' + uid).slideDown()
												.addClass('existEdit');

						$('#tdSuccess' + uid).html('<strong class="text-success">Asignado</strong>');
						$('#semestreStrong' + uid).html(semid + ' Semestre');

						$('#inputTutoring' + uid).val(data.tutoringId);
						$('#semidEdit' + uid).val(semid);
						$('#inputCantStudentEdit' + uid).val(cantStudents);

						$('#cantStudentsEdit' + uid).html('<img src="/img/spinner.gif" alt="C" />')
													.load('/acreditacion/tutorship/cantstudentsxsem/semid/' + semid)

						$('#idListDocentesAsignados').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center>')
													.load('/acreditacion/tutorship/listasignedteacher/');
					};
					$('#loading' + uid ).slideUp();
				},
				error : function(){
					$('#form' + uid).slideDown();
					$('#loading' + uid ).slideUp();
				}
			});
		});
		
		//Editar
		$('.formEdit').submit(function(e){
			e.preventDefault();
			$(this).slideUp();
			$('#loading' + uid).slideDown();
			semid = $('#semidEdit' + uid).val();

			$.ajax({
				type : 'post',
				url : '/acreditacion/tutorship/editasignaciondocente/',
				data : $(this).serialize(),
				dataType : 'json',
				success : function(data){
					if (data.success === 1) {
						$('#semestreStrong' + uid).html(semid + ' Semestre');
						$('#divAsignado' + uid).slideDown();

						$('#idListDocentesAsignados').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center>')
													.load('/acreditacion/tutorship/listasignedteacher/');
					}else{
						$('#formEdit' + uid).slideDown();
					};
					$('#loading' + uid ).slideUp();
				},
				error : function(){
					$('#formEdit' + uid).slideDown();
					$('#loading' + uid ).slideUp();
				}
			});
		});

		//Eliminar

		$('.btnDeleteAsignacion').on('click', function(){
			$('#loading' + uid ).slideDown();
			$('#divAsignado' + uid).slideUp();
			tutoringId = $('#inputTutoring' + uid).val();
			$.ajax({
				url : '/acreditacion/tutorship/desasignedteacher/',
				data : {tutoringid : tutoringId},
				success : function(data){
					if (data == 1) {
						$('#tdSuccess' + uid).html('No Asignado');
						$('#form' + uid).slideDown();
						$('#divAsignado' + uid).removeClass('existEdit');
						$('#semestreStrong' + uid).html('');

						$('#idListDocentesAsignados').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center>')
													.load('/acreditacion/tutorship/listasignedteacher/');
					}else{
						$('#formEdit' + uid).slideDown();
					};
					$('#loading' + uid ).slideUp();
				},
				error : function(){
					$('#divAsignado' + uid).slideDown();
					$('#loading' + uid ).slideUp();
				}
			});
		});
		

});
</script>