<table class="table table-hover">
	<tr class="active">
		<th class="text-center">#</th>
		<th>Docente</th>
		<th class="text-center">Codigo</th>
		<th class="btnAsignar text-center">Estado</th>
		<th></th>
	</tr>
	<?php foreach ($this->teachers as $c => $teacher): ?>
		<tr id="trDocente<?php echo $teacher['uid'] ?>" class="trDocente">
			<td class="text-center"><?php echo $c + 1 ?></td>
			<td><?php echo $teacher['full_name'] ?></td>
			<td class="text-center"><?php echo $teacher['uid'] ?></td>
			<td class="estado text-center">
				No Asignado
				<div id="asignarDocente<?php echo $teacher['uid'] ?>" uid="<?php echo $teacher['uid'] ?>" class="asignarDocente">
					<form id="form<?php echo $uid ?>" class="form">
						<input type="hidden" name="uid" value="<?php echo $teacher['uid'] ?>" />
						<select name="semid" class="semestre form-control">
							<option value="">Semestre</option>
							<?php foreach ($this->semesters as $semester): ?>
								<option value="<?php echo $semester['semid'] ?>"><?php echo $semester['name'] ?></option>
							<?php endforeach ?>
						</select>
						<input type="submit" class="btn btn-success btnAsignar form-control" value="Asignar" />
						<!--<a href="##" class="btn btn-success btnAsignar form-control">Asignar</a>-->
					</form>
				</div>
			</td>
			<td class="tdAsignar text-center">
				<a href="##" uid="<?php echo $teacher['uid'] ?>" title="Asignar" class="text-success showAsignar"><span class="glyphicon glyphicon-ok"></span></a>
			</td>
		</tr>
	<?php endforeach ?>
</table>

<script>
	$(function(){
		$('a').hover(function(){
			$(this).tooltip('toggle');
		});

		$('.showAsignar').on('click', function(){
			var uid = $(this).attr('uid');

			$('.asignarDocente').each(function(index, element){
				var block      = $(element).css('display');
				var uidElement = $(element).attr('uid');
				if (block != 'none' && uidElement != uid ) {
					$(element).slideUp('fast');
					$('#trDocente' + uidElement).removeClass('success');
				};
			});

			$('#asignarDocente' + uid).slideToggle('fast');
			$('#trDocente' + uid).toggleClass('success');
		});

		$('.form').submit(function(e){
			e.preventDefault();
			$.ajax({
				type : 'post',
				data : $(this).serialize(),
				url : '/acreditacion/tutorship/asignardocente/',
				success : function(data){
					console.log(data);
				}
			});
		});
});
</script>