<link rel="stylesheet" href="/css/tutorshipReport.css" />

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Tutoria');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/docente/"><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>

<?php if ($this->dataTutoring): 
	$dataTutoring = $this->dataTutoring;
	?>
	<div class="nameTutoring">
		<span class="glyphicon glyphicon-bookmark"></span> <?php echo $dataTutoring['name'] ?>
		<p class="cantStudents">
			<?php echo $dataTutoring['cant_register'].'/'.$dataTutoring['number'] ?>
		</p>
		<p class="nameTutor">
			<span class="glyphicon glyphicon-user"></span> <?php echo $dataTutoring['tutor_name'] ?>
		</p>
	</div>
	<div class="students">
	<?php if ($this->dataStudents): ?>
		
		<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Lista de Estudiantes Registrados :</p>
		<div class="listStudents">
			<table class="table table-hover">
				<tr class="active">
					<th class="text-center">#</th>
					<th>Apellidos y Nombres</th>
					<th class="text-center">Codigo</th>
					<th class="text-center">Fecha de Atención</th>
					<th></th>
				</tr>
				<?php foreach ($this->dataStudents as $c => $student): ?>
				<tr class="trStudent<?php echo $student['uid'] ?>" id="trStudentUid<?php echo $student['uid'] ?>">
					<td class="text-center"><?php echo $c + 1 ?></td>
					<td><?php echo $student['full_name'] ?></td>
					<td class="text-center"><?php echo $student['uid'] ?></td>
					<td class="text-center" id="tdDateAtention<?php echo $student['uid'] ?>"><?php echo $student['f_atention'] ?></td>
					<td class="text-center"><a href="##" uid="<?php echo $student['uid'] ?>" class="btnShowMoreDetail text-success"><span class="glyphicon glyphicon-wrench"></span></a></td>
				</tr>
				<tr class="trStudent<?php echo $student['uid'] ?>">
				<td colspan="5" style="padding: 0;">
					<div class="moreDetail" id="moreDetail<?php echo $student['uid'] ?>" uid="<?php echo $student['uid'] ?>" hidden>
						<form class="formData">
							<input type="hidden" name="idStudent" value="<?php echo $student['id'] ?>" />
							<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Elija la fecha de atención y explique el resumen y motivo :</p>
							<p class="dataPicker"> Fecha de Atención
								<input class="form-control inputDataPicker" id="inputDataPicker<?php echo $student['uid'] ?>" name="FechaAtencion" type="text" value="<?php echo $student['f_atention'] ?>" />
							</p>
							<div class="motivo">
								<p class="text-muted">Motivo</p>
								<textarea class="form-control" name="Motivo" id="" cols="30" rows="10" placeholder="Motivo de la atención......"><?php echo $student['motivo'] ?></textarea>
							</div>
							<div class="resumen">
								<p class="text-muted">Resumen</p>
								<textarea class="form-control" name="Resumen" id="" cols="30" rows="10" placeholder="Escriba el resumen de lo actuado......"><?php echo $student['resumen'] ?></textarea>
							</div>
							<hr>
							<div class="msgGuardado" id="msgGuardado<?php echo $student['uid'] ?>"></div>
							<input type="submit" class="btnSubmitForm btn btn-info form-control" value="Guardar" />
						</form>
					</div>
				</td>
				</tr>
				<?php endforeach ?>
			</table>
		</div>
		<div class="menu">
			<a id="_preview" href="#" class="btn btn-success form-control">Vista Previa</a>
			<a id="_print" href="/acreditacion/tutorship/printinfotutoria/pid/<?php echo base64_encode($this->pid)?>/perid/<?php echo base64_encode($this->perid)?>" class="btn btn-success form-control">Imprimir</a>
			<a href="##" class="btn btn-success form-control">Enviar Informe</a>
		</div>
		
		<!-- MODAL VISTA PREVIA -->
		<div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog" style='width:80%'>
			    <div class="modal-content">
			      	<div class="modal-body" id='_loadata'></div>
			    </div>
			</div>
		</div>
		<script>
			$("#_preview").click(function(){
				var url=("/acreditacion/tutorship/infotutoria/");
				$("#_loadata").html("<br><center><img src='/img/spinner.gif'> Cargando....</center>");
				$("#_loadata").load(url);
				$("#previewModal").modal('show');
			});

			var uid = '';
			$('.btnShowMoreDetail').on('click', function(){
				uid = $(this).attr('uid');
				$('.moreDetail').each(function(index, element){
					var display = $(element).css('display');
					var elementUid = $(element).attr('uid');
					if (uid != elementUid) {
						$(element).slideUp();
						$('.trStudent' + elementUid).removeClass('success');
					};
				});

				$('#moreDetail' + uid).slideToggle();
				$('.trStudent' + uid).toggleClass('success');

				$('html body').animate({
					scrollTop : $('#trStudentUid' + uid).offset().top,
				}, 500);
			});

			$('.inputDataPicker').datepicker();

			$('.formData').on('submit', function(e){
				e.preventDefault();
				$('#msgGuardado' + uid).html('<img src="/img/spinner.gif" alt="Loading..." />');
				$.ajax({
					type : 'post',
					url : '/acreditacion/tutorship/saveatention/',
					data : $(this).serialize(),
					success : function(data){
						console.log(data);
						if (data == 1) {
							var	dateAtentionSplit = $('#inputDataPicker' + uid).val().split('/');
							var dateAtention = '';
							if (dateAtentionSplit[1]) {
								dateAtention = dateAtentionSplit[1] + '-' + dateAtentionSplit[0] + '-' + dateAtentionSplit[2];
							}else{
								dateAtention = $('#inputDataPicker' + uid).val();
							};
							$('#msgGuardado' + uid).html('<span class="text-success">Se Guardaron los cambios con exito!</span>');
							$('#tdDateAtention' + uid).html(dateAtention);
						}else if(data == 2){
							$('#msgGuardado' + uid).html('<span class="text-danger">Falta rellenar algunos datos</span>');
						};
						setTimeout(function(){
							$('#msgGuardado' + uid).html('');
						}, 5000);
					}
				});
			});

		</script>

	<?php else: ?>
		<h4 class="text-muted text-center emptyStudents"><span class="glyphicon glyphicon-exclamation-sign"></span> Aun no existe <span class="text-info">estudiantes registrados</span></h4>
	<?php endif ?>
	</div>
<?php else: ?>
	<br><h4 class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign"></span> Usted no esta registrado <span class="text-info">para ser tutor este Periodo</span></h4>
<?php endif ?>