<link rel="stylesheet" href="/css/tutorshipReport.css" />

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Tutoria');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/docente/" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>

<?php if ($this->dataTutoring): 
	$dataTutoring = $this->dataTutoring;
	?>
	<div class="nameTutoring">
		<span class="glyphicon glyphicon-bookmark"></span> <?php echo $dataTutoring['name'] ?>
		<p class="cantStudents">
			<?php echo $dataTutoring['cant_register'].'/'.$dataTutoring['number'] ?>
		</p>
		<p class="nameTutor">
			<span class="glyphicon glyphicon-user"></span> <?php echo $dataTutoring['tutor_name'] ?>
		</p>
	</div>
	<div class="students">
	<?php if ($this->dataStudents): ?>
		
		<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Lista de Estudiantes Registrados :</p>
		<div class="listStudents">
			<table class="table table-hover">
				<tr class="active">
					<th class="text-center">#</th>
					<th>Apellidos y Nombres</th>
					<th class="text-center">Codigo</th>
					<th class="text-center">Fecha de Atención</th>
					<th></th>
				</tr>
				<?php foreach ($this->dataStudents as $c => $student): ?>
				<tr>
					<td class="text-center"><?php echo $c + 1 ?></td>
					<td><?php echo $student['full_name'] ?></td>
					<td class="text-center"><?php echo $student['uid'] ?></td>
					<td class="text-center"><?php echo $student['f_atention'] ?></td>
					<td class="text-center"><a href="##" uid="<?php echo $student['uid'] ?>" class="btnShowMoreDetail text-success"><span class="glyphicon glyphicon-wrench"></span></a></td>
				</tr>
				<tr>
				<td colspan="5" style="padding: 0;">
					<div class="moreDetail" id="moreDetail<?php echo $student['uid'] ?>" hidden>
						<form class="formData">
							<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Elija la fecha de atención y explique el resumen y motivo :</p>
							<p class="dataPicker"> Fecha de Atención
								<input class="form-control inputDataPicker" name="FechaAtencion" type="text"/>
							</p>
							<div class="resumen">
								<p class="text-muted">Resumen</p>
								<textarea class="form-control" name="Resumen" id="" cols="30" rows="10" placeholder="Escriba el resumen de lo actuado......"></textarea>
							</div>
							<div class="motivo">
								<p class="text-muted">Motivo</p>
								<textarea class="form-control" name="Motivo" id="" cols="30" rows="10" placeholder="Motivo de la atención......"></textarea>
							</div>
							<input type="submit" class="btnSubmitForm btn btn-info form-control" value="Guardar" />
						</form>
					</div>
				</td>
				</tr>
				<?php endforeach ?>
			</table>
		</div>
		<div class="menu">
			<a href="##" class="btn btn-success form-control">Vista Previa</a>
			<a href="##" class="btn btn-success form-control">Imprimir</a>
			<a href="##" class="btn btn-success form-control">Enviar Informe</a>
		</div>
		
		<script>
			var uid = '';
			$('.btnShowMoreDetail').on('click', function(){
				uid = $(this).attr('uid');
				$('#moreDetail' + uid).slideToggle();
			});

			$('.formData').on('submit', function(e){
				e.preventDefault();
				$.ajax({
					type : 'post',
					url : '/acreditacion/tutorship/saveatention/',
					data : $(this).serialize(),
					success : function(data){
						console.log(data);
					}
				});
			});
		</script>

	<?php else: ?>
		<h4 class="text-muted text-center emptyStudents"><span class="glyphicon glyphicon-exclamation-sign"></span> Aun no existe <span class="text-info">estudiantes registrados</span></h4>
	<?php endif ?>
	</div>
<?php else: ?>
	<br><h4 class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign"></span> Usted no esta registrado <span class="text-info">para ser tutor este Periodo</span></h4>
<?php endif ?>
