<?php 
//print_r($this->companias);
$com=$this->companias;
//print_r($com);
?>
<table class="table table-striped table-condensed">
	<tr>
        <th>DNI</th>
        <th>Company</th>
        <th>Condicion</th>
        <th>Apellidos y Nombres</th>
        <th>Salary</th>

	});

	</tr>
	<?php 

	$i=0;
	foreach ($com as $companias )
	{
		$i++;
		
		foreach ($companias as $key )
		{
			$per=new Api_Model_DbTable_Person();
			
			$where['pid'] = $key['pid'];
          	$where['eid'] = $key['eid'];
			$p=$per->_getOne($where);
            $info2 = $p['last_name0']." ".$p['last_name1']." ".$p['first_name'];
			       
			?>
			<tr>
			<td><?php echo $key['pid'];?></td>
			<td><?php echo $key['company'];?></td>
			<td><?php echo $key['condition'];?></td>
			<td><?php echo $info2;?></td>			
			<td><?php echo $key['salary'];?></td>
			</tr>
			
			<?php
		}

	}
?>
</table>
       
