<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-tint"></span> Prematricula');?>


<?php /*$this->placeholder('AuxiliarMobile')->append('<div class="info">
													<p class="active">
														<span class="full">Págo</span> 
														<span class="abbr">PR</span> 
														<strong>S/. 35.00</strong>
													</p>
													<p class="active">
														<span class="full">Pago a Realizar</span> 
														<span class="abbr">PO</span> 
														<strong>S/. 35.00</strong>
													<p class="active">
														<span class="full">Créditos Permitidos</span> 
														<span class="abbr">CP</span> 
														<strong>11</strong>
													</p>
													<p class="active">
														<span class="full">Créditos Matriculados</span> 
														<span class="abbr">CM</span> 
														<strong>8</strong>
													</p>
												</div>');*/ ?>

<?php /*$this->placeholder('AuxiliarMobile')->append('<div class="buttons one">
														<a href="##" class="button button--small button--print">Impirmir <span class="glyphicon glyphicon-print"></span></a>
													</div>');*/ ?>

<?php /*$this->placeholder('AuxiliarMobile')->append('<div class="buttons">
														<a href="##" class="button button--small  button--alter  button--alter--success">Nuevo <span class="glyphicon glyphicon-plus-sign"></span></a>
													</div>');*/ ?>

													

<section class="content content--small">
	<header class="content__header  content__header--interaction">
		<p class="info"><span class="glyphicon glyphicon-info-sign"></span> Tambien existe periodos en otros años...</p>
		<section class="interaction__content">
			<div class="column_uno">
				<select class="select" name="anio">
					<?php for ($i=date('Y'); $i>1992 ; $i--): ?>
						<option value=""><?php print $i ?></option>
					<?php endfor ?>
				</select>
			</div>
			<!--<div class="column_dos">
				<a href="##" class="button button--medium">Nuevo</a>
			</div> -->
		</section>

	</header>
	<section class="content__body">

		<section class="group  group--active">
			<header class="group__header">
				Periodo Activo
			</header>
			<section class="group__body">
				<article class="item-table  item-table--active">
					<header class="item-table__header">
						Periodo 15A
					</header>
					<section class="item-table__body">
						<p>Resolución 15 TRH-SUNDK 00001</p>
						<p>Inicio de Clases <strong>15-04-2015</strong></p>
						<p>Fin de Clases <strong>13-07-2015</strong></p>
						<p class="display-tablet">Otro Dato</p>
						<p class="display-tablet">Otro Dato Largo</p>
						<p>Otro Dato mas Largo</p>
					</section>
					<footer class="item-table__footer footer--buttons footer--buttons--two">
						<a href="##" class="button button--small button--table button--table--warning">Editar <span class="glyphicon glyphicon-pencil"></span></a>
						<a href="##" class="button button--small button--table button--table--danger">Eliminar <span class="glyphicon glyphicon-remove"></span> </a>
					</footer>
				</article>
			</section>
		</section>

		<section class="group group--temporary">
			<header class="group__header">
				Periodos Temporales
			</header>
			<section class="group__body">
				<article class="item-table">
					<header class="item-table__header">
						Periodo 15T
					</header>
					<section class="item-table__body">
						<p>Resolución 15 TRH-SUNDK 00001</p>
						<p>Inicio de Clases <strong>15-04-2015</strong></p>
						<p>Fin de Clases <strong>13-07-2015</strong></p>
						<p class="display-tablet">Otro Dato</p>
						<p class="display-tablet">Otro Dato Largo</p>
						<p>Otro Dato mas Largo</p>
					</section>
					<footer class="item-table__footer footer--buttons footer--buttons--two">
						<a href="##" class="button button--small button--table button--table--warning">Editar <span class="glyphicon glyphicon-pencil"></span></a>
						<a href="##" class="button button--small button--table button--table--danger">Eliminar <span class="glyphicon glyphicon-remove"></span> </a>
					</footer>
				</article>

				<article class="item-table">
					<header class="item-table__header">
						Periodo 15J
					</header>
					<section class="item-table__body">
						<p>Resolución 15 TRH-SUNDK 00001</p>
						<p>Inicio de Clases <strong>15-04-2015</strong></p>
						<p>Fin de Clases <strong>13-07-2015</strong></p>
						<p class="display-tablet">Otro Dato</p>
						<p class="display-tablet">Otro Dato Largo</p>
						<p>Otro Dato mas Largo</p>
					</section>
					<footer class="item-table__footer footer--buttons footer--buttons--two">
						<a href="##" class="button button--small button--table button--table--warning">Editar <span class="glyphicon glyphicon-pencil"></span></a>
						<a href="##" class="button button--small button--table button--table--danger">Eliminar <span class="glyphicon glyphicon-remove"></span> </a>
					</footer>
				</article>
			</section>
		</section>

	</section>
</section>

<!--<section class="preregister ok">
	<p class="info info--main"><span class="glyphicon glyphicon-info-sign"></span> Seleccione los cursos que llevara</p>

	<section class="content content--normal">
		<header class="content__header"><span class="glyphicon glyphicon-flag"></span> Semestre 1</header>
		
		<section class="content__body">
			<article class="item item--blue">
				<section class="item__body">
					<p class="icon vertical_center"><span class="glyphicon glyphicon-book"></span></p>
					<p class="text_left whit_code">Algoritmos I <small>0925412</small></p>
					<p class="text_left"><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
					<p class="inline">5 Créditos</p>
					<p class="inline">Turno A</p>
					<p>1 matriculado hasta ahora...</p>
				</section>
				<footer class="item__footer">
					<div class="checkbox checkbox--success">
						<input id="course_1" type="checkbox">
						<label for="course_1">Llevar <span class="glyphicon glyphicon-ok"></span></label>
					</div>
				</footer>
			</article>

			<article class="item item--blue">
				<section class="item__body">
					<p class="icon vertical_center"><span class="glyphicon glyphicon-book"></span></p>
					<p class="text_left whit_code">Calculo Psicomotriz I <small>0925412</small></p>
					<p class="text_left"><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
					<p class="inline">3 Créditos</p>
					<p class="inline">Turno A</p>
					<p>1 matriculado hasta ahora...</p>
				</section>
				<footer class="item__footer">
					<div class="checkbox checkbox--success">
						<input id="course_2" type="checkbox">
						<label for="course_2">Llevar <span class="glyphicon glyphicon-ok"></span></label>
					</div>
				</footer>
			</article>

			<article class="item item--blue">
				<section class="item__body">
					<p class="icon vertical_center"><span class="glyphicon glyphicon-book"></span></p>
					<p class="text_left whit_code">Tendencias Suicidads en la Juventud Conteporanea Actual I <small>0925412</small></p>
					<p class="text_left"><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
					<p class="inline">5 Créditos</p>
					<p class="inline">Turno A</p>
					<p>1 matriculado hasta ahora...</p>
				</section>
				<footer class="item__footer">
					<div class="checkbox checkbox--success">
						<input id="course_3" type="checkbox">
						<label for="course_3">Llevar <span class="glyphicon glyphicon-ok"></span></label>
					</div>
				</footer>
			</article>

			<article class="item item--blue">
				<section class="item__body">
					<p class="icon vertical_center"><span class="glyphicon glyphicon-book"></span></p>
					<p class="text_left whit_code">Matematica Basica I <small>0925412</small></p>
					<p class="text_left"><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
					<p class="inline">5 Créditos</p>
					<p class="inline">Turno A</p>
					<p>1 matriculado hasta ahora...</p>
				</section>
				<footer class="item__footer">
					<div class="checkbox checkbox--success">
						<input id="course_4" type="checkbox">
						<label for="course_4">Llevar <span class="glyphicon glyphicon-ok"></span></label>
					</div>
				</footer>
			</article>
		</section>
	</section>
	
	<section class="content--buttons one">
		<a href="##" class="button button--icon button--success">Prematricularme <span class="glyphicon glyphicon-ok-circle"></span></a>
	</section>
</section> -->

<!-- <section class="preregister error">
	<p class="info"><span class="glyphicon glyphicon-exclamation-sign"></span> Ups!!</p>
	<section class="content normal">
		<header>:(</header>
		<section>
			<p class="danger"><span class="glyphicon glyphicon-exclamation-sign"></span> Hay un retraso en la carga académica, acerquese a dirección de su escuela para mas información...</p>
		</section>
	</section>
</section> -->

<!-- <section class="preregister confirm">
	<p class="info"><span class="glyphicon glyphicon-ok"></span> Ok, llevaras estos cursos este periodo y perteneceras al <strong>IV Semestre</strong>, verificalo y confirma...</p>

	<section class="content normal">
		<header>
			Prematricula Periodo 14A
		</header>
		
		<section>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Algoritmos I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Tendencias Suicidas en la Juevntud Actual Contemporanea I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA Y MONTOYA, Cruela de Vil</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Calculo Psicomotriz I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA, San Ignacion</p>
				<p>10 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Tendencias Suicidas en la Juevntud Actual Contemporanea I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA Y MONTOYA, Cruela de Vil</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Calculo Psicomotriz I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA, San Ignacion</p>
				<p>10 Créditos</p>
				<p>Turno A</p>
			</article>
		</section>
	</section>

	<section class="content buttons one">
		<a href="##" class="button-icon success">Confirmar <span class="glyphicon glyphicon-ok-circle"></span></a>
	</section>
</section> -->

<!-- <section class="preregister success">
	<p class="info"><span class="glyphicon glyphicon-ok"></span> Prematricula realizada, perteneces al <strong>IV Semestre</strong>, validelo en Registros de su Facultad...</p>
	
	<section class="content normal">
		<header>
			Prematricula Periodo 14A
		</header>
		
		<section>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Algoritmos I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LA CRUZ ROCCA, Marco</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Tendencias Suicidas en la Juevntud Actual Contemporanea I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA Y MONTOYA, Cruela de Vil</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Calculo Psicomotriz I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA, San Ignacion</p>
				<p>10 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Tendencias Suicidas en la Juevntud Actual Contemporanea I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA Y MONTOYA, Cruela de Vil</p>
				<p>5 Créditos</p>
				<p>Turno A</p>
			</article>
			<article class="course">
				<p class="vertical_center"><span class="glyphicon glyphicon-book"></span></p>
				<p>Calculo Psicomotriz I <small>0925412</small></p>
				<p><span class="glyphicon glyphicon-user"></span> Ing. DE LOYOLA, San Ignacion</p>
				<p>10 Créditos</p>
				<p>Turno A</p>
			</article>

			<p class="info">
				<strong>Total de Créditos</strong> 17
			</p>
		</section>
	</section>
</section> -->
