<div id="datos">
    <center>

    <table class="table table-hover flotacarajo span12">
        <thead>
        <tr >
                
                <th class="span1">DNI</th>
                <th class="span1">Cod. Mat.</th>
                <th >Nombres y Apellidos</th>
                <th class="span1">Escuela</th>
                <th class="span1">Operaciones</th>
        </tr>
        </thead>

    <?php
    if ($this->datos)
    {
       foreach ($this->datos as $datos)    
        {
           ?>
            <tr>
                <td><?php echo $datos['pid'];?></td>
                <td><?php echo $datos['uid'];?></td>
                <td><?php echo $datos['last_name0']." ".$datos['last_name1'].", ".$datos['first_name'];?></td>
                <td><?php echo $datos['escid']?></td>
                <td><a href="/admin/password/keychange/uid/<?php echo base64_encode($datos['uid']);?>/eid/<?php echo base64_encode($datos['eid']);?>/oid/<?php echo base64_encode($datos['oid']);?>/pid/<?php echo base64_encode($datos['pid']);?>/escid/<?php echo base64_encode($datos['escid']);?>/subid/<?php echo base64_encode($datos['subid']);?>"><span class="glyphicon glyphicon-pencil"></span>
</a></td>
            </tr>
           <?php
        }
    }
    ?>
            

    </table>
        <div style="clear:both"></div>  
    </center>
</div>