<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-th-list"></span> RENDIMIENTO ACADEMICO');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<body onLoad="CargarSchool()">
<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/report/performance/listcurricula/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table  table-striped  table-condensed">
        <tr>
            <td colspan="2"><b>FACULTAD:</b></td>
            <td colspan="2"><?php 
                        if ( $this->rid=='RC' || $this->rid=='VA' || $this->rid=='PD')
                            {
                             print $this->fm->facid  ;  
                            }
                        if ( $this->rid=='RF')
                            {
                            print $this->fm->facid->setvalue($this->facid);
                             }
                        if ( $this->rid=='DR' && $this->esdirector=='S')
                        {?>
                            <select class='form-control' style='height:35px;width:350px' id="facu"><option><?php echo $this->nom_fac?></option></select>
                            <script type="text/javascript">
                                $("#facu").attr("disabled",true);
                            </script>
                            <?php
                        }
                        ?>
            </td>
            <td class="col-md-4" rowspan="3"><br><center><br><br><a href="/report/" class="btn btn-warning" style='width: 220px;'><i class="glyphicon glyphicon-circle-arrow-left glyphicon-white"></i><i class="glyphicon glyphicon-circle-arrow-left glyphicon-white"></i><i class="glyphicon glyphicon-circle-arrow-left glyphicon-white"></i>&nbsp; Regresar Reportes</a></center></td> 
        </tr>
        <tr>
            <td colspan="2"><b>SELECCIONE ESCUELA:</b></td>
            <td colspan="2"><?php 
            if ( $this->rid=='DR' && $this->esdirector=='S')
            {?>
                <select style='height:35px;width:350px' class='form-control' id="escu" name="escu"><option value="<?php echo $this->escid?>"><?php echo $this->nom_escuela?></option>
                </select>
                <script type="text/javascript">
                    $("#escu").attr("disabled",true);
                </script>
                <?php
            }
            else{

                 // if ( $this->rid=='DC' && $this->esdirector=='S' &&  $this->escid=='2ESTY')
                 //     {    print $this->fm->escid; }

               // else
                 //   { 
                        print $this->fm->escid; 
                   // }
            }
            ?></td>

        </tr>
        <tr>
            <td><b>AÑO:</br></td>
            <td><select id="lanios" class='form-control' name="lanios" style="width: 90px" >
                    <?php 
                    $anio= date('Y');
                    $i=0;
                    for($i = ($anio+1);$i>=2000;$i--){
                        if ($anio==$i) $t = "selected";
                        else $t="";
                        ?>            
                    <option value="<?php echo $i?>"<?php echo $t?>><?php echo $i?></option>
                    <?php }?>
                </select>
            </td>
            <td><b>PERIODO:</b></td>
            <td>
                <select id="periodo_c" name="periodo" class="form-control" style="width: 170px">
                    <option value="">Primero seleccione un año</option>
                </select>
            </td>
        </tr>
    </table>        
    <div style="clear:both" ></div>
</form>    
<div  id="cargadatos_"></div>    
<div style="clear:both" ></div>
<div  id="cargacursos_"></div>   
<script>
    $("#periodo_c").load("/report/performance/lperiods/anio/"+<?php echo $anio?>);
    
    $("#lanios").change(function(){
        var anio = $(this).val();
        $("#periodo_c").load("/report/performance/lperiods/anio/"+anio);
    });

    $("#frmFiltroDoc").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#cargadatos_').html(data);                     
            }
        });
        return false;
    });
    
    $("#facid").change(function () {
        $("#facid option:selected").each(function () {
            facultad = $(this).val();
            $('#escuela').html('<div class="controls"> <img src="/img/spinner.gif" /> Procesando...</div>');
            $.post("/report/performance/listshool/", { facid: facultad }, function(data){
            $('#escuela').html("<select id='escid' name='escid'><option value=''>- Seleccione la Escuela -</option></select>");
            $("#escid").html(data);
            });
             //$('#especialidad').hide();
        });
    });

    
    $("#escid").change(function () {
        $("#escid option:selected").each(function () {
            escuela = $(this).val();
            perid = $("#periodo_c").val();
            $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
            $("#frmFiltroDoc").submit();

         });
    });

    $("#periodo_c").change(function () {
        $("#periodo_c option:selected").each(function () {
            escuela = $("#escid").val();
            perid = $(this).val();
            $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
            $("#frmFiltroDoc").submit();
        });
    });

 function CargarSchool() {
   $('#escuela').html('<div class="controls"> <img src="/img/spinner.gif" /> Procesando...</div>');
             $.post("/report/performance/listshool/", { facid: <?php echo $this->facid; ?> }, function(data){
                 $('#escuela').html("<select id='escid' name='escid'><option value=''>- Seleccione la Escuela -</option></select>");
                 $("#escid").html(data);
            });
 }
 var rid="<?php echo $this->rid?>";
 if (rid == "RF") {
    var facultad="<?php echo $this->facid?>";
    $.post("/report/performance/listshool/", { facid: facultad }, function(data){
        $('#escuela').html("<select id='escid' name='escid'><option value=''>- Seleccione la Escuela -</option></select>");
        $("#escid").html(data);
    });     
 };
</script>