<?php 
if ($this->lper ){ ?>
	<option value=""> Seleccione...</option> 
	<?php
    $str = '';
    foreach ($this->lper  as $perio){
        if ($this->esdirector<>"S") {
            $str = ($this->perid==$perio['perid'])?"selected ":"";
        }
         if ($this->esdirector == "S" && $this->escid == "2ESTY") {
            $str = ($this->perid==$perio['perid'])?"selected ":"";
        }
        ?>
        <option <?php echo $str?> value="<?php echo $perio['perid']?>"><?php echo $perio['perid']." | ".$perio['name']?></option>
        <?php
    }
}else{
    ?>
        <option value="">No tienen ningun periodo</option>
    <?php
}
?> 