<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align: left;"><b>Periodo: </b><?php echo strtoupper($this->perid). " &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Curricula: </b>" .strtoupper($this->curid)?></div>
<div style="text-align:center; margin-top:1%"><b><h3> CUADRO DE MÉRITO <?php echo strtoupper($this->semestre)?> SEMESTRE </h3></b></div>
<table style="width:100%;">                  
    <tr>
        <th class='small'>#</th>
        <th>Apellidos y Nombres</th>
        <th class='small-100'>Cred. Aprobados</th>
        <th class='small-100'>Promedio Ponderado</th>
    </tr>
    <?php $i=0;
        foreach ($this->rep_alumnos as $ra) { $i=$i + 1;?>
            <tr>
                <td style="text-align:center"><?php echo $i; ?>  </td>
                <td><?php echo $ra['nom']?></td>
                <td style="text-align:center"><?php if ($ra['cred_apr']=='') { echo 0; } else { echo $ra['cred_apr'];}?></td>
                <td style="text-align:center"><?php echo round($ra['prom_pon'],2)?></td>
            </tr>
        <?php }?>          
</table>
<?php 
    $html = ob_get_contents(); 
    $mpdf=new mPDF('win-1252','A4','','',15,15,33,18,5,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;
    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer);
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Merito-'.$this->perid.'.pdf','D');
    // $mpdf->Output();
?>