<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align: left;"><b>Periodo: </b><?php echo strtoupper($this->perid)?></div>
<div style="text-align:center; margin-top:1%"><b><h3> REPORTE <?php echo strtoupper($this->superior)?> SUPERIOR </h3></b></div>
<table style="width:100%;" border="1">
    <tr>
        <th class='small'>#</th>
        <th class='small-50'>Código</th>
        <th >Apellidos y Nombres</th>
        <th class='small-50'>Semestre</th>
        <th class='small-50'>Promedio Ponderado</th>
        <th class='small-50'>Créditos Aprobados</th>
    </tr>
    <?php $i=1; 
        foreach ($this->rep_superior as $dr) {?>
        <tr>
            <td style="text-align:center"><?php echo $i ?></td>
            <td style="text-align:center"><?php echo $dr['uid']?></td>
            <td ><?php echo $dr['last_name0'].' '.$dr['last_name1'].', '.$dr['first_name'] ?></td>
            <td style="text-align:center"><?php echo $dr['semid']?></td>
            <td style="text-align:center"><?php echo $dr['prom_pond']?></td>              
            <td style="text-align:center"><?php echo $dr['cred_aprob']?></td>
        </tr>
    <?php $i=$i+1; }?>
</table>
<?php 
    $html = ob_get_contents(); 
    $mpdf=new mPDF('win-1252','A4','','',15,15,33,18,5,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;
    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer);
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Reporte_'.$this->superior.'_Superior_'.$this->perid.'.pdf','D');
    // $mpdf->Output();

?>
        

   
