<?php
$dat = $this->data;
$where['oid']=$dat['oid'];
$where['eid']=$dat['eid'];
$where['escid']=$dat['escid'];

$dbescuela = new Api_Model_DbTable_Speciality();
$escuela = $dbescuela ->_getFilter($where);
$infoescuela = $escuela[0]['name'];
$dat['facid']= $escuela[0]['facid'];
$dbfacultad = new Api_Model_DbTable_Faculty();
$facu = $dbfacultad ->_getOne($dat);
$infonombrefacultad = $facu['name'];

$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
ECHO $header='
<table style="width: 100%;" border="1">
    <tr>
        <th rowspan="2" style="width: 340px; "><img src="/img/header_imprimir.jpg"></th>
        <th style="text-align: center; font-size: 11px;">
        FACULTAD DE '.strtoupper($infonombrefacultad).'<br/>
        ESCUELA DE  '.strtoupper($infoescuela).' 
        </th>        
    </tr>
    <tr>
        <th style="border: 1px solid #000;"> REPORTE '.strtoupper($dat['superior']).' SUPERIOR </th>
    </tr>
</table>

    <tr>
        <td style="text-align: left;">Periodo: '.strtoupper($dat['perid']).'</td>
    </tr>
    <tr>
        <td style="text-align: left;">&nbsp;&nbsp;&nbsp;</td>
    </tr>
   

'    
?>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<table style="width:100%;" border="1">
        <center>
                <tr ></tr>
                <tr>
                  <td >Nro</td>
                  <td >Codigo</td>
                  <td >Apellidos y Nombres</td>
                  <td >Semestre</td>
                  <td >Promedio Pond</td>
                  <td >Creditos Aprobados</td>
                </tr>
          
            <?php $i=1; 
            foreach ($this->rep_superior as $dr) {?>
                <tr>
                    <td><?php echo $i ?></td>
                    <td><?php echo $dr['uid']?></td>
                    <td ><?php echo $dr['last_name0'].' '.$dr['last_name1'].', '.$dr['first_name'] ?></td>
                    <td><?php echo $dr['semid']?></td>
                    <td><?php echo $dr['prom_pond']?></td>              
                      <td><?php echo $dr['cred_aprob']?></td>
                </tr>
              <?php $i=$i+1; }?>
        
        </center>
</table>
<?php 
  $html = ob_get_contents(); 
  $mpdf=new mPDF('win-1252','A4','','',15,15,40);
  $mpdf->SetHTMLHeader($header);
  $mpdf->SetFooter($this->footer);
  ob_end_clean();
  $mpdf -> WriteHTML($html);
  $mpdf->Output($dat['superior'].'Superior-'.$infoescuela.$dat['perid'].'.pdf','D');
?>
        

   
