        <!-- <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  
        <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/jquery/external/base64/jquery.base64.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css"> -->      
        <!-- Texto Enriquecido-->
        <link rel="stylesheet" type="text/css" href="/external/jwysiwyg/jquery.wysiwyg.css">
        <script type="text/javascript" src="/external/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.image.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.link.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.table.js"></script>
        
        <!-- Bootstrap -->
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        <link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">        
        <link rel="stylesheet" type="text/css" href="/css/style.css">

        <script src="/js/jquery-1.11.0.js"></script>
        <script src="/external_library/bootstrap/js/bootstrap.js"></script>
        <script src="/external_library/bootstrap/js/jquery.functions.js"></script>
        <link rel="stylesheet" type="text/css" href="/external_library/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />


<table class="table  table-condensed" style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #D2F6F9;">
    <tr>
        <th rowspan="5" class="col-lg-7">
            <center>
                    <p>                
                    <span style="font-size: 15px; color:#74F7ED;">REPORTE RENDIMIENTO</span><br/>
                    
                    <span style="font-size: 14px">ESCUELA DE FORMACION PROFESIONAL DE 
                        <?php echo $this->nom_escuela;?> 
                    </span><br/>
                    <?php if ($this->especialidad<>""){?>
                        <span style="font-size: 14px">ESPECIALIDAD DE 
                            <?php echo $this->especialidad; ?>
                        </span>
                    <?php 
                    }
                    ?>
                    </center>
        </th>
        <th colspan="6">
            <span style="font-size: 14px"><?php print $this->nomcurricula;?></span>
        </th>        
    </tr>
    <tr>
       
        <th class="col-lg-1">Fecha</th>  
        <th class="col-lg-1"  rowspan="2">
             <a href="/report/performance/printrendimiento/escid/<?php echo base64_encode($this->escid);?>/curid/<?php echo base64_encode($this->curid);?>/perid/<?php echo base64_encode($this->perid)?>" class="btn btn-danger" style='color: #ccc'/>
               <b> <i class="glyphicon glyphicon-list-alt glyphicon-white"></i><br/>Imprimir</b></a>
           
        </th>
    </tr>
    <tr>    
        <td ><span class="label label-info" data-placement="bottom">
        <?php echo date("Y/m/d"); ?></span></td>     
        
    </tr>
</table>

        <table class="table col-lg-11 table-bordered table-condensed table-striped" style="font-size: 12px">
              <tr ></tr>
             <tr style="background: #333; color: #fff;">
              <td ><center><b>SEM</b></center></td>
              <td ><center><b>ASIGNATURAS</b></center></td>
              <td colspan="2"><center><b>APROBADOS</b></center></td>
              <td colspan="2"><center><b>DESAPROBADOS</b></center></td>
              <td colspan="2"><center><b>RETIRADOS</b></center></td>
              <td colspan="2"><center><b>TOTALES</b></center></td>
            </tr>
          
             <tr>
              
              <td ></td>
              <td ></td>
              <td><font color="blue">N°</font></td>
              <td><font color="blue">%</font></td>
              <td><font color="red">N°</font></td>
              <td><font color="red">%</font></td>
              <td><font color="green">N°</font></td>
              <td><font color="green">%</font></td>
              <td>N°</td>
              <td>%</td>
              
            </tr>

            <?php foreach ($this->rep_rendimiento as $dr) {?>
        <tr>  
            <td><b><?php echo $dr['semid']?></b></td>
            <td><b><?php echo $dr['name']?></b></td>
           
              <td><font color="blue"><?php echo $dr['aprobados']?></font></td>
              <td><font color="blue"><?php echo $dr['porc_ap']?></font></td>
              <td><font color="red"><?php echo $dr['desaprobados']?></font></td>              
              <td><font color="red"><?php echo $dr['porc_desap']?></font></td>
              <td><font color="green"><?php echo $dr['retirados']?></font></td>
              <td><font color="green"><?php echo $dr['porc_ret']?></font></td>
              <td><?php echo $dr['totales']?></td>
              <td><?php echo '100'?></td>
                         
        </tr>
      <?php }?>
        
      
        </table>


        


   


