


<div class='row' id='header-info'>
	<div class='col-xs-6  col-md-offset-1 	header-registration-course'>
		<h4 class='text-header-registration'> <span class='glyphicon glyphicon-list' style='color:#1abc9c;'></span> 
		Lista de Modulos
		</h4>
		
	</div>
	<div class="col-md-4">
        <a href="/admin/correctnotes" class='btn btn-default'><span class='glyphicon glyphicon-circle-arrow-left'></span> Regresar</a>
		<a data-toggle="modal" data-target="#modalNewModel" href="/admin/acl/new" class='btn btn-info' ><span class='glyphicon glyphicon-plus-sign'></span> Nuevo</a>
	</div>
</div>
<!-- end header-->
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<table class="table table-bordered">
		  <thead>
		  	<tr>
		        <th class='text-center'>#</th>
		        <th class='text-center'>Nombre</th>
		        <th class='text-center'>Icono</th>
			    <th class='text-center'>Recursos</th>
		        <th class='text-center'>Editar</th>
		        <th class='text-center'>Estado</th>
		    </tr>
		  </thead>
		  <tbody>
				<?php foreach ($this->modules as $key => $module) {?>
					<tr>
						<td><?php echo $key+1?></td>
						<td><?php echo $module['name']?></td>
						<td class="text-center text-muted"><span class='glyphicon glyphicon-<?php echo $module['imgicon']?>'></span></td>
						<td class='text-center'>
							<a href="/admin/acl/listresource/<?php echo base64_encode('mid')?>/<?php echo base64_encode($module['mid'])?>"><span  class='glyphicon glyphicon-plus-sign style-icon-all text-warning'></span></a>
						</td>
						<td class='text-center'>
							<span mid="<?php echo base64_encode($module['mid'])?>" class='glyphicon glyphicon-edit model-edit style-icon-all text-primary' ></span>
						</td>
						<td class="text-center"><?php echo ($module['state']=='A')? "<span class='text-success glyphicon glyphicon-ok-circle style-icon-all'></span>":"<span class='text-danger glyphicon glyphicon-remove-circle style-icon-all'></span>"?></td>
					</tr>
				<?php }?>		  		
		   </tbody>
		</table>
	</div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
</div><!-- /.modal -->
<div class="modal fade" id="modalNewModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
</div><!-- /.modal -->

<script>
	$(".model-edit").click(function(){
		$.ajax({
			url:"/admin/acl/edit",
			data:{mid:$(this).attr('mid')},
			success:function($data){
				$('#myModal').modal('show');
				$('#myModal').html($data);
			},
			error:function ($error) {
				alert('Disculpe, existió un problema');
			}
		});
		return false;
	});


</script>