<table class="table">
	<br>
	<br>
	<?php if($this->aclname){?>
		<tr>
			<th>Lista de Control de Acceso</th>
		</tr>
		<?php foreach ($this->aclname as $aclnm){?>
		<tr class="col-md-4">
			<td class="col-md-5"><?php echo $aclnm[0]['name']?></td>
			<td class="col-md-1"><a href="/admin/acl/delete/reid/<?php echo $aclnm[0]['reid']?>/rid/<?php echo $this->rid?>" class="pull-left" onclick="return confirm('Esta Seguro que desea eliminar!')"><span class="glyphicon glyphicon-remove"></span></a></td>
		</tr>
		<?php }
	}else{?>
		<center><h3>No existen Datos para este Rol......Ingrese nuevos Datos</h3></center>
	<?php }?>
	
</table>