<div class="row">
  	<div class="col-lg-6">
	    <div class="input-group">
      		<input id='search-student' type="text" class="form-control" autofocus>
      		<span class="input-group-btn">
        		<button class="btn btn-turq" type="button"><span class='glyphicon glyphicon-search'></span> Buscar</button>
      		</span>
    	</div><!-- /input-group -->
  	</div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<script type="text/javascript" src="/js/acreditation/services.js"></script>