<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-certificate"></span> CONVALIDACIÓN');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="POST" enctype="application/x-www-form-urlencoded">
    
    <center><table class="table table-hover">
        <thead>
        <tr>
            <th><center>BUSQUEDA DE ALUMNOS</center></th>
        </tr>
        <tr>
            <td>Ingrese Codigo del Alumno que Convalidara</td>
        </tr>
        </thead>
        <tr>
            <td><?php echo $this->form->uid; ?></td>
         </tr>
    </table></center>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>DNI</th>
                <th>Nombre</th>
                <th>Escuela</th>
                <th>Sede</th>
                <th>Agregar curso</th>
                <th>Cursos Convalidados</th>
            </tr>
        </thead>
            <?php
                $perids=$this->perid;
                if ($this->usuario){
                    $i=1;
                    $pid=$this->usuario[0]['pid'];
                    $eid=$this->usuario[0]['eid'];
                    $oid=$this->usuario[0]['oid'];
                    $uid=$this->usuario[0]['uid'];
                    $escid=$this->usuario[0]['escid'];
                    $subid=$this->usuario[0]['subid'];
                    $where['eid']=$eid;
                    $where['oid']=$oid;
                    $where['escid']=$escid;
                    $where['subid']=$subid;
                    $dbescuela = new Api_Model_DbTable_Speciality();
                    $escuela = $dbescuela ->_getOne($where);   
                    $infoescuela = $escuela['name'];
                    $persona = new Api_Model_DbTable_Person();
                    $data['eid']=$eid;
                    $data['pid']=$pid;
                    $list_p = $persona ->_getOne($data);
                    $info2 = $list_p['last_name0']." ".$list_p['last_name1']." ".$list_p['first_name'];
            ?>

              <td><?php echo $uid;?></td>
                <td><?php echo $pid?></td>
                <td><?php echo $info2;?></td>
  
                <td><?php echo $infoescuela;?></td>
                
                <td><?php echo $subid;?></td>
              <td><a class="btn btn-primary form-control" href="#" value= "<?php echo $this->usuario[0]['uid']?>" id="agregados" pid='<?php echo $pid?>' uid='<?php echo $uid?>' escid='<?php echo $escid?>' subid='<?php echo $subid;?>'><center><span class="glyphicon glyphicon-pencil"></span></center></a></td>

               <th><center><a target="black" style="float:right" class="btn btn-primary form-control"  href="/register/validation/print/perid/<?php echo $this->perid ?>/escid/<?php echo $escid ?>/subid/<?php echo $subid ?>/uid/<?php echo $uid ?>/pid/<?php echo $pid ?>  ">Imprimir</a></center></th>
            <?php
    }
    ?>
    </table>
</form>
<div id="carga_periodos_"></div>
<div id="guardar"></div>
<script>
$("#agregados").click(function(){
        var pid=$(this).attr('pid');
        var uid=$(this).attr('uid');
        var escid=$(this).attr('escid');
        var subid=$(this).attr('subid');
        var url = "/register/validation/lcontainer/uid/"+uid+"/subid/"+subid+"/escid/"+escid+"/pid/"+pid+"/nota/<?php echo $this->nota?>/perid/<?php echo $this->perid?>/temp/<?php echo $this->temp?>";
        $("#guardar").load(url);
    });
    $("#uid").keyup(function () {
        var vuid = $(this).val();
        if (isNaN(vuid))
        {
          $(this).val("");
        }
    });
</script>


