<?php
if ($this->data) {  ?>
    <option value="">Seleccione curso</option>
    <?php
    foreach ($this->data as $i => $datas) { ?>
        <option value="<?php echo $datas['courseid'].'|'.$datas['semid'].'|'.$datas['credits'].'|'.$datas['curid'].'|'.$datas['type']?>"><?php echo $datas['courseid']." | ".$datas['name']?></option>
    <?php
    }
}
else{   ?>
    <option value="">No tiene cursos</option>
<?php
}
?>
