<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-certificate"></span> CONVALIDACIÓN');?>
<?php $this->placeholder('Btnnav')->append('<a href="/rfacultad" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<section class="container">
    <h6 class='text-muted text-center'>Para BUSCAR presione <b>ENTER</b> o click en <span class='glyphicon glyphicon-search'></span> Buscar </h6>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2 col-md-offset-2">
                <b class='text-info'>Ingrese el Código del Alumno: </b>
            </div>
            <div class="col-md-2">
                <input type="text" name="uid" id="uid" class="form-control" maxlength="10" onkeypress="return soloNumero(event)">
            </div>
            <div class="col-md-2 col-md-offset-1">
                <button id='search' class='btn btn-success'><span class='glyphicon glyphicon-search'></span> Buscar</button>
            </div>
        </div>
    </div>
    <div id='loadData'></div>
</section>
<script>
    function soloNumero(e){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = "0123456789";
        especiales = [8,37,39,46];
        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }
        if(letras.indexOf(tecla)==-1 && !tecla_especial)
        return false;
    };
    $(function(){
        $("#search").on('click', function(){
            var uid=$("#uid").val();
            var count=uid.length;
            if (count==10) {
                var url="/register/validation/addcourse/uid/"+$.base64.encode(uid);
                $("#loadData").html("<br><center><img src='/img/spinner.gif'/> Cargando...</center>");
                $("#loadData").load(url);
            }
            else{
                alert("Ingrese un Código válido");
                $('#uid').focus();
            }
        });

        $("#uid").keypress(function (e) {
            if(e == 13 || e.which==13 || e.which==0){
                var cod = $('#uid').val();
                count=cod.length;

                if (count==10 || count==0) {
                    var uid=$("#uid").val();
                    var url="/register/validation/addcourse/uid/"+$.base64.encode(uid);
                    $("#loadData").html("<br><center><img src='/img/spinner.gif'/> Cargando...</center>");
                    $("#loadData").load(url);

                }
                else{
                    alert("Ingrese un Código válido");
                    $('#uid').focus();
                }
            }
        });
    });
</script>