<?php
if ($this->data) {
    if ($this->msg!='1') {   ?>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4 text-center">Curso <br>
                    <select name="courseid" id="courseid" class='form-control'>
                        <option value="">- Seleccione un Curso-</option>
                        <?php
                            foreach ($this->data as $i => $datas) { ?>
                                <option value="<?php echo $datas['courseid'].'|'.$datas['semid'].'|'.$datas['credits'].'|'.$datas['curid'].'|'.$datas['type']?>"><?php echo $datas['courseid']." | ".$datas['name']?></option>
                            <?php
                            }
                        ?>
                    </select>
                </div>
                <div class="col-md-2 text-center">Nota <br>
                    <div style='width:60px; margin-left:18px;'>
                        <input id='nota' name='nota' type="text" class='form-control text-center' maxlength="2">
                    </div>
                </div>
                <div class="col-md-6 text-center">Resolución <br>
                    <input id='resolution' name='resolution' type="text" class="form-control">
                </div>
            </div>
            <input id='pid' class='hidden' type="text" name="pid" value="<?php echo base64_encode($this->pid)?>">
            <input id='ofuid' class='hidden' type="text" name="uid" value="<?php echo base64_encode($this->uid)?>">
            <input id='escid' class='hidden' type="text" name="escid" value="<?php echo base64_encode($this->escid)?>">
            <input id='subid' class='hidden' type="text" name="subid" value="<?php echo base64_encode($this->subid)?>">
            <input id='perid' class='hidden' type="text" name="perid" value="<?php echo base64_encode($this->perid)?>">
        </div>
    <?php
    }
    else{   ?>
        <br>
        <div class="row">
            <div class="alert alert-info text-center col-md-4 col-md-offset-4"><span class='glyphicon glyphicon-info-sign'></span> Hubo problemas al cargar los cursos...</div>
        </div>
    <?php
    }
}
else{   ?>
    <br>
    <div class="row">
        <div class="alert alert-info text-center col-md-4 col-md-offset-4"><span class='glyphicon glyphicon-info-sign'></span> No tiene cursos para convalidar</div>
    </div>
<?php
}
?>
<script type="text/javascript" src="/js/notes/jquery.jstepper.js"></script>
<script type="text/javascript">
$("#nota").jStepper({minValue:-3, maxValue:20, minLength:2});
$(function(){
    $("#savecoursec").on('click', function(){
        var valcourseid=$("#courseid").val();
        var valnota=$("#nota").val();
        var valresolution=$("#resolution").val();

        if (!valcourseid) {
            alert("Seleccione un Curso.");
            $("#courseid").focus();
            return false;
        };

        if (!valnota) {
            alert("Ingrese una Nota.");
            $("#courseid").focus();
            return false;
        };

        if (!valresolution) {
            alert("Ingrese una Resolución.");
            $("#courseid").focus();
            return false;
        };

        var valcourseid = valcourseid.split('|');

        var pid = $("#pid").val();
        var uid = $("#ofuid").val();
        var escid = $("#escid").val();
        var subid = $("#subid").val();
        var perid = $("#perid").val();
        var courseid = valcourseid[0];
        var semid = valcourseid[1];
        var credits = valcourseid[2];
        var curid = valcourseid[3];
        var type_rate = valcourseid[4];
        var nota = valnota;
        var resolution = valresolution;

        var params = {    'pid': pid,
                          'uid': uid,
                        'escid': escid,
                        'subid': subid,
                        'perid': perid,
                        'curid': $.base64.encode(curid),
                         'nota': $.base64.encode(nota),
                        'semid': $.base64.encode(semid),
                   'resolution': $.base64.encode(resolution),
                     'courseid': $.base64.encode(courseid),
                      'credits': $.base64.encode(credits),
                    'type_rate': $.base64.encode(type_rate)
                     };

        $.ajax({
            type: 'POST',
            url : '/register/validation/save/',
            data: params,
            success: function(data) {
                if (data.status==true) {
                    $("#addCourseModal").modal('hide');
                };
            }
        });

    });
});
</script>