<?php
    $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
    include_once($dir);
    ob_start();
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">

<div>
    <div style="text-align:left; font-size:12px;"><b>Código: </b><?php echo strtoupper($this->uid)?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <b>Alumno: </b><?php echo strtoupper($this->person['last_name0']." ".$this->person['last_name1'].", ".$this->person['first_name'])?>
    </div>
</div><br><br>
<div style="text-align: center; font-size:16px;margin-top:10px"><b> REGISTRO DE NOTAS - PERIODO <?php echo strtoupper($this->perid)?> </b></div><br><br>

<table style="width:100%">
    <tr>
        <th>#</th>
        <th>Currícula</th>
        <th>Código</th>
        <th>Curso</th>
        <th>Turno</th>
        <th>Resolución</th>
        <th>Nota</th>
    </tr>
    <?php
    foreach ($this->cursosconvalidados as $a => $datas) {   ?>
        <tr>
            <td><center><?php echo $a+1?></center></td>
            <td><center><?php echo $datas['curid']?></center></td>
            <td><center><?php echo $datas['courseid']?></center></td>
            <td><?php echo $datas['namecourse']?></td>
            <td><center><?php echo $datas['turno']?></center></td>
            <td><?php echo $datas['document_auth']?></td>
            <td><center><?php echo $datas['notafinal']?></center></td>
        </tr>
    <?php
    }
    ?>
</table>
<?php
    $html = ob_get_contents();

    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');

    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Registro_Notas_'.$this->perid.'_'.$this->uid.'.pdf','D');
    // $mpdf -> Output();
?>

