<form id="<?php echo $this->form->getName();?>" name="<?php echo $this->form->getName();?>" action="<?php echo $this->form->getAction();?>"method="Post" enctype="application/x-www-form-urlencode">
	<table class="table  table-striped  table-condensed">
        <tr>
            <td colspan="4" ><br>
            <div style='height:45px;' class='alert alert-success'><CENTER><h4><b>MODIFICAR NOTA</b></h4></CENTER></div> 
           </td>
           <td colspan="2" ><br>
            <a style="float:right" class="btn btn-danger" href="/register/validation/">Cancelar</a>
           </td>

           
        </tr>
        
        <tr>
            <td colspan="1"><b>Codigo Alumno:</b></td>
            <td colspan="5"><div style='width: 200px'><?php echo $this->uid?>
            </td>
           
        </tr>
        <tr>
            <td colspan="1"><b>Currícula:</b></td>
            <td colspan="5"><div style='width: 200px'><?php echo $this->curid?></td>

        </tr>
        <tr>
            <td colspan="1"><b>Curso:</b></td>
            <td colspan="5"><div style='width: 200px'><?php echo $this->courseid?></td>

        </tr>
        <tr>
            <td><b>Nota Final:</br></td>
            <td><div style='width: 200px'><?php echo $this->form->notafinal?>
            </td>
            <td><b>Resolucion:</b></td>
            <td><div style='width: 200px'><?php echo $this->form->document_auth?>                
            </td>
        </tr>
        <tr>
            <td colspan="6">
            <center><?php echo $this->form->Guardar?><center>
            </td>
        </tr>
    </table>  



</form>
<script>
    $("#notafinal").keyup(function()
    {
        var v = $(this).val();
        if (isNaN(v))
        {
            $("#notafinal").val("");
            $(".msg").html("* solo se permite números");
        }
        else
        {
            if ((v > 20 || v < 1))
            {
                $("#notafinal").val("");
                $(".msg").html("* Ingrese de 0 a 20");
            }
            else
            {
                $(".msg").html("");
            }
        }

    });

    $("#notafinal").blur(function()
    {
        var vnota = $(this).val();
        if (vnota<11 && vnota>1)
        {
            $("#notafinal").focus();
            $("#notafinal").val("");
            $(".msg").html("* CONVALIDACION: notas aprobatorias");
        }
    });

    $("#document_auth").keyup(function()
    {
        var r = $(this).val();
        $("#document_auth").val(r.toUpperCase());
    });
</script>

<script>
var total_letras = 2;
$('#notafinal').keyup(function() 
{
    var longitud = $(this).val().length;
    var resto = total_letras - longitud;
    $('#numero').html(resto);
    if(resto <= 0){
        $('#notafinal').attr("maxlength", 2);
    }
});
</script>

