<?php 
    $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-lock"></span> BLOQUEO Y DESBLOQUEO DE CÓDIGOS');
    $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');
?>
<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltro" action="/bienestar/lockandunlock/getuser/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
	<table class="table table-condensed table-striped">
	    <tr>
	        <td class='col-lg-5'><p style='float:right; font-size:13px'>Código del Alumno: </p></td>
	        <td class='col-lg-3'><div style='width: 200px'><?php echo $this->fm->uid ?></td>
            <td class='col-lg-3'><?php echo $this->fm->Buscar?></td>
	    </tr>
	</table>
</form>
<div id="cargadata"></div>

<script>
    $("#uid").keypress(function (e) {
            var codi =  $(this).val();
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#uid').val();
            count=codi.length;
            if (count==10 || count==0)
            {
                $('#cargadata').html("<img src='/img/spinner.gif'> Cargando....");
                $("#frmFiltro").submit();
            }
            else
            {
                alert("Ingrese un codigo valido");
                $('#uid').val('');
            }
        }
    });
    
    $("#frmFiltro").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#cargadata').html(data);                                 
            }
        }); 
        return false;
    });

    $("#Buscar").click(function(){
        var uid =  $('#uid').val();
        url="/bienestar/lockandunlock/getuser/uid/"+uid;
        $("#cargadata").load(url);  
    })
    
    function validNumber(e) {
    var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
    }    
</script>