<style type="text/css">
	.nota{
		width: 53px;
		text-align: center;
	}
	span{
		cursor: pointer;
	}
	.error-input
	{
		background-color: red;
	}
</style>
<script type="text/javascript">

	var $partial = <?php echo $this->partial?>;
	var $assist = {};
	var $indicefa = -1;
	var $tr = null;
	/********************retirar-alumno*******************************/
	function retired_assist (obj) {
		var $icon = $(obj);
		var $parent = $(obj).parent();
		var $parent = $parent.parent();
		var $action = $(obj).attr('action');

		var $index = $icon.attr('index');

		if($action == "0")
		{
			$icon.removeClass('glyphicon-eye-open');
			$icon.addClass('glyphicon-eye-close');
			$parent.css('color','#FC4141');
        	$icon.attr("action","1");
		}
		else{

			$icon.removeClass('glyphicon-eye-close');
			$icon.addClass('glyphicon-eye-open');
			$parent.css('color','#000');
        	$icon.attr("action","0");
		}

		$assist = {};
		$assist[$.base64.encode('courseid')]=$.base64.encode($.trim($parent.attr('courseid')));
		$assist[$.base64.encode('curid')]=$.base64.encode($.trim($parent.attr('curid')));
		$assist[$.base64.encode('turno')]=$.base64.encode($.trim($parent.attr('turno')));
		$assist[$.base64.encode('regid')]=$.base64.encode($.trim($parent.attr('regid')));
		$assist[$.base64.encode('uid')]=$.base64.encode($.trim($parent.attr('uid')));
		$assist[$.base64.encode('pid')]=$.base64.encode($.trim($parent.attr('pid')));
		$assist[$.base64.encode('perid')]=$.base64.encode($.trim($parent.attr('perid')));
		$assist[$.base64.encode('escid')]=$.base64.encode($.trim($parent.attr('escid')));
		$assist[$.base64.encode('subid')]=$.base64.encode($.trim($parent.attr('subid')));

		$($parent[0].children).each(function(){
	        if(this.firstElementChild != null){
	            if(this.firstElementChild.nodeName == 'SPAN'){
	                
                    $checkbox= $(this.firstElementChild);
                    $name = $checkbox.attr("name");
                    
                    if ($action == '0') {
                    	$checkbox.attr('disabled',true);
                    	$checkbox.removeClass();
                    	$checkbox.addClass('inputassist  glyphicon glyphicon-registration-mark');
                    	$checkbox.attr('assistance','');
                		$assist[$.base64.encode($name)]=$.base64.encode("R");
                    }
                    else
                    {
                		$assist[$.base64.encode($name)]=$.base64.encode("");
                    	$checkbox.attr('disabled',false);
                    	$checkbox.removeClass();
                    	$checkbox.addClass('inputassist  glyphicon glyphicon-unchecked');
                    	$checkbox.attr('assistance','');
                    	// $checkbox
                    }
	            }
	        }
    	});

		result = "";
	    for (var prop in $assist ) {
	        result += '' + prop + '/' + $assist[prop]  + '/'; 
	    }
    	result = result.substring(0, result.length-1);
    	result = result + '/' + $.base64.encode('partial') + '/' + $.base64.encode($partial);
    	var $url = '/assistance/student/savefile/' + result;
    	$.ajax({
	        url:$url,
	        success:function($data){
	        	// alert($data);
	                if ($data.status == true) {
	                	if ($action == '0'){

	                	}
	                	if ($action == '1'){

	                	}
	                }
	        },
	        error:function($data){
	                //Pintar el error
	                alert($data.status)
	        }
	    });
    	$assist = {};
    	return true;
	}
	/*****************************asigner-asistencia***************************************/
	function assignet_assistance($obj){

		var $value = $($obj).attr('value');
		var $index = $($obj).attr('index');
		var $indexall = $($obj).attr('indexall');
		var $value_1 = $("#index-"+$indexall+"-"+$index).attr("assistance");

		/******removed class****/
		if ($value_1=="A"){
			$("#index-"+$indexall+"-"+$index).removeClass("glyphicon-ok-circle");
			$("#index-"+$indexall+"-"+$index).removeClass("text-primary");

		}
		if ($value_1=="F"){
			$("#index-"+$indexall+"-"+$index).removeClass("glyphicon-remove-circle");
			$("#index-"+$indexall+"-"+$index).removeClass("text-danger");
		}
		if ($value_1=="T"){
			$("#index-"+$indexall+"-"+$index).removeClass("glyphicon-copyright-mark");
			$("#index-"+$indexall+"-"+$index).removeClass("text-success");
		}
		if ($value_1==" "){
			$("#index-"+$indexall+"-"+$index).removeClass("glyphicon-unchecked");
		}
		/*********add class*********/

		if ($value == "A"){
			$("#index-"+$indexall+"-"+$index).addClass("glyphicon-ok-circle");
			$("#index-"+$indexall+"-"+$index).addClass("text-primary");
			$("#index-"+$indexall+"-"+$index).attr("data-content","<h5><span class='assignet-assist glyphicon glyphicon-remove-circle text-danger' value='F' index='"+$index+"' indexall='"+$indexall+"'  onclick='assignet_assistance(this);'> Falto</span></h5><h5><span class='assignet-assist glyphicon glyphicon-copyright-mark text-success' value='T' index='"+$index+"' indexall='"+$indexall+"' onclick='assignet_assistance(this);'> Tarde</span></h5>");

		}
		if ($value == "F"){
			$("#index-"+$indexall+"-"+$index).addClass("glyphicon-remove-circle");
			$("#index-"+$indexall+"-"+$index).addClass("text-danger");
			$("#index-"+$indexall+"-"+$index).attr("data-content","<h5><span class='assignet-assist glyphicon glyphicon-ok-circle text-primary' value='A' index='"+$index+"' indexall='"+$indexall+"'  onclick='assignet_assistance(this);'> Asistio</span></h5><h5><span class='assignet-assist glyphicon glyphicon-copyright-mark text-success' value='T' index='"+$index+"' indexall='"+$indexall+"' onclick='assignet_assistance(this);'> Tarde</span></h5>");

		}
		if ($value == "T"){
			$("#index-"+$indexall+"-"+$index).addClass("glyphicon-copyright-mark");
			$("#index-"+$indexall+"-"+$index).addClass("text-success");
			$("#index-"+$indexall+"-"+$index).attr("data-content","<h5><span class='assignet-assist glyphicon glyphicon-ok-circle text-primary' value='A' index='"+$index+"' indexall='"+$indexall+"'  onclick='assignet_assistance(this);'> Asistio</span></h5><h5><span class='assignet-assist glyphicon glyphicon-remove-circle text-danger' value='F' index='"+$index+"' indexall='"+$indexall+"' onclick='assignet_assistance(this);'> Falto</span></h5>");

		}

		/**************assign value****************/
		$("#index-"+$indexall+"-"+$index).attr("assistance",$value);
		$("#index-tr-"+$index).attr('edition',true);
		$("#save_assistance").attr('disabled',false);
		$(".popover").remove();
	}
	/****************asignar por columna**************************/
	function assigned_all_assistance($objet){

	}
	/***************************guardar-archivo*****************************************/
	function savefile(){
		var result = '';
		var resuldecode  = '';

		for (var prop in $assist ) {
            result += '' + prop + '/' + $assist[prop]  + '/'; 
        }  

        result = result.substring(0, result.length-1);
        result = result + '/' + $.base64.encode('partial') + '/' + $.base64.encode($partial);
    	var $url = '/assistance/student/savefile/' + result;
    	$.ajax({
        	url:$url,
	        async:false,
	        success:function($data){

	                if ($data.status == true) {
	                	$("#save_assistance").attr('disabled',true);
	                }
	                else{

	                }
	                $tr.attr('edition',false);
	        },
	        error:function($data){
	                //Pintar el error
	                alert("error");
	                $tr.attr('edition',false);

	        }
        });

    	$assist = {};
    	return true;
	}

	$(document).ready(function() {


		//*********************seleccionar todo***********************///

		$(".student-assist .selectedall").click(function (){
			$(this).attr('checked',true);
			var $index_all	=	$(this).attr('index-all');
			var $indexcefa	=	-2;

			var $checkedall = $(this);

			$("#talassist tr").each(function (){
				$indexcefa = parseInt($indexcefa)-1;
				$tr = $(this);
				$action = $tr.attr('edition');

					$($tr[0].children).each(function (){

						if (this.firstElementChild != null) {
                            if(this.firstElementChild.nodeName == 'SPAN'){

                            	$checkbox = $(this.firstElementChild);
                            	$indexall = $checkbox.attr('indexall');
                            	$disabled = $checkbox.attr('disabled');
                            	$assistance = $checkbox.attr('assistance');
                            	// $checkbox.attr =
                            	if ($checkedall.is(':checked')) {
	                            	if ($indexall == $index_all && $disabled != 'disabled' ) {
										$tr.attr('edition',true);
										$checkbox.removeClass();
										$checkbox.addClass('inputassist glyphicon glyphicon-ok-circle text-primary');
	                            		$checkbox.attr('assistance','A');
	                            	}
                            	}
                            	else{
                            		if ($indexall == $index_all && $disabled != 'disabled' ) {
										$tr.attr('edition',true);
										$checkbox.removeClass();
										$checkbox.addClass('inputassist glyphicon glyphicon-unchecked');
	                            		$checkbox.attr('assistance','');

	                            	}
                            	}
							}
						}

					});
				
			});
			$("#save_assistance").attr('disabled',false);
		});

		/*********************evento-para-guardar***************************/

			$("#save_assistance").click(function(){
			$indexcefa = -2;
			var $to_send = false;

			$("#talassist tr").each(function (){
				$indexcefa = parseInt($indexcefa)-1;
				$tr = $(this);
				$action = $tr.attr('edition');

				if ($action == 'true') {

					if ($to_send == false) {
						$to_send = true;
						$("#toserver").modal('show');
					}

					$assist = {};
					$assist[$.base64.encode('courseid')]=$.base64.encode($.trim($tr.attr('courseid')));
					$assist[$.base64.encode('curid')]=$.base64.encode($.trim($tr.attr('curid')));
					$assist[$.base64.encode('turno')]=$.base64.encode($.trim($tr.attr('turno')));
					$assist[$.base64.encode('regid')]=$.base64.encode($.trim($tr.attr('regid')));
					$assist[$.base64.encode('uid')]=$.base64.encode($.trim($tr.attr('uid')));
					$assist[$.base64.encode('pid')]=$.base64.encode($.trim($tr.attr('pid')));
					$assist[$.base64.encode('perid')]=$.base64.encode($.trim($tr.attr('perid')));
					$assist[$.base64.encode('escid')]=$.base64.encode($.trim($tr.attr('escid')));
					$assist[$.base64.encode('subid')]=$.base64.encode($.trim($tr.attr('subid')));

					$information = false;
					$($tr[0].children).each(function (){

						if (this.firstElementChild != null) {
                            if(this.firstElementChild.nodeName == 'SPAN'){
                            	$checkbox = $(this.firstElementChild);
                            	$name = $checkbox.attr('name');
                            	$value = $checkbox.attr('assistance');

                            	if ($value != '') {
                            		$information = true;
                            		$assist[$.base64.encode($name)] = $.base64.encode($.trim($value));
                            	}
							}
						}

					});

					if ($information) {
						savefile();
					}
				}
			});

			if ($to_send == true) {
				$("#toserver").modal('hide');
				$("save_assistance").attr('disabled',true);
			}	
		});	
	$(".inputassist").popover();
	$(".div-tooltip").tooltip();
	});

	/*****************************/

</script>	
<?php 
	$infocourse = $this->infocurso;
	print_r($infocourse);
?>

<div class='row'>
	<div class='col-xs-12 col-sm-6 col-md-8'>
		<h4> <span class='glyphicon glyphicon-calendar'></span> Asistencia <?php echo $infocourse['name']?> Turno <?php echo $this->turno?></h4>
	</div>
	<div class="col-md-4">
		<buttom  class='btn btn-info ' id='save_assistance' disabled ><span class='glyphicon glyphicon-save'></span> Guardar</buttom>
		
		<buttom  class='btn btn-danger' id='closure-assistance' ><span class='glyphicon  glyphicon-log-out'></span> Cerrar Asistencia</buttom>
	</div>
</div>

<?php $partial = $this->partial;
if ($this->infoassist) { ?>
<div class='row student-assist' >
	<div class='col-md-12'>
	<table class='table' id='talassist'>
		<thead>
			<tr>
				<th>#</th>
				<th>Apellidos y Nombres</th>
					<th class='success'>1
						<div class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-1' index-all='1'></th>
						</div>
					</th>
					<th class='success'>2
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-2' index-all='2'></th>
						</div>
					</th>
					<th class='success'>3
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-3' index-all='3'></th>
						</div>
					</th>
					<th class='success'>4
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-4' index-all='4'></th>
						</div>
					</th>
					<th class='success'>5
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-5' index-all='5'></th>
						</div>
					</th>
					<th class='success'>6
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-6' index-all='6'></th>
						</div>
					</th>
					<th class='success'>7
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-7' index-all='7'></th>
						</div >
					</th>
					<th class='success'>8
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-8' index-all='8'></th>
						</div>
					</th>
					<th class='success'>9
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-9' index-all='9'></th>
						</div>
					</th>
					<th class='success'>10
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-10' index-all='10'></th>
						</div>
					</th>
					<th class='success'>11
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-11' index-all='11'></th>
						</div>
					</th>
					<th class='success'>12
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-12' index-all='12'></th>
						</div>
					</th>
					<th class='success'>13
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-13' index-all='13'></th>
						</div>
					</th>
					<th class='success'>14
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-14' index-all='14'></th>
						</div>
					</th>
					<th class='success'>15
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-15' index-all='15'></th>
						</div>
					</th>
					<th class='success'>16
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-16' index-all='16'></th>
						</div>
					</th>
					<th class='success'>17
						<div  class ='div-tooltip' data-toggle="tooltip" title="Asignar Asistio a Todo">
							<input class='selectedall' type='checkbox' name='select-all-17' index-all='17'></th>
						</div>
					</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->infoassist as $key => $register) { ?>
			<tr id='index-tr-<?php echo $key+1?>'
				courseid='<?php echo $register['coursoid']?>'
				curid='<?php echo $register['curid']?>'
				turno='<?php echo $register['turno']?>'
				perid='<?php echo $register['perid']?>'
				escid='<?php echo $register['escid']?>'
				subid='<?php echo $register['subid']?>'
				regid='<?php echo $register['regid']?>'
				uid='<?php echo $register['uid']?>'
				pid='<?php echo $register['pid']?>'
                edition="false"
                style="color:<?php echo ($register['a_sesion_17'] == 'R' || $register['a_sesion_34'] == 'R' )?'#FC4141':'#000'; ?>;"
				>
			<td><?php echo $key+1?> <span  class='text-success glyphicon'></span></td>
			<td><?php echo $register['name']?></td>

			<?php if ($partial==1) { ?>
				<td>
					<?php switch ($register['a_sesion_1']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_1'] != 'R')?$register['a_sesion_1']:''; ?>"
							action='checkbox' name='a_sesion_1' index='<?php echo $key+1?>' indexall='1'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_1'] != 'R')?$register['a_sesion_1']:''; ?>"
							   	id='index-1-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_1' index='<?php echo $key+1?>' indexall='1' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_1'] != 'R')?$register['a_sesion_1']:''; ?>"
							action='checkbox' name='a_sesion_1' index='<?php echo $key+1?>' indexall='1'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_1'] != 'R')?$register['a_sesion_1']:''; ?>"
							action='checkbox' name='a_sesion_1' index='<?php echo $key+1?>' indexall='1'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_1'] != 'R')?$register['a_sesion_1']:''; ?>"
							action='checkbox' name='a_sesion_1' index='<?php echo $key+1?>' indexall='1'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- ******************sesion 2************** -->
				<td>
					<?php switch ($register['a_sesion_2']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_2'] != 'R')?$register['a_sesion_2']:''; ?>"
							action='checkbox' name='a_sesion_2' index='<?php echo $key+1?>' indexall='2'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_2'] != 'R')?$register['a_sesion_2']:''; ?>"
							   	id='index-2-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_2' index='<?php echo $key+1?>' indexall='2' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_2'] != 'R')?$register['a_sesion_2']:''; ?>"
							action='checkbox' name='a_sesion_2' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_2'] != 'R')?$register['a_sesion_2']:''; ?>"
							action='checkbox' name='a_sesion_2' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_2'] != 'R')?$register['a_sesion_2']:''; ?>"
							action='checkbox' name='a_sesion_2' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *********************sesion 3*************** -->
				<td>
					<?php switch ($register['a_sesion_3']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_3'] != 'R')?$register['a_sesion_3']:''; ?>"
							action='checkbox' name='a_sesion_3' index='<?php echo $key+1?>' indexall='3'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_3'] != 'R')?$register['a_sesion_3']:''; ?>"
							   	id='index-3-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_3' index='<?php echo $key+1?>' indexall='3' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_3'] != 'R')?$register['a_sesion_3']:''; ?>"
							action='checkbox' name='a_sesion_3' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_3'] != 'R')?$register['a_sesion_3']:''; ?>"
							action='checkbox' name='a_sesion_3' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_3'] != 'R')?$register['a_sesion_3']:''; ?>"
							action='checkbox' name='a_sesion_3' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				
				<!-- *******************sesion-4************* -->
				<td>
					<?php switch ($register['a_sesion_4']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_4'] != 'R')?$register['a_sesion_4']:''; ?>"
							action='checkbox' name='a_sesion_4' index='<?php echo $key+1?>' indexall='4'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_4'] != 'R')?$register['a_sesion_4']:''; ?>"
							   	id='index-4-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_4' index='<?php echo $key+1?>' indexall='4' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_4'] != 'R')?$register['a_sesion_4']:''; ?>"
							action='checkbox' name='a_sesion_4' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_4'] != 'R')?$register['a_sesion_4']:''; ?>"
							action='checkbox' name='a_sesion_4' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_4'] != 'R')?$register['a_sesion_4']:''; ?>"
							action='checkbox' name='a_sesion_4' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Falto</span></h5>'
							
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-5************* -->
				<td>
					<?php switch ($register['a_sesion_5']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_5'] != 'R')?$register['a_sesion_5']:''; ?>"
							action='checkbox' name='a_sesion_5' index='<?php echo $key+1?>' indexall='5'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_5'] != 'R')?$register['a_sesion_5']:''; ?>"
							   	id='index-5-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_5' index='<?php echo $key+1?>' indexall='5' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_5'] != 'R')?$register['a_sesion_5']:''; ?>"
							action='checkbox' name='a_sesion_5' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_5'] != 'R')?$register['a_sesion_5']:''; ?>"
							action='checkbox' name='a_sesion_5' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_5'] != 'R')?$register['a_sesion_5']:''; ?>"
							action='checkbox' name='a_sesion_5' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				
				<!-- *******************sesion-6************* -->

				<td>
					<?php switch ($register['a_sesion_6']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_6'] != 'R')?$register['a_sesion_6']:''; ?>"
							action='checkbox' name='a_sesion_6' index='<?php echo $key+1?>' indexall='6'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_6'] != 'R')?$register['a_sesion_6']:''; ?>"
							   	id='index-6-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_6' index='<?php echo $key+1?>' indexall='6' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_6'] != 'R')?$register['a_sesion_6']:''; ?>"
							action='checkbox' name='a_sesion_6' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_6'] != 'R')?$register['a_sesion_6']:''; ?>"
							action='checkbox' name='a_sesion_6' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_6'] != 'R')?$register['a_sesion_6']:''; ?>"
							action='checkbox' name='a_sesion_6' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>

				<!-- *******************sesion-7************* -->

				<td>
					<?php switch ($register['a_sesion_7']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_7'] != 'R')?$register['a_sesion_7']:''; ?>"
							action='checkbox' name='a_sesion_7' index='<?php echo $key+1?>' indexall='7'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_7'] != 'R')?$register['a_sesion_7']:''; ?>"
							   	id='index-7-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_7' index='<?php echo $key+1?>' indexall='7' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_7'] != 'R')?$register['a_sesion_7']:''; ?>"
							action='checkbox' name='a_sesion_7' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_7'] != 'R')?$register['a_sesion_7']:''; ?>"
							action='checkbox' name='a_sesion_7' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_7'] != 'R')?$register['a_sesion_7']:''; ?>"
							action='checkbox' name='a_sesion_7' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-8************* -->

				<td>
					<?php switch ($register['a_sesion_8']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_8'] != 'R')?$register['a_sesion_8']:''; ?>"
							action='checkbox' name='a_sesion_8' index='<?php echo $key+1?>' indexall='8'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_8'] != 'R')?$register['a_sesion_8']:''; ?>"
							   	id='index-8-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_8' index='<?php echo $key+1?>' indexall='8' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_8'] != 'R')?$register['a_sesion_8']:''; ?>"
							action='checkbox' name='a_sesion_8' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_8'] != 'R')?$register['a_sesion_8']:''; ?>"
							action='checkbox' name='a_sesion_8' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_8'] != 'R')?$register['a_sesion_8']:''; ?>"
							action='checkbox' name='a_sesion_8' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-9************* -->

				<td>
					<?php switch ($register['a_sesion_9']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_9'] != 'R')?$register['a_sesion_9']:''; ?>"
							action='checkbox' name='a_sesion_9' index='<?php echo $key+1?>' indexall='9'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_9'] != 'R')?$register['a_sesion_9']:''; ?>"
							   	id='index-9-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_9' index='<?php echo $key+1?>' indexall='9' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_9'] != 'R')?$register['a_sesion_9']:''; ?>"
							action='checkbox' name='a_sesion_9' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_9'] != 'R')?$register['a_sesion_9']:''; ?>"
							action='checkbox' name='a_sesion_9' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_9'] != 'R')?$register['a_sesion_9']:''; ?>"
							action='checkbox' name='a_sesion_9' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-10************* -->

				<td>
					<?php switch ($register['a_sesion_10']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_10'] != 'R')?$register['a_sesion_10']:''; ?>"
							action='checkbox' name='a_sesion_10' index='<?php echo $key+1?>' indexall='10'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_10'] != 'R')?$register['a_sesion_10']:''; ?>"
							   	id='index-10-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_10' index='<?php echo $key+1?>' indexall='10' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_10'] != 'R')?$register['a_sesion_10']:''; ?>"
							action='checkbox' name='a_sesion_10' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_10'] != 'R')?$register['a_sesion_10']:''; ?>"
							action='checkbox' name='a_sesion_10' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_10'] != 'R')?$register['a_sesion_10']:''; ?>"
							action='checkbox' name='a_sesion_10' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-11************* -->

				<td>
					<?php switch ($register['a_sesion_11']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_11'] != 'R')?$register['a_sesion_11']:''; ?>"
							action='checkbox' name='a_sesion_11' index='<?php echo $key+1?>' indexall='11'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_11'] != 'R')?$register['a_sesion_11']:''; ?>"
							   	id='index-11-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_11' index='<?php echo $key+1?>' indexall='11' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_11'] != 'R')?$register['a_sesion_11']:''; ?>"
							action='checkbox' name='a_sesion_11' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_11'] != 'R')?$register['a_sesion_11']:''; ?>"
							action='checkbox' name='a_sesion_11' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_11'] != 'R')?$register['a_sesion_11']:''; ?>"
							action='checkbox' name='a_sesion_11' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>

				<!-- *******************sesion-12************* -->

				<td>
					<?php switch ($register['a_sesion_12']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_12'] != 'R')?$register['a_sesion_12']:''; ?>"
							action='checkbox' name='a_sesion_12' index='<?php echo $key+1?>' indexall='12'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_12'] != 'R')?$register['a_sesion_12']:''; ?>"
							   	id='index-12-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_12' index='<?php echo $key+1?>' indexall='12' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_12'] != 'R')?$register['a_sesion_12']:''; ?>"
							action='checkbox' name='a_sesion_12' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_12'] != 'R')?$register['a_sesion_12']:''; ?>"
							action='checkbox' name='a_sesion_12' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_12'] != 'R')?$register['a_sesion_12']:''; ?>"
							action='checkbox' name='a_sesion_12' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-13************* -->

				<td>
					<?php switch ($register['a_sesion_13']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_13'] != 'R')?$register['a_sesion_13']:''; ?>"
							action='checkbox' name='a_sesion_13' index='<?php echo $key+1?>' indexall='13'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_13'] != 'R')?$register['a_sesion_13']:''; ?>"
							   	id='index-13-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_13' index='<?php echo $key+1?>' indexall='13' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_13'] != 'R')?$register['a_sesion_13']:''; ?>"
							action='checkbox' name='a_sesion_13' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_13'] != 'R')?$register['a_sesion_13']:''; ?>"
							action='checkbox' name='a_sesion_13' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_13'] != 'R')?$register['a_sesion_13']:''; ?>"
							action='checkbox' name='a_sesion_13' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-14************* -->

				<td>
					<?php switch ($register['a_sesion_14']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_14'] != 'R')?$register['a_sesion_14']:''; ?>"
							action='checkbox' name='a_sesion_14' index='<?php echo $key+1?>' indexall='14'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_14'] != 'R')?$register['a_sesion_14']:''; ?>"
							   	id='index-14-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_14' index='<?php echo $key+1?>' indexall='14' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_14'] != 'R')?$register['a_sesion_14']:''; ?>"
							action='checkbox' name='a_sesion_14' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_14'] != 'R')?$register['a_sesion_14']:''; ?>"
							action='checkbox' name='a_sesion_14' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_14'] != 'R')?$register['a_sesion_14']:''; ?>"
							action='checkbox' name='a_sesion_14' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-15************* -->

				<td>
					<?php switch ($register['a_sesion_15']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_15'] != 'R')?$register['a_sesion_15']:''; ?>"
							action='checkbox' name='a_sesion_15' index='<?php echo $key+1?>' indexall='15'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_15'] != 'R')?$register['a_sesion_15']:''; ?>"
							   	id='index-15-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_15' index='<?php echo $key+1?>' indexall='15' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_15'] != 'R')?$register['a_sesion_15']:''; ?>"
							action='checkbox' name='a_sesion_15' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_15'] != 'R')?$register['a_sesion_15']:''; ?>"
							action='checkbox' name='a_sesion_15' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_15'] != 'R')?$register['a_sesion_15']:''; ?>"
							action='checkbox' name='a_sesion_15' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-16************* -->

				<td>
					<?php switch ($register['a_sesion_16']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_16'] != 'R')?$register['a_sesion_16']:''; ?>"
							action='checkbox' name='a_sesion_16' index='<?php echo $key+1?>' indexall='16'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_16'] != 'R')?$register['a_sesion_16']:''; ?>"
							   	id='index-16-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_16' index='<?php echo $key+1?>' indexall='16' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_16'] != 'R')?$register['a_sesion_16']:''; ?>"
							action='checkbox' name='a_sesion_16' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_16'] != 'R')?$register['a_sesion_16']:''; ?>"
							action='checkbox' name='a_sesion_16' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_16'] != 'R')?$register['a_sesion_16']:''; ?>"
							action='checkbox' name='a_sesion_16' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-17************* -->

				<td>
					<?php switch ($register['a_sesion_17']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_17'] != 'R')?$register['a_sesion_17']:''; ?>"
							action='checkbox' name='a_sesion_17' index='<?php echo $key+1?>' indexall='17'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_17'] != 'R')?$register['a_sesion_17']:''; ?>"
							   	id='index-17-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_17' index='<?php echo $key+1?>' indexall='17' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_17'] != 'R')?$register['a_sesion_17']:''; ?>"
							action='checkbox' name='a_sesion_17' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_17'] != 'R')?$register['a_sesion_17']:''; ?>"
							action='checkbox' name='a_sesion_17' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_17'] != 'R')?$register['a_sesion_17']:''; ?>"
							action='checkbox' name='a_sesion_17' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
			<?php } if ($partial == 2) { ?>
					<!-- *******************sesion-18************* -->
				<td>
					<?php switch ($register['a_sesion_18']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_18'] != 'R')?$register['a_sesion_18']:''; ?>"
							action='checkbox' name='a_sesion_18' index='<?php echo $key+1?>' indexall='1'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_18'] != 'R')?$register['a_sesion_18']:''; ?>"
							   	id='index-1-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_18' index='<?php echo $key+1?>' indexall='1' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_18'] != 'R')?$register['a_sesion_18']:''; ?>"
							action='checkbox' name='a_sesion_18' index='<?php echo $key+1?>' indexall='1'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_18'] != 'R')?$register['a_sesion_18']:''; ?>"
							action='checkbox' name='a_sesion_18' index='<?php echo $key+1?>' indexall='1'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-1-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_18'] != 'R')?$register['a_sesion_18']:''; ?>"
							action='checkbox' name='a_sesion_18' index='<?php echo $key+1?>' indexall='1'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="1" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- ******************sesion 19************** -->
				<td>
					<?php switch ($register['a_sesion_19']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_19'] != 'R')?$register['a_sesion_19']:''; ?>"
							action='checkbox' name='a_sesion_19' index='<?php echo $key+1?>' indexall='2'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_19'] != 'R')?$register['a_sesion_19']:''; ?>"
							   	id='index-2-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_19' index='<?php echo $key+1?>' indexall='2' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_19'] != 'R')?$register['a_sesion_19']:''; ?>"
							action='checkbox' name='a_sesion_19' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_19'] != 'R')?$register['a_sesion_19']:''; ?>"
							action='checkbox' name='a_sesion_19' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-2-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_19'] != 'R')?$register['a_sesion_19']:''; ?>"
							action='checkbox' name='a_sesion_19' index='<?php echo $key+1?>' indexall='2'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="2" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *********************sesion 20*************** -->
				<td>
					<?php switch ($register['a_sesion_20']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_20'] != 'R')?$register['a_sesion_20']:''; ?>"
							action='checkbox' name='a_sesion_20' index='<?php echo $key+1?>' indexall='3'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_20'] != 'R')?$register['a_sesion_20']:''; ?>"
							   	id='index-3-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_20' index='<?php echo $key+1?>' indexall='3' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_20'] != 'R')?$register['a_sesion_20']:''; ?>"
							action='checkbox' name='a_sesion_20' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_20'] != 'R')?$register['a_sesion_20']:''; ?>"
							action='checkbox' name='a_sesion_20' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-3-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_20'] != 'R')?$register['a_sesion_20']:''; ?>"
							action='checkbox' name='a_sesion_20' index='<?php echo $key+1?>' indexall='3'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="3" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				
				<!-- *******************sesion-21************* -->
				<td>
					<?php switch ($register['a_sesion_21']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_21'] != 'R')?$register['a_sesion_21']:''; ?>"
							action='checkbox' name='a_sesion_21' index='<?php echo $key+1?>' indexall='4'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_21'] != 'R')?$register['a_sesion_21']:''; ?>"
							   	id='index-4-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_21' index='<?php echo $key+1?>' indexall='4' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_21'] != 'R')?$register['a_sesion_21']:''; ?>"
							action='checkbox' name='a_sesion_21' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_21'] != 'R')?$register['a_sesion_21']:''; ?>"
							action='checkbox' name='a_sesion_21' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-4-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_21'] != 'R')?$register['a_sesion_21']:''; ?>"
							action='checkbox' name='a_sesion_21' index='<?php echo $key+1?>' indexall='4'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="4" onclick="assignet_assistance(this);"> Falto</span></h5>'
							
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-22************* -->
				<td>
					<?php switch ($register['a_sesion_22']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_22'] != 'R')?$register['a_sesion_22']:''; ?>"
							action='checkbox' name='a_sesion_22' index='<?php echo $key+1?>' indexall='5'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_22'] != 'R')?$register['a_sesion_22']:''; ?>"
							   	id='index-5-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_22' index='<?php echo $key+1?>' indexall='5' 
								rel="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_22'] != 'R')?$register['a_sesion_22']:''; ?>"
							action='checkbox' name='a_sesion_22' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_22'] != 'R')?$register['a_sesion_22']:''; ?>"
							action='checkbox' name='a_sesion_22' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-5-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_22'] != 'R')?$register['a_sesion_22']:''; ?>"
							action='checkbox' name='a_sesion_22' index='<?php echo $key+1?>' indexall='5'
							rel="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="5" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				
				<!-- *******************sesion-23************* -->

				<td>
					<?php switch ($register['a_sesion_23']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_23'] != 'R')?$register['a_sesion_23']:''; ?>"
							action='checkbox' name='a_sesion_23' index='<?php echo $key+1?>' indexall='6'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_23'] != 'R')?$register['a_sesion_23']:''; ?>"
							   	id='index-6-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_23' index='<?php echo $key+1?>' indexall='6' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_23'] != 'R')?$register['a_sesion_23']:''; ?>"
							action='checkbox' name='a_sesion_23' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_23'] != 'R')?$register['a_sesion_23']:''; ?>"
							action='checkbox' name='a_sesion_23' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-6-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_23'] != 'R')?$register['a_sesion_23']:''; ?>"
							action='checkbox' name='a_sesion_23' index='<?php echo $key+1?>' indexall='6'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="6" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>

				<!-- *******************sesion-24************* -->

				<td>
					<?php switch ($register['a_sesion_24']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_24'] != 'R')?$register['a_sesion_24']:''; ?>"
							action='checkbox' name='a_sesion_24' index='<?php echo $key+1?>' indexall='7'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_24'] != 'R')?$register['a_sesion_24']:''; ?>"
							   	id='index-7-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_24' index='<?php echo $key+1?>' indexall='7' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_24'] != 'R')?$register['a_sesion_24']:''; ?>"
							action='checkbox' name='a_sesion_24' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_24'] != 'R')?$register['a_sesion_24']:''; ?>"
							action='checkbox' name='a_sesion_24' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-7-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_24'] != 'R')?$register['a_sesion_24']:''; ?>"
							action='checkbox' name='a_sesion_24' index='<?php echo $key+1?>' indexall='7'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="7" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-25************* -->

				<td>
					<?php switch ($register['a_sesion_25']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_25'] != 'R')?$register['a_sesion_25']:''; ?>"
							action='checkbox' name='a_sesion_25' index='<?php echo $key+1?>' indexall='8'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_25'] != 'R')?$register['a_sesion_25']:''; ?>"
							   	id='index-8-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_25' index='<?php echo $key+1?>' indexall='8' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_25'] != 'R')?$register['a_sesion_25']:''; ?>"
							action='checkbox' name='a_sesion_25' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_25'] != 'R')?$register['a_sesion_25']:''; ?>"
							action='checkbox' name='a_sesion_25' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-8-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_25'] != 'R')?$register['a_sesion_25']:''; ?>"
							action='checkbox' name='a_sesion_25' index='<?php echo $key+1?>' indexall='8'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="8" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-26************* -->

				<td>
					<?php switch ($register['a_sesion_26']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_26'] != 'R')?$register['a_sesion_26']:''; ?>"
							action='checkbox' name='a_sesion_26' index='<?php echo $key+1?>' indexall='9'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_26'] != 'R')?$register['a_sesion_26']:''; ?>"
							   	id='index-9-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_26' index='<?php echo $key+1?>' indexall='9' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_26'] != 'R')?$register['a_sesion_26']:''; ?>"
							action='checkbox' name='a_sesion_26' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_26'] != 'R')?$register['a_sesion_26']:''; ?>"
							action='checkbox' name='a_sesion_26' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-9-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_26'] != 'R')?$register['a_sesion_26']:''; ?>"
							action='checkbox' name='a_sesion_26' index='<?php echo $key+1?>' indexall='9'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="9" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-27************* -->

				<td>
					<?php switch ($register['a_sesion_27']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_27'] != 'R')?$register['a_sesion_27']:''; ?>"
							action='checkbox' name='a_sesion_27' index='<?php echo $key+1?>' indexall='10'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_27'] != 'R')?$register['a_sesion_27']:''; ?>"
							   	id='index-10-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_27' index='<?php echo $key+1?>' indexall='10' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_27'] != 'R')?$register['a_sesion_27']:''; ?>"
							action='checkbox' name='a_sesion_27' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_27'] != 'R')?$register['a_sesion_27']:''; ?>"
							action='checkbox' name='a_sesion_27' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-10-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_27'] != 'R')?$register['a_sesion_27']:''; ?>"
							action='checkbox' name='a_sesion_27' index='<?php echo $key+1?>' indexall='10'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="10" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-28************* -->

				<td>
					<?php switch ($register['a_sesion_28']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_28'] != 'R')?$register['a_sesion_28']:''; ?>"
							action='checkbox' name='a_sesion_28' index='<?php echo $key+1?>' indexall='11'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_28'] != 'R')?$register['a_sesion_28']:''; ?>"
							   	id='index-11-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_28' index='<?php echo $key+1?>' indexall='11' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_28'] != 'R')?$register['a_sesion_28']:''; ?>"
							action='checkbox' name='a_sesion_28' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_28'] != 'R')?$register['a_sesion_28']:''; ?>"
							action='checkbox' name='a_sesion_28' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-11-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_28'] != 'R')?$register['a_sesion_28']:''; ?>"
							action='checkbox' name='a_sesion_28' index='<?php echo $key+1?>' indexall='11'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="11" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>

				<!-- *******************sesion-29************* -->

				<td>
					<?php switch ($register['a_sesion_29']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_29'] != 'R')?$register['a_sesion_29']:''; ?>"
							action='checkbox' name='a_sesion_29' index='<?php echo $key+1?>' indexall='12'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_29'] != 'R')?$register['a_sesion_29']:''; ?>"
							   	id='index-12-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_29' index='<?php echo $key+1?>' indexall='12' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_29'] != 'R')?$register['a_sesion_29']:''; ?>"
							action='checkbox' name='a_sesion_29' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_29'] != 'R')?$register['a_sesion_29']:''; ?>"
							action='checkbox' name='a_sesion_29' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-12-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_29'] != 'R')?$register['a_sesion_29']:''; ?>"
							action='checkbox' name='a_sesion_29' index='<?php echo $key+1?>' indexall='12'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="12" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-30************* -->

				<td>
					<?php switch ($register['a_sesion_30']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_30'] != 'R')?$register['a_sesion_30']:''; ?>"
							action='checkbox' name='a_sesion_30' index='<?php echo $key+1?>' indexall='13'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_30'] != 'R')?$register['a_sesion_30']:''; ?>"
							   	id='index-13-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_30' index='<?php echo $key+1?>' indexall='13' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_30'] != 'R')?$register['a_sesion_30']:''; ?>"
							action='checkbox' name='a_sesion_30' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_30'] != 'R')?$register['a_sesion_30']:''; ?>"
							action='checkbox' name='a_sesion_30' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-13-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_30'] != 'R')?$register['a_sesion_30']:''; ?>"
							action='checkbox' name='a_sesion_30' index='<?php echo $key+1?>' indexall='13'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="13" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-31************* -->

				<td>
					<?php switch ($register['a_sesion_31']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_31'] != 'R')?$register['a_sesion_31']:''; ?>"
							action='checkbox' name='a_sesion_31' index='<?php echo $key+1?>' indexall='14'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_31'] != 'R')?$register['a_sesion_31']:''; ?>"
							   	id='index-14-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_31' index='<?php echo $key+1?>' indexall='14' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_31'] != 'R')?$register['a_sesion_31']:''; ?>"
							action='checkbox' name='a_sesion_31' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_31'] != 'R')?$register['a_sesion_31']:''; ?>"
							action='checkbox' name='a_sesion_31' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-14-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_31'] != 'R')?$register['a_sesion_31']:''; ?>"
							action='checkbox' name='a_sesion_31' index='<?php echo $key+1?>' indexall='14'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="14" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-32************* -->

				<td>
					<?php switch ($register['a_sesion_32']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_32'] != 'R')?$register['a_sesion_32']:''; ?>"
							action='checkbox' name='a_sesion_32' index='<?php echo $key+1?>' indexall='15'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_32'] != 'R')?$register['a_sesion_32']:''; ?>"
							   	id='index-15-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_32' index='<?php echo $key+1?>' indexall='15' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_32'] != 'R')?$register['a_sesion_32']:''; ?>"
							action='checkbox' name='a_sesion_32' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_32'] != 'R')?$register['a_sesion_32']:''; ?>"
							action='checkbox' name='a_sesion_32' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-15-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_32'] != 'R')?$register['a_sesion_32']:''; ?>"
							action='checkbox' name='a_sesion_32' index='<?php echo $key+1?>' indexall='15'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="15" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-33************* -->

				<td>
					<?php switch ($register['a_sesion_33']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_33'] != 'R')?$register['a_sesion_33']:''; ?>"
							action='checkbox' name='a_sesion_33' index='<?php echo $key+1?>' indexall='16'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_33'] != 'R')?$register['a_sesion_33']:''; ?>"
							   	id='index-16-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_33' index='<?php echo $key+1?>' indexall='16' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_33'] != 'R')?$register['a_sesion_33']:''; ?>"
							action='checkbox' name='a_sesion_33' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_33'] != 'R')?$register['a_sesion_33']:''; ?>"
							action='checkbox' name='a_sesion_33' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-16-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_33'] != 'R')?$register['a_sesion_33']:''; ?>"
							action='checkbox' name='a_sesion_33' index='<?php echo $key+1?>' indexall='16'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="16" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
				<!-- *******************sesion-34************* -->

				<td>
					<?php switch ($register['a_sesion_34']) {
						case 'R': ?>
						<span class='inputassist  glyphicon glyphicon-registration-mark' 
						   disabled id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_34'] != 'R')?$register['a_sesion_34']:''; ?>"
							action='checkbox' name='a_sesion_34' index='<?php echo $key+1?>' indexall='17'>
						</span>
					<?php	break; 
						case 'A': ?>
							<span class='inputassist glyphicon glyphicon-ok-circle text-primary' 
							   assistance="<?php echo ($register['a_sesion_34'] != 'R')?$register['a_sesion_34']:''; ?>"
							   	id='index-17-<?php echo $key+1?>'
								action='checkbox' name='a_sesion_34' index='<?php echo $key+1?>' indexall='17' 
								data-container='body' data-toggle="popover" data-placement='right' data-html='true'
								data-original-title="Asignar Asistencia" 
								data-content='
								<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17"  onclick="assignet_assistance(this);"> Falto</span></h5>
								<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>'
								data-trigger='click'
							></span>
					<?php break; 
					case 'F': ?>
							<span class='inputassist glyphicon glyphicon-remove-circle text-danger'
								id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_34'] != 'R')?$register['a_sesion_34']:''; ?>"
							action='checkbox' name='a_sesion_34' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Asistio</span></h5>
							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>'
							data-trigger='click'
							></span>
					<?php break; 
					case 'T': ?>
							<span class='inputassist glyphicon glyphicon-copyright-mark text-success'
							id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_34'] != 'R')?$register['a_sesion_34']:''; ?>"
							action='checkbox' name='a_sesion_34' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17"  onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Falto</span></h5>
							'
							data-trigger='click'
							></span>
					<?php break;
						default: ?>
							<span class='inputassist glyphicon glyphicon-unchecked'
							id='index-17-<?php echo $key+1?>'
						   assistance="<?php echo ($register['a_sesion_34'] != 'R')?$register['a_sesion_34']:''; ?>"
							action='checkbox' name='a_sesion_34' index='<?php echo $key+1?>' indexall='17'
							data-container='body' data-toggle="popover" data-placement='right' data-html='true'
							data-original-title="Asignar Asistencia" 
							data-content='
							<h5><span class="assignet-assist glyphicon glyphicon-ok-circle text-primary" value="A" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Asistio</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-copyright-mark text-success" value="T"  index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Tarde</span></h5>

							<h5><span class="assignet-assist glyphicon glyphicon-remove-circle text-danger" value="F" index="<?php echo $key+1?>" indexall="17" onclick="assignet_assistance(this);"> Falto</span></h5>'
							data-trigger='click'
							></span>
					<?php break; }?>
				</td>
			<?php }?>
				
			<td class='success'>
				<?php
					if ($this->state != "C" && $partial == 1) {
						if ($register['a_sesion_17'] == 'R') { ?>
							<span class='glyphicon glyphicon-eye-close presented' 
								action='1' onclick='retired_assist(this);' 
								index='<?php echo $key?>'></span>
						<?php }else{ ?>
							<span class='glyphicon glyphicon-eye-open presented' 
								action='0' onclick='retired_assist(this);'
								index='<?php echo $key?>'></span>
					<?php }}?>
				<?php
				if ($this->state != "C" && $partial == 2) {
					if ($register['a_sesion_34'] =='R') { ?>
						<span class='glyphicon glyphicon-eye-close presented' 
							action='1' onclick='retired_assist(this);' 
							index='<?php echo $key?>'></span>
					<?php }else{ ?>
						<span class='glyphicon glyphicon-eye-open presented' 
							action='0' onclick='retired_assist(this);'
							index='<?php echo $key?>'></span>
				<?php }}?>
			</td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	</div>
</div>
<?php }?>
<input type='hidden' id='coursoid' coursoid='<?php ?>'>
<div class="modal fade" id='toserver'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Enviado al Servidor</h4>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->