<style type="text/css">
	.nota{
		width: 53px;
		text-align: center;
	}
	.presented{
		cursor: pointer;
	}
	.error-input
	{
		background-color: red;
	}
</style>
<script type="text/javascript">

	$partial = <?php echo $this->partial?>;
	$assist = {};

	function retired_assist (obj) {
		var $icon = $(obj);
		var $parent = $(obj).parent();
		var $parent = $parent.parent();
		var $action = $(obj).attr('action');

		var $index = $icon.attr('index');

		if($action == "0")
		{
			$icon.removeClass('glyphicon-eye-open');
			$icon.addClass('glyphicon-eye-close');
			$parent.css('color','#FC4141');
        	$icon.attr("action","1");
		}
		else{

			$icon.removeClass('glyphicon-eye-close');
			$icon.addClass('glyphicon-eye-open');
			$parent.css('color','#000');
        	$icon.attr("action","0");
		}

		$assist = {};
		$assist[$.base64.encode('courseid')]=$.base64.encode($.trim($parent.attr('courseid')));
		$assist[$.base64.encode('curid')]=$.base64.encode($.trim($parent.attr('curid')));
		$assist[$.base64.encode('turno')]=$.base64.encode($.trim($parent.attr('turno')));
		$assist[$.base64.encode('regid')]=$.base64.encode($.trim($parent.attr('regid')));
		$assist[$.base64.encode('uid')]=$.base64.encode($.trim($parent.attr('uid')));
		$assist[$.base64.encode('pid')]=$.base64.encode($.trim($parent.attr('pid')));
		$assist[$.base64.encode('perid')]=$.base64.encode($.trim($parent.attr('perid')));
		$assist[$.base64.encode('escid')]=$.base64.encode($.trim($parent.attr('escid')));
		$assist[$.base64.encode('subid')]=$.base64.encode($.trim($parent.attr('subid')));

		$($parent[0].children).each(function(){
	        if(this.firstElementChild != null){
	            if(this.firstElementChild.nodeName == 'INPUT'){
	                
                    $checkbox= $(this.firstElementChild);
                    $name = $checkbox.attr("name");
                    
                    if ($action == '0') {
                    	$checkbox.attr('disabled',true);
                		$assist[$.base64.encode($name)]=$.base64.encode("R");
                    }
                    else
                    {
                		$assist[$.base64.encode($name)]=$.base64.encode("");
                    	$checkbox.attr('disabled',false);
                    }
	            }
	        }
    	});

		result = "";
	    for (var prop in $assist ) {
	        result += '' + prop + '/' + $assist[prop]  + '/'; 
	    }
    	result = result.substring(0, result.length-1);
    	result = result + '/' + $.base64.encode('partial') + '/' + $.base64.encode($partial);
    	var $url = '/assistance/student/savefile/' + result;
    	$.ajax({
	        url:$url,
	        success:function($data){
	                alert($data);
	        },
	        error:function($data){
	                //Pintar el error
	                
	        }
	    });

	}

</script>	


<?php $partial = $this->partial;
if ($this->infoassist) { ?>
<div class='row notas' >
	<div class='col-md-12'>
	<table class='table' id='tbnotas'>
		<thead>
			<tr>
				<th>#</th>
				<th>Apellidos y Nombres</th>
					<th class='success'>1
						<div>
							<input type='checkbox' name='select-all-1' index-all='1'></th>
						</div>
					</th>
					<th class='success'>2
						<div>
							<input type='checkbox' name='select-all-2' index-all='2'></th>
						</div>
					</th>
					<th class='success'>3
						<div>
							<input type='checkbox' name='select-all-3' index-all='3'></th>
						</div>
					</th>
					<th class='success'>4
						<div>
							<input type='checkbox' name='select-all-4' index-all='4'></th>
						</div>
					</th>
					<th class='success'>5
						<div>
							<input type='checkbox' name='select-all-5' index-all='5'></th>
						</div>
					</th>
					<th class='success'>6
						<div>
							<input type='checkbox' name='select-all-6' index-all='6'></th>
						</div>
					</th>
					<th class='success'>7
						<div>
							<input type='checkbox' name='select-all-7' index-all='7'></th>
						</div>
					</th>
					<th class='success'>8
						<div>
							<input type='checkbox' name='select-all-8' index-all='8'></th>
						</div>
					</th>
					<th class='success'>9
						<div>
							<input type='checkbox' name='select-all-9' index-all='9'></th>
						</div>
					</th>
					<th class='success'>10
						<div>
							<input type='checkbox' name='select-all-10' index-all='10'></th>
						</div>
					</th>
					<th class='success'>11
						<div>
							<input type='checkbox' name='select-all-11' index-all='11'></th>
						</div>
					</th>
					<th class='success'>12
						<div>
							<input type='checkbox' name='select-all-12' index-all='12'></th>
						</div>
					</th>
					<th class='success'>13
						<div>
							<input type='checkbox' name='select-all-13' index-all='13'></th>
						</div>
					</th>
					<th class='success'>14
						<div>
							<input type='checkbox' name='select-all-14' index-all='14'></th>
						</div>
					</th>
					<th class='success'>15
						<div>
							<input type='checkbox' name='select-all-15' index-all='15'></th>
						</div>
					</th>
					<th class='success'>16
						<div>
							<input type='checkbox' name='select-all-16' index-all='16'></th>
						</div>
					</th>
					<th class='success'>17
						<div>
							<input type='checkbox' name='select-all-17' index-all='17'></th>
						</div>
					</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->infoassist as $key => $registro) { ?>
			<tr courseid='<?php echo $registro['coursoid']?>'
				curid='<?php echo $registro['curid']?>'
				turno='<?php echo $registro['turno']?>'
				perid='<?php echo $registro['perid']?>'
				escid='<?php echo $registro['escid']?>'
				subid='<?php echo $registro['subid']?>'
				regid='<?php echo $registro['regid']?>'
				uid='<?php echo $registro['uid']?>'
				pid='<?php echo $registro['pid']?>'
                edicion="false"
                style="color:<?php echo ($registro['a_sesion_17'] != 'R')?'#000':'#FC4141'; ?>;"
				>
			<td><?php echo $key+1?> <span  class='text-success glyphicon'></span></td>
			<td><?php echo $registro['name']?></td>
			<?php if ($partial==1) { ?>
				<td>
					<input <?php echo ($register['a_sesion_1'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_1' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_2'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_2' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_3'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_3' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_4'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_4' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_5'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_5' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_6'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_6' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_7'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_7' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_8'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_8' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_9'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_9' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_10'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_10' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_11'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_11' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_12'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_12' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_13'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_13' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_14'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_14' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_15'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_15' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_16'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_16' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_17'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_17' >
				</td>
			<?php }if ($partial== 2) { ?>
				<td>
					<input <?php echo ($register['a_sesion_18'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_18' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_19'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_19' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_20'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_20' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_21'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_21' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_22'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_22' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_23'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_23' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_24'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_24' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_25'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_25' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_26'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_26' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_27'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_27' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_28'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_28' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_29'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_29' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_30'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_30' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_31'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_31' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_32'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_32' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_33'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_33' >
				</td>
				<td>
					<input <?php echo ($register['a_sesion_34'] != 'R')?'':'disabled' ?> type='checkbox' name='a_sesion_34' >
				</td>
			<?php }?>
			<td class='success'>
				<?php
					if ($this->state != "C") {
						if ($registro['a_sesion_17'] != 'R' || $registro['a_sesion_34'] !='R') { ?>
							<span class='glyphicon glyphicon-eye-open presented' 
								action='0' onclick='retired_assist(this);'
								index='<?php echo $key?>'></span>
						<?php }else{ ?>
							<span class='glyphicon glyphicon-eye-close presented' 
								action='1' onclick='retired_assist(this);' 
								index='<?php echo $key?>'></span>
					<?php }}?>
			</td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	</div>
</div>
<?php }?>

