<?php 
$rid=$this->rid;
if ($this->curriculas) { 

?>
<table class="table table-striped table-condensed span9">
	<tr>
		<th>#</th>
		<th>Cod. Cur.</th>
		<th>Nombre Currícula</th>
		<th>Estado</th>
		<th>Año</th>
		<th>Ver</th>
		 <th>Imprimir</th>
                        
	</tr>
	<?php
	$c=1;
	foreach ($this->curriculas as $curriculas) { 
		switch ($curriculas['state']) {
			case 'T': $estado="Temporal"; break;
			case 'A': $estado="Activo"; break;
            case 'C': $estado="Cerrado"; break;
			case 'B': $estado="Borrador"; break;
		}
		?>
		<tr>
			<td><?php echo $c?></td>
			<td><?php echo $curriculas['curid']?></td>
			<td><?php echo $curriculas['name']?></td>
			<td><?php echo $estado?></td>
			<td><?php echo $curriculas['year']?></td>
			<td><a href="/curricula/show/seecurricula/curid/<?php echo base64_encode($curriculas['curid'])?>/escid/<?php echo base64_encode($curriculas['escid'])?>/subid/<?php echo base64_encode($curriculas['subid'])?>" ><span class="glyphicon glyphicon-folder-open"></span></a></td>
            <td><a href="/curricula/show/print/subid/<?php echo base64_encode($curriculas['subid'])?>/escid/<?php echo base64_encode($curriculas['escid'])?>/curid/<?php echo base64_encode($curriculas['curid'])?>/state/<?php echo base64_encode($curriculas['state'])?>"><img src="/img/icono_imprimir.png"  rel="tooltip" title="Imprimir" /></a></td>
                  
                        
		</tr>
	<?php
	$c++;
	}?>
</table>
<?php 
}else{ ?>
	<div class="alert alert-success span9">No hay registro de Currículas en esta Escuela.</div>
<?php }?>
