<?php $this->placeholder('Btnnav')->append('<a href="/admin" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> ADMINISTRACION DE CURRICULAS');?>

<?php
$facid=$this->facid;

?>
<div>
	<table class="table table-striped table-condensed span9">
		<tr>
			<th>Facultad:</th>
			<td>
				<select class='form-control' style='height:35px;width:350px' id="facid">

					<option value="">- Seleccione Facultad -</option>
					<?php if ($this->facultad) {
						foreach ($this->facultad as $facultad) { 
							if($facid){
								if($facid==$facultad['facid']){
									if ($this->facid) $str = ($this->facid==$facultad['facid'])?"selected ":""; 
									?>
									<option <?php echo $str?> value="<?php echo $facultad['facid']?>"><?php echo $facultad['name']?></option>	
									<script type="text/javascript">
                                        $("#facid").attr("disabled",true);
                                    </script>

								<?php
								}
							}else{

							 if ($this->facid) $str = ($this->facid==$facultad['facid'])?"selected ":""; ?>
							<option <?php echo $str?> value="<?php echo $facultad['facid']?>"><?php echo $facultad['name']?></option>		
						<?php
					     }
						}
					} ?>
				</select>
			</td>
			<th>Escuela:</th>
			<td>
				<select class='form-control' style='height:35px;width:350px' id='escid'>
					<option>- Seleccione Escuela -</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div id="datos" class="flotacarajo span9"></div>

<script type="text/javascript">
	var $facid_temp = "<?php echo $facid?>";
	$("#escid").load("/curricula/show/lschools/facid/" + $facid_temp);
</script>

<script type="text/javascript">
var escid="<?php echo $this->escid?>";
if (escid) {
	$("#escid").attr('disabled',true);
	var url="/curricula/show/curriculas/escid/"+escid;
	$("#datos").html("<img src='/img/spinner.gif'>Cargando...");
	$("#datos").load(url);
};

$("#facid").change(function(){
	var facid=$(this).val();
	// alert(facid);
	var url = "/curricula/show/lschools/facid/"+facid;
	$("#escid").load("/curricula/show/lschools/facid/"+facid);
});

$("#escid").change(function(){
	var escid=$(this).val();
	var url="/curricula/show/curriculas/escid/"+escid;
	$("#datos").html("<img src='/img/spinner.gif'>Cargando...");
	$("#datos").load(url);
});
</script>