<?php 
if ($this->escuelas) { ?>
	<option>- Seleccione Escuela -</option>
		<?php
		foreach ($this->escuelas as $escuelas) { 
			if ($this->escid){
				$str=($this->escid==$escuelas['escid'])? "selected":""; 
			}
			else{
				$str=null;
			} 
			?>
			<option <?php echo $str?> value="<?php echo $escuelas['escid']?>"><?php echo $escuelas['name']?></option>		
		<?php
		}
}else{ ?>
<option value="">No tiene registro.</option>
<?php }?>