<?php 
$facid=trim(mb_substr($this->escid,0,1));
$escid=$this->escid; 
$subid=$this->subid;
$curid=$this->curid;
$state=$this->state;
$eid=$this->eid;
$oid=$this->oid;
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 

?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<table class="table table-striped table-bordered table-condensed">
        <tr>
            <th ><img src="/img/header_imprimir.jpg"></th>
            <th>    
                <center>
                <p>                
                <span style="font-size: 16px"> <?php print(strtoupper($this->nombre_curricula)); ?></span><br/>
                <span style="font-size: 15px"> FACULTAD DE <?php                    
                    $facultad= new Api_Model_DbTable_Faculty();
                    $where['eid']=$eid;
                    $where['oid']=$oid;
                    $where['facid']=$facid;
                    $datafacid=$facultad->_getOne($where);
                    print_r(strtoupper($datafacid['name']));
                ?></span><br/>                 
                <?php 
                    $escuela= new Api_Model_DbTable_Speciality();
                    $data['eid']=$eid;
                    $data['oid']=$oid;
                    $data['escid']=$escid;
                    $data['subid']=$subid;

                    $dataescid=$escuela->_getOne($data);
                    if ($dataescid['parent']=="")
                    {
                ?>
                    <span style="font-size: 14px">ESCUELA DE 
                        <?php 
                            // $escuela= new Admin_Model_DbTable_Escuela();
                            // $dataescid=$escuela->_getEscuela($eid,$oid,$escid);
                            print_r(strtoupper($dataescid['name']));
                        ?> 
                    </span><br/>

                    <?php 
                    }
                    else
                   {
                    ?>
                    <span style="font-size: 14px">ESCUELA DE 
                        <?php 
                         
                            // $escuela= new Admin_Model_DbTable_Escuela();
                            // // $dataescid=$escuela->_getEscuela($eid,$oid,$escid);
                            // $dataesciduno=$escuela->_getMostrardatosXEscuela($eid,$oid,$dataescid['parent_escuela']);

                            // print_r(strtoupper($dataesciduno['nom_escuela']));
                        ?> 
                    </span><br/>


                    <span style="font-size: 14px">ESPECIALIDAD DE 
                        <?php 
                   
                            // $escuela= new Admin_Model_DbTable_Escuela();
                            // $dataescid=$escuela->_getEscuela($eid,$oid,$escid);
                            print_r(strtoupper($dataescid['name']));

                        ?>
                    </span><br/>
                <?php 
            }
                
                ?>

                </p>
                </center>
                
            </th>
        </tr>
    </table>
        <?php
        foreach($this->semestre as $lsem)
        {?>

<div>

     <table class="table table-striped table-bordered table-condensed" style="font-size: 11px">
            <tr>
                <th colspan="10"><?php echo strtoupper($lsem['name']) ?></th>
            </tr>

            <tr>
                <th>Codigo</th>
                <th >Curso</th>
                <th>Tipo</th>
                <th>Creditos</th>
                <th>Horas Teoricas.</th>
                <th>Horas Practicas.</th>
                <th>Req 1</th>
                <th>Req 2</th>
                <th>Req 3</th>
                <th>Equivalencia</th>
            </tr>


             <?php
                $bdcursos = new Api_Model_DbTable_Course();
                $dat['eid']=$eid;
                $dat['oid']=$oid;
                $dat['escid']=$escid;
                $dat['subid']=$subid;
                $dat['curid']=$curid;
                $dat['semid']=$lsem["semid"];
                
                $cursos=$bdcursos->_getFilter($dat);
                foreach ($cursos as $lcursos){ 
                    
                ?>
                <tr>
                    <td><?php echo $lcursos['courseid'] ?></td>
                    <td><?php echo $lcursos['name'] ?></td>
                    <td><?php 
                        if ($lcursos['type']=='O') echo "Obligatorio";

                        if ($lcursos['type']=='E') echo "Electivo";
                    ?>
                    </td>
                    <td><?php echo $lcursos['credits']?></td>
                    <td><?php echo $lcursos['hours_theoretical']?></td>
                    <td><?php echo $lcursos['hours_practical']?></td>
                    <td><?php echo $lcursos['req_1']?></td>
                    <td><?php echo $lcursos['req_2']?></td>
                    <td><?php echo $lcursos['req_3']?></td>
                    <td><?php echo $lcursos['course_equivalence']?></td>
                </tr>
            <?php
                
            }
            ?>
        </table>
</div>
        <div style="clear:both" ></div>
        <?php }
        ?>
<?php 

  $html = ob_get_contents();
  
  $mpdf=new mPDF('win-1252','A4','','',15,15,40);
  $mpdf->SetHTMLHeader($header);
  $mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
  
  $mpdf->SetFooter($this->footer);
  ob_end_clean();
  $mpdf -> WriteHTML($html);
  $mpdf->Output('Curricula-'.$curid.'.pdf','D');
  
?>