<?php $this->placeholder('Btnnav')->append('<a href="/curricula/show/viewmanager" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span>CURSOS-DIRECCION');?>

<?php $datos = $this->cursos; ?>
<style>
.barlittle {
	background-color:#2187e7;  
	background-image: -moz-linear-gradient(45deg, #2187e7 25%, #a0eaff); 
	background-image: -webkit-linear-gradient(45deg, #2187e7 25%, #a0eaff);
	border-left:1px solid #111; border-top:1px solid #111; border-right:1px solid #333; border-bottom:1px solid #333; 
	width:10px;
	height:10px;
	display: inline-block;
	margin-left:5px;
    opacity:0.1;
	-moz-transform:scale(0.7);
	-webkit-transform:scale(0.7);
	-moz-animation:move 1s infinite linear;
	-webkit-animation:move 1s infinite linear;
}
#block_1{
 	-moz-animation-delay: .4s;
	-webkit-animation-delay: .4s;
 }
#block_2{
 	-moz-animation-delay: .3s;
	-webkit-animation-delay: .3s;
}
#block_3{
 	-moz-animation-delay: .2s;
	-webkit-animation-delay: .2s;
}
#block_4{
 	-moz-animation-delay: .3s;
	-webkit-animation-delay: .3s;
}
#block_5{
 	-moz-animation-delay: .4s;
	-webkit-animation-delay: .4s;
}
@-moz-keyframes move{
	0%{-moz-transform: scale(1.2);opacity:1;}
	100%{-moz-transform: scale(0.7);opacity:0.1;}
}
@-webkit-keyframes move{
	0%{-webkit-transform: scale(1.2);opacity:1;}
	100%{-webkit-transform: scale(0.7);opacity:0.1;}
}
	thead{
		color:white;
		background: rgb(0,0,0);
		font-weight: bold;
		text-align: center;
	}
	.carga{
		padding: 5px 0;
		text-align: center;
	}
</style>
<?php $this->placeholder('BtnSVCRight')->append('<a href="" type="button" id="guardar" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk"></span> Cerrar</a>') ?>
<div class="row">
	<div class="alert alert-info col-xs-8 col-xs-offset-2">
		<h2>CURSOS DE LA ESCUELA DE : <span> <?php echo $this->escuela; ?></span></h2>
		<h4>COD. DE CURRICULA <span class="label label-default"><?php echo($this->curid); ?></span> </h4>

	</div>
</div>
<!-- modal-->
<div class="modal fade" id="myModal" style="margin-top:10%">
  <div class="modal-dialog" style="width:30%">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title" id="myModalLabel"><span class='text-info'><b>ENVIANDO DATOS</b></span></h4>
			<div class="carga">
				<div class="contentBar">
    				<div id="block_1" class="barlittle"></div>
       				<div id="block_2" class="barlittle"></div>
        			<div id="block_3" class="barlittle"></div>
        			<div id="block_4" class="barlittle"></div>
			        <div id="block_5" class="barlittle"></div>
    			</div>
			</div>
			<p class="text-center"><span class="error1 label label-danger hidden">ERROR</span></p>
      </div>
    </div>
  </div>
</div>
<!---->
<?php $i=1;$sem=$datos[1]['semid']; ?>
<?php if($datos){ ?>
<div class="container">
	<table class="table table-striped table-bordered table-condensed span9">
		<thead class="list-group">
				<th>N°</th>
				<td>Nombre de curso</th>
				<th>Cod. Curso</th>
				<th>Semestre</th>
				<th>Sumilla</th>
		</thead>
		<tbody>
			<form id="formData" role="form" class="form-horizontal">
			<input type="hidden" name="escid" value="<?php echo base64_encode($this->escid); ?>" >
			<input type="hidden" name="curid" value="<?php echo base64_encode($this->curid); ?>" >
			<input type="hidden" name="cantidad" value="<?php echo(count($datos));?>">
				<?php foreach ($datos as $datos) {?>
					<?php if ($sem != $datos["semid"]){?>
						<tr style="border-top:5px solid #1B91E0;">
						<?php $sem++ ?>
					<?php }?>
						<td>
							<p><span class="label label-default"><?php echo($i);?></span></p>
						</td>
						<td>
							<p><?php echo $datos["name"];?></p>
						</td>
						<td>
							<input type="hidden" name="curso<?php echo($i);?>" value='<?php echo $datos["courseid"];?>'>
							<p><?php echo $datos["courseid"];?></p>
						</td>
						<td class="text-center">
							<p><?php echo $datos["semid"];?>°</p> 
						</td>
						<td>
							<div class="form-group has-feedback">
								<label class="control-label"></label>
    							<input type="text" class="form-control sumilla" contador="<?php echo($i)?>" placeholder="Ingrese sumilla" name="sumilla<?php echo($i); ?>" value=''>
    							<span class="glyphicon form-control-feedback" contador="<?php echo($i)?>"></span>

  							</div>
						</td>
					</tr>
					<?php $i++; ?>
				<?php } ?>

			</form>
		</tbody>	
	</table>
</div>
<?php }else{ ?>
	<div class="danger">
		<h3>No existen Cursos Registrados</h3>
	</div>
<?php } ?>
<script>
		var pos;
	$('.sumilla').change(function(event) {
		event.preventDefault();
		var sum = $(this).val();
		pos = $(this).attr('contador');
		if (sum == "") {
			$(this).parent().removeClass('has-success');
			$(this).parent().removeClass('has-warning');
			$(this).parent().addClass('has-error');
			$("span[contador="+pos+"]").removeClass('glyphicon-ok');
			$("span[contador="+pos+"]").removeClass('glyphicon-warning-sign');
			$("span[contador="+pos+"]").addClass('glyphicon-remove');
		}else{
			$(this).parent().removeClass('has-error');
			$(this).parent().removeClass('has-warning');
			$(this).parent().addClass('has-success');
			$("span[contador="+pos+"]").removeClass('glyphicon-remove');
			$("span[contador="+pos+"]").removeClass('glyphicon-warning-sign');
			$("span[contador="+pos+"]").addClass('glyphicon-ok');
		};

	});
	$("#guardar").click(function(event) {
		event.preventDefault();
		var x;

		$(".error1").addClass('hidden');
		$("#myModal").modal("show");
		var bandera=true;
		for (var i = 1; i < <?php echo $i; ?>; i++) {
			x = $('input[name=sumilla'+i+']').val();
			if (x == ""){
				bandera=false;
				pos=i;
				i=1000;
				$(".error1").removeClass('hidden');
				$("#myModal").modal("hide");
			}
		};
		if(bandera==true){
			$.ajax({
			type:'post',
			url:'/curricula/show/save',
			data : $('#formData').serialize(),
			success: function(data){
				console.log(data);
				$("#myModal").modal("hide");
				
				if(data=="1"){
					alert('FALTAN RELLENAR DATOS');
				}else if(data=="2") {
					alert('SE COMPLETO EL TRAMITE DEL  LLENADO DE SUMILLA');
				};
			}
			});
		}else{
			$('input[name=sumilla'+pos+']').focus();
			return false;
			$("span[contador="+pos+"]").parent().removeClass('has-success');
			$("span[contador="+pos+"]").parent().removeClass('has-error');
			$("span[contador="+pos+"]").parent().addClass('has-warning');
			$("span[contador="+pos+"]").removeClass('glyphicon-ok');
			$("span[contador="+pos+"]").removeClass('glyphicon-remove');
			$("span[contador="+pos+"]").addClass('glyphicon-warning-sign');
		};
	});
</script>
