<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Gestión Currícula');?>
<?php $this->placeholder('Btnnav')->append('<a href="/curricula/show/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar</a><button id="print_curri" class="btn btn-success"><span class="glyphicon glyphicon-print "></span> Imprimir</button>');
$curricula=$this->curricula;
$eid=$this->eid;
$oid=$this->oid;
$subid=$this->subid;
$escid=$this->escid; 
$curid=$this->curid; 
$curidant=$this->curidant;
$rid=$this->rid; 
?>

<div class="row">
    <div class="text-center">
        <h4>Escuela de Formación Profesional de <?php echo $this->escuela[0]['name']?></h4>
        <h5><b><?php echo $curricula['name']?></b></h5>
    </div>
</div>
<!-- <td><a href="/curricula/show/print/subid/<?php echo base64_encode($subid)?>/escid/<?php echo base64_encode($escid)?>/curid/<?php echo base64_encode($curid)?>/state/<?php echo base64_encode($cstate)?>" class="btn btn-info" id="llamar">Imprimir</a></td> -->
<div class="text-center">
    <h4><b>SEMESTRES ACADÉMICOS</b></h4>
</div>
<?php 
if ($this->semestre) { ?>
<div class="flotacarajo" style="margin:10px">    
    <ul class="nav nav-tabs" id="myTab">
        <?php
        foreach ($this->semestre as $semestre) { ?>
          <li><a href="#sem<?php echo $semestre['semid']?>"><?php echo $semestre['name']?></a>
          </li>
         <?php
        }?>
   </ul>
   
  
</div>
<div class="tab-content">
<?php
foreach ($this->semestre as $semestre) { ?>
    <div class="tab-pane" id="sem<?php echo $semestre['semid']?>">
     <?php if ($this->cursos) { ?>
                        <table class="table table-hover">
                            <tr>
                                <th colspan="7"><center>CURSOS ACTIVOS <?php echo $curid?></center></th>
                                <th colspan="3" class="colors"><center>CURSOS DE EQUIVALENCIA <?php echo $curidant?></center></th>
                            </tr>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Código</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Tipo</th>
                                <th class="text-center">Créditos</th>
                                <th class="text-center">H.T</th>
                                <th class="text-center">H.P</th>
                                <th class="colors text-center">Código</th>
                                <th class="colors text-center">Nombre</th>
                                <th class="colors text-center">Créditos</th>    
                            </tr>
                        <?php
                        $i=1;
                        foreach ($this->cursos as $cursos) { 
                            $equi=new Api_Model_DbTable_Course();
                            if ($semestre['semid']==$cursos['semid']) {
                                $where['eid']=$eid;
                                $where['oid']=$oid;
                                $where['escid']=$escid;
                                $where['subid']=$subid;
                                $where['courseid']=$cursos['course_equivalence'];
                                $where['curid']=$curidant;
                                $cursoequi=$equi->_getOne($where);
                                if ($cursoequi) {
                                    $cursoidequi=$cursoequi['courseid'];
                                    $nombreequi=$cursoequi['name'];
                                    $creditosequi=$cursoequi['credits'];
                                }else{
                                    $cursoidequi="-";
                                    $nombreequi="Ninguno";
                                    $creditosequi="-";
                                }
                                ?>
                            <tr>
                                <td class="text-center"><?php echo $i?></td>
                                <td class="text-center"><?php echo $cursos['courseid']?></td>
                                <td><?php echo $cursos['name']?></td>
                                    <?php
                                    switch ($cursos['type']) {
                                        case 'O':   ?>     
                                            <td class="text-center">Obligatorio</td>
                                        <?php
                                            break;
                                        case 'E':   ?>     
                                            <td class="text-center">Electivo</td>
                                        <?php
                                            break;
                                        default:    ?>
                                            <td class="text-center">-</td>
                                        <?php    
                                            break;
                                    }
                                    ?>
                                <td class="text-center"><?php echo $cursos['credits']?></td>
                                <td class="text-center">
                                    <?php 
                                    if ($cursos['hours_practical']) {
                                        echo $cursos['hours_theoretical'];
                                    }
                                    else{
                                        echo "-";    
                                    }
                                    ?>
                                </td>
                                <td class="text-center">
                                    <?php 
                                    if ($cursos['hours_practical']) {
                                        echo $cursos['hours_practical'];
                                    }
                                    else{
                                        echo "-";    
                                    }
                                    ?>
                                </td>
                                <td class="colors text-center"><?php echo $cursoidequi?></td>
                                <td class="colors"><?php echo $nombreequi?></td>
                                <td class="colors text-center"><?php echo $creditosequi?></td>
                            </tr>
                        <?php
                            $i++;
                            }
                        } ?>
                        </table>
                        <?php
                    }?>


    </div>

  
<?php
        }?>
</div> 


<?php
}?>

<script type="text/javascript">
    $('#myTab a:first').tab('show') // Select first tab
    $('#myTab a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });

    $("#print_curri").click(function(){
        var subid="<?php echo base64_encode($subid)?>";
        var escid="<?php echo base64_encode($escid)?>";
        var curid="<?php echo base64_encode($curid)?>";
        var state="<?php echo base64_encode($cstate)?>";
        var url="/curricula/show/print/subid/"+subid+"/escid/"+escid+"/curid/"+curid+"/state/"+state;
        $(location).attr('href',url);
    });
</script>


<style type="text/css">
    .colors{
        background: #f5f5f5; 
    }
</style>




