<?php $this->placeholder('Btnnav')->append('<a href="/docente" class="form-control btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span>CURRICULAS-DIRECCION');?>
<style>
	.carga{
		margin: 0;
		padding: 40px 0;
		text-align: center;
	}
.barlittle {
	background-color:#2187e7;  
	background-image: -moz-linear-gradient(45deg, #2187e7 25%, #a0eaff); 
	background-image: -webkit-linear-gradient(45deg, #2187e7 25%, #a0eaff);
	border-left:1px solid #111; border-top:1px solid #111; border-right:1px solid #333; border-bottom:1px solid #333; 
	width:10px;
	height:10px;
	display: inline-block;
	margin-left:5px;
    opacity:0.1;
	-moz-transform:scale(0.7);
	-webkit-transform:scale(0.7);
	-moz-animation:move 1s infinite linear;
	-webkit-animation:move 1s infinite linear;
}
#block_1{
 	-moz-animation-delay: .4s;
	-webkit-animation-delay: .4s;
 }
#block_2{
 	-moz-animation-delay: .3s;
	-webkit-animation-delay: .3s;
}
#block_3{
 	-moz-animation-delay: .2s;
	-webkit-animation-delay: .2s;
}
#block_4{
 	-moz-animation-delay: .3s;
	-webkit-animation-delay: .3s;
}
#block_5{
 	-moz-animation-delay: .4s;
	-webkit-animation-delay: .4s;
}
@-moz-keyframes move{
	0%{-moz-transform: scale(1.2);opacity:1;}
	100%{-moz-transform: scale(0.7);opacity:0.1;}
}
@-webkit-keyframes move{
	0%{-webkit-transform: scale(1.2);opacity:1;}
	100%{-webkit-transform: scale(0.7);opacity:0.1;}
}
	table{
		border-right:5px solid black;
	}
	tr th {
		color:white;
		font-weight:bold;
	}
	thead > tr{
		background:rgba(30,30,30,1);
		font-size: 16px;
	}
	tr{
		height: 35px;
	}
</style>

<?php $especialidades = $this->especialidades; ?>
<?php $datos = $this->datos; ?>
<?php if($especialidades){ ?>
	<div class="row">
	<div class="alert alert-info text-center col-xs-12">
		<div class="col-md-4">
			<strong><h5>Facultad:</h5><span><h4><?php echo $datos["facName"]; ?></h4></span></strong>	
		</div>
		<div class="col-md-4">
			<strong><h5>Escuela:</h5><span><h4><?php echo $datos["escName"]; ?></h4></span></strong>
		</div>
		<div class="col-md-4">
			<strong><h5>Especialidad: </h5>
			<div class="form-group">
				<select class='form-control' id='especialidad'>
					<option>-Seleccione Especialidad-</option>
					<?php
						foreach ($this->especialidades as $especialidad) { 
						?>
						<option value='<?php echo $especialidad['escid']?>'><?php echo $especialidad['name']?></option>
					<?php } ?>
				</select>
			</div>
			</strong>	
		</div>
	</div>
</div>
<div class="carga hidden">
	<div class="contentBar">
    	<div id="block_1" class="barlittle"></div>
        <div id="block_2" class="barlittle"></div>
        <div id="block_3" class="barlittle"></div>
        <div id="block_4" class="barlittle"></div>
        <div id="block_5" class="barlittle"></div>
    </div>
</div>
<script>
		$("#especialidad").click(function(){
			$(".carga").removeClass('hidden');
			$("#conten").html("");
			var ajax_data1 = {
   				"escid": $("#especialidad").val()
   			};
			$.ajax({
				type : 'post',
				url : '/curricula/show/curriculas/',
				data : ajax_data1,
				success : function(data){
					$("#conten").html(data);
					$(".carga").addClass('hidden');
				}
			});
		});
	
</script>

<?php }else{ ?>
<div class="row">
	<div class="alert alert-info text-center col-xs-12">
		<div class="col-md-6">
			<strong><h5>Facultad:</h5><span><h4><?php echo $datos["facName"]; ?></h4></span></strong>
		</div>
		<div class="col-md-6">
			<strong><h5>Escuela:</h5><span><h4><?php echo $datos["escName"]; ?> <?php echo $datos['escid'];?></h4></span></strong>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		var ajax_data = {
   			"escid": "<?php echo $datos['escid'];?>"
   		};
		$.ajax({
			type : 'post',
			url : '/curricula/show/curriculas/',
			data : ajax_data,
			success : function(data){
				$("#conten").html(data);
			}
		});
	});
</script>
<?php } ?>
<div id="conten"></div>
