<p class="titleRegister text-muted"><span class="glyphicon glyphicon-bookmark"></span> Matricula <span class="text-info"><?php echo $this->period['name'] ?></span></p>
<hr>
<?php if ($this->dataPrograms): ?>
	<div class="paymentBank" title="Recuerda Pagar a la Cuenta <?php echo $this->num_cuenta ?>" ><span class="glyphicon glyphicon-credit-card"></span> Pago al Banco <p class="payment">S/. 0</p></div>
	<hr>
	<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Esto son los cursos que estan disponibles en Idiomas.</p>
	
	<?php foreach ($this->dataPrograms as $c => $program): ?>
		<div class="program">
			<form class="formCourse">
			<input type="hidden" name="perid" value="<?php echo $program['perid'] ?>">
			<input type="hidden" name="cid" value="<?php echo $program['courseId'] ?>">
			<input type="hidden" name="pid" value="<?php echo $program['studentId'] ?>">
			<div class="detailProgram">
				<p class="courseIcon"><span class="glyphicon glyphicon-book"></span></p>
				<p class="courseName"><?php echo $program['courseName'] ?></p>
				<p class="coursePrice" title="Costo"><?php echo 'S/. '.$program['costo'] ?></p>
				<?php if ($program['alreadyRegister'] == 'no'): ?>
				<div class="divSelectTurno" id="selectTurno<?php echo $c ?>" numprogram="<?php echo $c ?>" hidden>
					<select class="selectTurno form-control" courseid="<?php echo $program['courseId'] ?>" name="turno">
						<?php foreach ($program['turnos'] as $turno): ?>
							<option value="<?php echo $turno['turnoid'] ?>"><?php echo $turno['turnoid'] ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<?php 
					$btnRegister = 'Matricularme';
				else: 
					$btnRegister = 'Matriculado';
				endif ?>
				<a href="##" numprogram="<?php echo $c ?>" class="btnRegister btn btn-success form-control" id="btnRegister<?php echo $c ?>"><?php echo $btnRegister ?></a>
			</div>
			<div class="detailRegister" id="detailRegister<?php echo $c ?>" numprogram="<?php echo $c ?>" hidden>
				<div class="detailTurno">
					<?php if ($program['alreadyRegister'] == 'no'): ?>
						<p class="text-muted text-success" id="questionConfirm<?php echo $c ?>">¿Seguro que desea llevar este curso?, si es asi elija el turno y confirme la matricula.</p>
						<p class="text-muted text-success" id="msgQuestionConfirm<?php echo $c ?>" hidden>Matricula Realizada</p>
						<hr>
						<?php foreach ($program['turnos'] as $cTurno => $turno): ?>
							<?php if ($cTurno != 0):
								$esconder = 'hidden';
							else:
								$esconder = '';
							endif ?>
							<p class="titleFrecuencia frecuenciaData<?php echo $program['courseId'] ?> changeDataTurno<?php echo $turno['turnoid'].$program['courseId'] ?>" <?php echo $esconder ?>><span class="glyphicon glyphicon-time"></span> Dias y Horario | Turno <?php echo $turno['turnoid'] ?></p>
							<p id="frecuenciaTurno<?php echo $turno['turnoid'].$program['courseId'] ?>" class="frecuenciaData<?php echo $program['courseId'] ?> text-muted changeDataTurno<?php echo $turno['turnoid'].$program['courseId'] ?>" <?php echo $esconder ?>>
								<?php echo $turno['frecuencia'] ?>
							</p>
						<?php endforeach ?>
					<?php else: ?>
						<p class="text-muted text-success" id="msgQuestionConfirm<?php echo $c ?>">Matricula Realizada</p>
						<hr>
						<?php foreach ($program['turnos'] as $cTurno => $turno): ?>
							<?php if ($program['turnoRegistrado'] == $turno['turnoid']): ?>
								<p class="titleFrecuencia"><span class="glyphicon glyphicon-time"></span> Dias y Horario | Turno <?php echo $turno['turnoid'] ?></p>
								<p class="text-muted">
									<?php echo $turno['frecuencia'] ?>
								</p>
							<?php endif ?>
						<?php endforeach ?>
					<?php endif ?>
				</div>
			<?php if ($program['alreadyRegister'] == 'no'): ?>
				<div class="btnsConfirm" id="btnsConfirm<?php echo $c ?>">
					<a href="##" class="btnCloseDetailRegister btn btn-danger">No por ahora</a>
					<input type="submit" class="btnConfirmRegister btn btn-info form-control" value="Si, deseo llevar este curso" id="btnConfirmRegister<?php echo $c ?>">
					<div class="chargeWhenRegister" id="chargeWhenRegister<?php echo $c ?>"></div>
				</div>
				<div class="msgConfirmRegister" id="msgConfirmRegister<?php echo $c ?>" hidden>
					<span class="iconConfirm glyphicon glyphicon-thumbs-up"></span>
					<p><span class="glyphicon glyphicon-info-sign"></span> Matricula Realizada con Exito!</p>
					<p>Dirigete al Centro de Idiomas para finalizar la validación.</p>
				</div>
			<?php else: ?>
				<div class="msgConfirmRegister" id="msgConfirmRegister<?php echo $c ?>">
					<span class="iconConfirm glyphicon glyphicon-thumbs-up"></span>
					<p><span class="glyphicon glyphicon-info-sign"></span> Matricula Realizada con Exito!</p>
					<p>Dirigete al Centro de Idiomas para finalizar la validación.</p>
				</div>
			<?php endif ?>
			</div>
			</form>	
		</div>
	<?php endforeach ?>

	<script>
	$(function(){
		var numProgram         = '';
		var numProgramforSlide = '';

		$('.btnRegister').on('click', function(){
			numProgram = $(this).attr('numprogram');

			$('.detailRegister').each(function(index, element){
				numProgramforSlide = $(element).attr('numprogram');
				if (numProgramforSlide != numProgram) {
					$(element).slideUp();
				};
			});

			$('.divSelectTurno').each(function(index, element){
				numProgramforSlide = $(element).attr('numprogram');
				if (numProgramforSlide != numProgram) {
					$(element).slideUp();
				};
			});

			$('#detailRegister' + numProgram).slideToggle();
			$('#selectTurno' + numProgram).slideToggle();
		});

		$('.btnCloseDetailRegister').on('click', function(){
			$('#detailRegister' + numProgram + ', #selectTurno' + numProgram).slideUp();
		});

		$('.paymentBank').hover(function(){
			$(this).tooltip('toggle');
		});

		var changeTurno = '';
		var courseId    = '';
		$('.selectTurno').on('change', function(){
			changeTurno = $(this).val();
			courseId    = $(this).attr('courseid');
			$('.frecuenciaData' + courseId).slideUp();
			$('.changeDataTurno' + changeTurno + courseId).slideDown();
		});

		var formData = '';
		$('.formCourse').on('submit', function(e){
			e.preventDefault();
			$('#btnConfirmRegister' + numProgram).attr('disabled', 'disabled');
			$('#chargeWhenRegister' + numProgram).html('<img src="/img/spinner.gif" alt="L" />');
			formData = $(this).serialize();
			registerStudent(formData, numProgram);
		});

		//Funciones

		//Registar Estudiante
		function registerStudent(formData, numProgram){
			$.ajax({
				type : 'post',
				url : '/alumno/idiomas/registerstudent/',
				data : formData,
				success : function(data){
					console.log(data);
					if (data == 1) {
						$('#questionConfirm' + numProgram + ', #btnsConfirm' + numProgram + ', #selectTurno' + numProgram).slideUp();
						$('#selectTurno' + numProgram).html('');
						$('#btnRegister' + numProgram).html('Matriculado');
						$('#msgQuestionConfirm' + numProgram + ', #msgConfirmRegister' + numProgram).slideDown();

					}else{
						$('#btnConfirmRegister' + numProgram).removeAttr('disabled', 'disabled');
					};
					$('#chargeWhenRegister' + numProgram).html('<img src="/img/spinner.gif" alt="L" />');
				}
			});
		};
	});
	</script>

<?php elseif ($this->validate): ?>
	<p class="text-muted text-center"><span class="glyphicon glyphicon-ok"></span> Vaya! Se matriculo a todos los cursos<span class="text-success">, dirijase a Matricula Actual para mas detalles : ) </span></p>
<?php else: ?>
	<p class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign"></span> Aun no existen cursos <span class="text-danger">para este periodo</span></p>
<?php endif ?>
