<div id="idperson">
    <?php
    if ($this->datauser || $this->datauser[0]){ 
            // print_r($this->datauser);exit();
        
    ?>

    <table class="table span9 table-bordered">
        <thead>
        <tr>
                <th><center>#</center></th>
                <th><center>Código</center></th>
                <th><center>DNI</center></th>
                <th>Apellidos y Nombres</th>
                <th><center>Rol</center></th>
                <th><center>Escuela</center></th>
                <th><center>Estado</center></th>
                <th colspan='2'><center>Operación</center></th>
        </tr>
        </thead>
    <?php
        $c=0;
        foreach ($this->datauser as $info) {
            $c++;
          ?>
            <tr>
                <td><center><?php echo $c?></center></td>
                <td><center><?php echo $info['uid']?></center></td>
                <td><center><?php echo $info['pid']?></center></td>
                <td><?php echo $info['last_name0']." ".$info['last_name1'].", ".$info['first_name'];?></td>
                <td><center><?php echo $this->inforol[$c-1]['name']?></center></td>
                <td><center><?php echo $this->infoesc[$c-1]['name']?></center></td>
                <?php
                switch ($info['state']) {
                    case 'A':
                        ?><td ><center>ACTIVO</center></td><?php
                        break;
                    case 'I':
                        ?><td ><center>INACTIVO</center></td><?php
                        break;
                    case 'B':
                        ?><td ><center>BOQUEADO</center></td><?php
                        break;
                    case 'S':
                        ?><td ><center>SUSPENDIDO</center></td><?php
                        break;
                        break;
                    case 'E':
                        ?><td ><center>BAJA</center></td><?php
                        break;                            
                }
                ?>
                <td><center><a href=""><span class='glyphicon glyphicon-pencil'></span></a></center></td>
                <td><center><a href=""><span class='glyphicon glyphicon-trash'></span></a></center></td>

            </tr>
          <?php  
        }  
    }
    else{
    ?>
    <div class="alert alert-info" style='font-size:15px'><b>El usuario no se ENCUENTRA registrado en el SISTEMA...
        Registrar Aqui </b><a class='btn btn-info' href="/admin/person/new"><span class='glyphicon glyphicon-pencil'>Nuevo</a></div>
    <?php
    exit();
    }
    ?>
    </table>
          
</div>