<div id="idperson">
    <?php
    if ($this->datauser and $this->datauser[0]){ 
        
    ?>

    <table class="table span9 table-bordered">
        <thead>
        <tr>
                <th><center>#</center></th>
                <th><center>Código</center></th>
                <th><center>DNI</center></th>
                <th>Apellidos y Nombres</th>
                <th><center>Rol</center></th>
                <th><center>Escuela</center></th>
                <th><center>Estado</center></th>
                <th><center>Operación</center></th>
        </tr>
        </thead>
    <?php
        $c=0;
        foreach ($this->datauser as $info) {
            $c++;
          ?>
            <tr>
                <td><center><?php echo $c?></center></td>
                <td><center><?php echo $info['uid']?></center></td>
                <td><center><?php echo $info['pid']?></center></td>
                <td><?php echo $info['last_name0']." ".$info['last_name1'].", ".$info['first_name'];?></td>
                <td><center><?php echo $this->inforol[$c-1]['name']?></center></td>
                <td><center><?php echo $this->infoesc[$c-1]['name']?></center></td>
                <?php
                switch ($info['state']) {
                    case 'A':
                        ?><td ><center>ACTIVO</center></td><?php
                        break;
                    case 'I':
                        ?><td ><center>INACTIVO</center></td><?php
                        break;
                    case 'B':
                        ?><td ><center>BOQUEADO</center></td><?php
                        break;
                    case 'S':
                        ?><td ><center>SUSPENDIDO</center></td><?php
                        break;
                        break;
                    case 'E':
                        ?><td ><center>BAJA</center></td><?php
                        break;
                    case '':
                        ?><td><center></center></td><?php
                        break;                            
                }
                ?>
                <td><center>
                <?php
                if (($this->inforol[$c-1]['rid']!='AL') and ($this->inforol[$c-1]['rid']!='EG') and ($this->inforol[$c-1]['rid']!='')) { ?>
                    <a href="/admin/user/updateuser/uid/<?php echo base64_encode($info['uid'])?>/pid/<?php echo base64_encode($info['pid'])?>/escid/<?php echo base64_encode($info['escid'])?>/subid/<?php echo base64_encode($info['subid'])?>"><span class='glyphicon glyphicon-pencil'></span></a></center></td>
                <?php
                }
                ?>      
                <!-- <td><center><a href=""><span class='glyphicon glyphicon-trash'></span></a></center></td> -->

            </tr>
          <?php  
        }  
    }
    else{
    ?>
    <div class="alert alert-info" style='font-size:15px'><b>El usuario no se ENCUENTRA registrado en el SISTEMA...        Registrar Aqui </b><a id='newperson' class='btn btn-info' href="#"><span class='glyphicon glyphicon-pencil'></span> Nuevo</a></div>
    <?php
    }
    ?>
    </table>
          
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style='width:1000px;'>
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title"><b class='text-info'> <center> NUEVA PERSONA </center></b></h2>
            </div>
            <div class="modal-body">
                <div id='nueva_persona'></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#newperson").click(function(){   
        $('#myModal').modal('show');            
        var url="/admin/person/new/u/A";
        $("#nueva_persona").html("</br></br><center><img src='/img/spinner.gif'> Cargando...</center>");
        $("#nueva_persona").load(url);
    });

</script>