<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-user"></span> CREAR USUARIO');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/admin/user/getuser" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table span9 table-striped table-bordered table-condensed">
        <tr>
            <td colspan='3'><a href="/admin/user/new" style='float:right' class='btn btn-info'><span class='glyphicon glyphicon-pencil'></span> Nuevo Usuario</a></td>
        </tr>
        <tr>
            <td><center>DNI</center></td>
            <td><center>Nombres y Apellidos</center></td>
            <td><center>Buscar por Código Usuario</center></td>
        </tr>
        <tr>                    
            <td><center><div style='width: 200px'><?php echo $this->fm->pid ?></center></td>
            <td><center><div style='width: 400px'><?php echo $this->fm->name ?></center></td>
            <td><center><div style='width: 200px'><?php echo $this->fm->uid ?></center></td>
        </tr>
    </table>
</form>
<div  id="cargadatos_"></div> 
<script>
    $("#name, #pid, #uid").keypress(function (e) {
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#pid').val();
            var nom =  $('#name').val();
            count=codi.length;
            if (count==8 || count==0)
            {
                $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
                $("#frmFiltroDoc").submit();
            }
            else
            {
                alert("Ingrese un DNI valido");
                $('#pid').val('');
            }
            var codi1 = $('#uid').val();
            count1=codi1.length;
            if (count1==10 || count1==0) {
                $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
                $('#frmFiltroDoc').submit();
            }
            else
            {
                alert("Ingrese un Código válido");
                $('#uid').val('');
            }   
        }
    });
    
    $("#frmFiltroDoc").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#cargadatos_').html(data);                                 
            }
        }); 
        return false;
    });

function validNumber(e) {
    var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
    }
function soloLetras(e){
       key = e.keyCode || e.which;
       tecla = String.fromCharCode(key).toLowerCase();
       letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
       especiales = [8,37,39,46];

       tecla_especial = false
       for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }

        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }     
</script>