<form id="<?php echo $this->fm->getName();?>" name="<?php echo $this->fm->getName();?>" action="/admin/user/newuser"method="Post" enctype="application/x-www-fm-urlencode">
	<table>
		<tr>
			<th>Sede: </th>
			<td><div style='width: 200px;'><?php echo $this->fm->subid;?></td>
			<th>Escuela: </th>
			<td><div style='width: 200px;'><?php echo $this->escid;?></td>
		</tr>
		<tr>
			<th>Rol: </th>
			<td><div style='width: 200px'><?php echo $this->fm->rid?></td>
			<th>Estado: </th>
			<td><div style='width: 200px'><?php echo $this->fm->state?></td>
		</tr>	
		<tr>
			<th>Comentario: </th>
			<td colspan='4'><div style='width: 450px'><?php echo $this->fm->comments?></td>
		</tr>
		</table><br>
	<div style='margin-left:250px'><?php echo $this->fm->Guardar?></div>
<input type="hidden" name='pid' value='<?php echo $this->pid?>'>
</form>
<script type="text/javascript">
	$("#subid").change(function(){
    var subid=$(this).val();
    // alert(subid);
    url="/admin/user/filterspeciality/subid/"+subid;
    $("#escid").load(url);
});             
</script> 