<form id="<?php echo $this->fm->getName();?>" name="<?php echo $this->fm->getName();?>" action="<?php echo $this->fm->getAction();?>"method="Post" enctype="application/x-www-fm-urlencode">
	<table>
		<tr>
			<th><h4>MODIFICAR USUARIO</h4></th>
		</tr>	
	</table>	
	<table>
		<tr>
			<th>Sede: </th>
			<td><div style='width: 200px;'><?php echo $this->fm->subid;?></td>
			<th>Escuela: </th>
			<td><div style='width: 200px;'><?php echo $this->fm->escid;?></td>
		</tr>
		<tr>
			<th>Rol: </th>
			<td><div style='width: 200px'><?php echo $this->fm->rid?></td>
			<th>Estado: </th>
			<td><div style='width: 200px'><?php echo $this->fm->state?></td>
		</tr>	
		<tr>
			<th>Comentario: </th>
			<td colspan='4'><div style='width: 450px'><?php echo $this->fm->comments?></td>
		</tr>
		</table><br>
	<div style='margin-left:250px'><?php echo $this->fm->Actualizar?></div>
<input type="hidden" name='rid' value='<?php echo $this->rid?>'>
</form>
<script type="text/javascript">
	$("#subid").change(function(){
    var subid=$(this).val();
    // alert(subid);
    url="/admin/user/filterspeciality/subid/"+subid;
    $("#escid").load(url);
});             
</script>  