<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Distribución');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<div class="row">
	<div class="col-md-1 col-md-offset-1">
		<h5 class="text-info">Año</h5>
		<select class="form-control" name="Anio" id="anio">
			<option value="">Seleccione Año</option>
			<?php $anio = date('Y');
			for ($i=$anio; $i >= 2000 ; $i--) { ?>
 				<option value="<?php echo $i?>"><?php echo $i?></option>
 			<?php } ?>
		</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-info">Periodo</h5>
		<select name="Periods" id="periods" class="form-control">
			<option value="">Primero Seleccione un Año</option>
		</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-info">Facultad</h5>
		<select name="faculty" id="faculty" class="form-control">
			<option value="">Seleccione Facultad</option>
			<?php
			foreach ($this->dataf as $dataf) {	
				if ($dataf['facid']<>"NINGUN") { ?>
 					<option value="<?php echo $dataf['facid']?>"><?php echo strtoupper($dataf['name'])?></option>
				<?php		
				}
 			} ?>
		</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-info" oncontextmenu='return false;' onmousedown='return false;' onselectstart='return false;'>_</h5>
		<a id="show" href="#" class="btn btn-success">Mostrar Distribucion</a>
	</div>
</div>
<hr>
<br>
<div id="data"></div>
<div class="row">
<div id="error1" class="alert alert-warning text-center col-xs-12">
	<h3><strong>Error!</strong> Seleccione un Periodo</h3>
</div>
	<div id="error2" class="alert alert-warning text-center col-xs-12">
		<h3><strong>Error!</strong> Seleccione una Facultad</h3>
	</div>
</div>


<script>
	$('#error1').fadeOut('fast');
	$('#error2').fadeOut('fast');
	$('#anio').change(function(){
		$('#anio option:selected').each(function(){
			var anio = $(this).val();
			var ajax_data = {
                            "anio" : anio,
                            };
			$.ajax({
                type : 'post',
                url : '/admin/opendistribution/lperiodo/',
                data : ajax_data,
                success: function(data){
            		$('#periods').html(data);
            
                }
            });

		});
	});

	$('#show').click(function(){
		
		var perid = $('#periods').val();
		var facid = $('#faculty').val();
		if (perid){
			if (facid) {
					$("#data").show();
					$('#error1').fadeOut('fast');
					$('#error2').fadeOut('fast');
					$('#data').html('<center><img class="text-center" src="/img/spinner.gif"></center>');
					var ajax_data = {
                            "perid" : perid,
                            "facid" : facid,
                            };
					$.ajax({
		                type : 'post',
		                url : '/admin/opendistribution/view/',
		                data : ajax_data,
		                success: function(data){
		            		$('#data').html(data);
		                }
		            });	
			}
			else{
				$("#data").hide();
				$('#error1').fadeOut('fast');
				$('#error2').fadeIn('slow');
			}
		}else{
			$("#data").hide();
			$('#error1').fadeIn('slow');
		}
	});
</script>