<?php if ($this->dis): ?>
		<div class="row">
        <div class="col-md-2 col-md-offset-1">
            <h5 class="text-muted">
                <strong>Leyenda</strong>
            </h5>
        </div>
        <div class="col-md-2">
            <h5 class="text-muted">
                <img src="/img/circulo-amarillo.png"><span class="text-warning"> <b>Recibido</b></span>
            </h5>
        </div>
        <div class="col-md-2">
            <h5 class="text-muted">
                <img src="/img/circulo-rojo.png"><span class="text-danger"> <b>Observado</b></span>
            </h5>
        </div>
        <div class="col-md-2">
            <h5 class="text-muted">
                <img src="/img/circulo-verde.png"><span class="text-success"> <b>Todo esta Correcto</b></span>
            </h5>
        </div>
        <div class="col-md-2">
            <h5 class="text-muted">
                <img src="/img/circulo-azul.png"><span class="text-info"> <b>Borrador</b></span>
            </h5>
        </div>
    </div>
	<hr>
	<table class="table table-hover table-condensed table-bordered" style="font-size:14px">
	<caption><h2>Distribuciones</h2></caption>
	<thead>
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Nombre de la Escuela</th>
			<th class="text-center">Fecha de Registro</th>
			<th class="text-center">Ver</th>
			<th class="text-center">Estado</th>
			<th class="text-center">Opciones</th>
		</tr>

	</thead>

	<tbody>
		<?php
		$i=0;
		foreach ($this->dis as $distrib) {
			switch ($distrib['state']) {
				case 'A': 	$state = "<img src='/img/circulo-amarillo.png'>"; 
							$namestate = "Enviado";
							$clase="warning";
							break;
				case 'I': 	$state = "<span style='font-size:24px' class='glyphicon glyphicon-info-sign'></span>"; 
							$namestate = "Inactivo";
							$clase="active";
							$temp="active";
							break;
				case 'C': 	$state = "<img src='/img/circulo-verde.png'>"; 
							$namestate = "Correcto";
							$clase="success";
							break;
				case 'O': 	$state = "<img src='/img/circulo-rojo.png'>"; 
							$namestate = "Observado";
							$clase="danger";
							break;
				case 'B': 	$state = "<img src='/img/circulo-azul.png'>"; 
							$namestate = "Borrador";
							$clase="info";
							break;
			}
			$valor=$this->valor;
				$i++;
			?>
			<tr style="padding:0px">
				<td class="text-center"><?php echo $i?></td>
				<td class="text-center <?php echo $clase ?>" > <p class="text-<?php echo $clase ?>"><?php echo $distrib['name']?></p> </td> 
				<td class="text-center" ><?php echo substr($distrib['created'],0,10)?></td>
				<td  class="text-center">
					<a data-toggle="tooltip" title="Ver" id="seeDistribution<?php echo $distrib['number']?>" href="#" onclick="javascript: window.open('/distribution/printdistribution/index/perid/<?php echo base64_encode($distrib['perid'])?>/distid/<?php echo base64_encode($distrib['distid'])?>/escid/<?php echo base64_encode($distrib['escid'])?>/subid/<?php echo base64_encode($distrib['subid'])?>/t/U','Ver distribución','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=850,height=750')"><span class="glyphicon glyphicon-eye-open"></span>
	                </a>
				</td>
				<td class='text-center'>
					<span data-toggle="tooltip" title="<?php echo $namestate?>"><?php echo $state?></span>
				</td>
				<td class="text-center ">
				<?php if ($this->rol=="AD") {?>
					<?php if ($distrib['state']=="C" or $distrib['state']=="O" or $distrib['state']=="A" or $distrib['state']=="I") { ?>
						<a class="abrirDis btn btn-info form-control" state="B" data-toggle="modal" data-target="#myModal" distid='<?php echo base64_encode($distrib['distid'])?>' perid='<?php echo base64_encode($distrib['perid'])?>' escid='<?php echo base64_encode($distrib['escid']);?>' subid='<?php echo base64_encode($distrib['subid'])?>'><span class="glyphicon glyphicon-edit"></span> En borrador</a>
						<?php } elseif($distrib['state']=="B"){?>
							<a class="btn btn-success form-control aceptar" state="C" data-toggle="modal" data-target="#myModal" distid='<?php echo base64_encode($distrib['distid'])?>' perid='<?php echo base64_encode($distrib['perid'])?>' escid='<?php echo base64_encode($distrib['escid']);?>' subid='<?php echo base64_encode($distrib['subid'])?>'> <span class="glyphicon glyphicon-check"></span> Aceptar</a>
					<?php }else{ ?>
				<?php } ?>	
				<?php } else { ?>
					<?php if ($distrib['state']=="C") {	?>
							<a class="abrirDis btn btn-info form-control" state="O" href="#" data-toggle="modal" data-target="#myModal" distid='<?php echo base64_encode($distrib['distid'])?>' perid='<?php echo base64_encode($distrib['perid'])?>' escid='<?php echo base64_encode($distrib['escid']);?>' subid='<?php echo base64_encode($distrib['subid'])?>'>
								<span class="glyphicon glyphicon-circle-arrow-right">
								</span>
							</a>
						
						<?php }else{ ?>
								<span class="glyphicon glyphicon-ban-circle " data-toggle="tooltip" title="Desactivada"></span>
						<?php } ?>
				<?php } ?>
				</td>
			</tr>
			<script> 
            $(function(){
            	$('#seeDistribution<?php echo $distrib['number']?>').hover(function(){
					$('#seeDistribution<?php echo $distrib['number']?>').tooltip('toggle');
				});
            });
        	</script>
			<?php } ?>
	</tbody>
	</table>
<?php else: ?>
	<div class='col-md-10 col-md-offset-1 cont-font-not-register alert alert-info'>
		<h3 class="text-info text-center"><span class='glyphicon glyphicon-exclamation-sign' ></span> <b>NO EXISTEN DISTRIBUCIONES DE ESTA FACULTAD</b></h3> 
	</div>
<?php endif ?>
<div id="cargaqui"></div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="margin-top:10%">
  <div class="modal-dialog" style="width:30%">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><span class='text-info'><b>ESTA SEGURO DE "MODIFICAR" LA DISTRIBUCIÓN? </b></span></h4>
      </div>
      <div class="modal-body text-right">
        	<button id="aceptar" type="button" class="btn btn-success"><span class='glyphicon glyphicon-ok'></span> Aceptar</button>
        	<button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-log-out'></span> Cancelar</button>
      </div>
    </div>
  </div>
</div>


<script>
$(function(){
	var ajax_data;
	$("span").tooltip();
	$("a").tooltip();
	$(".abrirDis, .aceptar").click(function(e){
		ajax_data = {
			'escid' : $(this).attr('escid'), 
			'subid' : $(this).attr('subid'),
			'distid' : $(this).attr('distid'),
			'perid' : $(this).attr('perid'),
			'state' : $(this).attr('state')

		};
		console.log(ajax_data);
	});

	$("#aceptar").click(function(e) {
		e.preventDefault();
		$.ajax({
            type : 'post',
            url : '/admin/opendistribution/opendistribution/',
            data : ajax_data,
            success: function(data){
            	console.log(data);
            	$("#myModal").modal("hide");
    		}
		});
	});
	$ ('#myModal').on('hidden.bs.modal',function()  { 
		var perid = $('#periods').val();
			var facid = $('#faculty').val();
			var ajax_dat = {
			"perid" : perid,
			"facid" : facid
		};
		$.ajax({
			type : 'post',
			url : '/admin/opendistribution/view/',
			data : ajax_dat,
			success: function(data){
				$('#data').html(data);
			}
		});
	});
});
</script>
