<style type="text/css">
	.importante:hover{
		font-size: 22px;
	}
	
	strong{
		font-size: 24px;
		color:black;
	}
	span{
		font-size: 20px;
	}
	th{
		background:black;
		color: #fff
	}

</style>
<?php if ($this->dis): ?>
	<div class="row" style="height:70px; border-top: 1px dotted gray; border-bottom: 1px dotted gray;">
		
		<div class="col-md-2 col-md-offset-1">
			<h5 class="text-muted">
				<strong>Leyenda</strong>
			</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-muted">
				<img src="/img/circulo-verde.png"><span class="text-success importante"> Enviado</span>
			</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-muted">
				<img src="/img/circulo-azul.png"><span class="text-info importante"> Borrador</span>
			</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-muted">
				<img src="/img/circulo-amarillo.png"><span class="text-warning importante"> Observado</span>
			</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-muted">
				<img src="/img/circulo-rojo.png"><span class="text-danger importante"> Cerrado/Inactivo</span>
			</h5>
		</div>
	</div>
	<hr>
	<table class="table table-hover table-striped" style="font-size:14px">
	<caption><h2 style="color:red;background: rgba(30,144,255,.5);">Distribuciones</h2></caption>
	<thead>
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Nombre de la Escuela</th>
			<th class="text-center">Fecha de Registro</th>
			<th class="text-center">Ver</th>
			<th class="text-center">Estado</th>
			<th class="text-center">Opciones</th>
		</tr>

	</thead>

	<tbody>
		<?php
		$i=0;
		foreach ($this->dis as $distrib) {
			switch ($distrib['state']) {
				case 'A': 	$state = "<img src='/img/circulo-verde.png'>"; 
							$namestate = "Enviado";
							break;
				case 'I': 	$state = "<img src='/img/circulo-rojo.png'>"; 
							$namestate = "Inactivo";
							break;
				case 'C': 	$state = "<img src='/img/circulo-rojo.png'>"; 
							$namestate = "Cerrado";
							break;
				case 'O': 	$state = "<img src='/img/circulo-amarillo.png'>"; 
							$namestate = "Observado";
							break;
				case 'B': 	$state = "<img src='/img/circulo-azul.png'>"; 
							$namestate = "Borrador";
							break;
			}
			$valor=$this->valor;
			
				$i++;
			?>
			<tr>
				
				<td class="text-center"><?php echo $i?></td>
				<td class="text-center"><?php echo $distrib['name']?></td> 
				<td class="text-center" style="width:6%"><?php echo substr($distrib['created'],0,10)?></td>
				<td  class="text-center">
					<h4><a id="seeDistribution<?php echo $distrib['number']?>" href="#" onclick="javascript: window.open('/distribution/printdistribution/index/perid/<?php echo base64_encode($distrib['perid'])?>/distid/<?php echo base64_encode($distrib['distid'])?>/escid/<?php echo base64_encode($distrib['escid'])?>/subid/<?php echo base64_encode($distrib['subid'])?>/t/U','Ver distribución','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=850,height=750')"><span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="Ver"></span>
	                </a></h4>	
				</td>

				<td class='text-center'>
					<span class='span' data-toggle="tooltip" title="<?php echo $namestate?>"><?php echo $state?></span>
				</td>

				<td class="text-center">
					<?php if ($distrib['state']=="C") {	?>
					<h4>
						<a class="abrirDis" href="#" data-toggle="modal" data-target="#myModal" distid='<?php echo base64_encode($distrib['distid'])?>' perid='<?php echo base64_encode($distrib['perid'])?>' escid='<?php echo base64_encode($distrib['escid']);?>' subid='<?php echo base64_encode($distrib['subid'])?>'>
							<span class="glyphicon glyphicon-circle-arrow-right" data-toggle="tooltip" title="pulse para abrir">								
							</span>
						</a>
					</h4>
					<?php
					}
					else{?>
					<h4>
							<span class="glyphicon glyphicon-ban-circle bloqueado" data-toggle="tooltip" title="Desactivada"></span>
					</h4>
					<?php
					}
					?>
				</td>
			</tr>

			
			<script> 
            $(function(){
            	$('#seeDistribution<?php echo $distrib['number']?>').hover(function(){
					$('#seeDistribution<?php echo $distrib['number']?>').tooltip('toggle');
				});
            });
        	</script>
			<?php				
		}
		?>
	</tbody>
	</table>
<?php else: ?>
	<div class='col-md-10 col-md-offset-1 cont-font-not-register alert alert-info'>
		<h3 class="text-info text-center"><span class='glyphicon glyphicon-exclamation-sign' ></span> <b>NO EXISTEN DISTRIBUCIONES DE ESTA FACULTAD</b></h3> 
	</div>
<?php endif ?>

<div id="cargaqui"></div>
<!-- Modal -->
<div class="modal fade" id="myModal" style="margin-top:10%">
  <div class="modal-dialog" style="width:30%">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><span class='text-info'><b>ESTA SEGURO DE "ABRIR" LA DISTRIBUCIÓN? </b></span></h4>
      </div>
      <div class="modal-body text-right">
        	<button id="aceptar" type="button" class="btn btn-success"><span class='glyphicon glyphicon-ok'></span> Aceptar</button>
        	<button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-log-out'></span> Cancelar</button>
      </div>
    </div>
  </div>
</div>

<script>
$(function(){
	var ajax_data;
	$(".glyphicon").tooltip();
	$("span").tooltip();
	$(".abrirDis").click(function(e){
		ajax_data = {
			'escid' : $(this).attr('escid'), 
			'subid' : $(this).attr('subid'),
			'distid' : $(this).attr('distid'),
			'perid' : $(this).attr('perid'),
		};
	});
	$("#aceptar").click(function(e) {
		e.preventDefault();
		$.ajax({
            type : 'post',
            url : '/admin/opendistribution/opendistribution/',
            data : ajax_data,
            success: function(data){
            	$("#myModal").modal("hide");
    		}
		});
	});
	$ ('#myModal').on('hidden.bs.modal',function()  { 
		var perid = $('#periods').val();
			var facid = $('#faculty').val();
			var ajax_dat = {
			"perid" : perid,
			"facid" : facid
		};
		$.ajax({
			type : 'post',
			url : '/admin/opendistribution/view/',
			data : ajax_dat,
			success: function(data){
				$('#data').html(data);
			}
		});
	});
});
</script>
 <div id="destino"></div> 
