<div align="right">
	<br>
	<a href="/register/registerealized/registerprint/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>/uid/<?php echo base64_encode($this->uid)?>" class='btn btn-success'><span class='glyphicon glyphicon-print'></span> Imprimir</a>
</div></br>
			<?php
			if ($this->newperiod) {
				foreach ($this->newperiod as $period) {
					$perid=$period['perid'];
					$pname=$period['name'];
					?>
	<div class="panel panel-primary">
			<div class="panel-heading">
					<p style='font-size:15px'><span class="glyphicon glyphicon-list"></span><?php echo " ".$perid." - ".$pname; 
						if ($this->rid!='AL') { ?>		
							<a href='/register/registerstudent/print/uid/<?php echo base64_encode($this->uid)?>/pid/<?php echo base64_encode($this->pid)?>/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>/perid/<?php echo base64_encode($perid)?>' class='btn btn-info' style='float:right; margin-left:10px; padding: 3px 12px'><span class='glyphicon glyphicon-file'></span> Copia FICHA</a>
						<?php
						}	
						?>	
							<a href="/register/registerealized/printperiod/perid/<?php echo base64_encode($perid)?>/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>/uid/<?php echo base64_encode($this->uid)?>" class='btn btn-info' style='float:right; padding: 3px 12px'><span class="glyphicon glyphicon-download-alt"></span> PDF</a><span class='glyphicon glyphicon cloud-download'></span>
					</p>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th class="col-md-1"><center>#</center></th>
						<th class="col-md-1"><center>Código</center></th>
						<th>Curso</th>
						<th class="clo-md-1"><center>Nota</center></th>
						<th class="col-md-1"><center>Turno</center></th>
						<th class="col-md-1"><center>Semestre</center></th>
						<th class="col-md-1"><center>Créditos</center></th>
					</tr>	
					<?php
					$a=0;
					$c=1;
					foreach ($this->data as $registrationcourses) {
						$state=$registrationcourses['state'];
						$perid1=$registrationcourses['perid'];
						$courseid=$this->datacourse[$a]['courseid'];
						$courseid1=$registrationcourses['courseid'];
						if($perid==$perid1){ 
						// print_r($this->datacourse);exit();
							if ($courseid=$courseid1) {
							?>
							<tr>
								<td><center><?php echo $c?></center></td>
								<td><center><?php echo $this->datacourse[$a]['courseid']?></center></td>	
								<td><?php echo $this->datacourse[$a]['name']?></td>
								<td><center>
									<?php
									if($registrationcourses['notafinal']==-2){ 
										echo 'N.S.P';
									}
									else{
										if($registrationcourses['notafinal']==-3){
											echo "Ret.";
										}
										else{
											echo $registrationcourses['notafinal'];
										}
									}
								?></center></td>
								<td><center><?php echo $registrationcourses['turno']?></center></td>
								<td><center><?php echo $this->datacourse[$a]['semid']?></center></td>
								<td><center><?php echo $this->datacourse[$a]['credits']?></center></td>
							</tr>
							<?php
							}
						}
						else{
							$c=0;
						}
					$a++;
					$c++;	
					}
					?>
			  	</table>
			</div>
	</div>	
	<?php
		}
	}
	else{    ?>
		<div class="alert alert-info" style='font-size:15px'><b>No EXISTE DATA en el sistema. </b></div>
	<?php
	}
	?>