<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
   
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div>
    <div style="text-align:left; font-size:12px;"><b>Codigo: </b><?php echo strtoupper($this->uid)?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <b>Alumno: </b><?php echo strtoupper($this->person[0]['last_name0']." ".$this->person[0]['last_name1'].", ".$this->person[0]['first_name'])?>
    </div>
</div>

<div>
    <div style="text-align: center; font-size:16px;margin-top:10px"><b> MATRÍCULA </b></div> <br/>
        <?php
        // print_r($this->dataperiod);exit();
            $perid=$this->dataperiod[0]['perid'];
            $pname=$this->dataperiod[0]['name'];
            ?>
        <table style="width:100%; margin-bottom:15px" border="1">
            <tr>
                <th colspan='7'><?php echo " ".$perid." - ".$pname?></th>
            </tr>       
        <tr>
            <th class='small'><center>#</center></th>
            <th class='small'><center>Código</center></th>
            <th class='small-400'>Curso</th>
            <th class='small'><center>Nota</center></th>
            <th class='small'><center>Turno</center></th>
            <th class='small'><center>Semestre</center></th>
            <th class='small'><center>Créditos</center></th>
        </tr>   
        <?php
        $a=0;
        $c=1;
        foreach ($this->data as $registrationcourses) {
            $courseid=$this->datacourse[$a]['courseid'];
            $courseid1=$registrationcourses['courseid'];
            // print_r($this->datacourse);exit();
            if ($courseid=$courseid1) {
                ?>
                <tr>
                    <td class='small'><center><?php echo $c?></center></td>
                    <td class='small'><center><?php echo $this->datacourse[$a]['courseid']?></center></td>    
                    <td class='small-400'><?php echo $this->datacourse[$a]['name']?></td>
                    <td class='small'><center>
                        <?php
                        if($registrationcourses['notafinal']==-2){ 
                            echo 'N.S.P';
                        }
                        else{
                            if($registrationcourses['notafinal']==-3){
                                echo "Ret.";
                            }
                            else{
                                echo $registrationcourses['notafinal'];
                            }
                        }
                    ?></center></td>
                    <td class='small'><center><?php echo $registrationcourses['turno']?></center></td>
                    <td class='small'><center><?php echo $this->datacourse[$a]['semid']?></center></td>
                    <td class='small'><center><?php echo $this->datacourse[$a]['credits']?></center></td>
                </tr>
                <?php
            }
            else{
                $c=0;
            }
        $a++;
        $c++;   
        }
        ?>
    </table>
</div>
<?php 
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,36,18,8,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');

    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Matrícula-'.$this->dataperiod[0]['name'].'.pdf','D');
    // $mpdf -> Output();
?>