<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div class="panel panel-primary col-md-12 table-responsive ">
    <div style="text-align: center; font-size:16px;margin-top:10px"><b> REPORTE DE SIAF </b></div> <br/>
    <table class="table text-center">
        <tr class="medium"> 
            <th colspan="9"><h4 class="text-primary"><center>EXPEDIENTES SIAF POR USUARIO AÑO</center></h4></th>
        </tr>
        <tr align="center" valign="middle"> 
            <td rowspan="2"><b><center>EXPEDIENTE</center></b></td>
            <td rowspan="2"><b><center>ESTADO</center></b></td>
            <td rowspan="2"><b><center>DETALLE</center></b></td>
            <td colspan="5"><b><center>FASES</center></b></td>
            <td rowspan="2"><b><center>MONTO</center></b></td>
        </tr>
        <tr align="center" valign="middle"> 
            <td><b>C</b></td>
            <td><b>D</b></td>
            <td><b>G</b></td>
            <td><b>P</b></td>
            <td><b>R</b></th>
        </tr>
        <?php
        foreach($this->subjects as $subject) { ?>
        <tr>
            <td><option><?php echo $subject['EXPEDIENTE']?></option></td>
            <td><option><?php echo $subject['ESTADO_ENV']?></option></td>
            <td><option><?php echo $subject['NOTAS']?></option></td>
            <td><option><?php echo $subject['FASE']?></option></td>
            <td>s</td>
            <td>s</td>
            <td>n</td>
            <td>n</td>
            <td>
                <option>
                    <?php if(($subject['MONTO']<>'')) {
                        echo $subject['MONTO'];
                    }
                    else{
                        echo "-";
                    }
                    ?>
                </option>   
            </td>
        </tr>
        <?php } ?>
    </table>
</div>

<?php
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');
    
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf -> Output('RecordNotas -'.$this->person['pid'].'.pdf','D');
    //$mpdf -> Output();  

?>