<div>
	<table class="table table-striped table-condensed">
		<tr>
			<th colspan="6" style="font-size:15px"><center>INGRESO DE NOTAS DE ACTAS ANTERIORES</center></th>
		</tr>
		<tr>
			<th>Año</th>
			<td class="col-lg-2">
				<select id='anio' class="form-control">
					<?php 
					$anio=date('Y');
					for ($i=$anio; $i>=1963; $i--) { ?>
						<option value="<?php echo $i?>"><?php echo $i?></option>
						<?php
					} ?>
				</select>
			</td>
			<th>Periodo:</th>
			<td class="col-lg-4">
				<select id="perid" class="form-control">
					<option value="">- Seleccione Periodo -</option>
				</select>
			</td>
			<th>Escuelas:</th>
			<td class="col-lg-4">
				<select id="escid" class="form-control">
					<option value="">- Seleccione -</option>
					<?php
					if ($this->escuelas) {
						foreach ($this->escuelas as $escuelas) { ?>
							<option value="<?php echo $escuelas['escid']?>"><?php echo $escuelas['name']?></option>
							<?php
						}
					}?>
				</select>
			</td>
		</tr>
		<tr>
			<th>Semestre:</th>
			<td>
				<select id="semid" class="form-control">
					<option value="">- Seleccione -</option>
				</select>
			</td>
			<th>Currículas:</th>
			<td>
				<select id="curid" class="form-control">
					<option value="">- Seleccione -</option>
				</select>
			</td>
			<th>Cursos:</th>
			<td>
				<select id="courseid" class="form-control">
					<option value="">- Seleccione -</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<center><a href="#" id="listar" class="btn btn-info">Listar Alumnos</a></center>
			</td>
		</tr>
	</table>
</div>
<div id="alumnos"></div>

<script type="text/javascript">
var anio=$("#anio").val();
$("#perid").load("/default/registernotesactas/lperiods/anio/"+anio);

$("#anio").change(function(){
	var anio=$(this).val();
	$("#perid").load("/default/registernotesactas/lperiods/anio/"+anio);
});

$("#perid").change(function(){
	var perid=$(this).val();
	var escid=$("#escid").val();
	if (escid!="") {
		$("#semid").load("/default/registernotesactas/lsemester/escid/"+escid+"/perid/"+perid);
	};
});




$("#escid").change(function(){
	var escid=$(this).val();
	var perid=$("#perid").val();
	$("#curid").load("/default/llenadonotasactas/lcurriculas/escid/"+escid);
	if (perid!="") {
		$("#semid").load("/default/llenadonotasactas/lsemestres/escid/"+escid+"/perid/"+perid);
	}else{
		alert("Seleccione el Periodo.");
	};
});

$("#curid").change(function(){
	var curid=$(this).val();
	var escid=$("#escid").val();
	var semid=$("#semid").val();
	var perid=$("#perid").val();
	if (semid=="") {
		alert("Seleccione un Semestre Académico.");
	}else{
		$("#courseid").load("/default/llenadonotasactas/lcursos/curid/"+curid+"/escid/"+escid+"/semid/"+semid+"/perid/"+perid);
	};
});

$("#semid").change(function(){
	var semid=$(this).val();
	var escid=$("#escid").val();
	var curid=$("#curid").val();
	var perid=$("#perid").val();
	if (curid!="") {
		$("#courseid").load("/default/llenadonotasactas/lcursos/curid/"+curid+"/escid/"+escid+"/semid/"+semid+"/perid/"+perid);
	};
});

$("#listar").click(function(){
	var curso=$("#courseid").val();
	var escid=$("#escid").val();
	var curid=$("#curid").val();
	var perid=$("#perid").val();
	var tmp=curso.split('--');
	if (curso!="") {
		$("#alumnos").html("<img src='/img/spinner.gif'>Cargando...");
		$("#alumnos").load("/default/llenadonotasactas/alumnos/curid/"+curid+"/escid/"+escid+"/courseid/"+tmp[0]+"/perid/"+perid+"/turno/"+tmp[1]+"/sedid/"+tmp[2]);
	}else{
		alert("Seleccione un Curso.");
	};
});
</script>