<?php $this->placeholder('Btnnav')->append('<a href="javascript:history.back()" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-tasks"></span> HISTORIAL');?>
<div class="panel panel-default">
	<table class="table">
		<tr>
			<td><h5>Codigo <b><br><?php echo $this->person[0]["uid"]?></b></h5></td>
			<td><h5>Nombre <b><br><?php echo $this->person[0]["last_name0"]." ".$this->person[0]["last_name1"]." ".$this->person[0]["first_name"]?></b></h5></td>
			<td><h5>Factultad de <b><?php echo $this->person["facesp"][0]["nomfac"]?></b></h5>
				<h5>Escuela de <b><?php echo $this->person["facesp"][0]["nomesc"]?></b></h5></td>
		</tr>
	</table>
	<div class="panel-heading">
		<h4><b>Matricula Por Curricula</b></h4>
	</div>
	<div class="panel-body">
		<?php if($this->courpercur){
			//print_r($this->courlleact);?>
		<div class="panel panel-default">
			<?php  $semid=0;
			$c=0;
			foreach ($this->courpercur as $sem) {
				if($sem['semid']<>$semid){?>
					<div class="panel-heading">
						<b>SEMESTRE <?php echo $sem['semid']?></b>
					</div>
					<div class="panel-body">
						<table class="table">
							<tr>
								<th><center>Codigo</center></th>
								<th>Cursos</th>
								<th><center>Tipo</center></th>
								<?php if($sem['semid']<>"1"){?>
									<th><center>Requisito</center></th>
								<?php }else{?>
									<th></th>
								<?php }?>
								<th><center>Creditos</center></th>
								<th>Nota</th>
								<th>Estado</th>
							</tr>
							
					<?php $semid=$sem['semid'];
						foreach ($this->courpercur as $courses) {
							if($courses['semid']==$semid) {?>
								<tr>
									<td align="center"><?php echo $courses['courseid']?></td>
									<td><?php echo $courses['name']?></td>
									<td align="center">
										<?php if($courses['type']=="E"){?>
											<h6><b>E</b></h6>			
										<?php }elseif($courses['type']=="O"){?>
											<h6><b>O</b></h6>
										<?php }?>
									</td>
									<td align="center">
										<?php if($sem['semid']<>"1"){
											$exreq=0;
											for($i=1; $i<=3 ; $i++){
												if($courses['req_'.$i]){
													echo $courses['req_'.$i]." ";
													$exreq=1;
												}
											}
											if($exreq==0){
												echo "Ninguno";
											}
										}?>
									</td>
									<td align="center"><?php echo $courses['credits']?></td>
									<td><!-- Imprimir mayor nota -->
										<?php if($this->courlle[$c]){
											$notafinal=$this->courlle[$c]['notafinal'];
											foreach ($this->courlle[$c] as $notaf) {
												if($notaf['notafinal']>=$notafinal){
													$notafinal=$notaf['notafinal'];
												}
											}
										echo $notafinal;
										}else{
											$est=1;
										}?>
									</td>
									<td>
										<?php if($est<>1){
											if($notafinal>=11){?>
												<img src="/img/circulo-verde.png">
											<?php }else{
												$pinto=0;
												foreach ($this->courlleact as $cact) {
													if($this->courlle[$c][0]['courseid']==$cact['courseid']){
														if($cact['state']=="M"){?>
															<img src="/img/circulo-amarillo.png">
														<?php $pinto=1;
														}else{?>
															<img src="/img/circulo-rojo.png">
														<?php $pinto=1;
														}
													}
												}
												if($pinto==0){?>
													<img src="/img/circulo-rojo.png">
												<?php }
											}
										}elseif($est==1){
											$est=0;?>
											<img src="/img/circulo-rojo.png">
										<?php }?>
									</td>
								</tr>
							<?php $c++;
							}
						}?>
						</table>
					</div>
				<?php  
				}?>
			<?php }?>
		</div><!-- Panel de Semestres -->
		<?php }else{?>
			<h4 align="center">No Existen Datos</h4>
		<?php }?>
	</div>
</div>