<div class="row">
	<div class="col-md-10 col-md-offset-1 boxbody sombras">
		<h5>
			<span class="glyphicon glyphicon-random"></span> - GRAFICA CANTIDAD DE MATRICULADOS PERIODO - <?php echo $this->perid?>
			<a href="#" style="float:right; color:white"><span class="glyphicon glyphicon-comment"></span></a>
		</h5>
		<div class="boxcontent">
            <iframe width="99.5%" height="97.3%" src="rfacultad/index/graphicschool"></iframe>
        </div><br>
	</div>
</div>