<div style="display: block; height: 120px; width: 100%; ">
  <div class="img-thumbnail pull-left">
    <img src="/fotos/<?php echo $this->person['uid']?>.jpg" title="">
  </div>
  <div class="pull-left" style="padding: 8px;">
    <p style="font-size: 18px"><b><?php echo $this->person[0]['last_name0']." ".$this->person[0]['last_name1']." ".$this->person[0]['first_name'];?></b><br>
    Código <b><?php echo $this->person['uid']?></b><br>
    Facultad de <?php echo $this->facesp[0]['nomfac']." Escuela de ".$this->facesp[0]['nomesc']?></p>
   </div>
   <div class="pull-right">
      <a href="/report/recordnotas/print/uid/<?php echo base64_encode($this->person['uid'])?>/escid/<?php echo base64_encode($this->facesp[0]['escid'])?>/eid/<?php echo base64_encode($this->person['eid'])?>/oid/<?php echo base64_encode($this->person['oid'])?>/subid/<?php echo base64_encode($this->facesp[0]['subid'])?>/pid/<?php echo base64_encode($this->person[0]['pid'])?>" class="btn btn-success">
      Record Notas
      </a>
    </div><br><br><br>
<!--   <div class="pull-right">
      <a id='click'  class="btn btn-primary"><span class="glyphicon glyphicon-earphone"></span>
      Contactar
      </a>
  </div> -->
</div>

<div style="display: block; width: 100%; ">
	<ul class="nav nav-tabs" id="profileTab">
		<li class="active"><a href="#info" id="btnmaininfo"><h5>Informacion</h5></a></li>
		<li><a href="#signin" id="btnmainsignin"><h5>Matricula</h5></a></li>
		<li><a class="hidden"></a></li>
	</ul>
	<div class="tab-content" style="margin: 0px; padding: 0px; min-height: 500px;" >
		<div class="tab-pane active" id="info" ></div>
		<div class="tab-pane" id="signin"></div>
	</div>
</div>


<script>
  $(function () {
    $("#info").load("/profile/private/studentinfo/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");

    $("#signin").load("/profile/private/studentsigncurrent/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");

    $('#profileTab a').click(function (e) {
      e.preventDefault()
        $(this).tab('show')
    });
      
    $("#btnmaininfo").click(function(){
      $("#signin").load("/profile/private/studentsigncurrent/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");
      $("#masinfosignTab a:last").tab('show')
    });
    $("#btnmainsignin").click(function(){
      $("#info").load("/profile/private/studentinfo/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");
      $("#masinfoTab a:last").tab('show')
    });
  });
</script>


<style type="text/css">
  .modal-dialog
  {
    width: 700px;
  }
</style>
<script type="text/javascript">
    $("#click").click(function(){  
      var $url ="/default/correo/index/uid/<?php echo base64_encode($this->person['uid'])?>/escid/<?php echo base64_encode($this->facesp[0]['escid'])?>/eid/<?php echo base64_encode($this->person['eid'])?>/oid/<?php echo base64_encode($this->person['oid'])?>/subid/<?php echo base64_encode($this->facesp[0]['subid'])?>/pid/<?php echo base64_encode($this->person[0]['pid'])?>";  
        $("#modal").modal('show');
        $(".modal-body").load($url);
    });
</script>

<div class="modal fade" id='modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style='background: #404040; color:white; font-size: 14px;'> Mensaje Nuevo 
        <button style='color:white;' type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer" style='background: #333; color:#fff;'>
         <a href="/admin/comunicados/nuevo" class="btn btn-primary" style="float:left;margin-left"><i class="icon-pencil icon-white"></i>Enviar</a> 
        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-log-out'></span> Salir</button>

      </div>
    </div>
  </div>
</div>