<div class="panel panel-info">

  <div class="panel-heading">
    <h4>Datos Estadísticos</h4>
  </div>

  <div class="panel-body">
  	<?php 
  	if($this->statistic){?>
    <table class="table">
    	<tr>
			<td>Conocimiento en Computación</td>
		</tr>
    	<tr>
			<td>Depende Económicamente de</td>
			<td>Denpenden de Usted</td>
		</tr>    	
		<tr>
			<td>Vivienda</td>
			<td>Tipo</td>
		</tr>    	
		<tr>
			<td>Tipo de Material</td>
			<td>Número de Habitaciones</td>
		</tr>
		<tr>
			<td>Servicios</td>
			<td>Personas que Habitan en su Hogar</td>
		</tr>
		<tr>
			<td>Problemas Con la Necesidad de Alimentos</td>
			<td>Lugar de Alimentación</td>
		</tr>
		<tr>
			<td>Costo Diario de Alimentos</td>
		</tr>
    </table>
    <?php }
    else{
    	?>
      <center><h5>No tiene Datos, Sugerir que Actualize su Perfil</h5></center>
    <?php }?>
  </div>

</div>
