<div class="panel panel-info">

  <div class="panel-heading">
    <h4>Datos Laborales</h4>
  </div>

  <div class="panel-body">
  	<?php if($this->laboral){
  		foreach ($this->laboral as $lab) {?>
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		    		<h5><b><?php echo $lab['company']?></b></h5>
		    	</div>
		    	<div class="panel-body">
		    		<table class="table">
		    			<tr>
		    				<th>Área <h5><b><?php echo $lab['industry']?></b></h5></th>
		    				<th>Condición <h5><b><?php echo $lab['condition']?></b></h5></th>
		    				<th>Salario Mensual <h5><b>S/. <?php echo $lab['salary']?></b></h5></th>
		    			</tr>
		    		</table>
		    	</div>
		    </div>
  		<?php }?>

  	<?php }else{?>
      <center><h5>No tiene Datos, Sugerir que Actualize su Perfil</h5></center>
    <?php 
	}?>
  </div>

</div>
