<div class="panel panel-default">
	<div class="panel-heading">
		<h5><b>Matrícula Por Curricula</b></h5>
	</div>
	<div class="panel-body">
		<?php if($this->courpercur){ ?>
		<div class="panel panel-primary">
			<?php 
			$semid=0;
			$c=0;
			foreach ($this->courpercur as $sem) {
				if($sem['semid']<>$semid){?>
					<div class="panel-heading">
						<b>SEMESTRE <?php echo $sem['semid']?></b>
					</div>
					<div class="panel-body">
						<table class="table">
							<tr>
								<th class="text-center">Código</th>
								<th class="col-md-4">Curso</th>
								<th class="text-center">Créditos</th>
								<th class="text-center">Tipo</th>
								<th class="text-center">Requisito</th>
								<th class="text-center">Nota</th>
								<th class="text-center">Estado</th>
								<th class="text-center">Sílabo</th>
							</tr>
					<?php
					$semid=$sem['semid'];
						foreach ($this->courpercur as $cCursos => $courses) {
							if($courses['semid']==$semid) {?>
								<tr>
									<td align="center"><?php echo $courses['courseid']?></td>
									<td><?php echo $courses['name']?></td>
									<td align="center"><?php echo $courses['credits']?></td>
									<td align="center"><?php if($courses['type']=='O'){
											echo "Obligatorio";
										}else{
											echo "Electivo";
										}?>
									</td>
									<td align="center">
										<?php if($sem['semid']<>"1"){
											$exreq=0;
											for($i=1; $i<=3 ; $i++){
												if($courses['req_'.$i]){
													echo $courses['req_'.$i]." ";
													$exreq=1;
												}
											}
											if($exreq==0){
												echo "Ninguno";
											}
										}?>
									</td>
									<td align='center'><!-- Imprimir mayor nota -->
										<?php
										if($this->courlle[$c]){
											$notafinal=$this->courlle[$c]['notafinal'];
											foreach ($this->courlle[$c] as $notaf) {
												if($notaf['notafinal']>=$notafinal){
													$notafinal=$notaf['notafinal'];
												}
											}
										echo $notafinal;
										}else{
											$est=1;
										}?>
									</td>
									<td align='center'>
										<?php if($est<>1){
											if($notafinal>=11){?>
												<img src="/img/circulo-verde.png">
											<?php }else{
												$pinto=0;
												foreach ($this->courlleact as $cact) {
													if($this->courlle[$c][0]['courseid']==$cact['courseid']){
														if($cact['state']=="M"){?>
															<img src="/img/circulo-amarillo.png">
														<?php $pinto=1;
														}else{?>
															<img src="/img/circulo-rojo.png">
														<?php $pinto=1;
														}
													}
												}
												if($pinto==0){?>
													<img src="/img/circulo-rojo.png">
												<?php }
											}
										}elseif($est==1){
											$est=0;?>
											<img src="/img/circulo-rojo.png">
										<?php }?>
									</td>
									<td class="text-center"><a title="Imprimir Sílabo" href="/syllabus/print/index/courseid/<?php echo base64_encode($courses['courseid'])?>/curid/<?php echo base64_encode($courses['curid'])?>/escid/<?php echo base64_encode($courses['escid'])?>/turno/<?php echo base64_encode($this->courlle[$cCursos][0]['turno'])?>/perid/<?php echo base64_encode($this->courlle[$cCursos][0]['perid'])?>/subid/<?php echo base64_encode($courses['subid'])?>"><span class="glyphicon glyphicon-book"></span></a></td>
								</tr>
							<?php $c++;
							}
						}?>
						</table>
					</div>
				<?php  
				}?>
			<?php }?>
		</div><!-- Panel de Semestres -->
		<?php }else{?>
			<h4 align="center">No Existen Datos</h4>
		<?php }?>
	</div>
</div>