<?php
$perid=$this->perid;
$escid=$this->escid;
?>
<table class="table span10">
	<?php if ($this->courses){?>
	    <tr>
	        <th class="span1"><center>Num</center></th>
	        <th class="span1"><center>Sem</center></th>   
	        <th class="span1"><center>Curricula</center></th>        
	        <th class="span1"><center>Codigo</center></th>
	        <th ><center>Curso</center></th>
	        <th class="span1"><center>Turno</center></th>         
	        <th class="span1"><center>Calificación</center></th>
	        <th class="span1"><center>Num Mat</center></th>
	        <?php if ($rid!='DC'){?>
	        	<th class="span1"><center>Fecha Acta</center></th>
	        	<th class="span1"><center>Estado</center></th>
	        <?php } ?>
	    </tr>
	 	<?php $c=1;
	 	foreach ($this->courses as $crs){?>
	 		<tr align="center">
	 			<td><?php echo $c ?></td>
	 			<td><?php echo $crs['semid'] ?></td>
	 			<td><?php echo $crs['curid'] ?></td>
	 			<td><?php echo $crs['courseid'] ?></td>
	 			<td><?php echo $crs['name']?></td>
	 			<td><?php echo $crs['turno'] ?></td>
	 			<?php if ($crs['type_rate']=="O") {?>
	 				<td>Objetivo</td>
	 			<?php }else{?>
					<td>Competitivo</td>
				<?php }?>
	 			<td>numMat</td>
	 			<td><?php echo $crs['closure_date'] ?></td>
	 			<td><?php echo $crs['state'] ?></td>
	 			<?php
	 			$urlcurso = "courseid/".base64_encode($crs['courseid'])."/curid/".base64_encode($crs['curid'])."/perid/".base64_encode($perid)."/escid/".base64_encode($escid)."/subid/".base64_encode($crs['subid'])."/turno/".base64_encode($crs['turno']);
	 			if ($rid!='DC'){?>
	 				<td><a href="#" onclick="javascript: window.open('record/courseteacher/<?php echo $urlcurso?>','Detalle de Acta','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=800,height=664')"><span class="glyphicon glyphicon-pencil"></span></a></td>
	 			<?php }?>	 		
	 		</tr>
	 	<?php $c++;	
	 	 }?>	

	<?php } else{?>
		<tr><center>No Existen Cursos...</center></tr>
	<?php }?>
</table>