 <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">
      function drawVisualization() {
       <?php $nombre = $this->nom;
              $turno = $this->turno;
              $nom=$nombre."-turno:".$turno;
          ?>
        var data = google.visualization.arrayToDataTable([
          ['ENCUESTA', 'SIEMPRE', 'CASI SIEMPRE', 'AVECES', 'NUNCA'],
           <?php  foreach ($this->cantidad as $datos) {
           $nombre=$datos['pregunta'];
           $siempre=$datos['siempre'];
           $casi_siempre=$datos['casi_siempre'];
           $aveces=$datos['aveces'];
           $nunca=$datos['nunca'];
          
          ?>
           ['<?php print $nombre?>' , <?php print $siempre?> ,<?php print $casi_siempre?> ,<?php print $aveces?> ,<?php print $nunca?>],
         <?php  }?>
 
        ]);

        var options = {
          title : 'CURSO: <?php print strtoupper($nom)?>',
          vAxis: {title: "CANTIDAD"},
          hAxis: {title: "PREGUNTAS"},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
      google.setOnLoadCallback(drawVisualization);
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 95%; height: 100%;"></div>
  </body>

 
