<!--<div class="panel panel-default">
    <div class="row container">
        <div class="col-md-12">
            <br>
            <h4 class="text-muted">Avance de <span class="text-info">Cursos</span><span class="pull-right glyphicon glyphicon-book"></span></h4>
        </div>
    </div>
    <hr>
    <div class="row container">
        <div class="col-md-12">
        <?php $c = 0; ?>
        <?php foreach ($this->courses as $course): ?>
            <div class="panel panel-default">
                <div class="container">
                    <div class="col-md-9">
                        <h4 class="text-info"><?php echo $this->coursesName[$c][0]['name'] ?> <small><?php echo $course['courseid'] ?></small></h4>
                    </div>
                    <div class="col-md-1">
                        <?php if ($this->porcentajeSyllabus[$c] <= 25){
                            $color = 'text-danger';
                        }elseif ($this->porcentajeSyllabus[$c] <= 99) {
                            $color = 'text-warning';
                        }elseif ($this->porcentajeSyllabus[$c] == 100) {
                            $color = 'text-success';
                        }?>
                        <h4 class="<?php echo $color ?>"><span class="glyphicon glyphicon-book"></span> <small class="<?php echo $color ?>"><?php echo $this->porcentajeSyllabus[$c] ?> %</small></h4>
                    </div>
                    <div class="col-md-1">
                        <?php print_r($this->progressSessions[$c]) ?>
                        <?php if ($this->progressSessions[$c] == 'FS'){
                            $progress = 'FS';
                        }else{
                            $progress = $this->progressSessions[$c].' %';
                        } ?>
                        <h4 class="text-danger"><span class="glyphicon glyphicon-dashboard"></span> <small class="text-danger"><?php echo $progress ?></small></h4>
                    </div>
                    <div class="col-md-1">
                        <h4 class="text-success"><span class="glyphicon glyphicon-saved"></span> <small class="text-success">100 %</small></h4>
                    </div>
                </div>
            </div>
        <?php $c++; ?>
        <?php endforeach ?>
        </div>
    </div>
</div>-->

<div class="row">
  	<div class="col-md-6">
        <div class ="col-md-3 content-calendar">
            <div class="content-day">
                <div class ="content-date pull-left">
                    <h5 class ='text-calendar' ><?php echo strtoupper($this->mounth)?></h5>
                    <h1 class="text-calendar calendar-text-day"><?php echo strtoupper($this->day_1)?></h1>
                    <h5 class='text-calendar'><?php echo strtoupper($this->day_last)?></h5>
                </div>
                <div class ="contet-add-cal pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                </div>
            </div>
            <div class="content-event">
                <span class="glyphicon glyphicon-book pull-left icon-event"></span>
                <h5 class='text-calendar text-event-title text-center'>Inicio Llenado de Notas</h5>
                <h3 class="text-calendar text-detail-event">Ingereso de Notas Primer Parcial</h3>
            </div>
        </div>
        <div class ="col-md-3 content-calendar">
            <div class="content-day">
                <div class ="content-date pull-left">
                    <h5 class ='text-calendar' ><?php echo strtoupper($this->mounth_2)?></h5>
                    <h1 class="text-calendar calendar-text-day"><?php echo strtoupper($this->day_2)?></h1>
                    <h5 class='text-calendar'><?php echo strtoupper($this->day_last)?></h5>
                </div>
                <div class ="contet-add-cal pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                </div>
            </div>
            <div class="content-event">
                <span class="glyphicon glyphicon-book pull-left icon-event"></span>
                <h5 class='text-calendar text-event-title text-center'>Inicio Llenado de Notas</h5>
                <h3 class="text-calendar text-detail-event">Ingereso de Notas Segundo Parcial</h3>
            </div>
        </div>
  </div>
  <div id="graphic-survey" class="col-md-6"></div>
</div>
<script type="text/javascript">
	$("#graphic-survey").load("/docente/index/xcourses");
</script>