    <link rel="stylesheet" href="/css/sliderNews.css">


<!--Slider de Noticias-->
<div class="row">
    <div class="col-md-12">
    <div class="row">
    <div id="newsSlider" class="slider">
        <?php $slideActive = 0; ?>
        <?php foreach ($this->news as $new): ?>
            <?php if ($slideActive == 0){
                $classSlide = 'slideActive';
                $slideActive = 1;
            } else {
                $classSlide = '';
            }?>
        <div class="slide <?php echo $classSlide ?>">
            <div class="col-md-6 title">
                <?php if ($new['type'] == 'NE') {
                    $icon = 'glyphicon glyphicon-info-sign';
                }else if ($new['type'] == 'SY') {
                    $icon = 'glyphicon glyphicon-envelope';
                }?>
                <h3 class="text-center"><span class="<?php echo $icon ?>"></span> <?php echo $new['title'] ?></h3>
            </div>
            <div class="col-md-6 content">
                    <p><?php echo substr($new['description'], 0, 125) ?>.........
                        <a newid="<?php echo $new['newid'] ?>" href="##" class="btn btn-link showData">Seguir leyendo</a>
                        <a newid="<?php echo $new['newid'] ?>" href="##" class="btn btn-link hideData hidden">Leer menos</a>
                    </p>
            </div>
        </div>
        <?php endforeach ?>
    </div>
    </div>
    
    <div class="row">

    <?php foreach ($this->news as $newData): ?>
    <div id="data<?php echo $newData['newid'] ?>" class="data">
        <div class="row">
            <div id="newImg<?php echo $newData['newid'] ?>" class="newImg col-md-6"></div>
            <script>
                var newId = "<?php echo $newData['newid'] ?>";
                var newImg = "<?php echo $newData['img'] ?>";
                $('#newImg' + newId).css("background-image", "url('/imgsNews/" + newImg + "')");
            </script>
            <div class="col-md-6 allDescription">
                <br><br>
                <?php if ($newData['type'] == 'NE') {
                    $iconNew = 'info-sign';
                }else {
                    $iconNew = 'envelope';
                } ?>
                <span class="glyphicon glyphicon-<?php echo $iconNew ?>"></span> Información <date class="text-muted"><?php echo date('d-m-Y', strtotime($newData['created'])) ?></date>
                <br><br><br>
                <p><?php echo $newData['description'] ?></p>
                <br><br>
                <span class="pull-right text-muted"><span class="glyphicon glyphicon-leaf"></span> Oficina de Informática</span>
            </div>
        </div>
    </div>
    <?php endforeach ?>
    </div>
    </div>
</div>
<br>


<!--Grafica Docentes-->
<!--<div id="graficaSlide" class="grafica">
    <div class="graficaTitle">
        <p class="text-muted">Gráfica de la encuesta realizada en el periodo 13B</p>
    </div>
    <a id="openSlideGrafica" href="##">
    <div class="openGraficaBotons">
        <p><span class="glyphicon glyphicon-stats"></span> Visualizar Gráfica</p>
    </div>
    </a>
    <a id="closeSlideGrafica" href="##">
    <div class="closeGraficaBotons hidden">
        <p><span class="glyphicon glyphicon-stats"></span> Cerrar Gráfica</p>
    </div>
    </a>
    <div class="allDataGrafica">
        <div class="botonsCourses">
            <div class="row">
                <div class="col-md-1 col-md-offset-3">
                    <a class="text-muted pull-right" id="backGrafica" href="##"><span class="glyphicon glyphicon-chevron-left"></span></a>
                </div>
                <div id="nameCourse" class="col-md-4 text-center text-muted"><?php echo $this->encuestaCoursesName[0] ?></div>
                <div class="col-md-1">
                    <a class="text-muted" id="nextGrafica" href="##"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>
            </div>
        </div>
        <!--Grafica Docentes
        <script type="text/javascript" src="/js/graphic/docente.js"></script>
        <script src="/external_library/highcharts/js/highcharts.js"></script>
        <script src="/external_library/highcharts/modules/exporting.js"></script>
        <div class="dataGraficas">
            <?php 
            $active = 0;
            $c = 0;
            foreach ($this->coursesBefore as $course): ?>
                <?php if ($active == 0) {
                    $classActive = 'activeGrafica';
                    $active = 1;
                }else{
                    $classActive = '';
                } ?>
                <div class="graficaCourse <?php echo $classActive ?>" courseid="<?php echo $course['courseid'] ?>" nameCourse="<?php echo $this->encuestaCoursesName[$c] ?>">
                    <span class="hidden" id="dataCourses<?php echo $course['courseid'] ?>"><?php print_r($this->datosEncuesta) ?></span>
                    <script type="text/javascript">
                        var datosEncuesta = <?php echo $this->datosEncuesta ?>;
                    </script>
                    <div id="container_encuesta<?php echo $course['courseid'] ?>" ></div>
                </div>
            <?php 
            $c++;
            endforeach ?>
        </div>
        <div class="dataPreguntas">
            <p class="text-info"><strong>Leyenda de Preguntas de la Encuesta</strong></p>
            <ol class="text-muted">
                <?php foreach ($this->pollQuestions as $question): ?>
                    <li><?php echo $question['question'] ?></li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>-->
<br><br> 

<!--Panel de Avance de Cursos-->
<div class="avanceCursos container">
    <div class="row">
        <div class="container">
        <div class="titleAvanceCursos col-md-12">
            <div class="title text-muted"><h4><span class="text-info">Avance de Cursos</span> Periodo <?php echo $this->perid ?></h4></div>
            <div class="iconAvance"><h4><span class="glyphicon glyphicon-book"></span></h4></div>
            <br>
        </div>
        </div>
    </div>
    <div class="allCursos">
    <br>
    <div class="row">
    <div class="container">
    <?php if ($this->courses): ?>
        
    <?php $c = 0; ?>
    <?php foreach ($this->courses as $course): ?>
    <div class="col-md-6">
        <div class="curso">
            <div class="container">
                <div class="col-md-6">
                    <h5 class="text-info"><span class="progressIcons" title="<?php echo $this->coursesSpecialityName[$c][0]['name'] ?>"><?php echo ucwords(strtolower($this->coursesName[$c][0]['name'])) ?></span> <small><?php echo $course['courseid'] ?></small></h5>
                </div>
                <div class="col-md-2">
                    <?php if ($this->porcentajeSyllabus[$c] == 0){
                        $color = 'text-danger';
                        $avisoSilabo = 'Empiece a rellenar su sílabo';
                    }elseif ($this->porcentajeSyllabus[$c] <= 25) {
                        $color = 'text-warning';
                        $avisoSilabo = 'Termine de rellenar su sílabo';
                    }elseif ($this->porcentajeSyllabus[$c] <= 99) {
                        $color = 'text-warning';
                        $avisoSilabo = 'Ya le falta poco, complete su sílabo';
                    }elseif ($this->porcentajeSyllabus[$c] == 100) {
                        $color = 'text-success';
                        $avisoSilabo = 'Sílabo completado';
                    }?>
                    <h5>
                        <?php 
                        $urlSyllabus = 'syllabus/syllabus/index'.   '/courseid/'.base64_encode($course['courseid']).
                                                                    '/curid/'.base64_encode($course['curid']).
                                                                    '/escid/'.base64_encode($course['escid']).
                                                                    '/subid/'.base64_encode($course['subid']).
                                                                    '/turno/'.base64_encode($course['turno']).
                                                                    '/perid/'.base64_encode($course['perid']) ; ?>
                        <a href="<?php echo $urlSyllabus ?>" class="<?php echo $color ?> progressIcons" title="<?php echo $avisoSilabo ?>"><span class="glyphicon glyphicon-book"></span></a>
                        <small class="<?php echo $color ?>"><?php echo $this->porcentajeSyllabus[$c] ?> %</small>
                    </h5>
                </div>
                <div class="col-md-2">
                    <?php if ($this->progressSessions[$c]['porcentaje']  == 'FS'){
                        $classSessions = 'text-danger';
                        $avisoSessions = 'Primero termine de rellenar su sílabo';
                        $urlControlActivity = '##';
                    }else{
                        $classSessions = 'text-success';
                        $avisoSessions = $this->progressSessions[$c]['contents'].' de '.$this->progressSessions[$c]['totalContents'].' sesiones realizadas';

                        $urlControlActivity = '/controlactivity/index/index'.   '/courseid/'.base64_encode($course['courseid']).
                                                                                '/curid/'.base64_encode($course['curid']).
                                                                                '/escid/'.base64_encode($course['escid']).
                                                                                '/subid/'.base64_encode($course['subid']).
                                                                                '/turno/'.base64_encode($course['turno']).
                                                                                '/perid/'.base64_encode($course['perid']) ;
                    } ?>
                    <h5>
                        <a href="<?php echo $urlControlActivity ?>" class="<?php echo $classSessions ?> progressIcons" title="<?php echo $avisoSessions ?>"><span class="glyphicon glyphicon-dashboard"></span></a>
                        <small class="<?php echo $classSessions ?>"><?php echo $this->progressSessions[$c]['porcentaje'] ?></small>
                    </h5>
                </div>
                <div class="col-md-2">
                    <?php if ($this->progressNotas[$c]['porcentaje'] == 'FS'){
                        $classNotas = 'text-danger';
                        $progressNotas = 'FS';
                        $avisoNotas = 'Primero termine de rellenar su sílabo';
                        $faltaSilabo = 'SI';
                        $urlNotas = '##';
                    }elseif ($this->progressNotas[$c]['porcentaje'] <= 25){
                        $classNotas = 'text-danger';
                        $progressNotas = $this->progressNotas[$c]['porcentaje'].' %';
                        $avisoNotas = $this->progressNotas[$c]['notasRellenadas'].' de '.$this->progressNotas[$c]['totalStudents'].' completados';
                        $faltaSilabo = 'No';
                    }elseif ($this->progressNotas[$c]['porcentaje'] <= 99){
                        $classNotas = 'text-warning';
                        $progressNotas = $this->progressNotas[$c]['porcentaje'].' %';
                        $avisoNotas = $this->progressNotas[$c]['notasRellenadas'].' de '.$this->progressNotas[$c]['totalStudents'].' completados';
                        $faltaSilabo = 'No';
                    }
                    elseif ($this->progressNotas[$c]['porcentaje'] == 100){
                        $classNotas = 'text-success';
                        $progressNotas = $this->progressNotas[$c]['porcentaje'].' %';
                        $avisoNotas = 'Todas las Notas Rellenadas';
                        $faltaSilabo = 'No';
                    } 
                    if ($faltaSilabo == 'No') {
                        $urlNotas = '/docente/fillnotes/target'.    '/'.base64_encode('escid').'/'.base64_encode($course['escid']).
                                                                    '/'.base64_encode('subid').'/'.base64_encode($course['subid']).
                                                                    '/'.base64_encode('courseid').'/'.base64_encode($course['courseid']).
                                                                    '/'.base64_encode('turno').'/'.base64_encode($course['turno']).
                                                                    '/'.base64_encode('perid').'/'.base64_encode($course['perid']).
                                                                    '/'.base64_encode('curid').'/'.base64_encode($course['curid']).
                                                                    '/'.base64_encode('state').'/'.base64_encode($this->coursesStateRecord[$c]);
                    }
                    ?>
                    
                    <h5>
                        <a href="<?php echo $urlNotas ?>" class="<?php echo $classNotas ?> progressIcons" title="<?php echo $avisoNotas ?>"><span class="glyphicon glyphicon-saved"></span></a>
                        <small class="<?php echo $classNotas ?>"><?php echo $progressNotas ?></small>
                    </h5>
                </div>
            </div>
        </div>
    </div>
    <?php $c++; ?>
    <?php endforeach ?>
    <?php else: ?>
        <h4 class="text-muted text-center">No tiene cursos en <span class="text-info">este periodo</span></h4>
    <?php endif ?>
    </div><!--Div Container-->
    </div><!--Div Row-->
    </div>
</div>
<br><br>
<!-- Avance Academico Solo Para Directores-->
<input id="rid" type="hidden" value="<?php echo $this->rid ?>">
<div id="avanceDirectores" class="container">
    <div class="row">
    <div class="container">
        <div class="titleAvanceCursos col-md-12">
            <div class="title"><h4 class="text-muted"><span class="text-info">Avance Académico</span> Periodo <?php echo $this->perid ?></h4></div>
            <div class="iconAvance"><h4><span class="glyphicon glyphicon-user"></span></h4></div>
        </div>
    </div>
    </div>
        
    
    <div class="allCursos">
        <br>
        <?php echo $var ?>
        <?php if ($this->totalTeachers != 0): ?>
        <div class="row">
            <div class="container">
            <div class="col-md-6">
                <div class="curso avance">
                <div class="container">
                <div id="showEmptySyllabus" class="progressIcons" title="<?php echo $this->emptySyllabus ?> Docentes aún Faltan Completar sus Sílabos">
                    <div class="container">
                        <?php if ($this->totalEmptySyllabus == $this->totalTeachers) {
                            $classSilabo = 'text-success';
                        }else {
                            $classSilabo = 'text-danger';
                        }?> 
                       <h5 class="text-info">Sílabo <strong class="pull-right <?php echo $classSilabo ?> " ><?php echo $this->totalEmptySyllabus.'/'.$this->totalTeachers ?></strong></h5>
                    </div>
                </div>
                </div>
                </div>
                <div id="listEmptySyllabus" class="dataSliderAvance">
                <div class="container">
                    <p class="text-danger text-center">Fálta Sílabo
                        <?php if ($this->emptySyllabus >= 5): ?>
                            <span class="text-muted">Algunos de los docentes son:</span>
                        <?php endif ?>
                    </p>
                    <div class="row">
                    <div class="container">
                    <?php 
                    $maxProfes = 0;
                    foreach ($this->teachersEmptySyllabus as $teacher): ?>
                        <div class="col-md-6">
                            <p><small class="text-muted"><span class="glyphicon glyphicon-user"></span></small> <?php echo $teacher['name'] ?></p>
                        </div>
                        <div class="col-md-6">
                            <?php $coursesEmpty = 0; ?>
                            <?php foreach ($this->coursesEmptySyllabus as $course): ?>
                                <?php if ($this->coursesEmptySyllabus[$teacher['uid']][$coursesEmpty]): ?>
                                    <p>
                                        <small><span class="glyphicon glyphicon-book text-muted"></span></small>
                                        <?php echo ucwords(strtolower($this->coursesEmptySyllabus[$teacher['uid']][$coursesEmpty]['name'])) ?>
                                        <small class="text-muted">turno <?php echo $this->coursesEmptySyllabus[$teacher['uid']][$coursesEmpty]['turno'] ?></small>
                                    </p> 
                                <?php endif ?>
                                <?php $coursesEmpty++; ?>
                            <?php endforeach ?>
                        </div>
                    <?php 
                        $maxProfes++;
                        if ($maxProfes == 5) {
                            break;
                        }
                    endforeach ?>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="curso avance">
                <div class="container">
                <div id="showEmptyReport" class="progressIcons" title="<?php echo $this->emptyReport ?> Docentes aún Faltan Completar su Informe Académico">
                    <div class="container">
                        <?php if ($this->totalEmptyReport == $this->totalTeachers){
                            $classReport = 'text-success';
                        }else{
                            $classReport = 'text-danger';
                        }?>
                       <h5 class="text-info">Informe Académico <strong class="pull-right <?php echo $classReport ?>"><?php echo $this->totalEmptyReport.'/'.$this->totalTeachers ?></strong></h5>
                    </div>
                </div>
                </div>
                </div>
                <div id="listEmptyReport" class="dataSliderAvance">
                    <div class="container">
                    <p class="text-center text-danger">Falta Informe Académico
                        <?php if ($this->emptyReport >= 10): ?>
                            <span class="text-muted">Algunos de los docentes son:</span>
                        <?php endif ?>
                    </p>
                    <div class="container">
                        <?php 
                        $maxProfes = 0;
                        foreach ($this->teachersEmptyReport as $teacher): ?>
                            <div class="col-md-6">
                                <p><small class="text-muted"><span class="glyphicon glyphicon-user"></span></small> <?php echo $teacher['name'] ?></p>
                            </div>
                        <?php 
                            $maxProfes++;
                            if ($maxProfes == 10) {
                                break;
                            }
                        endforeach ?>
                    </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
        <?php else: ?>
            <h4 class="text-muted text-center">No hay avance que mostrar para <span class="text-info">este periodo</span></h4>
        <?php endif ?>
        <br>
    </div>
</div>
<div style="height: 500px;"></div>

    <!--<div class="col-md-1 text-center">
        <br><br>
        <a href="##" class="text-muted previousSlide">
            <span class="glyphicon glyphicon-chevron-left text-center"></span>
        </a>
    </div>
    <div class="col-md-1 text-center">
        <br><br>
        <a href="##" class="text-muted nextSlide">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>-->


<!--<div class="row">
  	<div class="col-md-6">
        <div class ="col-md-3 content-calendar">
            <div class="content-day">
                <div class ="content-date pull-left">
                    <h5 class ='text-calendar' ><?php echo strtoupper($this->mounth)?></h5>
                    <h1 class="text-calendar calendar-text-day"><?php echo strtoupper($this->day_1)?></h1>
                    <h5 class='text-calendar'><?php echo strtoupper($this->day_last)?></h5>
                </div>
                <div class ="contet-add-cal pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                </div>
            </div>
            <div class="content-event">
                <span class="glyphicon glyphicon-book pull-left icon-event"></span>
                <h5 class='text-calendar text-event-title text-center'>Inicio Llenado de Notas</h5>
                <h3 class="text-calendar text-detail-event">Ingereso de Notas Primer Parcial</h3>
            </div>
        </div>
        <div class ="col-md-3 content-calendar">
            <div class="content-day">
                <div class ="content-date pull-left">
                    <h5 class ='text-calendar' ><?php echo strtoupper($this->mounth_2)?></h5>
                    <h1 class="text-calendar calendar-text-day"><?php echo strtoupper($this->day_2)?></h1>
                    <h5 class='text-calendar'><?php echo strtoupper($this->day_last)?></h5>
                </div>
                <div class ="contet-add-cal pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                </div>
            </div>
            <div class="content-event">
                <span class="glyphicon glyphicon-book pull-left icon-event"></span>
                <h5 class='text-calendar text-event-title text-center'>Inicio Llenado de Notas</h5>
                <h3 class="text-calendar text-detail-event">Ingereso de Notas Segundo Parcial</h3>
            </div>
        </div>
  </div>
  <div id="graphic-survey" class="col-md-6"></div>
</div>-->
<script type="text/javascript">
	//$("#graphic-survey").load("/docente/index/xcourses");
    
    

    var rid = $('#rid').val();
    if (rid != 'DR') {
        $('#avanceDirectores').addClass('hidden');
    };

    $('.progressIcons').hover(function(){
        $(this).tooltip('toggle');  
    });

    //Slider
    $('.data, #listEmptySyllabus, #listEmptyReport, .allDataGrafica').slideUp();
    
    var sliderGo = setInterval(function(){sliderForward();}, 4500);

    $('.nextSlide').click(function(){
        sliderForward();
    });
    $('.previousSlide').click(function(){
        sliderBackward();
    });

    $('.showData').click(function(){
        clearInterval(sliderGo);
        $('html,body').animate({
            scrollTop: $("#newsSlider").offset().top
        }, 500);
        var newid = $(this).attr('newid');
        $('#data' + newid).slideDown();
        $('.showData').addClass('hidden');
        $('.hideData').removeClass('hidden');
    })

    $('.hideData').click(function(){
        $('.data').slideUp();
        $('.showData').removeClass('hidden');
        $('.hideData').addClass('hidden');
        sliderGo = setInterval(function(){sliderForward();}, 4500);
    })

    //Navegacion Grafica
    $('#openSlideGrafica').click(function(){
        $('.allDataGrafica').slideDown();
        $('.openGraficaBotons').addClass('hidden');
        $('.closeGraficaBotons').removeClass('hidden');
        $(".openGraficaBotons, .closeGraficaBotons").animate({ "left": "+=50%" }, "slow", function(){
        });
    });

    $('#closeSlideGrafica').click(function(){
        $('.allDataGrafica').slideUp();
        $('.openGraficaBotons').removeClass('hidden');
        $('.closeGraficaBotons').addClass('hidden');
        $(".openGraficaBotons, .closeGraficaBotons").animate({ "left": "-=50%" }, "slow", function(){
        });
    });

    $('#nextGrafica').click(function(){
        coursesForward();
    })

    $('#backGrafica').click(function(){
        coursesBackward();
    })

    //Avance Academico
    $('#showEmptySyllabus').hover(function(){
        $('#listEmptySyllabus').slideToggle();
    });
    $('#showEmptyReport').hover(function(){
        $('#listEmptyReport').slideToggle();
    });


    function sliderForward(){
        $('.data').slideUp();
        var size = $('.slider').find('.slide').size();
        $('.slider').find('.slide').each(function(index, value){
            if ($(value).hasClass('slideActive')) {
                $($('.slider').find('.slide').get(index)).slideUp(function(){
                    $(value).removeClass('slideActive');
                });

                if (index+1 < size) {
                    $($('.slider').find('.slide').get(index+1)).slideDown('slow');
                    $($('.slider').find('.slide').get(index+1)).addClass('slideActive');
                    return false;
                }else{
                    $($('.slider').find('.slide').get(0)).slideDown('slow');
                    $($('.slider').find('.slide').get(0)).addClass('slideActive');
                    return false;
                };
            };
        });
    }

    //Funciones para Graficas de Cursos
    function coursesForward(){
        var size = $('.dataGraficas').find('.graficaCourse').size();
        $('.dataGraficas').find('.graficaCourse').each(function(index, value){
            if ($(value).hasClass('activeGrafica')) {
                $($('.dataGraficas').find('.graficaCourse').get(index)).slideUp(function(){
                    $(value).removeClass('activeGrafica');
                });

                if (index+1 < size) {
                    $($('.dataGraficas').find('.graficaCourse').get(index+1)).slideDown('slow');
                    $($('.dataGraficas').find('.graficaCourse').get(index+1)).addClass('activeGrafica');
                    var nameCourse = $($('.dataGraficas').find('.graficaCourse').get(index+1)).attr('nameCourse');
                    $('#nameCourse').html(nameCourse)
                    return false;
                }else{
                    $($('.dataGraficas').find('.graficaCourse').get(0)).slideDown('slow');
                    $($('.dataGraficas').find('.graficaCourse').get(0)).addClass('activeGrafica');
                    var nameCourse = $($('.dataGraficas').find('.graficaCourse').get(0)).attr('nameCourse');
                    $('#nameCourse').html(nameCourse)
                    return false;
                };
            };
        });
    }

    function coursesBackward(){
        var size = $('.dataGraficas').find('.graficaCourse').size();
        $('.dataGraficas').find('.graficaCourse').each(function(index, value){
            if ($(value).hasClass('activeGrafica')) {
                $(value).slideUp();
                $($('.dataGraficas').find('.graficaCourse').get(index)).slideUp(function(){
                    $(value).removeClass('activeGrafica');
                });

                if (index == 0) {
                    $($('.dataGraficas').find('.graficaCourse').get(size-1)).slideDown();
                    $($('.dataGraficas').find('.graficaCourse').get(size-1)).addClass('activeGrafica');
                    var nameCourse = $($('.dataGraficas').find('.graficaCourse').get(size-1)).attr('nameCourse');
                    $('#nameCourse').html(nameCourse)
                    return false;
                }else{
                    $($('.dataGraficas').find('.graficaCourse').get(index-1)).slideDown();
                    $($('.dataGraficas').find('.graficaCourse').get(index-1)).addClass('activeGrafica');
                    var nameCourse = $($('.dataGraficas').find('.graficaCourse').get(index-1)).attr('nameCourse');
                    $('#nameCourse').html(nameCourse)
                    return false;
                };
            };
        });
    }
</script>