<?php foreach ($this->subjects as $key => $subject) { ?>
    <?php  
        $url ="/".base64_encode('escid')."/".base64_encode($subject['escid'])."/".base64_encode('subid')."/".base64_encode($subject['subid'])."/".base64_encode('courseid')."/".base64_encode($subject['courseid'])."/".base64_encode('turno')."/".base64_encode($subject['turno'])."/".base64_encode('perid')."/".base64_encode($this->perid_netx)."/".base64_encode('curid')."/".base64_encode($subject['curid'])."";
    ?>
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <img data-src="holder.js/300x200" alt="...">
          <div class="caption">
            <h3><?php echo $subject['name']?></h3>
            <p><a href="#" class="btn btn-primary">Button</a> 
            <a href="/register/deferred/index<?php echo $url?>" class="btn btn-default">Aplazados</a></p>
          </div>
        </div>
      </div>
    </div>
<? }?>
 