<form  name="<?php echo $this->fm->getName(); ?>" action="<?php echo $this->fm->getAction(); ?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
<table class="table table-bordered">
	<tr>
		<th class="col-sm-3">Ingrese Clave Anterior</th>
		<th ><div class="col-sm-4"><?php echo $this->fm->acla; ?></div></th>
	</tr>
	<tr>
		<th class="col-sm-3">Ingrese Nueva Clave</th>
		<th><div class="col-sm-4"><?php echo $this->fm->ncla; ?></div></th>
	</tr>
	<tr>
		<th>Repita la Clave</th>
		<th><div class="col-sm-4"><?php echo $this->fm->rcla; ?></div></th>
	</tr>
	<tr>
		<th colspan="2"><?php echo $this->mensaje; ?></th>
	</tr>
	<tr>
		<th colspan="2"><?php echo $this->fm->guardar; ?></th>
	</tr>
</table>
<div style="clear:both" ></div>
</form>
<div id="carga"></div>