<?php
if ($this->datacourses) { ?>
<table class="table table-striped table-bordered" style="margin-top: 15px;">
    <tr>
        <th><center>#</center></th>
        <th><center>Sem.</center></th>   
        <th><center>Curricula</center></th>        
        <th><center>Codigo</center></th>
        <th><center>Nombre Curso</center></th>
        <th><center>Turno</center></th>         
        <th><center>Calificación</center></th>
        <th><center>Fecha de Cierre</center></th>
        <th><center>Operación</center></th>
    </tr>
<?php
    $c=0;
    foreach ($this->datacourses as $course) {
        $c++;
        $courseid=$course['courseid'];
        $curid=$course['curid'];
        $perid=$course['perid'];
        $turno=$course['turno'];
    ?>
    <tr>
        <td><center><?php echo $c?></center></td>
        <td><center><?php echo $this->datacourse[$c-1][0]['semid']?></center></td>
        <td><center><?php echo $curid?></center></td>
        <td><center><?php echo $courseid?></center></td>
        <td><?php echo $this->datacourse[$c-1][0]['name']?> </td>
        <td><center><?php echo $turno?></center></td>
        <?php
            switch ($tr) {
                case 'O':   ?>
                    <td><center><?php echo "Objetivo"?></center></td>
                <?php    
                    break;
                case 'C':   ?>
                    <td><center><?php echo "Competencia"?></center></td>
                <?php    
                    break;
            }
        ?>
        <td><center><?php echo $closedate?></center></td>
        <td></td>
        <td></td>
    </tr>
    <?php    
    }
?>
</table>
<?php    
}
else{
?>
    <div class="alert alert-info" style='margin-top:20px; font-size:15px'> No existen <b>Registros</b></div>
<?php
}

?>