<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-file"></span> SÍLABO');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<table style='margin-top:20px' class='table table-striped'>
	<tr>
		<td><h4><div style='margin-left:5px'>Año:</h4></td>
		<td><div style='margin-left:10px'><?php echo $this->fm->anio?></td>
		<td><h4><div style='margin-left:40px'>Periodo:</h4></td>
		<td><div style='width: 200px; margin-left:10px'><?php echo $this->fm->period?></td>
		<td><h4><div style='margin-left:40px'>Escuela:</h4></td>
		<td><div style='width: 250px; margin-left:10px'><?php echo $this->fm->esc?></td>
		<td><div style='margin-left:40px'><a href="#" id='ver' class='btn btn-info'>Ver</a></td>
	</tr>
</table>
<div id='viewcourses'></div>
<script>
    $("#anio").change(function(){
        var anio = $(this).val();
        // alert(anio);
        $("#period").load("/admin/opensillabus/lperiod/anio/"+anio);
    });
    $("#ver").click(function(){
    	var escid = $("#esc").val();
    	var perid = $("#period").val();
    	if (escid=="") {alert("Seleccione una escuela");$("#escid").focus();return false;}
        if (perid=="") {alert("Ingrese un periodo");$("#perid").focus();return false;}
        var tmp=escid.split(";--;");
        var escid=tmp[0];
        var subid=tmp[1];

        var url="/admin/opensillabus/courses/perid/"+perid+"/escid/"+escid+"/subid/"+subid;
        $("#viewcourses").html("<center><img src='/img/carga.gif' /></center>");
        $("#viewcourses").load(url);


    });
</script>