<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-envelope"></span> Gestión Correos Electronicos');?>
<?php $this->placeholder('Btnnav')->append('<a href="/admin" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<div class="row">
	<div class="col-md-9">
		<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Lista de correos enviados.</p>
	</div>
	<div class="col-md-3">
		<a id="openNewModal" data-toggle="modal" data-target="#newModal" href="##" class="btn btn-info form-control">Nuevo Correo</a>
	</div>
</div>
<hr>
<h4 class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> No existe <span class="text-danger">correos</span></h4>

<!--Modal Nuevo Correo-->
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog" style="width: 1200px;">
    	<div class="modal-content" style="border-radius:0;">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        		<h4 class="modal-title" id="myModalLabel">Enviar Correo</h4>
      		</div>
		  	<div class="modal-body">
		  		<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Elija los destinatarios del correo: </p>
		    	<div class="row text-muted">
		    		<div class="col-md-4">
						<p>Facultad</p>
						<select name="selectFaculty" id="selectFaculty" class="form-control">
							<option value="">Seleccione una Facultad</option>
							<?php if ($this->dataFaculties): ?>
							<?php foreach ($this->dataFaculties as $c => $faculty): ?>
								<option value="<?php echo base64_encode($faculty['facid']) ?>"><?php echo $faculty['name'] ?></option>
							<?php endforeach ?>
							<?php endif ?>
						</select>
		    		</div>

		    		<div class="col-md-4">
						<p>Escuela</p>
						<select name="selectSchool" id="selectSchool" class="form-control">
							<option value="">Seleccione una Escuela</option>
							<option value="">Seleccione primero una facultad ¬¬</option>
						</select>
		    		</div>

		    		<div class="col-md-4">
						<p>Especialidad</p>
						<select name="selectSpeciality" id="selectSpeciality" class="form-control">
							<option value="">Seleccione una Especialidad</option>
							<option value="">Seleccione primero una escuela ¬¬</option>
						</select>
		    		</div>
		    	</div>
		    	<hr>
		    	<div class="row text-muted">
		    		<div class="col-md-4">
						<p>¿Para?</p>
						<select name="selectDestinatarios" id="selectDestinatarios" class="form-control">
							<option value="">¿Para quienes sera el correo?</option>
							<option value="AL">Alumnos</option>
							<option value="DC">Docentes</option>
						</select>
		    		</div>
		    	</div>
		    	<hr>
				<p class="text-muted">Título:</p>
				<input class="form-control" type="text" placeholder="Motivo del correo...">	
				<br>
		    	<p class="text-muted">Redacción:</p>
		    	<textarea class="form-control" name="cuerpoCorreo" placeholder="Escriba el correo aqui..." rows="10"></textarea>
		  	</div>
	      	<div class="modal-footer">
	      		<div class="row">
	      			<div class="col-md-9">
						<p id="whoSend" class="text muted"></p>
	      			</div>
		      		<div class="col-md-3">
		      			<a href="##" id="sendEmail" class="btn btn-success form-control">Enviar</a>
		        		<!--<button type="button" class="btn btn-default form-control" data-dismiss="modal">Salir</button>-->
		      		</div>
	      		</div>
	      	</div>
    	</div>
  	</div>
</div>

<script>
	$(function(){
		var codeF  = '';
		var codeSc = '';

		$('#selectFaculty').on('change', function(){
			codeF = $(this).val();

			$('#selectSchool')	.html('<option value="">Cargando...</option>')
								.load('/default/sendmail/listschools/code/' + codeF);
		});

		$('#selectSchool').on('change', function(){
			codeSc = $(this).val();

			$('#selectSpeciality')	.html('<option value="">Cargando...</option>')
									.load('/default/sendmail/listspecialities/code/' + codeSc);
		});
	});
</script>