
<div class="panel panel-primary" style="padding: 2px">
	<div class="panel-heading" style="padding: 6px">
		<center><b style="font-size:15px; color: white">ENVIAR CORREO ELECTRONICO</b></center>
	</div>
</div>
<table class="table table-hover table-condensed">
	<tr>
		<th>Facultad:</th>
		<td class="col-lg-3">
			<select id="facid" class="form-control">
				<option>- Seleccione la Facultad -</option>
				<?php
				if ($this->facultades) {
					foreach ($this->facultades as $facultades) { 
						$str = ($this->facid==$facultades['facid'])?"selected ":""; ?>
						<option <?php echo $str?>  value="<?php echo $facultades['facid']?>"><?php echo $facultades['name']?></option>
					<?php
					}
				} ?>
			</select>
		</td>
		<th>Escuela:</th>
		<td>
			<select id="escid" class="form-control" style="width:260px">
				<option value="">- Seleccione la Escuela -</option>
			</select>
		</td>
		<th>Rol:</th>
		<td  >
			<div class="col-lg-6"> 
			      <span  class="input-group-addon">
			        <input style='float: left' type="radio" name="group2" value="1"> <font style='float: left'> &nbsp; &nbsp; Docente </font><br>
			      </span>
			 </div> <br><br>

			 <div class="col-lg-6">
			      <span  class="input-group-addon">
			        <input style='float: left' type="radio" name="group2" value="1"> <font style='float: left'>  &nbsp; &nbsp;Alumno</font><br>
			      </span>
			 </div>
		</td>
	</tr>
	<tr>
		<td colspan="6">
			<center><a id="generar" href="#" class="btn btn-success"><span class="glyphicon glyphicon-envelope"></span>&nbsp; Redactar</a></center>
		</td>
	</tr>
</table>
<div id="cargadatos"></div>

<script type="text/javascript">

$("#facid").change(function(){
	var facid=$(this).val();
	$("#escid").load("/default/sendmail/schools/facid/"+facid);
});

<script type="text/javascript">
$(document).ready(function()
{
        $("input[name=group2]").click(function () {   
        var tipo=$('input:radio[name=group2]:checked').val(); 
        var perid = $("#periodo_c").val();
        var facid = $("#facid").val();
        var tescid = $("#escid").val(); 
        var espec = $("#especialidad").val();
        var xx=tescid.split(";--;");
        var escid=xx[0];
        var subid=xx[1];
        if (tipo=="1" || tipo=="2" )  {  
        var $url = '/report/consolidated/registerxcourse/perid/'+ perid+'/escid/'+escid+'/espec/'+espec+'/facid/'+facid+'/subid/'+subid+'/tipo/'+tipo;

        } 
        if (tipo=="3" || tipo=="6")  {  
        var $url = '/report/consolidated/registerxsemester/perid/'+ perid+'/escid/'+escid+'/espec/'+espec+'/facid/'+facid+'/subid/'+subid+'/tipo/'+tipo;
        } 
        if (tipo=="4")  {  
        var $url = '/report/consolidated/countregisterxcourse/perid/'+ perid+'/escid/'+escid+'/espec/'+espec+'/facid/'+facid+'/subid/'+subid+'/tipo/'+tipo;
        }
        if (tipo=="5")  {  
        var $url = '/report/consolidated/registerxspeciality/perid/'+ perid+'/escid/'+escid+'/espec/'+espec+'/facid/'+facid+'/subid/'+subid+'/tipo/'+tipo;
        }
         if (tipo=="7")  {  
        // var $url = '/report/consolidated/totalturnosxspeciality/perid/'+ perid+'/escid/'+escid+'/espec/'+espec+'/facid/'+facid+'/subid/'+subid+'/tipo/'+tipo;
        }
        // alert($url);
        $("#modal").modal('show');
        $(".modal-body").load($url);
         });
});
</script>



$("#generar").click(function(){
	var facid = $("#facid").val();
	var escid = $("#escid").val();
	var espec = $("#especialidad").val();
	var anho = $("#anho").val();
	var periodo = $("#periodo_c").val();
	var xx = periodo.split(";--;");
    var perid = xx[0];
    var estado = xx[1];
	if (facid=='' || escid=='' || perid=='') {
		alert("Seleccione la Facultad, Escuela y el Periodo Académico.");
		return false;
	};
	var totales = $("#totales").val();
	if (totales=="N") {
		var url="/graduated/reportgraduated/listgraduateds/facid/"+facid+"/escid/"+escid+"/especialidad/"+espec+"/perid/"+perid+"/anho/"+anho;
	}else{
		var url="/graduated/reportgraduated/totalgraduateds/facid/"+facid+"/escid/"+escid+"/especialidad/"+espec+"/perid/"+perid+"/anho/"+anho;
	}
	$('#cargadatos').html("<img src='/img/spinner.gif'>Cargando...");
	$("#cargadatos").load(url);
});
</script>