<?php if ($this->dataSchools and $this->dataSchools != 'all'): ?>
	<option value="">Todas las Escuelas</option>
	<?php foreach ($this->dataSchools as $school): ?>
		<option value="<?php echo base64_encode($school['escid']) ?>"><?php echo $school['name'] ?></option>
	<?php endforeach ?>
<?php elseif ($this->dataSchools and $this->dataSchools == 'all'): ?>
	<option value="TE">Todas las Escuelas habidas y por haber</option>
<?php else: ?>

<?php endif ?>