<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align:left; font-size:12px;"><b>Curso: </b><?php echo strtoupper($this->coursename[0]['name'])?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <b>Turno: </b><?php echo strtoupper($this->turno)?>
</div>
<div style='width:100%'><b>Docente: </b><?php echo $this->nameteach?></div>
<div style='margin-top:2%; text-align:center; font-size:15px'><b>Informe sobre el grado de Cumplimiento del Sílabus</b></div>
<div class="row">
	<div class="col-md-10 col-md-offset-1">

<?php if ($this->completeSyllabus == 'Si'): ?>
	<div class="alert alert-success fade in">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      	<h4>Completo con exito su sílabo :D</h4>
      	<p>Ya finalizó con todas las clases de su sílabo.......</p>
    </div>
<?php endif ?>

<?php if ($this->contentsyllabus): ?>

	<?php $c = 0;
	if ($this->firstTime == 'No'): ?>
		<h4 class="text-muted" style="opacity : 0.8">Clases <span class="text-info">Pasadas</span></h4>
		<div id="pastSession" class="panel panel-warning" style="opacity : 0.8">
			<table class="table table-bordered table-hover">
				<tr>
					<th class='small-50'>Semana</th>
					<th class='small-50'>Unidad</th>
					<th class='small-50'>Sesión</th>
					<th class='small-500'>Clase</th>
					<th class='small'>Fecha de Finalización</th>
				</tr>
		<?php foreach ($this->contentsyllabus as $content): ?>
				<tr>
					<td><center><?php echo $content[0]['week'] ?></center></td>
					<td><center><?php echo $content[0]['unit'] ?></center></td>
					<td><center><?php echo $content[0]['session'] ?></center></td>
					<!-- <td><?php echo $content[0]['obj_content'] ?></td> -->
					<td>
						<?php 
						if ($content[0]['obj_content']) {
							echo $content[0]['obj_content'];
						}
						else{

							echo $content[0]['com_conceptual'];
						}
						?>
					</td>
					<td><center><?php echo $this->controlsyllabus[$c][0]['datecheck'] ?></center></td>
				</tr>
				<?php $c++;
				if ($c == $this->realizedSession): 
					break;
				endif ?>
		<?php endforeach ?>
			</table>
		</div>

	<?php endif ?>


<?php if ($this->completeSyllabus == 'No'): ?>
		<!-- <div id="alertCourse" class="alert alert-danger fade in">
	      	<h4>Seguro que deseas marca la clase como realizada</h4>
	      	<p>Una vez que la cambies no habra marcha atras</p>
	      	<p>
	      		<?php $url = '/courseid/'.base64_encode($this->contentsyllabus[$c][0]['courseid']).
							'/curid/'.base64_encode($this->contentsyllabus[$c][0]['curid']).
							'/turno/'.base64_encode($this->contentsyllabus[$c][0]['turno']).
							'/escid/'.base64_encode($this->contentsyllabus[$c][0]['escid']).
							'/subid/'.base64_encode($this->contentsyllabus[$c][0]['subid']).
							'/unit/'.base64_encode($this->contentsyllabus[$c][0]['unit']).
							'/session/'.base64_encode($this->contentsyllabus[$c][0]['session']).
							'/week/'.base64_encode($this->contentsyllabus[$c][0]['week']).
							'/perid/'.base64_encode($this->contentsyllabus[$c][0]['perid']); ?>
	        	<a href="/controlactivity/index/save<?php echo $url ?>" class="btn btn-danger">Marcar Clase</a>
	        	<a id="closeAlert" class="btn btn-default">Cancelar</a>
	      	</p>
	    </div> -->
	
			
	
	<?php if ($this->finalSession == 1): ?>
		<h4 class="text-muted">Clase en <span class="text-info">Curso</span></h4>
	<?php else: ?>
		<h4 class="text-muted">Clase <span class="text-info">Final</span></h4>
	<?php endif ?>

		<div id="presentSession" class="panel panel-warning">
			<table class="table table-bordered table-hover" style='width:100%; background:#EBEBEB'>
				<tr>
					<th style='width:7%'>Semana</th>
					<th style='width:7%'>Unidad</th>
					<th style='width:7%'>Sesión</th>
					<th style='width:79%'>Clase</th>
					<!-- <th></th> -->
				</tr>
				<tr>
					<td><center><?php echo $this->contentsyllabus[$c][0]['week'] ?></center></td>
					<td><center><?php echo $this->contentsyllabus[$c][0]['unit'] ?></center></td>
					<td><center><?php echo $this->contentsyllabus[$c][0]['session'] ?></center></td>
					<td>
						<?php 
						if ($this->contentsyllabus[$c][0]['obj_content']) {
							echo $this->contentsyllabus[$c][0]['obj_content'];
						}
						else{

							echo $this->contentsyllabus[$c][0]['com_conceptual'];
						}
						?>
					</td>

					
					<!-- <td class="text-center col-md-2"><h4><a id="openAlert" class="text-success" href="##"><span class="glyphicon glyphicon-check"></span></a></h4></td> -->
				</tr>
			</table>
		</div>

		<?php if ($this->finalSession == 1): ?>
			
		<h4 class="text-muted" style="opacity : 0.8">Futuras <span class="text-info">Clases</span></h4>
		<?php $c++; ?>
			
		<div id="futureSession" style="opacity : 0.8" class="panel panel-warning">
			<table class="table table-bordered table-hover" style='width:100%'>
				<tr>
					<th style="width:7%">Semana</th>
					<th style="width:7%">Unidad</th>
					<th style="width:7%">Sesión</th>
					<th style="width:79%">Clase</th>
				</tr>
		<?php for ($i = $c; $i < $this->restSession ; $i++): ?>
				<tr>
					<td><center><?php echo $this->contentsyllabus[$c][0]['week'] ?></center></td>
					<td><center><?php echo $this->contentsyllabus[$c][0]['unit'] ?></center></td>
					<td><center><?php echo $this->contentsyllabus[$c][0]['session'] ?></center></td>
					<!-- <td><?php echo $this->contentsyllabus[$c][0]['obj_content'] ?></td> -->
					<td>
						<?php 
						if ($this->contentsyllabus[$c][0]['obj_content']) {
							echo $this->contentsyllabus[$c][0]['obj_content'];
						}
						else{

							echo $this->contentsyllabus[$c][0]['com_conceptual'];
						}
						?>
					</td>
				</tr>
		<?php $c++;
		endfor ?>
			</table>
		</div>

		<?php endif ?>
		
<?php endif ?>	

<?php else: ?>
	
	<h4>No existen registros, tal vez no relleno su silabo aun....</h4>

<?php endif ?>

	</div>
</div>
<?php    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');
    
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    // $mpdf->Output('RecordNotas -'.$this->person['pid'].'.pdf','D');
    $mpdf -> Output();  

?>