<section class="container">
	<section class="content">
		<header class="content__header  content__header--interaction  js_interaction_header">
			<p class="info"><span class="glyphicon glyphicon-info-sign"></span> Puede ver distribuciones de otros años...</p>
			<section class="interaction__content">
				<div class="column_uno">
					<select class="select  js_select" name="anio">
						<!-- {% for i in years %} -->
							<option value="2000">2000</option>
							<option value="1999">1999</option>
						<!-- {% endfor %} -->
					</select>
				</div>
				<div class="column_dos">
					<a href="##" class="button  button--alter  button--alter--new  button--medium  js_button_new">Nuevo</a>
				</div>
			</section>
		</header>
		<section class="content__body">
			<!-- <img class="spinner--block" src="/img/spinner.gif" alt="Loading..."> -->

			<section class="group  group--active">
				<header class="group__header">
					Activo
				</header>
				<section class="group__body  js_group_active">
					<article class="item-table">
						<header class="item-table__header">
							Periódo 15A <small>15A-NHGD</small>
						</header>
						<section class="item-table__body">
							<section class="detail__buttons">
								<a href="##" class="button-icon button-icon--print"><span class="glyphicon glyphicon-eye-open"></span></a>
								<a href="##" class="button-icon button-icon--print"><span class="glyphicon glyphicon-print"></span></a>
								<a href="##" class="button-icon button-icon--danger"><span class="glyphicon glyphicon-trash"></span></a>
							</section>
							<section class="body___main-buttons">
								<div class="button-state  button-state--blue">
									<a href="##">Carga Académica</a>
									<p class="active"><span class="glyphicon glyphicon-ok-sign"></span> Rellenado</p>
								</div>
								<div class="button-state  button-state--blue">
									<a href="##">Administrar Horario</a>
									<p class="inactive"><span class="glyphicon glyphicon-exclamation-sign"></span> Falta</p>
								</div>
							</section>
						</section>
						<footer class="item-table__footer">
							<a href="##">Enviar a Pedagogía</a>
						</footer>
					</article>

					<!-- <p class="empty  margin-small"><span class="glyphicon glyphicon-exclamation-sign"></span> No hay un periodo activo...</p> -->
				</section>
			</section>

		</section>
	</section>
</section>