<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Control de Actividad');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente/notas/index" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<blockquote>
			<h4 class="text-muted">Curso <span class="text-info"><?php echo $this->coursename[0]['name'] ?></span></h4>
		</blockquote>
	</div>
	<div class="col-md-1">
		<blockquote>
			<h4 class="text-info"><span class="glyphicon glyphicon-book"></span></h4>
		</blockquote>
	</div>
</div>

<div class="row">
	<div class="col-md-10 col-md-offset-1">

<?php if ($this->completeSyllabus == 'Si'): ?>
	<div class="alert alert-success fade in">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      	<h4>Completo con exito su silabo :D</h4>
      	<p>Ya finalizo con todas las clases de su silabo.......</p>
    </div>
<?php endif ?>

<?php if ($this->contentsyllabus): ?>

	<?php $c = 0;
	if ($this->firstTime == 'No'): ?>
		<h4 class="text-muted" style="opacity : 0.8">Clases <span class="text-info">Pasadas</span></h4>
		<div id="pastSession" class="panel panel-warning" style="opacity : 0.8">
			<table class="table table-bordered table-hover">
				<tr>
					<th class="text-center">Semana</th>
					<th class="text-center">Unidad</th>
					<th class="text-center">Sesión</th>
					<th class="col-md-5">Clase</th>
					<th class="text-center col-md-2">Fecha de Finalización</th>
					<!-- <th class="">Reprogramar</th> -->
				</tr>
		<?php foreach ($this->contentsyllabus as $content): ?>
				<tr>
					<td class="text-center"><h5><?php echo $content[0]['week'] ?></h5></td>
					<td class="text-center"><h5><?php echo $content[0]['unit'] ?></h5></td>
					<td class="text-center"><h5><?php echo $content[0]['session'] ?></h5></td>
					<td><h5><?php echo $content[0]['obj_content'] ?></h5></td>
					<td class="text-center"><h5><?php echo $this->controlsyllabus[$c][0]['datecheck'] ?></h5></td>
				</tr>
				<?php $c++;
				if ($c == $this->realizedSession): 
					break;
				endif ?>
		<?php endforeach ?>
			</table>
		</div>

	<?php endif ?>


<?php if ($this->completeSyllabus == 'No'): ?>
		<div id="alertCourse" class="alert alert-danger fade in">
	      	<h4>Seguro que deseas marca la clase como realizada</h4>
	      	<p>Una vez que la cambies no habra marcha atras</p>
	      	<p>
	      		<?php $url = '/courseid/'.base64_encode($this->contentsyllabus[$c][0]['courseid']).
							'/curid/'.base64_encode($this->contentsyllabus[$c][0]['curid']).
							'/turno/'.base64_encode($this->contentsyllabus[$c][0]['turno']).
							'/escid/'.base64_encode($this->contentsyllabus[$c][0]['escid']).
							'/subid/'.base64_encode($this->contentsyllabus[$c][0]['subid']).
							'/unit/'.base64_encode($this->contentsyllabus[$c][0]['unit']).
							'/session/'.base64_encode($this->contentsyllabus[$c][0]['session']).
							'/week/'.base64_encode($this->contentsyllabus[$c][0]['week']).
							'/perid/'.base64_encode($this->contentsyllabus[$c][0]['perid']); ?>
	        	<a id='session_checket' href="/controlactivity/index/save<?php echo $url ?>" class="btn btn-danger">Marcar Clase</a>
	        	<a id="closeAlert" class="btn btn-default">Cancelar</a>
	      	</p>
	    </div>
	
			
	
	<?php if ($this->finalSession == 1): ?>
		<h4 class="text-muted">Clase en <span class="text-info">Curso</span></h4>
	<?php else: ?>
		<h4 class="text-muted">Clase <span class="text-info">Final</span></h4>
	<?php endif ?>

		<div id="presentSession" class="panel panel-warning">
			<table class="table table-bordered table-hover">
				<tr>
					<th class="text-center">Semana</th>
					<th class="text-center">Unidad</th>
					<th class="text-center">Sesión</th>
					<th>Clase</th>
					<th></th>
				</tr>
				<tr>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['week'] ?></h5></td>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['unit'] ?></h5></td>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['session'] ?></h5></td>
					<td class="col-md-5"><h5><?php echo $this->contentsyllabus[$c][0]['obj_content'] ?></h5></td>
					
					<td class="text-center col-md-2">
						<h4>
							<input type='text' style="display:none" class='form-control date_session'>
							<a id="openAlert" class="text-success" href="##"><span class="glyphicon glyphicon-check"></span></a>
						</h4>
						<a href="##" id='session_date'>Repregramar</a>
						<a href="##" class="btn btn-primary btn-xs"style='display:none'id='save_session_date'>Guardar</a>
						<a href="##" class="btn btn-danger btn-xs"style='display:none'id='close_session_date'>Cancelar</a>
					</td>
				</tr>
			</table>
		</div>

		<?php if ($this->finalSession == 1): ?>
			
		<h4 class="text-muted" style="opacity : 0.8">Futuras <span class="text-info">Clases</span></h4>
		<?php $c++; ?>
			
		<div id="futureSession" style="opacity : 0.8" class="panel panel-warning">
			<table class="table table-bordered table-hover">
				<tr>
					<th class="text-center">Semana</th>
					<th class="text-center">Unidad</th>
					<th class="text-center">Sesión</th>
					<th class="col-md-5">Clase</th>
				</tr>
		<?php for ($i = $c; $i < $this->restSession ; $i++): ?>
				<tr>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['week'] ?></h5></td>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['unit'] ?></h5></td>
					<td class="text-center"><h5><?php echo $this->contentsyllabus[$c][0]['session'] ?></h5></td>
					<td><h5><?php echo $this->contentsyllabus[$c][0]['obj_content'] ?></h5></td>
					<td class="col-md-2"></td>
				</tr>
		<?php $c++;
		endfor ?>
			</table>
		</div>

		<?php endif ?>
		
<?php endif ?>	

<?php else: ?>
	
	<h4>No existen registros, tal vez no relleno su silabo aun....</h4>

<?php endif ?>

	</div>
</div>

<script>
	$("#session_date").click(function(){
		var td = $(this).parent()
		$("#openAlert").hide()
		$(".date_session").show()
		$("#save_session_date").show()
		$("#close_session_date").show()
		$(this).hide()
	})
	$("#close_session_date").click(function(){
		$("#openAlert").show()
		$("#session_date").show()
		$(".date_session").hide()
		$("#save_session_date").hide()
		$(this).hide()
	})
	$("#alertCourse").fadeOut('fast');
	//$('#alertCourse').fadeOut('fast');
	$('#openAlert').click(function(){
		$('#alertCourse').fadeIn('slow');
	});
	$('#closeAlert').click(function(){
		$('#alertCourse').fadeOut('slow');
	});
	$(".date_session").datepicker({ dateFormat: 'dd/mm/yy' })
	$("#save_session_date").click(function(){
		val_date = $(".date_session").val()
		if (val_date !='' && typeof(val_date)!='undefined') {
			date_save = val_date.split('/')
			date_val = date_save[2]+"-"+date_save[1]+"-"+date_save[0]
			// console.log(date_val)
			var href = $("#session_checket").attr('href')
			$(this).attr('href',href+"/date/"+$.base64.encode(date_val))
		}
	})
	// $("#session_checket").click(function(){
	// 	$("#session_date").find()
	// })

</script>