<link rel="stylesheet" href="/css/controlActivity.css">

<?php $dataCourse = $this->dataCourse ?>
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Control de Actividad');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente/notas/index/perid/'.base64_encode($this->perid).'" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<?php 
	$idsCourse = base64_encode(	$dataCourse['perid'].'-'.
								$dataCourse['escid'].'-'.
								$dataCourse['subid'].'-'.
								$dataCourse['courseid'].'-'.
								$dataCourse['curid'].'-'.
								$dataCourse['turno'] );
 ?>
<input type="hidden" id="currentDate" value="<?php echo $dataCourse['currentDate'] ?>">

<div class="controlActivity_header">
	<p class="controlActivity_p"><?php echo $dataCourse['name'] ?> <small>Turno <?php echo $dataCourse['turno'] ?></small></p>
</div>
<?php if ($dataCourse['syllabus'] == 'C'): ?>
	<?php if ($dataCourse['finishSyllabus'] == 0): ?>
		<div class="controlActivity_Title thingsCompletDis">
			<p class="pCurrentSession">Clase en curso...</p>
		</div>
	<?php endif ?>
	<!-- Clases en curso -->
	<?php foreach ($dataCourse['syllabusContent'] as $cContent => $content): ?>
		<?php if ($cContent == $dataCourse['indexCurrent']):
			$classSession = 'currentSesionActive';
		else:
			$classSession = '';
		endif ?>
		<div id="sessionCurrent<?php echo $cContent ?>" class="controlActivity_currentSesion <?php echo $classSession ?>">
			<form id="formSession<?php echo $cContent ?>">
				<input type="hidden" name="idsCourse" value="<?php echo $idsCourse ?>">
				<input type="hidden" name="currentDate" value="<?php echo $dataCourse['currentDate'] ?>">
				<input type="hidden" id="whySend<?php echo $cContent ?>" name="whySend" value="">

				<input type="hidden" name="unit" value="<?php echo $content['unit'] ?>">
				<input type="hidden" name="week" value="<?php echo $content['week'] ?>">
				<input type="hidden" name="session" value="<?php echo $content['session'] ?>">

				<div class="cSesObOUnity controlActivity_Unidad">
					<p class="parrafoObO">Unidad <?php echo $content['unit'] ?></p>
				</div>
				<div class="cSesObOUnity controlActivity_Week">
					<p class="parrafoObO">Semana <?php echo $content['week'] ?></p>
				</div>
				<div class="cSesObOUnity controlActivity_Sesion">
					<p class="parrafoObO">Sesion <?php echo $content['session'] ?></p>
				</div>
				<div class="controlActivity_Name">
					<p class="parrafoName"><?php echo $content['name'] ?></p>
					<textarea id="textArea<?php echo $cContent ?>" class="controlActivity_textArea" name="comentClase" cols="20" rows="5" placeholder="Comente algo relevante que sucedio en la clase..."></textarea>
				</div>
				<!--Text Area-->
				<a href="##" class="controlActivity_Btns controlActivity_BtnComent" idtextarea="<?php echo $cContent ?>"><span class="parrafoBtn">Comentar</span></a>

				<!-- Clase realizada -->
				<div class="controlActivity_DivRealizedSesion">
					<a href="##" class="btnSessionRealized" idsession="<?php echo $cContent ?>">
						<span class="parrafoBtn">Marcar Clase</span>
						<span id="chargeBtnRealized<?php echo $cContent ?>" class="chargeBtnRealized"></span>
					</a>
					<p class="controlActivity_currentDate">Marque la clase como realizada con la fecha actual <strong><?php echo $dataCourse['currentDate'] ?></strong></p>
				</div>

				<!-- Cambiar fecha -->
				<div id="dateChange<?php echo $cContent ?>" class="controlActivity_SideChangeDate">
					<div class="sideBox">
						<input type="text" id="idDateChange<?php echo $cContent ?>" class="dateChange" name="dateChange">
						<a href="##" class="btnRegisterOtherDate" idsession="<?php echo $cContent ?>">
							Registrar con esta fecha
							<span id="chargeChangeData<?php echo $cContent ?>"></span>
						</a>
					</div>
				</div>
				<a href="##" class="controlActivity_Btns controlActivity_BtnChangeDate" idchangedate="<?php echo $cContent ?>"><span class="parrafoBtn">Cambiar Fecha</span></a>

			</form>
		</div>
	<?php endforeach ?>
	
	<!-- Clases faltantes -->
	<div class="controlActivity_otherSesions">
		<div id="idDivSesionRest" class="otherSesionsObO">
			<p class="otherSesion_title otherSesion_titleSeFa">Sesiones Faltantes</p>
			<?php foreach ($dataCourse['syllabusContent'] as $c => $content): ?>
				<?php if ($c > $dataCourse['indexCurrent']):
					$classSession = 'sessionActive';
				else:
					$classSession = '';
				endif ?>
				<div id="sessionRest<?php echo $c ?>" class="otherSesionsObO_session sessionRest <?php echo $classSession ?>">
					<div class="osObO otherSesionsObO_unity">
						<p class="parrafoDef">Unidad <?php echo $content['unit'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_week">
						<p class="parrafoDef">Semana <?php echo $content['week'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_sessionO">
						<p class="parrafoDef">Sesión <?php echo $content['session'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_name">
						<?php echo $content['name'] ?>
					</div>
				</div>
			<?php endforeach ?>
			
			<!-- Mensage para clases finalizadas -->
			<?php if ($dataCourse['indexCurrent'] != ($cContent + 1)):
				$classMessage = '';
			else:
				$classMessage = 'sessionActive';
			endif ?>
			<p class="otherSesion_parrafoGreat thingsCompletApp <?php echo $classMessage ?>"><span class="glyphicon glyphicon-ok"></span> Vaya! termino todo su sílabo <strong>con exito...</strong></p>

			<?php if ($dataCourse['indexCurrent'] == ($cContent)):
				$classMessage = 'sessionActive';
			else:
				$classMessage = '';
			endif ?>
			<p class="otherSesion_parrafoLessOne thingsLastSession thingsCompletDis <?php echo $classMessage ?>"><span class="glyphicon glyphicon-exclamation-sign"></span> Al parecer le falta solo una sesión <strong>que esta en curso...</strong></p>
		</div>

		<!-- Clases Realizadas -->
		<div id="idDivSesionRealized" class="otherSesionsObO">
			<p class="otherSesion_title otherSesion_titleSeRe">Sesiones Realizadas</p>
			<?php foreach ($dataCourse['syllabusContentInverse'] as $c => $content): ?>
				<?php if ($c > $dataCourse['indexRealized']):
					$classSession = 'sessionActive';
				else:
					$classSession = '';
				endif ?>
				<div id="sessionRealized<?php echo $c ?>" class="otherSesionsObO_session sessionRealized <?php echo $classSession ?>">
					<div class="osObO otherSesionsObO_unity">
						<p class="parrafoDef">Unidad <?php echo $content['unit'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_week">
						<p class="parrafoDef">Semana <?php echo $content['week'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_sessionO">
						<p class="parrafoDef">Sesión <?php echo $content['session'] ?></p>
					</div>
					<div class="osObO otherSesionsObO_name">
						<?php echo $content['name'] ?>
					</div>
					<p id="dateRealized<?php echo $c ?>" class="osObO otherSesionsObO_dateCheck">
						<?php echo $content['dateCheck'] ?>
					</p>
				</div>
			<?php endforeach ?>
			
			<!-- Mensage para marcar clases -->
			<?php if ($dataCourse['indexCurrent'] != 0):
				$classMessage = '';
			else:
				$classMessage = 'sessionActive';
			endif ?>
			<p class="otherSesion_parrafoEmpty thingsStartedSession <?php echo $classMessage ?>"><span class="glyphicon glyphicon-exclamation-sign"></span> Aun no realizó ninguna clase, <strong>no se olvide de marcarla como hecha si ya la termino...</strong></p>
		</div>
	</div>

	<script>
		$(function(){
			var idsCourse     = $('#idsCourse').val();
			var cantSesiones  = 0;
			var sessionAppear = 0;
			var idSession     = 0;
			var idFormSession = '';
			var idTextArea    = '';
			var idChangeDate  = '';
			var formSession   = '';
			var dateRealized  = '';

			//Comentarios de clase
			$('.controlActivity_BtnComent').on('click', function(){
				$(this).toggleClass('controlActivity_BtnComentActive');

				idTextArea = $(this).attr('idtextarea');
				if ($('#textArea' + idTextArea).hasClass('controlActivity_textAreaActive')) {
					$('#textArea' + idTextArea)	.removeClass('controlActivity_textAreaActive')
												.addClass('controlActivity_textAreaInactive');
				}else {
					$('#textArea' + idTextArea)	.removeClass('controlActivity_textAreaInactive')
												.addClass('controlActivity_textAreaActive');
				};
			});

			//Cambiar de Fecha
			$('.dateChange').datepicker();
			$('.controlActivity_BtnChangeDate').on('click', function(){
				$(this).toggleClass('controlActivity_BtnChangeDateActive');

				idChangeDate = $(this).attr('idchangedate');
				if ($('#dateChange' + idChangeDate).hasClass('controlActivity_SideChangeDateActive')) {
					$('#dateChange' + idChangeDate)	.removeClass('controlActivity_SideChangeDateActive')
													.addClass('controlActivity_SideChangeDateInactive');
				}else {
					$('#dateChange' + idChangeDate)	.removeClass('controlActivity_SideChangeDateInactive')
													.addClass('controlActivity_SideChangeDateActive');
				};
			});

			//marcar como realizado
			//Realizado hoy;
			$('.btnSessionRealized').on('click', function(){
				idFormSession = $(this).attr('idsession');
				dateRealized = $('#currentDate').val();
				
				$('#chargeBtnRealized' + idFormSession).html('<img src="/img/spinner.gif" alt="Loading...">');

				$('#whySend' + idFormSession).val('N');
				formSession = $('#formSession' + idFormSession).serialize();
				registerSession(formSession, dateRealized);
			});

			//Realizado cambiando la fecha
			$('.btnRegisterOtherDate').on('click', function(){
				idFormSession = $(this).attr('idsession');
				dateRealized = $('#idDateChange' + idFormSession).val();
				if(dateRealized){
					dateRealized = dateRealized.split('/');
					dateRealized = dateRealized[1] + '-' + dateRealized[0] + '-' + dateRealized[2];
					$('#chargeChangeData' + idFormSession).html('<img src="/img/spinner.gif" alt="Loading...">');
					$('#whySend' + idFormSession).val('O');
					formSession = $('#formSession' + idFormSession).serialize();
					registerSession(formSession, dateRealized);
				}
			});

			//Funciones
			function registerSession(formSession, dateRealized){
				$.ajax({
					type     : 'post',
					url      : '/controlactivity/index/savesession/',
					data     : formSession,
					dataType : 'json',
					success  : function(data){
						if (data.success === 1) {
							//desaparecer Clases Actual
							$('.controlActivity_currentSesion').each(function(index, element){
								if ($(element).hasClass('currentSesionActive')) {
									idSession = index;
									return false;
								};
							});
							$('#sessionCurrent' + idSession).removeClass('currentSesionActive');
							idSession++;
							$('#sessionCurrent' + idSession).addClass('currentSesionActive');

							//Desaparecer de Sesiones Faltantes
							$('.sessionRest').each(function(index, element){
								if ($(element).hasClass('sessionActive')) {
									idSession = index;
									return false;
								};
							});
							$('#sessionRest' + idSession).addClass('sessionHideUp');
							setTimeout(function(){
								$('#sessionRest' + idSession).removeClass('sessionActive');
							}, 300);

							//Aparecer en Sesiones Realizadas
							cantSesiones = 0;
							$('.sessionRealized').each(function(index, element){
								if (!$(element).hasClass('sessionActive')) {
									cantSesiones++;
								};
							});
							sessionAppear = cantSesiones - 1;
							$('#sessionRealized' + sessionAppear)	.addClass('sessionActive');
							$('#dateRealized' + sessionAppear).html(dateRealized);

							//Aparecer y Desaparecer mensajes
							$('.thingsStartedSession').slideUp();
							if (cantSesiones == 1) {
								$('.thingsCompletDis').slideUp();
								$('.thingsCompletApp').slideDown();
							}else if(cantSesiones == 2){
								$('.thingsLastSession').slideDown();
							};
						}else{

						};
					}
				});
		
			}

			/*$('#idDivSesionRest')	.html('<br><br><center><img src="/img/spinner.gif" alt=""></center>')
									.load('/controlactivity/index/sesionrest/data/' + idsCourse);

			$('#idDivSesionRealized')	.html('<br><br><center><img src="/img/spinner.gif" alt=""></center>')
										.load('/controlactivity/index/sesionrealized/data/'+idsCourse);*/
		});
	</script>
<?php else: ?>
	<p class="messageEmpty"><span class="glyphicon glyphicon-exclamation-sign"></span> Al parecer no completo <strong>su sílabo...</strong></p>
<?php endif ?>