<div class="modal-header" style="background-color: #d9edf7">
    <div class="row">
        <div class="col-md-5 col-md-offset-1">
            <h5 class="text-center"><br>Proceso de Matricula <span class="text-danger"><?php echo $this->dataStudent['perid'] ?></span></h5>
            
        </div>
        <div class="col-md-5">
            <p class="text-center">Facultad de <span class="text-info"><?php echo $this->infoSpeciality[0]['nomfac'] ?></span></p>
            <p class="text-center">Escuela de <span class="text-info"><?php echo $this->infoSpeciality[0]['nomesc'] ?></span></p>
        </div>
        <div class="col-md-1">
            <br>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-5 col-md-offset-1">
        <blockquote>
            <br>
            <p><span class="glyphicon glyphicon-user text-info"></span> <?php echo $this->person[0]['last_name0'].' '.$this->person[0]['last_name1'] ?> <span class="text-info"><?php echo $this->person[0]['first_name'] ?></span></p>
            <h6>Codigo <span class="text-info"><?php echo $this->person[0]['uid'] ?></span></h6>
            <h6>Semestre <span class="text-info"><?php echo $this->dataStudent['semid'] ?></span></h6>
        </blockquote>
    </div>

<?php if ($this->courses): ?>
        
    <div class="col-md-3">
        <blockquote>
            <br>
            <h5>Fecha de Pago <span class="text-info"><?php echo $this->paymentData[0]['date_payment'] ?></span></h5>
            <h5>Monto <span class="text-info">S/. <?php echo $this->paymentData[0]['amount'] ?> </span></h5>
            <?php if (!$this->condition and $this->matriculaCondicional == 'No'): 
                $classCondition = 'hidden';
                echo "<br>";
            elseif ($this->condition and $this->matriculaCondicional == 'Si'):
                $classCondition = 'text-success';
                $conditions     = 'Si';
            elseif (!$this->condition and $this->matriculaCondicional == 'Si'):
                $classCondition      = 'text-danger';
                $classButtonValidate = 'disabled';
            endif ?>
            <h5 class="<?php echo $classCondition ?>"><span id="condition">Condiciones <span class="glyphicon glyphicon-flag"></span></span></h5>
            <div class="col-md-6" id='conditionInfo' style="position: absolute; z-index: 2; background: white;">
                <?php if ($this->condition): ?>
                    <?php foreach ($this->condition as $condition): ?>
                        <strong class="text-success"><?php echo $condition['doc_authorize'] ?></strong>
                        <p class="small"><?php echo $condition['comments'] ?></p>
                    <?php endforeach ?>
                <?php else: ?>
                    <strong class="text-danger">No Existe Condiciones</strong>
                <?php endif ?>
            </div>
        </blockquote>
    </div>
    <div class="col-md-2">
        <br>
        <?php $urlRecord =  '/report/recordnotas/print'.'/uid/'.    base64_encode($this->dataStudent['uid']) .
                                                        '/pid/'.    base64_encode($this->dataStudent['pid']) .
                                                        '/escid/'.  base64_encode($this->dataStudent['escid']) .
                                                        '/subid/'.  base64_encode($this->dataStudent['subid']) .
                                                        '/eid/'.    base64_encode($this->dataStudent['eid']) .
                                                        '/oid/'.    base64_encode($this->dataStudent['oid']) ?>
        <a class="btn btn-default form-control" href="<?php echo $urlRecord ?>"><span class="glyphicon glyphicon-print"></span> Imprimir Record</a>
        <br><br>
        <?php if ($this->stateRegister == 'I' or $this->stateRegister == null or $this->stateRegister == 'O' or $this->stateRegister == 'R' or $this->stateRegister == 'B' ): 
            $classPrint = 'hidden';
        else:
            $classPrint = '';
        endif ?>
        <?php $urlPrintRegister =  '/register/registerstudent/print'. 
                                    '/uid/'.    base64_encode($this->dataStudent['uid']) .
                                    '/pid/'.    base64_encode($this->dataStudent['pid']) .
                                    '/escid/'.  base64_encode($this->dataStudent['escid']) .
                                    '/subid/'.  base64_encode($this->dataStudent['subid']) ?>
        <a id="printRegister" class="btn btn-default <?php echo $classPrint ?> form-control" target="_blank" href="<?php echo $urlPrintRegister ?>"><span class="glyphicon glyphicon-print"></span> Imprimir Matricula</a>
    </div>
</div>
<hr>

<!--Mensajes y todas esas cosas-->
<div class="row">
    <div id="waitingSpinner" class="col-md-11 col-md-offset-1">
        
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <!--Confirmación para Eliminar-->
        <div id="confirmDelete" class="alert alert-danger fade in hidden">
            <h4>Seguro que desea Eliminar la Matricula?</h4>
            <p>Una vez que lo haga no habra marcha atras....</p><br>
            <a id="deleteRegister" href="##" class="btn btn-danger">Eliminar</a>
            <a href="##" class="btn btn-default closeConfirmAlert">Cancelar</a>
        </div>
    </div>
</div>
    
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <!--Avisos para la Validación-->
        <div id="successValidate" class="alert alert-success fade in">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>Validación Realizada con Exito</h4>
            <p>Ahora puede imprimir la matricula</p>
        </div>
        <div id="failValidate" class="alert alert-danger fade in">
            <button class="close">&times;</button>
            <h4>Hubo un error en la validación</h4>
            <p>surgio un error mientras se validaba la matricula......</p>
        </div>

        <!--Avisos para la Eliminación-->
        <div id="deleteSuccessRegister" class="alert alert-danger fade in hidden">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>Matricula Eliminada</h4>
            <p>Se elimino la matricula con exito....</p>
        </div>
        <div id="deleteFailRegister" class="alert alert-danger fade in hidden">
            <button class="close">&times;</button>
            <h4>Error al Eliminar</h4>
            <p>Hubo un error al momento de eliminar la matricula....</p>
        </div>

        <!--Avisos para la Observación-->
        <div id="observedSuccessRegister" class="alert alert-warning fade in hidden">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>Matricula Observada con Exito</h4>
            <p>Se observo la matricula con exito....</p>
        </div>
        <div id="observedFailRegister" class="alert alert-danger fade in hidden">
            <button class="close">&times;</button>
            <h4>Error al Observar</h4>
            <p>Hubo un error al momento de observar la matricula....</p>
        </div>
        <!--Avisos para la Reservación-->
        <div id="reservedSuccessRegister" class="alert alert-info fade in hidden">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>Matricula Reservada con Exito</h4>
            <p>Se reservo la matricula con exito....</p>
        </div>
        <div id="reservedFailRegister" class="alert alert-danger fade in hidden">
            <button class="close">&times;</button>
            <h4>Error al Reservar</h4>
            <p>Hubo un error al momento de reservar la matricula....</p>
        </div>
    </div>
</div>

<div class="row">
    <div id="stateRegister" class="col-md-10 col-md-offset-1">
        <?php if ($this->stateRegister == 'I'): 
        $state = 'I';
        $claseFilas = ''; 
        elseif ($this->stateRegister == 'M'): ?>
            <div class="alert alert-success">
                <h5 class="text-center">Matricula Realizada</h5>
            </div>
        <?php 
        $state = 'M';
        $claseFilas = 'success';
        $nameState = 'Matriculado';
        $classButtons = 'hidden';
        elseif ($this->stateRegister == 'O'): ?>
            <div class="alert alert-warning">
                <h5 class="text-center">Matricula Observada</h5>
            </div>
        <?php 
        $state = 'O';
        $claseFilas = 'warning';
        $nameState = 'Observado';
        $classButtons = 'hidden';
        elseif ($this->stateRegister == 'R'): ?>
            <div class="alert alert-info">
                <h5 class="text-center">Matricula Reservada</h5>
            </div>
        <?php 
        $state = 'R';
        $claseFilas = 'info';
        $nameState = 'Reservado';
        $classButtons = 'hidden';
        endif ?>
    </div>
</div>

<!--Imprimir Cursos................. raetod oreiuq odasnac yotse  -->
<div class="row">
    <div id="allDataCourses" class="col-md-9 col-md-offset-1">
        <table class="table table-hover">
            <tr class="active">
                <th class="text-center">#</th>
                <th class="text-center">Codigo</th>
                <th>Curso</th>
                <th class="text-center">Creditos</th>
                <th class="text-center">Turno</th>
                <th>Profesor</th>
                <th class="text-center">Llevando por</th>
        <?php $c = 0;
        foreach ($this->courses as $course): ?>
            <?php if ($this->coursesName[$c]['veces'] >= 2):
                $styleCondition = 'background-color: #f2dede';
                $classtdVeces = 'text-danger';
            else:
                $styleCondition = '';
                $classtdVeces = 'text-success';
            endif ?>
            <tr id="fila<?php echo $course['courseid'] ?>" class="iluminate <?php echo $claseFilas ?>" style="<?php echo $styleCondition ?>">
                <td class="text-center"><?php echo $c + 1 ?></td>
                <td class="text-center"><?php echo $course['courseid'] ?></td>
                <td><?php echo $this->coursesName[$c][0]['name'] ?></td>
                <td class="text-center"><?php echo $this->coursesName[$c][0]['credits'] ?></td>
                <td id="courseTurno<?php echo $course['courseid'] ?>" class="text-center"><?php echo $course['turno'] ?></td>
                <td id="teacherTurno<?php echo $course['courseid'] ?>"><?php echo $this->teachers[$c][0]['last_name0'].' '.$this->teachers[$c][0]['last_name1'].' '.$this->teachers[$c][0]['first_name']  ?> </td>
                <?php if ($state == 'M'): ?>
                <td class="text-center <?php echo $classtdVeces ?>"><strong><?php echo $this->coursesName[$c]['veces'] ?> Vez</strong></td>
                <?php else: ?>
                <td class="text-center <?php echo $classtdVeces ?>"><strong><?php echo $this->coursesName[$c]['veces'] + 1 ?> Vez</strong></td>
                <?php endif ?>
                <td class="text-center <?php echo $classButtons ?> butonsCourses">
                    <a id="showEditAlert<?php echo $course['courseid'] ?>" href="##" title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
                </td>
                <td class="text-center <?php echo $classButtons ?> butonsCourses">
                    <a id="showAlert<?php echo $course['courseid'] ?>" href="##" title="Eliminar Curso" class="text-danger"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
                <td class="text-center text-success tdValidate hidden">Matriculado</td>
                <td class="text-center text-warning tdObserved hidden">Observado</td>
                <td class="text-center text-info tdReserved hidden">Reservado</td>
                <td><strong class="text-<?php echo $claseFilas.' '.$classState ?>"><?php echo $nameState ?></strong></td>
            </tr>

            <tr>
                <td id="alertDeleteCourse<?php echo $course['courseid'] ?>" class="hidden alertSpace" colspan="10">
                    <div class="alert alert-danger">
                        <h5>Seguro que desea eliminar <?php echo $this->coursesName[$c][0]['name'] ?> ?</h5>
                        <p>Una vez que lo haga no habra marcha atras...</p><br>
                        <a id="delete<?php echo $course['courseid'] ?>" href="##" class="btn btn-danger">Eliminar</a>
                        <a href="##" class="btn btn-default cancel">Cancelar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td id="editAlert<?php echo $course['courseid'] ?>" class="hidden alertSpace" colspan="10"></td>
            </tr>
            <script>
                $("#showEditAlert<?php echo $course['courseid'] ?>").click(function(){
                    $('.alertSpace').addClass('hidden');
                    $(".iluminate").removeClass('warning danger');
                    $("#editAlert<?php echo $course['courseid'] ?>").load("/register/registerstudent/editturno/uid/<?php echo base64_encode($course['uid']) ?>/pid/<?php echo base64_encode($course['pid']) ?>/escid/<?php echo base64_encode($course['escid']) ?>/subid/<?php echo base64_encode($course['subid']) ?>/courseid/<?php echo base64_encode($course['courseid']) ?>/curid/<?php echo base64_encode($course['curid']) ?>/turno/<?php echo base64_encode($course['turno']) ?>", function(){
                        $("#editAlert<?php echo $course['courseid'] ?>").removeClass('hidden');
                    });
                    $("#fila<?php echo $course['courseid'] ?>").addClass('warning');
                });

                $("#showAlert<?php echo $course['courseid'] ?>").click(function(){
                    $('.alertSpace').addClass('hidden');
                    $(".iluminate").removeClass('danger warning');
                    $("#alertDeleteCourse<?php echo $course['courseid'] ?>").removeClass('hidden');
                    $("#fila<?php echo $course['courseid'] ?>").addClass('danger');
                });


                $(".cancel").click(function(){
                    $(".iluminate").removeClass('danger warning');
                    $("#alertDeleteCourse<?php echo $course['courseid'] ?>").addClass('hidden');
                });
                $("#delete<?php echo $course['courseid'] ?>").click(function(){
                    $.get("/register/registerstudent/deletecourse/uid/<?php echo base64_encode($course['uid']) ?>/pid/<?php echo base64_encode($course['pid']) ?>/escid/<?php echo base64_encode($course['escid']) ?>/subid/<?php echo base64_encode($course['subid']) ?>/courseid/<?php echo base64_encode($course['courseid']) ?>/curid/<?php echo base64_encode($course['curid']) ?>/turno/<?php echo base64_encode($course['turno']) ?>", function(){
                            $("#fila<?php echo $course['courseid'] ?>").addClass('hidden');
                            $("#alertDeleteCourse<?php echo $course['courseid'] ?>").addClass('hidden');
                    });
                });

            </script>
        <?php $c++;
        endforeach ?>
        </table>
    </div>
    <!--Botones de interacción-->
    <div class="col-md-1">
        <?php if ($state == 'O' or $state == 'R'): 
            $classInteractions = 'hidden';
            $classValidate = 'hidden';
            $classActive = '';
        elseif ($state == 'M'):
            $classValidate = 'hidden';
            $classActive = 'hidden';
        else:
            $classInteractions = '';
            $classActive = 'hidden';
        endif ?>
        <a id="activeRegister" href="##" class="btn btn-success form-control <?php echo $classActive ?>">Activar</a>
        <br><br>
        <div class="validateRegister <?php echo $classValidate ?>">
            <a id="validateRegister" href="##" class="btn btn-success form-control <?php echo $classButtonValidate ?>">Validar</a>
            <br><br>
        </div>
        <div class="reservedRegister <?php echo $classInteractions ?>">
            <a id="reservedRegister" href="##" class="btn btn-info form-control">Reservar</a>
            <br><br>
        </div>
        <div class="observedRegister <?php echo $classInteractions ?>">
            <a id="observedRegister" href="##" class="btn btn-warning form-control">Observar</a>
            <br><br>
        </div>
        <a id="openConfirmAlert" href="##" class="btn btn-danger form-control">Eliminar</a>
    </div>
</div>
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3"><a href="##" class="btn btn-info form-control" id="despliega">Cursos Pendientes</a></div>
</div>

<script>
    //Barra Lateral
    $('#despliega').click(function(){
        $(this).attr('disabled', 'true');
        $("#coursesperCurriculum").addClass('abierto');
        var sameStudent = $("#coursesperCurriculum").attr("student");
        if (sameStudent != <?php echo $this->dataStudent['pid'] ?>) {
            $("#barraLateral").animate({ "left": "-=40%" }, "slow" );
            $("#coursesperCurriculum").attr("student", "<?php echo $this->dataStudent['pid'] ?>");
            $('#mensajeTryAgain').addClass('hidden');
            sendDataBarra();
        }else{
            $("#barraLateral").animate({ "left": "-=40%" }, "slow" );
        }
    });
    $('#tryAgainCurriculum').click(function(){
        sendDataBarra();
        $('#mensajeTryAgain').addClass('hidden');
    });
    

    function sendDataBarra(){
        $("#coursesperCurriculum").html('<br><center>Cargando <img src="/img/spinner.gif" alt="Wait" /></center>');
        $.ajax({
            url    : '/register/registerstudent/coursespercurriculum',
            data   : {  pid  : $.base64.encode("<?php echo $this->dataStudent['pid'] ?>"),
                        uid  : $.base64.encode("<?php echo $this->dataStudent['uid'] ?>"),
                        escid: $.base64.encode("<?php echo $this->dataStudent['escid'] ?>"),
                        subid: $.base64.encode("<?php echo $this->dataStudent['subid'] ?>"),
                        curid: $.base64.encode("<?php echo $this->dataStudent['curid'] ?>") },
            timeout: 15000,
            success: function(data){
                $("#coursesperCurriculum").html(data);
            },
            error: function(){
                $("#coursesperCurriculum").html('');
                $('#mensajeTryAgain').removeClass('hidden');
            }
        })
    }


    //Navegación
    $('#conditionInfo').slideUp();
    $('#condition').hover(function(){
        $('#conditionInfo').slideToggle();
    });

    var stateReg = "<?php echo $this->stateRegister ?>";

    $('#failValidate').addClass('hidden');
    $('#successValidate').addClass('hidden');
    $('a').hover(function(){
        $(this).tooltip('toggle');
    });

    $('.close').click(function(){
        $('#failValidate, #deleteFailRegister, #observedFailRegister, #reservedFailRegister').addClass('hidden');
    });

    $('.closeConfirmAlert').click(function(){
        $('#confirmDelete').addClass('hidden');
    });

    //Validar Matricula
    $('#validateRegister').click(function(){
        $('#waitingSpinner').html('<br><center><img src="/img/spinner.gif" alt="Cargando....." /></center><br>');
        $.get("/register/registerstudent/validate/escid/<?php echo base64_encode($this->dataStudent['escid']) ?>/subid/<?php echo base64_encode($this->dataStudent['subid']) ?>/uid/<?php echo base64_encode($this->dataStudent['uid']) ?>/pid/<?php echo base64_encode($this->dataStudent['pid']) ?>/state/<?php echo base64_encode($this->stateRegister) ?>", function(status){
            if (status.status == true) {
                $('.iluminate').removeClass('warning info');
                $('.iluminate').addClass('success');
                $('.butonsCourses, #stateRegister').addClass('hidden');
                $('#validateRegister').addClass('disabled');
                $('.tdValidate, #successValidate, #printRegister').removeClass('hidden');
                $('#waitingSpinner').html('');
                $('#studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('hidden');
                stateReg = 'M';
                var num = 1;
                var i   = 1;
                $("#students li").each(function(){
                    var classli = $(this).attr('class');
                    if (classli != 'hidden') {
                        $('#studentNum'+[i]).html(num);
                        num++;
                    };
                    i++;
                })
            }else{
                $('#failValidate').removeClass('hidden');
            };
        }, "json");
    });

    //Eliminar Matricula
    $('#openConfirmAlert').on('click', function(){
        $('#confirmDelete').removeClass('hidden');
    }); 

    $('#deleteRegister').click(function(){
        $('#waitingSpinner').html('<br><center><img src="/img/spinner.gif" alt="Cargando....." /></center><br>');
        $.ajax({
            url : '/register/registerstudent/deleteregister',
            data : {pid : $.base64.encode("<?php echo $this->dataStudent['pid'] ?>"),
                    uid : $.base64.encode("<?php echo $this->dataStudent['uid'] ?>"),
                    escid : $.base64.encode("<?php echo $this->dataStudent['escid'] ?>"),
                    subid : $.base64.encode("<?php echo $this->dataStudent['subid'] ?>"),
                    state : $.base64.encode(stateReg) },
            success: function(data){
                if (data == 'true') {
                    $('#allDataCourses').html('<h3 class="text-center">No existen <span class="text-danger">datos...</span></h3>');
                    $('#studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('danger');
                    $('#deleteSuccessRegister').removeClass('hidden');
                    $('#openConfirmAlert, #reservedRegister, #validateRegister, #printRegister, #observedRegister, #activeRegister').addClass('disabled');
                    $('#stateRegister, #confirmDelete').addClass('hidden');
                    $('#waitingSpinner').html('');
                    $('#studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('hidden');
                    stateReg = 'M';
                    var num = 1;
                    var i   = 1;
                    $("#students li").each(function(){
                        var classli = $(this).attr('class');
                        if (classli != 'hidden') {
                            $('#studentNum'+[i]).html(num);
                            num++;
                        };
                        i++;
                    })
                }else{
                    $('#deleteFailRegister').removeClass('hidden');
                };
            }
        });
    });

    //Observar Matricula
    $('#observedRegister').click(function(){
        $('#waitingSpinner').html('<br><center><img src="/img/spinner.gif" alt="Cargando....." /></center><br>')
        $.ajax({
            url : '/register/registerstudent/observedregister',
            data : {pid : $.base64.encode("<?php echo $this->dataStudent['pid'] ?>"),
                    uid : $.base64.encode("<?php echo $this->dataStudent['uid'] ?>"),
                    escid : $.base64.encode("<?php echo $this->dataStudent['escid'] ?>"),
                    subid : $.base64.encode("<?php echo $this->dataStudent['subid'] ?>"),
                    state : $.base64.encode("<?php echo $this->stateRegister ?>") },
            success: function(data){
                if (data == 'true') {
                    $('#stateRegister, .butonsCourses, td strong').addClass('hidden');
                    $('#reservedRegister, #validateRegister, #printRegister, #observedRegister, #activeRegister').addClass('disabled');
                    $('#observedSuccessRegister, .tdObserved').removeClass('hidden');
                    $('.iluminate, #studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('warning');
                    $('#waitingSpinner').html('');
                    $('#studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('hidden');
                    stateReg = 'M';
                    var num = 1;
                    var i   = 1;
                    $("#students li").each(function(){
                        var classli = $(this).attr('class');
                        if (classli != 'hidden') {
                            $('#studentNum'+[i]).html(num);
                            num++;
                        };
                        i++;
                    })
                }else{
                    $('#observedFailRegister').removeClass('hidden');
                };
            }
        });
    });

    //Reservar Matricula
    $('#reservedRegister').click(function(){
        $('#waitingSpinner').html('<br><center><img src="/img/spinner.gif" alt="Cargando....." /></center><br>');
        $.ajax({
            url : '/register/registerstudent/reservedregister',
            data : {pid : $.base64.encode("<?php echo $this->dataStudent['pid'] ?>"),
                    uid : $.base64.encode("<?php echo $this->dataStudent['uid'] ?>"),
                    escid : $.base64.encode("<?php echo $this->dataStudent['escid'] ?>"),
                    subid : $.base64.encode("<?php echo $this->dataStudent['subid'] ?>"),
                    state : $.base64.encode("<?php echo $this->stateRegister ?>") },
            success: function(data){
                if (data == 'true') {
                    $('#stateRegister, .butonsCourses, td strong').addClass('hidden');
                    $('#reservedRegister, #validateRegister, #printRegister, #observedRegister, #activeRegister, #reservedRegister').addClass('disabled');
                    $('#reservedSuccessRegister, .tdReserved').removeClass('hidden');
                    $('.iluminate, #studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('info');
                    $('#waitingSpinner').html('');
                    $('#studentRow<?php echo $this->dataStudent['uid'] ?>').addClass('hidden');
                    stateReg = 'M';
                    var num = 1;
                    var i   = 1;
                    $("#students li").each(function(){
                        var classli = $(this).attr('class');
                        if (classli != 'hidden') {
                            $('#studentNum'+[i]).html(num);
                            num++;
                        };
                        i++;
                    })
                }else{
                    $('#observedFailRegister').removeClass('hidden');
                };
            }
        });
    });

    //Activar Interacciones
    $('#activeRegister').click(function(){
        $('#activeRegister, td strong').addClass('hidden');
        $('.validateRegister, .butonsCourses').removeClass('hidden');
    });
    
</script>

<?php else: ?>
    <br><br>
    <h4 class="text-center text-muted">Aun no hizo la <span class="text-danger">prematricula</span></h4>
<?php endif ?>

<br><br>
















































<!--<?php
$eid=$this->eid;
$oid=$this->oid;
$escid= $this->escid;
$matricula = $this->matricula_;
$estadomatricula=trim($matricula['state']);
$fecha_act = date('Y-m-d');
$finimat = $this->finimat;
$ffinmat =  $this->ffinmat ;
$fin= strtotime($finimat." 11:59:00");
$ffn= strtotime($ffinmat." 11:59:00");
$urlmatri="uid/".base64_encode($matricula['uid'])."/pid/".base64_encode($matricula['pid'])."/escid/".base64_encode($matricula['escid'])."/subid/".base64_encode($matricula['subid']);
?>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  
        <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/jquery/external/base64/jquery.base64.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">      
        <link rel="stylesheet" type="text/css" href="/external/jwysiwyg/jquery.wysiwyg.css">
        <script type="text/javascript" src="/external/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.image.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.link.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.table.js"></script>
        
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        <link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
        
        <link rel="stylesheet" type="text/css" href="/css/style.css">



<div class='found'>
<table class="table  table-condensed " style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #3371F7;" >
    <tr style="color: #D2F6F9;" >
        <th rowspan="3" class="span4">
            <center>
                    <p>                
                    <span style="font-size: 13px">PROCESO MATRICULA  <?php print(strtoupper($this->perid));?>

                    </span><br/>
                    <span style="font-size: 12px">FACULTAD DE 
                        <?php print(strtoupper($this->facultad));?>
                    </span><br/> 
                    <span style="font-size: 12px">ESCUELA DE 
                        <?php echo $this->escuela;?> 
                    </span><br/>
                    <?php if ($this->especialidad<>""){?>
                        <span style="font-size: 12px">ESPECIALIDAD DE 
                            <?php echo $this->especialidad; ?>
                        </span>
                    <?php 
                    }
                    ?>
                    </center>
        </th>
        <th colspan="6">
            <span style="font-size: 14px"><?php print($matricula['uid']);?>  - <?php echo $this->alumno?></span>
        </th>        
    </tr>
    <tr>
        <th style="color: #D2F6F9;" class="span1">Semestre</th>
        <th style="color: #D2F6F9;" class="span1">F.Pago</th>
        <th style="color: #D2F6F9;" class="span1">Monto</th>
        <th style="color: #D2F6F9;" class="span1">Condiciones</th>
        <th class="span1" rowspan="2">
            <a href="/report/recordnotas/print/uid/<?php echo base64_encode($matricula['uid']);?>/pid/<?php echo base64_encode($matricula['pid']);?>/escid/<?php echo base64_encode($matricula['escid'])?>/subid/<?php echo base64_encode($matricula['subid']);?>/eid/<?php echo base64_encode($matricula['eid'])?>/oid/<?php echo base64_encode($matricula['oid']);?>" class="btn btn-info" target="_black">
            <i class="glyphicon glyphicon-list-alt glyphicon-white"></i><br/>Record</a>
        </th>
        <th class="span1"  rowspan="2">
            <?php if ($estadomatricula=="M"){?>
            <a href="/register/registerstudent/print/<?php echo $urlmatri?> " class="btn btn-danger" >
            <i class="glyphicon glyphicon-print glyphicon-white"></i><br/>Imprimir</a>
            <?php }else{?>
                <a href="" class="btn btn-danger" style='color: #ccc' atls="Valide la matricula para imprimir" title="Valide la matricula para imprimir"/>
                <i class="glyphicon glyphicon-print glyphicon-white"></i><br/>Imprimir</a>
            <?php }?>
        </th>
    </tr>
    <tr>
        <td style="color: #D2F6F9;" ><?php print($matricula['semid']);?></td>
        <td >
        <?php
        $titulo="Fecha de Pagos";
        if ($this->pagosrealizados){

            $ff_2="";
            foreach ($this->pagosrealizados as $fepa){
                $tf = split(" ",$fepa['date_payment']);
                $ff_2.="Pago S/. ".$fepa['amount']." el ".$tf[0]." OPE: ".$fepa['operation']."\t";
            }
        }
        $contenido=$ff_2;
        $f = split(" ",$this->fechapago);
        $ft_ = split("-",$f[0]);
        $ft = $ft_[2]."/".$ft_[1]."/".$ft_[0];
        ?>
        <span class="label label-info" id="mostrartexto" rel="popover" data-placement="bottom" data-original-title="<?php echo $titulo?>" data-content="<?php echo $contenido?>">
        <?php echo $ft?></span>
        </td>    
        <td >
            <?php
            $titulo="Tasa de Pagos";        
            $contenido="Monto que le corresponde: <b> S/. ".$this->montoapagar." </b> por la fecha de pago<b>".$this->fechapago."</b>";
            ?>
            <span class="label label-info" id="mostrartexto1" rel="popover" data-placement='bottom' data-original-title="<?php echo $titulo?>" data-content="<?php echo $contenido?>" >
            S/. <?php echo $this->montopagado?></span>
        </td>    
        <td ><center> 
            <?php
            if ($this->condision){
                 $titulo="Condiciones del Alumno";  
                 $cont="Este Alumno Dispone de CONDICIÓN";
                ?>
                <span id="mostrartexto2" rel="popover" data-placement='bottom' data-original-title="<?php echo $titulo?>" data-content="<?php 
                    foreach ($this->condision as $con) {
                            $cred = $con['credits'];
                            $vmat = $con['num_registration'];
                            $sem = $con['semester'];
                            echo $cont;
                        if ($cred !=0 or $cred !='0'){
                            echo "Tiene permitido llevar ". $cond['credits']." créditos mas con resolución" . $cond['doc_authorize'];
                        }

                         if ($vmat !=0 or $vmat !='0'){
                            echo "Tiene permitido llevar Matricula por". $cond['num_registration']." vez con resolución" . $cond['doc_authorize'];
                        }

                        if ($sem !=0 or $sem !='0'){
                            echo "Tiene permitido llevar Matricula en". $cond['sem']." semestres con resolución" . $cond['doc_authorize'];
                        }
                    }?>" >
                    <img src="/img/circulo-verde.png"  width="25" height="25"/>
                </span>
            <?php } 
            else{
                    $tit="Condiciones del Alumno";
                    $cont="No dispone de alguna CONDICIÓN"; ?>
                    <span id="mostrartexto3" rel="popover" data-placement='bottom' data-original-title="<?php echo $tit?>" data-content="<?php echo $cont?>" >
                    <img src="/img/circulo-rojo.png"   width="25" height="25"/>
                </span>
           <?php }
            ?>

             &nbsp;
            </center>
        </td>     
        
    </tr>
</table>
<script type="text/javascript">
$(function(){
    $("#mostrartexto,#mostrartexto1,#mostrartexto2,#mostrartexto3").popover({placement:'bottom',trigger:'hover'});
});
</script>

        <div class='found'>
        <div style="display: block; float: left;width: 720px; height: 200px; overflow: auto;margin: 0px;" >
            <table class="table table-bordered table-condensed" style="width: 700px;font-size: 11px; margin-left: 5px;margin-right: 0px; margin-bottom: 0px;">

                <thead>
                <tr style="background: #333; color: #fff;">    
                        <th style="width:25px">#</th>
                        <th style="width:45px">Cod. </th>
                        <th style="width:250px">Nombre Curso</th>
                        <th style="width:27px">Tur.</th>
                        <th style="width:30px">Sem.</th>
                        <th style="width:25px">Cre.</th>
                        <th style="width:200px">Docente</th>
                        <th style="width:15px">Veces</th>                
                        <th style="width:30px" colspan="2">  Operación.</th>
                </tr>
                </thead>               
                <?php
                
                $a=1;
                if ($this->listacurso)
                {
                foreach ($this->listacurso as $datos){
                        $eid_=$datos['eid'];
                        $oid_=$datos['oid'];
                        $uid_=$datos['uid'];
                        $pid_=$datos['pid'];
                        $courseid_=$datos['courseid'];
                        $curid_=$datos['curid'];
                        $perid_=$datos['perid'];
                        $escid_=$datos['escid'];
                        $subid_=$datos['subid'];
                        $turno_ =$datos['turno'];
                        $semid_ =$datos['semid'];
                        $veces_ =$datos['veces'];
                        $creditos_ =$datos['credits'];
                        $nombrecurso = $datos['namecourse'];
                        $docentes = $datos['teacherp'];
                        $nummat = $datos['nunmatriculados'];
                        $numpremat = $datos['nunmapretriculados'];
                        $texto="rel='popover' data-original-title='$nummat'";
                       $str=base64_encode("eid ='$eid_' and oid='$oid_' and courseid='$courseid_' and curid='$curid_' and perid='$perid_' and escid='$escid_' and subid='$subid_' and turno='$turno_' and uid='$uid_' and pid='$pid_'");
                ?>
                        <tr id="tr_<?php echo $courseid_.$a;?>" style="font-size: 10px" rel='popover' data-original-title=' Hay <?php echo ($nummat=="")?"0":$nummat?> alumnos matriculados y <?php echo ($numpremat=="")?"0":$numpremat?> prematriculados en ese curso'>
                            <td style="width:20px"><?php echo $a;?></td>
                            <td style="width:10px"><?php echo $courseid_;?></td>
                            <td style="width:181px"><?php echo $nombrecurso ;?></td>
                            <td style="width:27px"><?php echo $turno_;?></td>
                            <td style="width:30px"><?php echo $semid_?></td>
                            <td style="width:25px"><?php echo $creditos_;?></td>
                            <td style="width:155px"><?php echo $docentes;?></td>
                            <td style="width:25px" >
                                <?php
                                if ($estadomatricula=="M"){
                                    $veces_ = $veces_;
                                }else{
                                    $veces_ = ($veces_+1);
                                }
                                echo $veces_;
                                if (($veces_)>2){ ?>
                                <script>$("#tr_<?php echo $courseid_.$a;?>").css("background","#FD6868");</script>
                                <?php } ?>
                            </td>
                            <td style="width:15px " >
                                
                            <?php 

                                if ($estadomatricula=='I' ) {
                                   
                                    $urlcurso = "uid/".base64_encode($uid_)."/pid/".base64_encode($pid_)."/escid/".base64_encode($escid_)."/subid/".base64_encode($subid_)."/courseid/".base64_encode($courseid_)."/curid/".base64_encode($curid_)."/turno/".base64_encode($turno_);
                                    ?>
                                    <a id='eliminar' href="/register/registerstudent/deletecourse/<?php echo $urlcurso;?>" onclick="return confirm('Esta Seguro que desea eliminar esta matricula?');"  >
                                        <i class="glyphicon glyphicon-remove"></i>
                                    </a>   
                                <?php }?>
                                </td>
                                <td style="width:15px">
                                    <?php if ($estadomatricula=='I' ) {?>
                                    <a id="editar_<?php echo $courseid_.$a?>" rel="popover"  title="Editar Turno">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                    </a>   
                                    <?php }
                            ?>
                            </td>
                       </tr>
                        <?php
                        if ($estadomatricula<>"M"){ ?>

                            <tr id="formu_<?php echo $courseid_.$a;?>" style="font-size: 10px; color: #000;" data-original-title=' Guardar el Cambio de turno para saber la Cantidad de Matriculados del curso'>
                                <td ><?php echo $a;?></td>
                                <td ><?php echo $courseid_;?></td>
                                <td><?php echo $nombrecurso ;?></td>
                                <td >  
                                <select  name="turno" id="turno_<?php echo $courseid_.$a;?>" style='height:25px;width:50px;color: #000;vertical-align: middle;border: 1px solid #cccccc;border-radius: 4px;background-color: #ffffff;'>
                                    <?php 
                                    $listar = new Api_Model_DbTable_PeriodsCourses();
                                    $where['perid']=$perid_;
                                    $where['eid']=$eid_;
                                    $where['oid']=$oid_;
                                    $where['subid']=$subid_;
                                    $where['escid']=$escid_;
                                    $where['curid']=$curid_;
                                    $where['courseid']=$courseid_;
                                    $list= $listar->_getCourseXTur($where);
                                    foreach ($list as $turno1_){
                                        if ($turno1_['turno']==$turno) $s = "selected";
                                        else $s="";
                                    ?>
                                        <option  value="<?php echo $turno1_['turno']?>" <?php echo $s;?>><?php echo $turno1_['turno']?></option>
                                    <?php } ?>
                                </select>

                                </td>
                                <td ><?php echo $semid_?></td>
                                <td ><?php echo $creditos_;?></td>
                                <td><?php echo $docentes;?></td>
                                <td >
                                <?php
                                if ($estadomatricula=="M"){
                                    $veces_ = $veces_;
                                }else{
                                    $veces_ = ($veces_);
                                }
                                echo $veces_;
                                if (($veces_)>2){ ?>
                                <script>$("#formu_<?php echo $courseid_.$a;?>").css("background","#FD6868");</script>
                                <?php } ?>
                                </td>
                                <td ><a href="#" title="No hacer Ningun Cambio" id="ocultar_<?php echo $courseid_.$a;?>"><i class="glyphicon glyphicon-remove-circle"><i></a></td>                
                                <td ><a href="#" title="Guardar el cambio de Turno" id="enviar_<?php echo $courseid_.$a;?>"><i class="glyphicon glyphicon-ok"></i></a> </td>
                            </tr>
                                <script>
                                $("#formu_<?php echo $courseid_.$a;?>").hide();
                                $("#editar_<?php echo $courseid_.$a; ?>").click(function (){  
                                    $("#tr_<?php echo $courseid_.$a?>").hide();
                                    $("#formu_<?php echo $courseid_.$a?>").show();
                                });
                                $("#ocultar_<?php echo $courseid_.$a;?>").click(function(){
                                    $("#tr_<?php echo $courseid_.$a?>").show();
                                    $("#formu_<?php echo $courseid_.$a?>").hide();
                                });
                                $("#enviar_<?php echo $courseid_.$a?>").click(function (){ 
                                var str = "<?php echo $str;?>";           
                                var tu= $("#turno_<?php echo $courseid_.$a?>").val();
                                var url = "/register/registerstudent/turno/t/"+tu+"/str/"+str+"/nro/"+<?php echo $a;?>+"/";
                                $("#tr_<?php echo $courseid_.$a?>").load(url);
                                $("#tr_<?php echo $courseid_.$a?>").show();
                                $("#formu_<?php echo $courseid_.$a?>").hide(); 
                                });
                            </script>  

                       <?php }
   
                    $a++;
                    }
                }
                ?>
                <tr style="font-size: 10px">
                    <td colspan='4'>&nbsp; </td>
                    <td> Cre. </td>
                    <td> <?php echo $matricula['credits']; ?></td>
                    <td colspan='4'> &nbsp;</td>  
                </tr>
            </table>
        </div> 
        

 <div style="width: 45px;margin: 0px; text-align: center;float: right; margin-right: 50px;" >          
            <?php if ($estadomatricula=='I' ) {?>
            <a id='valida' href="/register/registerstudent/validate/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("M");?>" onclick="return confirm('Esta Seguro que desea validar esta matricula?');"  class="btn btn-success" style="width:80px" >
            <i class="glyphicon glyphicon-ok glyphicon-white"></i><br/>Validar</a><br />

            <a id='observa' href="/register/registerstudent/validate/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("E");?>" onclick="return confirm('Esta Seguro que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:80px" >
            <i class="glyphicon glyphicon-trash glyphicon-white"></i><br/>Eliminar</a><br />  

            <a id='observa' href="/register/registerstudent/validate/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("R");?>" onclick="return confirm('Esta Seguro que desea Reservar esta matricula?');" class="btn  btn-success " style="width:80px" >
            <i class="glyphicon glyphicon-hand-down glyphicon-white"></i><br/>Reservar</a><br />
            
            <?php } 
            if ($estadomatricula=='O' || $estadomatricula=='M'){?>
            <a id='observa' href="/register/registerstudent/validate/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("E");?>" onclick="return confirm('Esta Seguro que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:80px" >
            <i class="glyphicon glyphicon-trash glyphicon-white"></i><br/>Eliminar</a><br />                
            <a id='observa' href="/register/registerstudent/validate/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("R");?>" onclick="return confirm('Esta Seguro que que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:80px" >
                <i class="glyphicon glyphicon-hand-down glyphicon-white"></i><br/>Reservar</a><br />
            <?php }?>
</div>

<div style="clear:both" ></div>

<div style="width: 100%" class="flotacarajo"></div>
<?php if ($estadomatricula=="O"){?>
<div class="alert alert-warning flotacarajo">
    <h3><CENTER>LA MATRICULA FUE OBSERVADA</CENTER></h3>
</div>
<?php }
if ($estadomatricula=="R"){?>
<div class="alert alert-info  flotacarajo">
    <h3><CENTER>LA MATRICULA FUE RESERVADA</CENTER></h3>
</div>
<?php }
if ($estadomatricula=="M"){?>
<div class="alert alert-danger  flotacarajo">
    <h3><CENTER>LA MATRICULA FUE VALIDADA<CENTER></h3>
</div>
<?php }

if ($estadomatricula=="B"){?>
<div class="alert alert-success  flotacarajo">
    <h3><CENTER>EL ALUMNO NO REALIZA SU PREMATRICULA<CENTER></h3>
</div>
<?php } ?>
<br><br><br>
 <?php if ($estadomatricula=='I' || $estadomatricula=='M'){?>
<center><a href="#" class="btn btn-danger" id="clickeaki"> <i class="glyphicon glyphicon-list glyphicon-white"></i><b>Click para ver detalles de los cursos llevados según su currícula</b></a>
</center><br>
<?php } ?>
<div id="pendientes" class="flotacarajo" style="overflow: auto; float: left; height: 200px;width: 750px;">
</div>
<script>
$(function(){
    $("tr[rel=popover]").popover({placement:'bottom',trigger:'hover'});
});
    //cargamos los cursos pendientes 
$("#clickeaki").click(function(){
$("#pendientes").html("<img scr='/img/spinner.gif' />Cargando...");
var urls="/register/registerstudent/listcoursependient/<?php echo $urlmatri?>/curid/<? echo $this->listacurso[0][curid]?>";
$("#pendientes").load("/register/registerstudent/listcoursependient/<?php echo $urlmatri?>/curid/<? echo $this->listacurso[0][curid]?>");
    });    
</script>

<br><br><br><br><br>


        </div>-->

 





