<?php
$eid=$this->eid;
$oid=$this->oid;
$escid= $this->escid;
$matricula = $this->matricula_;
$estadomatricula=trim($matricula['state']);
$fecha_act = date('Y-m-d');
$finimat = $this->finimat;
$ffinmat =  $this->ffinmat ;
$fin= strtotime($finimat." 11:59:00");
$ffn= strtotime($ffinmat." 11:59:00");
echo $urlmatri="uid/".($matricula['uid'])."/pid/".($matricula['pid'])."/escid/".($matricula['escid'])."/subid/".($matricula['subid']);
?>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  
        <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/jquery/external/base64/jquery.base64.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">      
        <!-- Texto Enriquecido-->
        <link rel="stylesheet" type="text/css" href="/external/jwysiwyg/jquery.wysiwyg.css">
        <script type="text/javascript" src="/external/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.image.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.link.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.table.js"></script>
        
        <!-- Bootstrap -->
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        <link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
        
        <!-- JS  -->    
        
        <!-- CSS  Generic-->
        
        <link rel="stylesheet" type="text/css" href="/css/style.css">



<div class='found'>
<table class="table  table-condensed " style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #3371F7;" >
    <tr style="color: #D2F6F9;" >
        <th rowspan="3" class="span4">
            <center>
                    <p>                
                    <span style="font-size: 13px">PROCESO MATRICULA 13A

                    </span><br/>
                    <span style="font-size: 12px">FACULTAD DE 
                        <?php print(strtoupper($this->facultad));?>
                    </span><br/> 
                    <span style="font-size: 12px">ESCUELA DE 
                        <?php echo $this->escuela;?> 
                    </span><br/>
                    <?php if ($this->especialidad<>""){?>
                        <span style="font-size: 12px">ESPECIALIDAD DE 
                            <?php echo $this->especialidad; ?>
                        </span>
                    <?php 
                    }
                    ?>
                    </center>
        </th>
        <th colspan="6">
            <span style="font-size: 14px"><?php print($matricula['uid']);?>  - <?php echo $this->alumno?></span>
        </th>        
    </tr>
    <tr>
        <th style="color: #D2F6F9;" class="span1">Semestre</th>
        <th style="color: #D2F6F9;" class="span1">F.Pago</th>
        <th style="color: #D2F6F9;" class="span1">Monto</th>
        <th style="color: #D2F6F9;" class="span1">Condiciones</th>
        <th class="span1" rowspan="2">
            <a href="/default/recordnotas/imprimir/uid/<?php echo $matricula['uid'];?>/pid/<?php echo $matricula['pid'];?>/escid/<?php echo $matricula['escid']?>/sedid/<?php echo $matricula['sedid'];?>/eid/<?php echo $matricula['eid']?>/oid/<?php echo $matricula['oid'];?>" class="btn btn-info" target="_black">
            <i class="glyphicon glyphicon-list-alt glyphicon-white"></i><br/>Record</a>
        </th>
        <th class="span1"  rowspan="2">
            <?php if ($estadomatricula=="M"){?>
            <a href="/rfacultad/matricula/imprimir/<?php echo $urlmatri?> " class="btn btn-danger" >
            <i class="glyphicon glyphicon-print glyphicon-white"></i><br/>Imprimir</a>
            <?php }else{?>
                <a href="" class="btn btn-danger" style='color: #ccc' atls="Valide la matricula para imprimir" title="Valide la matricula para imprimir"/>
                <i class="glyphicon glyphicon-print glyphicon-white"></i><br/>Imprimir</a>
            <?php }?>
        </th>
    </tr>
    <tr>
        <td style="color: #D2F6F9;" ><?php print($matricula['semid']);?></td>
        <td >
        <?php
        $titulo="Fecha de Pagos";
        if ($this->pagosrealizados){

            $ff_2="";
            foreach ($this->pagosrealizados as $fepa){
                $tf = split(" ",$fepa['date_payment']);
                $ff_2.="Pago S/. ".$fepa['amount']." el ".$tf[0]." OPE: ".$fepa['operation']."\t";
            }
        }
        $contenido=$ff_2;
        $f = split(" ",$this->fechapago);
        $ft_ = split("-",$f[0]);
        $ft = $ft_[2]."/".$ft_[1]."/".$ft_[0];
        ?>
        <span class="label label-info" id="mostrartexto" rel="popover" data-placement="bottom" data-original-title="<?php echo $titulo?>" data-content="<?php echo $contenido?>">
        <?php echo $ft?></span>
        </td>    
        <td >
            <?php
            $titulo="Tasa de Pagos";        
            $contenido="Monto que le corresponde: <b> S/. ".$this->montoapagar." </b> por la fecha de pago<b>".$this->fechapago."</b>";
            ?>
            <span class="label label-info" id="mostrartexto1" rel="popover" data-placement='bottom' data-original-title="<?php echo $titulo?>" data-content="<?php echo $contenido?>" >
            S/. <?php echo $this->montopagado?></span>
        </td>    
        <td ><center> 
            <?php
            if ($this->condision){
                 $titulo="Condiciones del Alumno";  
                 $cont="Este Alumno Dispone de CONDICIÓN";
                ?>
                <span id="mostrartexto2" rel="popover" data-placement='bottom' data-original-title="<?php echo $titulo?>" data-content="<?php 
                    foreach ($this->condision as $con) {
                            $cred = $con['credits'];
                            $vmat = $con['num_registration'];
                            $sem = $con['semester'];
                            echo $cont;
                        if ($cred !=0 or $cred !='0'){
                            echo "Tiene permitido llevar ". $cond['credits']." créditos mas con resolución" . $cond['doc_authorize'];
                        }

                         if ($vmat !=0 or $vmat !='0'){
                            echo "Tiene permitido llevar Matricula por". $cond['num_registration']." vez con resolución" . $cond['doc_authorize'];
                        }

                        if ($sem !=0 or $sem !='0'){
                            echo "Tiene permitido llevar Matricula en". $cond['sem']." semestres con resolución" . $cond['doc_authorize'];
                        }
                    }?>" >
                    <img src="/img/circulo-verde.png"  width="25" height="25"/>
                </span>
            <?php } 
            else{
                    $tit="Condiciones del Alumno";
                    $cont="No dispone de alguna CONDICIÓN"; ?>
                    <span id="mostrartexto3" rel="popover" data-placement='bottom' data-original-title="<?php echo $tit?>" data-content="<?php echo $cont?>" >
                    <img src="/img/circulo-rojo.png"   width="25" height="25"/>
                </span>
           <?php }
            ?>

             &nbsp;
            </center>
        </td>     
        
    </tr>
</table>
<script type="text/javascript">
$(function(){
    $("#mostrartexto,#mostrartexto1,#mostrartexto2,#mostrartexto3").popover({placement:'bottom',trigger:'hover'});
});
</script>

        <div class='found'>
        <div style="display: block; float: left;width: 720px; height: 200px; overflow: auto;margin: 0px;" >
            <table class="table table-bordered table-condensed" style="width: 700px;font-size: 11px; margin-left: 5px;margin-right: 0px; margin-bottom: 0px; ">

                <thead>
                <tr style="background: #333; color: #fff;">    
                        <th style="width:25px">#</th>
                        <th style="width:45px">Cod. </th>
                        <th style="width:250px">Nombre Curso</th>
                        <th style="width:27px">Tur.</th>
                        <th style="width:30px">Sem.</th>
                        <th style="width:25px">Cre.</th>
                        <th style="width:200px">Docente</th>
                        <th style="width:15px">Veces</th>                
                        <th style="width:30px" colspan="2">  Operación.</th>
                </tr>
                </thead>               
                <?php
                
                $a=1;
                if ($this->listacurso)
                {
                foreach ($this->listacurso as $datos){
                        $eid_=$datos['eid'];
                        $oid_=$datos['oid'];
                        $uid_=$datos['uid'];
                        $pid_=$datos['pid'];
                        $courseid_=$datos['courseid'];
                        $curid_=$datos['curid'];
                        $perid_=$datos['perid'];
                        $escid_=$datos['escid'];
                        $subid_=$datos['subid'];
                        $turno_ =$datos['turno'];
                        $semid_ =$datos['semid'];
                        $veces_ =$datos['veces'];
                        $creditos_ =$datos['credits'];
                        $nombrecurso = $datos['namecourse'];
                        $docentes = $datos['teacherp'];
                        $nummat = $datos['nunmatriculados'];
                        $numpremat = $datos['nunmapretriculados'];
                        $texto="rel='popover' data-original-title='$nummat'";
                        $str=base64_encode("eid ='$eid_' and oid='$oid_' and courseid='$courseid_' and curid='$curid_' and perid='$perid_' and escid='$escid_' and subid='$subid_' and turno='$turno_' and uid='$uid_' and pid='$pid_'");
                ?>
                        <tr id="tr_<?php echo $courseid_.$a;?>" style="font-size: 10px" rel='popover' data-original-title=' Hay <?php echo ($nummat=="")?"0":$nummat?> alumnos matriculados y <?php echo $numpremat?> prematriculados en ese curso'>
                            <td style="width:20px"><?php echo $a;?></td>
                            <td style="width:10px"><?php echo $courseid_;?></td>
                            <td style="width:181px"><?php echo $nombrecurso ;?></td>
                            <td style="width:27px"><?php echo $turno_;?></td>
                            <td style="width:30px"><?php echo $semid_?></td>
                            <td style="width:25px"><?php echo $creditos_;?></td>
                            <td style="width:155px"><?php echo $docentes;?></td>
                            <td style="width:25px" >
                                <?php
                                if ($estadomatricula=="M"){
                                    $veces_ = $veces_;
                                }else{
                                    $veces_ = ($veces_+1);
                                }
                                echo $veces_;
                                if (($veces_)>2){ ?>
                                <script>$("#tr_<?php echo $courseid_.$a;?>").css("background","#FD6868");</script>
                                <?php } ?>
                            </td>
                            <td style="width:15px " >
                                
                            <?php 
                            //Verifica si esta dentro de la fecha de matricula
                            //if ($fecha_act>=$finimat && $fecha_act<= $ffinmat){
                                if ($estadomatricula=='I' ) {
                                   
                                    $urlcurso = "uid/".base64_encode($uid_)."/pid/".base64_encode($pid_)."/escid/".base64_encode($escid_)."/sedid/".base64_encode($sedid_)."/cursoid/".base64_encode($cursoid_)."/curid/".base64_encode($curid_);
                                    ?>
                                    <a id='eliminar' href="/rfacultad/matricula/eliminarcurso/<?php echo $urlcurso;?>" onclick="return confirm('Esta Seguro que desea eliminar esta matricula?');"  >
                                        <i class="glyphicon glyphicon-remove"></i>
                                    </a>   
                                <?php }?>
                                </td>
                                <td style="width:15px">
                                    <?php if ($estadomatricula=='I' ) {?>
                                    <a id="editar_<?php echo $courseid_.$a?>" rel="popover"  >
                                        <i class="glyphicon glyphicon-pencil"></i>
                                    </a>   
                                    <?php }
                            //}
                            ?>
                            </td>
                       </tr>
                        <?php
   
                    $a++;
                    }
                }
                ?>
                <tr style="font-size: 10px">
                    <td colspan='4'>&nbsp; </td>
                    <td> Cre. </td>
                    <td> <?php echo $matricula['credits']; ?></td>
                    <td colspan='4'> &nbsp;</td>  
                </tr>
            </table>
        </div> 
        

 <div style="width: 45px;margin: 0px; text-align: center;float: right; margin-right: 50px;" >          
            <?php if ($estadomatricula=='I' ) {?>
            <a id='valida' href="/rfacultad/matricula/validar/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("M");?>" onclick="return confirm('Esta Seguro que desea validar esta matricula?');"  class="btn btn-success" style="width:80px" >
            <i class="glyphicon glyphicon-ok glyphicon-white"></i><br/>Validar</a><br />

            <a id='observa' href="/rfacultad/matricula/validar/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("E");?>" onclick="return confirm('Esta Seguro que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:80px" >
            <i class="glyphicon glyphicon-trash glyphicon-white"></i><br/>Eliminar</a><br />  

            <a id='observa' href="/rfacultad/matricula/validar/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("R");?>" onclick="return confirm('Esta Seguro que desea Reservar esta matricula?');" class="btn  btn-success " style="width:80px" >
            <i class="glyphicon glyphicon-hand-down glyphicon-white"></i><br/>Reservar</a><br />
            
            <?php } 
            if ($estadomatricula=='O' || $estadomatricula=='M'){?>
                <a id='observa' href="/rfacultad/matricula/validar/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("E");?>" onclick="return confirm('Esta Seguro que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:80px" >
                    <i class="glyphicon glyphicon-trash glyphicon-white"></i><br/>Eliminar</a><br />                
        <a id='observa' href="/rfacultad/matricula/validar/<?php echo $urlmatri;?>/flag/<?php echo base64_encode("R");?>" onclick="return confirm('Esta Seguro que que desea Eliminar esta matricula?');" class="btn  btn-success " style="width:50px" >
                <i class="glyphicon glyphicon-hand-down glyphicon-white"></i><br/>Reservar</a><br />
            <?php }?>
</div>
    <?php
    //}else{
//      echo "Matricula Cerrada";
    //}
    ?>


<div style="clear:both" ></div>

<div style="width: 100%" class="flotacarajo"></div>
<?php if ($estadomatricula=="O"){?>
<div class="alert alert-danger flotacarajo">
    <h3>LA MATRICULA FUE OBSERVADA</h3>
</div>
<?php }
if ($estadomatricula=="R"){?>
<div class="alert alert-info  flotacarajo">
    <h3>LA MATRICULA FUE RESERVADA</h3>
</div>
<?php }
?>
<br><br><br>
<center><a href="#" class="btn btn-danger" id="clickeaki"> <i class="glyphicon glyphicon-list glyphicon-white"></i><b>Click para ver detalles de los cursos llevados según su currícula</b></a>
</center><br>
<div id="pendientes" class="flotacarajo" style="overflow: auto; float: left; height: 200px;width: 750px;">
</div>
<script>
$(function(){
    $("tr[rel=popover]").popover({placement:'bottom',trigger:'hover'});
});
</script>

<script>
    //cargamos los cursos pendientes 
    $("#clickeaki").click(function(){
        $("#pendientes").html("<img scr='/img/spinner.gif' />Cargando...");
        var urls="/register/registerstudent/listcoursependient/<?php echo $urlmatri?>/curid/<? echo $this->listacurso[0][curid]?>";
        $("#pendientes").load("/register/registerstudent/listcoursependient/<?php echo $urlmatri?>/curid/<? echo $this->listacurso[0][curid]?>");
    });    
</script>

<br><br><br><br><br>


        </div>        

 





