


<div class="alert alert-warning">
	<form id="formEditTurno">
	<input type="hidden" name="turnoActual" id="turnoActual" value="<?php echo $this->turno ?>">
	<input type="hidden" name="uid" value="<?php echo $this->data['uid'] ?>">
	<input type="hidden" name="pid" value="<?php echo $this->data['pid'] ?>">
	<input type="hidden" name="escid" value="<?php echo $this->data['escid'] ?>">
	<input type="hidden" name="subid" value="<?php echo $this->data['subid'] ?>">
	<input type="hidden" name="courseid" id="courseid" value="<?php echo $this->data['courseid'] ?>">
	<input type="hidden" name="curid" value="<?php echo $this->data['curid'] ?>">
	<?php if ($this->courses): ?>
		<div class="row">
			<div class="col-md-5">
				<h5>Editar <?php echo $this->coursesName[$c][0]['name'] ?></h5>
	    		<p>Edite el turno de este curso, si cambia de turno puede cambiar el profesor a cargo.....</p>
	    	</div>
			<div class="col-md-2">
				Turno
				<select class="form-control turnoCourses" name="turno">
					<?php $c = 0;
					foreach ($this->courses as $course): ?>
						<option value="<?php echo $course['turno'] ?>"><?php echo $course['turno'] ?></option>
					<?php $c++;
					endforeach ?>
				</select>
			</div>
			<div class="col-md-5">
				Docente a Cargo
				<?php $c = 0;
				foreach ($this->teachersInfo as $teacher): ?>
					<h5 id="docente<?php echo $teacher['turno'] ?>" class="hidden docentes">
						<?php echo $teacher[0]['last_name0'].' '.$teacher[0]['last_name1'].' '.$teacher[0]['first_name'] ?></h5>
				<?php $c++;
				endforeach ?>
			</div>
		</div><br>
	    <a id="editCourse" href="##" class="btn btn-warning">Guardar</a>
	    <a href="##" class="btn btn-default cancel">Cancelar</a>
	</form>
		<script>
			var courseid = $('#courseid').val();

			var turnoActual = $('#turnoActual').val();
			var name = $('#docente' + turnoActual).text();
			$('.turnoCourses').val(turnoActual);
			$('#docente' + turnoActual).removeClass('hidden');

			$('.turnoCourses').change(function(){
				turnoActual	= $(this).val();
				var name = $('#docente' + turnoActual).text();
				$('.docentes').addClass('hidden');
				$('#docente' + turnoActual).removeClass('hidden');
			});

			$("#editCourse").click(function(){
				$.ajax({
					type   : 'post',
					url    : '/register/registerstudent/updatecourseperturno',
					data   : $('#formEditTurno').serialize(),
					success: function(data){
						if (data == 'true') {
							$(".iluminate").removeClass('danger warning');
							$("#courseTurno" + courseid).html(turnoActual);
							$("#courseTurno" + courseid).attr('turno', turnoActual);
							$("#teacherTurno" + courseid).html(name);
							$("#editAlert" + courseid).addClass('hidden');
						};
					}
				});
			});

		 	$(".cancel").click(function(){
		        $("#editAlert<?php echo $this->data['courseid'] ?>").addClass('hidden');
		        $(".iluminate").removeClass('danger warning');
		    });

		</script>
	<?php else: ?>
		<h5>No existe otros turnos para este curso....</h5><br>
		<a href="##" class="btn btn-default cancel">Cancelar</a>
		<script>
			$(".cancel").click(function(){
		        $("#editAlert<?php echo $this->data['courseid'] ?>").addClass('hidden');
		        $(".iluminate").removeClass('danger warning');
		    });
		</script>
	<?php endif ?>
</div>