<?php if ($this->datos){ ?>
    <ul>
        <li style="list-style : none;">
            <table class="table table-condensed ">
                <tr class="active">    
                    <th class="col-md-1">#</th>               
                    <th class="col-md-1 text-center">Codigo</th>
                    <th class="col-md-4 text-center">Apellidos y Nombres</th>
                    <th class="col-md-1 text-center">Escuela</th>
                    <th class="col-md-1 text-center">Semestre</th>
                    <th class="col-md-1 text-center">T.Cred.</th>
                    <th class="col-md-1 text-center">Condicion</th>
                    <th class="col-md-1 text-center">Matricular</th>
                </tr>
            </table>
        </li>
    </ul>

    <ul id="students">
    <?php $i=1;
    foreach ($this->datos as $datos){
        switch (trim($datos['estmat'])){
            case 'M': $estadomat_="Matriculado"; break;
            case 'B': $estadomat_="Borrador"; break;
            case 'I': $estadomat_="Iniciado"; break;
            case 'C': $estadomat_="Cerrado"; break;
            case 'R': $estadomat_="Reservado"; break;
            case 'O': $estadomat_="Observado"; break;
        }
        ?>
    <li style="list-style : none;">
        <table class="table">
            <tr>
                <td class="col-md-1"><?php echo $i;?></td>
                <td class="col-md-1 text-center"><?php echo $datos['uid'];?></td>
                <td class="col-md-4"><?php echo $datos['last_name0']." ".$datos['last_name1'].", ".$datos['first_name'];?></td>
                <td class="col-md-1 text-center"><?php echo $datos['escid']?></td>
                <td class="col-md-1 text-center"><?php echo $datos['semid']?></td>
                <td class="col-md-1 text-center"><?php echo $datos['credits']?></td>
                <td class="col-md-1 text-center"><?php echo $estadomat_;?></td>
                <td class="col-md-1 text-center">                    
                    <?php
                        $url= "/register/registerstudent/detail/uid/".base64_encode($datos['uid'])."/pid/".base64_encode($datos['pid'])."/escid/".base64_encode($datos['escid'])."/subid/".base64_encode($datos['subid']);
                    ?>  
                    <a class="text-success" href="<?php echo $url ?>">
                    <span class="glyphicon glyphicon-send"></span>
                    </a>
                </td>
            </tr>
        </table>
    </li>
        <?php
            $i++;
        }?>
    </ul>
    <?php }else{?>
        <br>
        <h4 class="text-muted text-center">No existen <span class="text-danger">Registros</span></h4>
    <?php }?>
