<?php
if ($this->especialidad<>""){
          $esp =$this->especialidad;
         }
(trim($this->estadomatricula)<>"M")?"":$v="VALIDADO";
$a=1;
$cont='';
if ($this->listacurso){
       foreach ($this->listacurso as $datos){
            $cursoid_=$datos['courseid'];
            $turno_ =$datos['turno'];
            $nombrecurso = $datos['namecourse'];
            $semid_ =$datos['semid'];
            $creditos_ =$datos['credits'];
            $docente = $datos['teacherp'];
            $veces_ =$datos['veces'];
        $cont=$cont."<tr>
        <td style='width:20px ;margin-bottom:100px; padding-rigth:12px;'>".$a."</td>
        <td style='width:50px'><b>".$cursoid_."</b></td>
        <td style='width:25px'><b>".$turno_."</b></td>
        <td style='width:250px'><b>".$nombrecurso."</b></td>
        <td style='width:27px'><b>".$semid_."</b></td>
        <td style='width:22px'><b>".$creditos_."</b></td>
        <td style='width:250px'><b>".$docente."</b></td>
        <td>".$veces_."</td>
        </tr>";
         $a++; 
        } 
    }
$html = '
<table  style="font-size:11px; margin-left: 125px; margin-bottom:85px" >     
    <tr>
        <td >'. $this->facultad.'</td>         
    </tr>
    <tr>
        <td  >'.$this->escuela.'</td>
    </tr>
    <tr>
        <td >'.$this->especialidad.' </td>
    </tr>
    <tr>
        <td></td>
    </tr>
</table>
<table  style="font-size:14px;margin-left: 100px; margin-bottom: 48px;" >
    <tr>
        <td style="width: 100px" >'.$this->cod_matri.'</td>
        <td style="width:370px" >'.$this->alumno.'</td>
        <td style="width:100px">'.$this->curricula.'</td>
        <td style="width:20px">'.$this->perid.'</td>
    </tr>
</table>

<div id="datos">
    <table  style="font-size:12px;margin-left:35px;">
        <tr style="   height: 20px"><td></td>
        </tr>
</table>

<div id="datos">
    <table  style="font-size:12px;margin-left:35px;">
        <tr style="   height: 20px"><td></td>
        </tr>
       '.$cont.'
         <tr>
            <td colspan="3"> </td>
            <td> <b>Total Creditos</b> </td>
            <td> </td>
            <td><b>'.$this->total_creditos.'</td>
            <td colspan="2"> </td>  
        </tr>
    </table>
    <div style="clear:both"></div>  <br/>
    <table width="700px" style="font-size:11px;margin-left: 147px;">
        <tr>
            <td>Semestre :'.$this->semestre.'</td>
            <td width="400px" style="float:right">'.$v.'</td>
        </tr>
    </table>
</div>
 <h1  style="margin-left: 130px;"><b><center><span style="font-size: 12px">Usted imprimio la matricula el  '.date('d/m/Y') .' a las  '.date('H:m:s').'</span></b></center></h1> 

';

//==============================================================
//==============================================================
//==============================================================

$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 

$mpdf=new mPDF(); 
$mpdf=new mPDF('win-1252','A4','','','','',22);
$mpdf->WriteHTML($html);
$mpdf->Output();
exit;

//==============================================================
//==============================================================
//==============================================================

?>