<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-briefcase"></span> MODULO GESTION DE ORGANIZACIONES');?>
<?php $this->placeholder('Btnnav')->append('<a href="/admin" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<div class="form-group">
	<h2>
	<div class="pull-right"><a href="/admin/org/new" class="btn btn-info">Nuevo</a>
	</div></h2>
</div>

<table class="table span6">
	<?php print_r($dataorg)?>
	<?php
	if ($this->dataorg) {?>
		<tr>
				<td><b>Num</b></td>
				<td><b>Codigo</b></td>
				<td><b>Nombre</b></td>
		</tr>		
		<?php		
		$c=1;
		foreach ($this->dataorg as $org) {
			?>	
			<tr>
				<td><?php echo $c; ?></td>
				<td><?php echo $org['oid']; ?></td>
				<td><?php echo $org['name']; ?></td>
				<td> <a href="/admin/org/update/oid/<?php print $org['oid']?>">Modificar</a></td>
        		<td> <a href="/admin/org/delete/oid/<?php print $org['oid']?>"onclick="return confirm('Esta Seguro que desea eliminar la sede?');">Eliminar</a></td>
        	</tr>
		<?php
		$c++;
		}
	}
	?>
</table>