<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">

<table class="table span8">
		<th style="font-size: 20px" class="span8">Nueva Organizacion</th>
       		<td><a><?php print $this->form->save;?></a></td>
      	   	<td><br><a href="/admin/org"  class="btn btn-info" >Cancelar</a></td>	
</table>

	<table class="table span7 table-striped table-bordered">
		
		<tr>
				<div class="control-group">
					<td class="span4"><label class="control-label">Codigo:</label></td>
					<td class="span4"><div class="controls">
						<?php print $this->form->oid; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td class="span4"><label class="control-label">Nombre:</label></td>
					<td class="span4"><div class="controls">
						<?php print $this->form->name; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td><label class="control-label">Header</label></td>
					<td><div class="controls">
						<?php print $this->form->header_print; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td><label class="control-label">Footer</label></td>
					<td><div class="controls">
						<?php print $this->form->footer_print; ?>
					</div></td>
				</div>
		</tr>
	</table>
</form>