<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-briefcase"></span> MODIFICAR ORGANIZACION');?>
<?php $this->placeholder('Btnnav')->append('<a href="/admin/org" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">

	<div class="row">
	  <div class="col-sm-8"></div>
	  <div class="col-sm-2"><?php print $this->form->update;?></div>
	  <div class="col-sm-1"><br><a href="/admin/org"  class="btn btn-danger  " >Cancelar</a></br></div>
	</div>

	<table class="table span7 table-striped table-bordered">
		
		<tr>
				<div class="control-group">
					<td class="span4"><label class="control-label">Codigo:</label></td>
					<td class="span4"><div class="controls">
						<?php print $this->form->oid; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td class="span4"><label class="control-label">Nombre:</label></td>
					<td class="span4"><div class="controls">
						<?php print $this->form->name; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td><label class="control-label">Header</label></td>
					<td><div class="controls">
						<?php print $this->form->header_print; ?>
					</div></td>
				</div>
		</tr>
		<tr>
				<div class="control-group">
					<td><label class="control-label">Footer</label></td>
					<td><div class="controls">
						<?php print $this->form->footer_print; ?>
					</div></td>
				</div>
		</tr>
	</table>
</form>