<div class="panel panel-primary">
<div style="width:100%; font-size:15px">
	<b>NUEVO REGISTRO DE CONTENIDO</b>
	<a id="close_drag" href="#" class="btn btn-default" style="margin-left:10px; float: right" rel="tooltip" title="Cerrar Contenido"><span class="glyphicon glyphicon-eject"></span></a>
	<a id="save_content" href="#" class="btn btn-default" style="float: right" rel="tooltip" title="Guardar Contenido"><span class="glyphicon glyphicon-plus"></span></a>
</div>
<form name="<?php echo $this->form->getName(); ?>" id='frmcontentsillabus' action="/syllabus/syllabus/content/tipo_cali/<?php echo base64_encode($this->tipo_cali)?>" method="post" enctype="multipart/form-data">
	<br>
	<table class="table table-striped table-bordered" style="font-size:12px; width:96%; margin-left:20px">
			<tr>
	   			<th style="font-size:15px">Semana:</th>
	   			<td><div style="width:80px"><?php echo $this->form->week ?></div></td>
	   			<th style="font-size:15px">Sesión:</th>
	   			<td><div style="width:80px"><?php echo $this->form->session ?></div></td>
	   		</tr>
			<?php if ($this->tipo_cali=="O") { ?>   
		    <tr>
		       	<th>Contenidos:</th>
		      	<td colspan="3">
		       		<?php echo $this->form->obj_content ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Estrategias:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->obj_strategy ?>
		       	</td>
		    </tr>
			<?php }elseif ($this->tipo_cali=="C") { ?>
		    <tr>
		       	<th>Conceptual:</th>
		      	<td colspan="3">
		       		<?php echo $this->form->com_conceptual ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Procedimental:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_procedimental ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Actitudinal:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_actitudinal ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Indicadores de Desempeño:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_indicators ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Instrumentos de Evaluación:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_instruments ?>
		       	</td>
		    </tr>
		<?php }?>
	</table>
	<input type="hidden" name="turno" value="<?php echo $this->turno?>">
	<input type="hidden" name="perid" value="<?php echo $this->perid?>">
	<input type="hidden" name="courseid" value="<?php echo $this->courseid?>">
	<input type="hidden" name="curid" value="<?php echo $this->curid?>">
	<input type="hidden" name="escid" value="<?php echo $this->escid?>">
	<input type="hidden" name="subid" value="<?php echo $this->subid?>">
	<input type="hidden" name="unit" value="<?php echo $this->numunidad?>">
</form>
</div>

<script type="text/javascript">
$("#close_drag").click(function(){
	$("#tr_content").hide();
});

$("#save_content").click(function(){
	$("#frmcontentsillabus").submit();
});

$("#frmcontentsillabus").submit(function(){
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function(data) {                        
                $('#addcontents').html(data);                                 
            }
        }); 
        return false;
});

var exis = "<?php echo $this->exis?>";
if (exis == 1) {
	$("#tr_content").hide();
	alert("Ya existe un registro de la Sesion ingresada, por favor ingrese nuevamente.");
};

var success = "<?php echo $this->save_success?>";
if (success == 1) {
	window.location.reload();
};
$('a[rel=tooltip]').tooltip();
</script>