<button type='button' class='btn btn-info btn-xs' disabled='disabled' id='add_units_content'><span class ='glyphicon  glyphicon-plus'></span> Añadir Contenido</button>
<table class='table' id='table_units_content' >
    <thead>
        <tr>
            <th>Semana</th>
            <th>Sesión</th>
            <?php
                if($this->params['type_rate']=='O'){
                    echo "<th>Contenido</th>\n<th>Estrategia</th>";}
                if($this->params['type_rate']=='C'){
                    echo "<th>Conceptual</th>\n<th>Procedimental</th>\n<th>Actutudinal</th>";}

            ?>
            <th>Indicadores de Logro</th>
            <?php
                if($this->params['type_rate']=='O'){
                    echo "<th>Instrumentos</th>";}
                if($this->params['type_rate']=='C'){
                    echo "<th>Instrumentos de evaluacion</th>";}

            ?>
        </tr>
        <?php if ($this->params['type_rate']=='C') {
            echo ("<tr><td colspan='7'></td></tr>");
        }?>
        <tr>
            <form id='form_units_content' >
                <td><?php echo $this->form->week ?></td>
                <td><?php echo $this->form->session ?></td>
                <?php if ($this->params['type_rate'] == 'O') {?>
                    <td><?php echo $this->form->obj_content ?></td>
                    <td><?php echo $this->form->obj_strategy ?></td>
                    <td><?php echo $this->form->com_indicators ?></td>
                    <td><?php echo $this->form->com_instruments ?></td>
                <?php }?>
                <?php if ($this->params['type_rate'] == 'C') {?>
                    <td><?php echo $this->form->com_conceptual ?></td>
                    <td><?php echo $this->form->com_procedimental ?></td>
                    <td><?php echo $this->form->com_actitudinal ?></td>
                    <td><?php echo $this->form->com_indicators ?></td>
                    <td><?php echo $this->form->com_instruments ?></td>
                <?php }?>
                <input type="hidden" id='subid_hidden'name ="subid" value="<?php echo base64_encode($this->params['subid'])?>">
                <input type="hidden" id='perid_hidden'name ="perid" value="<?php echo base64_encode($this->params['perid'])?>">
                <input type="hidden" id='escid_hidden'name ="escid" value="<?php echo base64_encode($this->params['escid'])?>">
                <input type="hidden" id='curid_hidden' name ="curid" value="<?php echo base64_encode($this->params['curid'])?>">
                <input type="hidden" id='courseid_hidden' name ="courseid" value="<?php echo base64_encode($this->params['courseid'])?>">
                <input type="hidden" id='turno_hidden'name ="turno" value="<?php echo base64_encode($this->params['turno'])?>">
                <input type="hidden" id='type_hidden' name ="type_rate" value="<?php echo base64_encode($this->params['type_rate'])?>">
                <input type="hidden" id='unit_hidden'name ="unit" value="<?php echo base64_encode($this->params['unit'])?>">
            </form>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data_content) {
            foreach ($this->data_content as $key => $value) {?>
                <tr class='td-edit-content' data-session="<?php echo $value['session']?>" data-week="<?php echo $value['week']?>" >
                    <?php if($this->params['type_rate']=='O'){?>
                        <td><?php echo $value['week'] ?></td>
                        <td><?php echo $value['session'] ?></td>
                        <td><?php echo $value['obj_content'] ?></td>
                        <td><?php echo $value['obj_strategy'] ?></td>
                        <td><?php echo $value['com_indicators'] ?></td>
                        <td><?php echo $value['com_instruments'] ?></td>
                    <?php }?>

                    <?php if ($this->params['type_rate'] == 'C') {?>
                        <td><?php echo $value['week'] ?></td>
                        <td><?php echo $value['session'] ?></td>
                        <td><?php echo $value ['com_conceptual'] ?></td>
                        <td><?php echo $value ['com_procedimental'] ?></td>
                        <td><?php echo $value ['com_actitudinal'] ?></td>
                        <td><?php echo $value ['com_indicators'] ?></td>
                        <td><?php echo $value ['com_instruments'] ?></td>
                    <?php }?>
                    <td class='text-warning' ><span style="display:none" class='glyphicon glyphicon-edit save-edit-unit-content'></span></td>
                    <td class='text-primary'><span class='delete-unit-content glyphicon glyphicon-trash'></span></td>
                </tr>   
        <?php    }
        }?>
    </tbody>
</table>
<script type="text/javascript" src='/js/syllabus/content_units.js'></script>