<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Llenado de Sílabo');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente/notas/index"><span class="glyphicon glyphicon-circle-arrow-left "></span></a>');?>

<?php $this->placeholder('BtnSVCRight')->append('
	<a data-toggle="modal" data-target="#Modalpreviewsyllabus" id="preview_syllbus" class="btn btn-default"><span class="glyphicon glyphicon-eye-open text-info"></span> Vista Previa</a>

	<a id="save_sylabus" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk text-success"></span> Guardar</a>

	<a id="close_sylabus" class="btn btn-default"><span class="glyphicon glyphicon-remove text-danger"></span> Cerrar</a>');?>

<link rel="stylesheet" href="/css/syllabus.css">

<section class="container">
<div class="syllabusFill_Header">
	<p class="syllabusFill_HeaderFacultyName">FACULTAD DE <?php echo strtoupper($this->facultad['name']);?></p>
	<p class="syllabusFill_HeaderSchoolName">ESCUELA DE FORMACIÓN PROFESIONAL DE <?php echo strtoupper($this->escuelas['name']);?></p>
	<div class="syllabusFill_HeaderCubeSide">
		<p class="pCubeSide courseNum"><?php echo $this->num ?></p>
		<p class="pCubeSide courseName"><?php echo $this->curso['name']?></p>
	</div>
</div>

<hr>

<div class="syllabusFill_dataCourse">
	<div class="syllabusFill_ObO syllabusFill_firstData">
		<table class="syllabusFill_table">
			<tr>
				<td>Código</td>
				<td><strong><?php echo $this->curso['courseid']?></strong></td>
			</tr>
			<tr>
				<td>Requisito</td>
				<td><strong>
					<?php if ($this->curso['req_1'] or $this->curso['req_2'] or $this->curso['req_3']): ?>
					<strong><?php echo $this->curso['req_1'] ?> <?php echo $this->curso['req_2'] ?> <?php echo $this->curso['req_3'] ?></strong>
					<?php else: ?>
						-
					<?php endif ?>
				</strong></td>
			</tr>
			<tr>
				<td>Créditos</td>
				<td><strong><?php echo $this->curso['credits']?></strong></td>
			</tr>
			<tr>
				<td>Semestre</td>
				<td><strong><?php echo $this->curso['semid']?></strong></td>
			</tr>
			<tr>
				<td>Docente</td>
				<td><strong><?php echo $this->persona['last_name0']." ".$this->persona['last_name1'].", ".$this->persona['first_name']?></strong></td>
			</tr>
			<?php 
			$datajp=$this->datajp;
			$datauid=$this->datauid;
			if($datajp){ 
				$i=0;
				foreach ($datajp as $data) {
					$retVal = ((substr($datauid[$i]['uid'],8,2))=='JP') ? 'Jefe de Práctica' : 'Docente de Apoyo' ;
			 ?>	
					<tr>
						<td><?php echo $retVal ?></td>
						<td><?php echo $data['last_name0']." ".$data['last_name1'].", ".$data['first_name']?></td>
					</tr>					
				<?php
				$i++;
				}	
			}
			?>
		</table>
	</div>
	<div class="syllabusFill_ObO syllabusFill_secondData">
		<table class="syllabusFill_table">
			<tr>
				<td>Sección</td>
				<td><strong><?php echo $this->where['turno']?></strong></td>
			</tr>
			<tr>
				<td>Extensión Horaria</td>
				<td><strong>HT: <?php echo $this->docente['hours_t']?>	HP: <?php echo $this->docente['hours_p']?> TH: <?php echo $this->docente['hours_total']?></strong></td>
			</tr>
			<tr>
				<td>Duración</td>
				<td><strong><?php echo $this->date_stard ?>	Hasta: <?php echo $this->date_end ?></strong></td>
			</tr>
			<tr>
				<td>Correo Electronico</td>
				<td><strong><?php echo $this->persona['mail_person']?></strong></td>
			</tr>
		</table>
	</div>
</div>

<!--<div>
	<h5 style="margin: 0px 80px 0px 80px"><b>I. DATOS GENERALES:</b></h5> <br>
	<div class="panel panel-default" style="margin: 0px 80px 0px 80px">
		<div class="panel-heading">
		  	<table style="width: 100%">
		  		<tr>
		  			<?php 
		  			if ($this->periodocurso['type_rate']=="C") { ?>
			  			<th>ÁREA:</th>
			  			<td></td>
		  			<?php
		  			}?>
		  			<th>CÓDIGO:</th>
		  			<td><?php echo $this->curso['courseid']?></td>
		  		</tr>
		  		<tr>
		  			<?php echo ($this->periodocurso['type_rate']=='O')?'<th>PREREQUISITO:</th>':''?>
		  			<?php echo ($this->periodocurso['type_rate']=='C')?'<th>REQUISITO:</th>':''?>
		  			<td><?php echo $this->curso['req_1']?> <?php echo $this->curso['req_2']?> <?php echo $this->curso['req_3']?></td>
		  			<th>SECCIÓN:</th>
		  			<td><?php echo $this->where['turno']?></td>
		  		</tr>
		  		<tr>
		  			<th>CREDITOS:</th>
		  			<td><?php echo $this->curso['credits']?></td>
		  			<th>EXTENSIÓN HORARIA:</th>
		  			<td>HT: <?php echo $this->docente['hours_t']?>	HP: <?php echo $this->docente['hours_p']?> TH: <?php echo $this->docente['hours_total']?></td>
		  		</tr>
		  		<tr>
		  			<th>SEMESTRE:</th>
		  			<td><?php echo $this->curso['semid']?></td>
		  			<th>DURACIÓN:</th>
		  			<td>Desde: <?php echo $this->date_stard ?>	Hasta: <?php echo $this->date_end ?></td>
		  		</tr>
		  		<tr>
		  			<th>DOCENTE:</th>
		  			<td><?php echo $this->persona['last_name0']." ".$this->persona['last_name1'].", ".$this->persona['first_name']?></td>
		  			<th>E-MAIL:</th>
		  			<td><?php echo $this->persona['mail_person']?></td>
		  		</tr>
		  	</table>
		</div>
	</div>
</div>-->
<div id="campo"></div>
<div id="savedefault"></div>
  <!-- Modal -->
<div class="modal fade" id="Modalpreviewsyllabus" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title text-primary"><span class='glyphicon glyphicon-eye-open'></span> Llenado de Sílabo Vista Previa</h4>
        </div>
        <div class="modal-body" id="content_preview_syllbus">
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<input type='hidden' id="syl_perid_hidd" value='<?php echo $this->where['perid'] ?>' >
<input type='hidden' id="syl_subid_hidd" value='<?php echo $this->where['subid']?>' >
<input type='hidden' id="syl_turno_hidd" value='<?php echo $this->where['turno']?>' >
<input type='hidden' id="syl_courseid_hidd" value='<?php echo $this->where['courseid']?>' >
<input type='hidden' id="syl_curid_hidd" value='<?php echo $this->where['curid']?>' >
<input type='hidden' id="syl_escid_hidd" value='<?php echo $this->where['escid']?>' >

<div class="modal fade" id="myModal_acccept_colse" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
      		Esta seguro de Cerrar Sílabo 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
          <button type="button" id="accept_close_syllabus" class="btn btn-primary">Aceptar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</section>
<script type="text/javascript" src="/external_library/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/external_library/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript" src="/js/syllabus/syllabus.js"></script>

