<script src="/external/jquery/jquery-1.9.1.js"></script>
<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
<script src="/external/jquery/external/globalize.js"></script>
<script src="/external/jquery/external/jquery.mousewheel.js"></script>
<script src="/external/jquery/external/jshint.js"></script>
<script src="/external/jquery/external/qunit.js"></script>
<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
<script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/style.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<?php
$turno=$this->turno;
$perid=$this->perid;
$courseid=$this->courseid;
$curid=$this->curid;
$escid=$this->escid;
$subid=$this->subid;
$tipo_cali=$this->tipo_cali;
$units=$this->units;
$numunidad=$this->numunidad;
?>
<div style="width:100%; font-size:20px"><br><center><b>NUEVO REGISTRO DE CONTENIDO</b></center></div>
<form name="<?php echo $this->form->getName(); ?>" id='<?php echo $this->form->getName(); ?>' action="<?php echo $this->form->getAction(); ?>" method="post" enctype="multipart/form-data">
	<br>
	<table class="table table-striped table-bordered" style="font-size:13px; width:95%; margin-left:20px">
			<tr>
	   			<th style="font-size:16px">Semana:</th>
	   			<td><div style="width:80px"><?php echo $this->form->week ?></div></td>
	   			<th style="font-size:16px">Sesión:</th>
	   			<td><div style="width:80px"><?php echo $this->form->session ?></div></td>
	   		</tr>
			<?php if ($tipo_cali=="O") { ?>   
		    <tr>
		       	<th>Contenidos:</th>
		      	<td colspan="3">
		       		<?php echo $this->form->obj_content ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Estrategias:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->obj_strategy ?>
		       	</td>
		    </tr>
			<?php }elseif ($tipo_cali=="C") { ?>
		    <tr>
		       	<th>Conceptual:</th>
		      	<td colspan="3">
		       		<?php echo $this->form->com_conceptual ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Procedimental:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_procedimental ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Actitudinal:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_actitudinal ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Indicadores de Desempeño:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_indicators ?>
		       	</td>
		    </tr>
		    <tr>
		       	<th>Instrumentos de Evaluación:</th>
		       	<td colspan="3">
		       		<?php echo $this->form->com_instruments ?>
		       	</td>
		    </tr>
		<?php }?>
	</table>
	<div style="width:100%; text-align:center">
	    <?php echo $this->form->guardar?>
	    <a href="/syllabus/syllabus/units/perid/<?php echo base64_encode($perid)?>/subid/<?php echo base64_encode($subid)?>/escid/<?php echo base64_encode($escid)?>/curid/<?php echo base64_encode($curid)?>/courseid/<?php echo base64_encode($courseid)?>/turno/<?php echo base64_encode($turno)?>/tipo_cali/<?php echo base64_encode($tipo_cali)?>/units/<?php echo $units?>/numunidad/<?php echo $numunidad?>" class="btn btn-danger" style="margin-left:30px"><i class="icon-remove icon-white"></i>Cancelar</a>
	</div>
</form>
