<?php if ($this->form) { ?>
    
<?php 
$tipo = ($this->params['type_rate']=="O")?"Objetivos:":"Capacidad:";
switch ($this->params['unit']) {
    case '1': $numroma="I"; break;
    case '2': $numroma="II"; break;
    case '3': $numroma="III"; break;
    case '4': $numroma="IV"; break;
    case '5': $numroma="V"; break;
    case '6': $numroma="VI"; break;
    case '7': $numroma="VII"; break;
    case '8': $numroma="VIII"; break;
    case '9': $numroma="IX"; break;
    case '10': $numroma="X"; break;
}
?>

<div class="modal-dialog" id='content_syllabus_unit'>
  <div class="modal-content" >
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title"><?php 
                echo ($this->params['type_rate']=='O')? "PROGRAMACIÓN DE UNIDADES":"";
                echo ($this->params['type_rate']=='C')? "PROGRAMACIÓN DE CONTENIDOS":"";
                    ?></h4>
    </div>
    <div class="modal-body">
        <form name="<?php echo $this->form->getName(); ?>" id='<?php echo $this->form->getName(); ?>' action="<?php echo $this->form->getAction(); ?>" method="post" enctype="multipart/form-data">
            <table class='table'>
                <tr>
                    <th style="font-size:20px; width:150px">UNIDAD <?php echo $numroma ?>:</th>
                    <td><?php echo $this->form->name?></td>
                </tr>
                <tr>
                    <th style="font-size:13px"><?php echo $tipo?></th>
                    <td><?php echo $this->form->objetive?></td>
                </tr>
            </table>
            <div id='load_content_unit'>
            </div>
            <table class='table'>
                <tr>
                    <th style="font-size:13px; width:150px">Lectura:</th>
                    <td><?php echo $this->form->reading?></td>
                </tr>
                <tr>
                    <th style="font-size:13px">Actividades:</th>
                    <td><?php echo $this->form->activity?></td>
                </tr>
            </table>
            <input type="hidden" id='subid_hidden'name ="subid" value="<?php echo base64_encode($this->params['subid'])?>">
            <input type="hidden" id='perid_hidden'name ="perid" value="<?php echo base64_encode($this->params['perid'])?>">
            <input type="hidden" id='escid_hidden'name ="escid" value="<?php echo base64_encode($this->params['escid'])?>">
            <input type="hidden" id='curid_hidden' name ="curid" value="<?php echo base64_encode($this->params['curid'])?>">
            <input type="hidden" id='courseid_hidden' name ="courseid" value="<?php echo base64_encode($this->params['courseid'])?>">
            <input type="hidden" id='turno_hidden'name ="turno" value="<?php echo base64_encode($this->params['turno'])?>">
            <input type="hidden" id='type_hidden' name ="type_rate" value="<?php echo base64_encode($this->params['type_rate'])?>">
            <input type="hidden" id='unit_hidden'name ="unit" value="<?php echo base64_encode($this->params['unit'])?>">
        </form>
    </div>
    <div class="modal-footer" id='footer_syllabus'>
      <?php echo ($this->params['unit'] < $this->data_syllabus['units'] )? '<button data-status="'.$this->status.'" type="button" class="btn btn-default" id="btn_next_unit">Siguiente <span class="glyphicon glyphicon-arrow-right"></span></button>':''?>
      <button type="button" class="btn btn-dager" data-dismiss="modal">Cerrar</button>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<script type="text/javascript">
    var $all_units = "<?php echo $this->data_syllabus['units']?>";
</script>
<script type="text/javascript" src="/js/syllabus/unit.js"></script>
<?php }else print_r($this->json);?>