<style type="text/css">
.indent { 
    margin-left: 30px;
}
.detalle { 
    font-size: 12px; 
    text-align: justify; 
    margin-left: 30px;
}
td, th{
    padding-right: 10px;
}
</style>

<?php
$curso=$this->curso[0];
$total=$curso['hours_theoretical']+$curso['hours_practical']; ?>
<div>
    <center>
        <b>FACULTAD DE <?php echo strtoupper($this->facu['name'])?><br>
        ESCUELA DE FORMACIÓN PROFESIONAL DE <?php echo strtoupper($this->escuela['name'])?></b>
    </center>
</div>
<div>
    <h4 style="text-align: center; font-size: 15px;">SILABO</h4>
    <h4 style="text-align: center; font-size: 14px;"><?php echo $curso['name']?></h4>
</div>
<div>
    <center>
        <a href="/syllabus/syllabus/index/courseid/<?php echo base64_encode($this->courseid)?>/turno/<?php echo base64_encode($this->turno)?>/escid/<?php echo base64_encode($this->escid)?>/curid/<?php echo base64_encode($this->curid)?>/subid/<?php echo base64_encode($this->subid)?>/perid/<?php echo base64_encode($this->perid)?>" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>
    </center>
</div>
<div style="margin-left:30px">
    <h3 style="text-align: left; font-size: 14px;">I. DATOS GENERALES</h3>
</div>
<div>
    <table style="margin-left: 20%;text-align: left; font-size: 12px">
    <?php if ($curso["type_rate"]=='C') {
        $num=0; ?>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> AREA:</th>
            <td ><?php echo $tipo?></td>          
        </tr>
    <?php }?>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> CÓDIGO:</th>
            <td><?php echo $curso['courseid']?></td>
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> PREQUISITO:</th>
            <td><?php echo $curso["req_1"]." ".$curso["req_2"]." ".$curso["req_3"];?></td>
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> SECCIÓN:</th>
            <td><?php echo strtoupper($this->turno)?></td>
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> CREDITOS:</th>
            <td> <?php echo $curso['credits']?></td>   
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> EXTENSIÓN HORARIA:</th>
            <td> <?php echo "HT: ".$curso['hours_theoretical']."  "."HP: ". $curso['hours_practical']." "."TH: ".$total?></td>
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> SEMESTRE ACADÉMICO:</th>
            <td><?php echo strtoupper($curso['semid'])?></td>
            
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> DURACIÓN:</th>
            <td><?php echo "Desde: ".$this->periods['class_start_date']."  "."Hasta: ".$this->periods['class_end_date']?></td>
        </tr>
        <tr>
            <th>1.<?php echo $num=$num+1 ?> DOCENTE:</th>
            <td><?php echo $this->infouser['fullname']?></td>
        </tr>
        <tr>
            <th></th>
            <td><strong>e-mail:</strong> <?php echo $this->persona['mail_person']?></td>
        </tr>
    </table>
</div>
<div>
<?php if($this->silabo) { 
    $silabo=$this->silabo;?>
        <div style="margin-left:30px">
            <h5>II. SUMILLA GENERAL</h5>
            <div class='detalle'><?php echo $sumgral['course_sumilla']?></div>
        </div>
        <div style="margin-left:30px">
            <h5>III. SUMILLA ESPECIFICA</h5>
            <div class='detalle'><?php echo $silabo['sumilla']?></div>
        </div>
        <?php if ($curso["type_rate"]=="C") {?>
        <div style="margin-left:30px">
            <h5>IV. COMPETENCIAS Y CAPACIDADES</h5>
            <h5 class='indent'>3.1 COMPETENCIAS</h5>
            <div class='detalle'><?php echo $silabo['competency']?></div>
            <h5 class='indent'>3.2 CAPACIDADES</h5>
            <div class='detalle'><?php echo $silabo['capacity']?></div>
        </div>
        <?php } elseif ($curso["type_rate"]=="O") { ?>
        <div style="margin-left:30px">
            <h5>IV. OBJETIVOS</h5>
            <h5 class='indent'>4.1 OBJETIVO GENERAL</h5>
            <div class='detalle'><?php echo $silabo['competency']?></div>
            <h5 class='indent'>4.2 OBJETIVOS ESPECÍFICOS</h5>
            <div class='detalle'><?php echo $silabo['capacity']?></div>
        </div>
        <div>
        <?php }
        if ($curso["type_rate"]=="C") { ?>
            <h5 style="margin-left:30px">V. PROGRAMACIÓN DE UNIDADES</h5>
        <?php } elseif ($curso["type_rate"]=="O") { ?>
            <h5 style="margin-left:30px">V. PROGRAMACIÓN DE CONTENIDOS</h5>
        <?php } ?>
        </div>
        <?php
        if ($this->datunidades) {
            $unicon = new Api_Model_DbTable_Syllabusunitcontent();
            if ($curso["type_rate"]=="O") {
                foreach ($this->datunidades as $unidades) { 
                    $wherecont['eid']=$unidades['eid'];
                    $wherecont['oid']=$unidades['oid'];
                    $wherecont['perid']=$unidades['perid'];
                    $wherecont['escid']=$unidades['escid'];
                    $wherecont['subid']=$unidades['subid'];
                    $wherecont['courseid']=$unidades['courseid'];
                    $wherecont['curid']=$unidades['curid'];
                    $wherecont['turno']=$unidades['turno'];
                    $wherecont['unit']=$unidades['unit'];
                    $contenidos=$unicon->_getAllXUnit($wherecont); ?>
                    <div class="col-lg-11">
                        <table class="table table-bordered table-condensed table-striped flotacarajo" style="margin-left:60px; margin-bottom:20px">
                            <tr>
                                <td colspan='4'><b>UNIDAD <?php echo $unidades['unit']?>:</b> <?php echo $unidades['name']?></td>
                            </tr>
                            <tr>
                                <td colspan='4'><b>Objetivo Específico:</b> <?php echo $unidades['objetive']?></td>
                            </tr>
                            <?php if ($contenidos) { ?>
                            <tr>
                                <th style="width:30px">Semana</th>
                                <th style="width:30px">Sesión</th>
                                <th>Contenidos</th>
                                <th>Estrategias</th>
                            </tr>
                            <?php
                            foreach ($contenidos as $uniconte) { ?>
                            <tr>
                                <td><?php echo $uniconte['week']?></td>
                                <td><?php echo $uniconte['session']?></td>
                                <td><?php echo $uniconte['obj_content']?></td>
                                <td><?php echo $uniconte['obj_strategy']?></td>
                            </tr>
                            <?php }
                            }?>
                            <tr>
                                <td colspan='4'><b>Lectura:</b> <?php echo $unidades['reading']?></td>
                            </tr>
                            <?php if ($unidades['activity']<>"") { ?>
                            <tr>
                                <td colspan="4"><b>Actividad:</b> <?php echo $unidades['activity']?></td>
                            </tr> 
                            <?php
                        }?>
                        </table>
                    </div><br>
            <?php }
            }elseif ($curso["type_rate"]=="C") { 
                foreach ($this->datunidades as $unidades) {  
                    $wherecont['eid']=$unidades['eid'];
                    $wherecont['oid']=$unidades['oid'];
                    $wherecont['perid']=$unidades['perid'];
                    $wherecont['escid']=$unidades['escid'];
                    $wherecont['subid']=$unidades['subid'];
                    $wherecont['courseid']=$unidades['courseid'];
                    $wherecont['curid']=$unidades['curid'];
                    $wherecont['turno']=$unidades['turno'];
                    $wherecont['unit']=$unidades['unit'];
                    $contenidos=$unicon->_getAllXUnit($wherecont); ?>
                    <div class="col-lg-11">
                        <table class="table table-bordered table-condensed table-striped" style="margin-left:60px; margin-bottom:20px">
                            <tr>
                                <td colspan='7'><b>UNIDAD <?php echo $unidades['unit']?>:</b> <?php echo $unidades['name']?></td>
                            </tr>
                            <tr>
                                <td colspan='7'><b>Capacidad:</b> <?php echo $unidades['objetive']?></td>
                            </tr>
                            <tr>
                                <th colspan='7'><center>CONTENIDOS DE APRENDIZAJE</center></th>
                            </tr>
                            <?php if ($contenidos) { ?>
                            <tr>
                                <th style="width:30px">Semana</th>
                                <th style="width:30px">Sesión</th>
                                <th>Conceptual</th>
                                <th>Procedimental</th>
                                <th>Actitudinal</th>
                                <th>Indicadores de Desempeño</th>
                                <th>Instrumentos de Evaluación</th>
                            </tr>
                            <?php
                            foreach ($contenidos as $uniconte) { ?>
                            <tr>
                                <td><?php echo $uniconte['week']?></td>
                                <td><?php echo $uniconte['session']?></td>
                                <td><?php echo $uniconte['com_conceptual']?></td>
                                <td><?php echo $uniconte['com_procedimental']?></td>
                                <td><?php echo $uniconte['com_actitudinal']?></td>
                                <td><?php echo $uniconte['com_indicators']?></td>
                                <td><?php echo $uniconte['com_instruments']?></td>
                            </tr>
                            <?php }
                            }?>
                            <tr>
                                <td colspan='7'><b>Lectura:</b> <?php echo $unidades['reading']?></td>
                            </tr>
                            <tr>
                                <td colspan="7"><b>Actividad:</b> <?php echo $unidades['activity']?></td>
                            </tr> 
                        </table>
                    </div><br>
                <?php
                }
            }
        }?>

      <?php if ($curso['type_rate']=='C') {
        $rom="I"; ?>
        <div style="margin-left:30px; float:left">
            <h5>VI. ESTRATEGIAS METODÓLOGICAS</h5>
            <div class="detalle"><?php echo $silabo['methodology']?></div>
        </div> 
      <?php }?>
        <div style="margin-left:30px; float:left">
            <h5>VI<?php echo $rom?>. MEDIOS Y MATERIALES</h5>
            <div class="detalle"><?php echo $silabo['media']?></div>

            <h5>VII<?php echo $rom?>. SISTEMA DE EVALUACIÓN</h5>
            <div class="detalle"><?php echo $silabo['evaluation']?></div>

            <h5>VIII<?php echo $rom?>. FUENTES DE INFORMACIÓN</h5>
            <div class="detalle"><?php echo $silabo['sources']?></div>
        </div>
<?php }?>
</div>