<script type="text/javascript" src="/external_library/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/external_library/ckeditor/adapters/jquery.js"></script>

<?php
$tipo=($this->periodocurso['type_rate']=="O")? "OBJETIVOS": "COMPETENCIAS"; ?>

<?php if ($this->msgclose=="1") { ?>
	<div class="panel panel-default" style="margin: 0px 80px 0px 80px">
		<div class="panel-body">
			<div class="alert alert-danger" style="font-size:18px">
				<b>Aviso: </b>Rellene los campos obligatorios para Cerrar el Silabo.
			</div>
		</div>
	</div>

<?php }
if ($this->periodocurso['type_rate']!="O" && $this->periodocurso['type_rate']!="C") { ?>
	<div class="panel panel-default" style="margin: 0px 80px 0px 80px">
		<div class="panel-body">
			<div class="alert alert-info">
		  		<b>Información: </b>El director no ingreso todos los datos de la asignatura, comunique a su director de Escuela que actualize su Distribución Académica.
		  	</div>
		</div>
	</div>
<?php }?>

<form name="<?php echo $this->form->getName(); ?>" id='frmSyllabus' action="/syllabus/syllabus/viewfrm" method="post" enctype="multipart/form-data">
<?php
$rom="";
if ($this->periodocurso['type_rate']=="O" || $this->periodocurso['type_rate']=="C") {
	if ($this->syllabus['state']=="B") { ?>
			<div>
		<div class="panel-group" id="accordion2" style="margin: 0px 80px 0px 80px">
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapseO">
		                	II. SUMILLA
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapseO" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->sumilla?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
		             		<?php 
		             		if ($this->periodocurso['type_rate']=='C') echo "III. COMPETENCIA Y CAPACIDADES";
		             		if ($this->periodocurso['type_rate']=='O') echo "III. OBJETIVOS";
		             		?>
		             		<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse1" class="panel-collapse collapse">
	              	<div class="panel-body">
					    <?php 
					    if ($this->periodocurso['type_rate']=='C') {?>
			                    <div><h5>3.1 COMPETENCIA</h5></div>
			                    <?php echo $this->form->competency?>
			                    <div><h5>3.2 CAPACIDADES</h5></div>
			                    <?php echo $this->form->capacity?>
			            <?php }
			            if ($this->periodocurso['type_rate']=='O') {?>
			                    <div><h5>3.1 Objetivo General</h5></div>
			                    <?php echo $this->form->competency?>
			                    <div><h5>3.2 Objetivos Específicos</h5></div>
			                    <?php echo $this->form->capacity?>
			            <?php }?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
		                	<?php 
		             		if ($this->periodocurso['type_rate']=='C') echo "IV. PROGRAMACIÓN DE UNIDADES";
		             		if ($this->periodocurso['type_rate']=='O') echo "IV. PROGRAMACIÓN DE CONTENIDOS";
		             		?>
		             		<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse2" class="panel-collapse collapse">
	              	<div class="panel-body">
	                	<h5 style="float:left">Ingrese Cantidad de Unidades: </h5>
	                	<div style="width:60px; float:left; margin-left:30px"><?php echo $this->form->units?></div>
	                	<a data-toggle="modal" data-target="#myModalSyllabus" id="crearunidad" class="btn btn-info" style="margin-left:30px"><span class="glyphicon glyphicon-pencil"></span>Crear Unidades</a>
	              	</div>
	         	</div>
	      	</div>
	      	<?php if ($this->periodocurso['type_rate']=='C') {
	        $rom="I"; ?>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse3">
		                	V. ESTRATEGIAS METÓDOLOGICAS
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse3" class="panel-collapse collapse">
	              	<div class="panel-body">
	                	<?php echo $this->form->methodology?>
	              	</div>
	         	</div>
	      	</div>
	      <?php }?>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse4">
		                	V<?php echo $rom?>. MEDIOS Y MATERIALES
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse4" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->media?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse5">
		                	VI<?php echo $rom?>. SISTEMA DE EVALUACIÓN
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse5" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->evaluation?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse6">
		                	VII<?php echo $rom?>. FUENTES DE INFORMACIÓN
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse6" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->sources?>
	              	</div>
	         	</div>
	      	</div>
	    </div>
	    </div>
	<?php
	}elseif($this->syllabus['state']=="C"){ ?>
		<div style="margin:20px">
			<center>
				<a href="/syllabus/print/index/courseid/<?php echo base64_encode($this->courseid)?>/curid/<?php echo base64_encode($this->curid)?>/escid/<?php echo base64_encode($this->escid)?>/turno/<?php echo base64_encode($this->turno)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>" class="btn btn-primary" style="margin-left:150px"><span class="glyphicon glyphicon-print"></span> Imprimir</a>
			</center>
		</div>
		<?php
	}
}?>
<input type="hidden" id='subid_hidden'name ="subid" value="<?php echo base64_encode($this->periodocurso['subid'])?>">
<input type="hidden" id='perid_hidden'name ="perid" value="<?php echo base64_encode($this->periodocurso['perid'])?>">
<input type="hidden" id='escid_hidden'name ="escid" value="<?php echo base64_encode($this->periodocurso['escid'])?>">
<input type="hidden" id='curid_hidden' name ="curid" value="<?php echo base64_encode($this->periodocurso['curid'])?>">
<input type="hidden" id='courseid_hidden' name ="courseid" value="<?php echo base64_encode($this->periodocurso['courseid'])?>">
<input type="hidden" id='turno_hidden'name ="turno" value="<?php echo base64_encode($this->periodocurso['turno'])?>">
</form>
<div class="modal fade" id="myModalSyllabus" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<script type="text/javascript">
	var $send_units = false;
	var $type_rate = "<?php echo $this->periodocurso['type_rate']?>";
	$("#units").keypress(function(){
		$send_units = true;
	});
	$("#units").keyup(function(){
		$send_units = true;
	});
	

</script>
<script type="text/javascript" src="/js/syllabus/syllabus.js"></script>