<div id="closeSyllabusModal" class="divCloseSyllabusModal" hidden>
	<div class="capaNegra"></div>
	<div class="message">
		<div class="cursoSide">
			<p class="nombreCurso">
				<?php print($this->dataCourse['name']) ?> <small>Turno <?php print($this->dataCourse['turno']) ?></small>
			</p>
			<p class="escuela">
				<?php print($this->dataCourse['escuela']) ?>
			</p>
		</div>
		<p id="idStateSilabo" class="stateSilabo stateNoClose">Cerrando Silabo <span class="stateDiv"><img src="/img/spinner.gif" alt="Loading..."></span></p>
		<div class="anotherCourses">
			<?php if ($this->dataAnotherCourses == 'no'): ?>
				<p class="infoText text-muted"><span class="glyphicon glyphicon-info-sign"></span> No se detectaron otros turnos asignados para clonar el sílabo, o talvez ya han sido cerrados.</p>
			<?php else: ?>
				<p class="infoText text-muted"><span class="glyphicon glyphicon-info-sign"></span> Se detecto otros turnos a este mismo curso y en esta misma escuela, a continuación se clonara el sílabo. <br>
				<span class="glyphicon glyphicon-exclamation-sign text-danger"></span> <strong>Recuerde que necesita <span class="text-danger">cerrar</span> el silabo del curso al que se esta clonando.</strong></p>

				<?php foreach ($this->dataAnotherCoursesArray as $c => $course): ?>
					<p class="anotherCurso text-muted"><?php print($this->dataCourse['name']) ?> <small>Turno <?php print($course['turno']) ?></small> <span class="chargeDiv"><img src="/img/spinner.gif" alt="Loading.."> Clonando</span></p>
				<?php endforeach ?>
			<?php endif ?>
		</div>
		<p class="paciencia text-danger"><span class="glyphicon glyphicon-time"></span> Tenga paciencia, esto puede tardar un par de minutos....</p>
	</div>
</div>
<br>
<?php
$tipo=($this->periodocurso['type_rate']=="O")? "OBJETIVOS": "COMPETENCIAS"; ?>



<div id='error-syllabus' class="alert alert-danger divErrorSyllabus" hidden>
	<p><span class="glyphicon glyphicon-exclamation-sign"></span> Rellene todos los campos obligatorios para <strong>Cerrar el Silabo.</strong></p>
</div>

<?php 
if ($this->periodocurso['type_rate']!="O" && $this->periodocurso['type_rate']!="C") { ?>
	<div class="panel panel-default" style="margin: 0px 80px 0px 80px">
		<div class="panel-body">
			<div class="alert alert-info">
		  		<b>Información: </b>El director no ingreso todos los datos de la asignatura, comunique a su director de Escuela que actualize su Distribución Académica.
		  	</div>
		</div>
	</div>
<?php }?>

<form name="<?php echo $this->form->getName(); ?>" id='frmSyllabus' enctype="multipart/form-data">
<?php
$rom="";
if ($this->periodocurso['type_rate']=="O" || $this->periodocurso['type_rate']=="C") {
	if ($this->syllabus['state']=="B") { ?>
			<div>
		<div class="panel-group" id="accordion2" style="margin: 0px 80px 0px 80px">
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapseO">
		                	II. SUMILLA
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapseO" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->sumilla?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
		             		<?php 
		             		if ($this->periodocurso['type_rate']=='C') echo "III. COMPETENCIA Y CAPACIDADES";
		             		if ($this->periodocurso['type_rate']=='O') echo "III. OBJETIVOS";
		             		?>
		             		<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse1" class="panel-collapse collapse">
	              	<div class="panel-body">
					    <?php 
					    if ($this->periodocurso['type_rate']=='C') {?>
			                    <div><h5>3.1 COMPETENCIA</h5></div>
			                    <?php echo $this->form->competency?>
			                    <div><h5>3.2 CAPACIDADES</h5></div>
			                    <?php echo $this->form->capacity?>
			            <?php }
			            if ($this->periodocurso['type_rate']=='O') {?>
			                    <div><h5>3.1 Objetivo General</h5></div>
			                    <?php echo $this->form->competency?>
			                    <div><h5>3.2 Objetivos Específicos</h5></div>
			                    <?php echo $this->form->capacity?>
			            <?php }?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
		                	<?php 
		             		if ($this->periodocurso['type_rate']=='C') echo "IV. PROGRAMACIÓN DE UNIDADES";
		             		if ($this->periodocurso['type_rate']=='O') echo "IV. PROGRAMACIÓN DE CONTENIDOS";
		             		?>
		             		<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse2" class="panel-collapse collapse">
	              	<div class="panel-body">
	                	<h5 style="float:left">Ingrese Cantidad de Unidades: </h5>
	                	<?php echo $this->form->units?>
	                	<a data-toggle="modal" data-target="#myModalSyllabus" id="crearunidad" class="btn btn-info" style="margin-left:30px"><span class="glyphicon glyphicon-pencil"></span>Crear Unidades</a>
	              	</div>
	         	</div>
	      	</div>
	      	<?php if ($this->periodocurso['type_rate']=='C') {
	        $rom="I"; ?>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse3">
		                	V. ESTRATEGIAS METÓDOLOGICAS
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse3" class="panel-collapse collapse">
	              	<div class="panel-body">
	                	<?php echo $this->form->methodology?>
	              	</div>
	         	</div>
	      	</div>
	      <?php }?>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse4">
		                	V<?php echo $rom?>. MEDIOS Y MATERIALES
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse4" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->media?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse5">
		                	VI<?php echo $rom?>. SISTEMA DE EVALUACIÓN
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse5" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->evaluation?>
	              	</div>
	         	</div>
	      	</div>
	      	<div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h6 class="panel-title" style="font-size:14px">
		             	<a class="accordion-toggle height" data-toggle="collapse" data-parent="#accordion2" href="#collapse6">
		                	VII<?php echo $rom?>. FUENTES DE INFORMACIÓN
		                	<span class="glyphicon glyphicon-chevron-down" style="float: right"></span>
		              	</a>
	        		</h6>
	        	</div>
	        	<div id="collapse6" class="panel-collapse collapse">
	              	<div class="panel-body">
			        	<?php echo $this->form->sources?>
	              	</div>
	         	</div>
	      	</div>
	    </div>
	    </div>
	<?php
	}elseif($this->syllabus['state']=="C"){ ?>
		<div style="margin:20px">
			<center>
				<a href="/syllabus/print/index/courseid/<?php echo base64_encode($this->courseid)?>/curid/<?php echo base64_encode($this->curid)?>/escid/<?php echo base64_encode($this->escid)?>/turno/<?php echo base64_encode($this->turno)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>" class="btn btn-primary" style="margin-left:150px"><span class="glyphicon glyphicon-print"></span> Imprimir</a>
			</center>
		</div>
		<?php
	}
}?>
<input type="hidden" id='subid_hidden'name ="subid" value="<?php echo base64_encode($this->periodocurso['subid'])?>">
<input type="hidden" id='perid_hidden'name ="perid" value="<?php echo base64_encode($this->periodocurso['perid'])?>">
<input type="hidden" id='escid_hidden'name ="escid" value="<?php echo base64_encode($this->periodocurso['escid'])?>">
<input type="hidden" id='curid_hidden' name ="curid" value="<?php echo base64_encode($this->periodocurso['curid'])?>">
<input type="hidden" id='courseid_hidden' name ="courseid" value="<?php echo base64_encode($this->periodocurso['courseid'])?>">
<input type="hidden" id='turno_hidden'name ="turno" value="<?php echo base64_encode($this->periodocurso['turno'])?>">
<input type="hidden" id='type_hidden'name ="type_rate" value="<?php echo base64_encode($this->periodocurso['type_rate'])?>">

<input type="hidden" id="anotherCourses" name="anotherCourses" value="<?php echo base64_encode($this->dataAnotherCourses) ?>">
</form>
<div class="modal fade" id="myModalSyllabus" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<script type="text/javascript">
	
	

</script>
