<style type="text/css">
.text-header-registration{
	color: #34495e;
}
.form-control{
	width: 53px;
}
</style>
<script type="text/javascript" src="/external/notes/notes-target.js"></script>

<?php $infocourse=$this->infocourse;?>
<div class='row'>
	<div class='col-xs-8 header-registration-course'>
		<h4 class='text-header-registration'> <span class='glyphicon glyphicon-list' style='color:#1abc9c;'></span> 
			<?if($this->partial==1){
				echo "Primer Parcial ";
			}?>
			<?if($this->partial==2){
				echo "Segundo Parcial";
			}?>

			<?php echo $infocourse['name']?> Turno <?php echo $this->turno?></h4>
		
	</div>
	
	<div class="col-md-4">
		<?php if (ddd) { ?>
			<buttom  class='btn btn-info ' id='save_notes' disabled ><span class='glyphicon glyphicon-save'></span> Guardar</buttom>
		
		<buttom  class='btn btn-danger' id='closure-assistance' onclick='closurerecord(this);'
				coursoid='<?php echo $infocourse['courseid']?>'
				escid='<?php echo $infocourse['escid']?>'
				curid='<?php echo $infocourse['curid']?>'
				subid='<?php echo $infocourse['subid']?>'
				turno='<?php echo $this->turno?>'
				perid='<?php echo $this->perid?>'
		><span class='glyphicon  glyphicon-log-out'></span> Cerrar Acta</buttom>
		<?php }?>
	</div>
</div>
<?php if ($this->students) { ?>
<div class='row'>
	<div class='col-md-12'>
		<table class='table tb-notes'>
			<thead>
				<tr>
					<th>#</th>
	                <th>Cod Matricula</th>
	                <th>Apellidos y Nombres</th>
	                <?php if($this->partial == 2){?>
	                <th>Promedio 1</th>
	                <?php } ?>
	                <?php if($this->partial != 0){ ?>
	                <th>Nota 1</th>
	                <th>Nota 2</th>
	                <th>Nota 3</th>
	                <th>Nota 4</th>
	                <th>Nota 5</th>
	                <th>Nota 6</th>
	                <th>Nota 7</th>
	                <th>Nota 8</th>
	                <th>Nota 9</th>
	                <?php if($this->partial == 1){?>
	                <th class="promedio">Promedio 1</th>
	                <?php }else{ ?>
	                <th class="promedio">Promedio 2</th>
	                <th class="promedio">Nota Final</th>
	                <?php } ?>
	                <?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->students as $key => $register) { ?>
				<tr
					curid="<?php echo $register['curid'];?>" 
                    escid="<?php echo $register['escid'];?>" 
                    cursoid="<?php echo $register['cursoid'];?>" 
                    perid="<?php echo $register['perid'];?>" 
                    turno="<?php echo $register['turno'];?>" 
                    eid="<?php echo $register['eid'];?>"
                    oid="<?php echo $register['oid'];?>" 
                    sedid="<?php echo $register['sedid'];?>" 
                    matid="<?php echo $register['matid'];?>" 
                    uid="<?php echo $register['uid'];?>"
                    edition="false"
                    style="color:<?php echo ($register['promedio1'] != -3)?'#000':'#FC4141'; ?>;"
				>
				<td class='td-edit-note'>
                    <h6 class='pull-left'><?php echo $key + 1 ?></h6>
                    <span id="edit-note-<?php echo $key?>" class='pull-left text-primary glyphicon'></span>
                </td>
                <td><h6><?php echo $register['uid']?></h6></td>
				<td><h6><?php echo $register['last_name0']." ".$register['last_name1'].", ".$register['first_name']?></h6></td>
				<?php if($this->partial == 2){ ?>
                    <td>
                        <input class='form-control' style="color:<?php echo ($register['promedio1'] != -3)?'#000':'#FC4141'; ?>;" disabled class="uneditable-input"  type="text" name="promedio1"  value="<?php echo ($register['promedio1'] != -3)?$register['promedio1']:'RET'; ?>"/>
                    </td>
                    <?php } ?>
                 <?php if ($this->partial == 1) { ?>
                 	<td>
                 		<input  maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota1_i"  value="<?php echo  $register['nota1_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota2_i"  value="<?php echo  $register['nota2_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota3_i"  value="<?php echo  $register['nota3_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota4_i"  value="<?php echo  $register['nota4_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota5_i"  value="<?php echo  $register['nota5_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota6_i"  value="<?php echo  $register['nota6_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota7_i"  value="<?php echo  $register['nota7_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota8_i"  value="<?php echo  $register['nota8_i'] ;?>"/>
                 	</td>
                 	<td>
                 		<input maxlength="2" class='form-control' <?php echo ($register['promedio1'] != -3)?'':'disabled'; ?> editable=true index="<?php echo $key; ?>"   type="text" name="nota9_i"  value="<?php echo  $register['nota9_i'] ;?>"/>
                 	</td>
                 	<td class="promedio">
                        <input maxlength="2" class='form-control' style="color:<?php echo ($register['promedio1'] != -3)?'#000':'#FC4141'; ?>;" disabled class="uneditable-input"  type="text" name="promedio1"  value="<?php echo ($register['promedio1'] != -3)?$register['promedio1']:'RET'; ?>"/>
                    </td>
                 <?php }?>
				</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>
<?php }else{ ?>
<div class='col-md-12 cont-font-not-register'>
	<h1 class='span-not-register'>
		<span class='glyphicon glyphicon-exclamation-sign'></span>
	</h1>
	<h3 class='text-not-register'>No se encontro ningun Registro</h3>
</div>
	<?php }?>
