<div>
	<h4><center><b>DISTRIBUCIÓN ACADÉMICA PERIODO - <?php echo $this->perid?></b></center></h4>
</div>
<div style="margin-top:20px">
	<ul class="nav nav-pills nav-justified">
  		<li class="active">
  			<a id="courses" href="#datcourses"><b>Paso &nbsp &nbsp</b><span class="badge">1</span></a>
  		</li>
  		<li>
  			<a id="teachers" href="#datteachers"><b>Paso &nbsp &nbsp</b><span class="badge">2</span></a>
  		</li>
  		<li>
  			<a id="view" href="#datview"><b>Paso &nbsp &nbsp</b><span class="badge">3</span></a>
  		</li>
	</ul>
	<div class="tab-content">
	  	<div class="tab-pane active" id="datcourses"></div>
	  	<div class="tab-pane" id="datteachers"></div>
	  	<div class="tab-pane" id="datview"></div>
	</div>
</div>

<script type="text/javascript">
var perid="<?php echo $this->perid?>";
var escid="<?php echo $this->escid?>";
var subid="<?php echo $this->subid?>";
var distid="<?php echo $this->distid?>";

$("#datcourses").html("<img src='/img/spinner.gif'>Cargando...");
$("#datcourses").load("/distribution/distribution/courses/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);
</script>