<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Distribución Academica');?>
<?php $this->placeholder('Btnnav')->append('<a href="/distribution/distribution" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>


<div style="margin-top:20px">
    <ul class="nav nav-pills nav-justified" id="distribution">
        <li class="active">
            <a id="courses" href="#datcourses"><h4 class="text-info">Paso 1</h4><h5 style='color:#2C3138'>Lista de Asignaturas</h5></a>
        </li>
        <li>
            <a id="teachers" href="#datteachers"><h4 class="text-info">Paso 2</h4><h5 style='color:#2C3138'>Lista de Docentes</h5></a>
        </li>
        <li>
            <a id="view" href="#datview"><h4 class="text-info">Paso 3</h4><h5 style='color:#2C3138'>Imprimir Distribución</h5></a>
        </li>
    </ul>
	<div class="tab-content">
        <div id="datcourses" class="tab-pane fade in active"></div>
        <div id="datteachers" class="tab-pane fade"></div>
        <div id="datview" class="tab-pane fade">
            <br>
            <hr>
            <!-- <div class="row">
                <div class="col-md-9 col-md-offset-1">
                    <blockquote>
                        <h4>Imprimir <span class="text-info">Distribución</span></h4>
                    </blockquote>
                </div>
                <div class="col-md-1">
                    <blockquote>
                        <h4 class="text-info"><span class="glyphicon glyphicon-print"></span></h4>
                    </blockquote>
                </div>
            </div> -->
            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="jumbotron">
                        <div class="row">
                            <div class="col-md-8">
                                <h2 class="text-muted text-center"><span class="glyphicon glyphicon-eye-open"></span></h2>
                                <h3 class="text-center">Vista <span class="text-info">Preliminar</span></h3>
                            </div>
                            <div class="col-md-4">
                                <br>
                                <a class="btn btn-success" data-toggle="modal" data-target="#myModal">
                                    <span class="glyphicon glyphicon-eye-open" title="Vista Preliminar General Docente-Curso"></span> Visualizar
                                </a>
                                <!--<a onclick="javascript: window.open('/distribution/distribution/generalpreview/escid/<?php echo base64_encode($this->escid)?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>','Vista Preliminar General','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=900,height=720')" class="btn btn-success pull-right" style="float:right"><span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="Vista Preliminar General Docente-Curso"></span> Visualizar</a>-->
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="col-md-5">
                    <div class="jumbotron">
                        <div class="row">
                            <div class="col-md-8">
                                <h2 class="text-muted text-center"><span class="glyphicon glyphicon-print"></span></h2>
                                <h3 class="text-center">Imprimir <span class="text-info">Distribución</span></h3>
                            </div>
                            <div class="col-md-4">
                                <br>
                                <a href="/distribution/printdistribution/index/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>/perid/<?php echo base64_encode($this->perid);?>/distid/<?php echo base64_encode($this->distid);?>" class="btn btn-success" style="float:right"><span class="glyphicon glyphicon-print" data-toggle="tooltip" title="Imprimir Distribución"></span> Imprimir</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Button trigger modal -->
            

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div  style="width: 900px;" class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Vista <span class="text-info">Preliminar</span></h4>
                  </div>
                  <div id="previewPrint" class="modal-body">
                    ...
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
        </div>
    </div>
</div>

<script type="text/javascript">
var perid="<?php echo $this->perid?>";
var escid="<?php echo $this->escid?>";
var subid="<?php echo $this->subid?>";
var distid="<?php echo $this->distid?>";

$("#datcourses").html("<img src='/img/spinner.gif'>Cargando...");
$("#datcourses").load("/distribution/distribution/courses/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);

$("#datteachers").html("<img src='/img/spinner.gif'>Cargando...");
$("#datteachers").load("/distribution/distribution/teachers/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);

$("#previewPrint").load("/distribution/distribution/generalpreview/escid/<?php echo base64_encode($this->escid)?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>");

$('#distribution a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
$('a[rel=tooltip]').tooltip();
</script>