<link rel="stylesheet" href="/css/distributionAcademic.css">

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Distribución Academica');?>
<?php $this->placeholder('Btnnav')->append('<a href="/distribution/distribution" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<div class="distAcademic_nav">
    <a href="##" class="distAcademic_btnObO btnStepOne btnObOActive" goto="idDataStepOne">Paso 1 <br> <small>Lista de Asignaturas</small></a>
    <a href="##" class="distAcademic_btnObO btnStepTwo" goto="idDataStepTwo">Paso 2 <br> <small>Lista de Docentes</small></a>
    <a href="##" class="distAcademic_btnObO btnStepThree" goto="idDataStepThree">Paso 3 <br> <small>Vista Previa</small></a>
</div>
<div class="distAcademic_dataNav">
    <div id="idDataStepOne" class="dataStepObO dataStepOne"></div>
    <div id="idDataStepTwo" class="dataStepObO dataStepTwo" hidden></div>
    <div id="idDataStepThree" class="dataStepObO dataStepThree" hidden>
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-md-8">
                            <h2 class="text-muted text-center"><span class="glyphicon glyphicon-eye-open"></span></h2>
                            <h3 class="text-center">Vista <span class="text-info">Preliminar</span></h3>
                        </div>
                        <div class="col-md-4">
                            <br>
                            <a class="btn btn-success" data-toggle="modal" data-target="#myModalpreview">
                                <span class="glyphicon glyphicon-eye-open" title="Vista Preliminar General Docente-Curso"></span> Visualizar
                            </a>
                            <!--<a onclick="javascript: window.open('/distribution/distribution/generalpreview/escid/<?php echo base64_encode($this->escid)?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>','Vista Preliminar General','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=900,height=720')" class="btn btn-success pull-right" style="float:right"><span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="Vista Preliminar General Docente-Curso"></span> Visualizar</a>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-md-8">
                            <h2 class="text-muted text-center"><span class="glyphicon glyphicon-print"></span></h2>
                            <h3 class="text-center">Imprimir <span class="text-info">Distribución</span></h3>
                        </div>
                        <div class="col-md-4">
                            <br>
                            <a href="/distribution/printdistribution/index/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>/perid/<?php echo base64_encode($this->perid);?>/distid/<?php echo base64_encode($this->distid);?>" class="btn btn-success" style="float:right"><span class="glyphicon glyphicon-print" data-toggle="tooltip" title="Imprimir Distribución"></span> Imprimir</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModalpreview" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div  style="width: 900px;" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Vista <span class="text-info">Preliminar</span></h4>
            </div>
            <div id="previewPrint" class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(function(){
        var perid  = "<?php echo $this->perid?>";
        var escid  = "<?php echo $this->escid?>";
        var subid  = "<?php echo $this->subid?>";
        var distid = "<?php echo $this->distid?>";

        $("#idDataStepOne").html("<br><center><img src='/img/spinner.gif'></center>");
        $("#idDataStepOne").load("/distribution/distribution/courses/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);

        $("#idDataStepTwo").html("<br><center><img src='/img/spinner.gif'></center>");
        $("#idDataStepTwo").load("/distribution/distribution/teachers/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);

        $("#previewPrint").load("/distribution/distribution/generalpreview/escid/<?php echo base64_encode($this->escid)?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($this->subid)?>");

        $('#distribution a').click(function (e) {
          e.preventDefault()
          $(this).tab('show')
        })
        $('a[rel=tooltip]').tooltip();

        var goTo = '';

        $('.distAcademic_btnObO').on('click', function(){
            goTo = $(this).attr('goto');
            $('.distAcademic_btnObO').removeClass('btnObOActive');
            $(this).addClass('btnObOActive');

            $('.dataStepObO').fadeOut('fast');
            $('#' + goTo).fadeIn('fast');
        });
    });
</script>