<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<script src="/external/jquery/jquery-1.9.1.js"></script>
<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
<script src="/external/jquery/external/globalize.js"></script>
<script src="/external/jquery/external/jquery.mousewheel.js"></script>
<script src="/external/jquery/external/jshint.js"></script>
<script src="/external/jquery/external/qunit.js"></script>
<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
<script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
<link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/css/style.css">
<style type="text/css">
.cuadro{    
    background-color: #fff;
    border-radius: 5px;
    border: 1px solid silver;
    padding-top: 10px;
    padding-bottom: 15px;
    width: 96%;
    margin-left: 2%;
}
th, td{
    font-size:12px;
}
</style>
<body class="found">
<table class="table" style="background: #428bca; color: white">
    <tr>
        <td>
            <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-list-alt"></span> Vista Preliminar</a>
        </td>
        <td>
        	<h4><b><center><?php echo $this->person['last_name0']." ".$this->person['last_name1'].", ".$this->person['first_name'] ?></center></b></h4>
        </td>
        <td>
            <a style="float:right" class='btn btn-danger' onclick="javascript: window.close();"><span class="glyphicon glyphicon-eject"></span> Cerrar</a>
        </td>
    </tr>
</table>

<div id="academica" class="cuadro">
    <div>
        <h5 style="color: silver"><center><b>ACADEMICA</b></center></h5>
    </div>
    <center>
    <table class="table table-condensed table-hover" style="margin-top:10px; width:96%">
        <tr>
            <th><center>Currícula</center></th>
            <th><center>Asignaturas</center></th>
            <th><center>Comprom.</center></th>
            <?php    
            $uid=$this->uid;
            $riddoc=substr($uid,8,2); 
            if($riddoc=='DC'){ ?>
            	<th><center>Principal</center></th>
            <?php 
            } ?>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
        </tr>
        <tr>
            <td>
                <select id="curid" class="form-control" style="width:110px">
                    <option value="">Currícula</option>
                    <?php
                    foreach ($this->curriculas  as $curricula){ ?>
                        <option value="<?php echo $curricula['curid']?>"><?php echo $curricula['curid']?></option>
                        <?php
                    }?>
                </select>
            </td>
            <td>
                <select id="courseid" class="form-control">
                    <option value="">Seleccione Asignatura</option>
                </select>
            </td>
            <td>
                <center>
                    <input type="checkbox" id="compromiso" value="N" title="Compromiso">
                </center>
            </td>
            <?php    
            $uid=$this->uid;
            $riddoc=substr($uid,8,2); 
            if($riddoc=='DC'){ ?>
                <td>
                    <center>
                        <input type="checkbox" id="princ" value="N" title="Principal">
                    </center>
                </td>
            <?php  
            } ?>
            <td>
                <center>
                    <select id="grupos" class="form-control" style="width:60px">
                        <?php
                        for($i=1; $i<=20; $i++){ ?>            
                            <option value="<?php echo $i?>"><?php echo $i?></option>
                        <?php }?>
                    </select>
                </center>
            </td>
            <td>
                <center>
                    <select id="hteoria" class="form-control" style="width:80px">
                        <option value="">Teoría</option>
                        <?php    
                        $uid=$this->uid;
                        $riddoc=substr($uid,8,2); 
                        if($riddoc=='DC'){
                            for($i=0;$i<=20;$i++){ ?>
                                <option value="<?php echo $i?>"><?php echo $i?></option>
                            <?php 
                            }
                        }else{
                            $i=0; ?>
                            <option value="<?php echo $i?>" selected><?php echo $i?></option>
                            <?php
                        }?>
                    </select>
                </center>
            </td>
            <td>
                <center>
                    <select id="hpractica" class="form-control" style="width:80px">
                        <option value="">Práctica</option>
                        <?php           
                        $i=0;
                        for($i=0; $i<=20; $i++){ ?>            
                            <option value="<?php echo $i?>"><?php echo $i?></option>
                        <?php }?>
                    </select>
                </center>
            </td>
            <td>
                <center>
                    <input type="text" id="totalhoras" class="form-control" style="width:60px" disabled>
                </center>
            </td>
        </tr>
        <tr>
            <td colspan="8">
                <center>
                    <a href="#" class="btn btn-info" id="agregarcurso"><span class="glyphicon glyphicon-floppy-disk"></span> Agregar</a>
                </center>
            </td>
        </tr>
    </table>
    <br>    
    <?php
    $i=1;
    if ($this->cursosasignados){  ?>
    <table id="vercursosasig" style="width:96%; margin:0px" class="table table-bordered table-condensed table-striped">
        <tr>
            <th>#</th>
            <th>Código</th>
            <th>Nombre Asignatura</th>
            <th><center>Turno</center></th>
            <th><center>Sem</center></th>
            <th><center>Compromiso</center></th>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
            <th><center>Eliminar</center></th>       
        </tr>
        <?php              
            foreach ($this->cursosasignados as $cursos){ ?>
                <tr>
                    <td><?php echo $i?></td>            
                    <td><?php echo $cursos['courseid']?></td>
                    <td><?php echo $cursos['name']?></td>
                    <td><center><?php echo $cursos['turno']?></center></td>
                    <td><center><?php echo $cursos['semid']?></center></td>
                    <td>
                        <center>
                            <?php 
                            if($cursos['is_com']=='S') echo "SI";
                            elseif($cursos['is_com']=='N') echo "NO"; ?>
                        </center>
                    </td>
                    <?php 
                        $temporalh=$temporalh+$cursos['hours_total'];
                    ?>
                    <td><center><?php echo $cursos['groups']?></center></td>
                    <td><center><?php echo $cursos['hours_t']?></center></td>
                    <td><center><?php echo $cursos['hours_p']?></center></td>
                    <td><center><?php echo $cursos['hours_total']?></center></td>
                    <td>
                        <center><a href="/distribucion/distribucion/eliminarcursoasignado/perid/<?php echo $this->perid?>/sedid/<?php echo $this->sedid?>/escid/<?php echo $cursos['escid'];?>/cursoid/<?php echo $cursos['cursoid'];?>/turno/<?php echo $cursos['turno']?>/curid/<?php echo $cursos['curid']?>/pid/<?php echo $this->pid;?>/uid/<?php echo $this->uid;?>/distid/<?php echo $this->distid?>/escidorigen/<?php echo $this->escidorigen?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>" rel="tooltip" title="Eliminar Asignatura"><span class="glyphicon glyphicon-trash"></span></a></center>
                    </td>
                </tr>
            <?php
            $i++;
            }?>
            <tr>
                <td colspan='9'>Total Horas Académicas</td>
                <td><center><?php echo $temporalh;?></center></td>
                <td></td>
            </tr>
    </table>
    <?php }
    ?>
    <div id="guardarcursosasig"></div>
</div>
<br>
<div id="administrativo" class="cuadro">
    <div>
        <h5 style="color: silver"><center><b>ADMINISTRATIVA</b></center></h5>
    </div>
    <center>
        <form name="<?php echo $this->form->getName();?>" id="hsadmin" action="/distribution/distribution/savedistributionadmin/uid/<?php echo $this->uid?>/pid/<?php echo $this->pid?>/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid?>/esciddoc/<?php echo $this->esciddoc?>/subiddoc/<?php echo $this->subiddoc?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
            <table style="width:90%" class="table table-condensed table-striped">
                <tr>
                    <th>Labor Administrativa</th>
                    <th colspan="2"># Horas</th>
                </tr>
                <tr>
                    <td><?php echo $this->form->work;?></td> 
                    <td style="width:100px"><?php echo $this->form->hours;?></td> 
                    <td><?php echo $this->form->enviar;?></td>      
                </tr>
            </table>
        </form> 
        <?php
        $i=1;
        if ($this->administrativas){ ?>
        <table id="labores" style="width:90%; margin:0px" class="table table-bordered table-condensed table-striped">
            <tr>
                <th><center>#</center></th>
                <th>Labor Administrativa</th>
                <th><center># Horas</center></th>
                <th><center>Eliminar</center></th>        
            </tr>
                <?php
                foreach ($this->administrativas as $admin){ 
                        $y=$admin['hours'];
                        $temporalad=$temporalad+$y;
                        $temporal=$temporal+$y;
                        $tt=$temporal; ?>
                    <tr>
                        <td><center><?php echo $i?></center></td>
                        <td><?php echo $admin['work']?></td>
                        <td><center><?php echo $admin['hours']?></center></td>
                        <td><center><a  href="/distribution/distribution/eliminarlaboradmin/labor/<?php echo $admin['labor']?>/uid/<?php echo $this->uid;?>/pid/<?php echo $this->pid;?>/escid/<?php echo $this->escid;?>/sedid/<?php echo $this->sedid;?>/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid;?>/escidorigen/<?php echo $this->escidorigen?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>" rel="tooltip" title="Eliminar Labor Administrativa"><span class="glyphicon glyphicon-trash"></span></a></td>
                    
                    </tr>
            <?php
            $i++;   
            } ?>
            <tr>
                <td colspan='2' >Total Horas Administrativas</td>
                <td><center><?php echo $temporalad?></center></td>
                <td></td>
            </tr>
        </table>
        <?php 
        } ?>  
    <div id="ghorasadmin"></div>
    </center>     
</div>
<br>
<center style="padding-left:70%" class="col-lg-4">
    <div class="cuadro col-lg-4">
        <table class="table table-hover table-bordered table-condensed" style="margin:0px">
            <?php
            // $distdoc = new Distribucion_Model_DbTable_Distribuciondocente();
            // $ldistdoc = $distdoc ->_getDistribucionXDocenteXPeriodo($perid,$eid,$oid,$uid);
            $infothacad = $ldistdoc['t_h_acad'];
            $infothadmin = $ldistdoc['t_h_adm'];
            // $infothoras = $ldistdoc['nombre_curso'];
            $thoras=$infothacad+$infothadmin;
            if($infothacad>=30){ ?>   
                <script> 
                    alert('Sus horas teoricas exceden a 30\n Revise sus horas');
                </script> 
            <?php
            }
            if($thoras>40) { ?>   
                <script> 
                    alert('Sus horas totales exceden a 40\n Revise sus horas');
                </script> 
            <?php
            } ?>
            <tr>
                <th>T.H. Academicas:</th>
                <td><center><?php echo $infothacad?></center></td>
            </tr>
            <tr>
                <th>T.H. Administrativas:</th>       
                <td><center><?php echo $infothadmin?></center></td>
            </tr>
            <tr>
                <th>Total Horas:</th>       
                <td><center><?php echo $infothacad+$infothadmin?></center></td>
            </tr>
            <tr>
                <td colspan='2' ><a style="float:right" href="/distribucion/distribucion/asignacioncursos/uid/<?php echo $this->uid?>/pid/<?php echo $this->pid?>/escid/<?php echo $this->escid?>/sedid/<?php echo $this->sedid?>/perid/<?php echo $this->perid?>/distid/<?php echo $this->distid?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>/escidorigen/<?php echo $this->escidorigen?>" class="btn btn-danger"><span class="glyphicon glyphicon-refresh"></span> Actualizar</a></td>
            </tr>
        </table>
    </div>
</center>
</body>
<script>
 	$("#curid").change(function(){
        var curid = $(this).val();  
        var escid = "<?php echo $this->escid?>";   
        var perid = "<?php echo $this->perid?>";   
        var url = "/distribution/distribution/coursesxcurricula/curid/"+curid+"/escid/"+escid+"/perid/"+perid;
        // alert(url);
        $("#courseid").load(url);
    }); 

    $("#grupos, #hpractica, #hteoria").change(function(){
        var grupos= eval($("#grupos").val());
        var ht= eval($("#hteoria").val());
        var hp= eval($("#hpractica").val());
        var tt=grupos*hp+ht;
        $("#totalhoras").attr("value",tt);
    });

    $("#princ").click(function(){  
        var value =  $(this).attr('value');
        if (value == "N") $("#princ").attr("value","S");
        else $("#princ").attr("value","N");
    });

    $("#compromiso").click(function(){  
        var g = $(this).attr('value');
        if (g == "N") $("#compromiso").attr("value","S");
        else $("#compromiso").attr("value","N");
    }); 

    $("#agregarcurso").click(function(){
        $("#vercursosasig").hide();
        var uid="<?php echo $this->uid?>";
        var pid="<?php echo $this->pid?>";
        var perid="<?php echo $this->perid?>";
        var esciddoc="<?php echo $this->esciddoc?>";
        var subiddoc="<?php echo $this->subiddoc?>";
        var distid="<?php echo $this->distid?>";
        var curid=$("#curid").val();
        var curso=$("#courseid").val();
        var grupos=$("#grupos").val();
        var hteoria=$("#hteoria").val();
        var hpractica=$("#hpractica").val();
        var totalhoras=$("#totalhoras").val();
        var compromiso=$("#compromiso").val();
        var princ=$("#princ").val();
        // var temp="<?php echo $this->temp?>";
        // var temp2="<?php echo $this->temp2?>";
        // var principal="<?php echo $this->principal?>";        
        
        if (curso=='' || hteoria=='' || hpractica=='') {
            alert("Seleccione un Curso, Horas Teóricas y Horas Prácticas.");
            return false;
        };

        if(compromiso=='S') totalhoras=0;
        if(hteoria>0) {
            estado='A';
            principal='S';
        };
        
        if(hteoria==0){
            if(hpractica==0 && grupos==0){
                estado='L';
                principal='N';
            }else{
                estado='P';
                principal='N';
            };
           
        };

        if (princ=="S") {
            estado="A";
            principal=princ;
        };

        var tmp=curso.split(";--;");
        var courseid=tmp[0];
        var semid=tmp[1];
        var turno=tmp[2];
        
        var url="/distribution/distribution/saveasigncourse/curid/"+curid+"/courseid/"+courseid+"/turno/"+turno+"/semid/"+semid+"/grupos/"+grupos+"/hteoria/"+hteoria+"/hpractica/"+hpractica+"/totalhoras/"+totalhoras+"/compromiso/"+compromiso+"/uid/"+uid+"/pid/"+pid+"/distid/"+distid+"/perid/"+perid+"/principal/"+principal+"/estado/"+estado+"/esciddoc/"+esciddoc+"/subiddoc/"+subiddoc;
        // alert(url);
        $("#guardarcursosasig").load(url);
    });

    $("#hsadmin").submit(function(){
        $("#labores").hide();        
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function(data) {                        
                $('#ghorasadmin').html(data);                                 
            }
        }); 
        return false;
    });
    $('a[rel=tooltip]').tooltip();
</script>

<?php 
 $temp=$this->temp;
 $temp2=$this->temp2;
 if($temp==1 and $temp2==0)
 {
    ?>
    <script>
        $("#administrativo").hide();
        $("#labores").hide();
    </script>
    <?php
 }
?>
