<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<script src="/external/jquery/jquery-1.9.1.js"></script>
<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
<script src="/external/jquery/external/globalize.js"></script>
<script src="/external/jquery/external/jquery.mousewheel.js"></script>
<script src="/external/jquery/external/jshint.js"></script>
<script src="/external/jquery/external/qunit.js"></script>
<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
<script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
<style type="text/css">
.cuadro{    
    background-color: #fff;
    border-radius: 5px;
    border: 1px solid silver;
    padding-top: 10px;
    padding-bottom: 15px;
    width: 96%;
    margin-left: 2%;
}
</style>
<?php
$pid=$this->pid;
$uid=$this->uid;
$eid=$this->eid;
$oid=$this->oid;
$perid=$this->perid;
?>

<table class="table">
    <tr>
        <td>
            <a href="/distribucion/distribucion/asignacion/perid/<?php echo $this->perid?>/distid/<?php  echo $this->distid?>/escid/<?php echo $this->escid?>/sedid/<?php echo $this->sedid?>"  class="btn btn-danger" style="float:left"><span class="glyphicon glyphicon-list-alt"></span> Vista Preliminar</a>
        </td>
        <td>
        	<h4><b><center><?php echo $this->person['last_name0']." ".$this->person['last_name1'].", ".$this->person['first_name'] ?></center></b></h4>
        </td>
        <td>
            <a style="float:right" class='btn btn-danger' onclick="javascript: window.close();"><span class="glyphicon glyphicon-eject"></span> Cerrar</a>
        </td>
    </tr>
</table>

<div id="academica" class="cuadro">
    <div style="margin:0px 20px 0px 20px">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#" data-toggle="tab"><b>ACADEMICA</b></a>
            </li>
        </ul>
    </div>

    <center>
    <table class="table table-condensed table-striped" style="margin:0px; width:94%">
        <tr>
            <th style="font-size:12px"><center>Currícula</center></th>
            <th style="font-size:12px"><center>Asignaturas</center></th>
            <th style="font-size:12px"><center>Comprom.</center></th>
            
            <?php    
            $uid=$this->uid;
            $riddoc=substr($uid,8,2); 
            if($riddoc=='DC'){ ?>
            	<th style="font-size:12px"><center>Principal</center></th>
            <?php 
            } ?>
            <th style="font-size:12px"><center>Grupos</center></th>
            <th style="font-size:12px"><center>#H.T.</center></th>
            <th style="font-size:12px"><center>#H.P.</center></th>
            <th style="font-size:12px"><center>#T.T.</center></th>
        </tr>
        <tr>
            <td>
                <select id="curid" class="form-control">
                    <option value="">Currícula</option>
                    <?php
                    foreach ($this->curriculas  as $curricula){ ?>
                        <option value="<?php echo $curricula['curid']?>"><?php echo $curricula['curid']?></option>
                        <?php
                    }?>
                </select>
            </td>
            <td>
                <select id="courseid" class="form-control">
                    <option value="">Seleccione Asignaturas</option>
                </select>
            </td>
            <td>
                <center><input type="checkbox" id="compromiso" name="compromiso" value="N"></center>
            </td>
            
             <?php    
                    $uid=$this->uid;
                    $riddoc=substr($uid,8,2); 
                    // echo $riddoc;
                    if($riddoc=='DC')
                    {
                    ?>
            <td>
                <center><input type="checkbox" id="princ" name="princ" value="N" title="principal"></center>
            </td>
            <?php  } 
            ?>


            <td><center>
                <select id="grupos" name="grupos" class="form-control">
                    <?php
                    for($i = 1;$i<=20;$i++){ ?>            
                        <option value="<?php echo $i?>"><?php echo $i?></option>
                    <?php }?>
                </select></center>
            </td>
            <td><center>
                <select id="hteoria" name="hteoria" class="form-control">
                    <option value="">Teoricas</option>
                    <?php    
                    $uid=$this->uid;
                    $riddoc=substr($uid,8,2); 
                    // echo $riddoc;
                    if($riddoc=='DC'){
                        $i=0;
                        for($i=0;$i<=20;$i++){ ?>
                            <option value="<?php echo $i?>"><?php echo $i?></option>
                        <?php 
                        }
                    }else{
                        $i=0; ?>
                        <option value="<?php echo $i?>"><?php echo $i?></option>
                        <?php
                    }?>
                </select></center>
            </td>
            <td><center>
                <select id="hpractica" name="hpractica" class="form-control">
                    <option value="">Prácticas</option>
                    <?php           
                    $i=0;
                    for($i = 0;$i<=20;$i++){ ?>            
                        <option value="<?php echo $i?>"><?php echo $i?></option>
                    <?php }?>
                </select></center>
            </td>
            <script>
             $("#hpractica").change(function(){
                var grupos= eval($("#grupos").val());
                var ht= eval($("#hteoria").val());
                var hp= eval($("#hpractica").val());
                // alert(ht);
                // alert(hp);
                var tt=grupos*hp+ht;
                //alert(tt);
                //$("#turno1_"+g).attr("value","B");
                $("#totalhoras").attr("value",tt);

             });
            </script>

            <script>
             $("#hteoria").change(function(){
                var grupos= eval($("#grupos").val());
                var ht= eval($("#hteoria").val());
                var hp= eval($("#hpractica").val());
                // alert(ht);
                // alert(hp);
                var tt=grupos*hp+ht;
                //alert(tt);
                //$("#turno1_"+g).attr("value","B");
                $("#totalhoras").attr("value",tt);
             });
            </script>
            <script>
             $("#grupos").change(function(){
                var grupos= eval($("#grupos").val());
                var ht= eval($("#hteoria").val());
                var hp= eval($("#hpractica").val());
                // alert(ht);
                // alert(hp);
                var tt=grupos*hp+ht;
                //alert(tt);
                //$("#turno1_"+g).attr("value","B");
                $("#totalhoras").attr("value",tt);
             });
            </script>

            <td><center>
                <input type="text" id="totalhoras" disabled class="form-control" value=" " name="firstname"/></center>
            </td>
            </tr><tr>
            <td colspan="8">
                <center><a href="#" class="btn btn-info" id="agregar">Agregar</a></center>
            </td>
        </tr>
    </table><center>
    <br>    
    <?php
    $i=1;
    if ($this->cursosasignados){  ?>
    <center>
    <table id="vercursosasig" style="width:96%; margin:0px" class="table table-bordered table-condensed table-striped">
        <tr>
            <th>#</th>
            <th>Codigo</th>
            <th>Curso</th>
            <th><center>Sem</center></th>
            <th><center>Compromiso</center></th>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
            <th><center>Eliminar</center></th>       
        </tr>
        <?php              
            foreach ($this->cursosasignados as $cursos){ 
                     $cursoid=$cursos['cursoid'];
                     $curid=$cursos['curid'];
                     $escid=$cursos['escid'];
                     $cursill = new Admin_Model_DbTable_Cursos();
                     $list_curso = $cursill ->_getnombreXcurso($escid,$cursoid,$curid);
                     $infocurso = $list_curso['nombre_curso']; ?>
                <tr>
                    <td style="font-size:14px"><?php echo $i?></td>            
                    <td style="font-size:14px"><?php echo $cursos['cursoid']?></td>
                    <td style="font-size:14px"><?php echo $infocurso?></td>
                    <td style="font-size:14px"><center><?php echo $cursos['semid']?></center></td>
                    <td style="font-size:14px">
                    <center>
                        <?php 
                        if($cursos['compromiso']=='S') echo "SI";
                        if($cursos['compromiso']=='N') echo "NO"; ?>
                    </center>
                    </td>
                    <?php 
                        if($cursos['compromiso']=='S')
                        {
                            $cursos['total_horas']=0;
                        }
                        $yy=$cursos['total_horas'];
                        $temporalh=$temporalh+$yy;
                    ?>
                    <td  style="font-size:14px"><center><?php echo $cursos['grupos']?></center></td>
                    <td  style="font-size:14px"><center><?php echo $cursos['horas_teoria']?></center></td>
                    <td  style="font-size:14px"><center><?php echo $cursos['horas_practica']?></center></td>
                    <td  style="font-size:14px"><center><?php echo $cursos['total_horas']?></center></td>
                    <td  style="font-size:14px"><center><a  href="/distribucion/distribucion/eliminarcursoasignado/perid/<?php echo $this->perid?>/sedid/<?php echo $this->sedid?>/escid/<?php echo $cursos['escid'];?>/cursoid/<?php echo $cursos['cursoid'];?>/turno/<?php echo $cursos['turno']?>/curid/<?php echo $cursos['curid']?>/pid/<?php echo $this->pid;?>/uid/<?php echo $this->uid;?>/distid/<?php echo $this->distid?>/escidorigen/<?php echo $this->escidorigen?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>" ><img src="/img/delete.ico"></a></center></td>
                </tr>
            <?php
            $i++;   
            }?>
                <tr>
                    <td colspan='8' >Total Horas Teóricas</td>
                    <td style="font-size:14px"><center><?php echo $temporalh;?></center></td>
                    <td></td>
                </tr>
    </table>
    </center> 
    <?php }
    ?>
    <div id="gcursos">
        <div id="guardarcursosasig"></div>
    </div>
</div>

<br>

<div id="administrativo" class="cuadro">
    <div style="margin:0px 20px 0px 20px">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#" data-toggle="tab"><b>ADMINISTRATIVA</b></a>
            </li>
        </ul>
    </div>
        <form name="<?php echo $this->fm->getName(); ?>" id="hsadmin" action="/distribucion/distribucion/guardarhorasadmin/uid/<?php echo $this->uid?>/pid/<?php echo $this->pid?>/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid?>/escid/<?php echo $this->escid?>/sedid/<?php echo $this->sedid?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
        <center>
            <table style="width:90%" class="table table-condensed table-striped">
                <tr>
                     <td>Labor Administrativa</td>
                     <td># Horas</td>
                     <td></td>
                </tr>
                <tr>
                    <td><?php echo $this->fm->labor;?></td> 
                    <td><?php echo $this->fm->horas;?></td> 
                    <td><?php echo $this->fm->enviar;?></td>      
                </tr>
            </table>
        <center>
        </form> 
        <?php
        $i=1;
        if ($this->administrativas){ ?>
        <center>
        <table id="labores" style="width:90%; margin:0px" class="table table-bordered table-condensed table-striped">
            <tr>
                <th><center>#</center></th>
                <th>Labor Administrativa</th>
                <th><center>#Horas</center></th>
                <th><center>Eliminar</center></th>        
            </tr>
                <?php
                foreach ($this->administrativas as $admin){ 
                        $y=$admin['horas'];
                        $temporalad=$temporalad+$y;
                        $temporal=$temporal+$y;
                        $tt=$temporal; ?>
                    <tr>
                        <td style="font-size:14px"><center><?php echo $i?></center></td>
                        <td style="font-size:14px"><?php echo $admin['labor']?></td>
                        <td style="font-size:14px"><center><?php echo $admin['horas']?></center></td>
                        <td style="font-size:14px"><center><a  href="/distribucion/distribucion/eliminarlaboradmin/labor/<?php echo $admin['labor']?>/uid/<?php echo $this->uid;?>/pid/<?php echo $this->pid;?>/escid/<?php echo $this->escid;?>/sedid/<?php echo $this->sedid;?>/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid;?>/escidorigen/<?php echo $this->escidorigen?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>"><img src="/img/delete.ico"></center></a></td>
                    
                    </tr>
            <?php
            $i++;   }
            ?>
            <tr>
                <td colspan='2' >Total Horas Administrativas</td>
                <td style="font-size:14px"><center><?php echo $temporalad?></center></td>
                <td></td>
            </tr>
        </table>
        </center>
        <?php }
        ?>       
    <div id="gadmin">
        <div id="ghorasadmin"></div>
    </div>
</div>
<br>
    <center style="padding-left:70%">
         <table border="1" width="65%">
               <?php
                    $distdoc = new Distribucion_Model_DbTable_Distribuciondocente();
                    $ldistdoc = $distdoc ->_getDistribucionXDocenteXPeriodo($perid,$eid,$oid,$uid);
                    $infothacad = $ldistdoc['t_h_acad'];
                    $infothadmin = $ldistdoc['t_h_adm'];
                    // $infothoras = $ldistdoc['nombre_curso'];
                    $thoras=$infothacad+$infothadmin;
                    if($infothacad>=30){ ?>   
                        <script> 
                            alert('Sus horas teoricas exceden a 30\n Revise sus horas');
                        </script> 
                        <?php
                    }
                    if($thoras>40) { ?>   
                        <script> 
                            alert('Sus horas totales exceden a 40\n Revise sus horas');
                        </script> 
                        <?php
                    } ?>
            <tr>
                <td>T.H. Academicas:</td>
                <td><center><?php echo $infothacad?></center></td>
                <!-- <td><center><?php //echo $temporalh?></center></td> -->
            </tr>
            <tr>
                <td >T.H. Administrativas:</td>       
                <td ><center><?php echo $infothadmin?></center></td>
            </tr>
            <tr>
                <td >Total Horas:</td>       
                <td ><center><?php echo $infothacad+$infothadmin?></center></td>
            </tr>
            <tr>
                <td colspan='2' ><a style="float:right width='20%'" href="/distribucion/distribucion/asignacioncursos/uid/<?php echo $this->uid?>/pid/<?php echo $this->pid?>/escid/<?php echo $this->escid?>/sedid/<?php echo $this->sedid?>/perid/<?php echo $this->perid?>/distid/<?php echo $this->distid?>/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>/escidorigen/<?php echo $this->escidorigen?>"  class="btn btn-danger" style="float:left">Actualizar</a></td>
            </tr>
        </table>
</center>
<script type="text/javascript">
 	$("#curid").change(function(){
        var curid = $(this).val();  
        var escid= "<?php echo $this->escid;?>";   
        var perid= "<?php echo $this->perid;?>";   
        var url="/distribution/distribution/coursesxcurricula/curid/"+curid+"/escid/"+escid+"/perid/"+perid;
        alert(url);
        // $("#courseid").load(url);
    }); 
</script>

<script>
$("#agregar").click(function(){
        $("#vercursosasig").hide();
        var curid=$("#curid").val();
        var grupos=$("#grupos").val();
        var hteoria=$("#hteoria").val();
        var hpractica=$("#hpractica").val();
        var totalhoras=$("#totalhoras").val();
        //var compromiso=$(this).attr('checked');
        var compromiso=$("#compromiso").val();
        var cursoid=$("#cursoid").val();
        var uid="<?php echo $this->uid?>";
        var pid="<?php echo $this->pid?>";
        var temp="<?php echo $this->temp?>";
        var temp2="<?php echo $this->temp2?>";
        var escidorigen="<?php echo $this->escidorigen?>";
        var sedid="<?php echo $this->sedid?>";
        
        var principal="<?php echo $this->principal?>";
        var princ=$("#princ").val();

        // alert(princ);
        // alert(compromiso);

        if (cursoid=='' || hteoria=='' || hpractica=='') {
            alert("Seleccione un Curso, Horas Teóricas y Horas Prácticas por favor.");
            return false;
        };

        if(hteoria>0)
        {
            estado='A'
        }

        if(compromiso=='S')
        {
            totalhoras=0;
        }
        
        if(hteoria==0 )
        {
            if(hpractica==0 && grupos==0)
            {
                estado='L';
                principal='N';
            }
            else
            {
                estado='P';
                principal='N';
            }
           
        }

        if (princ=="S") {
            estado="A";
            principal=princ;
        };
        //  alert(estado);
          

        tmp=cursoid.split(";--;");
        curso=tmp[0];
        semid=tmp[1];
        turno=tmp[2];
   
        url="/distribucion/distribucion/guardarasigcurso/curid/"+curid+"/cursoid/"+curso+"/turno/"+turno+"/semid/"+semid+"/grupos/"+grupos+"/hteoria/"+hteoria+"/hpractica/"+hpractica+"/totalhoras/"+totalhoras+"/compromiso/"+compromiso+"/uid/"+uid+"/pid/"+pid+"/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid?>/principal/"+principal+"/estado/"+estado+"/temp/<?php echo $this->temp?>/temp2/<?php echo $this->temp2?>/escidorigen/<?php echo $this->escidorigen?>/sedid/<?php echo $this->sedid?>";
        //alert(url);
        $("#guardarcursosasig").load(url);

    });
</script>

<script>
 $("#compromiso ").click(function(){  
        var g = $(this).attr('value');
        //alert(g);
        var check =  $(this).attr('checked');
        //var cursoid=  $("<?php echo $curso['cursoid']?>").val();
        //alert(cursoid);
        if (check == "checked")
        {
            $("#compromiso").attr("value","S");
            // $("#compromiso").attr("readonly","TRUE");
        }
        else
        {
            $("#compromiso").attr("value","N");
        }
}); 
</script>

<script>
 $("#princ").click(function(){  
        var check =  $(this).attr('checked');
        if (check == "checked") $("#princ").attr("value","S");
        else $("#princ").attr("value","N");
}); 
</script>
         
<script>
    $("#hsadmin").submit(function(){
        $("#labores").hide();        
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        //data: cadena, 

        success: function(data) {                        
            $('#ghorasadmin').html(data);                                 
            }
        }); 
        return false;
    });
</script>

<?php 
 $temp=$this->temp;
 $temp2=$this->temp2;
 if($temp==1 and $temp2==0)
 {
    ?>
    <script>
        $("#administrativo").hide();
        $("#labores").hide();
    </script>
    <?php
 }
?>
