<br>
<hr>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<blockquote>
			<h4>Lista de <span class="text-info">Asignaturas</span></h4>
		</blockquote>
	</div>
	<div class="col-md-1">
		<blockquote>
			<h4 class="text-info"><span class="glyphicon glyphicon-book"></span></h4>
		</blockquote>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<center><a id="addcourses" href="#addcourse" data-toggle="modal" class="btn btn-info"><span class="glyphicon glyphicon-book"></span> Agregar Asignatura</a></center>
	</div>
</div>
<br>
<!--<div class="panel panel-default" style="margin-top:15px">
  	<div class="panel-body">
    	<b style="font-size:20px"><span class="glyphicon glyphicon-tasks"></span> - LISTA DE ASIGNATURAS</b>
    	<a id="addcourses" href="#addcourse" data-toggle="modal" class="btn btn-info" style="float:right"><span class="glyphicon glyphicon-pencil"></span> <b>Agregar Asignatura</b></a>
  	</div>
</div>-->
<?php if ($this->courses) { ?>
	<div id="coursesss">
		<table id='courses_distribution_list' class="table table-hover table-condensed table-striped">
			<tr class="active">
				<th>#</th>
				<th><center>Currícula</center></th>
				<th><center>Código</center></th>
				<th><center>Nombre Asignatura</center></th>
				<th><center>Turno</center></th>
				<th><center>Tipo Asignatura</center></th>
				<th><center>Semestre</center></th>
				<th><center>
				<select name="type_rate" id='edit-type-rate-all' class=" form-control input-sm">
						<option value="">Seleccione</option>
						<option value="O" <?php echo ($courses['type_rate'] == 'O')?'selected': '' ?> >Objetivo</option>
						<option value="C" <?php echo ($courses['type_rate'] == 'C')?'selected': '' ?>>Competencia</option>
				</select>
					</center></th>
				<th><center>Eliminar</center></th>
			</tr>
			<?php 
			$i=1;
			foreach ($this->courses as $courses) { 
				$type=($courses['type']=="O")? "Obligatorio":"Electivo"; ?>
				<tr 
					action = 'false'
					curid=<?php echo $courses['curid']?>
					courseid=<?php echo $courses['courseid']?>
					turno=<?php echo $courses['turno']?>
					escid=<?php echo $this->escid?>
					subid=<?php echo $this->subid?>
					distid=<?php echo $this->distid?>
					perid=<?php echo $this->perid?>
				>
					<td><?php echo $i?></td>
					<td><center><?php echo $courses['curid']?></center></td>
					<td><center><?php echo $courses['courseid']?></center></td>
					<td><?php echo $courses['name']?></td>
					<td><center><?php echo $courses['turno']?></center></td>
					<td><center><?php echo $type?></center></td>
					<td><center><?php echo $courses['semid']?></center></td>
					<td>
						<select name="type_rate" class="edit-type-rate form-control input-sm" 

						>
							<option value="">Seleccione</option>
							<option value="O" <?php echo ($courses['type_rate'] == 'O')?'selected': '' ?> >Objetivo</option>
							<option value="C" <?php echo ($courses['type_rate'] == 'C')?'selected': '' ?>>Competencia</option>
						</select>
					</td>
					<td>
						<center>
							<a href="#" id="deletecourse_<?php echo $i?>"><span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Eliminar Asignatura"></span></a>
						</center>
					</td>
					<script type="text/javascript">
						$("#deletecourse_<?php echo $i?>").click(function(){
							var perid="<?php echo $this->perid?>";
							var escid="<?php echo $this->escid?>";
							var subid="<?php echo $this->subid?>";
							var distid="<?php echo $this->distid?>";
							var courseid="<?php echo $courses['courseid']?>";
							var curid="<?php echo $courses['curid']?>";
							var semid="<?php echo $courses['semid']?>";
							var turno="<?php echo $courses['turno']?>";
							var url="/distribution/distribution/deletecourse/courseid/"+courseid+"/semid/"+semid+"/curid/"+curid+"/escid/"+escid+"/perid/"+perid+"/turno/"+turno+"/subid/"+subid;
	            			$("#loadingg").load(url);
	            			$("#datcourses").html("<img src='/img/spinner.gif'>Cargando...");
							var url2="/distribution/distribution/courses/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid;
							$("#datcourses").load(url2);
						});
					</script>
				</tr>
				<?php
				$i++;
			}?>
		</table>
	</div>
	<?php
}else{ ?>
<div class="alert alert-info">
	<b>INFORMACIÓN: </b>No hay Asignaturas registradas en este Periodo, para agregar las Asignaturas hacer click en "AGREGAR ASIGNATURA".
</div>
<?php
}?>
<div id="loadingg"></div>
<div class="modal fade" id="addcourse" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 750px">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button id="closemodal" type="button" class="close" aria-hidden="true">&times;</button>
          		<h4 class="modal-title"><span class="glyphicon glyphicon-tasks"></span> - AGREGAR ASIGNATURAS</h4>
        	</div>
        	<div class="modal-body">
          		<div id="loadingcourses"></div>
        	</div>
      	</div>
    </div>
</div>

<script>
$("#addcourses").click(function(){
	var perid="<?php echo $this->perid?>";
	var escid="<?php echo $this->escid?>";
	var subid="<?php echo $this->subid?>";
	var distid="<?php echo $this->distid?>";
	$("#loadingcourses").load("/distribution/distribution/addcourses/perid/"+perid+"/escid/"+escid+"/subid/"+subid+"/distid/"+distid);
});

$("#closemodal").click(function(){
	$("#addcourse").modal('hide');
	window.location.reload();
});

$('.glyphicon').tooltip();
</script>