
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Editar Distribución');?>
<?php $this->placeholder('Btnnav')->append('<a href="/distribution/distribution/index/anio/'.$this->dataforUpdate['anio'].'" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>
	');?>

<!--Mensajes-->
<div class="row">
	<div class="col-md-2 col-md-offset-8">
		<a href="##" id="save" class="btn btn-success form-control" style="border-radius:0;">Guardar</a>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<hr>
	</div>
</div>
<div class="row-fluid">
	<div class="col-md-8 col-md-offset-2">
		<div id="missing" class="alert alert-warning hidden">
			<button type="button" class="close">&times;</button>
			<strong>Falta Datos!</strong> Le falta rellenar algunos datos....
		</div>
	</div>
</div>

<form action="" id="form">

<input type="hidden" name="distid" value="<?php echo $this->dataforUpdate['distid'] ?>">
<input type="hidden" name="perid" value="<?php echo $this->dataforUpdate['perid'] ?>">

<div class="row">
	<div class="col-md-8 col-md-offset-2 panel panel-default">
		<div class="col-md-5">
			<h4><br></h4>
			<h5 class="text-muted">Codigo</h5>
			<?php echo $this->form->number ?>
		</div>
		<div class="col-md-7">
			<h5 class="text-muted">Periodo</h5>
			<?php echo $this->form->perid ?>
			<div class="row">
				<div class="col-md-6">
					<h5 class="text-muted">Fecha de Presentación</h5>
					<?php echo $this->form->datepress ?>
				</div>
				<div class="col-md-6">
					<h5 class="text-muted">Estado</h5>
					<?php echo $this->form->state ?>
				</div>
			</div><br>
		</div>
	</div>
</div>	
<input type="hidden" name="whySubmit" value="update">
</form>
<script>
	$("#datepress").datepicker();

	$('#save').click(function(){
		$.ajax({
			type   : 'post',
			url    : '/distribution/distribution/savedistribution',
			data   : $('#form').serialize(),
			success: function(data){
				$('.alert').addClass('hidden');
				if (data == 'exito') {
					$(location).attr('href', "/distribution/distribution/index/anio/<?php echo $this->dataforUpdate['anio'] ?>")
				}else if (data == 'falta-datos'){
					$('#missing').removeClass('hidden');
				}
			}
		});
	});

	//Close Alerts
	$('.close').click(function(){
		$('.alert').addClass('hidden');
	});

</script>