
<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Editar Distribución');?>
<?php $this->placeholder('Btnnav')->append('<a href="/distribution/distribution/index/anio/'.$this->anio.'" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a></a>
	<a href="##" id="save" class="btn btn-success">Guardar</a>');?>

<form action="/distribution/distribution/edit/distid/<?php echo $this->dataget['distid']?>/perid/<?php echo $this->dataget['perid']?>" method="post" id="form">

	<table class="table"> 
		<tr>
			<th class="col-md-2">Periodo</th>
			<th class="col-md-2" >Numero</th>
			<th class="col-md-2">Fecha Presentación</th>
			<th class="col-md-2">Estado</th>
		</tr>
		<tr>
			<td ><input id="year" class="form-control" type="text" value="<?php echo $this->period[0]['perid'].' | '.$this->period[0]['name'] ?>" disabled></td>
			<td ><?php print $this->form->number?></td>
			<td ><?php print $this->form->datepress?></td>
			<td ><?php print $this->form->state?></td>
		</tr>
	</table>
</form>
<script>

	$('#save').click(function(){
		$('#form').submit();
	});

	$('#form').submit(function(){
		$.ajax({
			type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function(data){
            	alert(data);
            }
		});
	});
	/*$(function() {
		
		$("#datepress").datepicker();
		$("#dateaccept").datepicker();
		$("#sendform").click(function(){
			$("#frmDistribution").submit();
		});
		
		
	});*/
	
</script>