<link rel="stylesheet" href="/css/distributionIndex.css">

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Distribuciones');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>

<input id="yearComing" type="hidden" value="<?php echo $this->anio ?>">
<input id="currentYear" type="hidden" value="<?php echo $this->yearActive ?>">

<div class="distribution_header">
	<p class="distribution_headerObO distribution_headerParrafo"><span class="glyphicon glyphicon-info-sign"></span> Puede filtrar distribuciones de otros años:</p>
	<div class="distribution_headerObO selectAnio">
		<select class="form-control" name="Año" id="anio">
			<?php for ($i=$this->yearActive + 1; $i >= 1993 ; $i--) : ?>
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
			<?php endfor ?>
		</select>
	</div>
	<a id="newDistribution" href="/distribution/distribution/new" class="distribution_headerObO distribution_headerBtnNewDist btn btn-success form-control"><span class="glyphicon glyphicon-plus"></span> Nueva Distribución</a>
</div>
<hr>

<div id="dataDistribution"></div>

<script>
	$(function(){
		var year = $('#yearComing').attr('value');
		if (year) {
			$('#anio').val(year);
		}else {
			$('#anio').val($('#currentYear').val());
		}

		var anio = $('#anio').val();
		$('#dataDistribution').html('<center><img src="/img/spinner.gif" alt="" /></center>');
		$('#dataDistribution').load('/distribution/distribution/showdistribution/anio/' + anio);
		$('#anio').change(function(){
			$('.obser').popover('hide');
			$('#dataDistribution').html('<center><img src="/img/spinner.gif" alt="" /></center>');
			anio = $(this).val();
			$('#dataDistribution').load('/distribution/distribution/showdistribution/anio/' + anio);
			$('#newDistribution').attr('href', '/distribution/distribution/new/anio/'+anio);
		});
	});
</script>