<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Listado de Distribuciones');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>
    <a href="/distribution/distribution/new" class="btn btn-success"><span class="glyphicon glyphicon-plus "></span> Nuevo</a>');?>
<?php
$ldistri =$this->ldistribution;
?>
<div class="row">
	<div class="col-md-2 col-md-offset-1">
		<h6 class="text-muted pull-right"><span class="glyphicon glyphicon-filter"></span> Filtre por Año</h6>
	</div>
	<div class="col-md-2">
		<select class="form-control" name="Año" id="anio">
			<?php for ($i=$this->yearActive; $i >= 1993 ; $i--) : ?>
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
			<?php endfor ?>
		</select>
	</div>
</div>
<hr>

<div id="dataDistribution"></div>

<script>
	var anio = $('#anio').val();
	$('#dataDistribution').html('<center><img src="/img/spinner.gif" alt="" /></center>');
	$('#dataDistribution').load('/distribution/distribution/showdistribution/anio/' + anio);
	$('#anio').change(function(){
		$('#dataDistribution').html('<center><img src="/img/spinner.gif" alt="" /></center>');
		var anio = $(this).val();
		$('#dataDistribution').load('/distribution/distribution/showdistribution/anio/' + anio);
	});
</script>