<?php
if ($this->usuarios){
$dbescid = new Api_Model_DbTable_Speciality();
$dbinfotea = new Api_Model_DbTable_UserInfoTeacher();?>
<table class="table table-condensed table-striped table-hover">
    <tr>
        <th><center>#</center></th>
        <th><center>Código</center></th>
        <th><center>Apellidos y Nombres</center></th>
        <th><center>Escuela</center></th>
        <th><center>Categoria</center></th>
        <th><center>Condición</center></th>
        <th><center>Dedicación</center></th>
        <th><center>Gestionar</center></th>
        <th><center>Asignar Horario</center></th>
        <th><center>Carga Académica</center></th>
    </tr>
    <?php
    $i=1;
    foreach ($this->usuarios as $user){
        $rid=substr($user['uid'], 8,2);
        if($user['state']=='A'){
            if($rid=='DC' or $rid=='JP'){
                $whereesc['eid'] = $whereinfo['eid'] = $user['eid'];
                $whereesc['oid'] = $whereinfo['oid'] = $user['oid'];
                $whereesc['escid'] = $whereinfo['escid'] = $user['escid'];
                $escuela = $dbescid->_getFilter($whereesc,$attrib=null,$orders=null);
                $whereinfo['subid'] = $user['subid'];
                $whereinfo['uid'] = $user['uid'];
                $whereinfo['pid'] = $user['pid'];
                $datainfotea = $dbinfotea->_getOne($whereinfo);?>
                <tr>
                    <td><center><?php echo $i?></center></td>
                    <td><center><?php echo $user['uid']?></center></td>
                    <td><?php echo $user['last_name0']." ".$user['last_name1'].", ".$user['first_name']?></td>
                    <td><center><?php echo $escuela[0]['name']?></center></td>
                    <td><center><?php echo $datainfotea['category']?></center></td>
                    <td><center><?php echo $datainfotea['condision']?></center></td>
                    <td><center><?php echo $datainfotea['dedication']?></center></td>
                    <td>
                        <center><a href="#" onclick="javascript: window.open('/distribution/distribution/assigncourses/uid/<?php print base64_encode($user['uid'])?>/pid/<?php print base64_encode($user['pid'])?>/escid/<?php print base64_encode($user['escid'])?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($user['subid'])?>','Asignación Cursos','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=900,height=720')" rel="tooltip" title="Asignar Asignaturas"><span class="glyphicon glyphicon-edit"></span></a></center>
                    </td>
                    <td>
                        <center>
                            <?php
                            if ($user['courseasig']) {   ?>
                                <a class='asighorarysuport' href="#" pid='<?php echo base64_encode($user['pid'])?>' uid='<?php echo base64_encode($user['uid'])?>' escid='<?php echo base64_encode($this->escid)?>' subid='<?php echo base64_encode($this->subid)?>' perid='<?php echo base64_encode($this->perid)?>'><span class="glyphicon glyphicon-calendar"></span></a>
                            <?php
                            }
                            else{ ?>
                                <a><span rel="tooltip" title="Deshabilitado" class="glyphicon glyphicon-ban-circle"></span></a>
                            <?php
                            }
                            ?>
                        </center>
                    </td>
                    <td>
                        <center>
                            <?php
                            if ($user['courseasig']) {   ?>
                                <a href="/distribution/distribution/printreportdistri/subid/<?php echo base64_encode($this->subid)?>/escid/<?php print base64_encode($this->escid)?>/uid/<?php print base64_encode($user['uid'])?>/pid/<?php print base64_encode($user['pid'])?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>" target="_blank" rel="tooltip" title="Imprimir carga"><span class="glyphicon glyphicon-print"></span></a>
                            <?php
                            }
                            else{ ?>
                                <a href="#"><span rel="tooltip" title="Deshabilitado" class="glyphicon glyphicon-ban-circle"></span></a>
                            <?php
                            }
                            ?>
                        </center>
                    </td>
                </tr>
            <?php
            $i++;
            }
        }
    } ?>
</table>
<?php
}else{ ?>
<div class="alert alert-info">
    <b>Información: </b>El Docente no se encuentra registrado en el Sistema.
</div>
<?php
}?>


<!-- Modal Asignar Horario-->
<div class="modal fade" id="myModalhorarySuport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" style="width:95%">
        <div class="modal-content">
            <div class="modal-body" id='inloadhorarySuport'></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal Horas clases-->
<div class="modal fade" id="mymodalhorasclaseSuport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 style="color:#428BCA"><b><center>Ingresar Horario</center></b></h3>
            </div>
            <div class="modal-body" id='asighoursSuport'></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal eliminar horario del docente apoyo-->
<div class="modal fade" id="myModalSuport" style="margin-top:10%" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:30%">
        <div class="modal-content">
            <div class="modal-body">
                <h4 class="modal-title text-danger" id="myModalLabel"><span class='glyphicon glyphicon-dashboard'></span><b> ESTA SEGURO DE ELIMINAR EL HORARIO DE ESTE CURSO? </b></h4>
            </div>
            <div class="modal-body text-right">
                <button id="aceptarsSuport" type="button" class="btn btn-success"><span class='glyphicon glyphicon-ok'></span> Aceptar</button>
                <button id='cancelSuport' type="button" class="btn btn-danger"><span class='glyphicon glyphicon-log-out'></span> Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('a[rel=tooltip]').tooltip();

    $(".asighorarysuport").on('click', function(){
        $('#myModalhorarySuport').modal('show');
        var pid=$(this).attr('pid');
        var uid=$(this).attr('uid');
        var escid=$(this).attr('escid');
        var subid=$(this).attr('subid');
        var perid=$(this).attr('perid');

        var ajax_data = {
                        "uid"   : uid,
                        "pid"   : pid,
                        "escid" : escid,
                        "subid" : subid,
                        "perid" : perid
                        };
        $("#inloadhorarySuport").empty();
        $("#inloadhorarySuport").html("<center><img src='/img/spinner.gif' /> Cargando...</center>");
        $.ajax({
            type : 'post',
            url  : '/horary/nhorary/fillhorarysuport/',
            data : ajax_data,
            success: function(data){
                $("#inloadhorarySuport").html(data);
            }
        });
        $("#asighoursSuport").empty();
        $("#asighoursSuport").html("<center><img src='/img/spinner.gif' /> Cargando...</center>");
        $.ajax({
            type : 'post',
            url  : '/horary/nhorary/asignationhoursuport/',
            data : ajax_data,
            success: function(data){
                $("#asighoursSuport").html(data);
            }
        });
    });

    $("#cancelSuport").on('click', function(){
        $("#myModalSuport").modal('hide');
    });

    $('#myModalSuport').on('hidden.bs.modal', function (e){
        $('#myModalhorarySuport').modal('show');
    });
</script>