<!-- <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<script src="/external/jquery/jquery-1.9.1.js"></script>
<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
<script src="/external/jquery/external/globalize.js"></script>
<script src="/external/jquery/external/jquery.mousewheel.js"></script>
<script src="/external/jquery/external/jshint.js"></script>
<script src="/external/jquery/external/qunit.js"></script>
<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
<script src="/external/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
<link href="/external/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet"> -->
<script src="/js/jquery-1.11.0.js"></script>
<script src="/external_library/bootstrap/js/bootstrap.js"></script>
<script src="/external_library/bootstrap/js/jquery.functions.js"></script>
<link rel="stylesheet" type="text/css" href="/external_library/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/css/style.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<style type="text/css">
.cuadro{
    background-color: #fff;
    border-radius: 5px;
    border: 1px solid silver;
    padding-top: 10px;
    padding-bottom: 15px;
    width: 96%;
    margin-left: 2%;
}
th, td{
    font-size:12px;
}
</style>
<body class="found">
<table class="table" style="background: #428bca; color: white">
    <tr>
        <td>
            <a href="/distribution/distribution/printpreview/perid/<?php echo base64_encode($this->perid)?>/distid/<?php echo base64_encode($this->distid)?>/uid/<?php echo base64_encode($this->uid)?>/pid/<?php echo base64_encode($this->pid)?>" class='btn btn-info'><span class="glyphicon glyphicon-print"></span> Imprimir</a>
        </td>
        <td>
        	<h4><b><center>VISTA PRELIMINAR</center></b></h4>
        </td>
        <td>
            <a style="float:right" class='btn btn-danger' onclick="javascript: window.close();"><span class="glyphicon glyphicon-eject"></span> Cerrar</a>
            <a style="float:right" href="/distribution/distribution/assigncourses/perid/<?php echo base64_encode($this->perid)?>/escid/<?php echo base64_encode($this->esciddoc)?>/subid/<?php echo base64_encode($this->subiddoc)?>/distid/<?php echo base64_encode($this->distid)?>/uid/<?php echo base64_encode($this->uid)?>/pid/<?php echo base64_encode($this->pid)?>" class="btn btn-warning"><span class="glyphicon glyphicon-arrow-left"></span> Atras</a>
        </td>
    </tr>
</table>
<div id="academica" class="cuadro">
    <div>
        <h5 style="color: silver"><center><b><?php echo $this->person['last_name0']." ".$this->person['last_name1'].", ".$this->person['first_name']?></b></center></h5>
    </div>
    <center>
    <?php
        if ($this->courses) { ?>
    <table class="table table-condensed table-hover" style="margin-top:10px; width:96%">
        <tr>
        	<th><center>#</center></th>
            <th><center>Currícula</center></th>
            <th>Asignaturas</th>
            <th><center>Escuela</center></th>
            <th><center>Turno</center></th>
            <th><center>Sem</center></th>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
        </tr>
        <?php
        $i = 1;
        foreach ($this->courses as $courses) {
        	$where = array(
        		'eid' => $courses['eid'], 'oid' => $courses['oid'], 'curid' => $courses['curid'],
        		'escid' => $courses['escid'], 'subid' => $courses['subid'], 'courseid' => $courses['courseid']);
        	$cour = new Api_Model_DbTable_Course();
        	$data_cour = $cour->_getOne($where);

        	$where = array('eid' => $courses['eid'], 'oid' => $courses['oid'], 'escid' => $courses['escid']);
        	$esc = new Api_Model_DbTable_Speciality();
        	$data_school = $esc->_getFilter($where,$attrib=null,$orders=null);
        	?>
        	<tr>
        		<td><center><?php echo $i ?></center></td>
        		<td><center><?php echo $courses['curid'] ?></center></td>
        		<td><?php echo $courses['courseid']." - ".$data_cour['name'] ?></td>
        		<td><center><?php echo $data_school[0]['name']?></center></td>
        		<td><center><?php echo $courses['turno']?></center></td>
        		<td><center><?php echo $courses['semid'] ?></center></td>
        		<td><center><?php echo $courses['groups'] ?></center></td>
        		<td><center><?php echo $courses['hours_t'] ?></center></td>
        		<td><center><?php echo $courses['hours_p'] ?></center></td>
        		<td><center><?php echo $courses['hours_total'] ?></center></td>
        	</tr>
        	<?php
        	$i++;
        }?>
    </table>
    <?php
	} ?>
	</center>
</div>
</body>