<div style="margin-top:20px">
    <table class="table table-condensed table-striped table-hover">
        <tr>
            <th><center>#</center></th>
            <th><center>Código</center></th>
            <th>Apellidos y Nombres</th>
            <th class="col-xs-1" ><center>Estado</center></th>
            <th><center>Categoria</center></th>
            <th><center>Condición</center></th>
            <th><center>Dedicación</center></th>
            <th><center>Asignar Curso</center></th>
            <th><center>Asignar Horario</center></th>
            <th><center>Carga Académica</center></th>
        </tr>
        <?php
        $i=1;
        if ($this->teacher){
            foreach ($this->teacher as $teacher){ ?>
                <tr>
                    <td><center><?php echo $i?></center></td>
                    <td><center><?php echo $teacher['uid']?></center></td>
                    <td>
                        <?php echo $teacher['last_name0']." ".$teacher['last_name1'].", ".$teacher['first_name']?>
                    </td>
                    <td>
                        <center>
                        <?php
                        if($teacher['state']=='A'){ ?>
                            <a href="#" id='state_<?php echo $i?>' dat="<?php echo $teacher['uid'].";--;".$teacher['escid'].";--;".$teacher['pid'].";--;".$teacher['subid'].";--;I"?>">
                                <img src="/img/circulo-verde.png" width="20" height="20" rel="tooltip" title="Inhabilitar Docente">
                            </a>
                        <?php
                        }else{ ?>
                            <a href="#" id='state_<?php echo $i?>' dat="<?php echo $teacher['uid'].";--;".$teacher['escid'].";--;".$teacher['pid'].";--;".$teacher['subid'].";--;A"?>">
                                <img src="/img/circulo-rojo.png" width="20" height="20" rel="tooltip" title="Habilitar Docente">
                            </a>
                        <?php
                        } ?>
                        </center>
                        <script type="text/javascript">
                            $("#state_<?php echo $i?>").click(function(){
                                var teacherasig="<?php echo $teacher['courseasig']?>";
                                if (teacherasig=="") {
                                    var distid="<?php echo $this->distid?>";
                                    var perid="<?php echo $this->perid?>";
                                    var tipo=$(this).attr('dat');
                                    var tmp=tipo.split(";--;");
                                    var uid=tmp[0];
                                    var escid=tmp[1];
                                    var pid=tmp[2];
                                    var subid=tmp[3];
                                    var content=tmp[4];
                                    var url="/distribution/distribution/modifyteacher/perid/"+perid+"/distid/"+distid+"/uid/"+uid+"/escid/"+escid+"/pid/"+pid+"/subid/"+subid+"/content/"+content+"/option/STA";
                                    // alert(url);
                                    $("#chargeteacher").load(url);

                                } else{
                                    alert("EL docente ya tiene asignado un curso no se puede inhabilitar");
                                };
                            });
                        </script>
                    </td>
                    <td>
                        <select id="category_<?php echo $i?>" class="form-control">
                            <option value="">- Seleccione -</option>
                            <?php
                            $catego = array('Asociado','Principal','Auxiliar');
                            for ($c=0; $c < 3; $c++) {
                                $selected=($teacher['category']==strtoupper($catego[$c]))? "selected":""; ?>
                                <option value="<?php echo $teacher['uid'].";--;".$teacher['escid'].";--;".$teacher['pid'].";--;".$teacher['subid'].";--;".strtoupper($catego[$c])?>" <?php echo $selected?>><?php echo $catego[$c]?></option>
                                <?php
                            }?>
                        </select>
                    </td>
                    <script>
                        $("#category_<?php echo $i?>").change(function(){
                            var distid="<?php echo $this->distid?>";
                            var perid="<?php echo $this->perid?>";
                            var tipo = $(this).val();
                            if (tipo=="") {
                                alert("Seleccione una Categoria.");
                                return false;
                            };
                            var tmp=tipo.split(";--;");
                            var uid=tmp[0];
                            var escid=tmp[1];
                            var pid=tmp[2];
                            var subid=tmp[3];
                            var content=tmp[4];
                            var url="/distribution/distribution/modifyteacher/perid/"+perid+"/distid/"+distid+"/uid/"+uid+"/escid/"+escid+"/pid/"+pid+"/subid/"+subid+"/content/"+content+"/option/CAT";
                            // alert(url);
                            $("#chargeteacher").load(url);
                        });
                    </script>
                    <td>
                        <select id="condision_<?php echo $i?>" class="form-control">
                            <option value="">- Seleccione -</option>
                            <?php
                            $condi = array('Contratado','Ordinario');
                            for ($c=0; $c < 2; $c++) {
                                $selected=($teacher['condision']==strtoupper($condi[$c]))? "selected":"";?>
                                <option value="<?php echo $teacher['uid'].";--;".$teacher['escid'].";--;".$teacher['pid'].";--;".$teacher['subid'].";--;".strtoupper($condi[$c])?>" <?php echo $selected?>><?php echo $condi[$c]?></option>
                                <?php
                            }?>
                        </select>
                    </td>
                    <script>
                        $("#condision_<?php echo $i?>").change(function(){
                            var distid="<?php echo $this->distid?>";
                            var perid="<?php echo $this->perid?>";
                            var tipo = $(this).val();
                            if (tipo=="") {
                                alert("Seleccione una Condición.");
                                return false;
                            };
                            var tmp=tipo.split(";--;");
                            var uid=tmp[0];
                            var escid=tmp[1];
                            var pid=tmp[2];
                            var subid=tmp[3];
                            var content=tmp[4];
                            var url="/distribution/distribution/modifyteacher/perid/"+perid+"/distid/"+distid+"/uid/"+uid+"/escid/"+escid+"/pid/"+pid+"/subid/"+subid+"/content/"+content+"/option/CON";
                            // alert(url);
                            $("#chargeteacher").load(url);
                        });
                    </script>
                    <td>
                        <select id="dedicacion_<?php echo $i?>" class="form-control">
                            <option value="">- Seleccione -</option>
                            <?php
                            $dedi[0]['val']='TIEMPOCOMPLETO';
                            $dedi[0]['name']='Tiempo Completo';
                            $dedi[1]['val']='DEDICACIONEXCLUSIVA';
                            $dedi[1]['name']='Dedicación Exclusiva';
                            $dedi[2]['val']='TIEMPOPARCIAL';
                            $dedi[2]['name']='Tiempo Parcial';
                            for ($c=0; $c < 3; $c++) {
                                $selected=($teacher['dedication']==strtoupper($dedi[$c]['val']))? "selected":"";?>
                                <option value="<?php echo $teacher['uid'].";--;".$teacher['escid'].";--;".$teacher['pid'].";--;".$teacher['subid'].";--;".$dedi[$c]['val']?>" <?php echo $selected?>><?php echo $dedi[$c]['name']?></option>
                                <?php
                            } ?>
                        </select>
                    </td>
                    <script>
                        $("#dedicacion_<?php echo $i?>").change(function(){
                            var distid="<?php echo $this->distid?>";
                            var perid="<?php echo $this->perid?>";
                            var tipo = $(this).val();
                            if (tipo=="") {
                                alert("Seleccione una Dedicación.");
                                return false;
                            };
                            var tmp=tipo.split(";--;");
                            var uid=tmp[0];
                            var escid=tmp[1];
                            var pid=tmp[2];
                            var subid=tmp[3];
                            var content=tmp[4];
                            var url="/distribution/distribution/modifyteacher/perid/"+perid+"/distid/"+distid+"/uid/"+uid+"/escid/"+escid+"/pid/"+pid+"/subid/"+subid+"/content/"+content+"/option/DED";
                            // alert(url);
                            $("#chargeteacher").load(url);
                        });
                    </script>
                    <td>
                        <center><a href="#" onclick="javascript: window.open('/distribution/distribution/assigncourses/uid/<?php print base64_encode($teacher['uid'])?>/pid/<?php print base64_encode($teacher['pid'])?>/escid/<?php print base64_encode($teacher['escid'])?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>/subid/<?php echo base64_encode($teacher['subid'])?>','Asignación Cursos','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=900,height=720')" rel="tooltip" title="Asignar Asignaturas"><span class="glyphicon glyphicon-edit"></span></a></center>
                    </td>
                    <td>
                        <center>
                            <?php
                            if ($teacher['courseasig']) {   ?>
                                <a class='asighorary' href="#" pid='<?php echo base64_encode($teacher['pid'])?>' uid='<?php echo base64_encode($teacher['uid'])?>' escid='<?php if ($teacher['escid']=='2ES') { echo base64_encode($this->escid);}else{echo base64_encode($teacher['escid']);}?>' subid='<?php echo base64_encode($teacher['subid'])?>' perid='<?php echo base64_encode($this->perid)?>'><span class="glyphicon glyphicon-calendar"></span></a>
                            <?php
                            }
                            else{ ?>
                                <a><span rel="tooltip" title="Deshabilitado" class="glyphicon glyphicon-ban-circle"></span></a>
                            <?php
                            }
                            ?>
                        </center>
                    </td>
                    <td>
                        <center>
                            <?php
                            if ($teacher['courseasig']) {   ?>
                                <a href="/distribution/distribution/printreportdistri/subid/<?php echo base64_encode($teacher['subid'])?>/escid/<?php print base64_encode($teacher['escid'])?>/uid/<?php print base64_encode($teacher['uid'])?>/pid/<?php print base64_encode($teacher['pid'])?>/distid/<?php echo base64_encode($this->distid)?>/perid/<?php echo base64_encode($this->perid)?>" target="_blank" rel="tooltip" title="Imprimir carga"><span class="glyphicon glyphicon-print"></span></a>
                            <?php
                            }
                            else{ ?>
                                <a href="#"><span rel="tooltip" title="Deshabilitado" class="glyphicon glyphicon-ban-circle"></span></a>
                            <?php
                            }
                            ?>
                        </center>
                    </td>
                </tr>
                <?php
            $i++;
            }
        } ?>
    </table>
</div>
<div id='chargeteacher'></div>

<!-- Modal Asignar Horario-->
<div class="modal fade" id="myModalhorary" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" style="width:95%">
        <div class="modal-content">
            <div class="modal-body" id='inloadhorary'></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal Horas clases-->
<div class="modal fade" id="mymodalhorasclase" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 style="color:#428BCA"><b><center>Ingresar Horario</center></b></h3>
            </div>
            <div class="modal-body" id='asighours'></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal eliminar horario-->
<div class="modal fade" id="myModal" style="margin-top:10%" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:30%">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-danger" id="myModalLabel"><span class='glyphicon glyphicon-dashboard'></span><b> ESTA SEGURO DE ELIMINAR EL HORARIO DE ESTE CURSO? </b></h4>
      </div>
      <div class="modal-body text-right">
            <button id="aceptars" type="button" class="btn btn-success"><span class='glyphicon glyphicon-ok'></span> Aceptar</button>
            <button id='cancel' type="button" class="btn btn-danger"><span class='glyphicon glyphicon-log-out'></span> Cancelar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$('img[rel=tooltip]').tooltip();
$('a[rel=tooltip]').tooltip();

$(".asighorary").on('click', function(){
    $('#myModalhorary').modal('show');
    var pid=$(this).attr('pid');
    var uid=$(this).attr('uid');
    var escid=$(this).attr('escid');
    var subid=$(this).attr('subid');
    var perid=$(this).attr('perid');

    var ajax_data = {
                    "uid"   : uid,
                    "pid"   : pid,
                    "escid" : escid,
                    "subid" : subid,
                    "perid" : perid
                    };
    $("#inloadhorary").empty();
    $("#inloadhorary").html("<center><img src='/img/spinner.gif' /> Cargando...</center>");
    $.ajax({
        type : 'post',
        url  : '/horary/nhorary/fillhorary/',
        data : ajax_data,
        success: function(data){
            $("#inloadhorary").html(data);
        }
    });
    $("#asighours").empty();
    $("#asighours").html("<center><img src='/img/spinner.gif' /> Cargando...</center>");
    $.ajax({
        type : 'post',
        url  : '/horary/nhorary/asignationhours/',
        data : ajax_data,
        success: function(data){
            $("#asighours").html(data);
        }
    });
});

$("#cancel").on('click', function(){
    $("#myModal").modal('hide');
});

$('#myModal').on('hidden.bs.modal', function (e){
    $('#myModalhorary').modal('show');
});
</script>