<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start();
$sesion1  = Zend_Auth::getInstance();
$sesion = $sesion1->getStorage()->read();
?>
<link rel="stylesheet" type="text/css" href="/css/print.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  
<div style="text-align:center; margin-top:2%"><b><h3> LISTA DE DOCENTES - ASIGNATURAS - <?php echo $this->perid?></h3></b></div>

<?php 
if ($this->coursenotassign) { ?>
    <div style="margin-bottom: 15px">
        <div>
            <h5><center><b>ASIGNATURAS SIN DOCENTE</b></center></h5>
        </div>
        <center>
        <table style="margin-top:10px; width:100%">
        <tr>
            <th><center>#</center></th>
            <th><center>Currícula</center></th>
            <th>Asignaturas</th>
            <th><center>Turno</center></th>
            <th><center>Sem</center></th>
        </tr>
        <?php
        $i = 1;
        foreach ($this->coursenotassign as $coursenotassign) {
                $where = array(
                    'eid' => $coursenotassign['eid'], 'oid' => $coursenotassign['oid'], 
                    'curid' => $coursenotassign['curid'], 'escid' => $coursenotassign['escid'], 
                    'subid' => $coursenotassign['subid'], 'courseid' => $coursenotassign['courseid']);
                $cour = new Api_Model_DbTable_Course();
                $data_cour = $cour->_getOne($where);
                ?>
                <tr>
                    <td><center><?php echo $i ?></center></td>
                    <td><center><?php echo $coursenotassign['curid'] ?></center></td>
                    <td><?php echo $coursenotassign['courseid']." - ".$data_cour['name'] ?></td>
                    <td><center><?php echo $coursenotassign['turno']?></center></td>
                    <td><center><?php echo $coursenotassign['semid'] ?></center></td>
                </tr>
                <?php
                $i++;
        }
        ?>
    </table>
    </center>
    </div>
    <?php
}?>

<?php 
if ($this->courses) { 
    foreach ($this->teachers as $teachers) { 
    $user = new Api_Model_DbTable_Users();
    $data_user = $user->_getUserXUid($where=array('eid' => $this->eid, 'oid' => $this->oid, 'uid' => $teachers)); ?>
    <div style="margin-bottom: 15px">
        <div>
            <h5><center><b><?php echo $teachers." - ".$data_user[0]['last_name0']." ".$data_user[0]['last_name1'].", ".$data_user[0]['first_name']?></b></center></h5>
        </div>
        <center>
        <table style="margin-top:10px; width:100%">
        <tr>
            <th><center>#</center></th>
            <th><center>Currícula</center></th>
            <th>Asignaturas</th>
            <th><center>Turno</center></th>
            <th><center>Sem</center></th>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
        </tr>
        <?php
        $i = 1;
        foreach ($this->courses as $courses) {
            if ($courses['uid'] == $teachers) {
                $where = array(
                    'eid' => $courses['eid'], 'oid' => $courses['oid'], 'curid' => $courses['curid'], 
                    'escid' => $courses['escid'], 'subid' => $courses['subid'], 'courseid' => $courses['courseid']);
                $cour = new Api_Model_DbTable_Course();
                $data_cour = $cour->_getOne($where);
                ?>
                <tr>
                    <td><center><?php echo $i ?></center></td>
                    <td><center><?php echo $courses['curid'] ?></center></td>
                    <td><?php echo $courses['courseid']." - ".$data_cour['name'] ?></td>
                    <td><center><?php echo $courses['turno']?></center></td>
                    <td><center><?php echo $courses['semid'] ?></center></td>
                    <td><center><?php echo $courses['groups'] ?></center></td>
                    <td><center><?php echo $courses['hours_t'] ?></center></td>
                    <td><center><?php echo $courses['hours_p'] ?></center></td>
                    <td><center><?php echo $courses['hours_total'] ?></center></td>
                </tr>
                <?php
                $i++;
            }
        }
        ?>
    </table>
    </center>
    </div>
    <?php
    }
}?>
<?php 
    $html = ob_get_contents();
    $mpdf=new mPDF('win-1252','A4','','',15,15,30,12,5,7);
    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer);
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('DOCENTES - ASIGNATURAS -'.$this->perid.'.pdf','D');
    // $mpdf->Output();
?>    