<?php
$i=1;
if ($this->cursosasignados){  ?>
    <table id="vercursosasig" style="width:96%; margin:0px" class="table table-bordered table-condensed table-striped">
        <tr>
            <th>#</th>
            <th>Código</th>
            <th>Nombre Asignatura</th>
            <th><center>Turno</center></th>
            <th><center>Sem</center></th>
            <th><center>Compromiso</center></th>
            <th><center>Grupos</center></th>
            <th><center>#H.T.</center></th>
            <th><center>#H.P.</center></th>
            <th><center>#T.T.</center></th>
            <th><center>Eliminar</center></th>       
        </tr>
        <?php              
        foreach ($this->cursosasignados as $cursos){ ?>
            <tr>
                <td><?php echo $i?></td>            
                <td><?php echo $cursos['courseid']?></td>
                <td><?php echo $cursos['name']?></td>
                <td><?php echo $cursos['turno']?></td>
                <td><center><?php echo $cursos['semid']?></center></td>
                <td>
                    <center>
                    <?php 
                        if($cursos['is_com']=='S') echo "SI";
                        elseif($cursos['is_com']=='N') echo "NO"; ?>
                    </center>
                </td>
                <?php 
                $yy=$cursos['hours_total'];
                $temporalh=$temporalh+$yy; ?>
                <td><center><?php echo $cursos['groups']?></center></td>
                <td><center><?php echo $cursos['hours_t']?></center></td>
                <td><center><?php echo $cursos['hours_p']?></center></td>
                <td><center><?php echo $cursos['hours_total']?></center></td>
                <td>
                    <center><a href="/distribution/distribution/deleteasigncourse/perid/<?php echo base64_encode($this->perid)?>/subiddoc/<?php echo base64_encode($this->subiddoc)?>/esciddoc/<?php echo base64_encode($this->esciddoc)?>/courseid/<?php echo base64_encode($cursos['courseid'])?>/turno/<?php echo base64_encode($cursos['turno'])?>/curid/<?php echo base64_encode($cursos['curid'])?>/pid/<?php echo base64_encode($this->pid)?>/uid/<?php echo base64_encode($this->uid)?>/distid/<?php echo base64_encode($this->distid)?>" rel="tooltip" title="Eliminar Asignatura"><span class="glyphicon glyphicon-trash"></span></a></center>
                </td>
            </tr>
        <?php
        $i++;
        }?>
        <tr>
            <td colspan='9'>Total Horas Académicas</td>
            <td><center><?php echo $temporalh;?></center></td>
            <td></td>
        </tr>
    </table>
<?php }
?>

<script type="text/javascript">
$('a[rel=tooltip]').tooltip();
</script>