<?php
$ldistri =$this->ldistribution;
?>
<?php if ($this->ldistribution): ?>



<div class="distribution_dataDistributions">
	<?php if ($ldistri): ?>
		<?php foreach ($ldistri as $i => $distri): ?>
			<?php
				$hours = $distri['hours'];
				$periodo = $distri['perid'];
				$num = $distri['number'];
				$approv = $distri['dateaccept'];
				$date = date_create($approv);
				$approv = date_format($date,'d-m-Y');
				$distid = base64_encode($distri['distid']);
				$perid = base64_encode($distri['perid']);
				$per = $distri['perid'];
				$state="";
				$image="";
				$state = ($distri['state']=='A')?"class='success'":"";

				switch ($distri['state']) {
					case 'A': 	$classState = "distEnviado";
								$nameState = "Enviado";
								break;
					case 'I': 	$classState = "distInactivo";
								$nameState = "Inactivo";
								break;
					case 'C': 	$classState = "distActive";
								$nameState = "Activo";
								break;
					case 'B': 	$classState = "distBorrador";
								$nameState = "Borrador";
								break;
					case 'O': 	$classState = "distObservado";
								$nameState = "Observado";
								break;
				}
			 ?>
			<div class="distribution <?php echo $classState ?>">
				<div class="distObO distPeriod">
					Periodo <?php echo $periodo ?>
				</div>
				<div class="distObO distName">
					<?php echo $num ?>
				</div>

				<?php if ($distri['state'] == 'O'): ?>
					<div class="distObO distState obser" title="Observado" data-container="body" data-toggle="popover" data-content="DISTRIBUCIÓN OBSERVADA POR PEDAGOGÍA" observation='<?php echo $distri['observation']?>' distid='<?php echo $distid;?>' perid='<?php echo $perid;?>' escid='<?php echo base64_encode($distri['escid']);?>' subid='<?php echo base64_encode($distri['subid'])?>'>
						<?php echo $nameState ?>
					</div>
				<?php else: ?>
					<div class="distObO distState">
						<?php echo $nameState ?>
					</div>
				<?php endif ?>
				<div class="distObO distDateAproved">
					<?php if ($approv): ?>
						<?php echo $approv ?>
					<?php else: ?>
						Falta Aprobación
					<?php endif ?>
				</div>
				<div class="distObO distBtnsSide">
					<?php if ($distri['state']=='C' || $distri['state']=='I'): ?>
						<?php 
							$distributionId = base64_encode($distri['perid'].'|'.
															$distri['escid'].'|'.
															$distri['subid'].'|'.
															$distri['distid'] );
						 ?>
						<a href="##" class="btnCObO btnListTeacher" data-toggle="modal" data-target="#modalDocentesDist" distributionid="<?php echo $distributionId ?>">Lista de Docentes</a>
						<a href="/distribution/printdistribution/index/escid/<?php echo base64_encode($distri['escid'])?>/subid/<?php echo base64_encode($distri['subid'])?>/perid/<?php echo $perid;?>/distid/<?php echo $distid;?>" class="btnCObO btnCPrint">Imprimir</a>
					<?php elseif ($distri['state']=="B" || $distri['state']=='O'): ?>
						<a href="/distribution/distribution/edit/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>/anio/<?php echo base64_encode($this->anio) ?>" class="btnEObO btnEdit">Editar</a>
						<a href="##" class="btnEObO btnSend sendp" distid='<?php echo $distid;?>' perid='<?php echo $perid;?>' escid='<?php echo base64_encode($distri['escid']);?>' subid='<?php echo base64_encode($distri['subid'])?>'>Enviar</a>
						<?php if ($hours): ?>
							<a href="##" class="btnEObO btnHorary updatehour" data-toggle="modal" data-target="#myModal" perid='<?php echo $per;?>' escid='<?php echo $distri['escid'];?>' subid='<?php echo $distri['subid']?>'>Horario</a>
						<?php else: ?>
							<a href="##" class="btnEObO btnHorary">Horario</a>
						<?php endif ?>
						<?php if ($distri['state']=='B'): ?>
							<a href="/distribution/distribution/delete/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>" class="btnEObO btnDelete">Eliminar</a>
						<?php else: ?>
							<a href="##" title="Imposible Eliminar" class="btnEObO btnDelete">Eliminar</a>
						<?php endif ?>
						<a href="/distribution/printdistribution/index/escid/<?php echo base64_encode($distri['escid'])?>/subid/<?php echo base64_encode($distri['subid'])?>/perid/<?php echo $perid;?>/distid/<?php echo $distid;?>" class="btnEObO btnEPrint">Imprimir</a>
						<?php if ($hours): ?>
							<a href="/distribution/distribution/academicload/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>/escid/<?php echo base64_encode($distri['escid'])?>/subid/<?php echo base64_encode($distri['subid'])?>" class="btnEObO btnAcademic">Carga Academica</a>
						<?php else: ?>
							<a href="##" class="btnEObO btnAcademic horary" data-toggle="modal" data-target="#myModal1" distid='<?php echo $distid;?>' perid='<?php echo $perid;?>' escid='<?php echo base64_encode($distri['escid']);?>' subid='<?php echo base64_encode($distri['subid'])?>' title="Primero Ingrese el Horario">Carga Academica</a>
						<?php endif ?>
					<?php elseif ($distri['state'] == 'A'): ?>
						<p class="parrafoSend"><span class="glyphicon glyphicon-time"></span> Su distribución se envio a pedagogia, espera una respuesta...</p>
					<?php endif ?>
				</div>
			</div>
		<?php endforeach ?>
	<?php endif ?>
</div>


<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      		</div>
      		<div class="modal-body">
        		<div id='hourbegin'></div>
        	</div>
      		<div class="modal-footer">
        		<button type="button" class="btn btn-danger" data-dismiss="modal" >Cerrar</button>
      		</div>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal Modificar-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      		</div>
      		<div class="modal-body">
        		<div id='updatehour'></div>
      		</div>
      		<div class="modal-footer">
        		<button type="button" class="btn btn-danger" data-dismiss="modal" >Cerrar</button>
      		</div>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Corregir distribución-->
<div class="modal fade" id="myModals" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
     		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        		<h3 class="modal-title text-danger text-center" id="myModalLabel"><b>Revise su distribución</b></h3>
        	</div>
      		<div class="modal-body">
        		<div class="alert alert-info" style="width:90%; margin-left:5%"><h4><b>Sí corrigió la distribución y desea hacer un comentario click aquí <button id="sendiss" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-send"></span></button></b></h4></div>
      			<div id="obs"></div>
      		</div>
      		<div class="modal-footer">
        		<button type="button" class="btn btn-danger" data-dismiss="modal" >Cancelar</button>
      		</div>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="Modals" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        	<h3 class="modal-title text-danger text-center" id="myModalLabel"><b>Revise su distribución</b></h3>
	      	</div>
	      	<div class="modal-body">
	      		<div>
	      			<div class="text-info"><b>Si desea ingresa un comentario: </b></div><br>
	      			<textarea id="comentss" rows="4" class="form-control" placeholder="Ingrese Comentario" cols="80"></textarea>
	      		</div>
	      	</div>
	      	<div class="modal-footer">
	      		<button id="sendis" type="button" class="btn btn-success"><span class="glyphicon glyphicon-send"></span> Enviar Distribución</button>
	        	<button id='cancel'type="button" class="btn btn-danger" data-dismiss="modal" >Cancelar</button>
	      	</div>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- MODAL ENVIAR DISTRIBUCION A PEDAGOGIA-->
<div class="modal fade" id="sendModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog" style='width:34%'>
    	<div class="modal-content">
	      	<div class="modal-body">
	      		<div class='text-center text-info'>
	      			<h4><span class='glyphicon glyphicon-info-sign'></span> Desea enviar su distribucion a pedagogía </h4>
	      		</div>
	      	</div>
	      	<div class="modal-footer">
	      		<button id="yesdis" type="button" class="btn btn-success"><span class="glyphicon glyphicon-send"></span> Enviar Distribución</button>
	        	<button id='cancels'type="button" class="btn btn-danger" data-dismiss="modal" >Cancelar</button>
	      	</div>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div id="valids"></div>
<div id="obsvalids"></div>


<!-- Modal para la lista de docentes -->
<div class="modal fade" id="modalDocentesDist" tabindex="-1">
	<div id="dataDocentesDist" class="modal-dialog modal-listDocentes">

	</div>
</div>

<script>
	$(function(){
		var distributionId = '';
		$('.btnListTeacher').on('click', function(){
			distributionId = $(this).attr('distributionid');
			$('#dataDocentesDist')
				.html('<br><br><br><br><br><br><center><img src="/img/spinner.gif" alt="Loading...">')
				.load('/distribution/distribution/docentesdistribution/distributionid/' + distributionId);
		});

		// $("#valids").hide();
		$('.obser').hover(function(){
			$('#myModals').modal('show');
			var params = {
				observation:$(this).attr('observation'),
				escid1:$(this).attr('escid'),
				subid1:$(this).attr('subid'),
				distid1:$(this).attr('distid'),
				perid1:$(this).attr('perid')
			};
			var sms="<h5><b>Este es la observación: </b>"+params['observation']+"</h5>";
			$('#obs').html(sms);
			$("#sendiss").click(function(){
				$("#myModals").modal("hide");
				$("#Modals").modal("show");
				$("#sendis").click(function(){
					var coments=$("textarea#comentss").val();
					var state="<?php echo base64_encode('C')?>";
					coments=coments.trim();
					//alert(coments);
					$("#Modals").modal("hide");
					$('#Modals').on('hidden.bs.modal', function (e) {
						$('.obser').popover('hide');
						var url1="/distribution/distribution/sendistribution/";
						var dataString = 'state='+state+'&escid='+params['escid1']+'&subid='+params['subid1']+'&distid='+params['distid1']+'&perid='+params['perid1']+'&comment=' + coments;

				        $.ajax({
				            type: "POST",
				            url: url1,
				            data: dataString,
				            success: function(data) {
				            	$('#obsvalids').html(data);
				            }
				        });

						// var url="/distribution/distribution/sendistribution/state/<?php echo base64_encode("A")?>/escid/"+params['escid1']+"/subid/"+params['subid1']+"/distid/"+params['distid1']+"/perid/"+params['perid1']+"/comment/"+coments;
						// $('.obser').popover('hide');
					});
				});
			});
		});
		$('#cancel').click(function(){
			$('#myModals').modal('show');
		});

		$(".sendp").click(function(){
			$("#sendModal").modal('show');
			var params = {
				escid1:$(this).attr('escid'),
				subid1:$(this).attr('subid'),
				distid1:$(this).attr('distid'),
				perid1:$(this).attr('perid')
			};
			$("#yesdis").click(function(){
				var url="/distribution/distribution/oksendistribution/state/<?php echo base64_encode("A")?>/escid/"+params['escid1']+"/subid/"+params['subid1']+"/distid/"+params['distid1']+"/perid/"+params['perid1'];
				$("#valids").load(url);
				$("#sendModal").modal("hide");
			});

		});
		$('.glyphicon').tooltip();

		$(function () {
			$('.obser').popover('show');
		});

		setTimeout(function() {
		  	$('.obser').popover('hide');
		}, 15000);

		$(".horary").click(function(){
			var params = {
				escid:$(this).attr('escid'),
				subid:$(this).attr('subid'),
				distid:$(this).attr('distid'),
				perid:$(this).attr('perid')
			};
			$.get("/horary/nhorary/changehours/",
				params,
				function  ($data) {
					$("#hourbegin").html('<br><center>Cargando <img src="/img/spinner.gif" alt="Cargando ..." /></center>');
					$("#hourbegin").html($data);
			});

		});

		$(".updatehour").click(function(){
			var para = {
				escid:$(this).attr('escid'),
				subid:$(this).attr('subid'),
				perid:$(this).attr('perid')
			};
			$.get("/horary/nhorary/updatehours/",
				para,
				function  ($data) {
					$("#updatehour").html('<br><center>Cargando <img src="/img/spinner.gif" alt="Cargando ..." /></center>');
					$("#updatehour").html($data);
			});
		});
	});
</script>

<?php else: ?>
	<h4 class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> No existen distribuciones <span class="text-danger">este año</span></h4>
<?php endif ?>