<form name="<?php echo $this->form->getName(); ?>" id="frmsearching" action="/distribution/distribution/listsupportteacher/distid/<?php echo $this->distid?>/perid/<?php echo $this->perid?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
    <table class="table table-striped" style="margin-top:20px">
        <tr>
            <th colspan="5"><center>BUSQUEDA DE DOCENTES</center></th>
        </tr>
        <tr>
            <th>Ingrese Apellidos:</th>
            <td title="Busqueda por Apellidos">
                <?php echo $this->form->name;?>
            </td>
            <th>Ingrese DNI:</th>
            <td style="width:150px"title="Ingrese su DNI">
                <?php echo $this->form->pid;?>
            </td>
            <td><?php echo $this->form->enviar?></td>
        </tr>
    </table>
</form>
<div id="chargesupport"></div>

<script type="text/javascript">
    $("#frmsearching").submit(function(){
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function(data) {                        
                $('#chargesupport').html(data);
            }
        }); 
        return false;
    });

    function soloLetras(e){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = [8,37,39,46];

        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            } 
        }
         
        if(letras.indexOf(tecla)==-1 && !tecla_especial)
            return false;
        };

    function soloNumero(e){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = "0123456789";
        especiales = [8,37,39,46];

        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            } 
        }
 
        if(letras.indexOf(tecla)==-1 && !tecla_especial)
            return false;
        };
</script>