<div class="panel panel-default" style="margin-top:15px">
  	<div class="panel-body">
    	<b style="font-size:20px"><span class="glyphicon glyphicon-user"></span> - LISTA DE DOCENTES</b>
    	<a id="add" href="#" class="btn btn-info" style="float:right"><span class="glyphicon glyphicon-pencil"></span> <b>Agregar Asignatura</b></a>
  	</div>
</div>
<div>
	<ul class="nav nav-tabs" id="listteachers">
	  	<li class="active"><a href="#primaryteacher">Docentes</a></li>
	  	<li><a href="#practiceteacher">Jefes de Práctica</a></li>
	  	<li><a href="#supportteacher">Docente de Apoyo</a></li>	  	
	</ul>

	<div class="tab-content">
	  	<div class="tab-pane active" id="primaryteacher"></div>
	  	<div class="tab-pane" id="practiceteacher"></div>
	  	<div class="tab-pane" id="supportteacher"></div>
	</div>
</div>

<script type="text/javascript">
var perid="<?php echo $this->perid?>";
var escid="<?php echo $this->escid?>";
var subid="<?php echo $this->subid?>";
var distid="<?php echo $this->distid?>";

$("#primaryteacher").html("<img src='/img/spinner.gif'>Cargando...");
$("#primaryteacher").load("/distribution/distribution/primaryteacher/escid/"+escid+"/subid/"+subid+"/perid/"+perid+"/distid/"+distid);

//   $("#tab2").html("<img src='/img/spinner.gif' />Cargando....");
//   $("#tab2").load("/distribucion/distribucion/jefepractica/escid/<?php echo $this->escid;?>/sedid/<?php echo $this->sedid;?>/perid/<?php echo $this->perid;?>/distid/<?php echo $this->distid;?>");

//   $("#tab3").html("<img src='/img/spinner.gif' />Cargando....");
//   $("#tab3").load("/distribucion/distribucion/agregardocentesdistribucion/escid/<?php echo $this->escid;?>/sedid/<?php echo $this->sedid;?>/perid/<?php echo $this->perid;?>/distid/<?php echo $this->distid;?>/sedid/<?php echo $this->sedid;?>");
$('#listteachers a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
});
</script>