<div id="data">

    <table class="table span9 table-bordered">
        <thead>
        <tr>
                
                <th >DNI</th>
                <th >USUARIO</th>
                <th >Nombres</th>
                <th >Escuela</th>
                <th >Record</th>
        </tr>
        </thead>

    <?php
    if ($this->data)
    {
       foreach ($this->data as $info)    
        {
           ?>
            <tr>
                <td><?php echo $info['pid'];?></td>
                <td><?php echo $info['uid'];?></td>
                <td><?php echo $info['last_name0']." ".$info['last_name1'].", ".$info['first_name'];?></td>
                <td><?php echo $info['escid']?></td>
                <td><center><a href="/rcentral/recordnotas/print/uid/<?php echo $info['uid'];?>/eid/<?php echo $info['eid']?>/oid/<?php echo $info['oid']?>/pid/<?php echo $info['pid']?>/escid/<?php $info['escid']?>/subid/<?php echo $info['subid']?>"><img src="/img/pdf.png"></a></center></td>
            </tr>
           <?php
        }
    }
    ?>
    </table>
        <div style="clear:both"></div>  
</div>
