<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/default/recordnotas/listaralumnosnom/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table span9 table-striped table-bordered table-condensed">
        <tr>
            <td colspan="2"><center><h3>Impresion de Record Notas </h3></center></td>
        </tr>
    </table>        
<!--     <table class="table span9 table-striped table-bordered table-condensed">
        <tr>
        	<td><center>Codigo del Alumno</center></td>
            <td><center>Nombres y Apellidos</center></td>
        </tr>
        <tr>                    
        	<td class="span4"><center><?php echo $this->fm->uid; ?></center></td>
            <td class="span4"><center><?php echo $this->fm->ap; ?></center></td>
        </tr>
    </table> -->
    <div style="clear:both" ></div>
</form>