<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-th-list"></span> REPORTE MATRICULADOS');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroRep" action="/report/registration/listreport/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
   
    <table class="table table-striped table-condensed">
        <tr>
            <td colspan="2">AÑO:</td>
            <td colspan="2"><?php print $this->fm->anio;  ?></td>
            <td colspan="2"></b>PERIODO:</b></td>
            <td colspan="2"> <?php print $this->fm->perid; ?></td>
            <td class="span3" rowspan="3"><br><br><br>  <center><a href="/reportes/" class="btn btn-warning">Regresar Rerportes</a></center></td> 
        </tr>
        <tr>             
           <td><?php print $this->fm->mat.'Matriculados';?></td>
           <td><?php print $this->fm->premat.'Pre - Matriculados';?></td>
           <td><?php print $this->fm->npremat.'No pre - matriculados';?></td>
           <td><?php print $this->fm->obs.'Observados';?></td>
           <td  colspan="4"><?php print $this->fm->res.'Reservados';?></td>
        </tr>
            <tr>
            <td colspan="7"><?php print $this->fm->x;?></td>
        </tr>
        <tr>
            <td colspan="9">
            <center><a href="#" id="generarreporte" style="float:center" class="btn btn-primary"><i class="glyphicon glyphicon-list-alt glyphicon-white"> </i>Generar Reporte</a><center>
            </td>
        </tr>
    </table>    
</form>



<div  id="cargadatos_"></div>  
<div style="clear:both" ></div>
<script>
    $("#anio").change(function () 
    {
        $("#anio option:selected").each(function () 
        {
            vanio = $(this).val();
            $('#periodo').html('<div class="controls"> <img src="/img/spinner.gif" /> Procesando...</div>');
            $.post("/report/registration/periods/", { anio: vanio }, function(data){
            $('#periodo').html("<select id='perid' name='perid'><option value=''>- Seleccione el periodo -</option></select>");
            $("#perid").html(data);
            });
        });
    });

    $("#frmFiltroRep").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) 
            {                        
            $('#cargadatos_').html(data);
            }
        }); 
        return false;
    });

    $("#generarreporte").click(function(){
        $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
        $("#frmFiltroRep").submit();
        return false;
    });
    /*$("#x-xfac,#x-xesc,#x-xsed,#perid").change(function () {
        $("#x-xfac,#x-xesc,#x-xsed option:selected").each(function () {
            $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
            $("#frmFiltroRep").submit();
        });
    });

    $("#mat,#premat,#npremat,#obs,#res").click(function () {
            $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
            $("#frmFiltroRep").submit();
    });

    $("#anio").change(function () {
        $("#anio option:selected").each(function() {
            $('#cargadatos_').html("Seleccione Periodo");
        });
    });     */   

    // $(document).ready(function(){
    //     document.getElementById("x-xfac").checked = true;
    //     document.getElementById("mat").checked = true;
    // });
</script>