<div class="panel panel-info" style="margin-top: 3%">
    <div class="panel-heading">
        <b>REPORTE GRAFICO DE EGRESADOS DE LA FACULTAD DE <?php echo strtoupper($this->faculty['name'])?> - ESCUELA DE <?php echo strtoupper($this->school['name'])?></b>
    </div>
    <div class="panel-body">
        <center>
            <iframe name="iFrame1" style="width:100%; height:300px" src="/graduated/graphicgraduated/loadgraphics/escid/<?php print $this->escid ?>/perid/<?php print $this->perid ?>/facid/<?php print $this->facid ?>/anho/<?php print $this->anho ?>/especialidad/<?php print $this->especialidad ?>" frameborder='0'>
            </iframe>
        </center>
    </div>
</div>