<div class="row">
	<div class="col-md-10 col-md-offset-1">

		<div class="panel panel-warning">
			<br>
		    <div class="panel-body">
		        <center>
		            <iframe name="iFrame1" style="width:100%; height:300px" src="/graduated/graphicgraduated/loadgraphics/escid/<?php print $this->escid ?>/perid/<?php print $this->perid ?>/facid/<?php print $this->facid ?>/anho/<?php print $this->anho ?>/especialidad/<?php print $this->especialidad ?>" frameborder='0'>
		            </iframe>
		        </center>
		    </div>
		</div>
		
	</div>
</div>

