 <script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
    google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(drawChart);
     
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
        <?php
            $escu = new Api_Model_DbTable_Speciality();
            foreach ($this->egresados as $curso) {
                $whereesc =array(
                    'eid' => $this->eid, 'oid' => $this->oid,
                    'escid' => $curso['escid']);
                $escuela = $escu->_getFilter($whereesc,$attrib=null,$orders=null);
                $infoescuela = $escuela[0]['name'];
                $cantidad=$curso['count']; ?>
                ['<?php print $infoescuela ?>' ,<?php print $cantidad?>],
            <?php  
            } ?>
        ]);
        
        var options = {'title':''};
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };

    function selectHandler() {
        var selectedItem = chart.getSelection()[0];
        var value = data.getValue(selectedItem.row, 0);
        alert('The user selected ' + value);
    };
</script>
<div id="chart_div" style="width: 100%; height: 100%"></div>