<div style="margin-bottom:10px">
	<center>
		<a href="#myModal" role="button" class="btn btn-info new_cur" data-toggle="modal"
			escid='<?php echo $this->escid?>'
			subid='<?php echo $this->subid?>'
		><span class='glyphicon glyphicon-plus'></span> Nueva Currícula</a>
	</center>
</div>
<?php
if ($this->curriculas) { ?>
	<div>
		<table class="table table-hover">
			<tr>
				<th>#</th>
				<th>Codigo</th>
				<th>Nombre Currícula</th>
				<th>Año</th>
				<th colspan="3">Operaciones</th>
			</tr>
			<?php
			$c=1;
			foreach ($this->curriculas as $curriculas) { ?>
				<tr>
					<td><?php echo $c?></td>
					<td><?php echo $curriculas['curid']?></td>
					<td><?php echo $curriculas['name']?></td>
					<td><?php echo $curriculas['year']?></td>
					<td>
						<?php
						if ($curriculas['state']=="B" || $curriculas['state']=="A") { ?>
							<a href="/rcentral/curricula/modifycurricula/curid/<?php echo base64_encode($curriculas['curid'])?>/escid/<?php echo base64_encode($curriculas['escid'])?>/subid/<?php echo base64_encode($curriculas['subid'])?>/accion/M" title="Modificar la Currícula"><i class="icon icon-pencil"></i>Modificar</a>	
							<?php
						}else{ ?>
							<a href="/rcentral/curricula/modifycurricula/curid/<?php echo base64_encode($curriculas['curid'])?>/escid/<?php echo base64_encode($curriculas['escid'])?>/subid/<?php echo base64_encode($curriculas['subid'])?>/accion/V" title="Ver la Currícula" data-toggle="modal" >Ver</a>
							<?php
						}?>
					</td>
					<td>
						<?php
						if ($curriculas['state']=="B") { ?>
							<a href="#" title="Eliminar la Currícula"><i class="icon icon-trash"></i>Eliminar</a>
							<?php
						}else{ ?>
							<a href="#" title="No se elimina la Currícula"><i class="icon icon-remove"></i>No Eliminar</a>
						<?php
						}?>
					</td>
					<td>
						<a href="#" title="Imprimir la Currícula"><i class="icon icon-print"></i>Imprimir</a>
					</td>
				</tr>
				<?php
				$c++;
			}?>
		</table>
	</div>
	<?php
}?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close " data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Nueva Curricula</h4>
        </div>
        <div class="modal-body cont_new_cur">
          
        </div>
        <div class="modal-footer">
          	<button type="button" class="btn btn-default close_new_cur" data-dismiss="modal">Close</button>
          	<button type="button" class="btn btn-success save_curri">
				<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
			 </button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script >
	$(".new_cur").click(function(){
		var escid=$.base64.encode($(this).attr('escid'));
		var subid=$.base64.encode($(this).attr('subid'));

		$.get("/rcentral/curricula/newcurricula",{escid:escid,subid:subid},
			function(data){

				$(".cont_new_cur").html(data);
		});
	});	
</script>