<!-- <div class="row">
	<br>
	<div class="col-md-5 col-md-offset-1">
		<blockquote>
			<h2>Historial <span class="text-warning">Académico</span></h2>
		</blockquote>
	</div>
	<div class="col-md-1 col-md-offset-4">
		<blockquote>
			<h2><span class="glyphicon glyphicon-hdd text-warning"></span></h2>
		</blockquote>
	</div>
</div> -->
<hr class="featurette-divider">

<div class="row">
	
	<div class='col-md-2 text-right text-info' style='font-size:20px'><b>Seleccione un Año:</b></div>	
	<div class="col-md-3 col-md-offset-1">
			<select id="anio" class="form-control" style="width: 120px">
				<option value="">- Año -</option>
				<?php
				$anio = date('Y');
				for ($i=$anio; $i > 1960; $i--) { ?>
					<option value="<?php echo $i?>"><?php echo $i?></option>
				<?php
				} ?>
			</select>
		</div>
	</div>
</div>
	<hr class="featurette-divider">
	<br>
<div id="loaddata" style="margin-top: 20px"></div>

<script type="text/javascript">
$("#anio").change(function(){
	var anio = $(this).val();
	if (!anio) {
		alert("Seleccione un Año.");
		return false;
	};
	$("#loaddata").html("<img src='/img/spinner.gif'>Cargando...");
	$("#loaddata").load("/docente/report/history/anio/"+anio);
});
</script>