<div class="panel panel-primary">
	<div class="panel-heading">
		<div style='font-size:14px'>
			<b><center>INICIO DE CLASES DE LA ESCUELA EN GENERAL</center></b>	
		</div>
	</div>
	<div class="panel-body">
		<form class="form-inline" role="form" name="<?php echo $this->fm->getName(); ?>" id ="frmhours" action="/horary/Nhorary/changehours"  method="POST" enctype="application/x-www-form-urlencoded">
			
				<div class='col-sm-12 form-group'>
					
					<label class='col-sm-12 control-label text-center'><h4><b>MAÑANA</b></h4></label>
	
					<div class='col-sm-1'><span class='glyphicon glyphicon-time' style='font-size:15px'></span></div>
					<label class="col-sm-2 control-label">Hora</label>
			    		<div class="col-sm-3"><?php echo $this->fm->hour?></div>
			    	<div class='col-sm-1'><h4><b>:</b></h4></div>
			  		<label class="col-sm-2 control-label">Minutos</label>
			    		<div class="col-sm-3"><?php echo $this->fm->minute?></div>

			  	</div></br></br>

			  	<div class='col-sm-12 form-group'>
					
					<label class='col-sm-12 control-label text-center'><h4><b>TARDE</b></h4></label>
	
					<div class='col-sm-1'><span class='glyphicon glyphicon-time' style='font-size:15px'></span></div>
					<label class="col-sm-2 control-label">Hora</label>
			    		<div class="col-sm-3"><?php echo $this->fm->hour_t?></div>
			    	<div class='col-sm-1'><h4><b>:</b></h4></div>
			  		<label class="col-sm-2 control-label">Minutos</label>
			    		<div class="col-sm-3"><?php echo $this->fm->minute_t?></div>

			  	</div></br>

				<div class='col-sm-12 form-group'>
					<div class="col-sm-12 text-center"><?php echo $this->fm->save?></div>		
				</div>
			<input type="hidden" name='escid' value='<?php echo $this->escid?>'>
    		<input type="hidden" name='perid' value='<?php echo $this->perid?>'>
    		<input type="hidden" name='subid' value='<?php echo $this->subid?>'>	
		</form>	
	</div>
</div>
<script type="text/javascript">
	var redirect=<?php echo $this->redirect?>;
	if (redirect==1) {

		window.location.href = window.location.href
	};
	
	$("#frmhours").submit(function(){
      $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#hourbegin').html(data);                                 
            }
        }); 
        return false;
      });
	
</script>


