<div class="panel panel-primary">
	<div class="panel-heading">
		<div style='font-size:14px'>
			<b><center>INICIO DE CLASES DE LA ESCUELA EN GENERAL</center></b>	
		</div>
	</div>
	<div class="panel-body">
		<form name="<?php echo $this->fm->getName(); ?>" id ="frmhours" action="/horary/Nhorary/changehours"  method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
			<table class='table'>
				<tr>
					<th colspan='2'><div class='text-center'><h3>MAÑANA</h3></div></th>
					<th colspan='2'><div class='text-center'><h3>TARDE</h3></div></th>
				</tr>
				<tr>
					<th><h5>Hora:</h5></th>
					<td><div style='width: 120px;'><?php echo $this->fm->hour?></td>
					<th><h5>Hora:</h5></th>
					<td><div style='width: 120px;'><?php echo $this->fm->hour_t?></td>
				</tr>
				<tr>
					<th><h5>Minutos:</h5></th>
					<td><div style='width: 120px'><?php echo $this->fm->minute?></td>
					<th><h5>Minutos:</h5></th>
					<td><div style='width: 120px'><?php echo $this->fm->minute_t?></td>
				</tr>
					<th><?php echo $this->fm->save?></th>
			</table>
		</form>	
	</div>
</div>



