<div class="panel panel-primary">
	<div class="panel-heading">
		<div style='font-size:16px'>
			<b><center>INICIO DE CLASES DE LA ESCUELA EN GENERAL</center></b>	
		</div>
	</div>
	<div class="panel-body">
		<form name="<?php echo $this->fm->getName(); ?>" id ="frmhours" action="/horary/Nhorary/changehours"  method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
			<table class='table table-striped table-hover'>
				<tr>
					<th><div class='col-md-6' style='margin-left:5px'><h3>MAÑANA</h3></th>
					<th><div class='col-md-6' style='margin-left:5px'><h3>TARDE</h3></th>
				</tr>
				<tr>
					<th><h4><div style='margin-left:5px'>Hora:</h4></th>
					<td><div style='width: 150px; margin-left:10px'><?php echo $this->fm->hour?></td>
					<th><h4><div style='margin-left:30px'>Minutos:</h4></th>
					<td><div style='width: 150px'><?php echo $this->fm->minute?></td>
				</tr>
				<tr>
					<th><h4><div style='margin-left:5px'>Hora:</h4></th>
					<td><div style='width: 150px; margin-left:10px'><?php echo $this->fm->hour_t?></td>
					<th><h4><div style='margin-left:30px'>Minutos:</h4></th>
					<td><div style='width: 150px'><?php echo $this->fm->minute_t?></td>
				</tr>
					<th><?php echo $this->fm->save?></th>
			</table>
		</form>	
	</div>
</div>


