<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<?php
    $hora=array();  
    $j=1;
    $hour_begin=array();
    $hour_begin=$this->valhoras;
    for ($i=0; $i <= 20; $i++) { 
        $hour[$i]=substr($hour_begin[$i],0,2);
        $minute[$i]=substr($hour_begin[$i],3,2);
    }
    for ($i=0; $i <= 20; $i++) {
        if ($hour[$i]<12) {
            if ($hour[$j]<12) {
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." am";
            }
            else{
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." pm";
            }
        } 
        else{
            $hora[$i]['hora']=$hour[$i].":".$minute[$i]." pm - ".$hour[$j].":".$minute[$j]." pm";
        }
        $hora[$i]['h_ini']=$hour[$i];
        $hora[$i]['h_fin']=$hour[$j];
        $hora[$i]['m_ini']=$minute[$i];
        $hora[$i]['m_fin']=$minute[$j];
        $j++;
    }

    $listacolores = array();
    $listacolores[0] = "#FA8D74";
    $listacolores[1] = "#A3CFE0";
    $listacolores[2] = "#CBE487";
    $listacolores[3] = "#FAF48D";
    $listacolores[4] = "#FCB16B";
    $listacolores[5] = "#CCF0EE";
    $listacolores[6] = "#DFDFDF";
    $listacolores[7] = "#81FF86";
    $listacolores[8] = "#CD88FD";
    $listacolores[9] = "#F59FFC";
    $listacolores[10] = "#A58CFF";
    $listacolores[11] = "#F2BBBB";
    $listacolores[12] = "#D8BADA";
    $listacolores[13] = "#C4E6CE";
    $listacolores[14] = "#B4DAA1";

    if ($this->horarios) {
    // print_r($this->horarios);
    $len=count($this->horarios);
    $hmen=13;
    $hmay=13;
    for ($i=0; $i < $len; $i++) {
        $n=new Api_Model_DbTable_Course();
        $where['eid']=$this->horarios[$i]['eid'];
        $where['oid']=$this->horarios[$i]['oid'];
        $where['escid']=$this->horarios[$i]['escid'];
        $where['curid']=$this->horarios[$i]['curid'];
        $where['subid']=$this->horarios[$i]['subid'];
        $where['courseid']=$this->horarios[$i]['courseid'];
        $ncur=$n->_getOne($where);
        
        $this->horarios[$i]['name']=$ncur['name'];
        $this->horarios[$i]['abbreviation']=$ncur['abbreviation'];
        if ($this->horarios[$i]['type_class']=="P") $this->horarios[$i]['type_class']="(P)";
        else $this->horarios[$i]['type_class']="";
        $ncursos=$this->ncursos;
        for ($j=0; $j < $ncursos; $j++) { 
        	if ($this->horarios[$i]['courseid']==$this->datcursos[$j]['courseid'] && $this->horarios[$i]['turno']==$this->datcursos[$j]['turno']) {
                $this->horarios[$i]['color']=$listacolores[$this->datcursos[$j]['num']];
            }
        }

        $hsplit=split(":", $this->horarios[$i]['hora_ini']);
        $hi=$hsplit[0];
        $hsplit=split(":", $this->horarios[$i]['hora_fin']);
        $hf=$hsplit[0];

        if ($hi<=$hmen) $hmen=$hi;
        if ($hf>=$hmay) $hmay=$hf;
    }
    // print_r($this->horarios);
    $k=0;
    for ($z=0; $z < 20; $z++) { 
        if ($hmen==$hora[$z]['h_ini'] && $k==0) {
            $inih=$z;
            $k=1;
        }
        if ($hmay==$hora[$z]['h_fin']) {
            $finh=$z;
        }
    }
    // print_r($this->horarios);
    $horaoriginal=$this->horarios;

   ?>
<div class="row" style="margin: 0px">
    <div class='col-md-12' id='encabezado'>
        <div class="cajadia">Hora:</div>
        <div class="cajadia" style='margin-left:3px'>Lunes</div>
        <div class="cajadia" style='margin-left:3px'>Martes</div>
        <div class="cajadia" style='margin-left:2px'>Miércoles</div>
        <div class="cajadia" style='margin-left:2px'>Jueves</div>
        <div class="cajadia" style='margin-left:2px'>Viernes</div>
        <div class="cajadia" style='margin-left:2px'>Sábado</div>
    </div>
    <div class='col-md-12 pull-left' style='margin-bottom:40px'>    
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { ?>
                <div class="cajadentro"><?php echo $hora[$i]['hora'] ?></div>
                <?php
            }
            ?>
        </div>
        <?php
               $dat=$this->horarios;
        ?>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                //print_r($dat);
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
                       
                    if ($dia==1) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                ?>
                                <div class="cajadentro" style="margin-left:2px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>"

                                     type="button" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style='margin-left:2px'></div>
                <?php
                }
            }
            ?>
        </div>

        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                //print_r($dat);
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
                    
                    if ($dia==2) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                ?>
                                <div class="cajadentro" style="margin-left:2px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>" type="button" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style="margin-left:2px" ></div>
                <?php
                }
            }
            ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                //print_r($dat);
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
                    
                    if ($dia==3) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";

                                ?>
                                <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style="margin-left:3px" ></div>
                <?php
                }
            }
            ?>
        </div>

         <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                //print_r($dat);
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
    
                    if ($dia==4) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                ?>
                                <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>" type="button" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style="margin-left:3px"></div>
                <?php
                }
            }
            ?>
        </div>

        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==5) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                ?>
                                <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>" type="button" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style="margin-left:3px"></div>
                <?php
                }
            }
            ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarios;
                //print_r($dat);
                for ($s=0; $s < $len; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
 
                    if ($dia==6) {
                        if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";

                                ?>

                                <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>">
                                    <a id="cajahora" href="/horary/nhorary/deletehorary/uid/<?php echo $horaoriginal[0]['teach_uid'] ?>/pid/<?php echo $horaoriginal[0]['teach_pid'] ?>/escid/<?php echo $dat[$s]['escid'] ?>/courseid/<?php echo $dat[$s]['courseid'] ?>/turno/<?php echo $dat[$s]['turno'] ?>/curid/<?php echo $dat[$s]['curid'] ?>/horaini/<?php echo $horaoriginal[$s]['hora_ini'] ?>/horafin/<?php echo $horaoriginal[$s]['hora_fin'] ?>/diasemana/<?php echo $horaoriginal[$s]['day'] ?>" type="button" class="close" title="Eliminar Horario" style="margin-right:1px" onclick="return confirm('Esta Seguro que desea eliminar el horario?');">x</a>
                                    <?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?>
                                </div>
                                <?php    
                                $c++;
                            } else { 
                                $band=1;
                            }
                        }
                    } else { 
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class="cajadentro" style="margin-left:3px"></div>
                <?php
                }
            }
            ?>
        </div>
    </div>    
</div>
<?php
}
else {
?>
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <b>No hay registro de horario.</b>
</div>
<?php
}	
?>




