<div class="panel panel-primary">
	<div class="panel-heading">
		<div style='font-size:14px'>
			<b><center>INICIO DE CLASES DE LA ESCUELA EN GENERAL</center></b>	
		</div>
	</div>
	<div class="panel-body">
		<form name="<?php echo $this->fm->getName(); ?>" id ="frmhours" action="/horary/Nhorary/updatehours"  method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
			<table class='table table-hover'>
				<tr>
					<th colspan='4'><div class='text-center'><h4><b>TURNO</b></h4></div></th>
				</tr>
				<tr>
					<th colspan='2'><div class='text-center'><h5><b>MAÑANA</b></h5></div></th>
					<th colspan='2'><div class='text-center'><h5><b>TARDE</b></h5></div></th>
				</tr>
				<tr>
					<th><h6>Hora:</h6></th>
					<td><div style='width: 120px;'><?php echo $this->fm->hour?></td>
					<th><h6>Hora:</h6></th>
					<td><div style='width: 120px;'><?php echo $this->fm->hour_t?></td>
				</tr>
				<tr>
					<th><h6>Minutos:</h6></th>
					<td><div style='width: 120px'><?php echo $this->fm->minute?></td>
					<th><h6>Minutos:</h6></th>
					<td><div style='width: 120px'><?php echo $this->fm->minute_t?></td>
				</tr>
				<tr>
					<th colspan='4' class='text-center'><?php echo $this->fm->update?></th>
				</tr>
			</table>
    		<input type="hidden" name='pk' value='<?php echo $this->pk['hoursid']?>'>
		</form>	
	</div>
</div>
<script type="text/javascript">
	var redirec=<?php echo $this->redirec?>;
	
	if (redirec==1) {
		window.location.href = window.location.href
	};
	
	$("#frmhours").submit(function(){
      $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#updatehour').html(data);                                 
            }
        }); 
        return false;
      });
	
</script>