<?php
if ($this->data) {	
	$where=$this->where;
	?>
	<div class='col-md-1 col-md-offset-10' style='margin-bottom:1em;'>
		<a href="/report/customreport/printdisapprovedcoursemore50percentlast3/eid/<?php echo base64_encode($where['eid'])?>/oid/<?php echo base64_encode($where['oid'])?>/escid/<?php echo base64_encode($where['escid'])?>/subid/<?php echo base64_encode($where['subid'])?>/curid/<?php echo base64_encode($where['curid'])?>/anio/<?php echo base64_encode($where['anio'])?>/escid1/<?php echo base64_encode($this->escid1)?>/subid1/<?php echo base64_encode($this->subid1)?>" class='btn btn-success'><span class='glyphicon glyphicon-print'></span> Imprimir</a>
	</div>
	<table class='table table-hover'>
		<tr class='info'>
			<th class='text-center'>#</th>
			<th class='text-center'>Código del Curso</th>
			<th class='text-center'>Nombre del Curso</th>
			<th class='text-center'>Porcentaje (%)</th>
		</tr>
		<?php
		foreach ($this->data as $key => $data) {	
			$number = number_format($data['porcentaje'], 2, ',', '');
			?>	
			<tr>
				<td class='text-center'><?php echo $key+1?></td>
				<td class='text-center'><?php echo $data['courseid']?></td>
				<td><?php echo $data['name']?></td>
				<td class='text-center'><?php echo $number." %"?></td>
			</tr>
		<?php	
		}
		?>
	</table>
<?php	
}
else{	?>
<hr>
<div class="row text-center">
	<div class="alert alert-activa col-md-4 col-md-offset-4">
		<h4><span class="text-info glyphicon glyphicon-info-sign"></span><b class="text-muted"> No se encontraron registros</b></h4>
	</div>	
</div>
<?php
}
?>