<?php
if ($this->data) {	
	$where=$this->where;	
	?>
	<div>
		<div class="col-md-12">
			<div class='alert alert-info col-md-8'>
				<span class='glyphicon glyphicon-info-sign'></span> Muesta la Frecuencia de acceso al sistema de una semana antes de la fecha elegida
			</div>
			<div class="col-md-2 col-md-offset-2" style="margin-top:8px">
				<a href="/report/customreport/printfrequencyaccessxweek/eid/<?php echo base64_encode($where['eid'])?>/oid/<?php echo base64_encode($where['oid'])?>/rid/<?php echo base64_encode($where['rid'])?>/fecha/<?php echo base64_encode($where['fecha'])?>" class="btn btn-success"><span class="glyphicon glyphicon-print"></span> Imprimir</a>
			</div>			
		</div>
		<table class='table table-hover'>
			<tr>
				<th class='text-center'>#</th>
				<th class="text-center">Código</th>
				<th class='text-center'>Nombre Escuela</th>
				<th class='text-center'>Frecuencia</th>
			</tr>
			<?php
			foreach ($this->data as $key => $lista) {	?>
				<tr>
					<td class='text-center'><?php echo $key+1?></td>
					<td class='text-center'><?php echo $lista['escid']?></td>
					<td><?php echo $lista['name']?></td>
					<td class='text-center'><?php echo $lista['cantidad']?></td>
				</tr>	
			<?php	
			}
			?>
		</table>
	</div>
<?php	
}
else{	?>
<hr>
<div class="row text-center">
	<div class="alert alert-activa col-md-4 col-md-offset-4">
		<h4><span class="text-info glyphicon glyphicon-info-sign"></span><b class="text-muted"> No se encontraron registros</b></h4>
	</div>	
</div>
<?php
}
?>