<?php 
  	$this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-tasks"></span> Reportes Personalizados');
  	$this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');
?>
<div class="panel panel-primary col-md-12">
	<br>
	<div class='row text-center'>
		<div class='col-md-12'>
			<div class='col-md-2'><b>Seleccione una facultad: </b></div>
			<div class='col-md-2'>
				<select id='seletfac' class='form-control'>
					<option value="nada">-- Seleccione Facultad --</option>
						<?php
							if ($this->data) {
								foreach ($this->data as $key => $facultys) {	
									if ($facultys['facid']!='TODO' && $facultys['facid']!='NINGUN') {
									?>
										<option value='<?php echo $facultys['facid']?>'><?php echo $facultys['name']?></option>
								<?php
									}
								}
							}
						?>
				</select>
			</div>
			<div class='col-md-2'><b>Seleccione una Escuela: </b></div>
			<div class='col-md-2'>
				<select id='seletspec' class='form-control'>
					<option value="nada">-- Seleccione una Facultad --</option>
				</select>
			</div>
			<div class='col-md-2'><b>Seleccione una Especialidad: </b></div>
			<div class='col-md-2'>
				<select id='seletspecia' class='form-control'>
					<option value="nada">-- Seleccione una Especialidad --</option>
				</select>
			</div>
		</div>
	</div><br><br>
	<div class='row hidden' id="contenido">
		<div class="col-md-10 col-md-offset-2">
		  	<div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Cantidad de Matrículas</b></span></h3>
		        		<p><b>Alumnos matriculados por 2º, 3º, 4º, 5º ..., a un curso en los ultimos 4 periodos.</b></p>
		        		<p class='text-right'><a id='report1' href="#" data-toggle="modal" data-target="#myModal1" class="btn btn-success" role="button"><span class='glyphicon glyphicon-list-alt'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div>
		  	<div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Desaprobados mayor a 50%</b></span></h3>
		        		<p><b>Curso cuyo grado de desaprobados es mayor al 50% en los ultimos 3 años.</b></p>
		        		<p class='text-right'><a id="report2" href="#" data-toggle="modal" data-target="#myModal2" class="btn btn-success" role="button"><span class='glyphicon glyphicon-circle-arrow-up'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div>
		</div>
		<div class="col-md-10 col-md-offset-2">
		  	<div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Alumnos con cursos pendientes</b></span></h3>
		        		<p><b>Se muestra a todos los alumnos que van a llevar algun curso por 3º, 4º, 5º ... vez.</b></p>
		        		<p class='text-right'><a id='report5' href="#" data-toggle="modal" data-target="#myModal5" class="btn btn-success" role="button"><span class='glyphicon glyphicon-warning-sign'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div>
		  	<div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Alumnos sin ninguna matrícula</b></span></h3>
		        		<p><b>Alumnos que nunca realizaron por lo menos una matrícula desde su ingreso.</b></p>
		        		<p class='text-right'><a id="report6" href="#" data-toggle="modal" data-target="#myModal6" class="btn btn-success" role="button"><span class='glyphicon glyphicon-tower'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div>
		</div>
	</div>
	<div class='row'>
		<div class="col-md-10 col-md-offset-2">
		  	<!-- <div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Promedio Académico</b></span></h3>
		        		<p><b>Alumnos que mejoran y/o disminuyen su promedio académico en los ultimos 4 periodos.</b></p>
		        		<p class='text-right'><a href="#" class="btn btn-success" role="button"><span class='glyphicon glyphicon-list-alt'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div> -->
		  	<div class="col-md-5">
		    	<div class="thumbnail">
		      		<div class="caption">
		        		<h3><span class='text-primary'><b>Frecuencia de Ingreso</b></span></h3>
		        		<p><b>Identificar frecuencia de ingreso al sistema por alumno/docente/administrativo.</b></p>
		        		<p class='text-right'><a id="report3" href="#" data-toggle="modal" data-target="#myModal3" class="btn btn-success" role="button"><span class='glyphicon glyphicon-stats'></span> Ver reporte</a></p>
		      		</div>
		    	</div>
		  	</div>
		</div>
	</div>	
</div>

<!-- Modal Reporte 1-->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style='width:80%'>
	    <div class="modal-content">
	      	<div class="modal-header" style='background:#e5e5e5'>
	        	<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-log-out"> Cerrar</span></button>
	        	<center><h3 class="modal-title" id="myModalLabel"><span class='glyphicon glyphicon-list-alt'></span><span class='text-primary'><b> Cantidad de Matrículas</b></span></h3></center>
	        	<p><b>Alumnos matriculados por 2º, 3º, 4º, 5º ..., a un curso en los ultimos 4 periodos.</b></p>
	      	</div>
		    <div class="modal-body">
	      		<div class='panel panel-primary'>
	      			<br>	      		
		      		<div class='row text-right'>
		      			<div class='col-md-12'>
		      				<div class='col-md-2 col-md-offset-1'><b>Seleccione un Año: </b></div>
		      				<div class='col-md-3'>
		      					<select id='seletanio' class='form-control'>
		      						<option value="vacio">-- Seleccione Año --</option>
		      							<?php
		      								if ($this->anio) {
		      									for ($i=$this->anio; $i >= 1991; $i--) { 
		      									?>
		      										<option value='<?php echo $i?>'><?php echo $i?></option>
		      									<?php
		      									}
		      								}
		      							?>
		      					</select>
		      				</div>
		      				<div class='col-md-2'><b>Seleccione un Periodo: </b></div>
		      				<div class='col-md-3'>
		      					<select id='seletperiod' class='form-control'>
		      						<option>-- Seleccione un Año --</option>
		      					</select>
		      				</div>
		      			</div>	
		      		</div><br>
		      		<div class='row text-right'>
		      			<div class='col-md-12'>
		      				<div class='col-md-2  col-md-offset-1'><b>Seleccione una Currícula: </b></div>
		      				<div class='col-md-3'>
		      					<select id='seletcurri' class='form-control'>
		      						<option>-- Seleccione una Escuela --</option>
		      					</select>
		      				</div>
		      				<div class='col-md-2'><b>Seleccione un Curso: </b></div>
		      				<div class='col-md-3'>
		      					<select id='seletcurso' class='form-control'>
		      						<option value='vacios'>-- Seleccione una Currícula --</option>
		      					</select>
		      				</div>
		      			</div>	
		      		</div><br>
		      		<div class='row'>
		      			<div class='col-md-12'>
		      				<div class='col-md-4 col-md-offset-5'><a id='viewReports' href="#" class='btn btn-primary disabled'>Ver reporte</a></div>
		      			</div>	
		      		</div><br>
		      		<div id='data_end'></div>
	      		</div>
	      	</div>
	      	<!-- <div class="modal-footer">
	        	<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
	      	</div> -->
	    </div>
	</div>
</div>

<!-- Modal Reporte 2-->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style='width:60%'>
	    <div class="modal-content">
	      	<div class="modal-header" style='background:#e5e5e5'>
	        	<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-log-out"> Cerrar</span></button>
	        	<center><h3 class="modal-title" id="myModalLabel"><span class='glyphicon glyphicon-circle-arrow-up'></span><span class='text-primary'><b> Desaprobados mayor a 50%</b></span></h3></center>
	        	<p><b>Curso cuyo grado de desaprobados es mayor al 50% en los ultimos 3 años.</b></p>
	      	</div>	      	
		    <div class="modal-body">
		    	<div class='panel panel-primary'>
	      			<br>	      		
		      		<div class='row text-right'>
		      			<div class='col-md-12 col-md-offset-1'>
		      				<div class='col-md-2'><b>Seleccione un Año: </b></div>
		      				<div class='col-md-2'>
		      					<select id='seletanio1' class='form-control'>
		      						<option>-- Seleccione Año --</option>
		      							<?php
		      								if ($this->anio) {
		      									for ($i=$this->anio; $i >= 1991; $i--) { 
		      									?>
		      										<option value='<?php echo $i?>'><?php echo $i?></option>
		      									<?php
		      									}
		      								}
		      							?>
		      					</select>
		      				</div>
		      				<div class='col-md-2 '><b>Seleccione una Currícula: </b></div>
		      				<div class='col-md-4'>
		      					<select id='seletcurri1' class='form-control'>
		      						<option>-- Seleccione una Escuela --</option>
		      					</select>
		      				</div>		      				
		      			</div>	
		      		</div><br>
		      		<div class='row'>
		      			<div class='col-md-12'>
		      				<div class='col-md-4 col-md-offset-5'><a id='viewReports1' href="#" class='btn btn-primary disabled'>Ver reporte</a></div>
		      			</div>	
		      		</div><br>
		    		<div id="dataLoad"></div>	
	      		</div>
	      	</div>
	    </div>
	</div>
</div>

<!-- Modal Reporte 3-->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style='width:60%'>
	    <div class="modal-content">
	      	<div class="modal-header" style='background:#e5e5e5'>
	        	<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-log-out"> Cerrar</span></button>
	        	<center><h3 class="modal-title" id="myModalLabel"><span class='glyphicon glyphicon-stats'></span><span class='text-primary'><b> Frecuencia de Ingreso </b></span></h3></center>
	        	<p><b>Identificar frecuencia de ingreso al sistema por alumno/docente/administrativo.</b></p>
	      	</div>	      	
		    <div class="modal-body">
		    	<div class='panel panel-primary'>
	      			<br>	      		
		      		<div class='row text-right'>
		      			<div class='col-md-12'>
		      				<div class='col-md-2'><b>Seleccione una Fecha: </b></div>
		      				<div class='col-md-4'>
		      					<input id="fecha" type="text" name="fecha" class="form-control" title="Fecha" value="<?php echo date('Y-m-d')?>">
		      				</div>
		      				<div class='col-md-2 '><b>Seleccione un Rol: </b></div>
		      				<div class='col-md-4'>
		      					<select id='seletrol' class='form-control'>
		      						<option value="vacio">-- Seleccione Rol --</option>
		      						<?php
		      							if ($this->datarol) {
		      								foreach ($this->datarol as $key => $datarol1) {
		      									if ($datarol1['rid']=='AL' || $datarol1['rid']=='DC') {
		      									?>
		      									<option value='<?php echo $datarol1['rid']?>'><?php echo $datarol1['name']?></option>
		      								<?php		
		      									}
		      								}
		      								?>
		      								<option value="otros">Administrativo</option>
		      								<?php
		      							}
		      						?>
		      					</select>
		      				</div>		      				
		      			</div>	
		      		</div><br>
		      		<div class='row'>
		      			<div class='col-md-12'>
		      				<div class='col-md-4 col-md-offset-5'><a id='viewReports2' href="#" class='btn btn-primary disabled'>Ver reporte</a></div>
		      			</div>	
		      		</div><br>
		    		<div id="dataload1"></div>	
	      		</div>
	      	</div>
	    </div>
	</div>
</div>

<!-- Modal Reporte 5-->
<div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style='width:80%'>
	    <div class="modal-content">
	      	<div class="modal-header" style='background:#e5e5e5'>
	        	<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-log-out"> Cerrar</span></button>
	        	<center><h3 class="modal-title" id="myModalLabel"><span class='glyphicon glyphicon-warning-sign'></span><span class='text-primary'><b> Alumnos con cursos pendientes</b></span></h3></center>
	        	<p><b>Se muestra a todos los alumnos que van a llevar algun curso por 3º, 4º, 5º ... vez.</b></p>
	      	</div>	      	
		    <div class="modal-body">
		    	<div class='panel panel-primary'>
	      			<br>	      		
		      		<div class='row text-right'>
		      			<div class='col-md-12 col-md-offset-1'>
		      				<div class='col-md-3 '><b>Seleccione una Currícula: </b></div>
		      				<div class='col-md-4'>
		      					<select id='seletcurri2' class='form-control'>
		      						<option>-- Seleccione una Escuela --</option>
		      					</select>
		      				</div>		      				
		      			</div>	
		      		</div><br>
		      		<div class='row'>
		      			<div class='col-md-12'>
		      				<div class='col-md-4 col-md-offset-5'><a id='viewReports5' href="#" class='btn btn-primary disabled'>Ver reporte</a></div>
		      			</div>	
		      		</div><br>
		    		<div id="dataload5"></div>	
	      		</div>
	      	</div>
	    </div>
	</div>
</div>

<!-- Modal Reporte 6-->
<div class="modal fade" id="myModal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style='width:60%'>
	    <div class="modal-content">
	      	<div class="modal-header" style='background:#e5e5e5'>
	        	<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-log-out"> Cerrar</span></button>	        	
	        	<center><h3 class="modal-title" id="myModalLabel"><span class='glyphicon glyphicon-tower'></span><span class='text-primary'><b> Alumnos que no tuvieron ninguna matrícula</b></span></h3></center>
		        <p><b>Alumnos que nunca realizaron por lo menos una matrícula desde su ingreso.</b></p>	        	
	      	</div>

		    <div class="modal-body">
		    	<div class='panel panel-primary'>
	      			<br>
		      		<div class='row'>
		      			<div class='col-md-12'>
		      				<div class='col-md-4 col-md-offset-5'><a id='viewReports6' href="#" class='btn btn-primary'>Ver reporte</a></div>
		      			</div>	
		      		</div><br>
		    		<div id="dataload6"></div>	
	      		</div>
	      	</div>
	    </div>
	</div>
</div>

<script type="text/javascript">
	$("#contenido").fadeOut();

	$(function() {
        $( "#fecha" ).datepicker({
            inline:true,
            minDate: new Date(2013, 0, 1),
            maxDate: new Date(2020, 12, 31),
            dateFormat: 'yy-mm-dd',
            //beforeShowDay: fechitas
        });
    });

	$("#seletfac").on('change', function(){
		var facid=$("#seletfac").val();
		var url=("/report/customreport/getspeciality/facid/"+$.base64.encode(facid));
		$("#seletspec").html("<img src='/img/spinner.gif'> Cargando....");
		$("#seletspec").load(url);

		if (facid=='nada') {
			$("#contenido").addClass("hidden");
		};
	});

	$("#seletspec").on('change', function(){
		$("#contenido").fadeIn();
		$("#contenido").removeClass("hidden");
		var valor=$("#seletspec").val();

		if (valor=='nada') {
			$("#contenido").fadeOut();
			$("#contenido").addClass("hidden");
		}
		else{
			$("#dataload6").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload6").empty();
			var ss=$("#seletspec").val();
			var vari=ss.split("|");
			var escid=vari[0];
			var subid=vari[1];
			var url=("/report/customreport/getcurricula/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid));

			var urlspe=("/report/customreport/specialityxscholl/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid));

			$("#seletspecia").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletspecia").load(urlspe);

			$("#seletcurri").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri").load(url);

			$("#seletcurri1").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri1").load(url);

			$("#seletcurri2").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri2").load(url);


		};
	});

	$("#seletspecia").on('change', function(){
		var esss=$("#seletspecia").val();
		if (esss) {
			$("#dataload6").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload6").empty();
			var esss=$("#seletspecia").val();
			var vari=esss.split("|");
			var escid=vari[0];
			var subid=vari[1];
			var url=("/report/customreport/getcurricula/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid));

			$("#seletcurri").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri").load(url);

			$("#seletcurri1").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri1").load(url);

			$("#seletcurri2").html("<img src='/img/spinner.gif'> Cargando...");
			$("#seletcurri2").load(url);			
		};
	});

	$('#myModal1').on('shown.bs.modal', function (e) {
		var valor1=$("#seletcurri").val();

		if (valor1=='vacio') {
			$("#data_end").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#data_end").empty();
			$("#viewReports").addClass('disabled');
			$('#seletcurso > option[value=]').attr('selected', 'selected');
		};
	});

	var anioo=<?php echo $this->anio?>;
	if (anioo) {
		$('#seletanio > option[value='+anioo+']').attr('selected', 'selected');
		$('#seletanio1 > option[value='+anioo+']').attr('selected', 'selected');
		var vanio=$("#seletanio").val();
		var url=("/report/customreport/getperiods/anio/"+$.base64.encode(vanio));
		$("#seletperiod").html("<img src='/img/spinner.gif'> Cargando....");
		$("#seletperiod").load(url);
	};

	$("#seletanio").on('change', function(){
		var vanio=$("#seletanio").val();
		var url=("/report/customreport/getperiods/anio/"+$.base64.encode(vanio));
		$("#seletperiod").html("<img src='/img/spinner.gif'> Cargando....");
		$("#seletperiod").load(url);
	});

	$("#seletcurri").on('change', function(){
		var valorr=$("#seletcurri").val();
		var s=valorr.split("|");
		var curid=s[0];
		var escid=s[1];
		var url=("/report/customreport/getcourses/curid/"+$.base64.encode(curid)+"/escid/"+$.base64.encode(escid))
		$("#seletcurso").html("<img src='/img/spinner.gif'> Cargando....");
		$("#seletcurso").load(url);
	});

	$("#seletcurso").on('change', function(){
		var vcurso=$("#seletcurso").val();
		var vperiod=$("#seletperiod").val();
		if (vcurso!='' ) {
			$("#viewReports").removeClass('disabled');			
		}
		else{
			$("#viewReports").addClass('disabled');	
		};
	});

	$("#viewReports").on('click', function(){
		var anio=$("#seletanio").val();
		var perid=$("#seletperiod").val();
		var valorr=$("#seletcurri").val();
		var s=valorr.split("|");
		var curid=s[0];
		var courseid=$("#seletcurso").val();
		var valor=$("#seletspec").val();
		var sp=$("#seletspecia").val();
		if (sp!='nada') {
			var sp=sp.split("|");
			var escid=sp[0];
			var subid=sp[1];

			var vari=valor.split("|");
			var escid1=vari[0];
			var subid1=vari[1];			
			
			var url=("/report/customreport/registrationquantityrepeatstudents/perid/"+$.base64.encode(perid)+"/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid)+"/courseid/"+$.base64.encode(courseid))+"/escid1/"+$.base64.encode(escid1)+"/subid1/"+$.base64.encode(subid1);
		}
		else{
			var vari=valor.split("|");
			var escid=vari[0];
			var subid=vari[1];			

			var url=("/report/customreport/registrationquantityrepeatstudents/perid/"+$.base64.encode(perid)+"/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid)+"/courseid/"+$.base64.encode(courseid));
		};
		

		if (anio=='vacio') {
			alert("Seleccione un Año");
			return false;
		}
		else if (perid=='') {
			alert("Seleccione un Periodo");
			return false;
		}
		else if (valorr=='vacio'){
			alert("Seleccione una Currícula");
			return false;	
		}
		else if (courseid==''){
			alert("Seleccione un Curso");
		}
		else{
			$("#data_end").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#data_end").load(url);			
		};
	});

	$("#seletcurri1").on('change', function(){
		var x=$("#seletcurri1").val();

		if (x!='') {
			$("#viewReports1").removeClass('disabled');			
		}
		else{
			$("#viewReports1").addClass('disabled');	
		};
	});

	$("#seletcurri2").on('change', function(){
		var x=$("#seletcurri2").val();		

		if (x!='') {
			$("#viewReports5").removeClass('disabled');			
		}
		else{
			$("#viewReports5").addClass('disabled');	
		};
	});

	$("#viewReports1").on('click', function(){
		var cc=$("#seletcurri1").val();
		var ccs=cc.split("|");
		var curid=ccs[0];

		var anio=$("#seletanio1").val();
		var ee=$("#seletspec").val();
		var sp=$("#seletspecia").val();
		if (sp!='nada') {
			var sp=sp.split("|");
			var escid=sp[0];
			var subid=sp[1];

			var ess=ee.split("|");
			var escid1=ess[0];
			var subid1=ess[1];

			var url=("/report/customreport/disapprovedcoursemore50percentlast3/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid)+"/anio/"+$.base64.encode(anio))+"/escid1/"+$.base64.encode(escid1)+"/subid1/"+$.base64.encode(subid1);
		}
		else{
			var ees=ee.split("|");
			var escid=ees[0];
			var subid=ees[1];

			var url=("/report/customreport/disapprovedcoursemore50percentlast3/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid)+"/anio/"+$.base64.encode(anio));
		};

		if (cc=='vacio'){
			alert("Seleccione una Currícula");
			return false;	
		}
		else if (anio=='vacio'){
			alert("Seleccione un Año");
			return false;		
		}
		else{
			$("#dataLoad").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataLoad").load(url);	
		};

	});

	$('#myModal2').on('shown.bs.modal', function (e) {
		var valor2=$("#seletcurri1").val();

		if (valor2=='vacio') {
			$("#dataLoad").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataLoad").empty();
			$("#viewReports1").addClass('disabled');	
		};
	});

	$('#myModal5').on('shown.bs.modal', function (e) {
		var valor3=$("#seletcurri2").val();

		if (valor3=='vacio') {
			$("#dataload5").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload5").empty();
			$("#viewReports5").addClass('disabled');	
		};
	});

	$("#seletrol").on('change',function(){
		var r=$("#seletrol").val();

		if (r!='') {
			$("#viewReports2").removeClass('disabled');			
		}
		else{
			$("#viewReports2").addClass('disabled');	
		};
	});

	$("#viewReports2").on('click',function(){
		var fechita=$("#fecha").val();
		var rid=$("#seletrol").val();
		if (fechita==''){
			alert("Seleccione una Fecha");
			return false;	
		}
		else if (rid=='vacio'){
			alert("Seleccione un Rol");
			return false;		
		}
		else{
			var url=("/report/customreport/frequencyaccessxweek/rid/"+$.base64.encode(rid)+"/fecha/"+$.base64.encode(fechita));

			$("#dataload1").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload1").load(url);			
		};

	});

	$("#viewReports5").on('click', function(){
		var valescid=$("#seletspec").val();
		var valcurid=$("#seletcurri2").val();
		if (valescid=='nada'){
			alert("Seleccione una Escuela");
			return false;	
		}
		else if (valcurid=='vacio'){
			alert("Seleccione una Currícula");
			return false;		
		}
		else{
			var s2=valcurid.split('|');
			var curid=s2[0];
			var sp=$("#seletspecia").val();
			if (sp!='nada') {
				var sp=sp.split("|");
				var escid=sp[0];
				var subid=sp[1];

				var s1=valescid.split("|");
				var escid1=s1[0];
				var subid1=s1[1];

				var url=("/report/customreport/getquantityfailcourseallstudent/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid))+"/escid1/"+$.base64.encode(escid1)+"/subid1/"+$.base64.encode(subid1);
			}
			else{
				var s1=valescid.split('|');
				var escid=s1[0];
				var subid=s1[1];

				var url=("/report/customreport/getquantityfailcourseallstudent/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid)+"/curid/"+$.base64.encode(curid));
			};

			$("#dataload5").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload5").load(url);
		};
	});

	$("#viewReports6").on('click', function(){
		var valescid=$("#seletspec").val();

		if (valescid==''){
			alert("Seleccione una Escuela");
			return false;	
		}
		else{
			var sp=$("#seletspecia").val();
			if (sp!='nada') {
				var sp=sp.split("|");
				var escid=sp[0];
				var subid=sp[1];

				var s1=valescid.split("|");
				var escid1=s1[0];
				var subid1=s1[1];
				
				var url=("/report/customreport/notregistrationstudentsall/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid))+"/escid1/"+$.base64.encode(escid1)+"/subid1/"+$.base64.encode(subid1);
			}
			else{
				var s1=valescid.split('|');
				var escid=s1[0];
				var subid=s1[1];

				var url=("/report/customreport/notregistrationstudentsall/escid/"+$.base64.encode(escid)+"/subid/"+$.base64.encode(subid));
			};			
			$("#dataload6").html("<center><img src='/img/spinner.gif'> Cargando...</center><br>");
			$("#dataload6").load(url);
		};
	});
</script>