<?php
if ($this->data) {	?>
	<table class="table table-hover">
		<tr class="info">
			<th class='text-center'>#</th>
			<th class='text-center'>DNI</th>
			<th class='text-center'>Código</th>
			<th class='text-center'>Alumno</th>
			<th class="text-center">Estado</th>
			<!-- <th class="text-center">Escuela</th> -->
		</tr>
		<?php
			foreach ($this->data as $key => $data) {
				?>
				<tr>
					<td class="text-center"><?php echo $key+1?></td>
					<td class="text-center"><?php echo $data['pid']?></td>
					<td class="text-center"><?php echo $data['uid']?></td>
					<td><?php echo $data['full_name']?></td>
					<td class="text-center"><?php echo $data['state']?></td>
					<!-- <td class="text-center"><?php echo $data['namespec']?></td> -->
				</tr>
			<?php	
			}
		?>
	</table>
<?php	
}
?>