<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div>
    <div style="text-align:left; font-size:12px;">
        <b>Curso: </b><?php echo strtoupper($this->datacourse['courseid']." - ".$this->datacourse['name'])?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        
        <b>Currícula: </b><?php echo strtoupper($this->datacourse['curid'])?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        
    </div>
    <div style="margin-top:10px">
        <b>Desde:</b> El periodo <b><?php echo strtoupper($this->perid1)?></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        
        <b>Hasta: </b>El periodo <b><?php echo strtoupper($this->perid)?></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
</div>
<div style="text-align: center; font-size:16px;margin-top:13px"><b> REPORTE CANTIDAD DE MATRÍCULAS </b></div> <br/>
<?php 
    if ($this->data) {
        ?>
        <table style="width:100%; margin-bottom:20px;" border=" 1px">
            <tr>
                <th class='small'>#</th>
                <th class='small-100'>DNI</th>
                <th class='small-100'>Código</th>
                <th >Apellidos y Nombres</th>
                <th class='small-50'>Veces</th>
            </tr>
            <?php
                foreach ($this->data as $key => $alumnos) {
                    ?>
                    <tr>
                        <td style="text-align:center"><?php echo $key+1?></td>
                        <td style="text-align:center"><?php echo $alumnos['pid']?></td>
                        <td style="text-align:center"><?php echo $alumnos['uid']?></td>
                        <td><?php echo $alumnos['full_name']?></td>
                        <td style="text-align:center"><?php echo $alumnos['veces']?></td>
                    </tr>
                    <?php
                }
            ?>
        </table>
    <?php 
    }
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');
    
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Reporte_cantidad_matriculas_'.$this->datacourse['courseid'].'.pdf','D');
    // $mpdf -> Output();  

?>
