<?php
if ($this->data) {  ?>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-1 col-md-offset-9">
                <a href="#" class="btn btn-success"><span class='glyphicon glyphicon-print'></span> Imprimir</a>
            </div>
        </div><br><br>
        <div class="col-md-12">
            <div class="col-md-10 col-md-offset-1">
                <table class="table table-hover table-bordered">
                    <tr class="info">
                        <th class="text-center">#</th>
                        <th class="text-center">Código</th>
                        <th class="text-center">Apellidos y nombres</th>
                        <th class="text-center">Promedio</th>
                    </tr>
                    <?php
                    $i=0;
                    foreach ($this->data as $k => $lista) { ?>
                        <tr>
                            <td class="text-center"><?php echo $i+1?></td>
                            <td class="text-center"><?php echo $lista['uid']?></td>
                            <td><?php echo $lista['full_name']?></td>
                            <td class="text-center"><?php echo $lista['notafinal']?></td>
                        </tr>
                    <?php
                    $i++;
                    }
                    ?>
                </table>
            </div>
        </div>
    </div>
<?php
}
?>