<?php
if ($this->data) {
	$data=$this->data;
	$where=$this->where;
	$cant=count($data);
	$vfinal=$data[$cant-1]['veces'];
    $s=1;
	for ($i=2; $i <= $vfinal; $i++) { 
		$c=0;
		for ($j=0; $j < $cant; $j++) { 
			if ($data[$j]['veces']==$i) {
				$c=$c+1;
			}
		}
		$s++;
		$cantidad[$s]=$c;
	}
	?>
	<ul id='myReport' class="nav nav-pills nav-justified">
		<li class="active">
	    	<a href="#2" id='val2' class='panel panel-primary' role='tab' data-toggle='tab'>
	      		<span class="badge pull-right"><?php echo $cantidad['2']?></span>
	      		<b>Los que llevaron 2 veces</b>
	    	</a>
	 	</li>
		<?php
		for ($i=3; $i <= $vfinal; $i++) { 	?>
		  	<li>
		    	<a href="#<?php echo $i?>" id='val<?php echo $i?>' class='panel panel-primary' role='tab' data-toggle='tab'>
		      		<span class="badge pull-right"><?php echo $cantidad[$i]?></span>
		      		<b>Los que llevaron <?php echo $i?> veces</b>
		    	</a>
		 	</li>
		<?php	
		}
		?>
	</ul>	
	<div class='table-responsive tab-content' style="margin-top:5px">
		<div class="tab-pane fade in active" id='<?php echo "2"?>'>
			<div class="col-md-2 pull-right" style="margin-bottom:5px">
				<a href="/report/customreport/printregistrationquantityrepeatstudents/eid/<?php echo base64_encode($where['eid'])?>/oid/<?php echo base64_encode($where['oid'])?>/escid/<?php echo base64_encode($where['escid'])?>/subid/<?php echo base64_encode($where['subid'])?>/curid/<?php echo base64_encode($where['curid'])?>/perid/<?php echo base64_encode($where['perid'])?>/courseid/<?php echo base64_encode($where['courseid'])?>/veces/<?php echo '2'?>/escid1/<?php echo base64_encode($this->escid1)?>/subid1/<?php echo base64_encode($this->subid1)?>" class="btn btn-success" ><span class="glyphicon glyphicon-print "></span> Imprimir</a>
			</div>
			<table class='table table-hover'>
				<tr class='info'>
					<th class='text-center'>#</th>
					<th class='text-center'>DNI</th>
					<th class='text-center'>Código</th>
					<th class='text-center'>Apellidos y Nombres</th>
					<th class='text-center'>Veces Llevadas</th>
				</tr>
			<?php
			$co=1;
			foreach ($data as $key => $students) {
		 		$vecess=$students['veces'];
		 		if($vecess=='2'){	?>
			 		<tr>
			 			<td class='text-center'><?php echo $co?></td>
			 			<td class='text-center'><?php echo $students['pid']?></td>
			 			<td class='text-center'><?php echo $students['uid']?></td>
			 			<td><?php echo $students['full_name']?></td>
			 			<td class='text-center'><?php echo $students['veces']?></td>
			 		</tr>
			 		<?php
			 		$co++;
		 		}
		 	}
			
			?>
			</table>
		</div>
	<?php
	for ($i=3; $i <= $vfinal; $i++) { 	?>
		<div class="tab-pane fade" id='<?php echo $i?>'>		
	  		<div class="col-md-2 pull-right" style="margin-bottom:5px">
				<a href="/report/customreport/printregistrationquantityrepeatstudents/eid/<?php echo base64_encode($where['eid'])?>/oid/<?php echo base64_encode($where['oid'])?>/escid/<?php echo base64_encode($where['escid'])?>/subid/<?php echo base64_encode($where['subid'])?>/curid/<?php echo base64_encode($where['curid'])?>/perid/<?php echo base64_encode($where['perid'])?>/courseid/<?php echo base64_encode($where['courseid'])?>/veces/<?php echo $i?>/escid1/<?php echo base64_encode($this->escid1)?>/subid1/<?php echo base64_encode($this->subid1)?>" class="btn btn-success" ><span class="glyphicon glyphicon-print "></span> Imprimir</a>
			</div>
			<table class='table table-hover'>
				<tr class='info'>
					<th class='text-center'>#</th>
					<th class='text-center'>DNI</th>
					<th class='text-center'>Código</th>
					<th class='text-center'>Apellidos y Nombres</th>
					<th class='text-center'>Veces Llevadas</th>
				</tr>
			<?php
			$co=1;
			foreach ($data as $key => $students) {
		 		$vecess=$students['veces'];
		 		if($vecess==$i){	
		 		?>
			 		<tr>
			 			<td class='text-center'><?php echo $co?></td>
			 			<td class='text-center'><?php echo $students['pid']?></td>
			 			<td class='text-center'><?php echo $students['uid']?></td>
			 			<td><?php echo $students['full_name']?></td>
			 			<td class='text-center'><?php echo $students['veces']?></td>
			 		</tr>
			 		<?php
			 		$co++;
		 		}
		 	}
			?>
			</table>
		</div>
	<?php	
	}
	?>	
	</div>
<?php	
}
else{	?>
<hr>
<div class="row text-center">
	<div class="alert alert-activa col-md-4 col-md-offset-4">
		<h4><span class="text-info glyphicon glyphicon-info-sign"></span><b class="text-muted"> No se encontraron registros</b></h4>
	</div>	
</div>
<?php
}
?>
<script type="text/javascript">
	$('#myReport a').on('click',function (e) {
	  	e.preventDefault()
	  	$(this).tab('show')
	});
</script>