<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list-alt"></span> GENERAR EGRESADOS');?>
<?php $this->placeholder('Btnnav')->append('<a href="/admin" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
</br>
<table class="table">
	<tr>
		<th>Facultad:</th>
		<td>
			<select id="facid" class="form-control">
				<?php 
				if ($this->faculty) { ?>
					<option value="">- Seleccione Facultad -</option>
					<?php 
					foreach ($this->faculty as $faculty) { ?>
						<option value="<?php echo $faculty['facid']?>"><?php echo $faculty['name']?></option>
					<?php	
					}
				}?>
			</select>
		</td>
		<th>Escuela:</th>
		<td>
			<select id="escid" class="form-control">
				<option>- Seleccione Escuela -</option>
			</select>
		</td>
		<td>
			<a id="generargraduated" href="#" class="btn btn-success"><span class="glyphicon glyphicon-download-alt"></span> Generar</a>
		</td>
	</tr>
</table>
<div id="loadgraduated" class='alert alert-info col-md-6 col-md-offset-3'></div>

<script type="text/javascript">
$("#loadgraduated").hide();
$("#facid").change(function(){
	var facid = $(this).val();
	if (!facid) {
		alert("Seleccione una Facultad.");
		return false;
	};
	$("#escid").load("/admin/generategraduated/school/facid/"+facid);
});

$("#generargraduated").click(function(){
	var tmp = $("#escid").val();
	if (!tmp) {
		alert("Seleccione una Escuela.");
		return false;
	};
	var tmpp = tmp.split('--');
	var escid = tmpp[0];
	var subid = tmpp[1];
	$("#loadgraduated").show();
	$("#loadgraduated").html("<div><center><h3><img src='/img/spinner.gif'> Generando...</h3></center></div>");
	$("#loadgraduated").load("/admin/generategraduated/generated/escid/"+escid+"/subid/"+subid);
});
</script>