<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> ASIGNATURAS A CARGO PERIODO - '.$this->perid.'');?>
<?php 
    
    $this->placeholder('Btnnav')->append('
    <div class="btn-group">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
            Seleccione Periodo <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu"> '
            .$this->periods.
          '</ul>
    </div>');
    
  $c=0;

    $perid_tmp = null;
    $btn_alp = false;
    if (substr($this->perid,2) == 'A') {
        $perid_tmp = str_replace('A', 'D', $this->perid);
        $btn_alp = true;
    }elseif (substr($this->perid,2)=='B') {
        $perid_tmp = str_replace('B', 'E', $this->perid);
        $btn_alp = true;

    }


  if ($this->faculty){
  foreach ($this->faculty as $number) {
    $c++;
    $c;
    $fname=$number['name'];

?>

<div id="coursesPrincipal">
<div class="panel-group" id="accordion">
    <div class="panel panel-primary">
        <div class="panel-heading ">
            <h4 class="panel-title ">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $c?>"
                style="font-size: 18px;">
                    <b>FACULTAD <?php echo strtoupper($fname)?></b>                         
                </a>
            </h4>
        </div>
        <div id="collapse<?php echo $c?>" class="panel-collapse collapse in">
            <div class="panel-body" >
                <div class='row'>
                    <div class='col-md-11 col-md-offset-1'>
                        <div class='row'>

                            <?php 
                                $f=0;
                                foreach ($this->data as $courses) {
                                $f++;

                                $u_="";
                                $urlAsist ="/".base64_encode('escid')."/".base64_encode($courses['escid'])."/".base64_encode('subid')."/".base64_encode($courses['subid'])."/".base64_encode('courseid')."/".base64_encode($courses['courseid'])."/".base64_encode('turno')."/".base64_encode($courses['turno'])."/".base64_encode('perid')."/".base64_encode($courses['perid'])."/".base64_encode('curid')."/".base64_encode($courses['curid'])."/".base64_encode('state')."/".base64_encode($courses['state_record']);

                                $url_aplazado ="/".base64_encode('escid')."/".base64_encode($courses['escid'])."/".base64_encode('subid')."/".base64_encode($courses['subid'])."/".base64_encode('courseid')."/".base64_encode($courses['courseid'])."/".base64_encode('turno')."/".base64_encode($courses['turno'])."/".base64_encode('perid')."/".base64_encode($perid_tmp)."/".base64_encode('curid')."/".base64_encode($courses['curid']);

                                $u_ = $courses['curid'].$courses['courseid'].$courses['turno'];
                                $urlcampus = "http://campus.undac.edu.pe/courses/$u_/index.php";
                                $partial = $this->partial;

                                                     
                                if ($number['facid']==$courses['facid']) { ?>
                                    <div class='col-md-3 cont-coruse' >

                                        <div class="alert alert-title-course">
                                          <h4 class='name-course'><?php echo $courses['courseid']." - ".$courses['name_course']." - Turno ".$courses['turno']?></h4>
                                        </div>
                                        <?php if (
                                                    $courses['closure_syllabus'] == 'C' && ($courses['closure_record_n']=='P' || $courses['closure_record_n']=='C')

                                                ) {?>
                                                <img src="/img/closure_.png" class='img-closure-course'>
                                        <?php }else{?>
                                            <h1 class='span-course'><span class='glyphicon glyphicon-book'></span></h1>
                                        <?php }?>

                                        <h6 >Curricula - <?php echo $courses['curid']?></h6>

                                        <!--option cursos-->

                                        <a id="silabo<?php echo $courses['courseid'] ?>" class="btn btn-primary btn-sm btn-group-course btn-couses-sil <?php echo ($courses['closure_record_n']=='P' || $courses['closure_record_n']=='C')? 'margin-top-btn':''?>" href="/syllabus/syllabus/index/escid/<?php echo base64_encode($courses['escid'])?>/curid/<?php echo base64_encode($courses['curid'])?>/courseid/<?php echo base64_encode($courses['courseid'])?>/turno/<?php echo base64_encode($courses['turno'])?>/subid/<?php echo base64_encode($courses['subid'])?>/perid/<?php echo base64_encode($courses['perid'])?>"data-toggle="tooltip" title="Registro del Sílabo" >Sílabo</a>
                                        
                                        <a href="/controlactivity/index/index/courseid/<?php echo base64_encode($courses['courseid']) ?>/curid/<?php echo base64_encode($courses['curid']) ?>/turno/<?php echo base64_encode($courses['turno']) ?>/perid/<?php echo base64_encode($courses['perid']) ?>/escid/<?php echo base64_encode($courses['escid']) ?>/subid/<?php echo base64_encode($courses['subid']) ?>" class="btn btn-primary btn-sm">Control de Actividad</a>
                                        
                                       <?php if($courses['closure_record_n']=='P' || $courses['closure_record_n']=='C'){?>
                                            <?php switch ($courses['type_rate']) {
                                            case 'O': ?>
                                                <div class="btn-group">
                                                  <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                                    Registro de Notas <span class="caret"></span>
                                                  </button>
                                                  <ul class="dropdown-menu">
                                                    <li> <a  href="/docente/fillnotes/target<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Registrar las Notas">Notas 1er Parcial</a></li>
                                                    <li> <a  href="/docente/fillnotes/target<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode('2')?>" data-toggle="tooltip" title="Registrar las Notas">Notas 2do Parcial</a></li>
                                                  </ul>
                                                </div>
                                        <?php       break;
                                            case 'C': ?>
                                                
                                                <div class="btn-group">
                                                  <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                                    Registro de Notas <span class="caret"></span>
                                                  </button>
                                                  <ul class="dropdown-menu">
                                                    <li> <a href="/docente/fillnotes/competition<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Registrar las Notas">Notas 1er Parcial</a></li>
                                                    <li> <a  href="/docente/fillnotes/competition<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode('2')?>" data-toggle="tooltip" title="Registrar las Notas">Notas 2do Parcial</a></li>
                                                  </ul>
                                                </div>
                                                <div class="btn-group">
                                                  <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                                    Porcentaje <span class="caret"></span>
                                                  </button>
                                                  <ul class="dropdown-menu">
                                                    <li><a <?php echo ($courses['state']=='P' || $courses['state']=='C' )? 'disabled':''?> class="load-persentage" href="/docente/fillnotes/persentagecompetition<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Asignar Porsentage" >Porcentaje 1er Parcial</a></li>
                                                    <li><a <?php echo ($courses['state']=='P' || $courses['state']=='C' )? 'disabled':''?> class="load-persentage" href="/docente/fillnotes/persentagecompetition<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode('2')?>" data-toggle="tooltip" title="Asignar Porsentage" >Porcentaje 2do Parcial</a></li>
                                                  </ul>
                                                </div>



                                        <?php        break;
                                            default: ?>
                                                <div class="alert alert-danger">Tipo de Curso no Asignado</div>
                                         <?php       break;
                                        }?>

                                       
                                    <div class="btn-group">
                                          <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                            Asistencia <span class="caret"></span>
                                          </button>
                                          <ul class="dropdown-menu">
                                            <li> <a  href="/assistance/student/index<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Llenado de Asistencia" > Asistencia 1er Parcial</a></li>
                                            <li>  <a href="/assistance/student/index<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode('2')?>" data-toggle="tooltip" title="Llenado de Asistencia" > Asistencia 2do Parcial</a></li>
                                          </ul>
                                    </div>
                                        
                                        <?php }else{?>
                                             <?php switch ($courses['type_rate']) {
                                            case 'O': ?>
                                                <a id="notas<?php echo $courses['courseid'] ?>" class="btn btn-primary btn-sm btn-group-course" href="/docente/fillnotes/target<?php echo $urlAsist ?>/<?php echo base64_encode('partial') ?>/<?php echo base64_encode($partial)?>" data-toggle="tooltip" title="Registrar las Notas">Notas </a>
                                        <?php       break;
                                            case 'C': ?>
                                                <a class="btn btn-primary btn-sm btn-group-course " href="/docente/fillnotes/competition<?php echo $urlAsist ?>/<?php echo base64_encode('partial') ?>/<?php echo base64_encode($partial)?>" data-toggle="tooltip" title="Registrar las Notas">Notas</a>

                                                <buttom <?php echo ($courses['state']=='P' || $courses['state']=='C' )? 'disabled':''?>class="btn btn-primary btn-sm btn-group-course load-persentage" href="/docente/fillnotes/persentagecompetition<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Asignar Porsentage" >Asignar % </buttom>                               
                                        <?php        break;
                                            default: ?>
                                                <div class="alert alert-danger">Tipo de Curso no Asignado</div>
                                         <?php       break;
                                        }?>

                                        <a class="btn btn-primary btn-sm btn-group-course" href="/assistance/student/index<?php echo $urlAsist."/".base64_encode('partial')."/".base64_encode($partial)?>" data-toggle="tooltip" title="Llenado de Asistencia" > Asistencia </a>

                                        <?php }?>



                                        <?php if ($courses['closure_record_n']=='C' && $btn_alp) {?>
                                            <a class="btn btn-primary btn-sm btn-group-course btn-fill-deferred" href="/register/deferred/index<?php echo $url_aplazado?>" data-toggle="tooltip" title="Llenado de Asistencia" > Aplazados</a>
                                        <?php }?>
                                        



                                        <!--prosentaje de llenado de notas-->
                                        <h5 class='text-persentage-couser'>Llenado de Notas. 
                                            <?php echo round($courses['persetage_notes'])?>%
                                            <?php if ($courses['persetage_notes']== 50 || $courses['persetage_notes']== 100) {?>
                                                <span class='glyphicon glyphicon-ok-sign text-success'></span>
                                            <?php }else{ ?>
                                                <span class='glyphicon glyphicon-info-sign text-danger'></span>
                                            <?php }?>
                                        </h5>
                                        <div class="progress-course progress progress-striped active">
                                          <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $courses['persetage_notes']?>%">
                                          </div>
                                        </div>

                                        <h5 class='text-persentage-couser'>Llenado de Asistencia. <?php echo round($courses['persetage_assit'])?>%
                                            <?php if ($courses['persetage_assit']== 50 || $courses['persetage_assit']== 100) {?>
                                                <span class='glyphicon glyphicon-ok-sign text-success'></span>
                                            <?php }else{ ?>
                                                <span class='glyphicon glyphicon-info-sign text-danger'></span>
                                            <?php }?>
                                        </h5>
                                        <div class="progress-course progress progress-striped active">
                                          <div class="progress-bar progress-bar-danger"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $courses['persetage_assit']?>%">
                                          </div>
                                        </div>
                                        <h5 class='text-persentage-couser'>Llenado de Sílabo. 
                                            <?php if ($courses['closure_syllabus']=='C') {?>
                                                <span class='glyphicon glyphicon-ok-sign text-success'></span>
                                            <?php }else{?>
                                                <span class='glyphicon glyphicon-info-sign text-danger'></span>
                                            <?php }?></h5>
                                        
                                    </div>

                                <?php }
                            }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
</div>
</div>
<?php 
}
}else{ ?>
    <div class='col-md-12 cont-font-not-register'>
        <h1 class='span-not-register'>
            <span class='glyphicon glyphicon-exclamation-sign'></span>
        </h1>
        <h3 class='text-not-register'>Ningún Curso Asignados</h3>
    </div>
<?php } ?>

<div id='sil'></div>



<div class="modal fade" id="modal-persentage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div><!-- /.modal -->

<script>
    $('#otherPicture').fadeOut('slow');

    $(".load-persentage").click(function(){
        var $url = $(this).attr('href');
        $("#modal-persentage").modal('show');
        $.get($url,function($data){
            $("#modal-persentage").html($data);
        });
        
        return false;
    });



    $(function () {
        $('[data-toggle=tooltip]').tooltip({ placement: 'bottom' }) ;
    });
</script>
