<h2 class="text-info"><center>Asignaturas</center></h2>
<?php 
  $c=0;
  foreach ($this->faculty as $number) {
   	$c++;
   	$fname=$number['name'];
   	
?>
<div class="panel-group" id="accordion">
  <div class="panel">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        	<h5><?php echo $fname?></h5>    	
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <?php
        	$b=0;
        	foreach ($this->data as $courses) {
        		$b++;
        		$where['eid']=$courses['eid'];
        		$where['oid']=$courses['oid'];
        		$where['curid']=$courses['curid'];
        		$where['escid']=$courses['escid'];
        		$where['subid']=$courses['subid'];
        		$where['courseid']=$courses['courseid'];
        		$list= new Api_Model_DbTable_Course();
	        	$course=$list->_getOne($where);
        		if ($number['facid']==$courses['facid']) { ?>
        		<div>
        			<div>
        				<?php 
        				echo $course['courseid'];
        				echo $course['name'];
        				?>
        			</div>
        			<div class="col-xs-6"><?php ?></div>
           		</div>
        <?php			
        		}
        	}

        ?>

      </div>
    </div>
  </div>
</div>
<?php 
} 
?>
