<table class="table table-striped table-bordered table-condensed">
    <tr>
        <td colspan="5"><h4><center>TASAS MATRICULA</center></h4></td>
    </tr>
    <tr>
        <td>Año</td>
        <td>Periodo</td>
        <td>Operaciones</td>   
    </tr>
    <tr>
        <td>
            <select id="lanios" name="lanios" class="input-small">
             <?php 
            $anio= date('Y');
            $i=0;
            for($i = ($anio+1);$i>=1991;$i--)
            {
                if ($anio==$i) $t = "selected";
                else $t="";?>            
            <option value="<?php echo $i?>" <?php echo $t?>><?php echo $i?></option>
                <?php }?>
            </select>
        </td>

        <td>
            <select id="periodo_c" name="periodo" class="input-large">
            <option value="">Primero seleccione un año</option>
            </select>
        </td>  

        <td ><center>
        <a href="#" class="btn btn-primary " id="nuevo">Nueva Tasa</a>
        <a href="#" class="btn btn-info " id="llamar">Ver Detalle</a>
       </center></td>
       </tr>
    
</table>
    <div id="detalle"></div>
<script>
    $("#periodo_c").load("/admin/rateregister/lperiods/anio/"+<?php echo $anio?>);
    $("#lanios").change(function(){
    	var anio = $(this).val();
        var url1 = "/admin/rateregister/lperiods/anio/"+anio;
    	$("#periodo_c").load(url1);
    });

    $("#periodo_c").change(function(){
    	var periodo = $(this).val();
    	var xx=periodo.split(";--;");
    	var perid=xx[0];
    	var estado=xx[1];    
    });    
    
    $("#llamar").click(function(){      
    	var periodo = $("#periodo_c").val(); 
    	var xx=periodo.split(";--;");
    	var perid=xx[0];
    	var state=xx[1];
        if (perid=="") 
        	{
        	alert ("Debe de seleccionar un periodo");return false;
        	}
   		var url="/admin/rateregister/list/perid/"+perid+"/state/"+state;
    	$("#detalle").html("<img src='/img/spinner.gif' />Cargando....");
    	$("#detalle").load(url);
    });            
          
    $("#nuevo").click(function(){    
    	var periodo = $("#periodo_c").val(); 
    	var xx=periodo.split(";--;");
    	var perid=xx[0];
    	var state=xx[1];
    	if (perid=="")
    	{
    		alert ("Debe de seleccionar un periodo");return false;
    	}
    	if (state=="C")
    	{
    	alert ("Usted no puede crear una tasa nueva escoja periodo Activo");return false;}
    	location.href="/admin/rateregister/new/perid/"+perid+"/state/"+state;                
    });
</script>





