<?php
 $state = $this->state;
 $perid = $this->perid;
?>
<?php
if ($this->tasas)
{
?>
<div class='col-md-10 col-md-offset-1'>
    <h3 class='text-primary'><b><center>TASAS - <?php echo $perid?></center></b></h3>
</div></br>
<table class="table table-hover">
    <thead>
        <tr>
            <th class='text-center'>#</th>
            <th class='text-center'>Nombre de la Tasa</th>
            <th class='text-center'>Código de Tasa</th>
            <th class='text-center'>Tasa Normal</th>
            <th class='text-center'>Tasa Incremento N°1 (%)</th>
            <th class='text-center'>Tasa Incremento N°2 (%)</th>
            <?php if ($state=='A' || $state=='I'){?>
            <th class='text-center'>Modificar</th>
            <th class='text-center'>Eliminar</th>
             <?php } ?>
        </tr>
    </thead>
<?php
    $i=1;
   foreach ($this->tasas as $tasa)    
    { ?>
    <body>
        <tr>
            <td class='text-center'> <?php print $i?> </td>
            <td> <?php print $tasa['name']?> </td>
            <td class='text-center'> <?php print $tasa['ratid']?> </td>
            <td class='text-center'> <?php print $tasa['t_normal']?> </td>
            <td class='text-center'> <?php print $tasa['t_incremento1']?> </td>
            <td class='text-center'> <?php print $tasa['t_incremento2']?> </td>
            <?php if ($state=='A' || $state=='I'){?>
            <td class='text-center'> <a href="/admin/rateregister/update/ratid/<?php print $tasa['ratid']?>/perid/<?php print $tasa['perid']?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
            <td class='text-center'> <a href="/admin/rateregister/delete/ratid/<?php print $tasa['ratid']?>/perid/<?php print $tasa['perid']?>"onclick="return confirm('Esta Seguro que desea eliminar el registro?');"><span class="glyphicon glyphicon-trash"></span></a></td>
            <?php } ?>
        </tr>
    </body>  
       <?php
        $i++;
    }
    ?>
</table>
<?php    
}
else{
    ?>
    <div class='col-md-8 col-md-offset-2 alert alert-info'>
        <h4><b><center> ¡ NO EXISTE DATOS !</center></b></h4>
        <h5><center>Crea nuevas tasas para este periodo <?php echo $perid?></center></h5>
    </div></br>
<?php   
}
?>

