<?php 
$perid=$this->perid;
$state=$this->state;
?>
 <form id="frmtasas" name="frmtasas" action="/admin/rateregister/new/" method="POST" enctype="application/x-www-form-urlencoded">

    <table class="table  table-striped table-bordered table-condensed">
        <tr>
            <td>     
                <label class="control-label">Periodo:</label>
                <div class="controls"><?php print $this->fm->perid->setvalue($perid);?></div>                                 
                <label class="control-label">Codigo tasa matricula (#):</label>
                <div class="controls"><?php print $this->fm->ratid;?></div>
                 
                <label class="control-label">Nombre Tasa:</label>
                <div class="controls"><?php print $this->fm->name;?></div>
               
                <label class="control-label">Nombre Resolucion:</label>
                <div class="controls"><?php print $this->fm->resolucion;?></div>
                
                <label class="control-label">Tasa Normal:</label>
                <div class="controls"><?php print $this->fm->t_normal;?></div>

                <label class="control-label">Fecha Inicio:</label>
                <div class="controls"><?php print  $this->fm->f_ini_tn;?></div>
                
                <label class="control-label">Fecha Final:</label>
                <div class="controls"><?php print $this->fm->f_fin_tnd;?></div>
            </td> 
            <td>
                <label class="control-label">Incremento 1:  (%)</label>
                <div class="controls"><?php print $this->fm->v_t_incremento1;?></div>
                   
                <label class="control-label">Monto a Pagar 1:</label>
                <div class="controls"><?php print $this->fm->t_incremento1?></div>
                    
                <label class="control-label">Fecha Final 1:</label>
                <div class="controls"><?php print $this->fm->f_fin_ti1;?></div>                    
             </td>
            <td>     
                <label class="control-label">Incremento 2:  (%) </label>
                <div class="controls"><?php print $this->fm->v_t_incremento2;?></div>
                  
                <label class="control-label">Monto a Pagar 2:</label>
                <div class="controls"><?php print $this->fm->t_incremento2;?></div>
                   
                <label class="control-label">Fecha Final 2:</label>
                <div class="controls"><?php print $this->fm->f_fin_ti2;?></div>
                    
            </td>
            <td>        
                <label class="control-label">Incremento 3: (%)</label>
                <div class="controls"><?php print $this->fm->v_t_incremento3;?></div>
                 
                <label class="control-label">Monto a Pagar 3:</label>
                <div class="controls"><?php print $this->fm->t_incremento3;?></div>
                  
                <label class="control-label">Fecha Final 3:</label>
                <div class="controls"><?php print $this->fm->f_fin_ti3;?></div>   
            </td> 
        </tr>       
    </table>
    <input type="hidden" name ="perid" value="<?php echo $this->perid?>">
    <input type="hidden" name ="state" value="<?php echo $this->state?>">
</form>

<div class="modal-footer">
    <button class="btn btn-success" id="nuevot"><span class="glyphicon glyphicon-save"></span> Guardar</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>    
</div>

<script>
    $(function() {
        $( "#f_ini_tn" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });

    $(function() {
        $( "#f_fin_tnd" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });

    $(function() {
        $( "#f_fin_ti1" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });

    $(function() {
        $( "#f_fin_ti2" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });

    $(function() {
        $( "#f_fin_ti3" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });


    $("#ratid").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#ratid").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#t_normal").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
        $(".msg").html("solo escriba numero");
        $("#t_normal").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#v_t_incremento1").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#v_t_incremento1").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#v_t_incremento2").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#v_t_incremento2").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#v_t_incremento3").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#v_t_incremento3").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#t_incremento1").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#t_incremento1").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#t_incremento2").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#t_incremento2").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#t_incremento3").keyup(function(){
        var v = $(this).val();
        if (isNaN(v)){
            $(".msg").html("solo escriba numero");
            $("#t_incremento3").val("");
        }
        else{
            $(".msg").html("");}
    });

    $("#nuevot").click(function(){
        $.ajax({
            url: $("#frmtasas").attr('action'),
            type: 'POST',
            data:$("#frmtasas").serialize(),
            success: function (data){
                $("#nueva_tasa").html(data); 
            }
        });
    });

    var valor="<?php echo $this->valor?>";
    if (valor==1) {
        $('#myModal').modal('hide');
        $('#myModal').on('hidden.bs.modal', function (e) {
            var perid="<?php echo $this->perid ?>";
            var state="<?php echo $this->state?>";
            var url="/admin/rateregister/list/perid/"+perid+"/state/"+state;
            $("#detalle").html("<img src='/img/spinner.gif' />Cargando....");
            $("#detalle").load(url);
        });
    };
</script>