
<div id="carga">
    <form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <table class="table span9 table-striped table-bordered ">
    <tr>
        <td class="span9"><h4 class="titulopagina">MODIFICAR TASA DE MATRICULA</h4></td>
        <td ><center>
        <a style="float:left"><?php echo $this->form->guardar?></a>
        <a style="float:left" href="/admin/rateregister" class="btn btn-danger " id="nuevo"><i class="icon-refresh icon-white"></i>Cancelar</a>
       </center></td>  
    </tr>
</table>
    <table class="table span9 table-striped table-bordered table-condensed">
             
                    <tbody>
                        <tr>
                            <div class="control-group">
                            <td>
                                <div class="control-group">
                                <label class="control-label">Codigo:</label>
                                <div class="controls"><?php print $this->form->ratid;?></div>
                                </div>
                               
                                
                                <div class="control-group">
                                <label class="control-label">Tasa Normal:</label>
                                <div class="controls"><?php print $this->form->t_normal;?></div>
                                </div>
                                  <div class="control-group">
                                <label class="control-label">Incremento 1: (%)</label>
                                <div class="controls"><?php print $this->form->v_t_incremento1;?></div>
                                </div>

                                 <div class="control-group">
                                <label class="control-label">Incremento 2: (%)</label>
                                <div class="controls"><?php print $this->form->v_t_incremento2;?></div>
                                </div>

                                 <div class="control-group">
                                <label class="control-label">Incremento 3: (%)</label>
                                <div class="controls"><?php print $this->form->v_t_incremento3;?></div>
                                </div>
                               
                                
                           </td> 
                           <td>
                                  <div class="control-group">
                                <label class="control-label">Nombre Tasa::</label>
                                <div class="controls"><?php print $this->form->name;?></div>
                                </div>

                                 <div class="control-group">
                                <label class="control-label">Fecha Inicio:</label>
                                <div class="controls"><?php print  $this->form->f_ini_tn;?></div>
                                </div>

                              
                                <div class="control-group">
                                <label class="control-label">Monto a Pagar 1:</label>
                                <div class="controls"><?php print $this->form->t_incremento1?></div>
                                </div>

                                 <div class="control-group">
                                <label class="control-label">Monto a Pagar 2:</label>
                                <div class="controls"><?php print $this->form->t_incremento2;?></div>
                                </div>

                                <div class="control-group">
                                <label class="control-label">Monto a Pagar 3:</label>
                                <div class="controls"><?php print $this->form->t_incremento3;?></div>
                                </div>
                                 
                            </td>
                            <td>
                                <div class="control-group">
                                <label class="control-label">Nombre Resolucion:</label>
                                <div class="controls"><?php print $this->form->resolucion;?></div>
                                </div>

                                <div class="control-group">
                                <label class="control-label">Fecha Final:</label>
                                <div class="controls"><?php print $this->form->f_fin_tnd;?></div>
                                </div>

                                <div class="control-group">
                                <label class="control-label">Fecha Final 1:</label>
                                <div class="controls"><?php print $this->form->f_fin_ti1;?></div>
                                </div>

                               
                               
                                 <div class="control-group">
                                <label class="control-label">Fecha Final 2:</label>
                                <div class="controls"><?php print $this->form->f_fin_ti2;?></div>
                                </div>

                                 <div class="control-group">
                                <label class="control-label">Fecha Final 3:</label>
                                <div class="controls"><?php print $this->form->f_fin_ti3;?></div>
                                </div> 
                               </td>
                             
                           </tr>                            
                        </tr>
                    </tbody>
                </table>
    </form>
</div>
<head>


    <script type="text/javascript" src="/js/jquery/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-ui-1.8.23.custom.min.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery.ui.datepicker-es.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/jquery/redmond/jquery-ui-1.8.23.custom.css">   
</head>
<script type="text/javascript">
    $('.dropdown-toggle').dropdown()
</script>
<script>
    $(function() {
        $( "#f_ini_tn" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });
</script>
<script>
    $(function() {
        $( "#f_fin_tnd" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });
</script>
<script>
    $(function() {
        $( "#f_fin_ti1" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });
</script>
<script>
    $(function() {
        $( "#f_fin_ti2" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });
</script>
<script>
    $(function() {
        $( "#f_fin_ti3" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy/mm/dd',
        });
    });
</script>
  
<script>
        $("#t_normal").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#t_normal").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#v_t_incremento1").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#v_t_incremento1").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#v_t_incremento2").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#v_t_incremento2").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#v_t_incremento3").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#v_t_incremento3").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#t_incremento1").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#t_incremento1").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#t_incremento2").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#t_incremento2").val("");
        }
        else
        {
        $(".msg").html("");}
        });

        $("#t_incremento3").keyup(function(){
        var v = $(this).val();
        if (isNaN(v))
        {
        $(".msg").html("solo escriba numero");
        $("#t_incremento3").val("");
        }
        else
        {
        $(".msg").html("");}
        });



 </script>