<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-tasks"></span> Avance Academico');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<hr class="featurette-divider">
<div class="row">
	<div class="col-md-3 col-md-offset-2">
		<h5 class="text-muted">Escuela </h5>
		<select id="school" class="form-control">
			<?php
			if ($this->speciality) { ?>
				<option value="">Seleccione Escuela</option>
				<?php if (condition): ?>
					<option value="<?php echo $this->allSchool?>">Todas las Especialidades</option>
				<?php endif ?>
				<?php 
				foreach ($this->speciality as $speciality) { 
					if ($this->director) $selected = ($this->escid == $speciality['escid'])? "selected": "";
					?>
					<option value="<?php echo $speciality['escid'].'--'.$speciality['subid']?>" <?php echo $selected?>><?php echo $speciality['name']?></option>
					<?php
				}
			}else{ ?>
				<option value="">- No hay Escuelas Disponibles -</option>
			<?php
			}?>
		</select>
	</div>
	<div class="col-md-1">
		<h5 class="text-muted">Año</h5>
		<select class="form-control" name="Anio" id="anio">
			<?php $anio = date(Y);
	 		for ($i=$anio; $i >=1993 ; $i--) :?> 
	 			<option value="<?php echo $i?>"><?php echo $i ?></option>
	 		<?php endfor?>
	 	</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-muted">Periodo</h5>
		<select class="form-control" name="Periodo" id="period"></select>
	</div>
	<div class="col-md-3">
		<h5><br></h5>
		<a id="showData" href="#data" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></a>
	</div>

</div>
<br>
<hr class="featurette-diveder">
<br>
<div id="data"></div>

<script>
	var vardiv = $('#school').val().split('--');
	var escid = vardiv[0];
	var subid = vardiv[1];

	$('#school').change(function(){
		$('#school option:selected').each(function(){
			vardiv = $(this).val().split('--');
			escid = vardiv[0];
			subid = vardiv[1];
		});
	});


	//Filtras  Periodos por años -------------------
	var anio = $('#anio').val();
	$.get('/report/periods/listperiods/anio/'+anio, function(data){
	$('#period').html(data);
	});
	$('#anio').change(function(){
		$('#anio option:selected').each(function(){
			anio = $(this).val();
			$.get('/report/periods/listperiods/anio/'+anio, function(data){
				$('#period').html(data);
			});
		});
	});
	//------------------------------------------------


	var perid = $('#period').val();
	$('#period').change(function(){
		$('#period option:selected').each(function(){
			perid = $(this).val();
		});
	});

	$('#showData').click(function(){
		$('#data').html("<br><center><img src='/img/spinner.gif' alt='Cargando...' /></center>");
		$('#data').load("/report/periods/listteacher/perid/" + perid + "/escid/" + escid + "/subid/" + subid);
	});
</script>

<!--<div>
	<table class="table table-condensed">
		<tr>
			<th>Escuela: </th>
			<td>
				
			</td>
			<th>Periodo: </th>
			<td>
				<select id="perid" class="form-control">
					<?php 
					if ($this->periods) { ?>
						<option value="">- Seleccione Periodo -</option>
						<?php
						foreach ($this->periods as $periods) { 
							if($this->perid) $select = ($this->perid == $periods['perid'])? "selected": "";?>
							<option value="<?php echo $periods['perid']?>" <?php echo $select?>><?php echo $periods['perid'].' | '.$periods['name']?></option>
							<?php
						}
					}else{ ?>
						<option value="">- No hay Periodos Disponibles -</option>
						<?php
					}?>
				</select>
			</td>
			<td>
				<a id="searching" href="#" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Buscar</a>
			</td>
		</tr>
	</table>
</div>
<div id="loaddata"></div>

<script type="text/javascript">
	$("#searching").click(function(){
		var tmp = $("#escid").val();
		var perid = $("#perid").val();
		if (tmp == "") {
			alert("Seleccione una Escuela."); 
			return false;
		};
		if (perid == "") {
			alert("Seleccione un Periodo."); 
			return false;
		};
		var tmpp = tmp.split('--');
		var escid = tmpp[0];
		var subid = tmpp[1];
		var url = "/report/periods/listteacher/perid/"+perid+"/escid/"+escid+"/subid/"+subid;
		$("#loaddata").html("<img src='/img/spinner.gif'>Cargando...");
		$("#loaddata").load(url);
	});
</script>-->