<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-time"></span> Avance Académico');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<?php 
	$anio = date('Y');
 ?>

<link rel="stylesheet" href="/css/avanceAcademico.css">

<input type="hidden" id="periodCurrent" value="<?php echo $this->dataVista['period'] ?>">
<div class="avanceAcademicoHeader">
	<p class="text-muted parrafoHeader"><span class="glyphicon glyphicon-info-sign"></span> Puede filtrar otros periodos si lo desea:</p>
	
	<div class="select selectAnio">
		<select name="anio" id="selectAnio" class="form-control">
			<?php for ($i=$anio; $i >= 1990; $i--) { ?>
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
			<?php } ?>
		</select>
	</div>
	
	<div class="select selectPeriod">
		<select name="period" id="selectPeriod" class="form-control">
		</select>
	</div>
</div>
<hr>
<div id="avanceAcademico_DataDocentes" class="avanceAcademicoDocentes">

</div>
<script>
	$(function(){
		var periodCurrent = $('#periodCurrent').val();
		var anio          = $('#selectAnio').val();
		var period        = '';

		$('#selectPeriod')	.html('<option>Cargando...</option>')
							.load('/report/periods/listperiods/anio/' + anio, function(){
								$(this).val(periodCurrent);
							});

		$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
											.load('/report/periods/listteacher/data/' + periodCurrent);
		
		$('#selectAnio').on('change', function(){
			$('#avanceAcademico_DataDocentes').html('');
			anio = $(this).val();

			$('#selectPeriod')	.html('<option>Cargando...</option>')
								.load('/report/periods/listperiods/anio/' + anio, function(){
									period = $(this).val();
									$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
																		.load('/report/periods/listteacher/data/' + period);
								});
		});

		$('#selectPeriod').on('change', function(){
			period = $(this).val();
			$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
												.load('/report/periods/listteacher/data/' + period);
		});
	});
</script>
