<?php $env = getenv('APPLICATION_ENV') ?>

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-time"></span> Avance Académico');?>
<?php $this->placeholder('Btnnav')->append('<a href="/"><span class="glyphicon glyphicon-circle-arrow-left "></span></a>');?>
<?php 
	$anio = date('Y');
	$dataVista = $this->dataVista;
 ?>


<input type="hidden" id="rol" value="<?php echo $dataVista['rid'] ?>">
<input type="hidden" id="escid" value="<?php echo $dataVista['dataEscid'] ?>">
<input type="hidden" id="periodCurrent" value="<?php echo base64_encode($dataVista['period']) ?>">

<section class="container">
	
<div class="avanceAcademicoHeader">
	<p class="text-muted parrafoHeader"><span class="glyphicon glyphicon-info-sign"></span> Puede filtrar otros periodos si lo desea:</p>
	
	<div class="select selectAnio">
		<select name="anio" id="selectAnio" class="form-control">
			<?php for ($i=$anio; $i >= 1990; $i--) { ?>
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
			<?php } ?>
		</select>
	</div>
	
	<div class="select selectPeriod">
		<select name="period" id="selectPeriod" class="form-control">
		</select>
	</div>
</div>
	
<?php if ($dataVista['rid'] == 'RF' or $dataVista['rid'] == 'DF'): ?>
	<div class="registroFacultadSide">
		<p class="rfObO parrafoRF"><span class="glyphicon glyphicon-info-sign"></span> Seleccione una escuela para empezar:</p>
		<div class="rfObO selectSchool">
			<select name="school" id="selectSchool" class="form-control">
				<option value="">Escuela</option>
				<?php foreach ($this->dataSchool as $c => $school): ?>
					<option value="<?php echo base64_encode($school['escid'].'|'.$school['subid']) ?>"><?php echo $school['name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>
	</div>
<?php elseif ($dataVista['rid'] == 'RC' or $dataVista['rid'] == 'ES' or $dataVista['rid'] == 'CU' or $dataVista['rid'] == 'VA'): ?>
	<div class="registroCentralSide">
		<p class="rcObO parrafoRC"><span class="glyphicon glyphicon-info-sign"></span> Seleccione facultad y escuela:</p>
		<div class="rcObO select selectFaculty">
			<select name="faculty" id="selectFaculty" class="form-control">
				<option value="">Facultad</option>
				<?php foreach ($this->dataFaculty as $c => $faculty): ?>
					<option value="<?php echo base64_encode($faculty['facid']) ?>"><?php echo $faculty['name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="rcObO select selectSchool">
			<select name="school" id="selectSchool" class="form-control">
				<option value="">Escuela</option>
				<option value="">Seleccione una facultad primero</option>
			</select>
		</div>
	</div>
<?php endif ?>
<div id="avanceAcademico_DataDocentes" class="avanceAcademicoDocentes">

</div>
</section>
<script>
	$(function(){
		var rid       = $('#rol').val();
		var period    = $('#periodCurrent').val();
		var anio      = $('#selectAnio').val();
		var facid     = '';
		var dataEscid = $('#escid').val();
		var data      = period + '-' + dataEscid;


		$('#selectPeriod')	.html('<option>Cargando...</option>')
							.load('/report/periods/listperiods/anio/' + anio, function(){
								$(this).val(period);
							});

		$('#selectAnio').on('change', function(){
			$('#avanceAcademico_DataDocentes').html('');
			anio = $(this).val();

			$('#selectPeriod')	.html('<option>Cargando...</option>')
								.load('/report/periods/listperiods/anio/' + anio, function(){
									period = $(this).val();
									if (dataEscid) {
									data = period + '-' + dataEscid;
										$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
																			.load('/report/periods/listteacher/data/' + data);
									}
								});
		});

		$('#selectPeriod').on('change', function(){
			period = $(this).val();
			if (dataEscid) {
				data = period + '-' + dataEscid;
				$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
													.load('/report/periods/listteacher/data/' + data);
			}
		});

		if (rid == 'DR') {
			$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
												.load('/report/periods/listteacher/data/' + data);
		}else if (rid == 'RF' || rid === 'DF'){
			$('#selectSchool').on('change', function(){
				dataEscid = $(this).val();
				if (dataEscid) {
					data = period + '-' + dataEscid;
					$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
														.load('/report/periods/listteacher/data/' + data);
				}else{
					$('#avanceAcademico_DataDocentes').html('');
				}
			});
		}else if (rid == 'RC' || rid == 'ES' || rid == 'CU' || rid == 'VA'){
			$('#selectFaculty').on('change', function(){
				facid = $(this).val();
				$('#avanceAcademico_DataDocentes')	.html('');
				$('#selectSchool')	.html('<option value="">Cargando...</option')
									.load('/default/global/listschools/id/' + facid);
			});

			$('#selectSchool').on('change', function(){
				dataEscid = $(this).val();
				if (dataEscid) {
					data = period + '-' + dataEscid;
					$('#avanceAcademico_DataDocentes')	.html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>')
														.load('/report/periods/listteacher/data/' + data);
				}else{
					$('#avanceAcademico_DataDocentes').html('');
				}
			});
		}
	});
</script>
