
<?php
if ($this->data_teacher) { ?>
	<div class="row">
		<div class="col-md-1 col-md-offset-1">
			<h5 class="text-muted">Leyenda</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> No existe</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-info"><span class="glyphicon glyphicon-print"></span> Impresiones</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-info"><span class="glyphicon glyphicon-calendar"></span> Horario</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-success"><span class="glyphicon glyphicon-ok"></span> Completo</h5>
		</div>
		<div class="col-md-2">
			<h5 class="text-danger"><span class="glyphicon glyphicon-remove"></span> Incompleto</h5>
		</div>
	</div>
<hr>

	<div class="row">
		<div class="col-md-4 col-md-offset-1">
		<br>
			 <div class="input-group">
                <input id="searchData" type="text" onkeyup="javascript:this.value=this.value.toUpperCase();" class="form-control" placeholder="Filtrar por Docente | Apellido o Codigo	">
                <span class="input-group-btn">
                <a class="btn btn-success" id="searchButton" title="Filtrar :D" href="##"><span class="glyphicon glyphicon-filter"></span></a>
                </span>
            </div>
		</div>
		<div class="col-md-1 col-md-offset-5">
			<h2><a title="Imprimir Reporte" href="/report/periods/print/perid/<?php echo base64_encode($this->perid)?>/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>" class="text-info"><span class="glyphicon glyphicon-print"></span></a></h2>
		</div>
	</div>

	<br>
	<ul id="teachers">
	<?php $c = 0;
	foreach ($this->data_teacher as $teachers) { ?>
		<li style="list-style : none;">
			<div class="row">
				<div class="col-md-1">
					<?php $br = 0;
					foreach ($teachers['courses'] as $t){ 
						$br++;
					}
					for ($i=0; $i < $br; $i++) {?> 
					 	<br>
					 <?php }?>
					<h3 class="text-muted text-right"><strong><?php echo $c + 1 ?> </strong></h3>
				</div>
				<div class="col-md-3">
					
					<?php $br = 0;
					foreach ($teachers['courses'] as $t){ 
						$br++;
					}
					for ($i=0; $i < $br-1; $i++) {?> 
					 	<br>
					 <?php }
					 ?>
					<blockquote>
					<h5 class="text-right"><?php echo $teachers['full_name'] ?></h5>
					<h5 class="text-right"><span class="text-muted">Codigo </span><?php echo $teachers['courses'][0]['uid'] ?></h5>
					<h3 class="text-right">
						<a class="text-info" title="Horario de Docente" href="##"><span class="glyphicon glyphicon-calendar"></span></a>
						<?php if ($this->reportAcademic[$c][0]['state'] == 'C'): 
						?>
							<a href="/docente/listacademicreport/print/pid/<?php echo base64_encode($teachers['courses'][0]['pid'])?>/uid/<?php echo base64_encode($teachers['courses'][0]['uid'])?>/escid/<?php echo base64_encode($teachers['courses'][0]['escid'])?>/subid/<?php echo base64_encode($this->data['subid'])?>/perid/<?php echo base64_encode($this->data['perid'])?>/nombre/<?php echo base64_encode($teachers['full_name'])?>" title="Imprimir Informe Academico" class="glyphicon glyphicon-print text-info"></a>
						<?php else: ?>
							<span title="No tiene Informe" class="glyphicon glyphicon-ban-circle text-danger"></span>
						<?php endif ?>
					</h3>
					</blockquote>
				</div>
				<div class="col-md-8">
					<blockquote>
					<?php $escuela = ''; ?>
					<table class="table table-hover">
					<?php foreach ($teachers['courses'] as $courses): ?>
						<?php if ($courses['escid'] != $escuela): ?>
							<?php 
							$escuela = $courses['escid']; 
						if ($this->TE == 'Si') {?>
						<tr>
							<th class="success" colspan="7"><span class="text-muted">Escuela </span><?php echo $courses['name_school'] ?></th>
						</tr>
						<?php }?>
						<tr class="active">
							<th class="col-md-5">Asignaturas</th>
							<th class="text-center">Turno</th>
							<th class="text-center">Silabo</th>
							<th class="text-center">Cierre Silabus</th>
							<th class="text-center">1° Parcial</th>
							<th class="text-center">2° Parcial</th>
							<th class="text-center">Cierre Acta</th>
						</tr>
						<?php endif ?>
						<tr>
							<td>
								<?php echo $courses['courseid']." - ".$courses['name']?>
							</td>
							<td>
								<center><?php echo $courses['turno']?></center>
							</td>
							<td>
								<center>
									<?php
									if ($courses['state_syllabus'] == 'C') { ?>
										<a href="/syllabus/print/index/courseid/<?php echo base64_encode($courses['courseid'])?>/turno/<?php echo base64_encode($courses['turno'])?>/curid/<?php echo base64_encode($courses['curid'])?>/escid/<?php echo base64_encode($courses['escid'])?>/subid/<?php echo base64_encode($courses['subid'])?>/perid/<?php echo base64_encode($courses['perid'])?>" rel="tooltip" title="Imprimir Silabo." class="text-success"><span class="glyphicon glyphicon-print"></span></a>
										<?php
									}else{ ?>
										<span title="No relleno el silabo" class="glyphicon glyphicon-ban-circle text-danger"></span>
									<?php
									}?>
								</center>
							</td>
							<td class="text-center">
								<?php 
							        $f_=$courses['create_syllabus'];
   									$tf =split(" ",$f_);
    								echo $tf[0];
								?>
							</td>
							<td class="text-center">
								<?php if ($courses['state_course'] == "P" || $courses['state_course'] == "C" || $courses['state_course'] == "S") {?>
									<span title="Completo el Parcial" class="glyphicon glyphicon-ok text-success"></span>
								<?php }else {?>
									<span title="No Completa el Parcial" class="glyphicon glyphicon-remove text-danger"></span>
								<?php } ?>
							</td>
							<td class="text-center">
								<?php if ($courses['state_course'] == "P" || $courses['state_course'] == "C" || $courses['state_course'] == "S") {?>
									<span title="Completo el Parcial" class="glyphicon glyphicon-ok text-success"></span>
								<?php }else {?>
									<span title="No Completa el Parcial" class="glyphicon glyphicon-remove text-danger"></span>
								<?php } ?>
							</td>
							<td>
								<center>
									<?php 
									echo $courses['closure_date_course'];
									?>
								</center>
							</td>
						</tr>
					<?php endforeach ?>
					</table>
					</blockquote>
				</div>
			</div>
			<hr class="featurette-divider">
		</li>
		<?php
		$c++;
	}?>
	</ul>	
	<!--</table>-->
<?php
}else{ ?>
	<div class='col-md-12 cont-font-not-register'>
        <h1 class='span-not-register'>
            <span class='glyphicon glyphicon-exclamation-sign'></span>
        </h1>
        <h3 class='text-not-register'>No existen <span class="text-danger">registros</h3>
    </div>
<?php
}?>



<script>
	$('a, span').hover(function(){
		$(this).tooltip('toggle');
	});

    $('#searchData').keyup(function(){

        var searchText = $(this).val();

        $('#teachers > li').each(function(){

            var currentLiText = $(this).text(),
                showCurrentLi = currentLiText.indexOf(searchText) !== -1;

            $(this).toggle(showCurrentLi);

        });     
    });
</script>