<?php
if ($this->data_teacher) { ?>
	<div style="margin-bottom: 10px">
		<center>
			<a href="/report/periods/print/perid/<?php echo base64_encode($this->perid)?>/escid/<?php echo base64_encode($this->escid)?>/subid/<?php echo base64_encode($this->subid)?>" class="btn btn-primary"><span class="glyphicon glyphicon-print"></span> Imprimir</a>
		</center>
	</div>
	<table class="table table-condensed table-hover">
		<tr>
			<th>#</th>
			<th>Docente</th>
			<th>Asignaturas</th>
			<th>Turno</th>
			<th>Silabo</th>
			<th>F.Cierre Silabus</th>
			<th>1° Parcial</th>
			<th>2° Parcial</th>
			<th >F.Cierre Acta</th>
			<th>Horario</th>
		</tr>
		<?php 
		$c=1;
		foreach ($this->data_teacher as $teachers) { ?>
			<tr>
				<td rowspan="<?php echo $teachers['cantidad_courses']+2?>"><?php echo $c?></td>
				<td rowspan="<?php echo $teachers['cantidad_courses']+2?>">
					<?php echo $teachers['uid']." - ".$teachers['full_name']?>
				</td>
				<td colspan="7"></td>
				<td rowspan="<?php echo $teachers['cantidad_courses']+2?>">
					<center>
						<a href="#" rel="tooltip" title="Ver Horario del Docente."><span class="glyphicon glyphicon-calendar"></span></a>
					</center>
				</td>
			</tr>
			<?php
				foreach ($teachers['courses'] as $courses) { 
					?>
					<tr>
						<td>
							<?php echo $courses['courseid']." - ".$courses['name']?>
						</td>
						<td>
							<center><?php echo $courses['turno']?></center>
						</td>
						<td>
							<center>
								<?php
								if ($courses['state_syllabus'] == 'C') { ?>
									<a href="/syllabus/print/index/courseid/<?php echo base64_encode($courses['courseid'])?>/turno/<?php echo base64_encode($courses['turno'])?>/curid/<?php echo base64_encode($courses['curid'])?>/escid/<?php echo base64_encode($courses['escid'])?>/subid/<?php echo base64_encode($courses['subid'])?>/perid/<?php echo base64_encode($courses['perid'])?>" rel="tooltip" title="Imprimir Silabo." style="color: green"><span class="glyphicon glyphicon-print"></span></a>
									<?php
								}else{ ?>
									<a href="#" rel="tooltip" title="El Silabo no se Encuentra Registrado." style="color: red"><span class="glyphicon glyphicon-ban-circle"></span></a>
								<?php
								}?>
							</center>
						</td>
							<td>
								<?php 
								        $f_=$courses['create_syllabus'];
       									$tf =split(" ",$f_);
        								echo $tf[0];
								?>
						</td>
						<td>
							<center>
								<?php 
								if ($courses['state_course'] == "P" || $courses['state_course'] == "C" || $courses['state_course'] == "S") $icon="ok";
								else $icon = "remove"; ?>
									<span class="glyphicon glyphicon-<?php echo $icon?>"></span>
							</center>
						</td>
						<td>
							<center>
								<?php 
								if ($courses['state_course']=="C" || $courses['state_course'] == "S") $icon="ok";
								else $icon = "remove"; ?>
									<span class="glyphicon glyphicon-<?php echo $icon?>"></span>
							</center>
						</td>
						<td>
							<center>
								<?php 
								echo $courses['closure_date_course'];
								?>
									
							</center>
						</td>
					</tr>
					<?php
				}?>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			<?php
			$c++;
		}?>
	</table>
<?php
}else{ ?>
	<div class="alert alert-info">
		<b>INFORMACIÓN: </b>No se registraron datos de esta Escuela.
	</div>
<?php
}?>

<script type="text/javascript">
$('a').tooltip();
</script>