 <?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start();    
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align: center; margin-bottom:3%"><b>REPORTE AVANCE ACADÉMICO - PERIODO <?php echo strtoupper($this->perid)?></b></div>    
<?php
if ($this->data_teacher) { ?>
	<table style="width:100%; font-size: 9px;" border="1">
		<tr>
			<th>#</th>
			<th>Docente</th>
			<th>Asignaturas</th>
			<th>Turno</th>
			<th>Silabo</th>
			<th>F.C. Silabus</th>
			<th>1° Parcial</th>
			<th>2° Parcial</th>
			<th>F.C. Acta</th>
		</tr>
		<?php 
		$c=1;
		foreach ($this->data_teacher as $teachers) { ?>
			<tr>
				<td rowspan="<?php echo $teachers['cantidad_courses']+2?>"><?php echo $c?></td>
				<td rowspan="<?php echo $teachers['cantidad_courses']+2?>">
					<?php echo $teachers['full_name']." - ".$teachers['uid']?>
				</td>
				<td colspan="7"></td>
			</tr>
			<?php
				foreach ($teachers['courses'] as $courses) { 
					?>
					<tr>
						<td>
							<?php echo $courses['courseid']." - ".$courses['name']?>
						</td>
						<td>
							<center><?php echo $courses['turno']?></center>
						</td>
						<td>
							<center>
								<?php
								if ($courses['state_syllabus'] == 'C') echo "SI";
								else echo "NO"; ?>
							</center>
						</td>
						<td>
								<?php 
								$f_=$courses['create_syllabus'];
       									$tf =split(" ",$f_);
        								echo $tf[0];
								?>
						</td>
						<td>
							<center>
								<?php 
								if ($courses['state_course'] == "P" || $courses['state_course'] == "C" || $courses['state_course'] == "S") echo "SI";
								else echo "NO"; ?>
							</center>
						</td>
						<td>
							<center>
								<?php 
								if ($courses['state_course']=="C" || $courses['state_course'] == "S") echo "SI";
								else echo "NO"; ?>
							</center>
						</td>
						<td>
							<center>
								<?php 
								echo $courses['closure_date_course'];
								?>
									
							</center>
						</td>
					</tr>

					<?php
				}?>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			<?php
			$c++;
		}?>
	</table>
<?php
} 
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,10,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.05,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');
    ob_end_clean();

    $mpdf -> WriteHTML($html);
  	$mpdf->Output('Escuela-'.$this->escid.'.pdf','D');
    // $mpdf->Output(); 
  
?>