<div class="col-md-12">
<center>
<h3><span class="glyphicon glyphicon-stats"></span> | Notas Periodo <?php echo $this->perid?></h3>
</center></div>
<?php if($this->courses){ ?>
<div class="col-sm-12">
	<?php 
	$c=0;
	foreach ($this->courses as $courses) {
	$course_ = $courses[0];
	$u_ = $course_['curid'].$course_['courseid'].$this->notes[$c]['turno'];
	$urlcampus = "http://campus.undac.edu.pe/courses/$u_/index.php";
	?>
	<div class="panel panel-primary" style="padding: 0px;">
		<div class="panel-heading" style="padding-top: 5px;padding-bottom: 0px;">
			<p style="font-size:14px"><b><?php echo $courses[0]['courseid']?> | <?php echo $courses[0]['name'];?></b>
			| <a href="<?php echo $urlcampus?>" class="btn " style="color: #fff;" target="black">
			Ir Campus</a></p>
			
		</div>
		<div class="panel-body" style="padding: 0px;">
			<table class="table table-bordered" style="margin: 0px">
				<tr>
					<td class="col-sm-1" style="padding: 0px; margin:0px">
						<table  style="padding: 0px; margin:0px">
							<tr>
								<td>Semestre</td>							
								<th><?php echo $courses[0]['semid']?></th>
							</tr>
							<tr>
								<td>Turno </td>
								<th><?php echo $this->notes[$c]['turno']?></th>
							</tr>
							<tr>
								<td>Creditos </td>
								<th><?php echo $courses[0]['credits']?></th>
							</tr>
						</table>
					</td>
					<td class="col-sm-5" style="margin: 0px; padding: 0px">
						<table class="table table-bordered table-striped" style="margin: 0px; padding: 0px">
							<tr>
								<?php 
								$numcol=9;
								$numuni = 1;
								$txtuni = " Parcial ";
								$tipo_=$this->typerate[$c][0]['type_rate'];
								if ($tipo_=="C"){
									$numcol=8;
									$numuni = 2; 
									$txtuni = " Unidad";
								}
								?>
								<?php for ($ii = 1; $ii <=$numuni;$ii++) {
									?>
									<th class="center" colspan="<?php echo $numcol/$numuni?>">Notas <?php echo $ii ." ".$txtuni?> </th>
									<?php 
								}?>
								<?php if ($tipo_=="O"){?>
								<th class="center"></th>
								<?php }?>
							</tr>
							<tr >
								<?php 
								for($rcr = 1;$rcr<=$numcol;$rcr++){
								$txtmp=$rcr;
								if ($tipo_ =="C"){
									if ($rcr>4) $txtmp = $rcr- 4 ;
									if($rcr==4 || $rcr==8) $txtmp ="Pr.";
								}
								?>
								<td class="center"><?php echo $txtmp?></td>
								<?php 
								}
								?>
								<?php if ($tipo_=="O"){?>
								<td class="center">Pr.</td>
								<?php }?>
							</tr>
							<tr class="success ">
								<?php for($rcr = 1;$rcr<=$numcol;$rcr++){
									$index="nota".$rcr."_i";
									$nota_ = $this->notes[$c][$index];
								?>
								<th class="center <?php echo ($nota_<11 && $nota_<>"")?"danger":"";?>">
									<?php echo $this->notes[$c][$index];?>
								</th>
								<?php } ?>
								<?php 
								if ($tipo_=="O"){ 
								$prom_ = trim($this->notes[$c]['promedio1']);
								?>
								<th class="center <?php echo ($prom_<11)?"danger":""?>">
									<?php echo $prom_;?>
								 </th>
								 <?php  } ?>
							</tr>
						</table>		
					</td>
					<td class="col-sm-5" style="margin: 0px; padding: 0px">
						<table class="table table-bordered table-striped" style="margin: 0px; padding: 0px">
							<tr>
								<?php 
								$suma=($tipo_=="O")?1:2;
								for ($ii = 1; $ii <=$numuni;$ii++) {
									?>
									<th class="center" colspan="<?php echo ($numcol/$numuni)?>">Notas <?php echo $ii+$suma ." ".$txtuni?> </th>
									<?php 
								}?>
								<?php if ($tipo_=="O"){?>
								<th class="center"></th>
								<?php }?>
							</tr>
							<tr>
								<?php 
								for($rcr = 1;$rcr<=$numcol;$rcr++){
								$txtmp=$rcr;
								if ($tipo_ =="C"){
									if ($rcr>4) $txtmp = $rcr- 4 ;
									if($rcr==4 || $rcr==8) $txtmp ="Pr.";
								}
								?>
								<td class="center"><?php echo $txtmp?></td>
								<?php 
								}
								?>
								<?php if ($tipo_=="O"){?>
								<td class="center">Pr.</td>
								<?php }?>
							</tr>
							<tr class="success center">
								<?php for($rcr = 1;$rcr<=$numcol;$rcr++){
									$index="nota".$rcr."_ii";
									$nota_ = $this->notes[$c][$index];
								?>
								<th class="center <?php echo ($nota_<11 && $nota_<>"")?"danger":"";?>">
									<?php echo $this->notes[$c][$index];?>
								</th>
								<?php } ?>
								<?php if ($tipo_=="O"){ 
								$prom = $this->notes[$c]['promedio2'];
								?>
								<th class="center <?php echo ($prom<11)?"danger":""?>">
									<?php echo $prom;?>
								 </th>
								 <?php  } ?>
							</tr>
						
						</table>
					</td>
					<?php 
					$final = $this->notes[$c]['notafinal'];
					?>
					<th class="col-sm-1 center <?php echo ($final<11)?"danger":"success"?>" style="margin: 0px; padding: 0px" >
					<P>PROMEDIO FINAL <br><br>
					<span class="label label-<?php echo ($final<11)?"danger":"success"?>" 
						style="font-size: 22px">
						<?php echo $final?>
					</span>
					</P>
					</th>
				</tr>
			</table>
		</div>
	</div>
	<?php 
	$c++;
	}
	?>
				
<?php }else{?>
	<br><br>
	<h4 align="center">Aun no se Matricula a este Periodo</h4>
<?php }?>
</div>




