

<div style="display: block; height: 120px; width: 100%; ">
  <div class="img-thumbnail pull-left">
    <img src="/fotos/<?php echo $this->person['uid']?>.jpg" title="">
  </div>
  <div class="pull-left" style="padding: 8px;">
    <p style="font-size: 18px"><b><?php echo $this->person[0]['last_name0']." ".$this->person[0]['last_name1']." ".$this->person[0]['first_name'];?></b><br>
    Código <b><?php echo $this->person['uid']?></b><br>
    Facultad de <?php echo $this->facesp[0]['nomfac']." Escuela de ".$this->facesp[0]['nomesc']?></p>
   </div>

</div>

<div style="display: block; width: 100%; ">
	<ul class="nav nav-tabs" id="profileTab">
		<li class="active"><a href="#info" id="btnmaininfo"><h5>Datos Personales</h5></a></li>
		<li><a href="#tab" id="btnmainsignin"><h5>Accesos</h5></a></li>
		<li><a class="hidden"></a></li>
	</ul>
	<div class="tab-content" style="margin: 0px; padding: 0px; min-height: 500px;" >
		<div class="tab-pane active" id="info" ></div>
		<div class="tab-pane" id="tab">hhhhh	</div>
		</div>
	</div>
</div>


<script>
  $(function () {
    $("#info").load("/profile/privateadm/adminfo/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");

    //$("#signin").load("/profile/privateadm/admlog/");
    $("#tab").load("/profile/privateadm/access/");

    $('#profileTab a').click(function (e) {
      e.preventDefault()
        $(this).tab('show')
    });

      
    $("#btnmainsignin").click(function(){
      $("#info").load("/profile/privateadm/adnminfo/eid/<?php echo $this->person['eid']?>/oid/<?php echo $this->person['oid']?>/pid/<?php echo $this->person[0]['pid']?>/uid/<?php echo $this->person['uid']?>/escid/<?php echo $this->facesp[0]['escid']?>/subid/<?php echo $this->facesp[0]['subid']?>");
      $("#masinfoTab a:last").tab('show')
    });

    $("#btnmaininfo").click(function(){
    $("#tab").load("/profile/privateadm/access/");
    //$("#signin").html("<h1>dddd</h1>")
       //$("#masinfosignTab a:last").tab('show')
    });

  });
</script>
