<div class="panel panel-default">
	<form id="form">
	<input type="hidden" name="eid" value="<?php echo $this->dataPerson['eid'] ?>">
	<input type="hidden" name="pid" value="<?php echo $this->dataPerson['pid'] ?>">

	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h3 class="text-muted"><span class="glyphicon glyphicon-user"></span> Información <span class="text-info">Principal</span></h3>
			</div>
			<div class="col-md-2">
				<?php echo $this->form->submit ?>
			</div>
			<div class="col-md-2">
				<br>
				<a href="##" class="form-control btn btn-default" id="backeditBtn">Volver</a>
			</div>
		</div>
		<hr>
		<div class="row text-muted">
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-4">
						<p>DNI</p>
						<?php echo $this->form->numdoc ?>
					</div>
					<div class="col-md-4">
						<p>Sexo</p>
						<?php echo $this->form->sex ?>
					</div>
					<div class="col-md-4">
						<p>Estado Civil</p>
						<?php echo $this->form->civil ?>
					</div>
				</div><br>

				<p class="text-center">Fecha de Nacimiento</p>
				<div class="row">
					<div class="col-sm-4">
						<?php echo $this->form->year?>
					</div>
					<div class="col-sm-4">
						<?php echo $this->form->month?>
					</div>
					<div class="col-sm-4">
						<?php echo $this->form->day?>
					</div>
				</div><br>
				
				<div class="row">
					<div class="col-md-6">
						<p>País</p>
						<?php echo $this->form->country?>
					</div>
					<div class="col-md-6">
						<p>Departamento</p>
						<?php echo $this->form->country_s?>
					</div>
				</div><br>
		
				<p>Email Personal</p>
				<?php echo $this->form->mail_work ?>
			</div>
			<div class="col-md-6">
				

				<div class="row">
					<div class="col-sm-6">
						<p>Provincia</p>
						<?php echo $this->form->country_p?>
					</div>
					<div class="col-sm-6">
						<p>Distríto</p>
						<?php echo $this->form->country_d?>
					</div>
				</div><br>

				<div class="row">
					<div class="col-md-6">
						<p>Telefono Fijo</p>
						<?php echo $this->form->phone ?>
					</div>
					<div class="col-md-6">
						<p>Celular</p>
						<?php echo $this->form->cellular ?>
					</div>
				</div><br>

				<p>Email de Trabajo</p>
				<?php echo $this->form->mail_work ?>
			</div>
		</div>
		<br>
	</div>
	</form>
</div>

<script>
	/*$("#form").submit(function(){
		var formData = new FormData($(this)[0]);
		$.ajax({
			type : 'post',
			url  : '/profile/privateadm/saveinfo',
			data : formData,
			contentType : false,
			processData : false,
			success : function(data){
				alert(data);
			}
		})
		return false;
	})*/
	

	$('#backeditBtn').click(function(){
    	$('#editData').fadeOut('fast', function(){
      		$('#admData').fadeIn('fast');
    	});
  	})
   
</script>