<div class="panel panel-default">
	<form action="/profile/privateadm/admeditinfo" method="post" id="form">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h3 class="text-muted"><span class="glyphicon glyphicon-user"></span> Información <span class="text-info">Principal</span></h3>
			</div>
			<div class="col-md-2">
				<?php echo $this->form->submit ?>
			</div>
			<div class="col-md-2">
				<br>
				<a href="##" class="form-control btn btn-default" id="backeditBtn">Volver</a>
			</div>
		</div>
		<hr>
		<div class="row text-muted">
			<div class="col-md-6">
				<p>DNI</p>
				<?php echo $this->form->numdoc ?><br>

				<div class="row">
					<div class="col-md-6">
						<p>Sexo</p>
						<?php echo $this->form->sex ?>
					</div>
					<div class="col-md-6">
						<p>Estado Civil</p>
						<?php echo $this->form->civil ?>
					</div>
				</div><br>

				<p>Email Personal</p>
				<?php echo $this->form->mail_work ?>
			</div>
			<div class="col-md-6">
				<p>Fecha de Nacimiento</p>
				<div class="row">
					<div class="col-sm-4">
						<?php echo $this->form->year?>
					</div>
					<div class="col-sm-4">
						<?php echo $this->form->month?>
					</div>
					<div class="col-sm-4">
						<?php echo $this->form->day?>
					</div>
				</div><br>
				<div class="row">
					<div class="col-md-6">
						<p>Telefono Fijo</p>
						<?php echo $this->form->phone ?>
					</div>
					<div class="col-md-6">
						<p>Celular</p>
						<?php echo $this->form->cellular ?>
					</div>
				</div><br>

				<p>Email de Trabajo</p>
				<?php echo $this->form->mail_work ?>
			</div>
		</div>
		<br>
	</div>
	</form>
</div>

<script>
	/*$("#form").submit(function(){
		var formdata = new FormData($(this)[0]);
		$.ajax({
			type : 'post',
			url  : '/profile/privateadm/saveinfo',
			processData : false,
			success : function(data){
				alert(data);
			}
		})
	})*/
	

	$('#backeditBtn').click(function(){
    	$('#editData').fadeOut('fast', function(){
      		$('#admData').fadeIn('fast');
    	});
  	})
   
</script>