
<div class="panel panel-default">

	<form id="form">
	<input type="hidden" name="eid" value="<?php echo $this->dataPerson['eid'] ?>">
	<input type="hidden" name="pid" value="<?php echo $this->dataPerson['pid'] ?>">

	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h3 class="text-muted"><span class="glyphicon glyphicon-user"></span> Información <span class="text-info">Principal</span></h3>
			</div>
			<div class="col-md-2">
				<?php echo $this->form->submit ?>
			</div>
			<div class="col-md-2">
				<br>
				<a href="##" class="form-control btn btn-default" id="backeditBtn">Volver</a>
			</div>
		</div>
		<hr>
		<div id="alertsEmptyData" class="row hidden">
			<div class="col-md-12">
				<div class="alert alert-warning">
					<a href="##" class="close closeAlerts">&times;</a>
					<p><strong>Faltan Datos!</strong> Verifique que lleno todos los datos correctamente</p>
				</div>
			</div>
		</div>

		<div class="row text-muted">
			<div class="col-md-6">
				<div class="panel panel-default" style="padding:20px">
					<br>
					<p class="text-center"><strong>Datos Principales</strong></p>
					<div class="row">
						<div class="col-md-4">
							<p>DNI</p>
							<?php echo $this->form->numdoc ?>
						</div>
						<div class="col-md-4">
							<p>Sexo</p>
							<?php echo $this->form->sex ?>
						</div>
						<div class="col-md-4">
							<p>Estado Civil</p>
							<?php echo $this->form->civil ?>
						</div>
					</div><br>

					<p class="text-center"><strong>Fecha de Nacimiento</strong></p>
					<div class="row">
						<div class="col-sm-4">
							<?php echo $this->form->year?>
						</div>
						<div class="col-sm-4">
							<?php echo $this->form->month?>
						</div>
						<div class="col-sm-4">
							<?php echo $this->form->day?>
						</div>
					</div><br>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default" style="padding:20px">
					<br>
					
						<p class="text-center"><strong>Lugar Donde Radica</strong></p>
						<div class="row">
							<div class="col-sm-6">
								<p>País</p>
								<?php echo $this->form->country ?>
							</div>
							<div class="col-sm-6">
								<p>Departamento</p>
								<?php echo $this->form->country_s ?>
							</div>
						</div><br>

						<div class="row">
							<div class="col-sm-6">
								<p>Provincia</p>
								<?php echo $this->form->country_p ?>
							</div>
							<div class="col-sm-6">
								<p>Distríto</p>
								<?php echo $this->form->country_d ?>
							</div>
						</div><br>
					
				</div>
			</div>
	
			<div class="col-md-12">
				<div class="panel panel-default" style="padding:20px">
					<br>
					
						<p class="text-center"><strong>Información Adicional</strong></p>
						<div class="row">
							<div class="col-md-3">
								<p>Celular</p>
								<?php echo $this->form->cellular ?>
							</div>
							<div class="col-md-3">
								<p>Telefono Fijo</p>
								<?php echo $this->form->phone ?>
							</div>
							<div class="col-md-3">
								<p>Email Personal</p>
								<?php echo $this->form->mail_person ?>
							</div>
							<div class="col-md-3">
								<p>Email de Trabajo</p>
								<?php echo $this->form->mail_work ?>
							</div>
						</div>
					
					<br>
				</div>
			</div>

		</div>
	</div>
	</form>
</div>

<script>
	$('.closeAlerts').click(function(){
		$('#alertsEmptyData').addClass('hidden');
	})
	
	$("#country_s").attr('disabled','disabled');
	$("#country_p").attr('disabled','disabled');
	$("#country_d").attr('disabled','disabled');


	$("#country").change(function(){
  		$('#country_s').removeAttr('disabled');
	    var coid=$(this).val();
    	// var coid=$("#country").val();
    	var url="/profile/public/countrystate/coid/"+coid;
    	$("#country_s").load(url);
    });

    $("#country_s").change(function(){
    	$('#country_p').removeAttr('disabled');
	    var cosid=$(this).val();
    	// var coid=$("#country").val();
    	var url="/profile/public/countryprovince/cosid/"+cosid;
    	$("#country_p").load(url);
    });

 	$("#country_p").change(function(){
    	$('#country_d').removeAttr('disabled');
	    var proid=$(this).val();
    	// var coid=$("#country").val();
    	var url="/profile/public/countrydistrict/proid/"+proid;
    	$("#country_d").load(url);
    });

	$("#form").submit(function(){
		var formData = new FormData($(this)[0]);
		$.ajax({
			type : 'post',
			url  : '/profile/privateadm/saveinfo',
			data : formData,
			contentType : false,
			processData : false,
			success : function(data){
				if (data == 1) {
					$('#editData').html('');
					$('#admData').fadeIn('fast');
					$('#admData').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center>');
					$('#admData').load('/profile/privateadm/adminfo');
				}else{
					$('#alertsEmptyData').removeClass('hidden');
				};
			}
		})
		return false;
	})
	

	$('#backeditBtn').click(function(){
    	$('#editData').fadeOut('fast', function(){
      		$('#admData').fadeIn('fast');
    	});
  	})
   
</script>