<style>
   .dataPerson{
      font-size: 20px;
   }
</style>

<div class="row">
  <div  id="datastudent" class="col-md-12">

    <div class="panel panel-default dataPerson" style="background : #f5f5f5;">
         <div class="row">
            <div class="col-md-1 pull-right">
               <h2>
                  <a id="editInfo" href="##" class="text-muted" title="Editar Información"><span class="glyphicon glyphicon-pencil"></span></a>
               </h2>
            </div>
         </div>
         
         <div class="row">
            <br>
            <div class="col-md-4">
               <div class="row">
                  <div class="col-md-4">
                     <br>
                     <h1 class="pull-right"><span title="Información Principal" class="glyphicon glyphicon-user text-muted"></span></h1>
                  </div>
                  <div class="col-md-8">
                     <p class="text-muted"><small class="text-info">DNI </small><strong><?php echo $this->datos[3]['numdoc']?></strong></p>

                     <p class="text-muted"><small class="text-info">Fecha de Nacimiento </small><strong><?php echo date('d-m-Y', strtotime($this->datos[3]['birthday'])) ?></strong></p>

                     <p class="text-muted"><small class="text-info">Sexo </small><strong>
                        <?php if ($this->datos[3]['sex']=="M") {
                          echo "Masculino";
                        }else{
                          echo "Femenino";
                        }?>
                     </strong></p>

                     <p class="text-muted"><small class="text-info">Estado Civil </small><strong>
                        <?php if ($this->datos[3]['civil']=="S") {
                          if ($this->datos[3]['sex']=="M") {
                            echo "Soltero";
                          }else{
                            echo "Soltera";
                          }
                        }elseif ($this->datos[3]['civil']=="C"){
                          if ($this->datos[3]['sex']=="M") {
                            echo "Casado";
                          }else{
                            echo "Casada";
                          }
                        }elseif ($this->datos[3]['civil']=="D"){
                          if ($this->datos[3]['sex']=="M") {
                            echo "Divorciado";
                          }else{
                            echo "Divorciada";
                          }
                        }elseif ($this->datos[3]['civil']=="V"){
                          if ($this->datos[3]['sex']=="M") {
                            echo "Viudo";
                          }else{
                            echo "Viuda";
                          }
                        }elseif ($this->datos[3]['civil']=="E"){
                          echo "Conviviente";
                        }?>
                     </strong></p>
                  </div>
               </div>
            </div>

            <div class="col-md-4">
               <div class="row">
                  <div class="col-md-2">
                     <h2 class="pull-right"><span title="Teléfonos" class="glyphicon glyphicon-earphone text-muted"></span></h2><br>
                  </div>
                  <div class="col-md-10">
                     <p class="text-muted"><small class="text-info">Teléfono </small><strong><?php echo $this->datos[3]['phone']?></strong></p>
                     <p class="text-muted"><small class="text-info">Celular </small> <strong><?php echo $this->datos[3]['cellular']?></strong></p>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-2">
                     <h2 class="pull-right"><span title="Correos" class="text-muted">@</span></h2>
                  </div>
                  <div class="col-md-10">
                     <p class="text-muted"><small class="text-info">e-Mail Personal </small><strong><?php echo $this->datos[3]['mail_person']?></strong></p>
                     <p class="text-muted"><small class="text-info">e-Mail de Trabajo </small> <strong><?php echo $this->datos[3]['mail_work']?></strong></p>
                  </div>
               </div>
            </div>
            <div class="col-md-4">
               <div class="col-md-2">
                  <br>
                  <h1 class="pull-right"><span title="Lugar Donde Radica" class="text-muted glyphicon glyphicon-map-marker"></span></h1>
               </div>
               <div class="col-md-10">
                  <p class="text-muted"><small class="text-info">País </small><strong><?php echo $this->datosUbicacion['pais'] ?></strong></p>
                  <p class="text-muted"><small class="text-info">Departamento </small> <strong><?php echo $this->datosUbicacion['departamento'] ?></strong></p>
                  <p class="text-muted"><small class="text-info">Provincia </small> <strong><?php echo $this->datosUbicacion['provincia'] ?></strong></p>
                  <p class="text-muted"><small class="text-info">Distrito </small> <strong><?php echo $this->datosUbicacion['distrito'] ?></strong></p>
               </div>
            </div>
         </div>
         <br><br>
    </div>
  </div><!-- div col 12 -->
</div>


<script>
  $('#editInfo').click(function(){
    $('#admData').fadeOut('fast', function(){
      $('#editData').load('/profile/privateadm/admeditinfo');
      $('#editData').fadeIn('slow');
    });
  });

  $('span').hover(function(){
      $(this).tooltip('toggle');
  })
</script>