<?php $dataStudent = $this->dataStudent ?>
<div class="container panel panel-info">
    <div class="row">
        <div class="col-md-9 col-md-offset-1">
            <h3 class="text-muted">
            <span class="glyphicon glyphicon glyphicon-link"></span> 
            Cambio de Contraseña
            </h3>    
        </div>
    </div>
    <div class="panel panel-warning">
        <br>
        <div class="row">
            <div class="col-xs-12">

                <form id="formpass" role="form" class="form-horizontal">
                    
                    
                    <div id="antiguo" class="form-group">
                        <label for="oldpass" class="control-label col-xs-4">Contraseña Actual:</label>
                        <div class="col-xs-4">
                            <input id="old" type="password" class="form-control" name="oldpass" value="" placeholder="Contraseña Actual">
                        </div>
                        <div class="col-xs-4"></div>
                    </div>

                    <div id="nueva" class="form-group">
                        <label for="newpass" class="control-label col-xs-4">Nueva contraseña:</label>
                        <div class="col-xs-4">
                            <input id="new" type="password" class="form-control" name="newpass" value="" placeholder="Nueva Contraseña">
                        </div>
                        <div class="col-xs-4"></div>
                    </div>

                    <div id="repnueva" class="form-group">
                        <label for="repnewpass" class="control-label col-xs-4">repita nueva contraseña:</label>
                        <div class="col-xs-4">
                            <input id="repnew" type="password" class="form-control" name="repnewpass" value="" placeholder="Repita Nueva Contraseña ">
                        </div>
                        <div class="col-xs-4"></div>
                    </div>
                    <br>
                    <br>
                    <input type="submit" class="btn btn-success col-xs-offset-5 col-xs-3" value="guardar">
                    <a id="btn-cancel" href="/docente" class="btn btn-danger col-xs-offset-1 col-xs-3">cancelar</a>
                    <br>
                    <br>
                    
                </form>
                
            </div>
        </div>

    </div>
</div>


<script>
    $(function(){

        $('#formpass').on('submit', function(e){
            e.preventDefault();
            var oldpass = $("#old").val();
            var newpass = $("#new").val();
            var repnewpass = $("#repnew").val();
                $('#repnueva').removeClass('has-error');
                $('#antiguo').removeClass('has-error');
                $('#nueva').removeClass('has-error');

                $.ajax({
                type : 'post',
                url : '/profile/privateadm/savepassword/',
                data : $('#formpass').serialize(),
                success: function(data){
                    if (data==1) {
                        alert("No Rellenó Completamente");
                        if (oldpass=="") {$("#old").focus();
                            $('#antiguo').addClass('has-error');
                        }
                        if (newpass=="") {$("#new").focus();
                            $('#nueva').addClass('has-error');
                        }
                        if (repnewpass=="") {$("#repnew").focus();
                            $('#repnueva').addClass('has-error');
                        }     
                   }else if (data==2) {
                        alert("Su contraseña es Incorrecta");
                        $("#new").val("");
                        $("#repnew").val("");
                        $("#old").val("");
                        $("#old").focus();
                        $('#antiguo').addClass('has-error')

                   }else if (data==3) {
                        alert("La nueva Contraseña no coinciden");
                        $("#new").val("");
                        $("#repnew").val("");
                        $("#old").val("");
                        
                   }else if (data==4) {
                        alert("su contraseña se cambio");
                        $("#new").val("");
                        $("#repnew").val("");
                        $("#old").val("");
                             
                   };

                   
                }
            });   
            
        });
    });
</script>
