<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 

$perid=$this->perid;
$course = $this->infocourse;
$students = $this->students;
$mpdf->mirrorMargins = 1;

$aprobados = 0;
$jalados = 0;
$retirados = 0;
?>
<style type="text/css">
address {
	margin-top: 10px;
	font-size: 8px;
	font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;

}
.table-bordered {
	width: 100%;
	font-size:10px;
	font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
	border: 1px solid #000;
	border-collapse: collapse;
	border-spacing: 0;
}
.text-name{
    border: 0.5px solid #2c242c;
    text-align: left;
}
.text-center{
	text-align: center;
	border: 0.5px solid #2c242c;
}
.header{
	background-color: #ebe9eb;
}
</style>
<table width="100%" style=" font-family: serif;  color: #000;">
    <tr >
        <td  style="font-size:10px; text-align:left;  " >
        <strong sytle="padding-right:5px">Curso: </strong><?php echo $course['courseid']." - ".$course['name']?>
        </td>
        
        <td style="text-align: right; font-size:10px;"><strong>Turno: </strong> <?php echo $this->turno?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Créditos: </strong><?php echo $course['credits'] ?></td>
    </tr>
    <tr >
        <td   style="text-align:left; font-size:10px;"><strong>Docente: </strong> <?php echo $this->lasname ?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Semestre: </strong><?php echo $course['semid'] ?></td>
        <td  style="text-align:right; font-size:10px;"><strong>Alumnos: </strong><?php echo count($students)?></td>
    </tr>
</table>
<div style="text-align:center; font-size:12px; margin-top:3%; margin-bottom:3%"><b>REGISTRO DE EVALUACION PERIODO <?php echo $this->perid?></b></div>
<table class='table table-bordered'>
    <thead>
    <tr>
        <th colspan="3" rowspan='2' class='text-center'></th>
        <th colspan="4" class='text-center'>UNIDAD I</th>
        <th colspan="4" class='text-center'>UNIDAD II</th>
        
        <?php if($this->partial == 2 && intval($this->units) == 3 ){?>
            <th colspan="4" class='text-center' >UNIDAD III</th>
            <th rowspan="3" class='text-center'>NF</th>
        <?php }if($this->partial == 2 && intval($this->units) != 3 ){?>
            <th colspan="4" class='text-center' >UNIDAD III</th>
            <th colspan="4" class='text-center' >UNIDAD IV</th>
            <th rowspan="3" class='text-center'>NF</th>
        <?php }?>
       
    </tr>
    <tr>
        <?php if($this->partial != 0){ 
                        
                    $porc["porc1"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc1_u1']:"N1";
                    $porc["porc2"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc2_u1']:"N2";
                    $porc["porc3"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc3_u1']:"N3";
                    $porc["porc4"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc1_u2']:"N1";
                    $porc["porc5"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc2_u2']:"N2";
                    $porc["porc6"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc3_u2']:"N3";
                    
                if($this->partial == 2){
                    $porc["porc7"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc1_u3']:"N1";
                    $porc["porc8"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc2_u3']:"N2";
                    $porc["porc9"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc3_u3']:"N3";
                    $porc["porc10"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc1_u4']:"N1";
                    $porc["porc11"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc2_u4']:"N2";
                    $porc["porc12"] = (isset($this->persetage) && count($this->persetage) > 0)?(string)$this->persetage['porc3_u4']:"N3";

                }
            }?>

        <th class='text-center' ><?php echo $porc['porc1']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc2']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc3']; ?>%</th>
        <th class='text-center success'>Prom 1</th>

        <th class='text-center' ><?php echo $porc['porc4']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc5']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc6']; ?>%</th>
        <th class='text-center success'>Prom 2</th>

        <?php if ($this->partial == 2 && intval($this->units) == 3  ) { ?>
        <th class='text-center' ><?php echo $porc['porc7']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc8']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc9']; ?>%</th>
        <th class='text-center success'>Prom 3</th>

        <?php }if ($this->partial == 2 && intval($this->units) != 3) { ?>
        <th class='text-center' ><?php echo $porc['porc7']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc8']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc9']; ?>%</th>
        <th class='text-center success'>Prom 3</th>

        <th class='text-center' ><?php echo $porc['porc10']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc11']; ?>%</th>
        <th class='text-center' ><?php echo $porc['porc12']; ?>%</th>
        <th class='text-center success'>Prom 4</th>
        <?php }?>
        
    </tr>
   	<tr class='header'>
   		<th style="width:20px;">#</th> 
        <th class="input-small">Codigo</th>
        <th class="input-xlarge" class='text-center'>Apellidos y Nombres</th>
        <th class='text-center'>C</th>
        <th class='text-center'>P</th>
        <th class='text-center'>A</th>
        <th class='text-center'>U1</th>
        <th class='text-center'>C</th>
        <th class='text-center'>P</th>
        <th class='text-center'>A</th>
        <th class='text-center'>U2</th>
        <?php if ($this->partial == 2 && intval($this->units) != 3 ) { ?>
            <th class='text-center'>C</th>
            <th class='text-center'>P</th>
            <th class='text-center'>A</th>
            <th class='text-center'>U3</th>
            <th class='text-center'>C</th>
            <th class='text-center'>P</th>
            <th class='text-center'>A</th>
            <th class='text-center'>U4</th>
        <?php }if ($this->partial == 2 && intval($this->units) == 3) { ?>
        	<th class='text-center'>C</th>
            <th class='text-center'>P</th>
            <th class='text-center'>A</th>
            <th class='text-center'>U3</th>
        <?php }?>
   	</tr>

    </thead>
    <tbody>
        <?php foreach ($this->students as $key => $student) {?>
            <tr>

                
                <?php if ($this->partial == 2) {
                    if (intval($student['notafinal']) >=  intval($course['min_note']) && intval($student['notafinal']) <=20) {$aprobados ++;}
                    if (intval($student['notafinal']) <  intval($course['min_note']) && intval($student['notafinal']) >=0) {$jalados ++;}
                    if ( $student['notafinal'] == -3 ) {$retirados ++;}
                }?>

                <td class='text-center' ><?php echo $key+1?></td>
                <td class='text-center'><?php echo $student['uid']?></td>
                <td class='text-name'><?php echo $student['name_complet'] ?></td>

                <!-- partial 1-->
                <td class='text-center'><?php echo ($student['nota4_i']==-3)? 'R': $student['nota1_i'] ?></td>
                <td class='text-center'><?php echo ($student['nota4_i']==-3)? 'R': $student['nota2_i'] ?></td>
                <td class='text-center'><?php echo ($student['nota4_i']==-3)? 'R': $student['nota3_i'] ?></td>
                <td class='success text-center'><?php echo ($student['nota4_i']==-3)? 'R': $student['nota4_i'] ?></td>

                <td class='text-center' ><?php echo ($student['nota4_i']==-3)? 'R': $student['nota6_i'] ?></td>
                <td class='text-center' ><?php echo ($student['nota4_i']==-3)? 'R': $student['nota7_i'] ?></td>
                <td class='text-center' ><?php echo ($student['nota4_i']==-3)? 'R': $student['nota8_i'] ?></td>
                <td class='text-center success' ><?php echo  ($student['nota4_i']==-3)? 'R': $student['nota9_i'] ?></td>
                <!-- partial 2-->

                <?php if($this->partial == 2 && intval($this->units) != 3  ){?>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota1_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota2_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota3_ii'] ?></td>
                <td class='text-center success' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota4_ii'] ?></td>

                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota6_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota7_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota8_ii'] ?></td>
                <td class='text-center success' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota9_ii'] ?></td>
                <td class='text-center success' ><?php echo  ($student['notafinal']==-3)? 'R': $student['notafinal'] ?></td>

                <?php }if($this->partial == 2 && intval($this->units) == 3 ){?>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota1_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota2_ii'] ?></td>
                <td class='text-center ' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota3_ii'] ?></td>
                <td class='text-center success' ><?php echo  ($student['nota4_ii']==-3)? 'R': $student['nota4_ii'] ?></td>

                <td class='text-center success' ><?php echo  ($student['notafinal']==-3)? 'R': $student['notafinal'] ?></td>
                <?php }?>
            </tr>

        <?php }?>
    </tbody>
</table>

<?php if ($this->partial == 2) { ?>
    <address>
        <strong>Aprobados</strong>  <?php echo $aprobados?><br>
        <strong>Desaprobados</strong>  <?php echo $jalados?><br>
        <strong>Retirados</strong>  <?php echo $retirados?><br>
        <strong>Total</strong>  <?php echo $aprobados+$jalados+$retirados?>
    </address>
<?php }?>

<?php 
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,5,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.05,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Registro-'.$course['name'].'-'.$this->turno.'.pdf','D');
    // $mpdf->Output();

?>