<style type="text/css">
	.nota{
		width: 53px;
		text-align: center;
	}
	.presented{
		cursor: pointer;
	}
	.error-input
	{
		background-color: red;
	}
</style>
<script type="text/javascript" src="/js/notes/note-deferred.js"></script>

<?php if ($this->state=='C') $disabled="disabled";?>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8"><h4><span class='glyphicon glyphicon-pencil' ></span> Llenado de Aplazados <?php echo $this->infocurso['name']?></h4></div>
  <div class="col-xs-6 col-sm-6 col-md-4">
  	<a href="/docente/notas" class="btn btn-default"><span class='glyphicon glyphicon-arrow-left'></span> Regresar</a>
  	<?php if ($this->students_register && $this->state !='C') { ?>
  		<button class='btn btn-info' id='save_notas' disabled > <span class='glyphicon glyphicon-save'></span> Guardar</button>
	  	<button class='btn btn-danger' id='closed_record'  <?php echo $disabled?> > <span class='glyphicon glyphicon-log-out'></span> Cerrar Acta</button>
  	<?php }?>
  	<?php if ($this->state=='C' ) { ?>
  		<a href="/register/deferred/printdeferred/curid/<?php echo base64_encode($this->infocurso['curid'])?>/escid/<?php echo base64_encode($this->infocurso['escid'])?>/subid/<?php echo base64_encode($this->infocurso['subid'])?>/courseid/<?php echo base64_encode($this->infocurso['courseid'])?>/turno/<?php echo base64_encode($this->students_register[0]['turno'])?>/perid/<?php echo base64_encode($this->students_register[0]['perid'])?>" class='btn btn-primary'><span class="glyphicon glyphicon-print"></span> Imprimir</a>
  	<?php }?>
  </div>
</div>

<?php if ($this->students_register) { ?>
<div class='row notas' >
	<div class='col-md-8 col-md-offset-1'>
	<table class='table' id='tbnotas'>
		<tr>
			<th>#</th>
			<th>Coodigo</th>
			<th>Apellidos y Nombres</th>
			<th class='success'>Recibo</th>
			<th class='success'>Nota</th>
		</tr>
		<?php foreach ($this->students_register as $key => $registro) { ?>
		<tr 	courseid='<?php echo $registro['courseid']?>'
				curid='<?php echo $registro['curid']?>'
				turno='<?php echo $registro['turno']?>'
				perid='<?php echo $registro['perid']?>'
				escid='<?php echo $registro['escid']?>'
				subid='<?php echo $registro['subid']?>'
				regid='<?php echo $registro['regid']?>'
				uid='<?php echo $registro['uid']?>'
				pid='<?php echo $registro['pid']?>'
                edicion="false"
                style="color:<?php echo ($registro['notafinal'] != -2)?'#000':'#FC4141'; ?>;"
		>
			
			<td><?php echo $key+1?> <span id='edit_nota_<?php echo $key?>' class='text-success glyphicon'></span>
			</td>
			<td><?php echo $registro['uid']?></td>
			<td><?php echo  $registro['name'] ?></td>
			<td class='td_select_<?php echo $key?> td_select'>
			
					<select class='form-control select_receipt' index='<?php echo $key ?>' name='receipt' <?php echo ($registro['notafinal'] != -2)?'':'disabled'; ?>  <?php echo $disabled?> >
						<option value="<?php echo $registro['receipt']?>"><?php echo ($registro['receipt'] != "")?$registro['receipt']:'Seleccione'; ?></option>
						<?php foreach ($registro['receipts'] as $key => $value) { ?>
						<option value='<?php echo $value['operation']?>'><?php echo $value['operation']?></option>
						<?php }?>
					</select>
				
			</td>
			<td class='td_input_<?php echo $key?> td_input' >
				<input type='text'  name='notafinal' maxlength='2' style="color:<?php echo ($registro['notafinal'] != -2)?'#000':'#FC4141'; ?>;" class='form-control nota' <?php echo ($registro['notafinal'] != -2)?'':'disabled'; ?> value='<?php echo ($registro['notafinal'] != -2)?$registro['notafinal']:'NP'; ?>' index='<?php echo $key?>'  <?php echo $disabled?> ></td>
			<td class='success'>
				<?php
					if ($this->state != "C") {
					if ($registro['notafinal'] != -2) { ?>
						<span class='glyphicon glyphicon-eye-open presented' 
							action='0' onclick='not_present(this);'
							index='<?php echo $key?>'></span>
					<?php }else{ ?>
						<span class='glyphicon glyphicon-eye-close presented' 
							action='1' onclick='not_present(this);' 
							index='<?php echo $key?>'></span>
					<?php }}?>
			</td>
		</tr>
		<?php }?>
	</table>
	</div>
</div>

<input type='hidden' id='record-courseid' name='courseid' value='<?php echo $this->students_register[0]['courseid']?>'>
<input type='hidden' id='record-turno' name='turno' value='<?php echo $this->students_register[0]['turno']?>'>
<input type='hidden' id='record-curid' name='curid' value='<?php echo $this->students_register[0]['curid']?>'>
<input type='hidden' id='record-escid' name='escid' value='<?php echo $this->students_register[0]['escid']?>'>
<input type='hidden' id='record-subid' name='subid' value='<?php echo $this->students_register[0]['subid']?>'>
<input type='hidden' id='record-perid' name='perid' value='<?php echo $this->students_register[0]['perid']?>'>
<?php }else{ ?>
	<!-- <img src="/img/009.png" width='90px'> -->
	<div class='col-md-12 cont-font-not-register'>
		<h1 class='span-not-register'>
			<span class='glyphicon glyphicon-exclamation-sign'></span>
		</h1>
		<h3 class='text-not-register'>No se encontro ningun Registro  </h3>
	</div>
<?php }?>

