<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$speciality = $this->info_speciality;
if ($speciality['parent']!= '') {
  $name_esc = $speciality['speciality'];
  $name_speciality='ESPECIALIDAD'.$speciality['name'];
}
else{
  $name_esc=$speciality['name'];
}
$perid=$this->perid;
$course = $this->infocourse;
$students = $this->students;
$mpdf->mirrorMargins = 1;

$aprobados = 0;
$jalados = 0;
$retirados = 0;
$back = '';
$back1 = '';
$header = '
<table width="100%" style="border: 1px solid #000;font-family: serif;  color: #000; ">
  <tr style="text-align:center; padding-left: 100px; ">
      <td  rowspan="2" width="340px" style="border: 1px solid #000 "><img src="/img/header_imprimir.jpg">
      </td>
      <td style="text-align:center; font-size:10px; border: 1px solid #000 ">
        FACULTAD '.strtoupper($this->faculty).'<br/>
        ESCUELA '.strtoupper($name_esc).'<br/>
        '.strtoupper($name_speciality).'<br/>
        
      </td>
  </tr>
  <tr>
    <td style="text-align:center; font-size:10px; border: 1px solid #000 " >ACTA EVALUACIÓN - PERIODO '.$perid.' </td>
  </tr>
</table>
<table width="100%" style="border-bottom: 2px solid #000; font-family: serif;  color: #000; margin-bottom:20px;">
  <tr >
    <td  style="font-size:10px; text-align:left;  " >
    <strong sytle="padding-right:10px">Curso </strong>'.$course['courseid'].' - '.$course['name'].'
    </td>
    
        <td style="text-align: right; font-size:10px;"><strong>Turno </strong> '.$this->turno.'</td>
        <td  style="text-align: right; font-size:10px;"><strong>Creditos </strong>'.$course['credits'].' </td>
  </tr>
  <tr >
        <td   style="text-align:left; font-size:10px;"><strong>Docente </strong> '.$this->lasname.'</td>
        <td  style="text-align: right; font-size:10px;"><strong>Semestre </strong>'.$course['semid'].' </td>
        <td  style="text-align:right; font-size:10px;"><strong>Alumnos </strong>'.count($students).' </td>
  </tr>
</table>
';
?>
<style type="text/css">
address {
  margin-top: 10px;
  font-size: 8px;
  font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;

}
.table-bordered {
  width: 100%;
  font-size:10px;
  font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
  border: 1px solid #000;
  border-collapse: collapse;
  border-spacing: 0;
}
.text-name{
    text-align: left;
    border: 0.5px solid #2c242c;
}
.text-center, {
  text-align: center;
  border: 0.5px solid #2c242c;
}
.header{
  background-color: #ebe9eb;
}
</style>
<?php if ($this->students) { ?>
    <div class='row'>
        <div class='col-md-12 table-responsive'>
            <table class='table table-bordered'>
                <thead>
                    <tr>
                        <th class='text-center'>#</th>
                        <th class='text-center' >Codigo</th>
                        <th class='text-name'>Apellidos y Nombres</th>
                        <th class='text-center' >Recibo</th>
                        <th class='text-center' >Nota</th>
                        
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->students as $key => $student) { ?>
                    <tr>

                        <?php 
                            if ($student['notafinal']== -2 ) { $retirados++;}
                            if ($student['notafinal'] > 10 && $student['notafinal'] <=20 ) { $aprobados++; $back="active text-primary";}
                            if ($student['notafinal'] >= 0 && $student['notafinal'] <=10 ) { $jalados++; $back="danger text-danger";} 
                       ?>

                        <td class='text-center'><?php echo $key+1?></td>
                        <td class='text-center'><?php echo $student['uid']?></td>
                        <td class='text-name'><?php echo $student['name_complet']?></td>
                        <td class='text-name'><?php echo $student['receipt']?></td>
                        <td class='text-name'><?php echo ($student['notafinal']==-2)?'N.S.P':$student['notafinal']?></td>

                    </tr>
                <?php }?>
                </tbody>
            </table>
        </div>
    </div>
<?php }?>
<address>
  <strong>Aprobados</strong>  <?php echo $aprobados?><br>
  <strong>Desaprobados</strong>  <?php echo $jalados?><br>
  <strong>No se Presentaron</strong>  <?php echo $retirados?><br>
  <strong>Total</strong>  <?php echo $aprobados+$jalados+$retirados?>
</address>


<?php 
$html = ob_get_contents();
$mpdf=new mPDF('win-1252','A4','','',10,10,42);
$mpdf->SetHTMLHeader($header);
$mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
$mpdf->SetFooter($this->footer);
ob_end_clean();
$mpdf -> WriteHTML($html);
$mpdf->Output('Registro-'.$course['name'].'-'.$this->turno.'.pdf','D');
 
?>