<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$perid=$this->perid;
$course = $this->infocourse;
$students = $this->students;
$mpdf->mirrorMargins = 1;

$aprobados = 0;
$jalados = 0;
$retirados = 0;
$back = '';
$back1 = '';
?>
<style type="text/css">
address {
  margin-top: 10px;
  font-size: 8px;
  font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;

}
.table-bordered {
  width: 100%;
  font-size:10px;
  font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
  border: 1px solid #000;
  border-collapse: collapse;
  border-spacing: 0;
}
.text-name{
    text-align: left;
    border: 0.5px solid #2c242c;
}
.text-center, {
  text-align: center;
  border: 0.5px solid #2c242c;
}
.header{
  background-color: #ebe9eb;
}
</style>
<table width="100%" style="font-family: serif;  color: #000;">
    <tr >
        <td  style="font-size:10px; text-align:left;  " >
        <strong sytle="padding-right:5px">Curso: </strong><?php echo $course['courseid']." - ".$course['name']?>
        </td>
        
        <td style="text-align: right; font-size:10px;"><strong>Turno: </strong> <?php echo $this->turno?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Créditos: </strong><?php echo $course['credits'] ?></td>
    </tr>
    <tr >
        <td   style="text-align:left; font-size:10px;"><strong>Docente: </strong> <?php echo $this->lasname ?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Semestre: </strong><?php echo $course['semid'] ?></td>
        <td  style="text-align:right; font-size:10px;"><strong>Alumnos: </strong><?php echo count($students)?></td>
    </tr>
</table>
<div style="text-align:center; font-size:12px; margin-top:2%; margin-bottom:3%"><b>ACTA EVALUACIÓN - PERIODO <?php echo $perid ?> </b></div>
<?php if ($this->students) { ?>
    <div class='row'>
        <div class='col-md-12 table-responsive'>
            <table class='table table-bordered'>
                <thead>
                    <tr>
                        <th class='text-center'>#</th>
                        <th class='text-center' >Código</th>
                        <th class='text-name'>Apellidos y Nombres</th>
                        <th class='text-center' >Recibo</th>
                        <th class='text-center' >Nota</th>
                        
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->students as $key => $student) { ?>
                    <tr>

                        <?php 
                            if ($student['notafinal']== -2 ) { $retirados++;}
                            if ($student['notafinal'] > 10 && $student['notafinal'] <=20 ) { $aprobados++; $back="active text-primary";}
                            if ($student['notafinal'] >= 0 && $student['notafinal'] <=10 ) { $jalados++; $back="danger text-danger";} 
                       ?>

                        <td class='text-center'><?php echo $key+1?></td>
                        <td class='text-center'><?php echo $student['uid']?></td>
                        <td class='text-name'><?php echo $student['name_complet']?></td>
                        <td class='text-name'><?php echo $student['receipt']?></td>
                        <td class='text-name'><?php echo ($student['notafinal']==-2)?'N.S.P':$student['notafinal']?></td>

                    </tr>
                <?php }?>
                </tbody>
            </table>
        </div>
    </div>
<?php }?>
<address>
  <strong>Aprobados</strong>  <?php echo $aprobados?><br>
  <strong>Desaprobados</strong>  <?php echo $jalados?><br>
  <strong>No se Presentaron</strong>  <?php echo $retirados?><br>
  <strong>Total</strong>  <?php echo $aprobados+$jalados+$retirados?>
</address>


<?php 
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,36,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');

    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Registro-'.$course['name'].'-'.$this->turno.'.pdf','D');
    // $mpdf->Output();
 
?>