<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encuesta</title>
    <link rel="stylesheet" href="/external_library/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/encuesta.css">
    <link href="http://fonts.googleapis.com/css?family=Cuprum:400italic,400,700italic,700" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/js/jquery-1.11.0.js"></script>
    <script type="text/javascript" src="/external_library/bootstrap/js/bootstrap.js"></script>
</head>
<body>
    <header>
        <p class="pHeader"><span class="glyphicon glyphicon-bookmark"></span> Encuesta</p>
        <a href="/logout" class="btnClose">
            Salir, no deseo rellenar la encuesta en este momento
            <div class="mensageAviso">
                <span class="glyphicon glyphicon-info-sign"></span>
                <p>Recuerde que la encuesta es obligatoria, tiene que rellenarla si desea entrar la sistema.</p>
            </div>
        </a>
    </header>
    <article>
    
    </article>
</body>
</html>
