<?php 
	$this->placeholder('Btnnav')->append('<a href="##" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');

	$this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list-alt"></span> Gestión de Encuesta');
 ?>
<div class="row">
	<div class="col-md-3 col-md-offset-9">
		<a id="create_poll" href="#poll_create" class="btn btn-info form-control" data-toggle="modal"><span class="glyphicon glyphicon-plus"></span> Nueva Encuesta</a>
	</div>
</div>
<hr>

<?php
if ($this->poll) { ?>
	<table class="table table-bordered table-hover">
		<tr class="active">
			<th class="text-center">#</th>
			<th>Título Encuesta</th>
			<th class="text-center">Periodo</th>
			<th class="text-center">Publicación</th>
			<th class="text-center">Cierre</th>
			<th class="text-center">Estado</th>
		</tr>
		<?php
		$c = 1;
		foreach ($this->poll as $data_poll) { 
			if ($data_poll['state']=="A") $img = "/img/circulo-verde.png";
			else $img = "/img/circulo-rojo.png";
			?>
			<tr>
				<td class="text-center"><?php echo $c?></td>
				<td><?php echo $data_poll['title']?></td>
				<td class="text-center"><?php echo $data_poll['perid']?></td>
				<td class="text-center"><?php echo $data_poll['published']?></td>
				<td class="text-center"><?php echo $data_poll['closed']?></td>
				<td class="text-center">
					<img src="<?php echo $img?>" title="<?php echo ($data_poll['state']=="A")? "Activa": "Cerrada"?>" rel="tooltip">
				</td>
				<td class="text-center">
					<a href="#poll_update" pollid="<?php echo $data_poll['pollid']?>" class="btnUpdatePoll" title="Editar Encuesta" rel="tooltip" data-toggle="modal"><span class="glyphicon glyphicon-edit"></span></a>
				</td>
				<td class="text-center">
					<a href="/poll/index/questions/pollid/<?php echo base64_encode($data_poll['pollid'])?>" title="Agregar Preguntas" rel="tooltip"><span class="glyphicon glyphicon-list"></span></a>
				</td>
			</tr>
			<?php
			$c++;
		}?>
	</table>
<?php	
}?>

<div class="modal fade" id="poll_create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          		<h4 class="modal-title"><span class="glyphicon glyphicon-list"></span> - Nueva Encuesta</h4>
        	</div>
        	<div id="load_poll_create" class="modal-body"></div>
        	<div class="modal-footer">
          		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
          		<a href="#" id="creating_poll" class="btn btn-success">
					<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
				</a>
        	</div>
      	</div>
    </div>
</div>

<div class="modal fade" id="poll_update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          		<h4 class="modal-title"><span class="glyphicon glyphicon-list"></span> Modificar Encuesta</h4>
        	</div>
        	<div id="load_poll_update" class="modal-body"></div>
        	<div class="modal-footer">
          		<a href="##" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
          		<a href="##" id="update_new_poll" class="btn btn-success">
					<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
				</a>
        	</div>
      	</div>
    </div>
</div>

<script>
	$(function(){
		$("a, img").tooltip();

		$("#create_poll").on('click', function(){
			$("#load_poll_create")	.html("<br><center><img src='/img/spinner.gif'></center>")
									.load("/poll/index/new/");
		});

		$("#creating_poll").on('click', function(){
		    $("#formPollcreate").submit();
		});


		var pollid = '';

		$(".btnUpdatePoll").on('click', function(){
			var pollid = $(this).attr('pollid');
			$("#load_poll_update")	.html("<br><center><img src='/img/spinner.gif'></center>")
									.load("/poll/index/update/pollid/"+pollid);
		});

		$("#update_new_poll").on('click', function(){
		    $("#formPoll").submit();
		});
	});
</script>