<?php 
	$this->placeholder('Btnnav')->append('<a href="/poll" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');
	
	$this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-pencil"></span> Gestión de Preguntas');
?>

<?php
if ($this->data_poll) { ?>
	<div class="row">
		<div class="col-md-9">
			<h4 class="text-muted">Titulo de la Encuesta: <span class="text-info"><?php echo $this->data_poll['title']?></span></h4>
		</div>
		<div class="col-md-3" style="padding-top: 3px;">
			<a id="new_question" href="#question_create" class="btn btn-info form-control" data-toggle="modal">Nueva Pregunta</a>
		</div>
	</div>
	<hr>
	<?php
	if ($this->data_ques) { ?>
		<div class="panel-group" id="accordion" style="margin: 0px 100px 0px 100px">
			<?php
			foreach ($this->data_ques as $question) { ?>
			    <div class="panel panel-default" style="margin-bottom: 10px">
			       	<div class="panel-heading">
			       		<h6 class="panel-title" style="font-size:14px">
			               	<?php echo $question['position'].' - '.$question['question']?>
			               	<img src="/img/<?php echo ($question['state']=="A")? "circulo-verde.png": "circulo-rojo.png"?>" rel="tooltip" title="<?php echo ($question['state']=="A")? "Activo": "Inactivo"?>">
			            	<a id="update_question_<?php echo $question['qid']?>" href="#question_update" data-toggle="modal"><span class="glyphicon glyphicon-edit" style="float: right" rel="tooltip" title="Editar Pregunta"></span></a>
			        	</h6>
			        </div>
			       	<div class="panel-collapse in">
			          	<div class="panel-body">
				        	<?php 
				        	$data_alt=array('eid' => $question['eid'], 'oid' => $question['oid'], 'qid' => $question['qid']);
				        	$alt = new Api_Model_DbTable_PollAlternatives();
				        	$data_alt = $alt->_getFilter($data_alt,$attrib=null,$orders=array('position'));
				        	if ($data_alt) { ?>
				        		<table class="table">
				        			<tr>
				        				<th>#</th>
				        				<th>Alternativa</th>
				        				<th>Eliminar</th>
				        			</tr>
					        		<?php
					        		$c = 1;
					        		foreach ($data_alt as $data_alt) { ?>
					        			<tr>
					        				<td><?php echo $c?></td>
					        				<td><?php echo $data_alt['alternative']?></td>
					        				<td><a id="alter_<?php echo $data_alt['atlid']?>" href="#delete_alter" data-toggle="modal"><span class="glyphicon glyphicon-trash" rel="tooltip" title="Eliminar Alternativa"></span></a></td>
					        			</tr>
					        			<script type="text/javascript">
					        				$("#alter_<?php echo $data_alt['atlid']?>").click(function(){
					        					var atlid = "<?php echo $data_alt['atlid']?>";
					        					var qid = "<?php echo $data_alt['qid']?>";
					        					$("#loaddelete").load("/poll/index/deletealternative/atlid/"+atlid+"/qid/"+qid);
					        				});
					        			</script>
					        		<?php
					        		$c++;
					        		} ?>
				        		</table>
				        		<?php
				        	} ?>
		              	</div>
		         	</div>
			    </div>
			    <script type="text/javascript">
				    $("#update_question_<?php echo $question['qid']?>").click(function(){
				    	var qid = "<?php echo $question['qid']?>";
				    	$("#load_question_update").html("<img src='/img/carga.gif'>");
						$("#load_question_update").load("/poll/index/updatequestion/qid/"+qid);
				    });
			    </script>
			<?php
			} ?>
    	</div>
	<?php
	}else{ ?>
		<h4 class="text-muted text-center"><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> Aun no existe preguntas, <span class="text-danger">cree algunas para empezar.</span></h4>
	<?php }
}?>
<div id="loaddelete"></div>

<div class="modal fade" id="delete_alter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-body">
        		Enviando Datos al Servidor!!!
        	</div>
      	</div>
    </div>
</div>

<div class="modal fade" id="question_create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          		<h4 class="modal-title"><span class="glyphicon glyphicon-list"></span> - NUEVA PREGUNTA</h4>
        	</div>
        	<div id="load_question_create" class="modal-body"></div>
        	<div class="modal-footer">
          		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
          		<a href="#" id="creating_question" class="btn btn-success">
					<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
				</a>
        	</div>
      	</div>
    </div>
</div>

<div class="modal fade" id="question_update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          		<h4 class="modal-title"><span class="glyphicon glyphicon-list"></span> - MODIFICAR PREGUNTA</h4>
        	</div>
        	<div id="load_question_update" class="modal-body"></div>
        	<div class="modal-footer">
          		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
          		<a href="#" id="updating_question" class="btn btn-success">
					<span class='glyphicon glyphicon-floppy-disk'></span> Guardar
				</a>
        	</div>
      	</div>
    </div>
</div>

<script type="text/javascript">
	$("#new_question").click(function(){
		var pollid = "<?php echo $this->pollid?>";
		$("#load_question_create").html("<img src='/img/carga.gif'>");
		$("#load_question_create").load("/poll/index/newquestion/pollid/"+pollid);
	});

	$("#creating_question").click(function(){
	    $("#formQuestion").submit();
	});

	$("#updating_question").click(function(){
	    $("#formQuestion").submit();
	});

	$("span, img").tooltip();
</script>