<form id="formQuestion" action="/poll/index/updatequestion/" method="post" enctype="application/x-www-form-urlencoded">
		<table class="table table-hover">
			<tr>
				<th>Pregunta: </th>
				<td colspan="3"><?php echo $this->form->question?></td>
			</tr>
			<tr>
				<th>Tipo: </th>
				<td><?php echo $this->form->type?></td>
				<th>Estado: </th>
				<td><?php echo $this->form->state?></td>
			</tr>
		</table>
		<table class="table table-hover">
			<tr>
				<th colspan="2" style="font-size: 14px"><center>Registro de Alternativas </center></th>
			</tr>
			<?php
			$alternatives = $this->alternatives;
			for ($i=0; $i < 5; $i++) { ?>
				<tr>
					<th><?php echo $i+1?></th>
					<td>
						<?php
						$alternatives[$i]['atlid']=(isset($alternatives[$i]['atlid'])?$alternatives[$i]['atlid']:null);
						if ($alternatives[$i]['atlid']) { ?>
							<input name="<?php echo $alternatives[$i]['atlid']?>" type="text" class="form-control" value="<?php echo $alternatives[$i]['alternative']?>">
							<?php
						}else{ ?>
							<input name="alternative<?php echo $i+1?>" type="text" class="form-control">
						<?php
						}?>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<input type="hidden" name="qid" value="<?php echo $this->qid?>">
</form>	

<script type="text/javascript">
	var success = "<?php echo $this->success?>";
	if (success == 1) {
		window.location.reload();
	};

    $("#formQuestion").submit(function(){
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(data) { 
                    $("#load_question_update").html(data);
                }
            }); 
            return false;
    });
</script>