<?php
if ($this->lockuser) {
  ?>
  <table class="table table-condensed table-striped table-hover table-bordered">
    <tr>
      <td colspan='5'><center style="font-size:25px"><b>LISTA DE LOS ALUMNOS </b></center></td>
    </tr>
    <tr>
      <th><center>#</center></th>
      <th><center>D.N.I</center></th>
      <th><center>Código</center></th>
      <th><center>Nombres y Apellidos</center></th>
      <th><center>Bloquear</center></th>
    </tr>
    <?php 
    $c=0;
    $i=1;
    foreach ($this->lockuser as $data) {
      $c++;
      $formdata=$this->formdata;
      $pid=$data['pid'];
      $uid=$data['uid'];
      $name=$data['last_name0']." ".$data['last_name1'].", ".$data['first_name'];
    ?>
    <tr>
      <td><center><?php echo $c?></center></td>
      <td><center><?php echo $pid?></center></td>
      <td><center><?php echo $uid?></center></td>
      <td><?php echo $name?></td>  
      <td><center><input type="checkbox" id="check_<?php echo $i?>" value="<?php echo $data['uid'].";--;".$data['pid'].";--;".$formdata['escid'].";--;".$formdata['subid'].";--;".$formdata['type_doc'].";--;".$formdata['date'].";--;".$formdata['reason'].";--;".$formdata['detail'].";--;".$formdata['office']?>"></center></td>
      <?php
      if($data['state'] =='A'){ 
        ?>
        <script>
            $("#check_<?php echo $i?>").change(function(){ 
              var s = $(this).attr('value');
              var check =  $(this).attr('checked');
              // alert(check);
              tmp=s.split(";--;");
              uid=tmp[0];
              pid=tmp[1];
              escid=tmp[2];
              subid=tmp[3];
              type_doc=tmp[4];
              date=tmp[5];
              reason=tmp[6];
              detail=tmp[7];
              office=tmp[8];
                if (check_<?php echo $i?>.checked == 1){
                  alert(<?php echo $i?>);
                  url = "/bienestar/specialitylock/created/uid/"+uid+"/pid/"+pid+"/escid/"+escid+"/subid/"+subid+"/type_doc/"+type_doc+"/date/"+date+"/reason/"+reason+"/detail/"+detail+"/office/"+office;
                  $("#sp").load(url);
               
            });
        </script>
        <?php
      } 
      ?>
    </tr>
    <?php
    $i++;
    }
    ?>
  </table>
<div id='sp'></div>
<?php
}
else{
  ?>
  <div class="alert alert-info" style='font-size:18px'><center><b>No se encuentran REGISTROS </b>......</center></div>
<?php 
}
?>