<?php
if ($this->lockuser) {
  ?>
<div class="text-center"><h3><b>LISTA DE LOS ALUMNOS </b></h3></div>
<div id="list">
    <table class="table table-condensed table-striped table-hover table-bordered">
        <tr>
            <th><center>#</center></th>
            <th><center>D.N.I</center></th>
            <th><center>Código</center></th>
            <th><center>Nombres y Apellidos</center></th>
            <th><center>Bloquear</center></th>
        </tr>
        <?php 
        $c=0;
        $j=1;
        foreach ($this->lockuser as $data) {
            $c++;
            $formdata=$this->formdata;
            $pid=$data['pid'];
            $uid=$data['uid'];
            $name=$data['last_name0']." ".$data['last_name1'].", ".$data['first_name'];
            ?>
        <tr>
            <td><center><?php echo $c?></center></td>
            <td><center><?php echo $pid?></center></td>
            <td><center><?php echo $uid?></center></td>
            <td><?php echo $name?></td>  
            <td><center><input type="checkbox" id="check_<?php echo $j?>" value="<?php echo $data['uid'].";--;".$data['pid'].";--;".$formdata['escid'].";--;".$formdata['subid'].";--;".$formdata['type_doc'].";--;".$formdata['date'].";--;".$formdata['reason'].";--;".$formdata['detail'].";--;".$formdata['office']?>"></center></td>
            <?php
            if($data['state'] =='A'){   ?>
            <script>
                $("#check_<?php echo $j?>").click(function(){ 
                    if($("#check_<?php echo $j?>").is(':checked')) {  
                        var s = $(this).attr('value');
                        tmp=s.split(";--;");
                        uid=tmp[0];
                        pid=tmp[1];
                        escid=tmp[2];
                        subid=tmp[3];
                        type_doc=tmp[4];
                        date=tmp[5];
                        reason=tmp[6];
                        detail=tmp[7];
                        office=tmp[8];
                        var url = "/bienestar/specialitylock/created/uid/"+uid+"/pid/"+pid+"/escid/"+escid+"/subid/"+subid+"/type_doc/"+type_doc+"/date/"+date+"/reason/"+reason+"/detail/"+detail+"/office/"+office;
                        $("#changes").load(url);
                    // var check =  $(this).attr('checked');
                    // alert(s);
                        // alert("Está activado");  
                    } 
                    // else {  
                    //     alert("No está activado");  
                    // } 
                    // alert(<?php echo $j?>);
                    // if (check_<?php echo $j?>.checked == 1){
                    // }    
                });
            </script>
            <?php
            } 
            ?>
        </tr>
        <?php
        $j++;
        exit();
    }    
    ?>
</table>
</div>  
<?php
}
else{
  ?>
  <div class="alert alert-info" style='font-size:18px'><center><b>No se encuentran REGISTROS </b>......</center></div>
<?php 
}
?>