<?php    
if ($this->unlockuser) {     ?>
    <table class="table table-condensed table-striped table-hover table-bordered">
        <tr>
        	<td colspan='5'><center style="font-size:25px"><b>LISTA DE LOS ALUMNOS </b></center></td>
        </tr>
        <tr>
          	<th><center>#</center></th>
          	<th><center>D.N.I</center></th>
          	<th><center>Código</center></th>
          	<th><center>Nombres y Apellidos</center></th>
          	<th><center>Desbloquear</center></th>
        </tr>

        <?php 
        $c=0;
        $i=1;
        foreach ($this->unlockuser as $data) {
          	$c++;
          	$formdata=$this->formdata;
          	$pid=$data['pid'];
          	$uid=$data['uid'];
            $dbuid=$data['dbuid'];
          	$name=$this->datauser[$c-1][0]['last_name0']." ".$this->datauser[$c-1][0]['last_name1'].", ".$this->datauser[$c-1][0]['first_name'];
        ?>
        <tr>
          	<td><center><?php echo $c?></center></td>
          	<td><center><?php echo $pid?></center></td>
          	<td><center><?php echo $uid?></center></td>
          	<td><?php echo $name?></td>  
          	<td><center><input type="checkbox" id="check_<?php echo $i?>" value="<?php echo $data['dbuid'].";--;".$data['uid'].";--;".$data['pid'].";--;".$formdata['escid'].";--;".$formdata['subid'].";--;".$formdata['type_doc'].";--;".$formdata['date'].";--;".$formdata['reason'].";--;".$formdata['detail'].";--;".$formdata['office']?>"></center></td>
        	<?php
          	if($data['state'] =='B'){?>
            	<script>
                	$("#check_<?php echo $i?>").change(function(){ 
                  	var s = $(this).attr('value');
                  	var check =  $(this).attr('checked');
                    tmp=s.split(";--;");
                    dbuid=tmp[0];
                  	uid=tmp[1];
                  	pid=tmp[2];
                  	escid=tmp[3];
                  	subid=tmp[4];
                  	type_doc=tmp[5];
                  	date=tmp[6];
                  	reason=tmp[7];
                  	detail=tmp[8];
                  	office=tmp[9];
                      if (check_<?php echo $i?>.checked == 1){
                          url = "/bienestar/specialitylock/updated/dbuid/"+dbuid+"/uid/"+uid+"/pid/"+pid+"/escid/"+escid+"/subid/"+subid+"/type_doc/"+type_doc+"/date/"+date+"/reason/"+reason+"/detail/"+detail+"/office/"+office;
                          $("#sp").load(url);
                    	}
                });
            	</script>
            <?php
            } 
            ?>
        </tr>
        <?php
        	$i++;
        }
        ?>
    </table>
    <div id='sp'><div>
    <?php    
}
else{
  ?>
  <div class="alert alert-info" style='font-size:18px'><center><b>No se encuentran REGISTROS </b>......</center></div>
<?php 
}
?>    