<?php //print_r($this->coursesname);
if($this->allcourses){?>
	<table class="table table-striped">
		<tr>
			<th>#</th>
			<th><center>Sem</center></th>
			<th><center>Codigo</center></th>
			<th>Curso</th>
			<th>Docente</th>
			<th><center>Turno</center></th>
			<th><center>Estado</center></th>
		</tr>
	
		<?php $c=0;
		foreach ($this->allcourses as $courses) {
			$cp=0;
			foreach ($courses as $coursesxper) {?>
				<tr>
					<td><b><?php echo $c+1;?></b></td>
					<td align="center"><?php echo $coursesxper['semid'];?></td>
					<td align="center"><?php echo $this->coursesname[$c][$cp]['courseid']?></td>
					<td><?php echo $this->coursesname[$c][$cp]['name']?></td>
					<td><?php echo $this->teachers[$c][$cp]['last_name0']." ".$this->teachers[$c][$cp]['last_name1']." ".$this->teachers[$c][$cp]['first_name']?></td>
					<td align="center"><?php echo $coursesxper['turno'];?></td>
					<td align="center">
						<?php if($this->coursesstate[$c][$cp]['state']=="C"){?>
							<img src="/img/circulo-verde.png">
						<?}else{?>
							<img src="/img/circulo-rojo.png">
						<?}?>
					</td>
					<td><a href="#"><span class="glyphicon glyphicon-print"></span></a></td>
				</tr>				
			<?php $c++;
			}
			$cp++;		 
		}?>
	</table>
<?php }elseif($this->filcourses){?>
	<table class="table table-striped">
		<tr>
			<th>#</th>
			<th>Sem</th>
			<th>Codigo</th>
			<th>Curso</th>
			<th>Docente</th>
			<th>Turno</th>
			<th>Estado</th>
		</tr>
	
		<?php $c=0;
		foreach ($this->filcourses as $courses) {?>
			<tr>
				<td><b><?php echo $c+1;?></b></td>
				<td><?php echo $courses['semid'];?></td>
				<td align="center"><?php echo $this->coursesname[$c][0]['courseid']?></td>
				<td><?php echo $this->coursesname[$c][0]['name']?></td>
				<td><?php echo $this->teachers[$c][0]['last_name0']." ".$this->teachers[$c][0]['last_name1']." ".$this->teachers[$c][0]['first_name']?></td>
				<td><?php echo $courses['turno'];?></td>
				<td>
					<?php if($this->coursesstate[$c][0]['state']=="C"){?>
						<img src="/img/circulo-verde.png">
					<?}else{?>
						<img src="/img/circulo-rojo.png">
					<?}?>
				</td>
				<td><a href="#"><span class="glyphicon glyphicon-print"></span></a></td>
			</tr>				
			<?php $c++;
			}
			$cp++;		 
		?>
	</table>
<?php }else{?>
	<center><h4>No Existen Datos</h4></center>
<?php }?>