<?php $year=date('Y')+1;?>
<div class="col-sm-12"  align="center">
	<h2>Lista de Silabus</h2>
	<div class="col-sm-3">
		<label for="">Año</label>
		<select name="Year" id="year" class="form-control">
			<?php for ($i=$year; $i>=1965 ; $i--) { 
				$txt="";
				if($i==date('Y')) $txt="selected";?>
				<option value="<?php echo $i;?>" <?php echo $txt;?>><?php echo $i;?></option>
			<?php }?>
		</select>
	</div>
	<div class="col-sm-5">
		<label>Periodo</label>
		<select name="Period" id="perid" class="form-control">
			<option value="">Periodo</option>
		</select>
	</div>
	<div class="col-sm-4">
		<label>Semestre</label>
		<select name="Semester" id="semester" class="form-control">
			<option value="2013">Seleccione un Periodo</option>
		</select>
	</div>
</div>

<div class="cl-sm-12" id="get_courses"></div>


<script>
	var year=$("#year").val();
	$("#perid").html("<option value=''>Cargando...</option>");
	$("#perid").load("/syllabus/director/listperiods/year/"+year);
	
	$("#year").change(function(){
		$("#year option:selected").each(function(){
			var year=$(this).val();
			$("#semester").html("<option value=''>Seleccione un Periodo</option>");
			$("#perid").html("<option value=''>Cargando...</option>");
			$("#perid").load("/syllabus/director/listperiods/year/"+year);
		})
	})


	$("#perid").change(function(){
		$("#perid option:selected").each(function(){
			var perid=$(this).val();
			$("#semester").html("<option value=''>Cargando...</option>");
			$("#semester").load("/syllabus/director/listsemester/perid/"+perid);
		})
	})
</script>