<form action="<?php echo $this->form->getAction() ?>" method="post">

	<div class="row">
  		<div class="col-sm-8"><h2>Nuevo Registro Acceso Api</h2></div>
  		<div class="col-sm-2"><?php print $this->form->guardar;?></div>
  		<div class="col-sm-1"><br><a href="/admin/accessapi"  class="btn btn-danger  " >Cancelar</a></br></div>
	</div>
	<table class="table span6 table-striped table-bordered">
		<tr>
			<th>Address Ip</th>
			<td><?php echo $this->form->ip;?></td>
		</tr>
		<tr>
			<th>Clave Key</th>
			<td><?php echo $this->form->key;?></td>
		</tr>
		<tr>
			<th>Empresa</th>
			<td><?php echo $this->form->emp;?></td>
		</tr>
		<tr>
			<th>Responsable</th>
			<td><?php echo $this->form->resp;?></td>
		</tr>
		<tr>
			<th>Correo Electronico</th>
			<td><?php echo $this->form->mail;?></td>
		</tr>
		<tr>
			<th>Register</th>
			<td><?php echo $this->form->register;?></td>
		</tr>
	</table>


		
</form>