<div id="wrapper" style="margin: auto; top: 50%; left: 50%;position: absolute;">    
	    
		<div style=" margin: 0 auto">
			<div id="logincampus123" style="display: none">
				<form  action="http://campus.undac.edu.pe/index.php" method="post" class="form-vertical" 
					name="formLogin" id="formLogin" target="iframelogin">
					<input type="text" name ="login" title="Codigo de Matricula" value="<?php echo $this->uid?>">
					<input type="password" name="password" title="Contraseña" value="<?php echo $this->pass?>">
					<button type="submit" class="btn" value="Ingresar" name="submitAuth">Entrar</button>
					<input name="_qf__formLogin" type="hidden" value="" />
				</form>
			</div>
		</div>
	
</div>
<script>
$(document).ready(function() {
	$("#wrapper").html("<body style='background: #555 '><img src='/img/default.gif'></body>");
  	var bar = document.getElementById("myProgress");
	var progress = 0;
	var http = "<?php echo $this->http?>";
	var pagina =http+"://"+document.location.host+"/<?php echo $this->mod;?>";
	function setProgress(percent){
			$("#formLogin").submit();
			$("#textos").html("<p style='color: green'>Terminando carga</p>");
	}
	
	var interval = setInterval(
	    function(){
	        setProgress(++progress);
	        if (progress == 20) {
	        	redirigir();
	        	window.clearInterval(interval);
	        	}
	    }, 100);
	function redirigir(){
		window.location.href = pagina;
	}
});
</script>
