<div id="wrapper">    
    <div style="margin: auto; top: 50%; left: 50%;position: absolute;margin-top: -53px; margin-left: -230px;">
		<div style=" margin: 0 auto">
			<div id="logincampus123" style="display: none">
				<form  action="http://campus.undac.edu.pe/index.php" method="post" class="form-vertical" 
					name="formLogin" id="formLogin" target="iframelogin">
					<input type="text" name ="login" title="Codigo de Matricula" value="<?php echo $this->uid?>">
					<input type="password" name="password" title="Contraseña" value="<?php echo $this->pass?>">
					<button type="submit" class="btn" value="Ingresar" name="submitAuth">Entrar</button>
					<input name="_qf__formLogin" type="hidden" value="" />
				</form>
			</div>
			<div class="progress">
			  <div class="progress-bar progress-bar-success" role="progressbar"  id="myProgress" 
			  	aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: 700px">
			     <div id="myProgress" class="progress-bar progress-bar-success"></div>
			    <iframe name="iframelogin" width="100%" height="0" ></iframe>
			  </div>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
  	var bar = document.getElementById("myProgress");
	var progress = 0;
	var http = "<?php echo $this->http?>";
	var pagina =http+"://"+document.location.host+"/<?php echo $this->mod;?>";
	function setProgress(percent){
	    bar.style.width = percent + "%";
		if (percent == 4 ){
			$("#textos").html("<p style='color: #000'>Cargando Componentes Básicos</p>");
		}
		if (percent == 8 ){
			$("#textos").html("<p style='color: red'>Cargando Campus Virtual</p>");
		}
		if (percent == 12 ){
			$("#formLogin").submit();
			$("#textos").html("<p style='color: green'>Terminando carga</p>");
		}			
	    if (percent > 16)
	        bar.className = "bar bar-success";
	    else if (percent > 13)
	        bar.className = "bar bar-warning";
	}
	
	var interval = setInterval(
	    function(){
	        setProgress(++progress);
	        if (progress == 20) {
	        	redirigir();
	        	window.clearInterval(interval);
	        	}
	    }, 100);
	function redirigir(){
		window.location.href = pagina;
	}
});
</script>
