<header class="headerLogin">
	<figure>
		<img src="/img/undac.png" alt="Logo" class="logoUniversidad">
	</figure>
	<div class="nombreUniversidad">
		Universidad Nacional <br>
		Daniel Alcides Carrión
	</div>
</header>

<div class="imagenFondo">

</div>

<div class="navegacion">
	<div class="logoUser">
		<figure>
			<img class="logoUserMuneco" src="/img/logoLogin.jpg" alt="LogoLogin">
		</figure>
	</div>
	<div class="bienvenido">
		<h4>BIENVENIDO - Inicio Sesión</h4>
	</div>
	<div class="botones">
		<form id="<?php  print $this->form->getname()?>"  name="<?php print $this->form->getname()?>" action="<?php print $this->form->getaction()?>" method="POST" enctype="application/x-www-form-urlencoded">
	    	<?php //print $this->form->eid ?>
	        <?php //print $this->form->oid ?>
	        <?php print $this->form->rid ?>		    
    		<?php print $this->form->usuario ?>
    		<?php print $this->form->clave?>
			<?php print $this->form->enviar?>
    	</form>
    	<?php if ($this->msgerror){?>
            <div style="color: red; border: 1px solid #zzz;padding-bottom: 30px;padding-top: 5px"><?php echo $this->msgerror?></div>
	    <?php } ?>
	</div>
</div>

<script>
$(function(){
	$('input[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$('select[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$("#oid").change(function() {
		var oid = $(this).val();
		var eid = $("#eid").val();
		$("#rid").load("/index/roles/eid/"+eid+"/oid/"+oid);
	});
	
	$("#usuario").keydown(function(event) {
		//alert(event.keyCode);
		if(event.shiftKey)
		{
			event.preventDefault();
		}
		if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 13 
				|| event.keyCode == 84 || event.keyCode == 77 || event.keyCode == 69 || event.keyCode == 80
				)    {
		}
		else {
			if (event.keyCode < 95) {
		    	if (event.keyCode < 48 || event.keyCode > 57) {
		        	event.preventDefault();
				}
			} 
			else {
		    	if (event.keyCode < 96 || event.keyCode > 105) {
		        	event.preventDefault();
				}
			}
		}
	});
});	
</script>

