<header class="headerLogin">
	<figure>
		<img src="/img/undac.png" alt="Logo" class="logoUniversidad">
	</figure>
	<div class="nombreUniversidad">
		Universidad Nacional <br>
		Daniel Alcides Carrión
	</div>
</header>
<div class="imagenFondo">
</div>

<div class="navegacion">

	<div class="logoUser">
		<figure>
			<img class="logoUserMuneco" src="/img/logoLogin.jpg" alt="LogoLogin">
		</figure>
	</div>
	<div class="bienvenido text-muted">
		BIENVENIDO <br><small class="text-muted">Inicie sesión...</small>
	</div>
	<div class="botones">
		<form name="<?php echo $this->form->getName();?>" action="<?php echo $this->form->getAction();?>" method="post" enctype="application/x-www-form-urlecncoded">
			<div class="">
				<span class="iconRol glyphicon text-muted"></span>
				<?php echo $this->form->rid ?>
			</div>
			<div class="userInput">
				<span class=" iconUser glyphicon text-muted"></span>
				<?php echo $this->form->usuario ?>
			</div>
			<div class="userInput">
				<span class="iconPass glyphicon text-muted"></span>
				<?php echo $this->form->clave ?>
			</div>
			<center><a href="#" id='change' class="text-primary">¿Olvidaste tu contraseña?</a></center>
			<?php echo $this->form->enviar ?>
			<p class="text-danger text-center"><?php echo $this->msgerror?></p>
		</form>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
	<div class="modal-dialog">
	    <div class="modal-content">
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title text-info" id="myModalLabel"><span class="glyphicon glyphicon-qrcode"></span> Recuperar Contraseña</h4>
		    </div>
			<div class="modal-body">
		    	<form name="frmchange" id ="frmchange" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
			    	<div class="row">
			    		<div class="col-md-4 col-md-offset-4 text-danger">
			    			<center><b>PASO 1</b></center>
			    			<hr style="margin-top:2px; margin-bottom:5px">
			    		</div>
			    		<div class="col-md-12">
			    			<span class="glyphicon glyphicon-info-sign text-success"></span><r class='text-success'> Recuerde que su correo electrónico debería estar registrado en el sistema.</r>
			    		</div><br><br><br><br>
			    		<div class="col-md-12">
			    			<div class="col-md-6 text-muted">
			    				<span class="glyphicon glyphicon-user text-primary"></span> Ingrese Cod. Mat. o Usuario
			    			</div>
			    			<div class="col-md-6">
			    				<input type="text" name='user1' id='user1' class='form-control' placeholder='11223344DC' maxlength="11" />
			    			</div>
			    			<div class="col-md-6 col-md-offset-6">
			    				<div id="smsuser"></div>
			    			</div>
			    		</div><br><br><br>
			    		<div class="col-md-12">
			    			<div class="col-md-6 text-muted">
			    				<span class="glyphicon glyphicon-envelope text-primary"></span> Ingrese su e-mail del sistema
			    			</div>
			    			<div class="col-md-6">
			    				<input type="text" name='mail' id='mail' class='form-control' placeholder='aaa_111@hotmail.com/gmail.com'/>
			    			</div>
			    			<div class="col-md-6 col-md-offset-6">
			    				<div id="smsmail"></div>
			    			</div>
			    		</div>
			    	</div><br>
			    	<div class="row">
			    		<div class="col-md-12">
			    			<div class="col-md-3 col-md-offset-4">
			    				<button type="button" class="comprobar btn btn-primary"></button>	
			    			</div>	
			    		</div>	
			    	</div><br>
			    	<div class="row">
			    		<div class="col-md-12 text-center">
			    			<div id="smsconf"></div>
			    		</div>	
			    	</div>
		    	</form>
			</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-log-out'></span> Cerrar</button>
		    	<div class="row">
			    	<div class="col-md-12 text-left">
		    			<span class='glyphicon glyphicon-home text-muted'></span><r class='text-muted'> Si no actualizó sus datos. Acercarse a la oficina de Informática.</r>
		    		</div>		    		
		    	</div>
		    </div>
	    </div>
	</div>
</div>

<script>
$(function(){
	$('#myModal').on('shown.bs.modal', function () {
		$(".comprobar").addClass('btn-primary');
	    $(".comprobar").removeClass('btn-default');
	    $(".comprobar").removeClass('btn-success');
	    $(".comprobar").removeClass('disabled');
		$("#user1").val(null);
		$("#mail").val(null);
		$("#smsuser").empty();
		$("#smsconf").empty();
		$(".comprobar").html("<span class='glyphicon glyphicon-transfer'></span> Comprobar");
  	});
	$('input[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$('select[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$("#oid").change(function() {
		var oid = $(this).val();
		var eid = $("#eid").val();
		$("#rid").load("/index/roles/eid/"+eid+"/oid/"+oid);
	});
	
	$("#usuario").keydown(function(event) {
		//alert(event.keyCode);
		if(event.shiftKey)
		{
			event.preventDefault();
		}
		if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 13 
				|| event.keyCode == 84 || event.keyCode == 77 || event.keyCode == 69 || event.keyCode == 80
				)    {
		}
		else {
			if (event.keyCode < 95) {
		    	if (event.keyCode < 48 || event.keyCode > 57) {
		        	event.preventDefault();
				}
			} 
			else {
		    	if (event.keyCode < 96 || event.keyCode > 105) {
		        	event.preventDefault();
				}
			}
		}
	});

	$("#change").on('click' , function(){
		$("#myModal").modal('show');
	});

	var s=0;
	$(".comprobar").on('click', function(){

		if (!$("#user1").val()) {
			$("#smsuser").html('<span class="text-danger">Ingrese un Usuario</span>');
		};
		if (!$("#mail").val()) {
			$("#smsmail").html('<span class="text-danger">Ingrese un E-mail</span>');	
		}
		else{
		    if($("#mail").val().indexOf('@', 0) == -1 || $("#mail").val().indexOf('.', 0) == -1) {
		        $("#smsmail").html('<span class="text-danger">Ingrese un E-mail correcto</span>');	
		    }
		    else{
		        var s=1;	    	
		    }			
		}


        if ($("#user1").val() && $("#mail").val() && s==1) {
		    $(".comprobar").removeClass('btn-primary');
		    $(".comprobar").addClass('btn-default');
	        $(".comprobar").html("<img src='/img/spinner.gif'> Comprobando...");

	        $.ajax({
		        type : 'post',
		        data : $("#frmchange").serialize(),
		        url  : '/default/index/recoverpassword/',
		        success: function(data){
		          	if (data.fail==true) {
		           		$("#smsuser").html("<span class='text-danger'>"+data.sms+"</span>");
		           		$("#smsmail").empty();
		           		$("#mail").val(null);
		            }
		            if (data.status==true) {
		              	$("#smsconf").html("<b>"+data.sms+"</b>");
		               	$(".comprobar").removeClass('btn-default').addClass('btn-success');
	                	$(".comprobar").html("<span class='glyphicon glyphicon-envelope'></span> Enviado");
	                	$(".comprobar").addClass('disabled');

	                	setTimeout(function(){
							$('.modal-body').empty().fadeIn(1000).load("/default/index/showtoken/eid/"+$.base64.encode(data.eid)+"/oid/"+$.base64.encode(data.oid)+"/escid/"+$.base64.encode(data.escid)+"/subid/"+$.base64.encode(data.subid)+"/pid/"+$.base64.encode(data.pid)+"/uid/"+$.base64.encode(data.uid)+"/");
						}, 3000);
	                }else{
	                	if (data.mail==true) {
		            		$("#smsmail").html("<span class='text-danger'>"+data.smsmail+"</span>");
	                	}
	                	else{
	                		if (data.fail!=true) {
	                			$("#smsmail").html("<span class='text-danger'>"+data.sms+"</span>");                			
	                		};
	                	}
	                	$(".comprobar").addClass('btn-primary');
					    $(".comprobar").removeClass('btn-default');
						$(".comprobar").html("<span class='glyphicon glyphicon-transfer'></span> Comprobar");
	            	}            
	            }	
		    });        		
        }
	});

	$("#user1").on('focus', function(){
		$("#smsuser").empty();
	});

	$("#mail").on('focus', function(){
		$("#smsmail").empty();
	});

	$('#frmchange').keypress(function(e){   
	    if(e == 13){
	      return false;
	    }
	});

	$('#user1,#mail').keypress(function(e){
	    if(e.which == 13){
	      return false;
	    }
	});
});	
</script>

