<div class='wrapper'>
	<div class='container-izquierda'>
    	<div class='logo'><img src="/img/logo_03.png"></div>
		<div id="banner-fade">
        	<ul class="bjqs">
          		<li><img src="/img/1.png" title=""></li>
          		<li><img src="/img/2.png" title=""></li>
          		<li><img src="/img/3.png" title=""></li>
          		<li><img src="/img/4.png" title=""></li>
          		<li><img src="/img/5.png" title=""></li>
        	</ul>
      	</div>
	</div>
	<div class='container-derecha'>
   		<div>
        	<h3>BIENVENIDO - Inicio Sesión</h3>
        <hr >
      	</div>
    	<div class='datos'>
    		<form id="<?php  print $this->form->getname()?>"  name="<?php print $this->form->getname()?>" action="<?php print $this->form->getaction()?>" method="POST" enctype="application/x-www-form-urlencoded">
		    	<?php //print $this->form->eid ?>
		        <?php //print $this->form->oid ?>
		        <?php print $this->form->rid ?>		    
	    		<?php print $this->form->usuario ?>
	    		<?php print $this->form->clave?>
				<?php print $this->form->enviar?>
	    		 
        	</form>
        	<?php if ($this->msgerror){?>
		                <div style="color: red; border: 1px solid #zzz;padding-bottom: 30px;padding-top: 5px"><?php echo $this->msgerror?></div>
		        <?php } 
		        ?>
      	</div>
	</div>
</div>

<script>
	$('input[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$('select[rel=tooltip]').tooltip({
	    placement: "right"
	});
	$("#oid").change(function() {
		var oid = $(this).val();
		var eid = $("#eid").val();
		$("#rid").load("/index/roles/eid/"+eid+"/oid/"+oid);
	});
	
		
</script>

