<form name="frmpassword" id ="frmpassword" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-danger">
			<center><b>PASO 3</b></center>
			<hr style="margin-top:2px; margin-bottom:5px">
		</div><br><br>
		<div class="col-md-12">
			<div class="col-md-5 text-muted">
				<span class="glyphicon glyphicon-lock text-primary"></span> Ingrese la nueva Contraseña
			</div>
			<div class="col-md-6">
				<input type="password" name='password1' id='password1' class='form-control' />
			</div>
			<div class="col-md-6 col-md-offset-5">
				<div id="smspassword1"></div>
			</div>
		</div><br><br><br>
		<div class="col-md-12">
			<div class="col-md-5 text-muted">
				<span class="glyphicon glyphicon-qrcode text-primary"></span> Repita la nueva contraseña
			</div>
			<div class="col-md-6">
				<input type="password" name='password2' id='password2' class='form-control' />
			</div>
			<div class="col-md-6 col-md-offset-5">
				<div id="smspassword2"></div>
			</div>
		</div>
	</div><br>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-7 col-md-offset-5 view">
				<input type="checkbox" name='mostrar1' id='mostrar1'/> <a href="#" id='clink'><span class='check text-muted'>Visualizar contraseñas ingresadas</span></a>				
			</div>
		</div>
	</div><br>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-3 col-md-offset-4">
				<button type="button" class="saved btn btn-success"><span class='glyphicon glyphicon-save'></span> Guardar</button>	
			</div>	
		</div>	
	</div><br>
	<input name="eid" id="eid" type="text" value="<?php echo $this->where['eid']?>" class='hide'>
	<input name="oid" id="oid" type="text" value="<?php echo $this->where['oid']?>" class='hide'>
	<input name="escid" id="escid" type="text" value="<?php echo $this->where['escid']?>" class='hide'>
	<input name="subid" id="subid" type="text" value="<?php echo $this->where['subid']?>" class='hide'>
	<input name="pid" id="pid" type="text" value="<?php echo $this->where['pid']?>" class='hide'>
	<input name="uid" id="uid" type="text" value="<?php echo $this->where['uid']?>" class='hide'>
	<div class="row">
		<div class="col-md-12 text-center">
			<div id="sms_saved"></div>
		</div>	
	</div>
</form>
<script type="text/javascript">
	$(function(){
		$("#mostrar1,#clink").on('click', function(){	

			if($("#mostrar1").is(':checked')) {  
				$("#password1").removeAttr('type');
				$('#password1').prop('type', 'text');

				$("#password2").removeAttr('type');
				$('#password2').prop('type', 'text');
	        } 
	        else{  
	          	$("#password1").removeAttr('type');
				$('#password1').prop('type', 'password');  

				$("#password2").removeAttr('type');
				$('#password2').prop('type', 'password');  
	        } 		
		});

		$(".saved").on('click', function(){
			if (!$("#password1").val()) {
				$("#smspassword1").html("<span class='text-danger'>Campo Obligatorio</span>");		
			};
			if (!$("#password2").val()) {
				$("#smspassword2").html("<span class='text-danger'>Campo Obligatorio</span>");		
			};

			if ($("#password1").val() && $("#password2").val()) {
				$.ajax({
			        type : 'post',
			        data : $("#frmpassword").serialize(),
			        url  : '/default/index/passwordsave/',
			        success: function(data){
			          	if (data.fail==true) {
			        		$("#smspassword2").html("<span class='text-danger'>"+data.sms1+"</span>");
			          	}
			          	else{
				          	if (data.status==true) {
				          		$("#sms_saved").html("<span class='text-success'><b>"+data.sms+"</b></span>");
				          		setTimeout(function(){
									$('#myModal').modal('hide');
								}, 2000);
								$('#myModal').on('hidden.bs.modal', function (e) {
								 	location.reload();
								});
				          	}
				          	else{
				          		$("#sms_saved").html("<span class='text-danger'><b> "+data.sms+"</b></span>");
				          	};		          		
			          	};
		            }
		        });				
			};

		});

		$("#password1, #password2").on('focus', function(){
			$("#smspassword1").empty();
			$("#smspassword2").empty();
		});

	});
</script>