<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Lista de Tutores');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/alumno/index" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>

<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
				
		</div>
	</div>
</div>