<?php $data_person=$this->data_person ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h5 class="panel-title">
        <span class='glyphicon glyphicon-eye-open'></span>
        <strong>CONDICIÓN DE MATRÍCULA | PERIODO <?php echo $this->perid ?></strong>
        <div class='pull-right'>
        <?php  echo $data_person['last_name0'].' '.$data_person['last_name1'].' '.$data_person['first_name'] ?>
        </div>
      </h5>
    </div>
    <div class="col-md-12 panel panel2 col21">
        <div class="col-md-12 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">CONDICION PARA AUMENTAR CREDITOS -- AUMENTAR SEMESTRES -- DEJARCURSO</h4>
            </div>
            <div class="col-md-3">
                <label>Aumentar semestres</label>
                <select id="nsem" name="nsem" class="form-control">
                    <option value="0">- Seleccione -</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>            
            </div>
            <div class="col-md-6"> 
                <label>Dejar Curso </label>
                <select id="dcurso" name="dcurso" class="form-control">
                    <option value="ns">- Seleccione -</option>
                        <?php
                        if($this->cursos){
                            foreach ($this->cursos as $cursos) {
                                $courseid_en=base64_encode($cursos['courseid']);?>
                                <option value="<?php echo $courseid_en?>"><?php echo $cursos['name']?></option>
                            <?php                        
                            }
                        }
                        ?>
                </select>            
            </div>
            <div class="col-md-3">
                <label>Aumentar creditos </label>
                <select id="credit" name="credit" class="form-control">
                    <option value="0">- Seleccione -</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                </select>            
            </div>
        </div>
        <div class="col-md-12 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">CONDICIÓN PARA NUMERO DE VECES DE MATRICULA</h4>
            </div>
            <div class="col-md-8"> 
                <label>Curso </label>
                <select id="curso" name="curso" class="form-control">
                    <option value="ns">- Seleccione -</option>
                        <?php
                        if($this->cursos){
                            foreach ($this->cursos as $cursos) {
                                $courseid_en=base64_encode($cursos['courseid']).';--;'.$cursos['veces'];?>
                                <option value="<?php echo $courseid_en?>"><?php echo $cursos['name']?></option>
                            <?php                        
                            }
                        }
                        ?>
                </select>                 
             </div>
            <div class="col-md-4"> 
                <label>Num de veces Matricula </span></label> 
                <div style="font-size: 23px;"><span class="label label-info form-control veces "></span></div>
                <!-- <span id="veces" class="label label-info"></span>   -->     
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-4 col-md-3">
            <a id="guardar" class="form-control btn btn-primary"
            uid = '<?php echo $this->uid?>'
            pid = '<?php echo $this->pid?>'
            escid = '<?php echo $this->escid?>'
            subid = '<?php echo $this->subid?>'
            perid = '<?php echo $this->perid?>'
            curid = '<?php echo $this->curid?>'
            ><span class="glyphicon glyphicon-floppy-disk"></span> AGREGAR</a>
        </div>
    </div>
    <br>
</div>
<div class="condition"></div>
<?php
if ($this->conditionsStudent){ ?>
<div class="panel panel-primary">
        <div class="panel-heading">
            <h5 class="panel-title"><span class='glyphicon glyphicon-th-list'></span><strong> DETALLE DE CONDICIÓN <span class="label label-default text-reght" ></span>
            </strong></h5>
        </div>
        <div class="conditions">
            
                <table class="table">
                    <tr class='tetx-center'>
                        <th>#</th>
                        <th>Detalle de Condicion</th>
                        <th>Opcion</th>
                    </tr>
                    <?php
                    $c=1;
                    foreach ($this->conditionsStudent as $conditions){  
                        if ($conditions['type']=='CO' || $conditions['type']=='LE'){
                            foreach ($this->cursos as $cursos) {
                                if($cursos['courseid']==$conditions['courseid']) {
                                    $coursename = $cursos['name'];
                                }                   
                            }
                        }
                        switch ($conditions['type']) {
                            case 'CO':  $detail = "Matricula condicional del curso ".$coursename;
                                        break;
                            case 'LE':  $detail = "Para dejar el curso ".$coursename;
                                        break;
                            case 'CR':  $detail = "Para adicionar ".$conditions['amount']." creditos ";                      
                                        break;
                            case 'SE':  $detail = "Para adicionar ".$conditions['amount']." semestres ";
                                        break;
                        }
                        ?>
                        <tr>
                        <td><?php echo $c ?></td>
                        <td><?php echo $detail ?></td>
                        <td>
                        <a class="eliminar"
                        uid = '<?php echo $conditions['uid']?>'
                        pid = '<?php echo $conditions['pid']?>'
                        escid = '<?php echo $conditions['escid']?>'
                        subid = '<?php echo $conditions['subid']?>'
                        perid = '<?php echo $conditions['perid']?>'
                        type = '<?php echo $conditions['type']?>'
                        clss="<?php echo $c.'tr' ?>"
                        ><span class="glyphicon glyphicon-trash"></span> Eliminar</a>
                        </td>
                        </tr>
                    <?php
                    $coursename = "";
                    $c++;
                    } ?>         
                </table>
        </div>
    </div>
<?php 
}?>
<script>

    $('#curso').change(function(){
        var valcod = $(this).val();
        var xx1 = valcod.split(";--;");
        var curso = xx1[0];
        var nveces = xx1[1];
        $(".veces").html(nveces)

    });

    $('#guardar').click(function(){
        var nsem = $('#nsem').val();
        var dcurso = $('#dcurso').val();
        var credit =$('#credit').val();
        var valcurso = $('#curso').val();
        var xx1 = valcurso.split(";--;");
        var curso = xx1[0];
        var nveces =$('#nveces').val();
        var sel = 'ns';
        if (nsem!='0') {sel='s'};
        if (credit!='0') {sel='s'};
        if (dcurso!='ns') {sel='s'};
        if (curso!='ns') {sel='s'};
        if (sel=='ns') {
            alert('agregue una condicion');
            return false;
        };
        var data_ajax = {
            'uid' : $(this).attr('uid'),
            'pid' : $(this).attr('pid'),
            'escid' : $(this).attr('escid'),
            'subid' : $(this).attr('subid'),
            'perid' :  $(this).attr('perid'),
            'nsem' : nsem,
            'dcurso' : dcurso,
            'credit' : credit,
            'curso' : curso,
            'curid' : $(this).attr('curid'),
        };
        $.ajax({
            type : "post",
            url : "/rfacultad/condition/guardar/",
            data : data_ajax,
            success : function(data){
                $(".condition").html("<div class='alert alert-success conditions' role='alert'<h3>Se ha agregado la condicion</h3></div>");
                setTimeout(function(){
                    $("#modal").modal('hide');
                }, 1000);

            }
        }); 
    });
    $(".eliminar").click(function(e){
        e.preventDefault();
        cls=$(this).parent().parent();
        var ajax_data = {
            'uid' : $(this).attr('uid'),
            'pid' : $(this).attr('pid'),
            'escid' : $(this).attr('escid'),
            'subid' : $(this).attr('subid'),
            'perid' : $(this).attr('perid'),
            'type' : $(this).attr('type'),
        };
        $.ajax({
            type : "post",
            url : "/rfacultad/condition/delete/",
            data : ajax_data,
            success : function(data){
                cls.fadeOut("fast");
            }
        }); 
    });
</script>
