<style type="text/css">
    .modal-dialog
    {
        width: 900px;
    }
</style>
<?php //print_r($this->datos);exit(); ?>

<div class="modal fade" id='modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body bodd">
        <p>Cargano informacion.&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-log-out'></span> Salir</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<table class="table table-hover table-condensed">
        <thead>
        <tr>
                <th >Nro</th>
                <th >Código</th>
                <th >Apellidos y Nombres</th>
                <th >Escuela</th>
                <th >Resolución</th>
                <th style="width: 100px">Condición</th>
        </tr>
        </thead>
        <tbody>
                <?php
                $i=1;
                if ($this->datos){
                  $where['perid']= $this->perid;
                   foreach ($this->datos as $datos){
                       $where['eid']=$datos['eid'];
                       $where['oid']=$datos['oid'];
                       $where['uid']=$datos['uid'];
                       $where['pid']=$datos['pid'];
                       $where['subid']=$datos['subid'];
                       $where['escid']=$datos['escid'];
                       $where['regid'] = $datos['uid'].$this->perid;
                       ?>
                        <tr>
                            <td><?php echo $i;?></td>
                            <td><?php echo $datos['uid'];?></td>
                            <td><?php echo $datos['last_name0']." ".$datos['last_name1'].", ".$datos['first_name'];?></td>
                            <td><?php echo $datos['escid']?></td>
                            <?php $datos['doc_authorize']=(isset($datos['doc_authorize']))?$datos['doc_authorize']:null;?>
                            <td><?php echo $datos['doc_authorize']?></td>
                            <td>
                            <?php
                            $mat = new Api_Model_DbTable_Registration();
                            $rmat = $mat->_getOne($where);
                            if ($rmat){
                                if (trim($rmat['state'])=="B"){?>

                                    <?php
                                        $condicion=$this->condicion;
                                        $url= "uid/".base64_encode($datos['uid'])."/pid/".base64_encode($datos['pid'])."/escid/".base64_encode($datos['escid'])."/subid/".base64_encode($datos['subid'])."/condi/".base64_encode($condicion);
                                    ?>
                                    <!-- /rfacultad/condition/detail/<?php echo $url?> -->
                                    <a id='a<?php echo $datos['uid']?>' data-toggle="modal" href = "#Modalcondition" class='<?php if ($this->condicion =='C') {echo 'btn   btn-warning ';} if ($this->condicion =='S') {echo 'btn   btn-primary';} ?>' aurl="/rfacultad/condition/detail/<?php echo $url?>">
                                    <i class=" icon-pencil icon-white"></i>
                                    <?php if ($this->condicion =='C') {?><?php echo 'Agregar Condición';} if ($this->condicion =='S') {echo 'Crear';}?></a>
                                    <script type="text/javascript">
                                        $('#a<?php echo $datos['uid']?>').click(function(){
                                            var url = $(this).attr('aurl')
                                            //console.log(url);
                                            //$("#view1").load(url);
                                            $("#modal").modal('show');
                                            $(".bodd").load(url);
                                        });
                                    </script>
                                <?php
                                } else {?>
                                    <span style="color: red">Pre matriculado</span>
                                <?php } ?>
                            <?php
                            }
                            else {?>
                                <span style="color: blue">Sin Matricula</span>
                            <?php
                            }
                            ?>
                            </td>
                        </tr>
                       <?php
              $i++;
                    }
                }
                ?>
            </tbody>
    </table>
        <div style="clear:both"></div>


