<a style="float:right" href="#" id="cancelar"><font color="red"><h4>X</h4></font></a> 
  <table class="table  table-bordered">
 <thead>
        <tr style="font-size: 12px" >
                
                <th >CODIGO</th>
                <th >CURSO</th>
                <th >TURNO</th>

                <th >CREDITOS</th>
                <th >SEMESTRE</th>
                <th >OPERACIONES</th>
        </tr>
 </thead>
<?php
    if ($this->cursos) 
    {   $g=0;
       foreach ($this->cursos as $datos)    
        {  
        if($datos['llevo']=='0'){
          ?>
            <tr style="font-size: 10px"  >
                <td><?php echo $datos['courseid'];?></td>
                <td><?php echo $datos['name'];?></td>
                <td><?php echo $datos['turno'];?></td>
                <td><?php echo $datos['credits'];?></td>
                <td><?php echo $datos['semid']?></td>
                <td><input type="checkbox" name="listacursos[]" value="<?php echo $datos['courseid'];?>"> Eliminar</td>               
                 
            </tr>
           <?php
        $g++;
        }    
         }
    }
    ?>

</div>
<div id="carga"></div>
<script type="text/javascript">
 $("#quitar").click(function()
{       
    $("#cursos").show(100);
});
$("#cancelar").click(function(){
        $("#cursos").hide("slow");
 
});
 </script>
