<div>
	<!-- <a style="float:right" class="btn btn-danger">Cerrar</a> -->
    <a style="float:right" rel="tooltip" title='Agregue Nuevo registro' href="#"  class="btn btn-primary" onclick="javascript: window.open('/default/rol/nuevo','Crear nuevo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=720,height=600')">
    <i class="icon-pencil"></i>Nuevo</a>
</div>
<table class="table table-bordered table-striped table-condensed span10">
    <tr>
        <th class="span1"><center>#</center></th>
        <th class="span1"><center>Cod.</center></th>   
        <th class="span1"><center>Nombre</center></th>        
        <th class="span1"><center>Estado</center></th>
        <th class="span1"><center>Operaciones</center></th>         
    </tr>
<?php
    $r=0;
    foreach ($this->data as $rol){
        $r++;
        $rid=$rol['rid'];
        // $oid=$rol['oid'];
        // $eid=$rol['eid'];
        $name=$rol['name'];
        $estado=$rol['state'];
        // $numdoc=$docente['numdoc'];        
        ?>       
            <tr id="tr_<?php echo $perid.$r?>">
                <td ><center><?php echo $r?></center></td>                    
                <td ><center><?php echo $rid?></center></td>
                <td ><?php echo $name?></td>                
                <td ><?php echo $estado?></td> 
            </tr>
          <?php 
        }
?>
</table>