<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-certificate"></span> CONVALIDACIÓN, DIRIGIDOS Y SUBSANACIÓN');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="form-control btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Regresar </a>');?>
<br>

<?php if ($this->usuario!='AD') { ?>
	<div>
		
		<table class="table table-striped table-condensed">
			<tr>
				<td class="col-xs-3">
					<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Ingrese Código de Matricula: </p>
				</td>
			<td class="col-xs-5">
				<div class="col-xs-9">
					<input id="uid" type="text" class="form-control" maxlength="10"  onkeypress="return soloNumero(event)" placeholder="Código De Alumno">
				</div>
			</td>
				<td class="col-xs-3">
					<div class="checkbox">
						<label>
						<input id="checkbox" type="checkbox">
						<?php echo date('Y')-1 ?>
						</label>
					</div>
				</td>
				<td class="col-xs-1">
					<a id="search" href="#" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Buscar</a>
				</td>
			</tr>
		</table>
	</div>
	<script type="text/javascript">
		$("#search").click(function(){
			var uid=$("#uid").val();
			var anios="<?php echo date('Y') ?>";
			anio = anios.substring(2);
			if (uid!="") {
				$("#student").html("<img src='/img/spinner.gif'>Cargando...");
				if ($('#checkbox').is(':checked')) {
					$("#student").load("/record/directed/student/uid/"+uid+"/perid/13");
				}else{
					$("#student").load("/record/directed/student/uid/"+uid+"/perid/"+anio );
				}
			}else{
				alert("Ingrese el Código de Matricula.");
				return false;
			};
		});
	</script>

<?php } elseif ($this->usuario=='AD'){ ?>
<div>
	<table class="table table-striped table-condensed">
		<tr>
			<td class="col-xs-3">
				<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Ingrese Código de Matricula y seleccione un año para comenzar</p>
			</td>
			<td class="col-lg-5">
				<div class="col-lg-9">
					<input id="uid" type="text" class="form-control" maxlength="10"  onkeypress="return soloNumero(event)" placeholder="Código De Alumno">
				</div>
			</td>
			<td class="col-xs-3">
			 <select id="anios" class='form-control' name="anios" style="width: 90px" >
                    <?php 
                    $anio= date('Y')-1;
                    $i=0;
                    for($i = ($anio+1);$i>=1990;$i--){
                        if ($anio==$i) $t = "selected";
                        else $t="";
                        ?>            
                    <option value="<?php echo $i?>"<?php echo $t?>><?php echo $i?></option>
                    <?php }?>
                </select>
            </td>
			<td class="col-xs-1">
				<a id="search" href="#" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Buscar</a>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript" >
	$("#search").click(function(){
	$("#student").html("<img src='/img/spinner.gif'>Cargando...");
	var uid=$("#uid").val();
	var anios=$("#anios").val();
	if (uid!="") {
		$("#student").load("/record/directed/student/uid/"+uid+"/perid/"+anios);
	}else{
		alert("Ingrese el Código de Matricula.");
		return false;
	};
});
</script>

<?php } ?>

<div id="student" class="text-center"></div>


<script >
function soloNumero(e){
	key = e.keyCode || e.which;
	tecla = String.fromCharCode(key).toLowerCase();
	letras = "0123456789";
	especiales = [8,37,39,46];
	tecla_especial = false
	for(var i in especiales){
	    if(key == especiales[i]){
			tecla_especial = true;
	  		break;
	    } 
	}
    if(letras.indexOf(tecla)==-1 && !tecla_especial)
    return false;
};
</script>