<div id="Datos">
    <form id="frmdirected" name="frmdirected" action="/record/directed/savedirected/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
    <table class="table table-striped table-hover">
        <tr>
            <th><center>Currículas</center></th>
            <th><center>Asignatura</center></th>
            <th colspan="3"><center>Reportes</center></th>
        </tr>
        <tr>
            <td>
                <select id="curid" class="form-control">
                    <option value="">-Seleccione-</option>
                    <?php
                    foreach ($this->curriculas  as $curricula){ ?>
                        <option value="<?php echo $curricula['curid']."--".$curricula['escid']."--".$curricula['subid']?>"><?php echo $curricula['curid']?></option>
                        <?php
                    }?>
                </select>
            </td>
            <td>
                <select id="courseid" name="courseid" class="form-control">
                    <option value="">- Seleccione Asignatura -</option>
                </select>
            </td>
            <td>
                <center>
                    <a href="#" class="btn btn-default" id="vermatriculadoscurso"><span class="glyphicon glyphicon-list-alt"></span> Matriculados en la Asignatura</a>
                </center>
            </td>
            <td>
                <a href="#total_registered"  data-toggle="modal" class="btn btn-default"><span class="glyphicon glyphicon-book"></span> Matriculas Totales</a>
            </td>
            <td>
                <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-list"></span> Cursos Pendientes</a>
            </td>
        </tr>
        <tr>
            <th class="col-lg-3"><center>Ingrese la Nota</center></th>
            <th class="col-lg-7"><center>Recibo</center></th>
            <th colspan="3"><center>Resolución</center></th>
        </tr>
        <tr>
            <td>
                <center>
                    <input type="text" id="nota" name="nota" class="form-control" style="width:50px" onkeypress="return soloNumero(event)"><label class="msg text-error"></label>
                </center>
            </td>
            <td>
                <center>
                    <input type="text" id="recibo" name="recibo" class="form-control" onBlur="CheckUserName(this);" style="width:200px" onkeypress="return soloNumero(event)">
                </center>
            </td>
            <td colspan="3">
                <center>
                    <input type="text" id="resolucion" name="resolucion" class="form-control" style="width:350px">
                </center>
            </td>
        </tr>
        <tr>
            <th><center>Seleccione el Turno</center></th>
            <th><center>Seleccione Escuela / Docente</center></th>
            <th colspan="3"><center>Seleccione el Docente</center></th>
        </tr>
        <tr>
            <td>
                <center>
                    <select id="turno" name="turno" class="form-control" style="width:80px">
                        <option value="A">A</option>
                        <option value="B">B</option>
                        <option value="C">C</option>
                        <option value="D">D</option>
                        <option value="E">E</option>
                        <option value="F">F</option>
                        <option value="G">G</option>
                        <option value="H">H</option>
                        <option value="I">I</option>
                        <option value="J">J</option>
                        <option value="K">K</option>
                        <option value="L">L</option>
                        <option value="M">M</option>
                        <option value="N">N</option>
                        <option value="O">O</option>
                        <option value="P">P</option>
                        <option value="R">R</option>
                        <option value="S">S</option>
                    </select>
                </center>
            </td>
            <td>
                <select id="escid" class="form-control">
                    <option value="">- Seleccione Escuela -</option>
                    <?php 
                    if ($this->lescuelas){
                        foreach ($this->lescuelas as $escu){ ?>
                            <option value="<?php echo $escu['escid'].";--;".$escu['subid']?>"><?php echo $escu['name']?></option>
                        <?php                                 
                        }
                    } ?>
                </select>
            </td>
            <td colspan="3">
                <center>
                    <select id='docente_reg' name='docente_reg' class="form-control" style="width:350px">
                        <option value="">- Seleccione Docente -</option>
                    </select>
                </center>
            </td>
        </tr>
        <tr>
            <td colspan="5">
                <center>
                    <a href="#" class="btn btn-info" id="registerstudent"><span class="glyphicon glyphicon-floppy-disk"></span> Guardar Curso</a>
                </center>
            </td>
        </tr>
        <input type="hidden" name="perid" value="<?php echo $this->perid?>">
        <input type="hidden" name="subid" value="<?php echo $this->subid?>">
        <input type="hidden" name="escid" value="<?php echo $this->escid?>">
        <input type="hidden" name="uid" value="<?php echo $this->uid?>">
        <input type="hidden" name="pid" value="<?php echo $this->pid?>">
    </table>
    </form>
    <div id="header_cursos"></div>
    <div id="header_alumnos"></div>
</div>

<?php
if ($this->cursosconvalidados){ ?>
<div id="lista">
    <div><h5><center><b>CURSOS REALIZADOS</b></center></h5></div>
    <div>
        <div style="display: block; height: 150px; overflow: auto;margin: 0px;" >
            <table class="table table-hover">
                <tr style="background: #ccc; color: #000000;">
                    <th>#</th> 
                    <th>Currícula</th>
                    <th>Código</th>
                    <th>Nombre Curso</th>
                    <th>Creditos</th>
                    <th>Turno</th>
                    <th>Resolución</th>
                    <th>Recibo</th>
                    <th>Notafinal</th>
                    <th>Pre-registro</th>
                    <th>Modificar</th>
                </tr>
                <?php
                    $i=1;
                    foreach ($this->cursosconvalidados as $convalidado){ ?>
                        <tr>
                            <td><?php echo $i;?></td>
                            <td><center><?php echo $convalidado['curid'];?></center></td>
                            <td><center><?php echo $convalidado['courseid'];?></center></td>
                            <td><?php echo $convalidado['name_course'];?></td>
                            <td><center><?php echo $convalidado['credits'];?></center></td>
                            <td><center><?php echo $convalidado['turno'];?></center></td>
                            <td><?php echo $convalidado['document_auth'];?></td>
                            <td size="12px"><?php echo $convalidado['receipt'];?></td>
                            <td><center><?php echo $convalidado['notafinal'];?></center></td>
                            <td>
                                <center>
                                    <a href="/record/directed/print/perid/<?php echo base64_encode($this->perid) ?>/escid/<?php echo base64_encode($this->escid) ?>/subid/<?php echo base64_encode($this->subid) ?>/uid/<?php echo base64_encode($this->uid) ?>/pid/<?php echo base64_encode($this->pid) ?>/courseid/<?php echo base64_encode($convalidado['courseid']) ?>/curid/<?php echo base64_encode($convalidado['curid']) ?>/turno/<?php echo base64_encode($convalidado['turno']) ?> "><span class="glyphicon glyphicon-print"></span></a>
                                </center>
                            </td>
                            <?php  
                             if ($convalidado['state']<>'C' and $convalidado['state_record']<>'C'){ ?>
                            <td>
                                <a id="modifyregister_<?php echo $i?>" data-toggle="modal" href="#modify" title="Modificar el Registro."><span class="glyphicon glyphicon-pencil"></span></a>
                            </td>
                            <script type="text/javascript">
                            $("#modifyregister_<?php echo $i?>").click(function(){
                                $("#notamodify").val("<?php echo $this->cursosconvalidados[$i-1]['notafinal']?>");
                                $("#recibomodify").val("<?php echo $this->cursosconvalidados[$i-1]['receipt']?>");
                                $("#resolmodify").val("<?php echo $this->cursosconvalidados[$i-1]['document_auth']?>");
                                $("#regidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['regid']?>");
                                $("#courseidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['courseid']?>");
                                $("#namecourseidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['name_course']?>");
                                $("#curidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['curid']?>");
                                $("#escidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['escid']?>");
                                $("#peridmodify").val("<?php echo $this->cursosconvalidados[$i-1]['perid']?>");
                                $("#turnomodify").val("<?php echo $this->cursosconvalidados[$i-1]['turno']?>");
                                $("#subidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['subid']?>");
                                $("#uidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['uid']?>");
                                $("#pidmodify").val("<?php echo $this->cursosconvalidados[$i-1]['pid']?>");
                            });
                            </script>
                            <?php 
                            }else{ ?>
                            <td>
                                <a href="#" title="No se puede Modificar el Registro."><span class="glyphicon glyphicon-ban-circle"></span></a>
                            </td>
                            <?php
                            }?>
                        </tr>
                        <?php
                        $i++;
                    } ?>
            </table>
        </div>        
    </div> 
</div>
<?php
} ?>

<div class="modal fade" id="modify" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<form id="frmmodifyregister" name="frmmodifyregister" action="/record/directed/modifyregister/option/M" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">MODIFICAR REGISTRO</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>Currícula:</th>
                        <td>
                            <input id="curidmodify" name="curid" type="text" class="form-control" readonly>
                        </td>
                        <th>Turno:</th>
                        <td>
                            <input id="turnomodify" name="turno" type="text" class="form-control" readonly>
                        </td>
                    </tr>
                    <tr>
                        <th>Asignatura:</th>
                        <td colspan="3">
                            <input id="namecourseidmodify" type="text" class="form-control" readonly>
                        </td>
                    </tr>
                    <tr>
                        <th>Nota:</th>
                        <td>
                            <input id="notamodify" name="notafinal" type="text" class="form-control" style="width:50px" onkeypress="return soloNumero(event)"><label class="msg text-error"></label>
                        </td>
                        <th>Recibo:</th>
                        <td>
                            <input id="recibomodify" name="receipt" type="text" class="form-control" style="width:200px" onkeypress="return soloNumero(event)">
                        </td>
                    </tr>
                    <tr>
                        <th>Resolución:</th>
                        <td colspan="3">
                            <input id="resolmodify" name="resolution" type="text" class="form-control" style="width:350px">
                        </td>
                    </tr>
                    <tr>
                        <th>Fecha Acta:</th>
                        <td colspan="3">
                            <input id="f_acta" name="f_acta" type="text" class="form-control" style="width:150px">
                        </td>
                    </tr>
                </table>
                <input id="regidmodify" name="regid" type="hidden">
                <input id="courseidmodify" name="courseid" type="hidden">
                <input id="escidmodify" name="escid" type="hidden">
                <input id="peridmodify" name="perid" type="hidden">
                <input id="subidmodify" name="subid" type="hidden">
                <input id="uidmodify" name="uid" type="hidden">
                <input id="pidmodify" name="pid" type="hidden">
            </div>
            <div class="modal-footer">
                <a href="#" id="savemodify" class="btn btn-success">Guardar</a>
                <a href="#" id="closerecord" class="btn btn-warning">Cerrar Acta</a>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</form>
</div>

<div class="modal fade" id="total_registered" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span class="glyphicon glyphicon-book"></span> - HISTORIAL DE MATRICULAS</h4>
            </div>
            <div class="modal-body">
                <div>
                    <ul class="nav nav-tabs" id="directedTab">
                        <li class="active"><a href="#course_curri"><h5><span class="glyphicon glyphicon-list-alt"></span> - Asignaturas Por Currícula</h5></a></li>
                        <li><a href="#registereds"><h5><span class="glyphicon glyphicon-list"></span> - Matriculas Realizadas</h5></a></li>
                    </ul>
                    <div class="tab-content" style="margin: 0px; padding: 0px; min-height: 500px;" >
                        <div class="tab-pane active" id="course_curri" ></div>
                        <div class="tab-pane" id="registereds"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" id="close_new_cur" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    .modal-dialog { width: 900px; }
    #course_curri, #registereds { margin-top: 15px; }
</style>

<script>
$(function () {
    $("#course_curri").html("<img src='/img/spinner.gif'>Cargando...");
    $("#course_curri").load("/profile/private/studentsignpercur/pid/<?php echo $this->pid?>/uid/<?php echo $this->uid?>/escid/<?php echo $this->escid?>/subid/<?php echo $this->subid?>/eid/<?php echo $this->eid?>/oid/<?php echo $this->oid?>");
    $("#registereds").html("<img src='/img/spinner.gif'>Cargando...");
    $("#registereds").load("/register/registerealized/index/pid/<?php echo $this->pid?>/uid/<?php echo $this->uid?>/escid/<?php echo $this->escid?>/subid/<?php echo $this->subid?>/perid/<?php echo $this->perid?>/rid/AL");

    $('#directedTab a').click(function (e) {
        e.preventDefault()
        $(this).tab('show');
    });
});
</script>

<script>
$("#f_acta").datepicker();

$("#savemodify").click(function(){
    $("#header_cursos").hide();
    $("#lista").hide();
    $("#frmmodifyregister").submit();
});

$('#frmmodifyregister').submit(function() {  
    $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) { 
            $('#header_alumnos').html(data);  
        }
    });          
    return false;
});

 $("#curid").change(function(){
    var curricula = $(this).val();
    if (curricula=="") {
        alert("Seleccione Currícula");
        return false;
    };
    var tmp = curricula.split('--');
    var curid= tmp[0];
    var escid= tmp[1];
    var subid= tmp[2];
    var url="/record/directed/coursesxcurricula/curid/"+curid+"/escid/"+escid+"/subid/"+subid;
    $("#courseid").load(url);
}); 

$("#vermatriculadoscurso").click(function(){    
    var curso = $("#courseid").val();
    if (curso=="") {
        alert("Seleccione un Curso.");
        return false;
    };
    var perid = "<?php echo $this->perid?>";
    var subid = "<?php echo $this->subid?>";
    var escid = "<?php echo $this->escid?>";
    var tmp=curso.split("--");
    var cursoid=tmp[0];
    var curid=tmp[1];
    var url = "/record/directed/viewregisteredcourse/subid/"+subid+"/escid/"+escid+"/curid/"+curid+"/courseid/"+cursoid+"/perid/"+perid;
    $("#header_cursos").html("<img src='/img/spinner.gif'>Cargando..."); 
    $("#header_cursos").load(url);
});

$("#escid").change(function(){
    var escuela = $(this).val();
    if (escuela=="") {
        alert("Seleccione una Escuela.");
        return false;
    };
    tmp=escuela.split(';--;');
    escid=tmp[0];
    $("#docente_reg").load("/record/directed/teacherxschool/escid/"+escid);
});

$("#registerstudent").click(function(){
    $("#header_alumnos").html("<img src='/img/spinner.gif'>Cargando..."); 
    $('#frmdirected').submit();
});

$('#frmdirected').submit(function() {  
    $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) { 
            $("#header_cursos").hide();
            $("#lista").hide();
            $('#header_alumnos').html(data);
        }
    });          
    return false;
});

$("#closerecord").click(function(){
    var f_acta = $("#f_acta").val();
    var perid = $("#peridmodify").val();
    var courseid = $("#courseidmodify").val();
    var escid = $("#escidmodify").val();
    var subid = $("#subidmodify").val();
    var curid = $("#curidmodify").val();
    var turno = $("#turnomodify").val();
    var uid = $("#uidmodify").val();
    var pid = $("#pidmodify").val();
    if (f_acta=="") {
        alert("Seleccione la fecha de Cierre de Acta.");
        return false;
    };
    var tmp = f_acta.split("/");
    var f_acta = tmp[2]+"-"+tmp[1]+"-"+tmp[0];
    var url = "/record/directed/modifyregister/courseid/"+courseid+"/perid/"+perid+"/escid/"+escid+"/subid/"+subid+"/curid/"+curid+"/turno/"+turno+"/uid/"+uid+"/pid/"+pid+"/f_acta/"+f_acta+"/option/C";
    // alert(url);
    $("#header_cursos").hide();
    $("#lista").hide();
    $("#header_alumnos").html("<img src='/img/spinner.gif'>Cargando..."); 
    $("#header_alumnos").load(url);
});

$("#nota, #notamodify").blur(function(){
    var vnota = $(this).val();
    if ( vnota > 20 || vnota < -3 ){
        $("#nota, #notamodify").val("");
        $(".msg").html("* Ingrese de 0 a 20");
    }                   
});

var total_letras_notas = 2;
$('#nota, #notamodify').keyup(function(){
    var longitud = $(this).val().length;
    var resto = total_letras_notas - longitud;
    $('#numero').html(resto);
    if(resto <= 0) $('#nota, #notamodify').attr("maxlength", 2);
});

var total_letras_recibo = 12;
$('#recibo, #recibomodify').keyup(function(){
    var longi = $(this).val().length;
    var rest = total_letras_recibo - longi;
    $('#numero').html(rest);
    if(rest <= 0) $('#recibo, #recibomodify').attr("maxlength", 12);
});

$("#resolucion, #resolmodify").keyup(function(){
    var r = $(this).val();
    $("#resolucion, #resolmodify").val(r.toUpperCase());
});

function CheckUserName(ele) {
    if (/\s/.test(ele.value)) alert("No se permiten espacios en blanco.");
}

function soloNumero(e){
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = "0123456789";
    especiales = [8,37,39,46];
    tecla_especial = false
    for(var i in especiales){
        if(key == especiales[i]){
            tecla_especial = true;
            break;
        } 
    }
    if(letras.indexOf(tecla)==-1 && !tecla_especial)
    return false;
};
</script>