<?php
if ($this->cursosconvalidados){ ?>
<div id="lista">
    <div><h5><center><b>CURSOS REALIZADOS</b></center></h5></div>
    <div>
        <div style="display: block; height: 150px; overflow: auto;margin: 0px;" >
            <table class="table table-hover">
                <tr style="background: #ccc; color: #000000;">
                    <th>#</th> 
                    <th>Currícula</th>
                    <th>Código</th>
                    <th>Nombre Curso</th>
                    <th>Creditos</th>
                    <th>Turno</th>
                    <th>Resolución</th>
                    <th>Recibo</th>
                    <th>Notafinal</th>
                    <th>Pre-registro</th>
                    <th>Modificar</th>
                </tr>
                <?php
                    $i=1;
                    foreach ($this->cursosconvalidados as $convalidado){ ?>
                        <tr>
                            <td><?php echo $i;?></td>
                            <td><center><?php echo $convalidado['curid'];?></center></td>
                            <td><center><?php echo $convalidado['courseid'];?></center></td>
                            <td><?php echo $convalidado['name_course'];?></td>
                            <td><center><?php echo $convalidado['credits'];?></center></td>
                            <td><center><?php echo $convalidado['turno'];?></center></td>
                            <td><?php echo $convalidado['document_auth'];?></td>
                            <td size="12px"><?php echo $convalidado['receipt'];?></td>
                            <td><center><?php echo $convalidado['notafinal'];?></center></td>
                            <td>
                                <center>
                                    <!-- <a target="black" style="float:right" href="/rfacultad/subsanacion/imprimir/perid/<?php echo $this->perid ?>/escid/<?php echo $this->escid ?>/subid/<?php echo $this->subid ?>/uid/<?php echo $this->uid ?>/pid/<?php echo $this->pid ?>/courseid/<?php echo $convalidado['courseid'] ?>/curid/<?php echo $convalidado['curid']?>/turno/<?php echo $convalidado['turno'] ?> "><img src="/img/pdf.png"></a> -->
                                </center>
                            </td>
                            <?php  
                             if ($convalidado['state']<>'C'){ ?>
                            <td>
                                <a href="#" onclick="javascript: window.open('/record/directed/modifyregister/regid/<?php echo base64_encode($convalidado['regid'])?>/courseid/<?php echo base64_encode($convalidado['courseid'])?>/curid/<?php echo base64_encode($convalidado['curid'])?>/escid/<?php echo base64_encode($convalidado['escid'])?>/perid/<?php echo base64_encode($convalidado['perid'])?>/uid/<?php echo base64_encode($convalidado['uid'])?>/pid/<?php echo base64_encode($convalidado['pid'])?>/turno/<?php echo base64_encode($convalidado['turno'])?>/subid/<?php echo base64_encode($convalidado['subid'])?>','Modificación Alumno','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=700,height=600')"><i class="icon-pencil"></i></a>
                            </td>
                            <?php 
                            } ?>
                        </tr>
                        <?php
                        $i++;
                    } ?>
            </table>
        </div>        
    </div> 
</div>
<?php
} ?>
