
<?php
if ($this->user) { 
	$whereesc['eid']=$this->user['eid'];
	$whereesc['oid']=$this->user['oid'];
	$whereesc['escid']=$this->user['escid'];
	$whereesc['subid']=$this->user['subid'];
	$esc= new Api_Model_DbTable_Speciality();
	$datesc=$esc->_getOne($whereesc);
	$wheresub['eid']=$this->user['eid'];
	$wheresub['oid']=$this->user['oid'];
	$wheresub['subid']=$this->user['subid'];
	$sub= new Api_Model_DbTable_Subsidiary();
	$datsub=$sub->_getOne($wheresub)?>
	
	<div class="panel">
		<div class="col-xs-2 col1">
			<span id="titu1">ALUMNO:</span>
		</div>
		<div class="col-xs-7 col2" >
			<div class="col-xs-12">
				<span class="glyphicon glyphicon-user"></span> <?php echo $this->user['last_name0']." ".$this->user['last_name1'].", ".$this->user['first_name']?>
			</div>
			<div class="col-xs-12">
				Cod: <?php echo $this->user['uid']?>
			</div>
			<div class="col-xs-12">
				DNI: <?php echo $this->user['pid']?>
			</div>
			<div class="col-xs-12">
				<p class="escuela">Escuela Profecional de:
				<?php echo $datesc['name']?>-
				<?php echo $datsub['name']?></p>
			</div>
		</div>
		<div class="col-xs-3 col3">
			<div class="col-xs-12">
			<p class="text-muted"><span class="glyphicon glyphicon-info-sign"></span> Seleccione un <span class="text-success">Periodo</span> al cual ingresara el <span class="text-success">Curso</span></p>
				<p id="Periodo" class=""></p>
				<select id="perid" class="form-control">
					<?php
					if ($this->periods) { ?>
						<option value="">- Seleccione periodo-</option>
						<?php
						foreach ($this->periods as $periods) { ?>
							<option name="selec" value="<?php echo $periods['perid']?>"><?php echo $periods['perid']." | ".$periods['name']?></option>
						<?php
						}
					}else{ ?>
						<option value="">No hay periodos.</option>
					<?php 
					}?>
				</select>
			</div>
			<div>
				<button id="addcourse" class="btn btn-success" href="#"><span class="glyphicon glyphicon-plus"></span> Agregar</button>
			</div>
		</div>
	</div>

<?php
}else{ ?>
<div class="alert alert-info">
	<b>Información: </b>El alumno no se encuentra registrado en el sistema o ingreso el Código de Matricula erróneo.
</div>
<?php
}?>
<div id="registration"></div>
<input type="hidden" id='hidden_uid' value="<?php echo $this->user['uid'] ?>"> 
<input type="hidden" id='hidden_pid' value="<?php echo $this->user['pid'] ?>"> 
<input type="hidden" id='hidden_subid' value="<?php echo $this->user['subid'] ?>"> 
<input type="hidden" id='hidden_escid' value="<?php echo $this->user['escid'] ?>"> 
<script type="text/javascript">
$("#addcourse").click(function(){
	var perid=$("#perid").val();
	var uid=$("#hidden_uid").val();
	var pid=$("#hidden_pid").val();
	var escid=$("#hidden_escid").val();
	var subid=$("#hidden_subid").val();
	if (perid=="") {
		$("#perid").focus();
		return false;
	};
	var url="/record/directed/register/perid/"+perid+"/uid/"+uid+"/pid/"+pid+"/subid/"+subid+"/escid/"+escid+"";
		$("#registration").html("<img src='/img/spinner.gif'>Cargando...");
		$("#registration").load(url);
});
</script>