<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/rcentral/code/listuser/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table table-striped table-bordered table-condensed ">
        <tr>
            <td><p style="font-size: 16px">Buscar nro DNI para crear un Usuario : <?php echo $this->fm->pid?></p></div></td>
        </tr>
    </table>
</form>
<div id="filtrorol"></div>  
<script>
    $("#pid").keypress(function (e) {     
        if(e == 13 || e.which==13 || e.which==0){           
            $('#filtrorol').html("<img src='/img/spinner.gif'> Cargando....");
            $("#frmFiltroDoc").submit();
        }
    });   
    
    $("#frmFiltroDoc").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#filtrorol').html(data);                                 
            }
        }); 
        return false;
    });
 </script>