<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Distribución');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>

<!-- <div class="row">
	<br><br>
	<div class="col-md-9 col-md-offset-1">
		<blockquote>
			<h2>Distribución</h2>
		</blockquote>
	</div>
	<div class="col-md-1">
		<blockquote>
			<h2><span class="glyphicon glyphicon-bookmark text-warning"></span></h2>
		</blockquote>
	</div>
</div>
<hr> -->
<div class="row">
	<div class="col-md-1 col-md-offset-1">
		<h5 class="text-info">Año</h5>
		<select class="form-control" name="Anio" id="anio">
			<option value="">Seleccione Año</option>
			<?php $anio = date('Y');
			for ($i=$anio; $i >= 1993 ; $i--) { ?>
 				<option value="<?php echo $i?>"><?php echo $i?></option>
 			<?php } ?>
		</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-info">Periodo</h5>
		<select id="seletperiod" class="form-control">
			<option value="">Primero Seleccione un Año</option>
		</select>
	</div>
	<div class="col-md-3">
		<h5 class="text-info">Facultad</h5>
		<select name="faculty" id="faculty" class="form-control">
			<option value="">Seleccione Facultad</option>
			<?php
			foreach ($this->dataf as $dataf) {
				if ($dataf['facid']<>"NINGUN") { ?>
 					<option value="<?php echo $dataf['facid']?>"><?php echo strtoupper($dataf['name'])?></option>
				<?php
				}
 			} ?>
		</select>
	</div>
	<div class="col-md-3 text-center">
		<h5 class="text-info">Mostrar Distribuciones<br> en Borrador</h5>
	    <input type="checkbox" id="borrador">
	</div>
	<div class="col-md-1 col-md-offset-5">
		<br><br>
		<a id="show" href="#" class="btn btn-success">Mostrar</a>
	</div>
</div>
<hr>
<br>
<div id="data"></div>

<div id="alert" class="alert alert-warning text-center">
	<h4><strong>Error!</strong> Seleccione un Periodo</h4>
</div>
<div id="alert1" class="alert alert-warning text-center">
	<h4><strong>Error!</strong> Seleccione una Facultad</h4>
</div>

<script>
	$('#alert').fadeOut('fast');
	$('#alert1').fadeOut('fast');

	var anioo=<?php echo $this->anio?>;
	if (anioo) {
		$('#anio > option[value='+anioo+']').attr('selected', 'selected');
		var vanio=$("#anio").val();
		var url=("/pedagogia/distribution/getperiods/anio/"+vanio);
		$("#seletperiod").html("Cargando....");
		$("#seletperiod").load(url);
	}

	$('#anio').change(function(){
		$('#anio option:selected').each(function(){
			var anio = $(this).val();
			$.get('/pedagogia/distribution/getperiods/anio/'+anio, function(data){
				$('#seletperiod').html(data);
			});
		});
	});

	$('#show').click(function(){
		// $('.correc').popover('hide');
		var perid = $('#seletperiod').val();
		var facid = $('#faculty').val();
		if (perid){
			if (facid) {
			    var check =  $(this).attr('checked');
			    if (borrador.checked == 1){
			    	$('.correc').popover('hide');
			        var b="B";
			        $("#data").show();
					$('#data').html('<center><img class="text-center" src="/img/spinner.gif"></center>');
					$('#data').load('/pedagogia/distribution/view/perid/'+$.base64.encode(perid)+'/facid/'+facid+"/borrador/"+b);
					$('#alert1').hide();
					$('#alert').hide();
			    }
			    else{
					$("#data").show();
					$('#data').html('<center><img class="text-center" src="/img/spinner.gif"></center>');
					$('#data').load('/pedagogia/distribution/view/perid/'+$.base64.encode(perid)+'/facid/'+facid);
					$('#alert1').hide();
					$('#alert').hide();
				}
			}
			else{
				$("#data").hide();
				$('#alert').fadeOut('fast');
				$('#alert1').fadeIn('slow');
			}
		}else{
			$("#data").hide();
			$('#alert').fadeIn('slow');
		}
	});
</script>
