
    <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>-->

<?php if ($this->dis): ?>
	<table class="table table-hover" style="font-size:14px">
	<thead>
		<tr>
			<th>#</th>
			<th>Nombre de la Escuela</th>
			<th>Fecha de Registro</th>
			<th>Ver</th>
			<th>Observacion</th>
			<th class="text-center">Impresion</th>
		</tr>

	</thead>

	<tbody>
		<?php
		$i=0;
		foreach ($this->dis as $distrib) {
			$i++;			
			?>
			<tr>
				<td><?php echo $i?></td>
				<td><?php echo $distrib['name']?></td>
				<td ><?php echo $distrib['number']?></td>
				<td>
				<h4><a id="seeDistribution<?php echo $distrib['number']?>" href="#" title="Ver" onclick="javascript: window.open('/distribution/printdistribution/index/perid/<?php echo base64_encode($distrib['perid'])?>/distid/<?php echo base64_encode($distrib['distid'])?>/escid/<?php echo base64_encode($distrib['escid'])?>/subid/<?php echo base64_encode($distrib['subid'])?>/t/U','Eliminar Cursos','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=850,height=750')">
                <span class="glyphicon glyphicon-eye-open"></span></a></h4>				
				</td>
				<td><span title="eescriba" rel="tooltip" placeholder="escribaa" id="<?php echo $i?>"  value='editar'>
				<?php if($distrib['observation']=='')
				{
				  echo "Haga doble clic para editar su observacion";
				}
				else
				{
				  echo trim($distrib['observation']);	
				}

				?></span></td>				


				<td class="text-center"><h4><a href='/distribution/printdistribution/index/perid/<?php echo base64_encode($distrib['perid'])?>/distid/<?php echo base64_encode($distrib['distid'])?>/escid/<?php echo base64_encode($distrib['escid'])?>/subid/<?php echo base64_encode($distrib['subid'])?>' data-dismiss="modal" aria-hidden="true" style="float:center"><span class="glyphicon glyphicon-print"></span></a></h4></td>
				<!--  Nombre: <span class="editText">Fulanito de tal</span> -->
			</tr>

			
			<script> 
            // $(function(){
            	$('#seeDistribution<?php echo $distrib['number']?>').hover(function(){
					$('#seeDistribution<?php echo $distrib['number']?>').tooltip('toggle');
				});

                $('#<?php echo $i?>').dblclick( function(){
                    var text = $(this).text();

					text=text.trim();
                    //alert(text);

                    $(this).empty().html('<input type="text" class="form-control" value="'+text+'">').find('input').focus();
                	}).keypress( function(e){
                    if(e.keyCode == 13){
                        var text = $('input', this).val();
                        $(this).html( text );

                    //alert("Campo actualizado");

                    //e.preventDefault();                 
                    //alert(url);
                    $("#destino").load("/pedagogia/distribution/distribution/", {escid: "<?php echo $distrib['escid']?>", distid: "<?php echo $distrib['distid']?>",perid: "<?php echo $distrib['perid']?>",subid: "<?php echo $distrib['subid']?>",observation: text}, function(){
                	});

                    }
                });
            // });
        	</script>

			<?php



		}
		?>
	</tbody>
	</table>
<?php else: ?>
	<h2 class="text-muted text-center">No <strong>existen</strong> datos en este periodo...</h2>
<?php endif ?>

<script>

	$(".span").tooltip();
</script>

 <div id="destino"></div> 
