<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-th-list"></span> RECORD DE NOTAS');?>
<?php $this->placeholder('Btnnav')->append('<a href="/index" class="form-control btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/report/recordnotas/getstudentuid/" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <!-- <table class="table span9 table-striped table-bordered table-condensed">
        <tr>
            <td colspan="2"><center><h3>Impresion de Record Notas </h3></center></td>
        </tr>
    </table> -->
    <table class="table span9 table-striped table-bordered table-condensed">
        <tr>
            <td><center>Codigo del Alumno</center></td>
            <td><center>Nombres y Apellidos</center></td>
        </tr>
        <tr>                    
            <td><center><div style='width: 200px'><?php echo $this->fm->uid ?></center></td>
            <td><center><div style='width: 400px'><?php echo $this->fm->last_name0 ?></center></td>
        </tr>
    </table>
</form>
<div  id="cargadatos_"></div> 
<script>
    $("#last_name0, #uid").keypress(function (e) {
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#uid').val();
            var nom =  $('#last_name0').val();
            count=codi.length;
            if (count==10 || count==0)
            {
                $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
                $("#frmFiltroDoc").submit();
            }
            else
            {
                alert("Ingrese un codigo valido");
                $('#uid').val('');
            }
        }
    });
    
    $("#frmFiltroDoc").submit(function(){
        $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data: $(this).serialize(),
        success: function(data) {                        
            $('#cargadatos_').html(data);                                 
            }
        }); 
        return false;
    });

function validNumber(e) {
    var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
    }    
function soloLetras(e){
       key = e.keyCode || e.which;
       tecla = String.fromCharCode(key).toLowerCase();
       letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
       especiales = [8,37,39,46];

       tecla_especial = false
       for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }

        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }    
</script>
