<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div>
    <div style="text-align:left; font-size:12px;"><b>Código: </b><?php echo strtoupper($this->uid)?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <b>Alumno: </b><?php echo strtoupper($this->person['last_name0']." ".$this->person['last_name1'].", ".$this->person['first_name'])?>
    </div>
</div>
<div style="text-align: center; font-size:16px;margin-top:10px"><b> RECORD DE NOTAS </b></div> <br/>
<?php 
    if ($this->data) {
        $countsem=$this->countsem;
        $c=0;
        $len=count($this->countsem);
        for ($i=0; $i < $len; $i++) { 
            
        ?>
        <table style="width:100%; margin-bottom:20px;" border=" 1px">
            <tr style='background:#E5E5E5'>
                <th colspan='6' style='font-size:12px; '><?php echo $countsem[$i]['semid']."º SEMESTRE"?></th>
            </tr>
            <tr>
                <th class='small-50'>Periodo</th>
                <th class='small-50'>Curso</th>
                <th >Nombre Curso</th>
                <th class='small'>Turno</th>
                <th class='small'>Créditos</th>
                <th class='small-70'>Prom. Final</th>
            </tr>
            <?php
                $notas=$this->data;
                for ($j=0; $j < $countsem[$i]['cant']; $j++) {
                    if ($notas[$c]['semid']==$countsem[$i]['semid']) { ?>
                        <tr>
                            <td class="center"><?php print $notas[$c]['perid'] ?></td>
                            <td class="center"><?php print $notas[$c]['courseid']?></td>
                            <td><?php print $notas[$c]['name']?></td>
                            <td class="center"> <?php print $notas[$c]['turno']?></td>
                            <td class="center"><?php print $notas[$c]['creditos']?></td>
                            <?php           
                            if ($notas[$c]['nota']=='' ){
                                ?> <td class="center"><?php print "-"?></td> <?php
                            }
                            else{

                                if ($notas[$c]['nota']=='-3' ){
                                    ?> <td class="center" style='color:red'><?php print "R"?></td> <?php   
                                }
                                else{       

                                    if ($notas[$c]['nota']=='-2' ){
                                        ?> <td class="center" style='color:red'><?php print "N. P."?></td> <?php
                                    }
                                    else{

                                        if ($notas[$c]['nota']>10) {
                                            ?> <td class="center" border-style:'solid'; style='color:blue'><?php print $notas[$c]['nota']?></td> <?php
                                        }
                                        else{

                                            if ($notas[$c]['nota']!=10) {
                                                ?> <td class="center" style='color:red;'><?php print $notas[$c]['nota']?></td> <?php
                                            }
                                            else{
                                                ?> <td class="center" style='color:red;'><?php print $notas[$c]['nota']?></td> <?php
                                            }
                                        }
                                    }
                                }
                            }
                            ?>
                        </tr>                            
                    <?php    
                    }
                    $c++;
                }
            ?>
        </table>
    <?php    
        }
    }
?>
<?php
    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');
    
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf -> Output('RecordNotas -'.$this->person['pid'].'.pdf','D');
    // $mpdf -> Output();  

?>
