<link rel="stylesheet" href="/css/listStandars.css" />

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Lista de Estándares');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/docente/index"><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>


<div class="tituloInformativo">
	<p><span class="glyphicon glyphicon-info-sign"></span> Para visualizar los estandares seleccione un año y luego el periodo.</p>
	<select class="form-control selectAnio" name="Anio" id="anio">
		<option value="">Año</option>
		<?php 
		for ($i=$this->anio; $i >= 2005; $i--) { ?>
		 	<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php } ?>
	</select>
	<select class="form-control selectPeriodo" name="Periodo" id="perid">
		<option value="">Periodo</option>
	</select>
</div>
<hr>
<div class="estandares" id="dataEstandares">

</div>

<script>
	$('#anio').change(function(){
		var anio = $(this).val();
		$('#dataEstandares').addClass('hidden');
		$('#perid').html("<option value=''>Cargando...</option>");
		$('#perid').load('/acreditacion/index/listperiods/anio/' + anio);
	});

	$('#perid').change(function(){
		var anio  = $('#anio').val();
		var perid = $(this).val();
		$('#dataEstandares').removeClass('hidden');
		$('#dataEstandares').html('<br><center><img src="/img/spinner.gif" alt="Cargando...." /></center><br>');
		$('#dataEstandares').load('/acreditacion/index/listestandares/anio/' + anio + '/perid/' + perid);
	})
</script>