<?php if ($this->estandares): ?>
 	<?php foreach ($this->estandares as $estandar): ?>
		<div class="estandar">
			<div class="estandarNombre">
				<?php echo ucwords(strtolower($estandar['description'])) ?>
			</div>
			<a estandarNumber="<?php echo $estandar['number'] ?>" class="showEstandarBtn btn" href="##">
				<?php echo $estandar['number'] ?>
			</a>

			<div id="estandarData<?php echo $estandar['number'] ?>" class="estandarData" hidden>
				<?php foreach ($estandar['factores_id'] as $factor): ?>
					<div class="factor">
						<p class="titleFactor"><span class="glyphicon glyphicon-flag text-muted"></span> <?php echo ucwords(strtolower($factor['name'])) ?> <small class="text-muted"><?php echo $factor['number'] ?></small></p>

						<?php if ($factor['criterid']): ?>
							<div class="factorData">
							<?php foreach ($factor['criterid'] as $criterio): ?>
								<div class="criterio">
									<div class="criterioTitulo">
										<div class="criteroTituloNombre"><span class="glyphicon glyphicon-tags text-muted"></span> <?php echo substr($criterio['estandares'][0]['namestandar'], 0, 150) ?> </div>
										<div class="criterioEstado">Aprobado</div>
										<a href="##" class="btn btn-info btnShowDetailFactor"><span class="glyphicon glyphicon-plus"></span></a>
										<!--<div class="pull-right text-muted"><?php echo $criterio['estandares'][0]['numstandar_school'] ?></div>-->
									</div>
									<div class="criterioData">
										<table class="table table-bordered table-hover">
										<?php foreach ($criterio['estandares'][0]['sources'] as $fuente): ?>
											<tr>
												<td class="col-md-10 fuenteName">
													<span class="glyphicon glyphicon-tag text-muted"></span> <?php echo $fuente['name'] ?>
												</td>
												<td class="col-md-1 text-center">
													<?php echo $fuente['codefuente'] ?>
												</td>	
												<td class="col-md-1 text-center">
													<?php echo substr($fuente['result'], 0, 5) ?>
												</td>
											</tr>
										<?php endforeach ?>
										</table>
									</div>

								</div>
							<?php endforeach ?>
							</div>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
 	<?php endforeach ?>
	<script>
		$('.estandarData').slideUp();

		$('.showEstandarBtn').click(function(){
			var estandarNumber = $(this).attr('estandarNumber');
			$('#estandarData' + estandarNumber).slideToggle();
		})
	</script>
<?php else: ?>
	<br>
	<h4 class="text-center text-muted">Aún no se Genera los<span class="text-danger"> Estandares para este Periodo</span></h4>
<?php endif ?>