<?php
if($this->t<>'U'){
    $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
    include_once($dir);
    ob_start();
    $sesion1  = Zend_Auth::getInstance();
    $sesion = $sesion1->getStorage()->read();
}
?>
<link rel="stylesheet" type="text/css" href="/css/print.css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  

<div style="text-align:center"><b><h3>DISTRIBUCIÓN ACADÉMICA - ADMINISTRATIVA DE DOCENTES - <?php echo strtoupper($this->perid)?></h3></b></div>

<h5><b>LISTA DE DOCENTES</b></h5>

<?php
$a[0]='PRINCIPAL';
$a[1]='ASOCIADO';
$a[2]='AUXILIAR';
for($n = 0; $n <= 2; $n++){ 
    $g = 0;
    foreach ($this->teachers as $teachers){
        $g++;
        if($teachers['condision']<>"CONTRATADO" and $teachers['category']==$a[$n]){ 
        // Obtengo los cursos ya asiganados
            $wherecourteac = array(
                'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'uid' => $teachers['uid'], 
                'pid' => $teachers['pid'], 'perid' => $this->perid, 'distid' => $this->distid);
            $couteach = new Api_Model_DbTable_Coursexteacher();
            $listacursos = $couteach->_getFilter($wherecourteac,$attrib=null,$orders=null);
            $tth = 0;
            if ($listacursos){
            ?>
                <table style="width: 100%">
                    <tr>
                        <th colspan='3' style='font-size:12px'>
                            <?php echo $teachers['last_name0']." ".$teachers['last_name1'].", ".$teachers['first_name']?>
                        </th>
                        <th colspan='4' style='font-size:10px'><center>
                            <?php echo $teachers['category']." - ".$teachers['dedication']?></center>
                        </th>
                    </tr>
                    <tr>
                        <th colspan="7">HORAS ACADÉMICAS</th>
                    </tr>
                    <tr>
                        <th class="span5"><center>Asignatura</center></th>
                        <th class="span1"><center>Sem</center></th>
                        <th class="span1"><center>Turno</center></th>
                        <th class="span1"><center>Grupo(s)</center></th>
                        <th class="span1"><center>Horas Teóricas</center></th>
                        <th class="span1"><center>Horas Prácticas</center></th>
                        <th class="span1"><center>Total Horas</center></th>
                    </tr>
                    <?php 
                    $nc = new Api_Model_DbTable_Course();
                    foreach ($listacursos as $curso){
                        $semid = $curso['semid'];
                        $turno = $curso['turno'];
                        $grupos = $curso['groups'];
                        $ht = $curso['hours_t'];
                        $hp = $curso['hours_p'];
                        $th = $curso['hours_total'];
                        $wherecourse = array(
                            'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'curid' => $curso['curid'], 
                            'escid' => $curso['escid'], 'subid' => $curso['subid'], 'courseid' => $curso['courseid']);
                        $tmp = $nc->_getOne($wherecourse);
                        $tth = $tth + $th;
                        if ($tmp){
                            $compromiso = ($curso['is_com']=='S')?" - Compromiso":"";
                            $licencia = ($curso['hours_t']=='0' and $curso['hours_t']=='0' and $curso['hours_p']=='0' )?" - Licencia":"";
                            $curso_nombre = $tmp['name']."  ".$compromiso." ".$licencia;
                            ?>
                            <tr>
                                <td><?php echo $curso_nombre;?></th>
                                <td><center><?php echo $semid?></center></td>
                                <td><center><?php echo $turno?></center></td>
                                <td><center><?php echo $grupos?></center></td>
                                <td><center><?php echo $ht?></center></td>
                                <td><center><?php echo $hp?></center></td>
                                <td><center><?php echo $th?></center></td>
                            </tr>
                            <?php
                        }
                    }

                    // Obtengo los cursos del docente que tiene apoyando a otros cursos
                    $wherecoursup=array(
                        'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'uid' => $teachers['uid'], 
                        'pid' => $teachers['pid'], 'perid' => $this->perid, 'escid' => $this->escid);
                    $lcapoyo = $couteach->_getAllCoursesSupportXTeacherXPeriod($wherecoursup);
                    if ($lcapoyo) {
                        foreach ($lcapoyo as $rk){
                            $g++;
                            $grupos = $rk['groups'];
                            $ht = $rk['hours_t'];
                            $hp = $rk['hours_p'];
                            $th = $rk['hours_total'];
                            $turno = $rk['turno'];
                            $semid = $rk['semid'];
                            $wherecourse = array(
                                'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'curid' => $curso['curid'], 
                                'escid' => $curso['escid'], 'subid' => $curso['subid'], 'courseid' => $curso['courseid']);
                            $tmp = $nc->_getOne($wherecourse);                
                            
                            // Leer Escuela
                            $whereespe=array('eid' => $rk['eid'], 'oid' => $rk['oid'],
                                'escid' => $rk['escid'], 'subid' => $rk['subid']);
                            $e= new Api_Model_DbTable_Speciality();
                            $es = $e->_getOne($whereespe);
                            
                            $compromiso = ($rk['is_com']=='S')?" - Compromiso":"";
                            $curso_nombre = $tmp['name'] ." --- Escuela : ".$es['name']." ".$compromiso;
                            $tht = $tht + $ht;
                            $thp = $thp + $hp;
                            $tth = $tth + $th;
                            ?>
                            <tr>
                                <td><?php echo $curso_nombre;?></th>
                                <td><center><?php echo $semid?></center></td>
                                <td><center><?php echo $turno?></center></td>
                                <td><center><?php echo $grupos?></center></td>
                                <td ><center><?php echo $ht?></center></td>
                                <td ><center><?php echo $hp?></center></td>
                                <td ><center><?php echo $th?></center></td>
                            </tr>
                            <?php
                        }
                    } ?>
                    <tr>
                        <th colspan="6">TOTALES</th>
                        <th><center><?php echo $tth?></center></th>
                    </tr>
                </table>
                <br>         
                <?php 
                $pkdistadm = array(
                    'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'escid' => $this->escid, 
                    'subid' => $this->subid, 'distid' => $this->distid, 'perid' => $this->perid,
                    'uid' => $teachers['uid'], 'pid' => $teachers['pid']);
                $ll = new Distribution_Model_DbTable_DistributionAdmin();
                $l = $ll->_getAll($pkdistadm);  
                if($l){
                ?>
                <table style="width: 100%">
                    <tr>
                        <th colspan="2">HORAS ADMINISTRATIVAS</th>
                    </tr>
                    <tr>
                        <th class="span7" >Labor</th>
                        <th class="span1"><center>Horas</center></th>
                    </tr>
                        <?php    
                        $tth = 0;
                        foreach ($l as $adm){
                            $labor = $adm['work'];
                            $horas = $adm['hours'];
                            $tth = $tth + $horas;
                            ?>
                            <tr>
                                <td><?php echo $labor?></td>
                                <td><center><?php echo $horas?></center></td>
                            </tr>
                        <?php 
                        } ?>
                        <tr>
                            <th colspan="1">TOTALES</th>                
                            <th><center><?php echo $tth?></center></th>    
                        </tr>
                        <?php
                    $hh = new Distribution_Model_DbTable_DistributionTeacher();
                    $h = $hh->_getOne($pkdistadm);
                    $hacad = $h['total_hour_acad'];
                    $hadmin = $h['total_hour_admin'];
                    $htotales = $hacad + $hadmin;
                    ?>
                    <tr> 
                        <th>TOTAL DE HORAS </th>                
                        <th><center><?php echo $htotales?></center></th>
                    </tr>
                </table>
                    <?php
                    } ?>
                <br><br><br>
                <?php
            }
        }
    }
} ?>

<h5><b>LISTA DE DOCENTES CONTRATADOS</b></h5>
<?php
$g=0;
foreach ($this->teachers as $teachers){
    $g++;
    $cond = $teachers['condision']; 
    $dedicacion = $teachers['dedication'];
    $cat = $teachers['category'];

    if($cond=="CONTRATADO"){ 
        // Obtengo los cursos ya asiganados
        $wherecourteac = array(
            'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'uid' => $teachers['uid'], 
            'pid' => $teachers['pid'], 'perid' => $this->perid, 'distid' => $this->distid);
        $couteach = new Api_Model_DbTable_Coursexteacher();
        $listacursos = $couteach->_getFilter($wherecourteac,$attrib=null,$orders=null);
        $tth = 0;
        if ($listacursos){
        ?>
            <table style="width: 100%">
                <tr>
                    <th colspan='3'>
                        <?php echo $teachers['last_name0']." ".$teachers['last_name1'].", ".$teachers['first_name']?>
                    </th>
                    <th colspan='4' style='font-size:10px'><center><?php echo $cat." - ".$dedicacion?></center></th>
                </tr>
                <tr>
                    <th colspan="7">HORAS ACADÉMICAS</th>
                </tr>
                <tr>
                    <th class="span5"><center>Curso</center></th>
                    <th class="span1"><center>Sem</center></th>
                    <th class="span1"><center>Turno</center></th>
                    <th class="span1"><center>Grupo(s)</center></th>
                    <th class="span1"><center>Horas Teóricas</center></th>
                    <th class="span1"><center>Horas Prácticas</center></th>
                    <th class="span1"><center>Total Horas</center></th>
                </tr>
                <?php 
                $nc = new Api_Model_DbTable_Course();
                foreach ($listacursos as $curso){
                    $semid = $curso['semid'];
                    $turno = $curso['turno'];
                    $grupos = $curso['groups'];
                    $ht = $curso['hours_t'];
                    $hp = $curso['hours_p'];
                    $th = $curso['hours_total'];
                    $wherecourse = array(
                        'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'curid' => $curso['curid'], 
                        'escid' => $curso['escid'], 'subid' => $curso['subid'], 'courseid' => $curso['courseid']);
                    $tmp = $nc->_getOne($wherecourse);          
                    $tth = $tth + $th;
                    if ($tmp){
                        $compromiso = ($curso['is_com']=='S')?" - Compromiso":"";
                        $curso_nombre = $tmp['name']."    ".$compromiso;
                        ?>
                        <tr>
                            <td><?php echo $curso_nombre;?></th>
                            <td><center><?php echo $semid?></center></td>
                            <td><center><?php echo $turno?></center></td>
                            <td><center><?php echo $grupos?></center></td>
                            <td><center><?php echo $ht?></center></td>
                            <td><center><?php echo $hp?></center></td>
                            <td><center><?php echo $th?></center></td>
                        </tr>
                        <?php
                    }
                }
                // Obtengo los cursos del docente que tiene apoyando a otros cursos
                $wherecoursup=array(
                    'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'uid' => $teachers['uid'], 
                    'pid' => $teachers['pid'], 'perid' => $this->perid, 'escid' => $this->escid);
                $lcapoyo = $couteach->_getAllCoursesSupportXTeacherXPeriod($wherecoursup);                       
                if ($lcapoyo) {
                    foreach ($lcapoyo as $rk){
                        $g++;
                        $grupos = $rk['groups'];
                        $ht = $rk['hours_t'];
                        $hp = $rk['hours_p'];
                        $th = $rk['hours_total'];
                        $oid = $rk['oid'];
                        $semid = $rk['semid'];
                        $wherecourse = array(
                            'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'curid' => $rk['curid'], 
                            'escid' => $rk['escid'], 'subid' => $rk['subid'], 'courseid' => $rk['courseid']);
                        $tmp = $nc->_getOne($wherecourse);                
                            
                        // Leer Escuela
                        $whereespe = array('eid' => $rk['eid'], 'oid' => $rk['oid'],
                                    'escid' => $rk['escid'], 'subid' => $rk['subid']);
                        $e = new Api_Model_DbTable_Speciality();
                        $es = $e->_getOne($whereespe);
                            
                        $compromiso = ($rk['is_com']=='S')?" - Compromiso":"";
                        $curso_nombre = $tmp['name'] ." --- Escuela : ".$es['name']." ".$compromiso;
                        $tht = $tht + $ht;
                        $thp = $thp + $hp;
                        $tth = $tth + $th;
                        ?>
                        <tr>
                            <td><?php echo $curso_nombre;?></th>
                            <td><center><?php echo $semid?></center></td>
                            <td><center><?php echo $turno?></center></td>
                            <td><center><?php echo $grupos?></center></td>
                            <td><center><?php echo $ht?></center></td>
                            <td><center><?php echo $hp?></center></td>
                            <td><center><?php echo $th?></center></td>
                        </tr>
                        <?php
                    }
                } ?>
                <tr>
                    <th colspan="6">TOTALES</th>
                    <th><center><?php echo $tth?></center></th>
                </tr>
            </table> 
            <br>   
            <?php
            $pkdistadm = array(
                'eid' => $teachers['eid'], 'oid' => $teachers['oid'], 'escid' => $this->escid, 
                'subid' => $this->subid, 'distid' => $this->distid, 'perid' => $this->perid,
                'uid' => $teachers['uid'], 'pid' => $teachers['pid']);
            $ll = new Distribution_Model_DbTable_DistributionAdmin();
            $l = $ll->_getAll($pkdistadm);
            if ($l) {
                ?>
            <table style="width: 100%">
                <tr>
                    <th colspan="2">HORAS ADMINISTRATIVAS</th>
                </tr>
                <tr>
                    <th class="span7" >Labor</th>
                    <th class="span1"><center>Horas</center></th>
                </tr>
                    <?php
                    $tth = 0;
                    foreach ($l as $adm){
                        $labor = $adm['work'];
                        $horas = $adm['hours'];
                        $tth = $tth + $horas;
                        ?>
                        <tr>
                            <td><?php echo $labor?></td>                        
                            <td><center><?php echo $horas?></center></td>
                        </tr> 
                        <?php 
                    } ?>
                    <tr>
                        <th colspan="1" >TOTALES</th>                
                        <th><center><?php echo $tth?></center></th>
                    </tr> 
                    <?php
                $hh = new Distribution_Model_DbTable_DistributionTeacher();
                $h = $hh->_getOne($pkdistadm);
                $hacad = $h['total_hour_acad'];
                $hadmin = $h['total_hour_admin'];
                $htotales = $hacad + $hadmin;
                ?>
                <tr> 
                    <th>TOTAL DE HORAS </th>                
                    <th><center><?php echo $htotales?></center></th> 
                </tr>                             
            </table>
            <?php
                }
            ?>    
            <br><br><br>
            <?php 
        }
    }
} ?>
<br>
<?php
$g=0;
if($this->practiceteachers){ ?>
    <h5><b>LISTA DE JEFES DE PRÁCTICA</b></h5>
    <?php
    foreach ($this->practiceteachers as $practiceteachers){
        $g++;
        $dedicacion = $practiceteachers['dedication'];
        $cat = $practiceteachers['category'];
        ?> 
        <table style="width: 100%">
            <tr>
                <th colspan='3'>
                    <?php echo $practiceteachers['last_name0']." ".$practiceteachers['last_name1'].", ".$practiceteachers['first_name']?>
                </th>
                <th colspan='4' style='font-size:10px'><center><?php echo $cat." - ".$dedicacion?></center></th>
            </tr>
            <tr>
                <th colspan="7">HORAS ACADÉMICAS</th>
            </tr>
            <tr>
                <th>Curso</th>
                <th><center>Sem</center></th>
                <th><center>Turno</center></th>
                <th><center>Grupo(s)</center></th>
                <th><center>Horas Teóricas</center></th>
                <th><center>Horas Prácticas</center></th>
                <th><center>Total Horas</center></th>
            </tr>
            <?php 
            // Obtengo los cursos ya asiganados
            $wherecourteac=array(
                'eid' => $practiceteachers['eid'], 'oid' => $practiceteachers['oid'],
                'uid' => $practiceteachers['uid'], 'pid' => $practiceteachers['pid'],
                'perid' => $this->perid, 'distid' => $this->distid);
            $couteach = new Api_Model_DbTable_Coursexteacher();
            $listacursos = $couteach->_getFilter($wherecourteac,$attrib=null,$orders=null);
            $tth = 0;
            $ht = $hp = $th=0;
            if ($listacursos){
                $nc = new Api_Model_DbTable_Course();
                foreach ($listacursos as $curso){
                    $semid = $curso['semid'];
                    $turno = $curso['turno'];
                    $grupos = $curso['groups'];
                    $ht = $curso['hours_t'];
                    $hp = $curso['hours_p'];
                    $th = $curso['hours_total'];
                    $wherecourse = array(
                        'eid' => $practiceteachers['eid'], 'oid' => $practiceteachers['oid'], 
                        'curid' => $curso['curid'], 'escid' => $curso['escid'], 
                        'subid' => $curso['subid'], 'courseid' => $curso['courseid']);
                    $tmp = $nc->_getOne($wherecourse);
                    $tth = $tth + $th;
                    if ($tmp){
                        $compromiso = ($curso['is_com']=='S')?" - Compromiso":"";
                        $curso_nombre = $tmp['name']."    ".$compromiso;
                        ?>
                        <tr>
                            <td><?php echo $curso_nombre;?></th>
                            <td><center><?php echo $semid?></center></td>
                            <td><center><?php echo $turno?></center></td>
                            <td><center><?php echo $grupos?></center></td>
                            <td><center><?php echo $ht?></center></td>
                            <td><center><?php echo $hp?></center></td>
                            <td><center><?php echo $th?></center></td>
                        </tr>
                        <?php
                    }
                }
            }
            // Obtengo los cursos del docente que tiene apoyando a otros cursos
            $wherecoursup=array(
                'eid' => $practiceteachers['eid'], 'oid' => $practiceteachers['oid'], 
                'uid' => $practiceteachers['uid'], 'pid' => $practiceteachers['pid'],
                'perid' => $this->perid, 'escid' => $this->escid);
            $lcapoyo = $couteach->_getAllCoursesSupportXTeacherXPeriod($wherecoursup);                       
            if ($lcapoyo) {
                foreach ($lcapoyo as $rk){
                    $g++;
                    $grupos = $rk['groups'];
                    $ht = $rk['hours_t'];
                    $hp = $rk['hours_p'];
                    $th = $rk['hours_total'];    
                    $semid = $rk['semid'];
                    $turno = $rk['turno'];
                    $wherecourse = array(
                        'eid' => $practiceteachers['eid'], 'oid' => $practiceteachers['oid'], 'curid' => $rk['curid'], 
                        'escid' => $rk['escid'], 'subid' => $rk['subid'], 'courseid' => $rk['courseid']);
                    $tmp = $nc->_getOne($wherecourse);
                                            
                    // Leer Escuela
                    $whereespe=array('eid' => $rk['eid'], 'oid' => $rk['oid'],
                        'escid' => $rk['escid'], 'subid' => $rk['subid']);
                    $e= new Api_Model_DbTable_Speciality();
                    $es = $e->_getOne($whereespe);
                                            
                    $compromiso = ($rk['is_com']=='S')?" - Compromiso":"";
                    $curso_nombre = $tmp['name'] ." --- Escuela : ".$es['name']." ".$compromiso;
                    $tht = $tht + $ht;
                    $thp = $thp + $hp;
                    $tth = $tth + $th;
                    ?>
                    <tr>
                        <td><?php echo $curso_nombre;?></th>
                        <td><center><?php echo $semid?></center></td>
                        <td><center><?php echo $turno?></center></td>
                        <td><center><?php echo $grupos?></center></td>
                        <td><center><?php echo $ht?></center></td>
                        <td><center><?php echo $hp?></center></td>
                        <td><center><?php echo $th?></center></td>
                    </tr>
                    <?php
                }
            } ?>
            <tr>
                <th colspan="6">TOTALES</th>
                <th><center><?php echo $tth?></center></th>
            </tr>
        </table> 
        <br>
        <?php 
        $pkdistadm = array(
            'eid' => $practiceteachers['eid'], 'oid' => $practiceteachers['oid'], 'escid' => $this->escid, 
            'subid' => $this->subid, 'distid' => $this->distid, 'perid' => $this->perid,
            'uid' => $practiceteachers['uid'], 'pid' => $practiceteachers['pid']);
        $ll = new Distribution_Model_DbTable_DistributionAdmin();
        $l = $ll->_getAll($pkdistadm);
        if ($l){
            ?>
        <table style="width: 100%"> 
            <tr>
                <th colspan="2">HORAS ADMINISTRATIVAS</th>
            </tr>
            <tr>
                <th class="span7" >Labor</th>
                <th class="span1"><center>Horas</center></th>
            </tr>
                <?php
                $tth = 0;
                foreach ($l as $adm){                        
                    $labor = $adm['work'];
                    $horas = $adm['hours'];
                    $tth = $tth + $horas;
                    ?>
                    <tr>
                        <td><?php echo $labor?></td>                    
                        <td><center><?php echo $horas?></center></td>
                    </tr>
                    <?php 
                } ?>
                <tr>
                    <th>TOTALES</th>
                    <th><center><?php echo $tth?></center></th>
                </tr>
                <?php
            $hh = new Distribution_Model_DbTable_DistributionTeacher();
            $h = $hh->_getOne($pkdistadm);
            $hacad = $h['total_hour_acad'];
            $hadmin = $h['total_hour_admin'];
            $htotales = $hacad + $hadmin;
            ?>
            <tr> 
                <th>TOTAL DE HORAS</th>                
                <th><center><?php echo $htotales?></center></th> 
            </tr>
        </table>
        <?php
            }
        ?>    
        <br><br><br>
        <?php 
    }
}?>
<br>
<?php
$g=0;
foreach ($this->allteachers as $allteachers){
    $g++;
    $whereuser = array('eid' => $allteachers['eid'], 'oid' => $allteachers['oid'], 'uid' => $allteachers['uid']);
    $usuario = new Api_Model_DbTable_Users();
    $list_p1 = $usuario ->_getUserXUid($whereuser);
    $escidorigenusuario = $list_p1[0]['escid'];

    $whereespe = array(
        'eid' => $allteachers['eid'], 'oid' => $allteachers['oid'],
        'escid' => $list_p1[0]['escid'], 'subid' => $list_p1[0]['subid']);
    $e = new Api_Model_DbTable_Speciality();
    $es = $e->_getOne($whereespe);
    $infoescuela = $es['name'];
    if($escidorigenusuario<>$allteachers['escid']){ ?>  
        <h5><?php echo 'Docente de Apoyo :'.$infoescuela?></h5>
        <h5><?php echo $list_p1[0]['last_name0']." ".$list_p1[0]['last_name1'].", ".$list_p1[0]['first_name']?></h5>
        <table style="width: 100%">
            <tr>
                <th class='span5'><center>Curso</center></th>
                <th class='span1'><center>Sem</center></th>
                <th class='span1'><center>Turno</center></th>
                <th class='span1'><center>(Grupo)s</center></th>
                <th class='span1'><center>Horas Teoricas</center></th>
                <th class='span1'><center>Horas Practicas</center></th>
                <th class='span1'><center>Total Horas</center></th>
            </tr>
            <?php
            foreach ($this->datateachers as  $datateachers) {
                $turno=$datateachers['turno'];
                $semid=$datateachers['semid'];                                  

                // Leer el nombre del curso
                $wherecourse = array(
                    'eid' => $datateachers['eid'], 'oid' => $datateachers['oid'], 'curid' => $datateachers['curid'], 
                    'escid' => $datateachers['escid'], 'subid' => $datateachers['subid'], 'courseid' => $datateachers['courseid']);
                $tmp = $nc->_getOne($wherecourse); 
                $ncurso_ = $tmp['name'];

                if($datateachers['uid']==$allteachers['uid']){
                    $cursoid = $allteachers['courseid'];
                    $curid = $allteachers['curid'];
                    ?>
                    <tr>
                        <td><?php echo $ncurso_?></td>                    
                        <td><center><?php echo $semid?></center></td>
                        <td><center><?php echo $turno?></center></td>
                        <td><center><?php echo $datateachers['groups']?></center></td>
                        <td><center><?php echo $datateachers['hours_t']?></center></td>
                        <td><center><?php echo $datateachers['hours_p']?></center></td>
                        <td><center><?php echo $datateachers['hours_total']?></center></td>
                    </tr>
                    <?php 
                }                                   
            } ?>
        </table>
        <br><br>
        <?php  
    }
} ?>
<br><br>
<div style="margin-left: 65%">
    <h5 style="border-top: solid 1px #000; text-align: center">
        <?php echo $this->datadir[0]['last_name0']." ".$this->datadir[0]['last_name1'].", ".$this->datadir[0]['first_name']?><br>
            DIRECTOR(A)
    </h5>
</div>

<?php 
    $html = ob_get_contents();
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,5,5);
    // $mpdf=new mPDF('win-1252','A4','','',15,15,30,12,5,7);
    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer);
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('INFORME DISTRIBUCION - '.$this->perid.'.pdf','D');
    // $mpdf->Output();
?>    