<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start();

$sesion1  = Zend_Auth::getInstance();
$sesion = $sesion1->getStorage()->read(); 

    $header='

      <table style="width: 100%;" border="1">
        <tr>
              <th rowspan="2" style="width: 340px; "><img src="/img/header_imprimir.jpg"></th>
              <th style="text-align: center; font-size: 12px;">
                FACULTAD DE  '.strtoupper($sesion->nom_facultad).'<br/>
                ESCUELA DE  '.strtoupper($sesion->nom_escuela).'
                   
              </th>        
          </tr>
        <tr>
          <th style="border: 1px solid #000;font-size: 12px;"> DISTRIBUCIÓN ACADEMICA-ADMINISTRATIVA DE DOCENTES - '.$this->perid.'</th>
        </tr>
      </table>      
    '    



    ?>    
    <link rel="stylesheet" type="text/css" href="/css/impresion.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap-responsive.min.css">


    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  

  
        <?php

         $distid=$this->distribucion['distid']; 
         $perid= $this->distribucion['perid'];
         $sedid = $this->distribucion['sedid'];


        ?>

    <table class="table span10 table-condensed">
    <tr>
        <th>
           <h5><b>LISTA DE DOCENTES</b> </h5>
        </th>
    </tr>
    </table>


    <?php 
    $a[0]='PRINCIPAL';
    $a[1]='ASOCIADO';
    $a[2]='AUXILIAR';

    for($n=0;$n<=2;$n++)
    {
    ?>
 
    <table class="table span10 table-condensed">
    
        <tbody>
        <?php
        $g=0;
        foreach ($this->docentes as $docente)
        {
            $g++;
            $d = new Admin_Model_DbTable_Persona();
            $eid = $docente['eid'];
            $oid = $docente['oid'];
            $pid = $docente['pid'];
            $uid = $docente['uid'];
           
            $escid = $docente['escid'];
            $director = $docente['esdirector'];
            $dl = $d->_getPersona($eid, $oid, $pid);
            $datos = trim($dl['ape_pat']." ".$dl['ape_mat'].", ".$dl['nombres']);

            $existedoc = new Admin_Model_DbTable_Docentexcursos();
            $dl = $existedoc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);

            $doccondicion = new Admin_Model_DbTable_Usuario();
            $condicion = $doccondicion-> _getUsuario($eid,$oid,$uid);
            $cond=$condicion['condision_doc'];
            $dedicacion=$condicion['dedicasion_doc'];
            $cat=$condicion['categoria_doc'];
            
            if($dl and $cond<>"CONTRATADO" and $cat==$a[$n])
            {               

                ?>   
                <tr colspan="4">
                    <td >
                    <table  class="table span10 table-striped table-bordered table-condensed">
                        <tr>
                            <th colspan='3'><?php echo $datos?></th>
                            <th colspan='4' style='font-size:10px'><center><?php echo $cat." - ".$dedicacion?></center></th>
                        </tr>
                        
                        <tr>
                            <th colspan="7">HORAS ACADÉMICAS</th>
                        </tr>

                        <tr>
                            <th class="span5"><center>Curso</center></th>
                            <th class="span1"><center>Sem</center></th>
                            <th class="span1"><center>Turno</center></th>
                            <th class="span1"><center>Grupo(s)</center></th>
                            <th class="span1"><center>Horas Teóricas</center></th>
                            <th class="span1"><center>Horas Prácticas</center></th>
                            <th class="span1"><center>Total Horas</center></th>
                        </tr>
                            <?php 
                                // Obtengo los cursos ya asiganados
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
                                $tth=0;
                                if ($listacursos)
                                {          
                                  // echo "si";
                                    foreach ($listacursos as $curso)
                                    {
                                        $nc = new Admin_Model_DbTable_Cursos();
                                        $cursoid=$curso['cursoid']; 
                                        $curid=$curso['curid'];
                                        $semid=$curso['semid'];
                                        $turno=$curso['turno'];
                                        $grupos=$curso['grupos'];
                                        $ht=$curso['horas_teoria'];
                                        $hp=$curso['horas_practica'];
                                        $th=$curso['total_horas'];
                                        $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);            
                                        $tth=$tth+$th;
                                        if ($tmp)
                                        {
                                            $compromiso = ($curso['compromiso']=='S')?" - Compromiso":"";
                                            $licencia = ($curso['horas_teoria']=='0' and $curso['horas_teoria']=='0' and $curso['horas_practica']=='0' )?" - Licencia":"";

                                            $curso_nombre = $tmp['nombre_curso']."  ".$compromiso." ".$licencia;
                                            // " Turno: ".$curso['turno']."
                                        ?>
                                        <tr>
                                            <td><?php echo $curso_nombre;?></th>
                                            <td><center><?php echo $semid?></center></td>
                                            <td><center><?php echo $turno?></center></td>
                                            <td><center><?php echo $grupos?></center></td>
                                            <td ><center><?php echo $ht?></center></td>
                                            <td ><center><?php echo $hp?></center></td>
                                            <td ><center><?php echo $th?></center></td>
                                        </tr>
                                        <?php
                                        }
                                    }

                                }
                                
                                // Obtengo los cursos del docente que tiene apoyando a otros cursos
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
                                    
                                $ncu = new Distribucion_Model_DbTable_Docentescursos();
                                $lcapoyo=$ncu->_getCursosApoyoXDocenteXPeriodo($eid, $oid,$perid,$uid,$pid,$escid);
                               

                                foreach ($lcapoyo as $rk)
                                {
                                    $g++;
                                    $grupos=$rk['grupos'];
                                    $ht=$rk['horas_teoria'];
                                    $hp=$rk['horas_practica'];
                                    $th=$rk['total_horas'];
                                    $nc = new Admin_Model_DbTable_Cursos();
                                    $eid=$rk['eid'];
                                    $oid=$rk['oid'];
                                    $escid=$rk['escid'];            
                                    $semid=$rk['semid'];            
                                    $sedid=$rk['sedid'];  
                                    $cursoid=$rk['cursoid'];            
                                    $curid=$rk['curid'];            
                                    $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);                
                                    //Leer Escuela
                                    $e= new Admin_Model_DbTable_Escuela();
                                    $es = $e->_getEscuela($eid, $oid, $escid);
                                    $compromiso = ($rk['compromiso']=='S')?" - Compromiso":"";

                                    $curso_nombre = $tmp['nombre_curso'] ." --- Escuela : ".$es['nom_escuela']." ".$compromiso;
                                    // ." Turno: ".$curso['turno']
                                    $tht = $tht+$ht;
                                    $thp = $thp+$hp;
                                    $tth=$tth+$th;
                                    ?>
                                    <tr>
                                        <td><?php echo $curso_nombre;?></th>
                                        <td><center><?php echo $semid?></center></td>
                                        <td><center><?php echo $turno?></center></td>
                                        <td><center><?php echo $grupos?></center></td>
                                        <td ><center><?php echo $ht?></center></td>
                                        <td ><center><?php echo $hp?></center></td>
                                        <td ><center><?php echo $th?></center></td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                <tr>
                                <th  colspan="6">TOTALES</th>
                                <th ><center><?php echo $tth?></center></th>
                                </tr>
                    </table>
                    </td>
                </tr>
                <tr>
                    <td>          
                    <table  class="table span10 table-striped table-bordered table-condensed">
                            <tr>
                                <th colspan="2">HORAS ADMINISTRATIVAS</th>
                            </tr>
                            <tr >
                                <th class="span7" >Labor</th>
                                <th class="span1"><center>Horas</center></th>
                            </tr>
                            <?php 
                            $ll = new Distribucion_Model_DbTable_Distribucionadmin();
                            $l = $ll->_getDistribuciones($eid, $oid, $distid, $uid, $pid);

                          

                            if($l)
                            {
                                $tth=0;
                                foreach ($l as $adm)
                                {
                                    $labor = $adm['labor'];
                                    $horas = $adm['horas'];
                                    $tth=$tth+$horas;
                                    ?>
                                    <tr>
                                        <td><?php echo $labor?></td>
                                        <td><center><?php echo $horas?></center></td>
                                    </tr> 
                                    <?php 
                                }
                                ?>
                                <tr>
                                    <th colspan="1" >TOTALES</th>                
                                    <th ><center><?php echo $tth?></center></th>    

                                </tr>  
                                <?php
                            }
                            ?>
                            <?php
                                $hh = new Distribucion_Model_DbTable_Distribuciondocente();
                                $h = $hh->_getDistribuciones($eid, $oid, $distid, $uid, $pid);
                                $hacad=$h['t_h_acad'];
                                $hadmin=$h['t_h_adm'];
                                $htotales=$hacad+$hadmin;
                            ?>
                            <tr> 
                                <th colspan="1" >TOTAL DE HORAS </th>                
                                <th ><center><?php echo $htotales?></center></th> 
                            </tr> 
                    </table>
                   
                    </td>
                </tr>           
                <?php
            }
        }
         ?>
        </tbody>
    </table> 
    <?php
    }
    ?>
  

    <br>
    <?php  
    $eid=$this->eid; 
    $oid=$this->oid; 
    $escid=$this->escid; 
    $sedid=$this->sedid; 
    $estado='A';
    $condi='CONTRATADO';

    $ll = new Default_Model_DbTable_Usuario();    
    if($ll->_getUsuarioXContratadosXEscuela($eid,$oid,$escid,$condi,$estado))
    {
        ?>
        <table class="table  span14  table-condensed">
         <tr>
            <th>
               <h5><b>LISTA DE DOCENTES CONTRATADOS</b> </h5>
            </th>
        </tr>
        </table>

        <?php
    } ?>

    <table class="table span10 table-condensed"><!--table-bordered-->
        <tbody>
        <?php
        $g=0;
        foreach ($this->docentes as $docente)
        {
            $g++;
            $d = new Admin_Model_DbTable_Persona();
            $eid = $docente['eid'];
            $oid = $docente['oid'];
            $pid = $docente['pid'];
            $uid = $docente['uid'];
           
            $escid = $docente['escid'];
            $director = $docente['esdirector'];
            $dl = $d->_getPersona($eid, $oid, $pid);
            $datos = trim($dl['ape_pat']." ".$dl['ape_mat'].", ".$dl['nombres']);

            $existedoc = new Admin_Model_DbTable_Docentexcursos();
            $dl = $existedoc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
            
            $doccondicion = new Admin_Model_DbTable_Usuario();
            $condicion = $doccondicion-> _getUsuario($eid,$oid,$uid);
            $cond=$condicion['condision_doc']; 
            $dedicacion=$condicion['dedicasion_doc'];
            $cat=$condicion['categoria_doc'];          


            if($dl and $cond=="CONTRATADO")
            {             
                    ?>       
                    <tr colspan="4">
                        <td >
                        <table  class="table span14 table-striped table-bordered table-condensed">
                       
                                <tr  >
                                
                                <th colspan='3'><?php echo $datos?></th>
                                <th colspan='4' style='font-size:10px'><center><?php echo $cat." - ".$dedicacion?></center></th>
                                </tr> 



                                <tr>
                                    <th colspan="7">HORAS ACADÉMICAS</th>
                                </tr>
                                <tr >
                                    <th class="span5"><center>Curso</center></th>
                                    <th class="span1"><center>Sem</center></th>
                                    <th class="span1"><center>Turno</center></th>
                                    <th class="span1"><center>Grupo(s)</center></th>
                                    <th class="span1"><center>Horas Teóricas</center></th>
                                    <th class="span1"><center>Horas Prácticas</center></th>
                                    <th class="span1"><center>Total Horas</center></th>
                                </tr>
                                <?php 
                                // Obtengo los cursos ya asiganados
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
                                $tth=0;
                                if ($listacursos)
                                {          
                                  
                                    foreach ($listacursos as $curso)
                                    {
                                        $nc = new Admin_Model_DbTable_Cursos();
                                        $cursoid=$curso['cursoid']; 
                                        $curid=$curso['curid'];
                                        $grupos=$curso['grupos'];
                                        $ht=$curso['horas_teoria'];
                                        $hp=$curso['horas_practica'];
                                        $th=$curso['total_horas'];
                                        $semid=$curso['semid'];
                                        $turno=$curso['turno'];
                                        $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);            
                                        $tth=$tth+$th;
                                        if ($tmp)
                                        {
                                            $compromiso = ($curso['compromiso']=='S')?" - Compromiso":"";
                                            $curso_nombre = $tmp['nombre_curso']."    ".$compromiso;
                                            // ." Turno: ".$curso['turno']
                                            ?>
                                            <tr>
                                                <td><?php echo $curso_nombre;?></th>
                                                <td><center><?php echo $semid?></center></td>
                                                <td><center><?php echo $turno?></center></td>
                                                <td><center><?php echo $grupos?></center></td>
                                                <td ><center><?php echo $ht?></center></td>
                                                <td ><center><?php echo $hp?></center></td>
                                                <td ><center><?php echo $th?></center></td>
                                            </tr>
                                            <?php
                                        }
                                    }

                                }
                                
                                // Obtengo los cursos del docente que tiene apoyando a otros cursos
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
                                
                                $ncu = new Distribucion_Model_DbTable_Docentescursos();
                                $lcapoyo=$ncu->_getCursosApoyoXDocenteXPeriodo($eid, $oid,$perid,$uid,$pid,$escid);
                               

                                foreach ($lcapoyo as $rk)
                                {
                                    $g++;
                                    $grupos=$rk['grupos'];
                                    $ht=$rk['horas_teoria'];
                                    $hp=$rk['horas_practica'];
                                    $th=$rk['total_horas'];
                                    $nc = new Admin_Model_DbTable_Cursos();
                                    $eid=$rk['eid'];
                                    $oid=$rk['oid'];
                                    $escid=$rk['escid'];            
                                    $sedid=$rk['sedid'];
                                    $semid=$rk['semid'];   
                                    $cursoid=$rk['cursoid'];            
                                    $curid=$rk['curid'];            
                                    $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);                
                                    //Leer Escuela
                                    $e= new Admin_Model_DbTable_Escuela();
                                    $es = $e->_getEscuela($eid, $oid, $escid);
                                    $curso_nombre = $tmp['nombre_curso'] ." --- Escuela(Apoyo) : ".$es['nom_escuela'];
                                    // ." Turno: ".$curso['turno']
                                    $tht = $tht+$ht;
                                    $thp = $thp+$hp;
                                    $tth=$tth+$th;
                                     ?>
                                    <tr>
                                    <td><?php echo $curso_nombre;?></th>
                                    <td><center><?php echo $semid?></center></td>
                                    <td><center><?php echo $turno?></center></td>
                                    <td><center><?php echo $grupos?></center></td>
                                    <td ><center><?php echo $ht?></center></td>
                                    <td ><center><?php echo $hp?></center></td>
                                    <td ><center><?php echo $th?></center></td>
                                    </tr>
                                    <?php
                                }

                                ?>
                                <tr>
                                <th  colspan="6">TOTALES</th>
                                <th ><center><?php echo $tth?></center></th>
                                </tr>
                        </table> 
                        </td>
                    </tr>
                    <tr>
                        <th>    

                        <table  class="table span10 table-striped table-bordered table-condensed">
                    
                                <tr>
                                    <th colspan="2">HORAS ADMINISTRATIVAS</th>
                                </tr>
                                <tr >
                                    <th class="span7" >Labor</th>                       
                                    <th class="span1"><center>Horas</center></th>

                                </tr>
                                <?php 
                                $ll = new Distribucion_Model_DbTable_Distribucionadmin();
                                $l = $ll->_getDistribuciones($eid, $oid, $distid, $uid, $pid);
                                if ($l)
                                {
                                    $tth=0;
                                    foreach ($l as $adm)
                                    {
                                        $labor = $adm['labor'];
                                        $horas = $adm['horas'];
                                        $tth=$tth+$horas;
                                        ?>
                                        <tr>
                                            <td><?php echo $labor?></td>                        
                                            <td><center><?php echo $horas?></center></td>
                                        </tr> 
                                        <?php 
                                    }
                                     ?>
                                    <tr>
                                        <th colspan="1" >TOTALES</th>                
                                        <th ><center><?php echo $tth?></center></th>
                                    </tr> 
                                    <?php
                                }

                                $hh = new Distribucion_Model_DbTable_Distribuciondocente();
                                $h = $hh->_getDistribuciones($eid, $oid, $distid, $uid, $pid);
                                $hacad=$h['t_h_acad'];
                                $hadmin=$h['t_h_adm'];
                                $htotales=$hacad+$hadmin;
                                ?>
                                <tr> 
                                    <th colspan="1" >TOTAL DE HORAS </th>                
                                    <th ><center><?php echo $htotales?></center></th> 
                                </tr>                             

                        </table>
                        </th>
                    </tr>           
                    <?php 
            }
        }
        ?>
        </tbody>
    </table>


    <?php  
    $eid=$this->eid; 
    $oid=$this->oid; 
    $escid=$this->escid; 
    $sedid=$this->sedid; 
    $rid='JP';

    $ll = new Admin_Model_DbTable_Usuario();
    $l = $ll->_getUsuariosXRolXSedeXEscuela($eid,$oid,$escid,$sedid,$rid);
    //print_r($l);
    if($l)
    {
        ?>

        <table class="table  span10  table-condensed" >
            <tr>
                <th>
                   <h5><b>LISTA DE JEFES DE PRÁCTICA</b></h5>
                </th>
            </tr>    
        </table>
        <?php
    }

    ?>
    <table class="table span10 table-condensed"> 
        <tbody>
        <?php
        $g=0;    
        if($this->listajefepracticas)
        {
            foreach ($this->listajefepracticas as $docentejp)
            {
                $g++;
                $d = new Admin_Model_DbTable_Persona();
                $eid = $docentejp['eid'];
                $oid = $docentejp['oid'];
                $pid = $docentejp['pid'];
                $uid = $docentejp['uid'];
                $escid = $docentejp['escid'];
                $director = $docentejp['esdirector'];
                $dl = $d->_getPersona($eid, $oid, $pid);
                $datos = trim($dl['ape_pat']." ".$dl['ape_mat'].", ".$dl['nombres']);

                $existedoc = new Admin_Model_DbTable_Docentexcursos();
                $dl = $existedoc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);

                $doccondicion = new Admin_Model_DbTable_Usuario();
                $condicion = $doccondicion-> _getUsuario($eid,$oid,$uid);
                $cond=$condicion['condision_doc'];
                $dedicacion=$condicion['dedicasion_doc'];
                $cat=$condicion['categoria_doc'];
                    
                if($dl)
                {   
                    ?>        
                    <tr>
                        <td colspan="4">
                            
                            <table  class="table span14 table-striped table-bordered table-condensed" >
                                
                                <tr  >                                
                                <th colspan='3'><?php echo $datos?></th>
                                <th colspan='4' style='font-size:10px'><center><?php echo $cat." - ".$dedicacion?></center></th>
                                </tr> 


                                <tr>
                                    <th colspan="7">HORAS ACADÉMICAS</th>
                                </tr>
                                <tr >
                                    <th class="span5"><center>Curso</center></th>
                                    <th class="span1"><center>Sem</center></th>
                                    <th class="span1"><center>Turno</center></th>
                                    <th class="span1"><center>Grupo(s)</center></th>
                                    <th class="span1"><center>Horas Teóricas</center></th>
                                    <th class="span1"><center>Horas Prácticas</center></th>
                                    <th class="span1"><center>Total Horas</center></th>
                                </tr>
                                <?php 
                                    // Obtengo los cursos ya asiganados
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);
                                $tth=0;
                                $ht = $hp= $th=0;
                                if ($listacursos)
                                {                        
                                    foreach ($listacursos as $curso)
                                    {
                                        $nc = new Admin_Model_DbTable_Cursos();
                                        $cursoid=$curso['cursoid']; 
                                        $curid=$curso['curid'];
                                        $grupos=$curso['grupos'];
                                        $ht=$curso['horas_teoria'];
                                        $hp=$curso['horas_practica'];
                                        $th=$curso['total_horas'];
                                        $semid=$curso['semid'];
                                        $turno=$curso['turno'];
                                        $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);            
                                        $tth=$tth+$th;
                                        if ($tmp)
                                        {
                                            $compromiso = ($curso['compromiso']=='S')?" - Compromiso":"";
                                            $curso_nombre = $tmp['nombre_curso']."    ".$compromiso;
                                                // ." Turno: ".$curso['turno']
                                            ?>
                                            <tr>
                                                <td><?php echo $curso_nombre;?></th>
                                                <td><center><?php echo $semid?></center></td>
                                                <td><center><?php echo $turno?></center></td>
                                                <td><center><?php echo $grupos?></center></td>
                                                <td ><center><?php echo $ht?></center></td>
                                                <td ><center><?php echo $hp?></center></td>
                                                <td ><center><?php echo $th?></center></td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                }
                                ?>
                                <?php 
                                    // Obtengo los cursos del docente que tiene apoyando a otros cursos
                                $lc = new Admin_Model_DbTable_Docentexcursos();
                                $listacursos = $lc->_getCursosXDocenteXPeriodoXDistribucion($eid,$oid,$uid,$pid,$perid,$distid);

                                    // Listar cursos de otras escuelas
                                $ncu = new Distribucion_Model_DbTable_Docentescursos();
                                $lcapoyo=$ncu->_getCursosApoyoXDocenteXPeriodo($eid, $oid,$perid,$uid,$pid,$escid);
                                foreach ($lcapoyo as $rk)
                                {
                                        $g++;
                                        $grupos=$rk['grupos'];
                                        $ht=$rk['horas_teoria'];
                                        $hp=$rk['horas_practica'];
                                        $th=$rk['total_horas'];
                                        $nc = new Admin_Model_DbTable_Cursos();
                                        $eid=$rk['eid'];
                                        $oid=$rk['oid'];
                                        $escid=$rk['escid'];            
                                        $sedid=$rk['sedid'];
                                        $semid=$rk['semid'];   
                                        $cursoid=$rk['cursoid'];            
                                        $curid=$rk['curid'];            
                                        $tmp = $nc->_getCurso($eid, $oid, $escid, $sedid, $cursoid,$curid);                
                                        //Leer Escuela
                                        $e= new Admin_Model_DbTable_Escuela();
                                        $es = $e->_getEscuela($eid, $oid, $escid);
                                        $curso_nombre = $tmp['nombre_curso'] ." --- Escuela / Especialidad : ".$es['nom_escuela'];
                                        // ." Turno: ".$curso['turno']
                                        $tht = $tht+$ht;
                                        $thp = $thp+$hp;
                                        $tth=$tth+$th;
                                        ?>
                                        <tr>
                                            <td><?php echo $curso_nombre;?></th>
                                            <td><center><?php echo $semid?></center></td>
                                            <td><center><?php echo $turno?></center></td>
                                            <td><center><?php echo $grupos?></center></td>
                                            <td ><center><?php echo $ht?></center></td>
                                            <td ><center><?php echo $hp?></center></td>
                                            <td ><center><?php echo $th?></center></td>
                                        </tr>
                                        <?php
                                }
                                ?>
                                <tr>
                                    <th  colspan="6">TOTALES</th>
                                    <th ><center><?php echo $tth?></center></th>
                                </tr>
                            </table> 
                           
                        </td>
                    </tr>
                    <tr>
                        <th colspan="4">
                            <table  class="table span10 table-striped table-bordered table-condensed"> 
                                <tr>
                                    <th colspan="2">HORAS ADMINISTRATIVAS</th>
                                </tr>
                                <tr >
                                    <th class="span7" >Labor</th>
                                    <th class="span1"><center>Horas</center></th>
                                    
                                </tr>
                                <?php 
                                $ll = new Distribucion_Model_DbTable_Distribucionadmin();
                                $l = $ll->_getDistribuciones($eid, $oid, $distid, $uid, $pid);
                                if ($l)
                                {
                                    $tth=0;
                                    foreach ($l as $adm)
                                    {                        
                                        $labor = $adm['labor'];
                                        $horas = $adm['horas'];
                                        $tth=$tth+$horas;
                                        ?>
                                        <tr>
                                            <td><?php echo $labor?></td>                    
                                            <td><center><?php echo $horas?></center></td>
                                        </tr>
                                        <?php 
                                    }
                                     ?>
                                    <tr>
                                        <th>TOTALES</th>
                                        <th ><center><?php echo $tth?></center></th>
                                    </tr>
                                    <?php
                                }
                                $hh = new Distribucion_Model_DbTable_Distribuciondocente();
                                $h = $hh->_getDistribuciones($eid, $oid, $distid, $uid, $pid);
                                $hacad=$h['t_h_acad'];
                                $hadmin=$h['t_h_adm'];
                                $htotales=$hacad+$hadmin;
                                ?>
                                <tr> 
                                    <th colspan="1" >TOTAL DE HORAS</th>                
                                    <th ><center><?php echo $htotales?></center></th> 
                                </tr>
                            </table>            
                        </th>
                    </tr>
                    <?php 
                }
            }
        }
        ?>    
        </tbody>
    </table>
   
    <br>
    <table class="table span10 table-condensed" >
     
        <?php
        $g=0;
        foreach ($this->docentesunicos as $docentea)
        {
            $g++;
            $d = new Admin_Model_DbTable_Persona();
            $eid = $docentea['eid'];
            $oid = $docentea['oid'];
            $pid = $docentea['pid'];      
            
            $uid = $docentea['uid'];
            $escid = $docentea['escid'];
            $director = $docentea['esdirector'];
            $dl = $d->_getPersona($eid, $oid, $pid);
            $datos = trim($dl['ape_pat']." ".$dl['ape_mat'].", ".$dl['nombres']);

            $usuario = new Admin_Model_DbTable_Usuario();
            $estado='A';
            // $list_p1 = $usuario ->_getUsuarioXEstado($eid,$oid,$uid,$estado);
            $list_p1 = $usuario ->_getUsuario($eid,$oid,$uid);

            $info3 = $list_p1['categoria_doc'];
            $escidorigenusuario=$list_p1['escid'];

            $cond=$condicion['condision_doc'];
            $dedicacion=$condicion['dedicasion_doc'];
               

            $dbescuela = new Admin_Model_DbTable_Escuela();
            $escuela = $dbescuela ->_getEscuela($eid,$oid,$escidorigenusuario);
            $infoescuela = $escuela['nom_escuela'];

                if($escidorigenusuario<>$docentea['escid'])
                {
                    ?>
                   
                    <tr>                    
                        <th colspan='4' ><h5><?php echo 'Docente de Apoyo :'.$infoescuela?></h5></th>
                    </tr>
                    <tr>                    
                        <th colspan='4' ><?php echo $datos?></th>
                    </tr>     

                    <tr>
                        <td>  
                            <table class="table span14  table-bordered ">               
                                <thead>
                                <tr>
                                    <!-- <th ><center>Escuela</center></th> -->
                                    <th class='span5'><center>Curso</center></th>
                                    <th class='span1'><center>Sem</center></th>
                                    <th class='span1'><center>Turno</center></th>
                                    <th class='span1'><center>(Grupo)s</center></th>
                                    <th class='span1'><center>Horas Teoricas</center></th>
                                    <th class='span1'><center>Horas Practicas</center></th>
                                    <th class='span1'><center>Total Horas</center></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($this->docentesapoyodetalle as  $detallecursos) {

                                    $eid=$detallecursos['eid'];
                                    $oid=$detallecursos['oid'];
                                    $escid=$detallecursos['escid'];
                                    $sedid=$detallecursos['sedid'];
                                    $cursoid=$detallecursos['cursoid'];
                                    $curid=$detallecursos['curid'];
                                    $turno=$detallecursos['turno'];
                                    $semid=$detallecursos['semid'];                                  

                                    $es = new Admin_Model_DbTable_Escuela();
                                    $res = $es->_getEscuela($eid, $oid, $escid);
                                    $nomescuela = $res['nom_escuela'];
                                    // Leer el nombre del curso
                                    $ncur = new Admin_Model_DbTable_Cursos();
                                    $rncur = $ncur->_getCurso($eid,$oid,$escid,$sedid,$cursoid,$curid);
                                    $ncurso_ =$rncur['nombre_curso'];

                                    if($detallecursos['uid']==$docentea['uid'])
                                    {
                                    ?>
                                  
                                    <?php
                                            
                                    $cursoid = $docentea['cursoid'];
                                    $curid = $docentea['curid'];

                                  
                                    ?>
                                    <tr>                                                           
                                         <td><?php echo $ncurso_?></td>                    
                                         <td><center><?php echo $semid?></center></td>                    
                                         <td><center><?php echo $turno?></center></td>                    
                                         <td><center><?php echo $detallecursos['grupos']?></center></td>
                                         <td><center><?php echo $detallecursos['horas_teoria']?></center></td>
                                         <td><center><?php echo $detallecursos['horas_practica']?></center></td>
                                         <td><center><?php echo $detallecursos['total_horas']?></center></td>   
                                    </tr>
                                    <?php 
                                        }                                   
                                    }
                                    ?>                                                                    
                                </tbody>              
                            </table>               
                        </td>
                    </tr>            
                    <?php  
                }
        } 
        ?>   
    </table>
    
    <br>
    <table class="table span10 table-condensed">
        <tr>
            <td><?php echo date("d/m/Y");?></td>
        </tr>

        <tr>
            <td></td>
        </tr>

        <br>      
        <center>
            <tr>
                <?php
                $eid=$this->eid;
                $oid=$this->oid;
                $pid=$this->pid;
                $persona = new Admin_Model_DbTable_Persona();
                $list_p = $persona ->_getPersona($eid,$oid,$pid);
                $info2 = $list_p['ape_pat']." ".$list_p['ape_mat']." ".$list_p['nombres'];
                ?>
                <td class='span4'><td>
                <td style='align:center'><?php echo $info2;?></td>     
            </tr>
        </center>
    </table>

    <?php 
      $html = ob_get_contents();
      $mpdf=new mPDF('win-1252','A4','','',15,15,2,12,5,7);
      $mpdf->SetHTMLHeader($header);
      $mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
      ob_end_clean();
      $mpdf -> WriteHTML($html);
      $mpdf->Output('INFORME DISTRIBUCION-'.'.pdf','D');
    ?>
    