<h3><center>Módulo Gestión de Escuelas</center></h3>
<table class="table">
	<tr>
   	<td style="text-align: right">
			<a style="float:right" title="Agregue Nuevo registro" class="btn btn-info" href="/admin/speciality/new"><i class="icon-pencil"></i>Nuevo</a>
   	</td>   				
	</tr>
</table>
<table style='margin-top:20px'>
	<tr>
		<td><h4>Seleccione Facultad:</h4></td>
		<td><div style='width: 250px; margin-left:100px'><?php echo $this->form->facid?></td>
	</tr>
</table>
<div id="list" style='margin-top:50px'></div>
<script type="text/javascript">
    $("#facid").change(function(){
    var facid=$(this).val();
    // alert(escid);
    url="/admin/speciality/getspeciality/facid/"+facid;
    $("#list").load(url);
     // alert(url);
});
</script>