<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Nueva Escuela');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/admin/speciality/  " class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>
<form id="<?php echo $this->form->getName();?>" name="<?php echo $this->form->getName();?>" action="<?php echo $this->form->getAction();?>"method="Post" enctype="application/x-www-form-urlencode">  
  
  <div class="flotacarajo">
    <div style="float:right; margin-left:10px"><?php echo $this->form->send?></div><br>
    <a style="float:right" class="btn btn-danger" href="/admin/speciality/">Cancelar</a>  
  </div>	
	<div class="flotacarajo">
      <table class="table table-striped table-hover ">
      <tr>
            <td>Facultades:</td>
            <td><div style='width: 200px'><?php echo $this->form->facid?></td>
      </tr>
      <tr>
            <td>Sedes:</td>
            <td><div style='width: 200px'><?php echo $this->form->subid?></td>
      </tr>
      <tr>
      	<td>Pariente:</td>
            <td><div style='width: 200px'><?php echo $this->form->parent?></td>
      </tr>	
      <tr>
            <td>Cod.Escuela:</td>
            <td><div style='width: 200px'><?php echo $this->form->escid?></td>
      </tr>      
      <tr>
            <td>Nombre:</td>
            <td><div style='width: 200px'><?php echo $this->form->name?></td>
      </tr>
      <tr>
            <td>Abreviacion:</td>
            <td><div style='width: 200px'><?php echo $this->form->abbreviation?></td>
      </tr>
      <tr>
            <td>Estado:</td>
            <td><div style='width: 200px'><?php echo $this->form->state?></td>
      </tr>
	  </table>
	</div>	
</form>

<script type="text/javascript">
    $("#facid").change(function(){
    var facid=$(this).val();
    // alert(escid);
    url="/admin/speciality/getfaculty/facid/"+facid;
    $("#parent").load(url);// alert(url);
});
</script> 

