<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-calendar"></span> Calendario');?>
<?php $this->placeholder('Btnnav')->append('<div class="btn-group">
	  <button type="button" class="btn btn-default">Día</button>
	  <button type="button" class="btn btn-default">Semana</button>
	  <button type="button" class="btn btn-default">Agenda</button>
	</div>');?>

<div class='row'>
	<div class="col-md-2">
		<div id="calendar_datapiket"></div>
	</div>
	<div class="col-md-10">
		<div class='row'>
			<div classs='col-md-11'>
				<div id="topcontainerwk">
				</div>
				<div id="topcontainerBorderwk" class="wk-border"></div>
				<div id="scrolltimedeventswk" class="wbkt wk-scrolltimedevents" style="height: 390px;">
					<div class="tg-mainwrapper" style="margin-top:0px;">
						
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>
<!-- <div style="z-index: 1001; width: 400px; left: 759.3333333333334px; top: 36px; visibility: visible;" class="bubble has-bottom-prong has-no-prong">
	<div id="bubblePromo:d" style="display: none;"></div>
	<div class="bubblemain">
		<div id="bubbleClose:d" class="bubbleclose"></div>
		<div class="bubblecontent" id="bubbleContent:d"><div><div></div>
		<div class="cb-root">
			
		</div>
		</div></div><div id="prong:d" class="bottom-prong" style="left: 182px;"><div class="prong-dk"></div><div class="prong-lt"></div></div>
	</div>
</div> -->
<script type="text/javascript" src="/js/controlactivity/calendar.js"></script>
<style type="text/css">
	.ui-datepicker{
		width: 14em;
	}
</style>