<?php
if ($this->data_user) {		
	$fullname = $this->data_user[0]['last_name0']." ".$this->data_user[0]['last_name1'].", ".$this->data_user[0]['first_name'];
	?>
<hr>
<div class='row col-md-8 col-md-offset-2'>
	<div class='panel panel-primary'>
		<div class='panel-body' style='font-size:17px'>
			<div>
				<div class='col-md-1'></div>
				<div class='col-md-3 text-right'><b>Apellidos y Nombres:</b></div>	
				<div class='col-md-6 text-info'><b><?php echo $fullname?></b></div>	
			</div><br><br>
			<div>
				<div class='col-md-2 text-right'><b>Escuela: </b></div>
				<div class='col-md-4'><?php echo $this->data_school['name']?></div>
				<div class='col-md-2 text-right'><b>Sede: </b></div>
				<div class='col-md-4'><?php echo $this->data_subsidiary['name']?></div>				
			</div><br><br>
			<div>
				<div class='col-md-2 text-right'><b>Periodo: </b></div>
				<div class='col-md-4 '>
					<select id='period' class='form-control'>
					<?php
						foreach ($this->data_period as $key => $periods) {
							?>
							<option value="<?php echo $periods['perid']?>"><?php echo $periods['perid']." | ".$periods['name']?></option>
						<?php	
						}
					?>
					</select>				
				</div>				
				<div class='col-md-2 text-right'><b>Tipo: </b></div>
				<div class='col-md-4 '>
					<select id='tipo' class='form-control'>
						<option value="ME">Movilidad Estudiantil</option>
						<option value="BE">Beca 18</option>
						<option value="PA">Pasantía</option>
					</select>				
				</div>
			</div><br><br><br>
			<div>
				<div class='col-md-3 '>
				</div>				
				<div class='col-md-4 text-right'>
					<a id='_save' href="#" class='btn btn-success' uid='<?php echo base64_encode($this->uid)?>' fullname='<?php echo base64_encode($fullname)?>' escid='<?php echo base64_encode($this->data_school['escid'])?>'><span class='glyphicon glyphicon-save'></span>Guardar</a>
				</div>
			</div><br><br>
		</div>
	</div>
</div>
<div id="saving"></div>
<?php	
}
else{	?>
	<hr>
	<div class='row col-md-8 col-md-offset-2 alert alert-danger text-center'>
		<h4><b>No existe el alumno(a)</b></h4>
	</div>
<?php
}
?>

<script type="text/javascript">
	$("#_save").click(function(){
		var uid=$(this).attr("uid");
		var fullname=$(this).attr("fullname");
		var escid=$(this).attr("escid");
		var tipo=$('#tipo').val();
		var period=$('#period').val();

		var url=("/acreditacion/universityextension/registerstudentsextension/type/"+tipo+"/perid/"+period+"/state/A/uid/"+uid+"/fullname/"+fullname+"/escid/"+escid);
		$("#saving").load(url);
	});
</script>