
<div>
	<div class="panel panel-primary">
  	<div class="panel-heading">
		<h5 class="panel-title">

	  	<span class='glyphicon glyphicon-eye-open'></span>

	  	<strong> <?php echo $this->info_couser['name']?> TURNO <?php echo $this->turno?></strong>
	  	<?php $data_course=$this->info_couser; 
	  		$uidac="";
	  		$pidac="";
	  		$url="/".base64_encode('escid')."/".base64_encode($data_course['escid']).
	  			"/".base64_encode('subid')."/".base64_encode($data_course['subid']).
	  			"/".base64_encode('curid')."/".base64_encode($data_course['curid']).
	  			"/".base64_encode('perid')."/".base64_encode($this->perid).
	  			"/".base64_encode('type')."/".base64_encode($this->type).
	  			"/".base64_encode('turno')."/".base64_encode($this->turno).
	  			"/".base64_encode('courseid')."/".base64_encode($data_course['courseid']);
	  	?>
	  	<div class='pull-right'>
	  		<a href="/record/index/preregister<?php echo $url?>" class='btn btn-xs btn-success'><span class='glyphicon glyphicon-print'></span> Pre-Registro</a>
	  		<a href="#" class='btn btn-xs btn-success'><span class='glyphicon glyphicon-print'></span> Avance Notas</a>

	  	</div>
	  </h5>
  	</div>
	<table class="table">
	  	<tr>
	  		<th>Curricula</th>
	  		<th>Tipo de Calificacion</th>
	  		<th>Fecha de Cierre de Acta </th>
	  		<th>Estado del Acta</th>
	  	</tr>
	  	<tr>
	  		<td><?php echo $this->info_couser['curid']?></td>
	  		<td><?php if($this->type =="O") echo "Objetivo";
	  				 else echo "Compencia";?>
	  		</td>
	  		<td><?php echo $this->closure?></td>
	  		<td><?php 
				switch ($this->state){
					case "A": $img="verde";break;	
					case "C": $img="rojo";break;
					default: $img="azul";break;
				}?>
				<img src="/img/circulo-<?php echo $img?>.png"></td>
	  	</tr>
    </table>
	</div>
	<div class="panel panel-primary">
  		<div class="panel-heading"><h5 class="panel-title"><span class='glyphicon glyphicon-ok-circle'></span><strong> Docentes Asignados</strong></h5></div>
	  		<table class="table">
		  	<tr>
		  		<th>DNI</th>
		  		<th>Apellidos y Nombres</th>
		  		<th>Estado</th>
		  		<th>Principal</th>
		  		<th>Compromiso</th>
		  		<?php 
		  		if($this->rid=='AD'){?>
		  		<th>Opcion</th>
		  		<?php
		  		}?>
		  	</tr>
		  	<?php 
		  	if ($this->info_teacher) {		  		
		  	foreach ($this->info_teacher as $key => $teacher) { ?>
		  		<tr>
		  			<td id="pid<?php echo $teacher['pid']?>"><?php echo $teacher['pid']?></td>
		  			<td><?php echo $teacher['name']?></td>
		  			<td><?php 
		  				switch ($teacher['state']) {
		  					case 'A':
		  						echo 'Activo';
		  						break;
		  					case 'P':
		  						echo 'Jefe de Practica';
		  						break;
		  					case 'L':
		  						echo 'Licencia';# code...
		  						break;	
		  					default:
		  						echo "";# code...
		  						break;
		  				}
		  			?></td>
		  			<td><?php switch ($teacher['is_main']) {
		  				case 'S':
		  					echo '<p id="active" pid="'.$teacher['pid'].'" uid="'.$teacher['uid'].'">SI<p>';
		  					break;
		  				case 'N':
		  					echo "NO";# code...
		  					break;
		  				default:
		  					echo "";# code...
		  					break;
		  			}
		  			?></td>
		  			<td><?php switch ($teacher['is_com']) {
		  				case 'S':
		  					echo "SI";# code...
		  					break;
		  				case 'N':
		  					echo "NO";# code...
		  					break;
		  				default:
		  					echo "";# code...
		  					break;
		  			}?></td>
		  			<?php 
		  			if($this->rid=='AD'){?>
		  			<td>
		  				<?php
		  				if($teacher['state']=='P'){?>
		  					<button type="button" class="btn btn-info btn-xs"
		  					id="reasignar<?php echo $teacher['pid']?>" 
		  					escid="<?php echo $data_course['escid']?>"
		  					subid="<?php echo $data_course['subid']?>"
		  					curid="<?php echo $data_course['curid']?>"
		  					perid="<?php echo $this->perid?>"
		  					courseid="<?php echo $data_course['courseid']?>"
		  					turno="<?php echo $this->turno?>"
		  					uid= "<?php echo $teacher['uid']?>"
		  					pid= "<?php echo $teacher['pid']?>"
		  					>
		  					<span class="glyphicon glyphicon-upload"></span> Principal</button>
		  					<script>
		  					$("#reasignar<?php echo $teacher['pid']?>").click(function(e){
								var dataAjax = {
									'escid' : $(this).attr('escid'),
									'subid' : $(this).attr('subid'),
									'curid' : $(this).attr('curid'),
									'perid' : $(this).attr('perid'),
									'courseid' : $(this).attr('courseid'),
									'turno' : $(this).attr('turno'),
									'pid' : $(this).attr('pid'),
									'uid' : $(this).attr('uid'),
									'uidac' : $('#active').attr('uid'),
									'pidac' : $('#active').attr('pid')
								};
								console.log(dataAjax);
								e.preventDefault;
								$.ajax({
									type : "post",
									url : "/record/index/principalteacher/",
									data : dataAjax,
									success : function(data){
										$('.infor').html(data);
										$("#modal").modal("hide");
									}
								});
							});	
		  					</script>
						<?php
		  				}
		  				?>		  					  				
		  			</td><?php
		  			}
		  			?>
		  		</tr>
	  		<?php }?>
	  		</table>
	  		<?php
		  	}else{
	  	?>
	  	<div>
	  		<table class="table table-striped">
	  					<tr><th colspan="10" style="background:#7A7A7A;color:white"><center>ASIGNAR DOCENTE</center></th></tr>
						<tr>
				            <th><center>Seleccione Escuela / Docente</center></th>
				            <th colspan="2"><center>Seleccione el Docente</center></th>
				            <th> <center> Opcion</center></th>
						</tr>
						<tr>
							<td>
				                <select id="escuid" class="form-control">
				                    <option value="">- Seleccione Escuela -</option>
				                    <?php 
				                    if ($this->lescuelas){
				                        foreach ($this->lescuelas as $escu){ 
				                        	if($escu['escid']==$this->escuela){?>
				                        		<option value="<?php echo $escu['escid'].";--;".$escu['subid']?>"><?php echo $escu['name']?></option>          
				                        	<?php
				                        	}?>
				                            
				                        <?php                                 
				                        }
				                    } ?>
				                </select>
				            </td>
				            <td colspan="2">
				                <center>
				                    <select id='docente_reg' name='docente_reg' class="form-control" style="width:350px">
				                        <option value="">- Seleccione Docente -</option>
				                    </select>
				                </center>
				            </td>
				            <td>
				            	<center><a type="button" class="btn btn-success" id="savedata" 
				            	data-dismiss="modal"
				            	escid = '<?php echo $data_course['escid']?>'
				            	curid =	'<?php echo $data_course['curid']?>'
				            	subid = '<?php echo $data_course['subid']?>'
				            	perid = '<?php echo $this->perid?>'
				            	courseid = '<?php echo $data_course['courseid']?>'
				            	turno = '<?php echo $this->turno?>'
				            	opcion = '0'
				            	href='#'><span class="glyphicon glyphicon-floppy-disk"></span> Guardar </a></center>
				            </td>
						</tr>
				</table>
		</div>
	  	<?php 
	  		}?>
	  <div class="infor"></div>
	</div>
	</div>
	<?php
	  if($teacher['pid'] == "TEMP01"){?>
		  	<div class="panel panel-primary">
		  		<div class="panel-heading">
			  		<h5 class="panel-title"><span class='glyphicon glyphicon-plus-sign'></span><strong> Asignar Docente <span class="label label-default text-reght" ></span>
			 		</strong></h5>
			  	</div>
		  			<table class="table">
						<tr>
				            <th><center>Seleccione Escuela / Docente</center></th>
				            <th colspan="2"><center>Seleccione el Docente</center></th>
				            <th> <center> Opcion</center></th>
						</tr>
						<tr>
							<td>
				                <select id="escuid" class="form-control">
				                    <option value="">- Seleccione Escuela -</option>
				                    <?php 
				                    if ($this->lescuelas){
				                        foreach ($this->lescuelas as $escu){ ?>
				                            <option value="<?php echo $escu['escid'].";--;".$escu['subid']?>"><?php echo $escu['name']?></option>
				                        <?php                                 
				                        }
				                    } ?>
				                </select>
				            </td>
				            <td colspan="2">
				                <center>
				                    <select id='docente_reg' name='docente_reg' class="form-control" style="width:350px">
				                        <option value="">- Seleccione Docente -</option>
				                    </select>
				                </center>
				            </td>
				            <td>
				            	<center><a type="button" class="btn btn-success" id="savedata" 
				            	data-dismiss="modal"
				            	escid = '<?php echo $data_course['escid']?>'
				            	curid =	'<?php echo $data_course['curid']?>'
				            	subid = '<?php echo $data_course['subid']?>'
				            	perid = '<?php echo $this->perid?>'
				            	courseid = '<?php echo $data_course['courseid']?>'
				            	turno = '<?php echo $this->turno?>'
				            	opcion = '1'
				            	href='#'><span class="glyphicon glyphicon-floppy-disk"></span> Guardar </a><center>
				            </td>
						</tr>
					</table>
		</div>
	  	<?php   }?>
	<div class="panel panel-primary">
	  	<div class="panel-heading">
	  		<h5 class="panel-title"><span class='glyphicon glyphicon-th-list'></span><strong> Alumnos Matriculados <span class="label label-default text-reght" ><?php echo $this->numregister?></span>
	 		</strong></h5>
	  	</div>
	  	<table class="table">
	    	<tr class='tetx-center'>
	    		<th>#</th>
	    		<th>Codigo</th>
	    		<th>Apellidos y Nombres</th>
	    		<th>Promedio</th>
	    		<th>Recibo</th>
	    		<th>Resolucion</th>
	    	</tr>
	    	  		<?php 
	    	  		if ($this->data_students) {
	    	  			
	    	  		foreach ($this->data_students as $key => $student) { ?>
			    		<tr>
			    			<td><?php echo $key+1?> </td>
			    			<td><?php echo $student['uid']?></td>
			    			<td><?php echo $student['name_complet']?></td>
			    			<td class='text-center'><?php 
			    				switch ($student['notafinal']) {
			    					case '-3':
			    						echo "Retirado";
			    						break;
			    					case '-2':
			    						echo "N.S.P";
			    						break;
			    					default:
			    						echo $student['notafinal'];
			    						break;
			    				}
			    			?></td>
			    			<td><?php 
			    				if ($student['receipt']) {
			    					echo $student['receipt'];
			    				}
			    				// else{	
			    				// 	switch ($student['notafinal']) {
				    			// 		case '-3':
				    			// 			echo "";
				    			// 			break;
				    			// 		case '-2':
				    			// 			echo "";
				    			// 			break;
				    			// 		default:				    			
				    			// 			break;
				    			// 	}	
			    				// }
			    				?>			    					
			    			</td>
			    		</tr>
	    			<?php }
	 				}
	    		?>
	  	</table>
	</div>
	<div class="data"></div>
</div>
<script>
$("#escuid").change(function(){
    var escuela = $(this).val();
    if (escuela=="") {
        alert("Seleccione una Escuela.");
        return false;
    };
    tmp=escuela.split(';--;');
    escid=tmp[0];
    $("#docente_reg").load("/record/index/teacherxschool/escid/"+escid);
});
$("#savedata").click(function(e){
	var docente = $("#docente_reg").val();
	var tmp = docente.split(';--;');
	var uid = tmp[0];
	var pid = tmp[1];
	var ajaxData ={
		'escid' : $(this).attr('escid'),
		'curid' : $(this).attr('curid'),
		'subid' : $(this).attr('subid'),
		'perid' : $(this).attr('perid'),
		'courseid' : $(this).attr('courseid'),
		'turno' : $(this).attr('turno'),
		'uid' : uid,
		'pid' : pid,
		'opcion' : $(this).attr('opcion')
	};
	console.log(ajaxData);
	e.preventDefault();
	$.ajax({
		type : "post",
		url : "/record/index/updatedatacourse/",
		data : ajaxData,
		success : function(data){
			$(".loaddelete").html(data);
			//$("#modal1").modal("hide");
		}
	});	
});
</script>