
<div>
	<div class="panel panel-primary">
  	<div class="panel-heading">
		<h5 class="panel-title">

	  	<span class='glyphicon glyphicon-eye-open'></span>

	  	<strong> <?php echo $this->info_couser['name']?> TURNO <?php echo $this->turno?></strong>
	  	<?php $data_course=$this->info_couser; 
	  		$url="/".base64_encode('escid')."/".base64_encode($data_course['escid']).
	  			"/".base64_encode('subid')."/".base64_encode($data_course['subid']).
	  			"/".base64_encode('curid')."/".base64_encode($data_course['curid']).
	  			"/".base64_encode('perid')."/".base64_encode($this->perid).
	  			"/".base64_encode('type')."/".base64_encode($this->type).
	  			"/".base64_encode('turno')."/".base64_encode($this->turno).
	  			"/".base64_encode('courseid')."/".base64_encode($data_course['courseid']);
	  	?>
	  	<div class='pull-right'>
	  		<a href="/record/index/preregister<?php echo $url?>" class='btn btn-xs btn-success'><span class='glyphicon glyphicon-print'></span> Pre-Registro</a>
	  		<a href="#" class='btn btn-xs btn-success'><span class='glyphicon glyphicon-print'></span> Avance Notas</a>

	  	</div>
	  </h5>
  	</div>
	<table class="table">
	  	<tr>
	  		<th>Curricula</th>
	  		<th>Tipo de Calificacion</th>
	  		<th>Fecha de Cierre de Acta </th>
	  		<th>Estado del Acta</th>
	  	</tr>
	  	<tr>
	  		<td><?php echo $this->info_couser['curid']?></td>
	  		<td><?php if($this->type =="O") echo "Objetivo";
	  				 else echo "Compencia";?>
	  		</td>
	  		<td><?php echo $this->closure?></td>
	  		<td><?php 
				switch ($this->state){
					case "A": $img="verde";break;	
					case "C": $img="rojo";break;
					default: $img="azul";break;
				}?>
				<img src="/img/circulo-<?php echo $img?>.png"></td>
	  	</tr>
    </table>
	</div>
	<div class="panel panel-primary">
  		<div class="panel-heading"><h5 class="panel-title"><span class='glyphicon glyphicon-ok-circle'></span><strong> Docentes Asignados</strong></h5></div>
	  		<table class="table">
		  	<tr>
		  		<th>DNI</th>
		  		<th>Apellidos y Nombres</th>
		  		<th>Estado</th>
		  		<th>Principal</th>
		  		<th>Compromiso</th>
		  	</tr>
		  	<?php foreach ($this->info_teacher as $key => $teacher) { ?>
		  		<tr>
		  			<td><?php echo $teacher['pid']?></td>
		  			<td><?php echo $teacher['name']?></td>
		  			<td><?php 
		  				switch ($teacher['state']) {
		  					case 'A':
		  						echo 'Activo';
		  						break;
		  					case 'P':
		  						echo 'Jefe de Practica';
		  						break;
		  					case 'L':
		  						echo 'Licencia';# code...
		  						break;
		  					default:
		  						echo "";# code...
		  						break;
		  				}
		  			?></td>
		  			<td><?php switch ($teacher['is_main']) {
		  				case 'S':
		  					echo "SI";# code...
		  					break;
		  				case 'N':
		  					echo "NO";# code...
		  					break;
		  				default:
		  					echo "";# code...
		  					break;
		  			}
		  			?></td>
		  			<td><?php switch ($teacher['is_com']) {
		  				case 'S':
		  					echo "SI";# code...
		  					break;
		  				case 'N':
		  					echo "NO";# code...
		  					break;
		  				default:
		  					echo "";# code...
		  					break;
		  			}?></td>
		  		</tr>
	  	<?php }?>
	  </table>
	</div>
	<div class="panel panel-primary">
	  	<div class="panel-heading">
	  		<h5 class="panel-title"><span class='glyphicon glyphicon-th-list'></span><strong> Alumnos Matriculados <span class="label label-default text-reght" ><?php echo $this->numregister?></span>
	 		</strong></h5>
	  	</div>
	  	<table class="table">
	    	<tr class='tetx-center'>
	    		<th>#</th>
	    		<th>Codigo</th>
	    		<th>Apellidos y Nombres</th>
	    		<th>Promedio</th>
	    		<th>Recibo</th>
	    		<th>Resolucion</th>
	    	</tr>
	    	  		<?php foreach ($this->data_students as $key => $student) { ?>
	    		<tr>
	    			<td><?php echo $key+1?> </td>
	    			<td><?php echo $student['uid']?></td>
	    			<td><?php echo $student['name_complet']?></td>
	    			<td class='text-center'><?php 
	    				switch ($student['notafinal']) {
	    					case '-3':
	    						echo "Retirado";
	    						break;
	    					case '-2':
	    						echo "N.S.P";
	    						break;
	    					default:
	    						echo $student['notafinal'];
	    						break;
	    				}
	    			?></td>
	    			<td><?php echo $student['receipt']?></td>

	    		</tr>
	    	<?php }?>
	  	</table>
	</div>

</div>