<form id="formRecord" name="formRecord" action="/record/index/list/" method="post">
	<table class="table table-hover table-condensed">
		<tr>
			<th class="col-lg-1">Año</th>
			<th class="col-lg-2">Periodo</th>
			<th class="col-lg-2">Escuela(s)</th>
			<th class="col-lg-2">Nombre Curso</th>
			<th class="col-lg-1">Operaciones</th>
		</tr>
		<tr>
			<td>
				<select name="year" id="year" class="form-control">
				<?php 
				for($i=date('Y')+1;$i>=1965;$i--){
				$txt="";
				if ($i==date('Y')) $txt = "selected";
				?>
					<option value="<?php echo base64_encode($i)?>" <?php echo $txt?>><?php echo $i?></option>
					<?php 
				}
				?>
				</select>
			</td>
			<td>
				<select id="perid" name="perid" class="form-control">
					<option value="">Selección un periodo</option>
				</select>
			</td>
			<td>
				<select id="escid" name="escid" class="form-control">
				<?php 
				$specialitys =$this->specialitys;
				if ($specialitys){
					foreach ($specialitys as $esc){
						$escid=base64_encode($esc['escid']);
						$subid_cryp=base64_encode($esc['subid']);
						$name=($esc['name']);
					?>
					<option value="<?php echo $escid.";--;".$subid_cryp?>"><?php echo $name?></option>
					<?php 
					}
				}else{
				?>
					<option value="">Selección una escuela</option>
				<?php } ?>
				</select>
			</td>
			<td>
				<input type="text" name="coursename" id="coursename" class="form-control">
			</td>
			<td><input type="submit" name="send" id="sendform" value="Buscar" class="form-control btn btn-success"></td>
		</tr>

	</table>
</form>
<div class="panel panel-default">
	<div class="loadcourses">Espacio para mostrar las asignaturas	</div>
  	
</div>

<script>
$(function() {
	var year_a="<?php echo base64_encode(date('Y'));?>";
	$("#year").change(function(){
		var year =$("#year").val();
		$("#perid").html("<option value=''>Cargando...</option>");
		$("#perid").load("/record/index/periods/year/"+year);		
	});
	$("#perid").load("/record/index/periods/year/"+year_a);
	$("#sendform").click(function(e){
		e.preventDefault();
		$(".loadcourses").html("<img src='/img/spinner.gif'>Cargando....");
		$.ajax({
	        type: "POST",
	        url: $("#formRecord").attr("action"),
	        data: $("#formRecord").serialize(),
	        success: function(data){
	       		$(".loadcourses").html(data);
	      	}		
		});
		return false;
		
	});
	
});
</script>
