<style type="text/css">
	.modal-dialog
	{
		width: 900px;
	}
</style>
<script >
	function modified_record($this){
		var $record = {};

		$record[$.base64.encode('courseid')] = $.base64.encode($.trim($($this).attr('courseid')));
		$record[$.base64.encode('turno')] = $.base64.encode($.trim($($this).attr('turno')));
		$record[$.base64.encode('curid')] = $.base64.encode($.trim($($this).attr('curid')));
		$record[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
		$record[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
		$record[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
		$record[$.base64.encode('state')] = $.base64.encode($.trim($($this).attr('state')));
		$record[$.base64.encode('closure')] = $.base64.encode($.trim($($this).attr('closure')));
		$record[$.base64.encode('typea')] = $.base64.encode($.trim($($this).attr('typea')));

		var result='';

		for(var pro in $record){
			result += '' + pro + '/' + $record[pro]+ '/';
		}
        result = result.substring(0, result.length-1);
        var $url = '/record/index/modifiedrecord/'+ result;
        $("#modal").modal('show');
        $(".modal-dialog").load($url);
	}
</script>

<div class="modal fade" id='modal'>
  <div class="modal-dialog">
    
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php 
$stateperiod = $this->stateperiod;
$strprint = "/record/index/printavence/"
?>

<div class="alert alert-info " style="margin:0px; padding:3px;">
<?php if ($stateperiod=="A"){?>
	<a class="btn btn-primary " href="#">Agregar Asignatura</a>
<?php } ?>
	<a class="btn btn-primary " href="#" id="openwindows">Reporte Avance de Notas</a>
</div>

<table class="table table-striped table-hover table-bordered table-condensed">
	<tr>
		<th class="small">#</th>
		<th class="small">Sem.</th>
		<th class="col-sm-1">Curricula </th> 
		<th class="col-sm-1">Código Asig.</th>
		<th class="col-sm-4">Nombre Asignatura </th>
		<th class="small">Turno</th>
		<th class="col-sm-1">Calificación</th>
		<th class="col-sm-1"># Matric.</th>
		<th class="col-sm-1">Primer Parcial</th>
		<th class="col-sm-1">Segundo Parcial</th>
		<th class="col-sm-2">Fecha Cierre Acta</th>
		<th class="small">Estado</th>
	</tr>
	
	<?php 
	$courses =$this->courses;
	
	if ($courses){
		$i=0;
		foreach ($courses as $course){
			$i++;
			$counregister=0;
			$semid=($course['semid']);
			$name=($course['course']);
			//PK
			$courseid=($course['courseid']);
			$courseid_cr=base64_encode($course['courseid']);
			$escid=($course['escid']);
			$escid_cy=base64_encode($course['escid']);
			$subid=($course['subid']);
			$subid_cy=base64_encode($course['subid']);
			$turno=($course['turno']);
			$turno_cy=base64_encode($course['turno']);
			$curid=($course['curid']);
			$curid_cy=base64_encode($course['curid']);
			$perid=($course['perid']);
			$perid_cy=base64_encode($course['perid']);
			
			$urldetaul = "perid/$perid_cy/escid/$escid_cy/subid/$subid_cy/courseid/$courseid_cr/curid/$curid_cy/turno/$turno_cy";
			$date=($course['closure_date']);
			$type = ($course['type_rate']=="O")?"Objetivo":"Competencia";
			$stater = $course['state_record'];
			switch ($stater){
				case "A": $txtstate = "class='success'";break;
				case "C": $txtstate = "class='danger'";break;
				default: $txtstate = "";break;
			}
			$state = $course['state'];
			if ($state=="S" && ($stater=="C" || $stater=="A")){
				$sp = "glyphicon-ok";
				$pp = "glyphicon-ok";
			}else{
				$sp="glyphicon-remove";
				$pp = ($state=="P" && $stater=="A")?"glyphicon-ok":"glyphicon-remove";
			}
			$counregister = $course['numregister'];
			?>
	<tr >
		<td rowspan="2" style="vertical-align:middle"><?php echo $i;?></td>
		<td class="center"><?php echo $semid?></td>
		<td class="center"><?php echo $curid?></td>
		<td class="center"><?php echo $courseid?></td>
		<td><?php echo $name?></td>
		<td class="center"><?php echo $turno?></td>
		<td class="center"><?php echo $type;?></td>
		<td class="center"><?php echo $counregister;?></td>
		<td class="center"><span class="glyphicon <?php echo $pp?> txthover" 
		data-toggle="tooltip" title="Estado del Primer parcial"
		></span></td>
		<td class="center"><span class="glyphicon <?php echo $sp?> txthover"
		data-toggle="tooltip" title="Estado del segundo parcial"></span></td>
		<td><?php echo $date;?></td>
		<td class="center">
		<a href="#" onclick=" javascript:
				window.open('/record/index/detail/<?php echo $urldetaul?>',
				'Detalle de Asignatura',
				'width=800,height=600,menubar=no,resizable=yes,toolbar=no,scrollbars=yes');
			">
		<span class="glyphicon glyphicon-folder-open txthover" 
		data-toggle="tooltip" title="Ver detalles del acta"></span>
		</a></td>
		<td class="center"  rowspan="2">
			<?php 
			switch ($course['state_record']){
				case "A": $img="verde";break;	
				case "C": $img="rojo";break;
				default: $img="azul";break;
			}?>
			<img src="/img/circulo-<?php echo $img?>.png">
		</td>
	</tr>	
	<tr>
		<th colspan="2">OPERACIONES</th>
		<td colspan="9" >
			<button type="button" 
			class="btn btn-primary btn-xs"
			courseid="<?php echo $course['courseid']?>"
			turno="<?php echo $course['turno']?>"
			curid="<?php echo $course['curid']?>"
			escid="<?php echo $course['escid']?>"
			subid="<?php echo $course['subid']?>"
			perid="<?php echo $course['perid']?>"
			state="<?php echo $course['state_record']?>"
			closure="<?php echo $course['closure_date']?>"
			typea="<?php echo $course['type_rate']?>"
			onclick="modified_record(this)"
			>
			<span class='glyphicon glyphicon-edit'></span> Modificar Acta</button>
		</td>
	</tr>		
			<?php 
			}
	}else{
	?>
		Ni hay ningun dato
	<?php } ?>
</table>

<script>
	$("#openwindows").click(function (){
		var perid=$("#perid").val();
		var escid=$("#escid").val();
		var url = "<?php echo $strprint?>perid/"+perid+"/escid/"+escid;
		open(url);
	});
	$(".txthover").tooltip({
	    placement: "left"
	});
	
</script>
