<script type="text/javascript">
	$("#new-teacher").click(function(){
		var data =  $("#form-new-teacher").serializeArray();
		var url = "/record/index/savemodifiedrecord/";
		$.get(url,data,function($data){
			alert($data);
		});
	});
	
</script>

<div class="modal-content">
    <div class="modal-body">
        	<div class='row'>
        		<div class='col-md-12'>
        			<div class='row'>
        				<div class="panel panel-primary">
						  <div class="panel-heading">
						  	<h5 class="panel-title">
						  	<span class='glyphicon glyphicon-edit'></span><strong> <?php echo $this->info_couser['name']?> TURNO <?php echo $this->turno?></strong>
						  </h5>
						</div>
							  <table class="table">
							  	<tr>
							  		<th>Curricula</th>
							  		<th>Tipo de Calificacion</th>
							  		<th>Fecha de Cierre de Acta </th>
							  		<th>Estado del Acta</th>
							  	</tr>
							  	<tr>
							  		<td><?php echo $this->info_couser['curid']?></td>
							  		<td><?php if($this->type =="O") echo "Objetivo";
							  				 else echo "Compencia";?>
							  		</td>
							  		<td><?php echo $this->closure?></td>
							  		<td><?php 
										switch ($this->state){
											case "A": $img="verde";break;	
											case "C": $img="rojo";break;
											default: $img="azul";break;
										}?>
										<img src="/img/circulo-<?php echo $img?>.png"></td>
							  	</tr>
							  </table>
						</div>
						<form id= "form-new-teacher" >
        				<div class="panel panel-primary">
						  <div class="panel-heading"><h5 class="panel-title">Docentes Asignados</h5></div>
							  <table class="table">
							  	<tr>
							  		<th>DNI</th>
							  		<th>Apellidos y Nombres</th>
							  		<th>Estado</th>
							  		<th>Principal</th>
							  		<th>Compromiso</th>
							  		<th>Eliminar</th>
							  	</tr>
							  	<?php foreach ($this->info_teacher as $key => $teacher) { ?>
							  		
							  		<tr>
							  			<td><?php echo $teacher['pid']?></td>
							  			<td><?php echo $teacher['name']?></td>
							  			<td><?php echo $teacher['state']?></td>
							  			<td><?php if ($teacher['is_main']=='S'){echo "SI"; ?>
							  				<input type='hidden' name="hourstS" value='<?php echo $teacher['hours_t']?>'>
							  				<input type='hidden' name="hourspS" value='<?php echo $teacher['hours_p']?>'>
							  				<input type='hidden' name="hourstotalS" value='<?php echo $teacher['hours_total']?>'>
							  			<?php } else { echo "No";?>
											<input type='hidden' name="hourstN" value='<?php echo $teacher['hours_t']?>'>
							  				<input type='hidden' name="hourspN" value='<?php echo $teacher['hours_p']?>'>
							  				<input type='hidden' name="hourstotalN" value='<?php echo $teacher['hours_total']?>'>
							  			<?php }
							  			?></td>
							  			<td><?php if($teacher['is_com']=='S') echo "SI";
							  						else echo "NO";?></td>
							  			<td><a href="#"><span class='glyphicon glyphicon-trash'></span></a></td>
							  		</tr>
							  	<?php }?>
							  </table>
						</div>
					
						<div class="panel panel-primary">
						  <div class="panel-heading">
						    <h3 class="panel-title">Asignar Nuevo Docentes</h3>
						  </div>
						  
							  <div class="panel-body">
							    <div class="row">
							    	<input type="hidden" name='courseid'value='<?php echo $this->info_couser['courseid']?>'>
							    	<input type="hidden" name='curid'value='<?php echo $this->info_couser['curid']?>'>
							    	<input type="hidden" name='escid'value='<?php echo $this->info_couser['escid']?>'>
							    	<input type="hidden" name='semid'value='<?php echo $this->info_couser['semid']?>'>
							    	<input type="hidden" name='perid'value='<?php echo $this->perid?>'>
							    	<input type="hidden" name='subid'value='<?php echo $this->subid?>'>
							    	<input type="hidden" name='turno'value='<?php echo $this->turno?>'>
							    	
								  <div class="col-lg-3">
								  	<strong>Escuela de procedencia:</strong>
								    <select class="form-control" name='speciality' id="speciality">
								    	<option value=''>Seleccione Escuela</option>
								    	<?php foreach ($this->speciality as  $value) { ?>
								    		<option value='<?php echo $value['escid']?>'><?php echo $value['name']?></option>
								    	<?php  }?>
								    </select>
								  </div>
								  <div class="col-lg-3">
								    <label>Docente</label>
								    <select class="form-control" name='teachers' id='teachers'>
								    	<option value='' >Seleccione Docente</option>
								    </select>
								  </div>
								  <div class="col-lg-2">
								    <strong>Estado</strong>
								    <select class="form-control" name='state' id='state'>
								    	<option Value='A'>Activo</option>
								    	<option Value='L'>Licencia</option>
								    	<option Value='P'>Jefe Practica</option>
								    </select>
								  </div>
								  <div class="col-lg-2">
								    <strong>Compromiso</strong>
								    <select class="form-control" name='iscom' id='iscom'>
								    	<option Value='N'>No</option>
								    	<option Value='S'>Si</option>
								    </select>
								  </div>
								  <div class="col-lg-2">
								    <strong>Principal</strong>
								    <select class="form-control" name='ismain' id='ismain'>
								    	<option Value='S'>Si</option>
								    	<option Value='N'>No</option>
								    </select>
								  </div>
								</div>
							  </div>
							  <button type="button" class="btn btn-success" id='new-teacher'
						        	><span class='glyphicon glyphicon-floppy-disk'>
						     	</span> Guardar</button>
						  </form>
						</div>
        			</div>
        		</div>
        	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class='glyphicon glyphicon-floppy-remove'></span> Cancelar</button>
        
      </div>
</div><!-- /.modal-content -->

<script type="text/javascript">
	$("#speciality").change(function(){
		$("#speciality").each(function(){
			var escid = $(this).val();
			var url = "/record/index/teachers/";
			if (escid != ""){
				$.get(url,{escid:$.base64.encode(escid)},function(data){
				$("#teachers").html(data);
				});
			}
			else{
				alert("slecion Escuela");
				$(".alert").alert();
			}
		});
	});
</script>
