<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$perid=$this->perid;
$course = $this->info_couser;
$students = $this->students;
$mpdf->mirrorMargins = 1;
$mpdf->mirrorMargins = 1;	// Use different Odd/Even headers and footers and mirror margins

$header = '
<table width="100%" style="border: 1px solid #000;font-family: serif;  color: #000; ">
	<tr style="text-align:center; padding-left: 100px; ">
    	<td  rowspan="2" width="340px" style="border: 1px solid #000 "><img src="/img/header_imprimir.jpg">
    	</td>
    	<td style="text-align:center; font-size:10px; border: 1px solid #000 ">
    		FACULTAD '.strtoupper($speciality['name_faculty']).'<br/>
    		ESCUELA '.strtoupper($name_esc).'<br/>
    		'.strtoupper($name_speciality).'<br/>
    		
    	</td>
	</tr>
	<tr>
		
	</tr>
</table>
<table width="100%" style="border-bottom: 2px solid #000; font-family: serif;  color: #000; margin-bottom:20px;">
	<tr >
		<td  style="font-size:10px; text-align:left;  " >
		<strong sytle="padding-right:10px">Curso </strong>'.$course['courseid'].' - '.$course['name'].'
		</td>
		
        <td style="text-align: right; font-size:10px;"><strong>Turno </strong> '.$course['turno'].'</td>
        <td  style="text-align: right; font-size:10px;"><strong>Creditos </strong>'.$course['credits'].' </td>
	</tr>
	<tr >
        <td   style="text-align:left; font-size:10px;"><strong>Docente </strong> '.$course['name_teacher'].'</td>
        <td  style="text-align: right; font-size:10px;"><strong>Semestre </strong>'.$course['semid'].' </td>
        <td  style="text-align:right; font-size:10px;"><strong>Alumnos </strong>'.count($students).' </td>
	</tr>
</table>
';

?>
<style type="text/css">
.sv
{
	right: 
}
</style>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<table width="100%">
    <tr >
        <td  style="font-size:10px; text-align:left;  " >
        <strong sytle="padding-right:5px">Curso: </strong><?php echo $course['courseid']." - ".$course['name']?>
        </td>
        
        <td style="text-align: right; font-size:10px;"><strong>Turno: </strong> <?php echo $course['turno']?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Créditos: </strong><?php echo $course['credits'] ?></td>
    </tr>
    <tr >
        <td   style="text-align:left; font-size:10px;"><strong>Docente: </strong> <?php echo $course['name_teacher']?></td>
        <td  style="text-align: right; font-size:10px;"><strong>Semestre: </strong><?php echo $course['semid'] ?></td>
        <td  style="text-align:right; font-size:10px;"><strong>Alumnos: </strong><?php echo count($students)?></td>
    </tr>
</table>
<div style="text-align:center; font-size:12px; width:100%; margin-top:2%;" ><strong>ACTA EVALUACIÓN - PERIODO <?php echo $perid?></strong></div>
<table style='font-size:11px; width:100%; margin-top:2%;'>
	<tr style='background-color: #cccbcb'>
		<th class="center">#</th>
		<th class="center">Código</th>
		<th class="center">Apellidos y Nombres</th>
		<th class="center">Nota</th>
	</tr>
	<?php $R=0;	$apro=0; $j=0;
		foreach ($students as $key => $student) {?>
		<tr>
			<td class="center"><?php echo $key+1?></td>
			<td class="center"><?php echo $student['uid']?></td>
			<td><?php echo $student['name_complet']?></td>
			<td class="center"><?php
				
				$notafinal = intval(trim($student['notafinal']));
				switch ($notafinal) {
				 	case -2:
				 		echo "N.S.P";
				 		$R++;
				 		break;
				 	case -3:
				 		echo "Retirado";
				 		$R++;
				 		break;
				 	default:
				 		echo $notafinal;
				 		if ($notafinal <= 10) {
				 			$j++;
				 		}
				 		else{
				 			$apro++;
				 		}
				 		break;
				 } ?>
			</td>
		</tr>	
	<?php }?>
</table>
<hr style="height: 1px; color: #000">
<p style='font-size: 10px'>
	Aprobados: <?php echo $apro?><br/>
	Desaprobados: <?php echo $j?><br/>
	Retirados: <?php echo $R?><br/>
	Total Matriculados: <?php echo count($students);?>
</p>

<?php 

    date_default_timezone_set("America/Lima");
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,33,18,5,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
	$mpdf->Output('Constancia-'.$this->person['pid'].'.pdf','D');
    // $mpdf->Output();
 
?>