<?php
// $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
// include_once($dir);
// ob_start(); 
$header='
  

'    
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">

<?php 

  // $html = ob_get_contents();
  
  // $mpdf=new mPDF('win-1252','A4','','',15,15,40);
  // $mpdf->SetHTMLHeader($header);
  // // $mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
  
  // $mpdf->SetFooter($this->footer);
  // ob_end_clean();
  // $mpdf -> WriteHTML($html);
  // $mpdf->Output('RecordNotas-'.$this->person['pid'].'.pdf','D');
  
?>