<?php
$perid=$this->perid;
$courses = $this->info_couser;
$conntent = '';
if ($courses) {
	$i=0;
	foreach ($courses as $course) {
		$i++;
		$courseid=$course['courseid'];
		$course_n=$course['course'];
		$turno=$course['turno'];
		$semid=$course['semid'];
		$name_teacher=$course['name_teacher'];
		$numregister = $course['numregister'];
		$conntent = $conntent .
		'<tr >
			<td height="25px">'.$i.'</td>
			<td>'.$courseid.'</td>
			<td>'.$course_n.'</td>
			<td>'.$turno.'</td>
			<td>'.$semid.'</td>
			<td>'.$name_teacher.'<t/d>
			<td></td>
			<td></td>
			<td></td>
			<td>'.$numregister.'</td>
		</tr>';
	}
}

$html = '
	<div style="text-align: center; font-size:14px;margin-top:10px"><b> CONTROL DE DOCUMENTOS OFICIALES '.$perid.'</b></div><br/>
	<table style="font-size:14px; font-family: Courier , monospace; width:100%;" border="1">
	<tr height="30px">
        <th width="30px" ><center>Nº</center></th>
		<th width="50px"><center>Codigo</center></th>
        <th width="350px"><center>Nombre Curso</center></th>
        <th width="30px"><center>Turno</center></th>
        <th width="30px"><center>Sem.</center></th>         
        <th width="350px"><center>Docente</center></th>
        <th width="70px"><center>Actas</center></th>
        <th width="70px"><center>Registro</center></th>
        <th width="50px"><center>R. N.</center></th>
        <th width="30px"><center># Mat.</center></th>	
	</tr>
	'.$conntent.'
	</table>
	<table style="width: 100%; margin-top:100px;" >
    <tr >
        <td height="90px">&nbsp;</td>
        <td></td> 
      </tr>
      <tr>
    	<td><center>_____________________________</center></td>
    	<td><center>_____________________________</center></td>
      
      </tr>
    <tr>
    	<td><center>Entregue Conforme</center></td>
    	<td><center>Recibi Conforme</center></td>
      
      </tr>
  	</table>
';
 ?>



<?php
//==============================================================
//==============================================================
//==============================================================

	$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
	include_once($dir);
	ob_start(); 

	$mpdf=new mPDF();
	$mpdf=new mPDF('win-1252','A4',0,0,0,0,34,10,0,0); 
	// $mpdf=new mPDF('utf-8','A4',0,0,0,0,40,'',''); 
	$mpdf->SetWatermarkImage('/img/undac.png',0.02,'F');
    $mpdf->showWatermarkImage = true;
	$mpdf->SetHTMLHeader($this->header);
	$mpdf->SetHTMLFooter($this->footer);
	$mpdf->WriteHTML($html);
	$mpdf->Output('Control de Actas'.'.pdf','D');
	// $mpdf->Output();
	exit();
//==============================================================
//==============================================================
//==============================================================


?>