<?php

$speciality = $this->info_speciality;
$name_esc = null;
$name_speciality = null;
if ($speciality['parent']!= '') {
	$name_esc = $speciality['speciality'];
	$name_speciality='ESPECIALIDAD'.$speciality['name'];
}
else{
	$name_esc=$speciality['name'];
}

$perid=$this->perid;
$courses = $this->info_couser;

$header = '
	<table width="100%" style="border: 1px solid #000; font-family: serif;">
	<tr style="text-align:center; padding-left: 100px; ">
    	<td  rowspan="2" width="340px" style="border: 1px solid #000 "><img src="/img/header_imprimir.jpg">
    	</td>
    	<td style="text-align:center; font-size:10px; border: 1px solid #000 ">
    		FACULTAD '.strtoupper($speciality['name_faculty']).'<br/>
    		ESCUELA '.strtoupper($name_esc).'<br/>
    		'.strtoupper($name_speciality).'<br/>
    		
    	</td>
	</tr>
	<tr>
		<td style="text-align:center; font-size:10px; border: 1px solid #000 " > CONTROL DE DOCUMENTOS OFICIALES '.$perid.' </td>
	</tr>
</table>
';

$conntent = '';
if ($courses) {
	$i=0;
	foreach ($courses as $course) {
		$i++;
		$courseid=$course['courseid'];
		$course_n=$course['course'];
		$turno=$course['turno'];
		$semid=$course['semid'];
		$name_teacher=$course['name_teacher'];
		$numregister = $course['numregister'];
		$conntent = $conntent .
		'<tr >
			<td height="25px">'.$i.'</td>
			<td>'.$courseid.'</td>
			<td>'.$course_n.'</td>
			<td>'.$turno.'</td>
			<td>'.$semid.'</td>
			<td>'.$name_teacher.'<t/d>
			<td></td>
			<td></td>
			<td></td>
			<td>'.$numregister.'</td>
		</tr>';
	}
}

$html = '
	<table style="font-size:14px; font-family: Courier , monospace; width:100%;" border="1">
	<tr height="30px">
        <th width="30px" ><center>Nº</center></th>
		<th width="50px"><center>Codigo</center></th>
        <th width="350px"><center>Nombre Curso</center></th>
        <th width="30px"><center>Turno</center></th>
        <th width="30px"><center>Sem.</center></th>         
        <th width="350px"><center>Docente</center></th>
        <th width="70px"><center>Actas</center></th>
        <th width="70px"><center>Registro</center></th>
        <th width="50px"><center>R. N.</center></th>
        <th width="30px"><center># Mat.</center></th>	
	</tr>
	'.$conntent.'
	</table>
	<table style="width: 100%; margin-top:100px;" >
    <tr >
        <td height="90px">&nbsp;</td>
        <td></td> 
      </tr>
      <tr>
    	<td><center>_____________________________</center></td>
    	<td><center>_____________________________</center></td>
      
      </tr>
    <tr>
    	<td><center>Entregue Conforme</center></td>
    	<td><center>Recibi Conforme</center></td>
      
      </tr>
  	</table>
';
 ?>



<?php
//==============================================================
//==============================================================
//==============================================================

$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 

$mpdf=new mPDF();
$mpdf=new mPDF('win-1252','A4',0,0,0,0,32,10,0,0); 
// $mpdf=new mPDF('utf-8','A4',0,0,0,0,40,'',''); 
$mpdf->SetHTMLHeader($this->header);
$mpdf->SetHTMLFooter($this->footer);
$mpdf->WriteHTML($html);
// $mpdf->Output('Control'.'.pdf','D');
$mpdf->Output();

exit();
//==============================================================
//==============================================================
//==============================================================


?>