<?php
	$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
	include ($dir);
	ob_start();
	$students = $this->students;
	$subsidiary= $this->subid;
	$periods = $this->perid;

	$tota_students = $this->tota_students;
	$total_approved = $this->total_approved;
	$total_disapp = $this->total_disapp;
	$total_retired = $this->total_retired;
	$total_NSP = $this->total_NSP;

   
?>
<style type="text/css">
.normal-td
{
	padding-left: 57px;

}
table {
	font-family: "Arial";
	font-size:11px; 
	text-align: center;
	margin-left:52%;
}
.date_record{
	font-family: "Arial";
	font-size: 11px;
	margin-left: 30%;
	margin-top: 136px;
}
.acuerdo {

	font-family: "Arial";
	font-size: 11px;
	text-align: left;
}
.magno{
	
	margin-top: 65%;
}
</style>
	<table >
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td' ></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
		<tr>
			<td ></td>
			<td class='normal-td'></td>
		</tr>
	</table>
	<p class='date_record'></p>

	<p class='acuerdo magno'>Por acuerdo del Magno Consejo Universitario y la incorporación del nuevo Sistema Académico Digital se obvia el párrafo </p>

	<p class='acuerdo'>3 de la nota adjunta a este documento, según Resolución de Consejo Universitario Nº 1462-2009-UNDAC-C.U.</p>

	
<?php

	$html = ob_get_contents();
	$mpdf=new mPDF('utf-8','A4','','',15,15,55,15,15);
	$mpdf->SetHTMLHeader($header);
	ob_end_clean();
	$mpdf -> WriteHTML($html);
	$mpdf->Output('Acta-'.$course['courseid'].'turno'.$course['turno'].'.pdf','D'); 
?>

