<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$speciality = $this->info_speciality;
if ($speciality['parent']!= '') {
	$name_esc = $speciality['speciality'];
	$name_speciality='ESPECIALIDAD'.$speciality['name'];
}
else{
	$name_esc=$speciality['name'];
}
$perid=$this->perid;
$courses = $this->info_couser;

$mpdf->mirrorMargins = 1;	// Use different Odd/Even headers and footers and mirror margins

$header = '
<table width="100%" style="border: 1px solid #000;font-family: serif;  color: #000; ">
	<tr style="text-align:center; padding-left: 100px; ">
    	<td  rowspan="2" width="340px" style="border: 1px solid #000 "><img src="/img/header_imprimir.jpg">
    	</td>
    	<td style="text-align:center; font-size:10px; border: 1px solid #000 ">
    		FACULTAD '.strtoupper($speciality['name_faculty']).'<br/>
    		ESCUELA '.strtoupper($name_esc).'<br/>
    		'.strtoupper($name_speciality).'<br/>
    		
    	</td>
	</tr>
	<tr>
		<td style="text-align:center; font-size:10px; border: 1px solid #000 " >ACTA EVALUACIÓN - PERIODO '.$perid.' </td>
	</tr>
</table>
';

?>
<style type="text/css">
.normal-td
{
}
</style>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<table style='font-size:14px; font-family: Courier, monospace ; width:100%; text-align:none; ' border='1'>
	<tr height="30px">
        <th width="30px" ><center>Nº</center></th>
		<th width="50px"><center>Codigo</center></th>
        <th width="350px"><center>Nombre Curso</center></th>
        <th width="30px"><center>Turno</center></th>
        <th width="30px"><center>Sem.</center></th>         
        <th width="350px"><center>Docente</center></th>
        <th  width="70px"><center>Actas</center></th>
        <th width="70px"><center>Registro</center></th>
        <th  width="50px"><center>R. N.</center></th>
        <th width="30px"><center># Mat.</center></th>	
	</tr>
	<?php 
		foreach ($courses as $key => $course) {?>
		<tr >
			<td height="25px"><?php echo $key+1?></td>
			<td><?php echo $course['courseid']?></td>
			<td><?php echo $course['course']?></td>
			<td><?php echo $course['turno'] ?></td>
			<td><?php echo $course['semid'] ?></td>
			<td><?php echo $course['name_teacher'] ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td><?php echo $course['numregister']?></td>
		</tr>	
	<?php }?>
</table>

<?php 

$html = ob_get_contents();
  
$mpdf=new mPDF('win-1252','A4','','','','',23,'','');
  
$mpdf->SetHTMLHeader($header);
ob_end_clean();
$mpdf -> WriteHTML($html);
$mpdf->Output('Control-Acta'.'.pdf','D');
  
?>