<?php 
if ($this->escid) { ?>
	<option selected value="TODOEP">Todas las especialidades.</option>
<?php
}else{
	if ($this->especialidad) { ?>
		<option value="">- Seleccione  -</option>
		<?php
		foreach ($this->especialidad as $especialidad) { 
			$escid=base64_encode($especialidad['escid']);
			$subid_cryp=base64_encode($especialidad['subid']);
			?>
			<option value="<?php echo $subid_cryp."--".$escid?>"><?php echo $especialidad['name']?></option>
			<?php
		} 
	}else{ ?>
		<option value="">No tiene ningun registro.</option>
	<?php
	}
} ?>