<table class="table">
	<tr>
    	<td class="span2">
       		<img src="/img/circulo-verde.png"><b>ACTIVO</b>
       	</td>
      	<td class="span3">
      		    <img src="/img/circulo-rojo.png" width='30' height='30'><b>CERRADO</b>
      	</td>
  	    <td class="span2">
  		    <img src="/img/circulo-amarillo.png"><b>TEMPORAL</b>
  	    </td>
  	    <td class="span2">
  		    <img src="/img/circulo-azul.png"><b>INICIADO</b>
   	    </td>
   	    <td style="text-align: right">
            <button id="newper" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Nuevo</button>
<!-- 			<a id="#"  class="btn btn-info" onclick="javascript: window.open('/rcentral/periods/nuevo/','Periodo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=0,fullscreen=yes,dependent=no,width=600,height=600')"> 
   			<i class="glyphicon glyphicon-pencil"></i>Nuevo</a> -->
   	    </td>   				
	</tr>
</table>
<table class="table  table-bordered table-condensed table-striped">
<thead>
    <tr>
      <th class="span1">#</th> 
      <th class="span2">CODIGO PERIODO</th>
      <th >NOMBRE DEL PERIODO</th>
      <th class="span2">FINICIO CLASES</th>
      <th class="span2">FFIN CLASES</th>
      <th class="span2">RESOLUCION</th>
      <th class="span1">ESTADO</th>
      <th class="span1">OPERACIONES</th>
    </tr>
</thead>
    <?php
    if ($this->lper)
    {  
      $i=1;
      foreach ($this->lper as $periodo)    
        { $estado=$periodo['state']; ?>
            <tr>               
                <td><?php echo $i;?></td>
                <td><?php echo $periodo['perid'];?></td>
                <td><?php echo $periodo['name'];?></td>
                <td><?php echo $periodo['class_start_date'];?></td>
                <td><?php echo $periodo['class_end_date'];?></td>
                <td><?php echo $periodo['document_auth'];?></td> 
                <td>
                <?php if($estado=='I'){?>
                    <img src="/img/circulo-azul.png" id="editar_<?php echo $escid.$r; ?>" rel="tooltip" title="<?php echo $titulo?>"  />
                       <td>
                       <a href="#"  onclick="javascript: window.open('/rcentral/periods/modificar/perid/<?php echo $periodo['perid'];?>','Periodo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=600,height=550')">
                                 <i class="glyphicon glyphicon-pencil"></i></a>
                <?php } ?>
                <?php if($estado=='A'){?>
                    <img src="/img/circulo-verde.png" id="editar_<?php echo $escid.$r; ?>" rel="tooltip" title="<?php echo $titulo?>"  />
                       <td>
                       <a href="#"  onclick="javascript: window.open('/rcentral/periods/modificar/perid/<?php echo $periodo['perid'];?>','Periodo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=600,height=550')">
                                 <i class="glyphicon glyphicon-pencil"></i></a>
                <?php } ?>
                <?php if($estado=='T'){?>
                    <img src="/img/circulo-amarillo.png" id="editar_<?php echo $escid.$r; ?>" rel="tooltip" title="<?php echo $titulo?>"  />
                       <td>
                       <a href="#"  onclick="javascript: window.open('/rcentral/periods/modificar/perid/<?php echo $periodo['perid'];?>','Periodo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=600,height=550')">
                                 <i class="glyphicon glyphicon-pencil"></i></a>
                <?php } ?>
                <?php if($estado=='C'){?>
                    <img src="/img/circulo-rojo.png" id="editar_<?php echo $escid.$r; ?>" rel="tooltip" title="<?php echo $titulo?>"  />
                       <td>
                       <a href="#"  onclick="javascript: window.open('/rcentral/periods/modificar/perid/<?php echo $periodo['perid'];?>','Periodo','resizable=no,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=yes,dependent=no,width=600,height=550')">
                                 <i class="glyphicon glyphicon-pencil"></i></a>
                <?php } ?>
               </td>
            </tr>
           <?php
             $i++;
        }
    }
    ?>
    </table>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                
            </div>
            <div class="modal-body">
                <div id='nuevo_periodo'></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#newper").click(function(){   
        $('#myModal').modal('show');            
        var url="/rcentral/periods/nuevo/";
        $("#nuevo_periodo").html("</br></br><center><img src='/img/spinner.gif'> Cargando...</center>");
        $("#nuevo_periodo").load(url);
    });
</script>








