        <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/login/js/bjqs-1.3.min.js"></script>
        <script src="/external/login/js/scripts.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">    
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
         <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  

        
<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
	<table style="font-size:12px" width="100%" class="table-hover table-condensed table-striped">
    	        <div class="panel panel-primary" style="padding: 2px">
            <div class="panel-heading" style="padding: 6px">
            <center><b style="font-size:15px; color: white">MODIFICAR PERIODO</b></center>
            </div>
        </div>
                <tr>
         <th colspan="3" ><center><?php echo $this->form->guardar?></center></th>
         <th><br><a style="float:left" href='/distribucion/distribucion/listar' class='btn btn-danger' onclick="javascript: window.close();">
            <i class="icon-eject icon-white"></i>Cerrar</a>
        </th>
        </tr>
        <tr>
        	<th  ><center>PERIODO</center></th>
            <th  colspan="3"><center>NOMBRE PERIODO</center></th>
      	</tr>
        <tr>
        	<td ><center><?php print $this->form->perid->setAttrib('disable','disable');?></center></td>
            <td  colspan="3"><center> <?php print $this->form->name;?></center></td>
      	</tr>
        <tr>
        	<th><center>ESTADO</center></th>
            <th colspan="3"><center>RESOLUCION</center></th>
      	</tr>
        <tr>
		<?php
        $estado=$this->estado;
		if($estado=='B')
        { ?>
			<th><center><?php print $this->form->state;?></center></th>
        <?php
        } else { ?>
			<td>
				<center>
                <select  id="state" name="state" class="form-control">
                	<option value="<?php echo $estado?>">
                    <?php
                    if($estado=='A')
                    { echo "Activo";    
                    }

                    if($estado=='T')
                    { echo "Temporal";
                    ?>
					<option value="A">Activo</option>  
                    <?php } ?>
                    <option value="C">Cerrado</option>            
                    <option value="I">Inactivo</option>     

              	</select>
                </center>
         	</td>
            <?php  } ?>
           	<th colspan="3"><center><?php print $this->form->document_auth;?></center></th>
     	</tr>
		<tr>
        	<th colspan="2"><center>FECHA CLASES</center></th>
            <th colspan="2"><center>FECHA MATRICULA</center></th>
      	</tr>
        <tr>
        	<th ><center>Inicio</center></th>
            <th ><center>Fin</center></th>
            <th ><center>Inicio</center></th>
            <th ><center>Fin</center></th>
      	</tr>
        <tr>
        	<td ><center><?php print $this->form->class_start_date;?></center></td>
            <td ><center><?php print $this->form->class_end_date;?></center></td>
            <td ><center><?php print $this->form->start_registration;?></center></td>
            <td ><center><?php print $this->form->end_registration;?></center></td>
      	</tr>
        <tr>
        	<th colspan="2"><center>FECHA INGRESO NOTAS PRIMER PARCIAL</center></th>
            <th colspan="2"><center>FECHA INGRESO NOTAS SEGUNDO PARCIAL</center></th>
       	</tr>
        <tr>
        	<th ><center>Inicio</center></th>
            <th ><center>Fin</center></th>
            <th ><center>Inicio</center></th>
            <th ><center>Fin</center></th>
		</tr>
        <tr>
        	<td ><center><?php print $this->form->start_register_note_p;?></center></td>
            <td ><center><?php print $this->form->end_register_note_p;?></center></td>
            <td ><center><?php print $this->form->start_register_note_s;?></center></td>
            <td ><center><?php print $this->form->end_register_note_s;?></center></td>
		</tr>
	</table>
    
   
</form>






<script>
        $(function() {
        $( "#class_start_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
            
        });
    });      
</script>

<script>
        $(function() {
        $( "#class_end_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#start_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

  
<script>
        $(function() {
        $( "#start_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#start_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'            
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
           
        });
    });      
</script>