<form id="frmModificar" role="form">
    <div class="col-md-12 panel">
        <div class="row">
            <div class="col-md-3">
                <p><span class="glyphicon glyphicon-chevron-right span11"></span> <span class="text-muted"> Perido</span></p>
                <?php print $this->form->perid->setAttrib('disable','disable');?>
            </div>
            <div class="col-md-9">
                <p><span class="glyphicon glyphicon-chevron-right span11"></span><span class="text-muted"> Nombre</span></p>
                <?php print $this->form->name;?>
            </div>
        </div>
        <div class="row row2">
            <div class="col-md-3">
                <p><span class="glyphicon glyphicon-chevron-right span11"></span> <span class="text-muted"> Estado<span class="glyphicon glyphicon-sort-by-attributes-alt"></span></span></p>
                <?php $estado=$this->estado;?>
                <center>
            <select  id="state" name="state" class="form-control">
                <?php if($estado=='A'){?>
                    <option value="<?php echo $estado?>">Activo</option>
                    <option value="T">Temporal</option>  
                    <option value="C">Cerrado</option> 
                <?php }?>
                <?php if($estado=='I'){//I=iniciado?>
                    <option value="<?php echo $estado?>">Iniciado</option>
                    <option value="A">Activo</option>  
                    <option value="T">Temporal</option>
                    <option value="C">Cerrado</option> 
                <?php }?>
                <?php if($estado=='T'){?>
                    <option value="<?php echo $estado?>">Temporal</option>
                    <option value="A">Activo</option>  
                    <option value="C">Cerrado</option> 
                <?php }?>
                <?php if($estado=='C'){?>
                    <option value="<?php echo $estado?>">Cerrado</option>  
                    <option value="T">Temporal</option> 
                <?php }?>                            
            </select>
            </center>
            </div>
            <div class="col-md-9">
                <p><span class="glyphicon glyphicon-chevron-right span11"></span><span class="text-muted"> Resolucion</span></span></p>
                <?php print $this->form->document_auth;?>
            </div>
        </div>
    </div>
    <div class="col-md-12 panel panel2">
        <div class="col-md-6 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">Fecha de Clases</h4>
            </div>
            <div class="col-md-6">
                <label>Inicio <span class="glyphicon glyphicon-play span12"></span></label>
                <?php print $this->form->class_start_date;?>
            </div>
            <div class="col-md-6"> 
                <label>Fin <span class="glyphicon glyphicon-stop span12"></span></label>
                <?php print $this->form->class_end_date;?>
            </div>
        </div>
        <div class="col-md-6 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">Fecha de Matricula</h4>
            </div>
            <div class="col-md-6"> 
                <label>Inicio <span class="glyphicon glyphicon-play span12"></span></label>
                <?php print $this->form->start_registration;?>
            </div>
            <div class="col-md-6"> 
                <label>Fin <span class="glyphicon glyphicon-stop span12"></span></label> 
                <?php print $this->form->end_registration;?>
            </div>
        </div>
    </div>
    <div class="col-md-12 panel panel3">
        <div class="col-md-6 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">Ingreso de Notas Primer Parcial</h4>
            </div>
            <div class="col-md-6">
                <label>Inicio <span class="glyphicon glyphicon-play span12"></span></label>
                <?php print $this->form->start_register_note_p;?>
            </div>
            <div class="col-md-6"> 
                <label>Fin <span class="glyphicon glyphicon-stop span12"></span></label>
                <?php print $this->form->end_register_note_p;?>
            </div>
        </div>
        <div class="col-md-6 col21">
            <div class="text-center col-md-12">
                <h4 class="text-info">Ingreso de Notas Segundo Parcial</h4>
            </div>
            <div class="col-md-6"> 
                <label>Inicio <span class="glyphicon glyphicon-play span12"></span></label>
                <?php print $this->form->start_register_note_s;?>
            </div>
            <div class="col-md-6"> 
                <label>Fin <span class="glyphicon glyphicon-stop span12"></span></label> 
                <?php print $this->form->end_register_note_s;?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-6 col-md-3">
            <a class='btn btn-danger form-control' onclick="$('#myModal2').modal('hide');"><span class="glyphicon glyphicon-remove"></span>  Cerrar</a>
        </div>
        <div class="col-md-3">
            <a id="guardar2" class="form-control btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Guardar</a>
        </div>
    </div>
    <input type="hidden" name="periodo" id="periodo" value="" class="form-control">
</form>
<script>
    var anio=$("#lanios").val();
    var valor = $("#perid").val();
    $("#periodo").val(valor);    
    $('#guardar2').click(function(e) {
        e.preventDefault();
        var perid = valor;
        $.ajax({
            url: '/rcentral/periods/guardar/',
            type : 'post',
            data: $('#frmModificar').serialize(),
            success: function(data){
                $('#myModal2').modal('hide');
            }
        });
    });
</script>
<script>
    $(function(){
        $( "#class_start_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
            
        });
        $( "#class_end_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
        $( "#start_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
        $( "#end_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
        $( "#start_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    
        $( "#end_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
        
        $( "#start_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'            
        });
        $( "#end_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
           
        });
    });      
</script>