       <!-- <script src="/external/jquery/jquery-1.9.1.js"></script>
        <script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
        <script src="/external/jquery/external/globalize.js"></script>
        <script src="/external/jquery/external/jquery.mousewheel.js"></script>
        <script src="/external/jquery/external/jshint.js"></script>
        <script src="/external/jquery/external/qunit.js"></script>
        <script src="/external/login/js/bjqs-1.3.min.js"></script>
        <script src="/external/login/js/scripts.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
        <script src="/external/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
        -->
        <link rel="stylesheet" href="/external_library/jquery-ui/jquery.ui.datepicker.css"/>
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>


         <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  
<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">     
         <table style="font-size:12px"  class=" table table-hover table-condensed table-striped">
		

        <div class="panel panel-primary" style="padding: 2px">
            <div class="panel-heading" style="padding: 6px">
            <center><b style="font-size:15px; color: white">CREAR NUEVO PERIODO</b></center>
            </div>
        </div>

        <tr>
         <th colspan="3" ><center><?php echo $this->form->guardar?></center></th>
         <th><br><a style="float:left" href='/rcentral/periods/index' class='btn btn-danger' onclick="javascript: window.close();">
            <i class="icon-eject icon-white"></i>Cerrar</a>
        </th>
        </tr>
		<tr>
			<th colspan="4" style="color:red;"> * Todos los campos son obligatorios</th>
		</tr>

		<tr>
			<th >CODIGO PERIODO</th>
			<td ><?php print $this->form->perid;?></td>
			<th >NOMBRE DEL PERIODO:</th>
			<td><?php print $this->form->name;?></td>
		</tr>
		<tr>
			<th >RESOLUCION</th>
			<td colspan="3"><?php print $this->form->document_auth;?></td>
		</tr>
		<tr>
			<th colspan="4" style="background: #ccc">FECHAS DE INICIO Y FIN DE CLASES</th>
		</tr>
		<tr>
			<th >INICIO CLASES</th>
			<td ><?php print $this->form->class_start_date;?></td>
			<th >FINAL CLASES</th>
			<td><?php print $this->form->class_end_date;?></td>
		</tr>
		<tr>
			<th colspan="4" style="background: #ccc">FECHAS DE INICIO Y FIN DE MATRICULA</th>
		</tr>
		<tr>
			<th >INICIO MATRICULA</th>
			<td ><?php print $this->form->start_registration;?></td>
			<th >FINAL MATRICULA</th>
			<td><?php print $this->form->end_registration;?></td>
		</tr>
		<tr>
			<th colspan="4" style="background: #ccc">LLENADO DE NOTAS DEL PRIMER PARCIAL</th>
		</tr>
		
		<tr>
			<th >F. INICIO </th>
			<td ><?php print $this->form->start_register_note_p;?></td>
			<th >F. FIN 1er PARCIAL</th>
			<td><?php print $this->form->end_register_note_p;?></td>
		</tr>
		<tr>
			<th colspan="4" style="background: #ccc">LLENADO DE NOTAS SEGUNDO PARCIAL</th>
		</tr>
		<tr>
			<th >F. INICIO </th>
			<td ><?php print $this->form->start_register_note_s;?></td>
			<th >F. FIN 2do PARCIAL</th>
			<td><?php print $this->form->end_register_note_s;?></td>
		</tr>
		
	</table>
</form>




<script>
        $(function() {
        $("#class_start_date").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $("#class_end_date").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#start_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_registration" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

  
<script>
        $(function() {
        $( "#start_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_register_note_p" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    });      
</script>

<script>
        $(function() {
        $( "#start_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'            
        });
    });      
</script>

<script>
        $(function() {
        $( "#end_register_note_s" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
           
        });
    });      
</script>