<?php $auth = Zend_Auth::getInstance();
   if (!$auth->hasIdentity()) {
     exit();
   }
   $sesion = $auth->getStorage()->read();
   $rol = $sesion->rol['rid']; ?>
<?php if ($rol != 'AL' && $rol !='DC'){ ?>
      <form id="main_search_form">
         <input type="text" name='data' placeholder="Busque a estudiantes o docentes...">
         <button type="submit" name='enviar'><span class='glyphicon glyphicon-search'></span></button>
      </form>
<?php }?>

