<?php 
$sesion  = Zend_Auth::getInstance();
if(!$sesion->hasIdentity() ){
	echo "ingreso no permitido";
	Header ("Location: /");
	exit();
}
?>

<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->headTitle(); ?>
		
   		<!-- JQuery UI-->
   		<script src="/external/jquery/jquery-1.9.1.js"></script>
   		<script src="/external/jquery/additional-methods.min.js"></script>
   		<script src="/external/jquery/jquery.validate.min.js"></script>
   		<script src="/external/jquery/messages_es.js"></script>
   		
   		
   		<script src="/external/jquery/ui/minified/i18n/jquery.ui.datepicker-es.min.js"></script>
   		<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
   		
   		
   		<script src="/external/jquery/external/globalize.js"></script>
   		<script src="/external/jquery/external/jquery.mousewheel.js"></script>
   		<script src="/external/jquery/external/jshint.js"></script>
   		<script src="/external/jquery/external/qunit.js"></script>
   		<script src="/external/jquery/external/base64/jquery.base64.min.js"></script>

   		
   		<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
      	<link rel="stylesheet" type="text/css" href="/css/maquetacion.css">
   		
   		<!-- Texto Enriquecido-->
   		<link rel="stylesheet" type="text/css" href="/external/jwysiwyg/jquery.wysiwyg.css">
        <script type="text/javascript" src="/external/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.image.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.link.js"></script>
        <script type="text/javascript" src="/external/jwysiwyg/wysiwyg.table.js"></script>
   		
   		<!-- Bootstrap -->
   		<script src="/external/bootstrap/js/bootstrap.min.js"></script>
   		
   		<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.min.css">
   		<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap-theme.min.css">
   		
   		<!-- JS  -->
   		
   		
   		<!-- CSS  Generic-->
   		
   		<link rel="stylesheet" type="text/css" href="/css/style.css">
    
    </head>
 <body>
<!--[if IE]>
	<div class="mensaje">
                Estas utilizando una version obsoleta del navegador Internet Explorer el sitema no se vera
                correctamente. Actualiza o descarga un nuevo navegador como este <a href="https://www.google.com/chrome?hl=es">Google Chrome</a>.
    </div>
<?php //exit();?>
<![endif]-->
<div class="col-lg-12 header-center">
	<div class="panel panel-default">
		<?php print $this->layout()->content; ?>
	</div>
</div>
</body>
</html>
