<?php $auth = Zend_Auth::getInstance();

    if (!$auth->hasIdentity()) {
        exit();
    }
    $sesion = $auth->getStorage()->read();
    $uid = $sesion->uid;
    $uid_ = substr($uid, 0,2);
    $parent = $sesion->rol['parent'];
    $home = $sesion->rol['module'];
    $permission_recource = new Default_Model_DbTable_Premission();
    $tb_module = new Api_Model_DbTable_Module();
    $where =    array(
                    'eid'   =>  $sesion->eid,
                    'oid'   =>  $sesion->oid,
                    'rid'   =>  $sesion->rol['rid']
                   );
    if (!isset($parent)) {
        $menu = $permission_recource->_getAllMenu($where);
        if (is_array($menu)) {
            foreach ($menu as $key => $value) {
                $where['mid']=$value['mid'];
                $dat_module = $tb_module->_getOne($where);
                $menu[$key]['icon']=$dat_module['imgicon'];
                $linnk = $permission_recource->_getResources($where);
                $menu[$key]['link']=$linnk;
            }
        }
    }else{
        $where['parent'] = $parent;
        $menu = $permission_recource->_getAllMenu_parent($where);
        if (is_array($menu)) {
            foreach ($menu as $key => $value) {
                $where['mid']=$value['mid'];
                $dat_module = $tb_module->_getOne($where);
                $menu[$key]['icon']=$dat_module['imgicon'];
                $linnk = $permission_recource->_getResources_parent($where);
                $menu[$key]['link']=$linnk;
            }
        }
    }
    
?>

<footer>
    <ul>
        <li class="active"><a href="/<?php echo $home?>"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
        <?php 
        if ($menu && $uid_!='14') {
        foreach ($menu as $cF => $value) { ?>
        <li class="slideButtonLayout" slideupnumber="<?php echo $cF ?>">
            <a href="##"><span class="glyphicon glyphicon-<?php echo $value['icon']?>"></span> <?php echo $value['name']?></a>
            <div id="slideUpLayout<?php echo $cF ?>" class="desplegableLayout" hidden>
                <ul>
                    <?php foreach ($value['link'] as $value_1) {?>
                        <li><a href="/<?php echo $value_1['module']?>/<?php echo $value_1['controller']?>/<?php echo $value_1['action']?>" title=""><?php echo strtoupper($value_1['name'])?></a></li>
                    <?php }?>
                </ul>
            </div>
        </li>
        <?php }} ?>
    </ul>
</footer>

<script>
$(function(){
    var slideUpNumberLayout = '';
    $('.slideButtonLayout').hover(function(){
        slideUpNumberLayout = $(this).attr('slideupnumber');
        $('#slideUpLayout' + slideUpNumberLayout).fadeToggle(200);
    });
});
</script>

<!--<div id="footer_fondo">
  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <ul class="nav nav-pills nav-justified footerText footerBtnHover">
          <li class="active"><a href="/<?php echo $home?>"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
            <?php 
                if ($menu && $uid_!='14') {
                foreach ($menu as $key => $value) { ?>
                <li class="dropdown dropup">
                    <a href="#" class="dropdown-toggle menu-main" data-toggle="dropdown"><span class="glyphicon glyphicon-<?php echo $value['icon']?>"></span> <?php echo $value['name']?></a>
                        <ul class="dropdown-menu menu-eundac-fooder">
                            <?php foreach ($value['link'] as $key => $value_1) {?>
                                <li><a class='sub-menu' href="/<?php echo $value_1['module']?>/<?php echo $value_1['controller']?>/<?php echo $value_1['action']?>" title=""><?php echo strtoupper($value_1['name'])?></a></li>
                            <?php }?>
                        </ul>
                </li>
            <?php }} ?>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>-->
