<?php $auth = Zend_Auth::getInstance();

    if (!$auth->hasIdentity()) {
        exit();
    }

    $sesion = $auth->getStorage()->read();
    $last_name = $sesion->infouser['fullname'];
    $speciality = $sesion->speciality->name;
    $module = $sesion->rol['module'];
    $rol = $sesion->rid;
    $uid = $sesion->uid;
    $pid = $sesion->pid;
    
?>
<?php if ($sesion->encuesta->existeEncuesta == 'Yes'): ?>
    <input type="hidden" id="rellenoEncuesta" value="<?php echo $sesion->encuesta->rellenoEncuesta ?>">
<?php endif ?>
<input type="hidden" id="rol" value="<?php echo $rol ?>">
<input type="hidden" id="fullProfile" value="<?php echo $sesion->fullProfile->success ?>">
<nav id="undac-menu" class="navbar navbar-default navLayout" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="btnLogo">
        <a href="/<?php echo $module?>"><img src="/img/logo_03.png" alt=""></a>
    </div>
    <div class="welcomeDiv">
        <p>Bienvenido a UNDAC 2.0, <?php echo $last_name?></p>
        <p>Adscrito Escuela <?php echo $speciality?></p>
    </div>
    <div class="buttomsLayout">
        <ul>
            <li><a href="/<?php echo $module ?>"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
            <li><a href="/profile/<?php echo ($rol=='AL')? 'public/student':'privateadm/adm'?>"><span class="glyphicon glyphicon-user"></span> Mi Perfil </a></li>
            <li><a href="##"><span class="glyphicon glyphicon-envelope"></span> Notificaciones</a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-off "></span> <b>Cerrar Sessión</b></a></li>
            <!--<li class="ver dropdown" id='li_change'>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cambiar clave <b class="caret"></b></a>
            </li>          
            <div class="dropdown-menu" id='form-change'>
                <div class="form-group" data-toggle="tooltip" title="Ingrese clave correcta" data-placement='left'>
                    <input type="password" class="form-control" name="password_actual" id="password_actual" placeholder="Contraseña Actual">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password_change" id="password_change" placeholder="Nueva Contraseña">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password_verify" id="password_verify" placeholder="Repetir Nueva Contraseña">
                </div>
                <button 
                    type="submit" id='valida_password' class="btn btn-taipa btn-block">Cambiar</button>
            </div>-->
        </ul>
    </div>
</nav>
<script type="text/javascript" src='/external_library/md5/md5.js'></script>
<script type="text/javascript" src='/external_library/md5/change.js'></script>
<script>
    $(function(){
        var rol = $('#rol').val();
        if (rol == 'AL' || rol == 'EG') {
          var fullProfile = $('#fullProfile').val();
          var allCurrentUrl = window.location.pathname;
          var currentUrl = allCurrentUrl.substr(0, 23);
          if (fullProfile == 'no' && currentUrl != '/profile/public/student') {
            $(location).attr('href', '/profile/public/student');
          };
        };

        var rellenoEncuesta = $('#rellenoEncuesta').val();
        if (rellenoEncuesta && rellenoEncuesta == 'No') {
            $(location).attr('href', '/alumno/index/encuesta');
        };
    });
 </script>
