<?php echo $this->doctype(); ?>
<html lang="es">
	<head>
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		 <![endif]-->
		<!-- Mobile Specific Metas -->
		<?php echo $this->headTitle()?>
		<?php echo $this->headMeta()?>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
		<link href="http://fonts.googleapis.com/css?family=Cuprum:400italic,400,700italic,700" rel="stylesheet" type="text/css">
	
		<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
		<?php echo $this->headLink()?>
		<?php echo $this->headScript()?>
	</head>
	<body>
		<!-- <div id="loading_overlay" class="classLoading_Overlay">
			<div class="loading_message round_bottom">Cargando....</div>
			<div class="loading_allBlack"></div>
		</div> -->
		<?php echo $this->render('header.phtml')?>
		<nav class="navigationLayout">
		    <?php echo $this->placeholder('Textnav') ?>
		    <?php echo $this->placeholder('Btnnav') ?>
			<?php echo $this->render('_search.phtml') ?>
			
		    <?php echo $this->placeholder('BtnSVCRight') ?>
		    <?php echo $this->placeholder('BtnSVCLeft') ?>
		</nav>
		<?php echo $this->placeholder('AuxiliarMobile') ?>
		<main>
			<?php echo $this->layout()->content ?>
		</main>

		<?php echo $this->render('footer.phtml') ?>
	</body>
</html>
<script>
	/*$(function(){

		function loadingOverlay(){
			$("#loading_overlay .loading_message").delay(1000).fadeOut(function(){}); 
			$("#loading_overlay").delay(500).fadeOut();
		}
		
		window.onload = function () {
			loadingOverlay();   
		};

		$(window).scroll(function(){
            if($(this).scrollTop() >= 120){
               $('.navigationButtonsSVCLayoutRight').addClass('navigationButtonsSVCFixed');
               $('.navigationButtonsSVCLayoutLeft').addClass('navigationButtonsSVCFixed');
            }
            else{
               $('.navigationButtonsSVCLayoutRight').removeClass('navigationButtonsSVCFixed');
               $('.navigationButtonsSVCLayoutLeft').removeClass('navigationButtonsSVCFixed');
            }
        });

	});*/
</script>