<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->headTitle(); ?>
		
   		<!-- JQuery UI-->
   		<script src="/external/jquery/jquery-1.9.1.js"></script>
   		<script src="/external/jquery/ui/minified/jquery-ui.custom.min.js"></script>
   		<script src="/external/jquery/external/globalize.js"></script>
   		<script src="/external/jquery/external/jquery.mousewheel.js"></script>
   		<script src="/external/jquery/external/jshint.js"></script>
   		<script src="/external/jquery/external/qunit.js"></script>
   		<script src="/external/login/js/bjqs-1.3.min.js"></script>
    	<script src="/external/login/js/scripts.js"></script>
    
   		<link rel="stylesheet" type="text/css" href="/external/jquery/themes/redmond/jquery-ui.css">
   		
   		
   		<!-- Bootstrap -->
   		<script src="/external/bootstrap/js/bootstrap.min.js"></script>
   		<link rel="stylesheet" type="text/css" href="/external/bootstrap/css/bootstrap.css">
   		
   		<!-- JS  -->   		
   		
   		<!-- CSS  Generic-->
   		
   		<link rel="stylesheet" type="text/css" href="/css/login.css">        
   	
    </head>
 <body>
<!--[if IE]>
	<div class="mensaje">
                Estas utilizando una version obsoleta del navegador Internet Explorer el sitema no se vera
                correctamente. Actualiza o descarga un nuevo navegador como este <a href="https://www.google.com/chrome?hl=es">Google Chrome</a>.
    </div>
<![endif]-->
<?php print $this->layout()->content; ?>

</body>
</html>

