<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
   	
    </head>
 <body class="login">
<!--[if IE]>
	<div class="mensaje">
                Estas utilizando una version obsoleta del navegador Internet Explorer el sitema no se vera
                correctamente. Actualiza o descarga un nuevo navegador como este <a href="https://www.google.com/chrome?hl=es">Google Chrome</a>.
    </div>
<![endif]-->
<?php print $this->layout()->content;?>
</body>
</html>

