<?php $auth=Zend_Auth::getInstance();
    
    
    $role= $auth->getStorage()->read()->rid;
    $eid= $auth->getStorage()->read()->eid;
    $oid= $auth->getStorage()->read()->oid;
	$where = array('eid'=>$eid,'oid'=>$oid,'rid'=>$role) ;
	$permissios = new Default_Model_DbTable_Premission();
	$siderbarLeft=$permissios->_getAllMenu($where);
	$estructura = array();
    $fc = false;
    $ec = false;
    $ifc  = 0;
    $iec = 0;
	if ($siderbarLeft) {
		foreach ($siderbarLeft as $key => $value) {
			if ($fc == false || $fc != $value['mid']) {
				$ifc = count($estructura);
				$estructura[$ifc] = array(
						'text_'.$ifc=>$value['name_m'],
						'icon_'.$ifc=>$value['icon_m'],
						'mid_'.$ifc=>$value['mid']);
				$fc = $value['mid']; 
			}
			//$estructura['ul'.$key]=array(
			//	'href_'.$key =>$value['module']."/".$value['controller']."/".$value['action'],
			//	'icon_2_'.$key=>$value['icon_r'],
			//	'text_2_'.$key=>$value['name_r']);
		}
	}
	//print_r($estructura);

?>
<div id="slider">
	<ul>
		<li class="titulo">
			<span class="glyphicon glyphicon-home"></span>
			<a href="/">INICIO</a>
		</li>
		<?php foreach ($estructura as $clave => $_li) { ?>
			<li>
				<a href="" class="titulo">
					<span class="glyphicon glyphicon-<?php echo $_li['icon_'.$clave]?>"></span>
					<?php echo $_li['text_'.$clave]?>
				</a>
				<?php foreach ($siderbarLeft as $clave1 => $value) {?>
					<ul class="cuerpo">
						<li>
					<?php	if($value['mid'] == $_li['mid_'.$clave]){?>
							<a href="/<?php echo $value['module']."/".$value['controller']."/".$value['action']?>">
								<span class="glyphicon glyphicon-<?php echo $value['icon_r']?>"></span>
								<?php echo $value['name_r'];?>
							</a>
					<?php }?>
						</li>
					</ul>
				<?php }?>
			</li>	
		<?php }?>


		
	</ul>
</div>