<?php
    $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
    include_once($dir);
    ob_start(); 
$perid=$this->perid;
$header='
<table style="width: 100%;" border="1">
    <tr>
        <th rowspan="2" style="width: 340px; "><img src="/img/header_imprimir.jpg"></th>
        <th style="text-align: center; font-size: 11px;">
        FACULTAD DE '.strtoupper($this->faculty).'<br/>
        ESCUELA DE  '.strtoupper($this->speciality).'<br/> 
        </th>        
    </tr>
    <tr>
        <th style="border: 1px solid #000;"> PRE-MATRICULA '.$perid.'</th>
    </tr>
</table>
<table style="width: 100%;margin-top:10px;" border="0">
    <tr>
        <th style="text-align: left;">Código:</th>
        <th style="text-align: left;">'.strtoupper($this->uid).'</th>
        <th style="text-align: left;">Alumno:</th>
        <th style="text-align: left;">'.strtoupper($this->fullname).'</th>
        <th style="text-align: left;">Semestre :</th>
        <th style="text-align: left;">'.strtoupper($this->regmatr['semid']).'</th>
    </tr>   
</table>
';    
?>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">

<table style="width:100%; text-align:center; margin-top: 10px;">
        <tr>
            <th class='small'>Código Curso</th>
            <th >Nombre Curso</th>
            <th class='small'>Condición</th>
            <th class='small'>Creditos</th>
            <th class='small'>Semestre</th>
            <th class='small'>Turno</th>
            <th class=''>Docente</th>
        </tr>
        <?php foreach ($this->data_subjects as $key => $value) { ?>
            <tr>
                <td><?php echo $value['courseid']?></td>
                <td><?php echo $value['name']?></td>
                <td><?php if ($value['type']=='O') echo "Obligatorio";
                            elseif ($value['type']=='E') echo "Electivo";?></td>
                <td><?php echo $value['credits']?></td>
                <td><?php echo $value['semid']?></td>
                <td><?php echo $value['turno']?></td>
                <td><?php echo $value['name_t']?></td>
            </tr>
        <?php }?>
        <tr >
            <td style='border: 0px; solid #fff;'></td>
            <td style='border: 0px; solid #fff'></td>
            <td border='0'>Total</td>
            <td border='0'><strong><?php echo $this->regmatr['credits']?></strong></td>
        </tr>
</table>

<?php 
    $html = ob_get_contents();
    $mpdf=new mPDF('win-1252','A4','','',15,15,40);
    $mpdf->SetHTMLHeader($header);
    $mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Pre-Matricula-'.$this->uid.'.pdf','D');
   
?>