<style type="text/css">
	.glyphicon{
		cursor: pointer;
	}
</style>

<?php if ($this->state == "B") { ?> 
	<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span> Pre Matrícula Periodo '.$this->perid.'');
	$this->placeholder('Btnnav')->append('<a href="/alumno" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');
	$this->placeholder('BtnSVCRight')->append('<buttom  class="btn btn-default" id="save_register"
	   	total="'.$this->total_credits.'" 
	   	regid="'.$this->regid.'"
		escid="'.$this->escid.'"
		subid="'.$this->subid.'"
		perid="'.$this->perid.'"
		onclick="save_registration(this)"
	><span class="glyphicon glyphicon-ok text-primary"></span> Guardar Pre Matricula</buttom> 
	<a href="/register/student" class="btn btn-default">
	<span class="glyphicon glyphicon-repeat text-success"></span> Actualizar Pago
	</a>
	');?>
<?php }?>
<?php if ($this->state == "I") { 
		$url = "/register/student/printregister/".
			"escid/".base64_encode($this->escid).
			"/subid/".base64_encode($this->subid).
			"/regid/".base64_encode($this->regid).
			"/perid/".base64_encode($this->perid).
			"/curid/".base64_encode($this->curid);						;
		?>
		<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span>Matrícula Iniciada Periodo '.$this->perid.'');
		$this->placeholder('Btnnav')->append('<a href="/alumno" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>');
		$this->placeholder('BtnSVCRight')->append('
			<a href="'.$url.'" class="btn btn-default"><span class="glyphicon glyphicon-print text-primary"></span> Imprimir</a>
			<buttom  class="btn btn-default"
			regid="'.$this->regid.'"
			escid="'.$this->escid.'"
			subid="'.$this->subid.'"
			perid="'.$this->perid.'"
			deleted="'.$this->deleted.'"
			onclick="delete_pre_register(this)"
			><span class="glyphicon glyphicon-remove text-danger"></span> Eliminar Pre Matricula</buttom>
		');?>
		
<?php }?>
<?php if ($this->state == "M") { 
		$this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-edit"></span>Matrícula Validada Periodo '.$this->perid.'');}?>

<div class='row'>
	<div class='col-md-12'>
		<div class='row'>
			<div class="table-responsive col-md-7 ">
				<table class='table text-center alert-'>
					<tr>
						<th>Número de Créditos Permitidos</th>
						<td><span class='label label-default' id='assign_credist' style="font-size: 16px; valing: middle;">
						<?php echo $this->assign_credist?></span></td>
						<th>Semestre de Matrícula</h5></th>
						<td><span class='label label-default' id='assign_semester' style="font-size: 16px; valing: middle;">
						<?php echo $this->assign_semester?></span></td>
					</tr>
					<tr>
						<th>Usted pagó el monto de</th>
						<td>S/. <?php echo $this->amount_payment?></td>
						<th>Usted debe de pagar el monto de </th>
						<td>S/. <?php echo $this->amount_assing?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

<div class ='row'>
	<?php 
	if ($this->register_paymnets) { ?>

	<div class="col-md-9">
		<div class='col-md-offset-9'>
			<h4>Total Créditos
				<span id='total_credits' class='label label-primary' value="<?php echo $this->total_credits?>"> <?php echo $this->total_credits?></span>
			</h4>
		</div>
		<hr>
	<?php if ($this->amount_payment >= $this->amount_assing ) {	?>
			
			<?php 
				if($this->subjects){?>
			<table class=' table table-hover '>
				<thead>
					<tr>
						<th class="small">Código Asig.</th>
						<th class="small-100">Nombre Asignatura</th>
						<th class="small-50 center">Tipo</th>
						<th class="small center"># Cred.</th>
						<th class="small center">Semes.</th>
						<th class="small center"># Matri.</th>
						<th class="small center">Turno</th>
						<th class="small-200" colspan="2">Docente</th>
					</tr>
				</thead>
			<?php	foreach ($this->subjects as $key => $subject) { ?>

				<?php 
					$content_veces = null;
					$content = null;
					$style_reg = null;
					$disabled_reg = null;
					$btnsuccess = null;

					if($subject['veces'] >= 2){
						$class='danger';
						$addClass = 'btn-danger';
					}
					else{
						 $class='';
						 $addClass='';	
					}

					if (isset($subject['veces_cur'])) {
						if($subject['veces_cur']==1 ){

						$veces_cur='veces_cur';
						$content_veces=$subject['veces']+1;
						$content="Requisito: Debe presentar una solicitud a Decanura de su Facultar  y Compromiso";
						}
						
					}else {$veces_cur='';}

				?>
				<?php if (isset($subject['register'])) {
					if($subject['register'] == 1  ){

							$display_reg="display:none";
							$btnsuccess='btn-success';
							$display_mod="";
							// $style_reg="";
							
						}
					 else{
					 	
						$display_reg="";
						$display_mod="display:none";
						// $disabled_reg = "disabled";
						// $style_reg="display:none";
					 }

					if(isset($subject['register'] ) && $subject['register'] == 1  && $this->state != "B" ){
							$style_reg="";
						}
					 elseif ($this->state !="B") {
							$style_reg="display:none";
					 }
				}else{
					$display_reg="";
					$display_mod="display:none";}
				?>

				<tbody>
					<tr class='<?php echo $class?> tr-<?php echo $subject['courseid']?> tr-<?php echo $subject['courseid'].$subject['turno']?>' id='<?php echo $veces_cur?>' 
						rel="popover" data-placement='bottom' 
						data-original-title="Matricula por <?php echo $content_veces ?> Vez" 
						data-content="<?php echo $content?>" data-trigger='hover'

						style="<?php echo $style_reg?>"
						>
						<td class="center"><?php echo $subject['courseid']?></td>
						<td><?php echo $subject['name']?></td>
						<td class="center"><?php 
								if (trim($subject['type'])=='O') 
										echo "Obligatorio";
								if (trim($subject['type'])=='E')
										echo "Electivo";	
						?></td>
						<td class="center"><?php echo $subject['credits']?></td>
						<td class="center"><?php echo $subject['semid'] ?></td>
						<td class="center"><?php echo $subject['veces'] ?></td>
						<td class="center"><?php echo $subject['turno'] ?></td>
						<td><?php echo $subject['docente'] ?></td>
						<td>
							
							<?php if ($this->veces < 2 || $this->condition_register == 1 ) { 
								if ($this->state == "B"){?>
								
							<button class='btn-register register-<?php echo $subject['courseid']?>-<?php echo $subject['turno']?> btn <?php echo $addClass?>'
									
									courseid='<?php echo $subject['courseid']?>'
									curid='<?php echo $subject['curid']?>'
									turno='<?php echo $subject['turno']?>'
									credits='<?php echo $subject['credits']?>'
									regid='<?php echo $this->regid?>'
									escid='<?php echo $this->escid?>'
									subid='<?php echo $this->subid?>'
									perid='<?php echo $this->perid?>'
									veces='<?php print_r ($this->veces)?>'
									condition='<?php echo $this->condition_credits?>'
									style='<?php echo $display_reg?>'
									<?php echo $disabled_reg;?>
								 	onclick='register_subject(this)'>
									<span 	class='glyphicon glyphicon-unchecked'></span>
							</button>

							<button class='modified-<?php echo $subject['courseid']?>-<?php echo $subject['turno']?> btn <?php echo $btnsuccess?>' 
									courseid='<?php echo $subject['courseid']?>'
									curid='<?php echo $subject['curid']?>'
									turno='<?php echo $subject['turno']?>'
									regid='<?php echo $this->regid?>'
									escid='<?php echo $this->escid?>'
									subid='<?php echo $this->subid?>'
									veces='<?php print_r($this->veces)?>'
									perid='<?php echo $this->perid?>'
									condition='<?php echo $this->condition_credits?>'
									onclick='modified_subjet(this)' 
									style='<?php echo $display_mod ?>'>
								<span class='glyphicon glyphicon-check'></span>
							</button>
							<?php }}?>
						</td>
					</tr>
				</tbody>
		
			<?php }?></table><?php }else{?>
				<h4 class='text-muted text-center'><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> Cursos no registrados <span class="text-danger">por parte del director...</span></h4>
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<small class="text-muted">Al parecer la distribución de su escuela no a sido <strong class="text-danger">cargada al sistema</strong>, o caso contrario a sido <strong class="text-danger">observada</strong>; espere tranquilo o acerquece a su dirección a exigir que se regularice el trámite...</small>
					</div>	
				</div>
			<?php }?>
	<?php } else {?>
			<h4 class='text-muted text-center'><span class="glyphicon glyphicon-exclamation-sign text-danger"></span> :( Pago no registrado</h4>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
				<small class="text-center text-muted">Si usted pago el dia de hoy, recuerde que tiene que esperar un tiempo aproximado de <strong class="text-danger">12 horas</strong> para que la operación se cargue al sistema; caso contrario puede <a href="/register/student" class="text-danger">Actualizar</a> su págo. Si persiste el problema envie un correo a <strong class="text-danger">informatica@undac.edu.pe</strong> o acerquece a la <strong>Oficina de Informatica...</strong></small>
				</div>	
			</div>
	<?php } ?>
	</div>
	<?php } else { ?>
		<div class='row'>
			<div class='alert alert-block alert-danger fade in col-md-5 col-md-offset-1' >
				<button type="button" class="close" data-dismiss="alert-danger" aria-hidden="true">×</button>
				<h4>Error de Pago</h4>
				<p> <?php echo $this->message_paymnet?></p>
			</div>	
		</div>
	<?php } 
	if($this->error_cur){ ?>
		<div class='row'>
			<div class='alert alert-block alert-danger fade in col-md-5 col-md-offset-1' >
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
				<h4><?php echo $this->error_cur?></h4>
				<p>Envie un correo a informatica@undac.edu.pe o acercase a la oficina de informatica </p>
			</div>
		</div>
	<?php }?>
		<div class='col-md-3'>
			<h5 class='text-danger '><strong>CONDICIONES APROBADAS</strong></h5>
			<div class='alert alert-info'>
				<p class='text-primary'>
				Segun Resolución de Consejo Universitario <b>Nº 0304-2012-UNDAC-CU</b> Usted tiene la opción para llevar <b>un </b> crédito adicional, asi como la opcion de matricularse a 3 semestres.
				</p>
			</div>
		<?php if($this->cont_conmment){ 
				if($this->cont_conmment['num_registration'] != ""){ ?> 
					<h5 class='text-danger '><strong>MATRICULA CONDICIONAL</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['num_registration']?>
						</p>
					</div>
				<?php } if(isset($this->cont_conmment['credits'])){ ?>
					<h5 class='text-danger '><strong>CREDITOS</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['credits']?>
						</p>
					</div>
				<?php }  if(isset($this->cont_conmment['semester'])){ ?>
					<h5 class='text-danger '><strong>Semestres</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['semester']?>
						</p>
					</div>
				<?php }  ?>
		<?php  } ?>
		</div>
</div>


<div class="modal fade" id='modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <h4 id="error_"></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
		function register_subject($this){
			var $register={};
			$register[$.base64.encode('curid')] = $.base64.encode($.trim($($this).attr('curid'))); 
			$register[$.base64.encode('courseid')] = $.base64.encode($.trim($($this).attr('courseid'))); 
			$register[$.base64.encode('turno')] = $.base64.encode($.trim($($this).attr('turno')));
			$register[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$register[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$register[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$register[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$register[$.base64.encode('veces')] = $.base64.encode($.trim($($this).attr('veces')));
			$register[$.base64.encode('credits')] = $.base64.encode($.trim($($this).attr('credits')));
			$register[$.base64.encode('condition')] = $.base64.encode($.trim($($this).attr('condition')));
			var result='';
			for(var pro in $register){
				result += '' + pro + '/' + $register[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/createdregister/'+ result;
	        $.ajax({
	            url:$url,
	            success:function($data){
	            
	            		var courseid=$($this).attr('courseid');
	            		var turno=$($this).attr('turno');
	                    if($data.status == true){

	                    	$(".tr-"+courseid).hide();
	                    	$(".tr-"+courseid+turno).show();
	                    	$('#assign_credist').html($data.credits_assing);
	                    	$('#assign_semester').html($data.semester);
	                    	$('#total_credits').attr("value",$data.total_credits);
	                    	$('#total_credits').html($data.total_credits);
	                    	$("#pre_register").attr('total',$data.total_credits);
	                    	$(".register"+'-'+courseid+'-'+turno).hide();
	                    	$(".modified"+'-'+courseid+'-'+turno).show();
	                    	$(".modified"+'-'+courseid+'-'+turno).addClass('btn-success');
	                    	$("#modal").modal('hide');

	                    }else{
	                        //Pintar Fracaso
	                    		$("#modal").modal('show');
	                    		$("#error_").html("A exedido en Numero de Creditos Permitidos");

	                    		$(".btn-register").prop('disabled',true);
	                    		$(".register"+'-'+courseid+'-'+turno).prop('disabled',true);

	                    }
	                    $('#modalloader').modal('hide');
	            },
	            error:function($data){
	                    //Pintar el error
                    $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	                    
	            }
        	});	
			// return false;
		}

		function modified_subjet($this){

			var $register={};
			
			$register[$.base64.encode('curid')] = $.base64.encode($.trim($($this).attr('curid'))); 
			$register[$.base64.encode('courseid')] = $.base64.encode($.trim($($this).attr('courseid'))); 
			$register[$.base64.encode('turno')] = $.base64.encode($.trim($($this).attr('turno')));
			$register[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$register[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$register[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$register[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$register[$.base64.encode('veces')] = $.base64.encode($.trim($($this).attr('veces')));
			$register[$.base64.encode('credits')] = $.base64.encode($.trim($($this).attr('credits')));
			$register[$.base64.encode('condition')] = $.base64.encode($.trim($($this).attr('condition')));


			var result='';

			for(var pro in $register){
				result += '' + pro + '/' + $register[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/removeregister/'+ result;
	        
    		var courseid=$($this).attr('courseid');
    		var turno=$($this).attr('turno');
	        $.ajax({
	            url:$url,
	            success:function($data){


				        if($data.status == true){

	                    	$(".tr-"+courseid).show();
	                    	$('#assign_credist').html($data.credits_assing);
	                    	$('#assign_semester').html($data.semester);
	                    	$('#total_credits').html($data.total_credits);
	                    	$("#pre_register").attr('total',$data.total_credits);
	                    	$(".modified"+'-'+courseid+'-'+turno).hide();
	                    	$(".register"+'-'+courseid+'-'+turno).show();
                    		$(".btn-register").prop('disabled',false);
	                    	
	                    }else{
	                    //     //Pintar Fracaso
	                    		$("#modal").modal('show');
	                    		$("#error_").html("Error Al Eliminar Curso");
	                    }
	                    $('#modalloader').modal('hide');
	            },
	            error:function($data){
	                    //Pintar el error
	                $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}

		function save_registration($this){

			var $objets={};
			$("#save_register").attr('disabled');
			// alert();
			$objets[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$objets[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$objets[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$objets[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$objets[$.base64.encode('total')] = $.base64.encode($.trim($("#total_credits").attr('value')));
			var result='';

			for(var pro in $objets){
				result += '' + pro + '/' + $objets[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/registartion/'+ result;
	        
	        $.ajax({
	            url:$url,
	            success:function($data){
                    if($data.status == true){                    	
	                    window.location.href=window.location.href;
                    }else{
                        //Pintar Fracaso
                    	$("#modal").modal('show');
                    	$("#error_").html("Selecione al menos una asignatura para realizar su Pre- Matrícula");
                        // mensajeria('error','El registro no se Guardado ');
                    }
	            },
	            error:function($data){
	                    //Pintar el error
	                //alert("Error");
                    $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}

		function delete_pre_register($this){
			var $objets={};

			// alert();
			$objets[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$objets[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$objets[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$objets[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$objets[$.base64.encode('deleted')] = $.base64.encode($.trim($($this).attr('deleted')));

			var result='';

			for(var pro in $objets){
				result += '' + pro + '/' + $objets[pro]+ '/';
			}

	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/regiterdeleted/'+ result;
	        
	        $.ajax({
	            url:$url,
	            success:function($data){
                    if($data.status == true){
	                    window.location.href=window.location.href;
                    }else{
                        //Pintar Fracaso
                    	$("#modal").modal('show');
                    	$("#error_").html("A exedido los Cantidad de Eliminar Pre Matrícula");
                    }
	                    $('#modalloader').modal('hide');
        				
	            },
	            error:function($data){
	                    //Pintar el error
	                $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}
	$(function(){
    	$("#veces_cur").popover();
	});
</script>
