<style type="text/css">
	.glyphicon{
		cursor: pointer;
	}
</style>
<script type="text/javascript">

		function register_subject($this){
			var $register={};
			
			$register[$.base64.encode('curid')] = $.base64.encode($.trim($($this).attr('curid'))); 
			$register[$.base64.encode('courseid')] = $.base64.encode($.trim($($this).attr('courseid'))); 
			$register[$.base64.encode('turno')] = $.base64.encode($.trim($($this).attr('turno')));
			$register[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$register[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$register[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$register[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$register[$.base64.encode('veces')] = $.base64.encode($.trim($($this).attr('veces')));
			$register[$.base64.encode('credits')] = $.base64.encode($.trim($($this).attr('credits')));
			$register[$.base64.encode('condition')] = $.base64.encode($.trim($($this).attr('condition')));


			var result='';

			for(var pro in $register){
				result += '' + pro + '/' + $register[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/createdregister/'+ result;
	        

	        $.ajax({
	            url:$url,
	            success:function($data){
	            		var courseid=$($this).attr('courseid');
	            		var turno=$($this).attr('turno');

	            		
	                    if($data.status == true){

	                    	$('#assign_credist').html($data.credits_assing);
	                    	$('#assign_semester').html($data.semester);
	                    	$('#total_credits').html($data.total_credits);
	                    	$("#pre_register").attr('total',$data.total_credits);
	                    	$(".register"+'-'+courseid+'-'+turno).hide();
	                    	$(".modified"+'-'+courseid+'-'+turno).show();
	                    	$(".modified"+'-'+courseid+'-'+turno).addClass('btn-success');

	                        // window.location.href=window.location.href;
	                    }else{
	                        //Pintar Fracaso
	                    		$("#modal").modal('show');
	                    		$("#error_").html("A exedido en Numero de Creditos Permitidos");

	                    		$(".btn-register").prop('disabled',true);
	                    		$(".register"+'-'+courseid+'-'+turno).prop('disabled',true);

	                    }
	                    // $('#modalloader').modal('hide');
	            },
	            error:function($data){
	                    //Pintar el error
                    $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	                    
	            }
        	});	
			// return false;
		}

		function modifiedsubjet($this){
			var $register={};
			
			$register[$.base64.encode('curid')] = $.base64.encode($.trim($($this).attr('curid'))); 
			$register[$.base64.encode('courseid')] = $.base64.encode($.trim($($this).attr('courseid'))); 
			$register[$.base64.encode('turno')] = $.base64.encode($.trim($($this).attr('turno')));
			$register[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$register[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$register[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$register[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$register[$.base64.encode('veces')] = $.base64.encode($.trim($($this).attr('veces')));
			$register[$.base64.encode('credits')] = $.base64.encode($.trim($($this).attr('credits')));
			$register[$.base64.encode('condition')] = $.base64.encode($.trim($($this).attr('condition')));


			var result='';

			for(var pro in $register){
				result += '' + pro + '/' + $register[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/removeregister/'+ result;
	        
    		var courseid=$($this).attr('courseid');
    		var turno=$($this).attr('turno');
	        $.ajax({
	            url:$url,
	            success:function($data){

				        if($data.status == true){

	                    	$('#assign_credist').html($data.credits_assing);
	                    	$('#assign_semester').html($data.semester);
	                    	$('#total_credits').html($data.total_credits);
	                    	$("#pre_register").attr('total',$data.total_credits);
	                    	$(".modified"+'-'+courseid+'-'+turno).hide();
	                    	$(".register"+'-'+courseid+'-'+turno).show();
                    		$(".btn-register").prop('disabled',false);
	                    	
	                    //     // window.location.href=window.location.href;
	                    }else{
	                    //     //Pintar Fracaso
	                    		$("#modal").modal('show');
	                    		$("#error_").html("Error Al Eliminar Curso");
	                    }
	                    // $('#modalloader').modal('hide');
	            },
	            error:function($data){
	                    //Pintar el error
	                $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}

		function registration($this){
			var $objets={};

			// alert();
			$objets[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$objets[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$objets[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$objets[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$objets[$.base64.encode('total')] = $.base64.encode($.trim($($this).attr('total')));

			var result='';

			for(var pro in $objets){
				result += '' + pro + '/' + $objets[pro]+ '/';
			}
	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/registartion/'+ result;
	        
	        $.ajax({
	            url:$url,
	            success:function($data){
							         
                    if($data.status == true){
    					window.location.reload(true);
                    }else{
                        //Pintar Fracaso
                    	$("#modal").modal('show');
                    	$("#error_").html("Selecione al menos una asignatura para realizar su Pre- Matrícula");
                        // mensajeria('error','El registro no se Guardado ');
                    }
                    // $('#modalloader').modal('hide');
	            },
	            error:function($data){
	                    //Pintar el error
                    $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}

		function delete_pre_register($this){
			var $objets={};

			// alert();
			$objets[$.base64.encode('escid')] = $.base64.encode($.trim($($this).attr('escid')));
			$objets[$.base64.encode('subid')] = $.base64.encode($.trim($($this).attr('subid')));
			$objets[$.base64.encode('regid')] = $.base64.encode($.trim($($this).attr('regid')));
			$objets[$.base64.encode('perid')] = $.base64.encode($.trim($($this).attr('perid')));
			$objets[$.base64.encode('deleted')] = $.base64.encode($.trim($($this).attr('deleted')));

			var result='';

			for(var pro in $objets){
				result += '' + pro + '/' + $objets[pro]+ '/';
			}

	        result = result.substring(0, result.length-1);
	        var $url = '/register/student/regiterdeleted/'+ result;
	        
	        $.ajax({
	            url:$url,
	            success:function($data){
	            	// alert($data.de+" "+$data.deleted);
                    if($data.status == true){
        				window.location.reload(true);
                    }else{
                        //Pintar Fracaso
                    	$("#modal").modal('show');
                    	$("#error_").html("A exedido los Cantidad de Eliminar Pre Matrícula");
                    }
	                    // $('#modalloader').modal('hide');
        				
	            },
	            error:function($data){
	                    //Pintar el error
	                $("#modal").modal('show');
                	$("#error_").html("Error en el Servidor");
	            }
        	});
		}


	$(function(){
    	$("#veces_cur").popover();
	});
</script>

<div class="modal fade" id='modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <h4 id="error_"></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id='contet_matri'>
<div class='row'>
	<div class='col-md-12'>
		<div class='row'>
			<!-- <div class='col-md-3'>
				<h4><span class='glyphicon glyphicon-book'></span><a href="#"> Pagos Realizados</a></h4>
			</div> -->

			<div class='col-md-2'>
				<h4><span class='glyphicon glyphicon-book'></span><a href="/register/student/"> Pre Matrícula</a></h4>
			</div>
			<div class='col-md-4'>
				<h4><span class='glyphicon glyphicon-book'></span><a href="#"> Matrícula</a></h4>
			</div>
			<div class='col-md-6'>
				<?php if ($this->state == "B") { ?> 
					
					<a href="#" class='btn btn-success' id='pre_register'
					   	total="<?php echo $this->total_credits?>"
					   	regid='<?php echo $this->regid?>'
						escid='<?php echo $this->escid?>'
						subid='<?php echo $this->subid?>'
						perid='<?php echo $this->perid?>'
						onclick='registration(this)'
					><span class='glyphicon glyphicon-ok'></span> Guardar Pre Matricula</a>

					<a href="/register/student" class='btn btn-success'><span class='glyphicon glyphicon-repeat'></span> Actualizar Pago</a>
				<?php }?>
			
				<?php if ($this->state == "I") { 
					$url = "/register/Student/printregister/".
						"escid/".base64_encode($this->escid).
						"/subid/".base64_encode($this->subid).
						"/regid/".base64_encode($this->regid).
						"/perid/".base64_encode($this->perid).
						"/curid/".base64_encode($this->curid);						;
					?>
					<a href="<?php echo $url ?>" class='btn btn-primary'><span class='glyphicon glyphicon-print'></span> Imprimir</a>

					<a href="#" class='btn btn-danger'
						regid='<?php echo $this->regid?>'
						escid='<?php echo $this->escid?>'
						subid='<?php echo $this->subid?>'
						perid='<?php echo $this->perid?>'
						deleted='<?php echo $this->deleted?>'
						onclick='delete_pre_register(this)'
					><span class='glyphicon glyphicon-remove'></span> Eliminar Pre-Matricula</a>
				<?php }?>
			</div>
				
		</div>
	</div>
</div>


<div class='row'>
	<div class='col-md-12'>
		<div class='row'>
			<div class="table-responsive col-md-5 col-md-offset-1">
				<table class='table text-center'>
					<tr>
						<td><h5>Número de Créditos Permitidos</h5></td>
						<td><h4><span class='label label-default' id='assign_credist'><?php echo $this->assign_credist?></span></h4></td>
						<td><h5>Semestre de Matrícula</h5></td>
						<td><h4><span class='label label-default' id='assign_semester'><?php echo $this->assign_semester?></span></h4></td>
					</tr>
					<tr>
						<td>Usted pagó el monto de</td>
						<td><?php echo $this->amount_payment?></td>
						<td>Usted debe de pagar el monto de</td>
						<td><?php echo $this->amount_assing?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

<div class ='row'>
<?php 
	if ($this->register_paymnets) {
	if ($this->amount_payment >= $this->amount_assing ) {	?>	
		
	<div class ='col-md-12'>
	<div class='row'>
	
	<div class='col-md-8 col-md-offset-1'>
		<div class='col-md-4 col-md-offset-9'>
			<h4>Total Creditos
				<span id='total_credits' class='label label-primary'> <?php echo $this->total_credits?></span>
			</h4>
		</div>
		<table class=' table table-hover text-center'>
			<thead>
			<tr>
				<th>Código Curso</th>
				<th>Nombre Curso</th>
				<th>Condición</th>
				<th>Crédito</th>
				<th>Semestre</th>
				<th>Matriculas</th>
				<th>Turno</th>
				<th>Docente</th>
			</tr>
			</thead>
			<tbody class='table-striped'>
			<?php foreach ($this->subjects as $key => $subject) { ?>

				<?php 
					if($subject['veces'] >= 2){
						$class='danger';
						$addClass = 'btn-danger';
					}
					else{
						 $class='';
						 $addClass='';	
					}

					if($subject['veces_cur']==1 ){

						$veces_cur='veces_cur';
						$content_veces=$subject['veces']+1;
						$content="Requisito: Debe presentar una solicitud a Decanura de su Facultar  y Compromiso";
					}
					else $veces_cur='';

				?>
				<?php if($subject['register'] == 1  ){

							$display_reg="display:none";
							$btnsuccess='btn-success';
							$display_mod="";
							
						}
					 else{
					 	
						$display_reg="";
						$display_mod="display:none";
					 }

					 if($subject['register'] == 1  && $this->state != "B" ){
							$style_reg="";
						}
					 elseif ($this->state !="B") {
							$style_reg="display:none";
					 }
					 
				?>

				<tr class='<?php echo $class?>' id='<?php echo $veces_cur?>' 
					rel="popover" data-placement='bottom' 
					data-original-title="Matricula por <?php echo $content_veces ?> Vez" 
					data-content="<?php echo $content?>" data-trigger='hover'

					style="<?php echo $style_reg?>"
					>
					<td><?php echo $subject['courseid']?></td>
					<td><?php echo $subject['name']?></td>
					<td><?php 
							if (trim($subject['type_rate'])=='O') 
									echo "Obligatorio";
							if (trim($subject['type_rate'])=='E')
									echo "Electivo";	
					?></td>
					<td><?php echo $subject['credits']?></td>
					<td><?php echo $subject['semid'] ?></td>
					<td><?php echo $subject['veces'] ?></td>
					<td><?php echo $subject['turno'] ?></td>
					<td><?php echo $subject['docente'] ?></td>
					<td>
						
						<?php if ($this->veces < 2 || $this->condition_register == 1 ) { 
							if ($this->state == "B"){?>
							
						<button class='btn-register register-<?php echo $subject['courseid']?>-<?php echo $subject['turno']?> btn <?php echo $addClass?>'
								
								courseid='<?php echo $subject['courseid']?>'
								curid='<?php echo $subject['curid']?>'
								turno='<?php echo $subject['turno']?>'
								credits='<?php echo $subject['credits']?>'
								regid='<?php echo $this->regid?>'
								escid='<?php echo $this->escid?>'
								subid='<?php echo $this->subid?>'
								perid='<?php echo $this->perid?>'
								veces='<?php print_r ($this->veces)?>'
								condition='<?php echo $this->condition_credits?>'
								style='<?php echo $display_reg?>'
							 	onclick='register_subject(this)'>
								<span 	class='glyphicon glyphicon-unchecked'></span>
						</button>

						<button class='modified-<?php echo $subject['courseid']?>-<?php echo $subject['turno']?> btn <?php echo $btnsuccess?>' 
								courseid='<?php echo $subject['courseid']?>'
								curid='<?php echo $subject['curid']?>'
								turno='<?php echo $subject['turno']?>'
								regid='<?php echo $this->regid?>'
								escid='<?php echo $this->escid?>'
								subid='<?php echo $this->subid?>'
								veces='<?php print_r($this->veces)?>'
								perid='<?php echo $this->perid?>'
								condition='<?php echo $this->condition_credits?>'
								onclick='modifiedsubjet(this)' 
								style='<?php echo $display_mod ?>'>
							<span class='glyphicon glyphicon-check'></span></button>
						<?php }}?>
					</td>
				</tr>
			<?php }?>
			</tbody>
		</table>
	
<?php }} else { ?>
	<div class='row'>
		<div class='alert alert-block alert-danger fade in col-md-5 col-md-offset-1' >
			<button type="button" class="close" data-dismiss="alert-danger" aria-hidden="true">×</button>
			<h4>Error de Pago</h4>
			<p> <?php echo $this->message_paymnet?></p>
		</div>	
	</div>
<?php } if($this->error_cur){ ?>
	<div class='row'>
		<div class='alert alert-block alert-danger fade in col-md-5 col-md-offset-1' >
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			<h4><?php echo $this->error_cur?></h4>
			<p>Envie un correo a informatica@undac.edu.pe o acercase a la oficina de informatica </p>
		</div>
	</div>
<?php }?>
	</div>
	<div class='col-md-3'>
		<h5 class='text-danger '><strong>CONDICIONES APROBADAS</strong></h5>
		<div class='alert alert-info'>
			<p class='text-primary'>
				Segun Resolución de Consejo Universitario <b>Nº 0304-2012-UNDAC-CU</b> Usted tiene la opción para llevar <b>un </b> crédito adicional, asi como la opcion de matricularse a 3 semestres.
			</p>
		</div>
		<?php if($this->cont_conmment){ 
			
				if($this->cont_conmment['num_registration'] != ""){ ?> 
					<h5 class='text-danger '><strong>MATRICULA CONDICIONAL</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['num_registration']?>
						</p>
					</div>
				<?php } if($this->cont_conmment['credits'] != ""){ ?>
					<h5 class='text-danger '><strong>CREDITOS</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['credits']?>
						</p>
					</div>
				<?php }  if($this->cont_conmment['semester'] != ""){ ?>
					<h5 class='text-danger '><strong>Semestres</strong></h5>
					<div class='alert alert-info'>
						<p class='text-primary'>
							<?php echo $this->cont_conmment['semester']?>
						</p>
					</div>
				<?php }  ?>
				
		<?php  } ?>
		

	</div>
	</div>
	</div>
</div>
</div>