<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
<table class="table  table-striped">
	<tr style="font-size: 16px">
		<td colspan="6"><b>De:</b></td>
	</tr>
	<tr style="font-size: 16px">
		<td colspan="6"><b>Para:</b></td>
	</tr>

	<tr style="font-size: 16px">
		<td colspan="6"><b>Asunto:</b> <?php print $this->form->title;?></td>
	</tr>
	<tr style="font-size: 16px">
		<td colspan="6"><?php print $this->form->Asunto;?></td>
		
	</tr>



</table>
</form>