<?php 
$code_student=$this->datarec[0]['code_student'];
$num_ope=$this->datarec[0]['operation'];
$perid=$this->datarec[0]['perid'];
?>
<div class="row">
	<div class="col-md-12">
		<div class="col-md-6">
			<div class="panel panel-primary"><br>
				<div style="margin-left:5%">
					<b>Apellidos y Nombres: </b>
					<?php echo $this->nomalum[0]['last_name0']." ".$this->nomalum[0]['last_name1'].", ".$this->nomalum[0]['first_name'] ?><br>
					<b>Fecha Pago: </b><?php echo $this->datarec[0]['payment_date']?><br>
					<b>Concepto: </b><?php echo $this->datarec[0]['concept']?><br>
					<b>Operación: </b><?php echo $num_ope ?><br>
					<b>Código: </b><?php echo $code_student ?><br>
					<b>Periodo: </b><?php echo $perid ?><br>
					<b>Monto: </b><?php echo $this->datarec[0]['amount']?><br>
				</div>
			<br></div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-primary"><br>
				<div style="margin-left:5%">
					<p class="text-info text-center" style="font-size:15px"><b><u>Asignar</u></b></p>
					<b>Código Matricula:</b>
					<input id="codigo" type="text" value="<?php echo $code_student?>" class="form-control" maxlength="10" style="width:50%" />
					<b>Concepto:</b>
					<input id="concepto" type="text" value="<?php echo $this->datarec[0]['concept']?>" class="form-control" style="width:50%" />
					<input id="old_operation" type="text" value="<?php echo base64_encode($num_ope)?>" hidden>
					<input id="old_codestudent" type="text" value="<?php echo base64_encode($code_student)?>" hidden>
					<input id="old_perid" type="text" value="<?php echo base64_encode($perid)?>" hidden>					
				</div>
			<br></div>
		</div>
	</div>
</div>
<div id="carga"></div>

<script type="text/javascript">
	$(function(){
		$("#carga").empty();

		$(".reasignation").on('click',function () {
			var uid = $("#codigo").val();
			var concept = $("#concepto").val();
			var old_operation = $("#old_operation").val();
			var old_codestudent = $("#old_codestudent").val();
			var old_perid = $("#old_perid").val();

			var fini = "<?php echo $this->fini?>";
			var ffin = "<?php echo $this->ffin?>";

			if (!uid) {
				alert("Ingrese un Código de Matrícula");
			}
			else if(!concept){
				alert("Ingrese un Concepto");
			}
			else{
				var ajaxdata = {
                            "uid"   : $.base64.encode(uid),
                        "concept"   : $.base64.encode(concept),
                    "codestudent"   : old_codestudent,
                      "operation"   : old_operation,
                          "perid"   : old_perid
                };

				$.ajax({
			        type: 'POST',
			         url: '/admin/bankpayments/assigned',
			        data: ajaxdata,
			        success: function(data) {
			        	$("#carga").html("<img src='/img/spinner.gif'> Cargando....");

			        	if (data.status) {
			            	$("#carga").html("<p class='text-center text-success'><b>"+data.sms+"</b></p>");

			            	setTimeout(function(){
			            		$("#myModal").modal('hide');
							}, 2500);

			            	$('#myModal').on('hidden.bs.modal', function (e) {
								var url1="/admin/bankpayments/list/fini/"+fini+"/ffin/"+ffin+"/usuario/"+old_codestudent;
					            $("#listadatos").html("<img src='/img/spinner.gif'> Cargando....");
					            $("#listadatos").load(url1);
							});    
			        	}
			        	else{
			            	$("#carga").html("<p class='text-center text-danger'><b>"+data.sms+"</b></p>");    
			        	};                     
			        }
		        });
				/*var url="/admin/bankpayments/assigned/uid/"+$.base64.encode(uid)+"/concept/"+$.base64.encode(concept)+"/codestudent/"+old_codestudent+"/operation/"+old_operation+"/perid/"+old_perid;
				$("#carga").load(url);*/
			}
		});
	});
</script>