<?php
if ($this->nodata=="1") { ?>
	<div class="alert alert-success">
        <p> No tiene ningun registro </p>
    </div>
<?php	
}else{ ?>
<table class="table table-striped table-condensed ">
	<tr>
		<th>#</th>
		<th>Periodo</th>
		<th><center>Num. Operación</center></th>
		<th>Cod. Mat.</th>
		<th>Nombre</th>
		<th>Fecha Pago</th>
		<th>Concepto</th>
		<th>Monto</th>
		<th>Procesado</th>
		<th>Asignar</th>
	</tr>
	<?php
	if ($this->drecibo) {
		$c=1;
		foreach ($this->drecibo as $recibos) { 
			$per=new Api_Model_DbTable_Users();
			$where['oid']=$this->oid;
			$where['eid']=$this->eid;
			$where['uid']=$recibos['code_student'];
			$datper=$per->_getUserXUid($where);
			//$nombres=$datper[0]['last_name0'];
			?>
			<tr>
				<td><?php echo $c ?></td>
				<td><?php echo $recibos['perid'] ?></td>
				<td><?php echo $recibos['operation'] ?></td>
				<td><?php echo $recibos['code_student'] ?></td>
				<td><?php echo $datper[0]['last_name0']; ?> <?php echo $datper[0]['last_name1']; ?> <?php echo $datper[0]['first_name']; ?></td>
				<td><?php echo $recibos['payment_date'] ?></td>
				<td><?php echo $recibos['concept'] ?></td>
				<td><?php echo $recibos['amount'] ?></td>
				<td><?php echo $recibos['processed'] ?></td>
				
				<td>
					<?php 
					if ($recibos['processed']=="N") { ?>
						<a href="/admin/bankpayments/assign/uid/<?php echo $recibos['code_student'] ?>/perid/<?php echo $recibos['perid'] ?>/num_operacion/<?php echo $recibos['operation'] ?>"><span class="glyphicon glyphicon-pencil"></span></a>
					<?php
					}else{ ?>
						<a id="desasignar" href="/admin/bankpayments/remove/uid/<?php echo $recibos['code_student']?>/num_operacion/<?php echo $recibos['operation']?>" onclick="return confirm('Esta seguro de anular la asignación del pago.')"><i class="icon icon-remove"></i></a>
					<?php }
					?>
				</td>
			</tr>
			<?php
			$c++;
		}
	}
	?>
</table>
<?php } ?>
