<div class="panel panel-primary" style="padding: 2px">
    <div class="panel-heading" style="padding: 6px">
        <center><b style="font-size:15px; color: white">NUEVO RECIBO</b></center>
    </div>
</div>
<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
	<table class="table">
		<tr>
			<th class="col-md-2">Número de Operación:</th>
			<td>
				<div class="col-md-5"><?php echo $this->form->operation?></div>
			</td>
			<th class="col-md-2">Fecha de Pago:</th>
			<td class="col-md-2"><?php echo $this->form->payment_date?></td>
		</tr>
		<tr>
			<th>Código de Matricula:</th>
			<td>
				<div class="col-md-5"><?php echo $this->form->code_student?></div>
			</td>
			<th>Monto:</th>
			<td><?php echo $this->form->amount?></td>
		</tr>
		<tr>
			<th>Apellidos y Nombres:</th>
			<td>
				<div class="col-md-10"><?php echo $this->form->info_person?></div>
			</td>
			<th>Concepto:</th>
			<td><?php echo $this->form->concept?></td>
		</tr>
		<tr>
			<th>Periodo:</th>
			<td colspan="3">
				<div class="col-md-6"><?php echo $this->form->perid?></div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<center>
					<?php echo $this->form->save?>
				</center>
			</td>
			<td colspan="2">
				<center>
					<br><a href="/admin/bankpayments/" class="btn btn-danger">Cancelar</a>
				</center>
			</td>
		</tr>
	</table>
</form>

<script type="text/javascript">
$("#payment_date").datepicker();

function soloNumero(e){
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = "0123456789";
    especiales = [8,37,39,46];
    tecla_especial = false
    for(var i in especiales){
        if(key == especiales[i]){
            tecla_especial = true;
            break;
        } 
    }
    if(letras.indexOf(tecla)==-1 && !tecla_especial)
    return false;
};

function soloLetras(e){
       key = e.keyCode || e.which;
       tecla = String.fromCharCode(key).toLowerCase();
       letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
       especiales = [8,37,39,46];

       tecla_especial = false
       for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }

        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }
</script>