<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-plus"></span> NUEVO RECIBO');?>
<?php $this->placeholder('Btnnav')->append('<a href="/admin/bankpayments/index" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
<div class="col-md-10 col-md-offset-1">	
	<div class="panel panel-primary">
	    <div class="panel-body">
			<div class="col-md-10">
				<div class="col-md-3 text-right"><b>Número de Operación :</b></div>
				<div class="col-md-3"><?php echo $this->form->operation?></div>
				<div class="col-md-3 text-right"><b>Fecha Pago:</b></div>
				<div class="col-md-3"><?php echo $this->form->payment_date?></div>
			</div><br><br><br>
			<div class="col-md-10">
				<div class="col-md-3 text-right"><b>Código de Matricula :</b></div>
				<div class="col-md-3"><?php echo $this->form->code_student?></div>
				<div class="col-md-3 text-right"><b>Monto:</b></div>
				<div class="col-md-3"><?php echo $this->form->amount?></div>
			</div><br><br><br>
			<div class="col-md-10">
				<div class="col-md-3 text-right"><b>Apellidos y Nombres :</b></div>
				<div class="col-md-5"><?php echo $this->form->info_person?></div>
				<div class="col-md-2"><b>Concepto:</b></div>
				<div class="col-md-2"><?php echo $this->form->concept?></div>
			</div><br><br><br>
			<div class="col-md-10">
				<div class="col-md-3 text-right"><b>Año:</b></div>
				<div class="col-md-3"><?php echo $this->form->anios?></div>
				<div class="col-md-3 text-right"><b>Periodo:</b></div>
				<div class="col-md-3"><?php echo $this->form->perid?></div>
			</div><br><br><br>
			<div class="col-md-10">
				<div class="col-md-8"><center><?php echo $this->form->save?></center></div>
				<div><center><br><a href="/admin/bankpayments/" class="btn btn-danger">Cancelar</a></center></div>
			</div><br><br><br>
		</div>	
	</div>
</div>	
</form>

<script type="text/javascript">
$("#payment_date").datepicker();

$("#anios").change(function(){
	var anio=$(this).val();
	var url=("/admin/bankpayments/listperiod/anio/"+anio);
	$("#perid").load(url);

});

function soloNumero(e){
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = "0123456789";
    especiales = [8,37,39,46];
    tecla_especial = false
    for(var i in especiales){
        if(key == especiales[i]){
            tecla_especial = true;
            break;
        } 
    }
    if(letras.indexOf(tecla)==-1 && !tecla_especial)
    return false;
};

function soloLetras(e){
       key = e.keyCode || e.which;
       tecla = String.fromCharCode(key).toLowerCase();
       letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
       especiales = [8,37,39,46];

       tecla_especial = false
       for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }

        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }
</script>