<link rel="stylesheet" href="/css/egresadosPorAnio.css" />

<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Lista de Egresados por Año de Ingreso');?>
<?php $this->placeholder('Btnnav')->append(' <a href="/docente/index" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> Regresar</a>');?>

<div class="tituloDescriptivo">
	<p><span class="glyphicon glyphicon-info-sign"></span> Seleccione una año para que visualice la cantidad de egresados de acuerdo al año de ingreso</p>
	<select name="Anio" id="anio" class="form-control selectAnio">
		<option value="">Año de Ingreso</option>
		<?php for ($i=$this->currentYear-4; $i >= 1965 ; $i--) { ?> 
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php } ?>
	</select>
</div>
<hr>
<div class="menuEgresados">
	<div class="navegacion" hidden>
		<p><span class="glyphicon glyphicon-filter"></span> Filtre los Resultados de Egresados</p>
		<a href="##" id="btnInvictos" data="Invicto" class="btn btn-info btnsFilter btnInvictos">Invictos</a>
		<a href="##" id="btnBachiller" data="Bachiller" class="btn btn-info btnsFilter btnBachiller">Bachiller</a>
		<a href="##" id="btnTitulados" data="Titulado" class="btn btn-info btnsFilter btnTitulados">Titulados</a>
	</div>
	<div class="showCantidadEgresados" hidden>
		<p><span class="glyphicon glyphicon-user"></span> Cantidad de Egresados <span id="putAnio"></span></p>
		<p class="cantEgresados" id="numEgresados"> </p>
	</div>
</div>
<div class="listEgresados" id="dataEgresados" hidden>

</div>

<script>
	$(function(){
		$('#data').addClass('hidden');
		var anio = '';
		$('#anio').change(function(){
			$('.navegacion').fadeIn('slow');
			setTimeout(function(){$('.showCantidadEgresados, #dataEgresados').fadeIn('slow');}, 500);

			$('#dataEgresados').html('<br><center><img src="/img/spinner.gif" alt="Loading..." /></center><br>')
			$('#numEgresados').html('<center><img src="/img/spinner.gif" alt="Loading..." /></center>');
			
			anio = $(this).val();
			$('#putAnio').html(anio);

			$('#dataEgresados').load('/acreditacion/egresados/listegresados/anio/' + anio, function(){
				$('html body').animate({
					scrollTop : $('.tituloDescriptivo').offset().top,
				});
			});
		});
	});
</script>