<?php if ($this->egresados): ?>
	<input type="hidden" id="numEgresadosSend" value="<?php echo $this->numEgresados ?>" />
	<br>
	<table class="table table-hover table-bordered">
		<tr class="success">
			<th class="text-center">#</th>
			<th class="text-center col-md-1">DNI</th>
			<th>Apellidos y Nombres</th>
			<th class="text-center">Escuela</th>
		</tr>
		<?php 
		$c = 0;
		foreach ($this->egresados as $egresado): ?>
			<tr>
				<td class="text-center"><?php echo $c + 1 ?></td>
				<td class="text-center"><?php echo $egresado['numdoc'] ?></td>
				<td><?php echo $egresado['nombre'] ?></td>
				<td class="text-center"><?php echo $this->specialityName[$c][0]['name'] ?></td>
			</tr>
		<?php 
		$c++;
		endforeach ?>
	</table>
<?php else: ?>
	<br>
	<h4 class="text-center text-muted">No Existen Datos de <span class="text-danger">Alumnos Egresados de <?php echo $this->anio ?></span></h4>
	<br>
<?php endif ?>
<script>
	var	numEgresados = $('#numEgresadosSend').val();
	if (numEgresados) {
		$('#numEgresados').html(numEgresados);
	}else{
		$('#numEgresados').html(0);
	};
</script>