<script type="text/javascript" src="/external_library/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/external_library/ckeditor/adapters/jquery.js"></script>

<?php if($this->informedoc['state']<>'C') { ?>
<div id="alert" class="alert alert-danger text-center">
    <h3><strong>Error!</strong> Rellene todos los campos obligatorio</h3>
</div>
<div class="alert alert-danger">
    <B>IMPORTANTE! :</B> Los porcentajes desarrollados se activan siempre y cuando usted haya terminado de registrar todas las notas de las asignaturas que tiene a su cargo.
</div>
<p style="font-size: 15px;text-align: center"><b> I.INFORME ACADEMICO</b></p>

<form  id='frmInformacademic' name="<?php echo $this->form->getName(); ?>" action="/docente/informacademic/closeinfo" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="perid" value="<?php echo base64_encode($this->perid) ?>">
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th colspan="10"><p style="font-size: 15px;text-align: center"><b> 1.1. Desarrollo de las Asignaturas </b>  </p></th>
            </tr>
            <tr>
                <th><center>#</center></th>
                <th><center>Asignaturas</center></th>
                <th><center>Turno</center></th>
                <th><center>Semestre</center></th>
                <th><center>% Desarrollado</center></th>
                <th><center> Matriculados:  N° -  %</center></th>
                <th><center>Aprobados  N° -  %</center></th>
                <th><center>Desaprobados  N° -  %</center></th>
                <th><center>Retirados  N° -  %</center></th>
            </tr>
        </thead>
        <?php
        $i=1; 
        foreach ($this->datacourses as $datacourses) { ?>
            <tr>
                <td><?php echo $i ?></td>
                <td><?php echo $datacourses['name'] ?></td>
                <td><center><?php echo $datacourses['turno'] ?></center></td>
                <td><center><?php echo $datacourses['semid'] ?></center></td>
                <td>
                    <center>
                    <?php 
                    if($datacourses['state']=='C'){ ?>
                        <input class="form-control" maxlength="3" type="text" value="<?php echo $datacourses['percentage'];?>" name="percentage[<?php echo $i-1 ?>]" style="width: 60px" onkeypress="return validNumber(event)"required>
                        <?php   
                    }else{ ?>
                        <input class="form-control" maxlenght="3" type="text" value="<?php echo $datacourses['percentage'];?>" name="percentage[<?php echo $i-1 ?>]" style="width: 60px"  title="Cierre el Acta del Curso Primero" rel="tooltip" disabled required>
                        <?php
                    } ?>
                    </center>
                </td>
                <td>
                    <center>
                    <?php 
                    $wherecant = array(
                        'eid' => $datacourses['eid'], 'oid' => $datacourses['oid'],
                        'perid' => $datacourses['perid'], 'curid' => $datacourses['curid'],
                        'escid' => $datacourses['escid'], 'courseid' => $datacourses['courseid'],
                        'turno' => $datacourses['turno'], 'subid' => $datacourses['subid']);
                    $regcour = new Api_Model_DbTable_Registrationxcourse();
                    echo $cantstu = $regcour->_getCantRegistration($wherecant)." - 100%";
                    ?>
                    </center>
                </td>
                <td>
                    <center>
                    <?php 
                    $aprobados = $regcour->_get_approved($wherecant);
                    $por = '';
                    if ($cantstu > 0) {
                        $por = round(($aprobados[0]['count'] / $cantstu) * 100,2);
                    }
                    echo $aprobados[0]['count']." - ".$por."%";
                    ?>
                    </center>
                </td>
                <td>
                    <center>
                    <?php 
                    $desaprobados = $regcour->_get_disapproved_x_course($wherecant);
                    if ($cantstu > 0) {
                        $por=round(($desaprobados[0]['count'] / $cantstu) * 100,2);
                    }
                    echo $desaprobados[0]['count']." - ".$por."%";
                    ?>
                    </center>
                </td>
                <td>
                    <center>
                    <?php 
                    $retirados = $regcour->_get_retired_x_course($wherecant);
                    if ($cantstu > 0) {
                        $por=round(($retirados[0]['count'] / $cantstu) * 100,2);
                    }
                    echo $retirados[0]['count']." - ".$por."%";
                    ?>
                    </center>
                </td>
                <input type="hidden" value="<?php echo $datacourses['courseid'];?>" name="courseid[]">
                <input type="hidden" value="<?php echo $datacourses['turno'];?>" name="turno[]">
                <input type="hidden" value="<?php echo $datacourses['escid'];?>" name="escid[]">
                <input type="hidden" value="<?php echo $datacourses['subid'];?>" name="subid[]">
                <input type="hidden" value="<?php echo $datacourses['curid'];?>" name="curid[]">
            </tr>
            <?php 
            $i++;
            } ?>
        <tr>
            <!-- <td colspan="5"><center><?php echo  $this->form->enviar ?></center></td>
            <td colspan="4"><center><?php echo  $this->form->cerrar ?></center></td> -->
        </tr>
    </table>

    <div class="alert alert-info" style="margin-top: 10px;margin-bottom: 10px;">
        <B>INFORMACIÓN:</B> Usted puede registrar el contenido completo de su informe según los cuadros presentados, le recomendamos el uso de viñetas y sangria para poder distingir entre los logros, dificultades y sugerencias.
    </div>
    <br>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><p style="font-size: 14px;text-align: left"><b>1.1 Medios y Materiales Educativos utilizados por asignatura</b> - (Dificultades, Sugerencias)</p></th>
        </tr>
        <tr>
            <td><?php print $this->form->acad_medios;?></td>
        </tr>
        <tr>
            <th><p style="font-size: 14px;text-align: left"><b>1.2. Tutoria</b> - (Logros, Dificultades, Sugerencias)</p></th>
        </tr>
        <tr>
            <td><?php print $this->form->acad_tutoria;?></td>
        </tr>
        <tr>
            <th><p style="font-size: 15px;text-align: left"><b>II. INFORME ADMINISTRATIVO</b></p></th>
        </tr>
        <tr>
            <th><p style="font-size: 14px;text-align: left"><b> 2.1. Acreditacion</b>  - (Logros, Dificultades, Sugerencias) </p></th>
        </tr>
        <tr>
            <td><?php print $this->form->adm_acreditacion;?></td>
        </tr>
        <tr>
            <th><p style="font-size: 14px;text-align: left"><b> 2.2. Investigacion o Proyeccion Social</b>  - (Logros, Dificultades, Sugerencias) </p></th>
        </tr>
        <tr>
            <td><?php print $this->form->adm_investigacion;?></td>
        </tr>
        <tr>
            <th><p style="font-size: 14px;text-align: left"><b> 2.3. Asesoria de Tesis </b> - (Logros, Dificultades, Sugerencias)  </p></th>
        </tr>
        <tr>
            <td>
                <?php print $this->form->adm_asesoria;?>
            </td>
        </tr>
        <tr>
            <th ><p style="font-size: 14px;text-align: left"><b> 2.4. Labor Administrativa (Coordinaciones, comisiones y otras) </b> - (Logros, Dificultades, Sugerencias)  </p></th>
        </tr>
        <tr>
            <td><?php print $this->form->adm_labores;?></td>
        </tr>      
    </table>
</form>
<?php
}
 ?>
<script>
    $(function(){
        $('#alert').fadeOut('fast');

        $("#enviar").click(function(){
            var url="/docente/informacademic/saveinfo";    
            $.ajax({
                url: url,
                type: 'POST',
                data:$("#frmInformacademic").serialize(),
                success: function (data){
                    console.log(data);
                    // $("#hola").html(data);    
                    // $(location).href('/docente/informacademic/')
                }
            });
        });

        $("#cerrar").click(function(){    
            $.ajax({
                url: $("#frmInformacademic").attr('action'),
                type: 'POST',
                data:$("#frmInformacademic").serialize(),
                success: function (data){
                    $("#alldata").html(data);   
                }
            });
        });

        var clave="<?php echo $this->clave?>";
            if (clave=="1") {
                $('#alert').fadeIn('slow');
                 // $(location).href('/docente/informacademic/viewimpression');
            }

        var cierre="<?php echo $this->cierre?>";
        if (cierre=="1") {
            $(location).attr("href", "/docente/informacademic/viewimpression")
             // $(location).href('/docente/informacademic/viewimpression');
        }

        (function($) {
          // $(document).ready(function() {
            $('textarea#acad_medios, textarea#acad_tutoria, textarea#adm_acreditacion, textarea#adm_investigacion, textarea#adm_asesoria, textarea#adm_labores').ckeditor();
          // });
        })(jQuery);

        $('input[rel=tooltip]').tooltip();

        function validNumber(e) {
                var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
                return ((tecla > 47 && tecla < 58) || tecla == 8);
            } 
    });
</script>