<table class="table table-condensed">
    <tr>
        <th style="font-size: 15px;text-align: center">FACULTAD DE <?php echo strtoupper($this->faculty)?></th>
    </tr>
    <tr>
        <th style="font-size: 15px;text-align: center">Escuela de Formación Profesional de <?php echo $this->speciality?></th>
    </tr>
    <tr>
        <th style="font-size: 15px;text-align: center">Informe Académico Administrativo - Periodo <?php echo $this->perid?></th>
    </tr>
    <tr>
      	<th style="font-size: 15px;text-align: center">Docente: <?php echo $this->infouser?></th>
	</tr>
</table>