<?php 
	$hora = array();
    $j=1;
    $hour_begin=array();
    $hour_begin=$this->valhoras;
    for ($i=0; $i <= 20; $i++) { 
        $hour[$i]=substr($hour_begin[$i],0,2);
        $minute[$i]=substr($hour_begin[$i],3,2);
    }
    for ($i=0; $i <= 20; $i++) {
        if ($hour[$i]<12) {
            if ($hour[$j]<12) {
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." am";
            }
            else{
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." pm";
            }
        } 
        else{
            $hora[$i]['hora']=$hour[$i].":".$minute[$i]." pm - ".$hour[$j].":".$minute[$j]." pm";
        }
        $hora[$i]['h_ini']=$hour[$i];
        $hora[$i]['h_fin']=$hour[$j];
        $hora[$i]['m_ini']=$minute[$i];
        $hora[$i]['m_fin']=$minute[$j];
        $j++;
    }

    $listacolores = array();
    $listacolores[0] = "#FA8D74";
    $listacolores[1] = "#A3CFE0";
    $listacolores[2] = "#CBE487";
    $listacolores[3] = "#FAF48D";
    $listacolores[4] = "#FCB16B";
    $listacolores[5] = "#CCF0EE";
    $listacolores[6] = "#DFDFDF";
    $listacolores[7] = "#81FF86";
    $listacolores[8] = "#CD88FD";
    $listacolores[9] = "#F59FFC";
    $listacolores[10] = "#A58CFF";
    $listacolores[11] = "#F2BBBB";
    $listacolores[12] = "#D8BADA";
    $listacolores[13] = "#C4E6CE";
    $listacolores[14] = "#B4DAA1"; 

if ($this->horarys) {
    	$len=count($this->horarys);
    	$cco=0;
    	$hmen=13;
    	$hmay=13;
    	for ($i=0; $i < $len;$i++){
    		$rid=substr($this->horarys[$i]['teach_uid'],8,2);
    		if ($rid=='JP') $this->horarys[$i]['practica']='(P)';
    		else $this->horarys[$i]['practica']="";
    		$codcurso=$this->horarys[$i]['courseid'];
    		$codcursodes=$this->horarys[$i+1]['courseid'];
    		$turno=$this->horarys[$i]['turno'];
    		$curid=$this->horarys[$i]['curid'];

    		if($codcurso==$codcursodes){
    			$this->horarys[$i]['color']=$listacolores[$cco];
    		}
    		else{
    			$this->horarys[$i]['color']=$listacolores[$cco];
    			$cco++;
    		}
    		$hsplit=split(":",$this->horarys[$i]['hora_ini']);
    		$hi=$hsplit[0];
    		$hsplit=split(":", $this->horarys[$i]['hora_fin']);
    		$hf=$hsplit[0];
    		if($hi<=$hmen) $hmen=$hi;
    		if($hf>=$hmay) $hmay=$hf;
    		
    	}
    	$k=0;
    	for ($z=0;$z < 20; $z++){
    			// print_r($hmen);exit();
    		if ($hmen==$hora[$z]['h_ini'] && $k==0) {
    			$inih=$z;
    			$k=1;
    		}
    		if($hmay==$hora[$z]['h_fin']){
    			$finh=$z;
    		}
    	}
    	// $horaoriginal=$this->horarys;
?>
<div class="row col-md-12" style="margin:0px">
	<div class='nomdoc col-md-10' style='font-size:20px'>
		<b>HORARIO ALUMNO</b>
	</div>
	<div class='col-md-2'>
		<center><a href="/horary/consolidated/printconsolidated/" class='btn btn-success'><i class='glyphicon glyphicon-print'></i> Imprimir</a></center>
	</div>
</div>
<div class='row' style="margin:0px">
    <div class='col-md-12' id='encabezado'>
        <div class='cajadia'>Hora:</div>
        <div class='cajadia' style='margin-left:3px'>Lunes</div>
        <div class='cajadia' style='margin-left:3px'>Martes</div>
        <div class='cajadia' style='margin-left:2px'>Miercoles</div>
        <div class='cajadia' style='margin-left:2px'>Jueves</div>
        <div class='cajadia' style='margin-left:2px'>Viernes</div>
        <div class='cajadia' style='margin-left:2px'>Sábado</div>
    </div>
    <div class='col-md-12 pull-left' style='margin-bottom:40px'>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($h=$inih; $h <= $finh ; $h++) { ?> 
                <div class='cajadentro'><?php echo $hora[$h]['hora']?></div>
            <?php   
            }
            ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <=$finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                // print_r($dat); exit();
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":",$dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];
                    
                    if ($dia==1){
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m){
                                $this->horarys[$s]['hora_ini']=$hora[$i]['h_fin'].':'.$hora[$i]['m_fin'].':00';
                                ?>
                                <div class='cajadentro' style='margin-left:2px; background-color:<?php echo $dat[$s]['color']?>'><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica']?></div>
                                <?php
                                $c++;
                            } else {
                                $band=1;
                            }
                        }
                    } else {
                        $band=1;
                    }
                }
                if ($band==1 && $c==0){ ?>
                    <div class='cajadentro' style='margin-left:2px'></div>
                <?php
                }
           }
        ?>
        </div>

        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==2) {
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                        $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                        <?php    
                                        $c++;
                                    } else { 
                                        $band=1;
                                    }
                                }
                            } else { 
                                $band=1;
                            }
                        }
                        if($band==1 && $c==0){ ?>
                            <div class='cajadentro' style="margin-left:3px;"></div>
                        <?php    
                        }
                }
                ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==3) {
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                        $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                        <?php    
                                        $c++;
                                    } else { 
                                        $band=1;
                                    }
                                }
                            } else { 
                                $band=1;
                            }
                        }
                        if($band==1 && $c==0){ ?>
                            <div class='cajadentro' style="margin-left:3px;"></div>
                        <?php    
                        }
                }
                ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==4) {
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                        $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                        <?php    
                                        $c++;
                                    } else { 
                                        $band=1;
                                    }
                                }
                            } else { 
                                $band=1;
                            }
                        }
                        if($band==1 && $c==0){ ?>
                            <div class='cajadentro' style="margin-left:3px;"></div>
                        <?php    
                        }
                }
                ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==5) {
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                        $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                        <?php    
                                        $c++;
                                    } else { 
                                        $band=1;
                                    }
                                }
                            } else { 
                                $band=1;
                            }
                        }
                        if($band==1 && $c==0){ ?>
                            <div class='cajadentro' style="margin-left:3px;"></div>
                        <?php    
                        }
                }
                ?>
        </div>
        <div class='pull-left' style='width:144px'>
            <?php
            for ($i=$inih; $i <= $finh ; $i++) { 
                $band=0;
                $c=0;
                $dat=$this->horarys;
                for ($s=0; $s < $len ; $s++) { 
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                    if ($dia==6) {
                        if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                        $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="margin-left:3px; background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                        <?php    
                                        $c++;
                                    } else { 
                                        $band=1;
                                    }
                                }
                            } else { 
                                $band=1;
                            }
                        }
                        if($band==1 && $c==0){ ?>
                            <div class='cajadentro' style="margin-left:3px"></div>
                        <?php    
                        }
                }
                ?>
        </div>
    </div>
    <div class='row'>
            <div class='col-md-12'>
                <div class='cajadentro' style='margin-left:20px; width:50px; box-shadow: 0px 0px 4px #343434'>#</div>
                <div class='cajadentro' style='width:70px; box-shadow: 0px 0px 4px #343434'>Código</div>
                <div class='cajadentro' style='width:350px; box-shadow: 0px 0px 4px #343434'>Nombre Curso</div>
                <div class='cajadentro' style='width:40px; box-shadow: 0px 0px 4px #343434'>Sem.</div>
                <div class='cajadentro' style='width:40px; box-shadow: 0px 0px 4px #343434'>Turno</div>
                <div class='cajadentro' style='width:50px; box-shadow: 0px 0px 4px #343434'>Créditos</div>
                <div class='cajadentro' style='width:324px; box-shadow: 0px 0px 4px #343434'>Docente</div>
            </div>
                <?php
                // print_r($horaoriginal);
                $n=1;
                foreach ($this->horarys as $dathora) { 
                    if ($cursoant!=$dathora['courseid']) {
                        $cursoant=$dathora['courseid'];
                    ?>
            <div class='col-md-12 pull-left'>
                <div class="cajadentro" style="margin-left:20px; width:50px"><?php echo $n ?></div>
                <div class="cajadentro" style="width:70px; background-color:<?php echo $dathora["color"] ?>"><?php echo $dathora['courseid'] ?></div>
                <div class="cajadentro" style="width:350px"><?php echo $dathora['name'] ?></div>
                <div class="cajadentro" style="width:40px"><?php echo $dathora['semid'] ?></div>
                <div class="cajadentro" style="width:40px"><?php echo $dathora['turno'] ?></div>
                <div class="cajadentro" style="width:50px"><?php echo $dathora['credits'] ?></div>
                <div class="cajadentro" style="width:324px"><?php echo $dathora['nombredoc'] ?></div>
            </div>        
                <?php
                $n++;
                    }
                }
                ?>
    </div>
</div>    
<?php
} 
else{
    ?>
    <div class="alert alert-info">No hay registro.</div>
<?php
}
?> 
