<?php 
    $hora = array();
    $j=1;
    $hour_begin=array();
    $hour_begin=$this->valhoras;
    for ($i=0; $i <= 20; $i++) { 
        $hour[$i]=substr($hour_begin[$i],0,2);
        $minute[$i]=substr($hour_begin[$i],3,2);
    }
    for ($i=0; $i < 20; $i++) {
        if ($hour[$i] < 12) {
            if ($hour[$j] < 12) {
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." am";
            }
            else{
                $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." pm";
            }
        } 
        else{
            $hora[$i]['hora']=$hour[$i].":".$minute[$i]." pm - ".$hour[$j].":".$minute[$j]." pm";
        }
        $hora[$i]['h_ini']=$hour[$i];
        $hora[$i]['h_fin']=$hour[$j];
        $hora[$i]['m_ini']=$minute[$i];
        $hora[$i]['m_fin']=$minute[$j];
        $j++;
    }

    $listacolores = array();
    $listacolores[0] = "#FA8D74";
    $listacolores[1] = "#A3CFE0";
    $listacolores[2] = "#CBE487";
    $listacolores[3] = "#FAF48D";
    $listacolores[4] = "#FCB16B";
    $listacolores[5] = "#CCF0EE";
    $listacolores[6] = "#DFDFDF";
    $listacolores[7] = "#81FF86";
    $listacolores[8] = "#CD88FD";
    $listacolores[9] = "#F59FFC";
    $listacolores[10] = "#A58CFF";
    $listacolores[11] = "#F2BBBB";
    $listacolores[12] = "#D8BADA";
    $listacolores[13] = "#C4E6CE";
    $listacolores[14] = "#B4DAA1";
if ($this->error<>"A") {
    if ($this->horarys) {
            $len=count($this->horarys);
            $cco=0;
            $hmen=13;
            $hmay=13;
            for ($i=0; $i < $len - 1;$i++){
                $rid=substr($this->horarys[$i]['teach_uid'],8,2);
                if ($rid=='JP') $this->horarys[$i]['practica']='(P)';
                else $this->horarys[$i]['practica']="";
                $codcurso=$this->horarys[$i]['courseid'];
                $codcursodes=$this->horarys[$i+1]['courseid'];
                $turno=$this->horarys[$i]['turno'];
                $curid=$this->horarys[$i]['curid'];

                if($codcurso==$codcursodes){
                    $this->horarys[$i]['color']=$listacolores[$cco];
                }
                else{
                    $this->horarys[$i]['color']=$listacolores[$cco];
                    $cco++;
                }
                $hsplit=split(":",$this->horarys[$i]['hora_ini']);
                $hi=$hsplit[0];
                $hsplit=split(":", $this->horarys[$i]['hora_fin']);
                $hf=$hsplit[0];
                if($hi<=$hmen) $hmen=$hi;
                if($hf>=$hmay) $hmay=$hf;
                
            }
            $k=0;
            for ($z=0;$z < 20; $z++){
                    // print_r($hmen);exit();
                if ($hmen==$hora[$z]['h_ini'] && $k==0) {
                    $inih=$z;
                    $k=1;
                }
                if($hmay==$hora[$z]['h_fin']){
                    $finh=$z;
                }
            }
            $horaoriginal=$this->horarys;
            // print_r($hora[0]);
            // print_r($horaoriginal[0]);exit();
    ?>
    <div class="row col-md-12" style="margin:0px">
        <div class='nomdoc col-md-10' style='font-size:20px'>
            <b>HORARIO ALUMNO</b>
        </div>
        <div class='col-md-2'>
            <center><a href="/horary/consolidated/printconsolidated/" class='btn btn-success'><i class='glyphicon glyphicon-print'></i> Imprimir</a></center>
        </div>
    </div>
    <div class='row'>
        <div class="col-md-12">
            <div class='arreglo pull-left'>
                <div class='cajadia'><b>Hora:</b></div>
            </div>
            <div class='arreglo pull-left'>
                <div class='cajadia'><b>Lunes</b></div>
            </div>
            <div class='arreglo pull-left'>    
                <div class='cajadia'><b>Martes</b></div>
            </div>    
            <div class='arreglo pull-left'>    
                <div class='cajadia'><b>Miércoles</b></div>
            </div>        
            <div class='arreglo pull-left'>    
                <div class='cajadia'><b>Jueves</b></div>
            </div>        
            <div class='arreglo pull-left'>    
                <div class='cajadia'><b>Viernes</b></div>
            </div>        
            <div class='arreglo pull-left'>    
                <div class='cajadia'><b>Sábado</b></div>
            </div>    
        </div>    
        <div class='col-md-12'>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($h=$inih; $h <= $finh ; $h++) { ?> 
                    <div class='cajadentro'><?php echo $hora[$h]['hora']?></div>
                <?php   
                }
                ?>
            </div>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <=$finh ; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    // print_r($dat); exit();
                    for ($s=0; $s < $len ; $s++) { 
                        $hsplit=split(":",$dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];
                        
                        if ($dia==1){
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                if($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m){
                                    $this->horarys[$s]['hora_ini']=$hora[$i]['h_fin'].':'.$hora[$i]['m_fin'].':00';
                                    ?>
                                    <div class='cajadentro' style='background-color:<?php echo $dat[$s]['color']?>'><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica']?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                     <?php
                                    $c++;
                                } else {
                                    $band=1;
                                }
                            }
                        } else {
                            $band=1;
                        }
                    }
                    if ($band==1 && $c==0){ ?>      
                        <div class='cajadentro' ></div>
                    <?php
                    }
               }
            ?>
            </div>

            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh ; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    for ($s=0; $s < $len ; $s++) { 
                        $hsplit=split(":", $dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];

                        if ($dia==2) {
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                            $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                            ?>
                                            <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php  echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                            <?php    
                                            $c++;
                                        } else { 
                                            $band=1;
                                        }
                                    }
                                } else { 
                                    $band=1;
                                }
                            }
                            if($band==1 && $c==0){ ?>
                                <div class='cajadentro'></div>
                            <?php    
                            }
                    }
                    ?>
            </div>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh ; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    for ($s=0; $s < $len ; $s++) { 
                        $hsplit=split(":", $dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];

                        if ($dia==3) {
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                            $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                            ?>
                                            <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php  echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                            <?php    
                                            $c++;
                                        } else { 
                                            $band=1;
                                        }
                                    }
                                } else { 
                                    $band=1;
                                }
                            }
                            if($band==1 && $c==0){ ?>
                                <div class='cajadentro'></div>
                            <?php    
                            }
                    }
                    ?>
            </div>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    for ($s=0; $s < $len - 1 ; $s++) { 
                        $hsplit=split(":", $dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];

                        if ($dia==4) {
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                            $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                            ?>
                                            <div class="cajadentro" style="background-color:<?php echo $dat[$s]['color'] ?>"><?php  echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                            <?php    
                                            $c++;
                                        } else { 
                                            $band=1;
                                        }
                                    }
                                } else { 
                                    $band=1;
                                }
                            }
                            if($band==1 && $c==0){ ?>
                                <div class='cajadentro'></div>
                            <?php    
                            }
                    }
                    ?>
            </div>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh ; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    for ($s=0; $s < $len ; $s++) { 
                        $hsplit=split(":", $dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];

                        if ($dia==5) {
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                            $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                            ?>
                                            <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php  echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                            <?php    
                                            $c++;
                                        } else { 
                                            $band=1;
                                        }
                                    }
                                } else { 
                                    $band=1;
                                }
                            }
                            if($band==1 && $c==0){ ?>
                                <div class='cajadentro'></div>
                            <?php    
                            }
                    }
                    ?>
            </div>
            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh ; $i++) { 
                    $band=0;
                    $c=0;
                    $dat=$this->horarys;
                    for ($s=0; $s < $len ; $s++) { 
                        $hsplit=split(":", $dat[$s]['hora_ini']);
                        $h=$hsplit[0];
                        $m=$hsplit[1];
                        $dia=$dat[$s]['day'];

                        if ($dia==6) {
                            if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                            $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                            ?>
                                            <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                            <?php    
                                            $c++;
                                        } else { 
                                            $band=1;
                                        }
                                    }
                                } else { 
                                    $band=1;
                                }
                            }
                            if($band==1 && $c==0){ ?>
                                <div class='cajadentro'></div>
                            <?php    
                            }
                    }
                    ?>
            </div>
        </div>
    </div>    
        <div class='row'>
            <div class='col-md-12' style="margin-bottom:1%">
                <div class='cajadia' style='width:3%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>#</b></div>
                <div class='cajadia' style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Código</b></div>
                <div class='cajadia' style='width:38%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Nombre Curso</b></div>
                <div class='cajadia' style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Sem.</b></div>
                <div class='cajadia' style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Turno</b></div>
                <div class='cajadia' style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Créditos</b></div>
                <div class='cajadia' style='width:30%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Docente</b></div>
            </div>
                <?php
                // print_r($horaoriginal);
                $n=1;
                $cursoant = '';
                foreach ($this->horarys as $dathora) { 
                    if ($cursoant != $dathora['courseid']) {
                        $cursoant=$dathora['courseid'];
                    ?>
            <div class='col-md-12 pull-left'>
                <div class="cajacursos" style="width:3%; margin-right:1%;"><?php echo $n ?></div>
                <div class="cajacursos" style="width:5%; margin-right:1%; background-color:<?php echo $dathora["color"] ?>"><?php echo $dathora['courseid'] ?></div>
                <div class="cajacursos" style="width:38%; margin-right:1%;"><?php echo $dathora['name'] ?></div>
                <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $dathora['semid'] ?></div>
                <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $dathora['turno'] ?></div>
                <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $dathora['credits'] ?></div>
                <div class="cajacursos" style="width:30%; margin-right:1%;"><?php echo $dathora['nombredoc'] ?></div>
            </div>        
                <?php
                $n++;
                    }
                }
                ?>
        </div>
    </div>    
    <?php
    } 
    else{
        ?>
        <div class="alert alert-info">No hay registro.</div>
    <?php
    }
}
else{   ?>
<div class='col-md-6 col-md-offset-3 pull-center'>
    <div class='cont-font-not-register'>
        <h1 class='span-not-register'>
            <span class='glyphicon glyphicon-exclamation-sign'></span>
        </h1>
        <h3 class='text-not-register'>Hubo problemas con el servidor <a href="/profile/public/student">Click para Actualizar</a></h3>
    </div>
</div>
<?php
}
?> 
