<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-user"></span> Gestión Persona');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>

<div style="text-align:right">
    <button id="newper" type="button" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span> Nueva Persona</button>
</div>
</br>
<form name="frmFiltroDoc" id ="frmFiltroDoc" action="/admin/person/getperson" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table table-hover table-bordered">
        <tr>
            <td><center>DNI</center></td>
            <td><center>Nombres y Apellidos</center></td>
        </tr>
        <tr>                    
            <td><center><div style='width: 200px'><?php echo $this->fm->pid ?></center></td>
            <td><center><div style='width: 400px'><?php echo $this->fm->name ?></center></td>
        </tr>
    </table>
</form>
</br>
<div  id="cargadatos_"></div> 

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style='width:1000px;'>
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title"><b class='text-info'> <center> NUEVA PERSONA </center></b></h2>
            </div>
            <div class="modal-body">
                <div id='nueva_persona'></div>
            </div>
        </div>
    </div>
</div>

<script>
    $("#name, #pid").keypress(function (e) {
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#pid').val();
            var nom =  $('#name').val();
            count=codi.length;
            if (count==8 || count==0)
            {
                $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
                $("#frmFiltroDoc").submit();
            }
            else
            {
                alert("Ingrese un DNI valido");
                $('#pid').val('');
            }
        }
    });
    
    $("#frmFiltroDoc").submit(function(){
        $.ajax({
            url: $(this).attr('action'),
            type: 'POST',
            data: $(this).serialize(),
            success: function(data) {                        
                $('#cargadatos_').html(data);                                 
            }
        }); 
        return false;
    });

    $("#newper").click(function(){   
        $('#myModal').modal('show');            
        var url="/admin/person/new/";
        $("#nueva_persona").html("</br></br><center><img src='/img/spinner.gif'> Cargando...</center>");
        $("#nueva_persona").load(url);
    });

    function validNumber(e) {
        var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
        return ((tecla > 47 && tecla < 58) || tecla == 8);
    } 
    function soloLetras(e){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = [8,37,39,46];

        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }

        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }       
</script>