<style>
    .row1{
        padding:5px; 
        border: 1px solid #7F8C8D;
        margin: 2px
    }
    .row1:hover{
        background-color: #BDC3C7;
        border-left: 6px solid gray;
    }
    .row1:nth-child(2){
        background-color: #E74C3C
    }
    .col11{
        border-right: 1px solid gray;
    }
    .info1{
        border-radius: 0px;
    }
</style>
<?php $sms = $this->sms;
$C="btnChange btn btn-success form-control";
$A="btnChange btn btn-danger form-control";
if ($sms==1) {?>
    <?php if($this->row) { ?>
    <div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-success text-center" id="smsServ" role="alert">
                <strong>Que bien!</strong> se encontraron <strong><?php echo count($this->row); ?></strong>  Registros. <span class="label label-success"> Los docentes que no aparecen Aun no Comenzaron a rellenar este documento.</span>
            </div>
        </div>
    </div>
    <div class="row row1">
        <div class="col-xs-1 col11">Indice</div>
        <div class="col-xs-2 col11">Dni</div>
        <div class="col-xs-7 col11">Datos personales</div>
        <div class="col-xs-2">Opcion</div>
    </div>
        <?php $c=1;  foreach($this->row as $row){?>
            <div class="row row1">
                <div class="col-xs-1 col11"><?php echo $c ?></div>
                <div class="col-xs-2 col11"><?php echo $row['pid'];?></div>
                <div class="col-xs-7 col11"><?php echo $row['last_name0']." ".$row['last_name1']." ".$row['first_name']?></div>
                <div class="col-xs-2">
                    
                    <?php if ($row['state']=='C') {?>
                        <button class="<?php echo $C?>" perid= "<?php echo base64_encode($this->perid)?>" escid="<?php echo base64_encode($this->escid)?>" pid="<?php echo base64_encode($row['pid'])?>" state="C"> Abrir <span class="glyphicon glyphicon-folder-open"></span></button>
                    <?php } else { ?>
                        <button class="<?php echo $A?>" perid= "<?php echo base64_encode($this->perid)?>" escid="<?php echo base64_encode($this->escid)?>" pid="<?php echo base64_encode($row['pid'])?>" state="B"> Cerrar <span class="glyphicon glyphicon-folder-close"></span></button>
                    <?php } ?>
                </div>
            </div>
        <?php $c++;} ?>
    </div>
    <script type="text/javascript">
        $(".btnChange").click(function(e){
            e.preventDefault();
            var btn=$(this);
            btn.html("Cargando... <img src='/img/spinner.gif' />");
            var ajax_data = {
                "perid" : $(this).attr('perid'),
                "escid" : $(this).attr('escid'),
                "pid"   : $(this).attr('pid'),
                "state" : $(this).attr('state')
            };
            $.ajax({
                type : 'post',
                url  : '/admin/openinfoacademic/updatestate/',
                data : ajax_data,
                success: function(data){
                    if (data.status == true) {
                        btn.attr('class', data.do);
                        btn.attr('state', data.estado);
                        btn.html(data.text + " <span></span>");
                        btn.children('span').attr('class', data.icon);
                    };
                    console.log(data.sms);
                }
            });
        });
    </script>
    
    
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <strong> <h2>: (</h2>Lo sentimos!</strong> No tenemos registros de Informes Academicos en este periodo.
        </div>
    <?php } ?>
<?php } elseif($sms==2 || $sms==3) { ?>
    <div class="alert alert-danger" role="alert">
            <strong> <h2>: (</h2>Lo sentimos!</strong> Los Datos ingresados son erroneos.
    </div>
<?php }?>