<table class="table table-condensed" style="font-size: 12px;margin: 10px 0 -10px 0; width: 98%">
    <tr>
        <th style="font-size: 16px;"><center><?php echo $this->uid ?> - <?php echo strtoupper($this->user['last_name0']." ".$this->user['last_name1'].", ".$this->user['first_name']) ?></center></th> 
    </tr>
    <tr>
        <th><center>            
            FACULTAD DE <?php echo strtoupper($this->faculty['name']) ?><br/>
            ESCUELA DE  <?php echo strtoupper($this->school['name']) ?>
            </center>
        </th>      
    </tr>
</table>
<table class="table table-condensed" style="font-size: 12px;margin: 10px 0 -10px 0; width: 98%">
    <tr>
        <th style="font-size: 12px;">AÑO QUE TERMINO: </th> 
    </tr>
    <tr>
        <th style="font-size: 12px;">NIVEL DE ESTUDIOS: </th> 
    </tr>
    <tr>
        <th style="font-size: 12px;">TITULO OBTENIDO: </th> 
    </tr>
</table>