<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-globe"></span> Reporte Egresados');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<?php $anio = date('Y'); 
$dataVista = $this->dataVista;
?>
<style>
	.etiqueta:hover{
		color: red;
	}
	input[type="checkbox"] {

		transform:scale(2,2);
   		-ms-transform:scale(2,2); /* IE 9 */
   		-moz-transform:scale(2,2); /* Firefox */
   		-webkit-transform:scale(2,2); /* Safari and Chrome */
   		-o-transform:scale(2,2); /* Opera */
	}
	hr{
		color: red;
	}
	body{
		z-index: 1;
	}
	#generate{
		background-color: #3498DB;
	}
	#generate:hover{
		background-color: #2980B9;
	}
	#report{
		display: none;
		position: absolute;
		height: 50px;
		width: 300px;
		background-color: #9B59B6;
		z-index: 5;
		top: 100px;
		left: 500px;
	}
</style>
<input type="hidden" id="rol" value="<?php echo $dataVista['rid'] ?>">
<input type="hidden" id="escid" value="<?php echo $dataVista['dataEscid'] ?>">
<input type="hidden" id="periodCurrent" value="<?php echo ($dataVista['period']) ?>">

<div class="row">
<div class="col-md-2">
		<p class=""><span class="glyphicon glyphicon-info-sign"></span> Seleccione Año y periodo	:</p>
		</div>
	<div class="form-group">
		<div class='col-md-5'>
			<select name="anio" id="selectAnio" class="form-control">
				<?php for ($i=$anio; $i >= 1990; $i--) { ?>
					<option value="<?php echo $i ?>"><?php echo $i ?></option>
				<?php } ?>
			</select>
		</div>
		<div class='col-md-5'>
			<select id="selectPeriod" class="form-control">
			</select>
		</div>
	</div>
</div>
<hr>
<?php if ($dataVista['rid'] === "RC") { ?>
	<div class="row">
		<div class="col-md-2">
		<p class=""><span class="glyphicon glyphicon-info-sign"></span> Seleccione facultad y escuela:</p>
		</div>
		<div class="col-md-5 col1">
			<select name="faculty" id="selectFaculty" class="form-control"> 
				<option value="TODOFAC">TODAS LAS FACULTADES</option>
				<?php foreach ($this->dataFaculty as $c => $faculty): ?>
					<option value="<?php echo ($faculty['facid']) ?>" cod="<?php echo $faculty['facid'] ?>"><?php echo $faculty['name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="col-md-5 col1">
			<select name="school" id="selectSchool" class="form-control">
				<option value="TODOESC">TODAS LAS ESCUELAS</option>
			</select>
		</div>
		<div id="div-spec" style="display:none">
			<select name="speciality" id="selectSpeciality" class="form-control">
			</select>
		</div>
	</div>
	<hr>
	<script>
		$('#selectFaculty').on('change', function(){
				facid = $(this).val();
				reset();
			if (facid=='TODOFAC') {
				$('#selectSchool').html('<option value="TODOESC">TODAS LAS ESCUELAS</option>');
			}else{
				$('#selectSchool').html('<option value="">Cargando...</option').load('/graduated/reportgraduated/schools/facid/'+facid);
			};
		});

			$('#selectSchool').on('change', function(){
				dataEscid = $(this).val();
 
				if (dataEscid =='TODOESC') {
					$('#selectSpeciality').html('');
				}else{
					var ajax_data = {
						"escid" : dataEscid
					};
					$.ajax({
						type : 'post',
						url  : '/graduated/reportgraduated/speciality/',
						data : ajax_data,
						success: function(data){
							if (data!='') {
								$(".col1").removeClass('col-md-5').addClass('col-md-3');
								$('#div-spec').attr('class','col-md-4').addClass('has-error').show("slow");
								$('#selectSpeciality').html(data);
							}else{
								reset();
								$('#selectSpeciality').html('');
							};
						}
					});
				};
			});
	</script>
<?php } elseif($dataVista['rid'] === "RF"){ ?>
<!-- vista de RF -->
	<div class="row">
		<select name="faculty" id="selectFaculty" class="hide"> 
				<option value="<?php echo $dataVista['facid']; ?>"></option>
		</select>
		<div class="col-md-2">
			<p><span class="glyphicon glyphicon-info-sign"></span> Seleccione una escuela para empezar:</p>
		</div>
		<div class="col-md-10 col2">
			<select name="school" id="selectSchool" class="form-control">
				<option value="TODOESC">**TODA LA FACULTAD**</option>
				<?php foreach ($this->dataSchool as $c => $school): ?>
					<option value="<?php echo $school['escid'] ?>"><?php echo $school['name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div id="div-spec" style="display:none">
			<select name="speciality" id="selectSpeciality" class="form-control">
			</select>
		</div>
	</div>
	<script>
		$('#selectSchool').on('change', function(){
				dataEscid = $(this).val();
					var ajax_data = {
						"escid" : dataEscid
					};
					$.ajax({
						type : 'post',
						url  : '/graduated/reportgraduated/speciality/',
						data : ajax_data,
						success: function(data){
					if (data!='') {
						$(".col2").removeClass('col-md-10').addClass('col-md-5');
						$('#div-spec').attr('class','col-md-5').addClass('has-error').show("slow");
						$('#selectSpeciality').html(data);
					}else{
						reset();
					};
				}
			});
		});
	</script>
<?php } else { ?>
<!-- vista demas usuarios -->
<div class="row hide" id="div-spec">
	<div class="col-md-2">
		<p><span class="glyphicon glyphicon-info-sign"></span> Seleccione una Especialidad:</p>
	</div>

	<select name="faculty" id="selectFaculty" class="hide"> 
		<option value="<?php echo $dataVista['facid']; ?>"></option>
	</select>
	<select name="school" id="selectSchool" class="hide"> 
		<option value="<?php echo $dataVista['escid']; ?>"></option>
	</select>
	<div class="col-md-10 has-error">
		<select name="speciality" id="selectSpeciality" class="form-control"></select>
	</div>
</div>
<hr/>

<script>
	$(function(){
		var ajax_data = {
			 	"escid" : "<?php echo $dataVista['escid'] ?>"
			};
			$.ajax({
				type : 'post',
				url  : '/graduated/reportgraduated/speciality/',
				data : ajax_data,
				success: function(data){
					if (data!='') {
						$('#div-spec').removeClass('hide').append("<hr>");
						$('#selectSpeciality').html(data);
					}else{
						reset();
					};
				}
			});
	});
</script>
<?php } ?>

<div class="row">
    <div class="col-sm-4 col-sm-offset-2" style="height:34px; background:#2ECC71;">
    	<div class="checkbox text-center">
	        <label id="totales">
			    <input id="totales-act" name="check-cantidad" type="checkbox">
			   	<span class="glyphicon glyphicon-list"></span>  ¡Click Aqui! si desea un reporte en cantidades.
			</label>
    	</div>
    </div>
	<div class="col-sm-4">

		<button class="btn form-control" type="button" id="generate" data-loading-text="Buscando..."><span class="glyphicon glyphicon-play-circle"></span> Generar</button>
	</div>
</div>
<br/>
<br/>
<div id="report">
</div>
<div id="reporte" class="row"></div>
<script>
$(function(){
	var rid       = $('#rol').val();
	var period    = $('#periodCurrent').val();
	var anio      = $('#selectAnio').val();
	var facid     = '';
	var dataEscid = $('#escid').val();
	var data      = period + '-' + dataEscid;

	$('#selectPeriod').html('<option>Cargando...</option>').load("/graduated/reportgraduated/periods/anio/"+anio);
	$("#selectAnio").change(function(){
		var anio = $(this).val();
		var url = "/graduated/reportgraduated/periods/anio/"+anio;
		$("#selectPeriod").load(url);
	});
	$('#generate').on( "click", function() {
		var btn = $(this);
		var dir;
    	btn.button('loading');
		var total    = document.getElementById("totales-act").checked;
  		var perid    = document.getElementById("selectPeriod").value;
  		var facidt   = document.getElementById("selectFaculty").value;
  		var escidf   = document.getElementById("selectSchool").value;
  		var espid    = document.getElementById("selectSpeciality").value;
		var ajax_dat = {
		 	"perid"		: perid,
		 	"facid"			: facidt,
		 	"escid"			: escidf,
		 	"especialidad"	: espid
		};
		if (total==true) {
			dir='/graduated/reportgraduated/totalgraduateds/';
		}else{
			dir='/graduated/reportgraduated/listgraduateds/';
		};
		$.ajax({	
			type : 'post',
			url  : dir,
			data : ajax_dat,
			success: function(data){
				$('#reporte').html(data);
				btn.button('reset');
			}
		});
	});
});
	
function reset (argument) {
	$('#div-spec').hide( 1000, function() {
		$('#selectSpeciality').html("");
		$(".col1").removeClass('col-md-3').addClass('col-md-5');
		$(".col2").removeClass('col-md-5').addClass('col-md-10');
		$('#report').html("");
  	} );

}
</script>
