<?php
if ($this->egresados) { ?>
<div class="row">
	<div class="col-md-4 col-md-offset-1">
		<div id="showList">
			<blockquote>
				<h4>Imprimir <span class="text-muted">Lista </span><a href="/graduated/reportgraduated/print/facid/<?php echo base64_encode($this->facid)?>/escid/<?php echo base64_encode($this->escid)?>/especialidad/<?php echo base64_encode($this->especialidad)?>/perid/<?php echo base64_encode($this->perid)?>/anho/<?php echo base64_encode($this->anho)?>" class="text-warning"><span class="glyphicon glyphicon-print"></span></a></h4>
			</blockquote>
		</div>
		<div id="showGraphic">
			<blockquote>
				<h4>Vista <span class="text-warning">Gráfica</span></h4>
			</blockquote>
		</div>
	</div>
	<div class="col-md-1 col-md-offset-4">
		<h3><a title="Vista en Tabla" id="btnTable" href="##" class="text-warning"><span class="glyphicon glyphicon-list-alt"></span></a></h3>
	</div>
	<div class="col-md-1">
		<h3><a title="Vista en Gráfico" id="btnGraphic" href="##" class="text-warning"><span class="glyphicon glyphicon-picture"></span></a></h3>
	</div>
</div>

<div id="data">

	<table class="table table-hover">
		<tr>
			<th><h5><strong>#</strong></h5></th>
			<th class="text-center"><h5><strong>Cod. Matricula</strong></h5></th>
			<th class="text-center"><h5><strong>DNI</strong></h5></th>
			<th><h5><strong>Apellidos y Nombres</strong></h5></th>
			<th class="text-center"><h5><strong>Escuela | Especialidad</strong></h5></th>
			<th class="text-center"><h5><strong>Currícula</strong></h5></th>
			<th class="text-center"><h5><strong>Nivel</strong></h5></th>
		</tr>
	<?php
		$c=1;
		$escu= new Api_Model_DbTable_Speciality();
		foreach ($this->egresados as $egre) { 
			$whereesc =array(
				'eid' => $egre['eid'], 'oid' => $egre['oid'],
				'subid' => $egre['subid'], 'escid' => $egre['escid']);
			$dat = $escu->_getOne($whereesc); ?>
			<tr>
				<td><h5><?php echo $c?></h5></td>
				<td class="text-center"><h5><?php echo $egre['uid']?></h5></td>
				<td class="text-center"><h5><?php echo $egre['pid']?></h5></td>
				<td><h5><?php echo $egre['fullname']?></h5></td>
				<td class="text-center"><h5><?php echo $dat['name']?></h5></td>
				<td class="text-center"><h5><?php echo $egre['curid']?></h5></td>
				<td class="text-center"><h5><a href="#myModal" id='<?php echo $c?>'><span class="glyphicon glyphicon-pencil"></span></a></h5></td>
				<script>
					$("#<?php echo $c?>").click(function() {
						var uid = "<?php echo $egre['uid']?>";
						var escid = "<?php echo $egre['escid']?>";
						var pid = "<?php echo $egre['pid']?>";
						$("#cargarformrol").html("<img src='/img/spinner.gif'>Cargando...");
						$("#cargarformrol").load("/graduated/reportgraduated/academic/uid/"+uid+"/escid/"+escid+"/pid/"+pid);
						$('#myModal').modal('show');
					});
				</script>	
				</tr>
		<?php
		$c++; ?>
	<?php	}
		?>
	</table>
	<?php 
	}else{ ?>
		<div class="alert alert-info">No hay registro de Egresados.</div>
	<?php 
	} ?>

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          		<h4 class="modal-title">FICHA ACADEMICA</h4>
        	</div>
        	<div class="modal-body">
        		<div id="cargarformrol"></div>
        	</div>
        	<div class="modal-footer">
          		<a href="#" id="close_new_cur" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
        	</div>
      	</div>
    </div>
</div>

<script>
	$('#showGraphic').fadeOut('fast');
	$('#btnTable').click(function(){
		$('#showGraphic').fadeOut('slow');
		$('#showList').fadeIn('slow');
		$('#graphic').fadeOut('slow');
		$('#data').fadeIn('slow');
	});

	$('#btnGraphic').click(function(){
		$('#showList').fadeOut('slow');
		$('#showGraphic').fadeIn('slow');
		$('#data').fadeOut('slow');
		$('#graphic').fadeIn('slow');
	});
</script>