<?php 
if ($this->lper){ ?>
	<option value="<?php echo $this->an."T" ?>">Ambos periodos</option>
	<?php
    foreach ($this->lper as $perio){ 
    	?>
        	<option value="<?php echo $perio['perid']?>"><?php echo $perio['perid']." | ".$perio['name']?></option>
        <?php 
    } ?>
<?php 
}else{ ?>
    <option value=""><?php echo $this->anio?>--No tienen ningun periodo</option>
    <?php
} ?> 