<?php 
	if ($this->escuelas) { ?>
		<option value="TODOESC"> **TODAS ESTA FACULTAD**</option>
		<?php
		foreach ($this->escuelas as $escuelas) {
			if ($this->escid) $str = ($this->escid==$escuelas['escid'])?"selected ":""; ?>
			<option value="<?php echo $escuelas['escid']?>"><?php echo $escuelas['name']?></option>
		<?php
		} 
	}else{ ?>		
		<option value="">No tiene ningun registro.</option>
	<?php
	} 
?>