<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-list"></span> Listado de Horarios');?>
<?php $this->placeholder('Btnnav')->append('<a href="/docente" class="btn btn-default form-control"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<div class="row">
	<div class="col-md-3 col-md-offset-2">
		<h5 class="text-info">Año</span></h5>
		<?php echo $this->fm->anio ?><br>
	</div>
	<div class="col-md-3 col-md-offset-1">
		<h5 class="text-info">Periodo</span></h5>
		<?php echo $this->fm->perids ?><br>
	</div>
</div>
<div id="loading"></div>
<div id='changehorary'></div>
<script type="text/javascript">
	$(function(){
		var anio='<?php echo $this->anio?>';	
		$("#anio option[value="+anio+"]").attr('selected','selected');
		var anio=$("#anio").val();
		var url=("/horary/semester/periodlist/anio/"+anio);
		$("#perids").load(url);
	});
	$("#anio").change(function(){
		var anio=$(this).val();
		var url=("/horary/semester/periodlist/anio/"+anio);
		$("#perids").load(url);
	});

	$("#perids").change(function(){
		var perid=$(this).val();
		var url=("/horary/semester/semesterlist/perid/"+perid);
		$("#loading").load(url);
	});
</script>