<?php 
	$hora = array();
	$hora[0]['hora']="6:20 am - 7:10 am";
    $hora[0]['h_ini']="06";  $hora[0]['h_fin']="07";  $hora[0]['m_ini']="20";  $hora[0]['m_fin']="10";
    $hora[1]['hora']="7:10 am - 8:00 am";
    $hora[1]['h_ini']="07";  $hora[1]['h_fin']="08";  $hora[1]['m_ini']="10";  $hora[1]['m_fin']="00";
    $hora[2]['hora']="8:00 am - 8:50 am";
    $hora[2]['h_ini']="08";  $hora[2]['h_fin']="08";  $hora[2]['m_ini']="00";  $hora[2]['m_fin']="50";
    $hora[3]['hora']="8:50 am - 9:40 am";
    $hora[3]['h_ini']="08";  $hora[3]['h_fin']="09";  $hora[3]['m_ini']="50";  $hora[3]['m_fin']="40";
    $hora[4]['hora']="9:40 am - 10:30 am";
    $hora[4]['h_ini']="09";  $hora[4]['h_fin']="10";  $hora[4]['m_ini']="40";  $hora[4]['m_fin']="30";
    $hora[5]['hora']="10:30 am - 11:20 am";
    $hora[5]['h_ini']="10";  $hora[5]['h_fin']="11";  $hora[5]['m_ini']="30";  $hora[5]['m_fin']="20";
    $hora[6]['hora']="11:20 am - 12:10 pm";
    $hora[6]['h_ini']="11";  $hora[6]['h_fin']="12";  $hora[6]['m_ini']="20";  $hora[6]['m_fin']="10";
    $hora[7]['hora']="12:10 pm - 13:00 pm";
    $hora[7]['h_ini']="12";  $hora[7]['h_fin']="13";  $hora[7]['m_ini']="10";  $hora[7]['m_fin']="00";
    $hora[8]['hora']="13:00 pm - 13:50 pm";
    $hora[8]['h_ini']="13";  $hora[8]['h_fin']="13";  $hora[8]['m_ini']="00";  $hora[8]['m_fin']="50";
    $hora[9]['hora']="13:50 pm - 14:40 pm";
    $hora[9]['h_ini']="13";  $hora[9]['h_fin']="14";  $hora[9]['m_ini']="50";  $hora[9]['m_fin']="40";
    $hora[10]['hora']="14:40 pm - 15:30 pm";
    $hora[10]['h_ini']="14";  $hora[10]['h_fin']="15";  $hora[10]['m_ini']="40";  $hora[10]['m_fin']="30";
    $hora[11]['hora']="15:30 pm - 16:20 pm";
    $hora[11]['h_ini']="15";  $hora[11]['h_fin']="16";  $hora[11]['m_ini']="30";  $hora[11]['m_fin']="20";
    $hora[12]['hora']="16:20 pm - 17:10 pm";
    $hora[12]['h_ini']="16";  $hora[12]['h_fin']="17";  $hora[12]['m_ini']="20";  $hora[12]['m_fin']="10";
    $hora[13]['hora']="17:10 pm - 18:00 pm";
    $hora[13]['h_ini']="17";  $hora[13]['h_fin']="18";  $hora[13]['m_ini']="10";  $hora[13]['m_fin']="00";
    $hora[14]['hora']="18:00 pm - 18:50 pm";
    $hora[14]['h_ini']="18";  $hora[14]['h_fin']="18";  $hora[14]['m_ini']="00";  $hora[14]['m_fin']="50";
    $hora[15]['hora']="18:50 pm - 19:40 pm";
    $hora[15]['h_ini']="18";  $hora[15]['h_fin']="19";  $hora[15]['m_ini']="50";  $hora[15]['m_fin']="40";
    $hora[16]['hora']="19:40 pm - 20:30 pm";
    $hora[16]['h_ini']="19";  $hora[16]['h_fin']="20";  $hora[16]['m_ini']="40";  $hora[16]['m_fin']="30";
    $hora[17]['hora']="20:30 pm - 21:20 pm";
    $hora[17]['h_ini']="20";  $hora[17]['h_fin']="21";  $hora[17]['m_ini']="30";  $hora[17]['m_fin']="20";
    $hora[18]['hora']="21:20 pm - 22:10 pm";
    $hora[18]['h_ini']="21";  $hora[18]['h_fin']="22";  $hora[18]['m_ini']="20";  $hora[18]['m_fin']="10";
    $hora[19]['hora']="22:10 pm - 23:00 pm";
    $hora[19]['h_ini']="22";  $hora[19]['h_fin']="23";  $hora[19]['m_ini']="10";  $hora[19]['m_fin']="00";

    $listacolores = array();
    $listacolores[0] = "#FA8D74";
    $listacolores[1] = "#A3CFE0";
    $listacolores[2] = "#CBE487";
    $listacolores[3] = "#FAF48D";
    $listacolores[4] = "#FCB16B";
    $listacolores[5] = "#CCF0EE";
    $listacolores[6] = "#DFDFDF";
    $listacolores[7] = "#81FF86";
    $listacolores[8] = "#CD88FD";
    $listacolores[9] = "#F59FFC";
    $listacolores[10] = "#A58CFF";
    $listacolores[11] = "#F2BBBB";
    $listacolores[12] = "#D8BADA";
    $listacolores[13] = "#C4E6CE";
    $listacolores[14] = "#B4DAA1"; 

if ($this->horarys) {
    	$len=count($this->horarys);
    	$cco=0;
    	$hmen=13;
    	$hmay=13;
    	for ($i=0; $i < $len;$i++){
    		$rid=substr($this->horarys[$i]['teach_uid'],8,2);
    		if ($rid=='JP') $this->horarys[$i]['practica']='(P)';
    		else $this->horarys[$i]['practica']="";
    		$codcurso=$this->horarys[$i]['courseid'];
    		$codcursodes=$this->horarys[$i+1]['courseid'];
    		$turno=$this->horarys[$i]['turno'];
    		$curid=$this->horarys[$i]['curid'];

    		if($codcurso==$codcursodes){
    			$this->horarys[$i]['color']=$listacolores[$cco];
    		}
    		else{
    			$this->horarys[$i]['color']=$listacolores[$cco];
    			$cco++;
    		}
    		$hsplit=split(":",$this->horarys[$i]['hora_ini']);
    		$hi=$hsplit[0];
    		$hsplit=split(":", $this->horarys[$i]['hora_fin']);
    		$hf=$hsplit[0];
    		if($hi<=$hmen) $hmen=$hi;
    		if($hf>=$hmay) $hmay=$hf;
    		
    	}
    	$k=0;
    	for ($z=0;$z < 20; $z++){
    			// print_r($hmen);exit();
    		if ($hmen==$hora[$z]['h_ini'] && $k==0) {
    			$inih=$z;
    			$k=1;
    		}
    		if($hmay==$hora[$z]['h_fin']){
    			$finh=$z;
    		}
    	}
    	// $horaoriginal=$this->horarys;
?>
<div>
	<div class='nomdoc col-md-10' style='font-size:20px; margin-top:20px'>
		<b>HORARIO ALUMNO</b>
	</div>
	<div class='col-md-2' style='float:left;margin-top:20px'>
		<a href="/horary/semester/printhorary/" class='btn btn-success'><i class='glyphicon glyphicon-print'></i>Imprimir</a>
	</div>
</div>
<div class='col-md-16' style='float:left;'>
	<div id='encabezado'>
		<div class='cajadia'>Hora:</div>
		<div class='cajadia' style='margin-left:2px'>Lunes</div>
		<div class='cajadia' style='margin-left:2px'>Martes</div>
		<div class='cajadia' style='margin-left:2px'>Miercoles</div>
		<div class='cajadia' style='margin-left:2px'>Jueves</div>
		<div class='cajadia' style='margin-left:2px'>Viernes</div>
		<div class='cajadia' style='margin-left:1px'>Sábado</div>
	</div>
	<div style='float:left; width:144px'>
		<?php
		for ($h=$inih; $h <= $finh ; $h++) { ?> 
			<div class='cajadentro'><?php echo $hora[$h]['hora']?></div>
		<?php	
		}
		?>
	</div>
	<div style='float:left; width:144px'>
		<?php
		for ($i=$inih; $i <=$finh ; $i++) { 
			$band=0;
			$c=0;
			$dat=$this->horarys;
			// print_r($dat); exit();
			for ($s=0; $s < $len ; $s++) { 
				$hsplit=split(":",$dat[$s]['hora_ini']);
				$h=$hsplit[0];
				$m=$hsplit[1];
				$dia=$dat[$s]['day'];
				
				if ($dia==1){
					if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
						if($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m){
							$this->horarys[$s]['hora_ini']=$hora[$i]['h_fin'].':'.$hora[$i]['m_fin'].':00';
							// exit();	
							?>
							<div class='cajadentro' style='background-color:<?php echo $dat[$s]['color']?>'><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica']?></div>
							<?php
							$c++;
						} else {
							$band=1;
						}
					}
				} else {
					$band=1;
				}
			}
			if ($band==1 && $c==0){ ?>
				<div class='cajadentro'></div>
			<?php
			}
	   }
	?>
	</div>

    <div style="float:left; width:144px">
        <?php
        for ($i=$inih; $i <= $finh ; $i++) { 
            $band=0;
            $c=0;
            $dat=$this->horarys;
            for ($s=0; $s < $len ; $s++) { 
                $hsplit=split(":", $dat[$s]['hora_ini']);
                $h=$hsplit[0];
                $m=$hsplit[1];
                $dia=$dat[$s]['day'];

                if ($dia==2) {
                    if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                    $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                    <?php    
                                    $c++;
                                } else { 
                                    $band=1;
                                }
                            }
                        } else { 
                            $band=1;
                        }
                    }
                    if($band==1 && $c==0){ ?>
                        <div class='cajadentro'></div>
                    <?php    
                    }
            }
            ?>
    </div>
    <div style="float:left; width:144px">
        <?php
        for ($i=$inih; $i <= $finh ; $i++) { 
            $band=0;
            $c=0;
            $dat=$this->horarys;
            for ($s=0; $s < $len ; $s++) { 
                $hsplit=split(":", $dat[$s]['hora_ini']);
                $h=$hsplit[0];
                $m=$hsplit[1];
                $dia=$dat[$s]['day'];

                if ($dia==3) {
                    if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                    $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                    <?php    
                                    $c++;
                                } else { 
                                    $band=1;
                                }
                            }
                        } else { 
                            $band=1;
                        }
                    }
                    if($band==1 && $c==0){ ?>
                        <div class='cajadentro'></div>
                    <?php    
                    }
            }
            ?>
    </div>
    <div style="float:left; width:144px">
        <?php
        for ($i=$inih; $i <= $finh ; $i++) { 
            $band=0;
            $c=0;
            $dat=$this->horarys;
            for ($s=0; $s < $len ; $s++) { 
                $hsplit=split(":", $dat[$s]['hora_ini']);
                $h=$hsplit[0];
                $m=$hsplit[1];
                $dia=$dat[$s]['day'];

                if ($dia==4) {
                    if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                    $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                    <?php    
                                    $c++;
                                } else { 
                                    $band=1;
                                }
                            }
                        } else { 
                            $band=1;
                        }
                    }
                    if($band==1 && $c==0){ ?>
                        <div class='cajadentro'></div>
                    <?php    
                    }
            }
            ?>
    </div>
    <div style="float:left; width:144px">
        <?php
        for ($i=$inih; $i <= $finh ; $i++) { 
            $band=0;
            $c=0;
            $dat=$this->horarys;
            for ($s=0; $s < $len ; $s++) { 
                $hsplit=split(":", $dat[$s]['hora_ini']);
                $h=$hsplit[0];
                $m=$hsplit[1];
                $dia=$dat[$s]['day'];

                if ($dia==5) {
                    if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                    $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                    <?php    
                                    $c++;
                                } else { 
                                    $band=1;
                                }
                            }
                        } else { 
                            $band=1;
                        }
                    }
                    if($band==1 && $c==0){ ?>
                        <div class='cajadentro'></div>
                    <?php    
                    }
            }
            ?>
    </div>
    <div style="float:left; width:144px">
        <?php
        for ($i=$inih; $i <= $finh ; $i++) { 
            $band=0;
            $c=0;
            $dat=$this->horarys;
            for ($s=0; $s < $len ; $s++) { 
                $hsplit=split(":", $dat[$s]['hora_ini']);
                $h=$hsplit[0];
                $m=$hsplit[1];
                $dia=$dat[$s]['day'];

                if ($dia==6) {
                    if ($this->horarys[$s]['hora_ini']!=$this->horarys[$s]['hora_fin']){
                            if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) { 
                                    $this->horarys[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['practica'] ?></div>
                                    <?php    
                                    $c++;
                                } else { 
                                    $band=1;
                                }
                            }
                        } else { 
                            $band=1;
                        }
                    }
                    if($band==1 && $c==0){ ?>
                        <div class='cajadentro'></div>
                    <?php    
                    }
            }
            ?>

    </div>
    <div class='col-md-12' style='margin-top:450px'>
        <div class='cajadentro' style='width:30px;box-shadow: 0px 0px 4px #343434'>#</div>
        <div class='cajadentro' style='width:60px;box-shadow: 0px 0px 4px #343434'>Código</div>
        <div class='cajadentro' style='width:320px;box-shadow: 0px 0px 4px #343434'>Nombre Curso</div>
        <div class='cajadentro' style='width:40px;box-shadow: 0px 0px 4px #343434'>Sem.</div>
        <div class='cajadentro' style='width:40px;box-shadow: 0px 0px 4px #343434'>Turno</div>
        <div class='cajadentro' style='width:50px;box-shadow: 0px 0px 4px #343434'>Créditos</div>
        <div class='cajadentro' style='width:320px;box-shadow: 0px 0px 4px #343434'>Docente</div>

        <?php
        // print_r($horaoriginal);
        $n=1;
        foreach ($this->horarys as $dathora) { 
            if ($cursoant!=$dathora['courseid']) {
                $cursoant=$dathora['courseid'];
            ?>
        <div>
            <div class="cajadentro" style="width:30px"><?php echo $n ?></div>
            <div class="cajadentro" style="width:60px;background-color:<?php echo $dathora["color"] ?>"><?php echo $dathora['courseid'] ?></div>
            <div class="cajadentro" style="width:320px"><?php echo $dathora['name'] ?></div>
            <div class="cajadentro" style="width:40px"><?php echo $dathora['semid'] ?></div>
            <div class="cajadentro" style="width:40px"><?php echo $dathora['turno'] ?></div>
            <div class="cajadentro" style="width:50px"><?php echo $dathora['credits'] ?></div>
            <div class="cajadentro" style="width:320px"><?php echo $dathora['nombredoc'] ?></div>
        </div>
        <?php
        $n++;
            }
        }
        ?>    
    </div>
</div>
<?php
// print_r($this->horarios);
}else{
?>
<div class="alert alert-info">No hay registro.</div>
<?php
    }
?> 
