<option value="">Seleccione un Periodo</option>
<?php
if ($this->period) {
    foreach ($this->period as $periodos) {
    	$perid_sub = substr($periodos['perid'],2,1);
    	if ($perid_sub=='A' || $perid_sub=='B' || $perid_sub=='N') {    	?>
    		<option value="<?php echo $periodos['perid']?>"><?php echo $periodos['perid']." | ".$periodos['name']?></option>
    	<?php
    	}
    }
}
else{	?>
	<option value="">No existen periodos</option>
<?php
}
?>
<script>
	$(function(){
		var rid = '<?php echo $this->rid ?>';
		var perid='<?php echo $this->perid ?>';
		$("#perids option[value="+perid+"]").attr('selected','selected');
		var perid=$("#perids").val();

		if (rid!='PD') {
			$("#loading").empty();
			$("#changehorary").empty();
			
			var url=("/horary/semester/semesterlist/perid/"+perid);
        	$("#loading").html("<center><img src='/img/spinner.gif'/> Cargando...</center>");
			$("#loading").load(url);			
		}
	});
</script>