<?php
	if ($this->escuelas) { ?>
		<option value="">- Seleccione Escuela -</option>
        <?php
			foreach ($this->escuelas as $escuelas) {
				$escid=base64_encode($escuelas['escid']);
				$subid_cryp=base64_encode($escuelas['subid']); 
				if($escuelas['state']=='A'){?>
					<option value="<?php echo $escid."||".$subid_cryp?>"><?php echo $escuelas['name']?></option>
				<?php
				}	
			}
	}else{ ?>		
		<option value="">No tiene ningun registro.</option>
	<?php
	} 
?>