<?php
	if($this->semester) { ?>
		<div class='alert alert-success' style='text-align:center'>
			<center style='font-size:20px'><b>SEMESTRES</b></center>
		<?php
			foreach($this->semester as $semester) { ?>			 
				<a id='semester<?php echo $semester['semid']?>' href="#" class='btn btn-success' semid='<?php echo $semester['semid']?>' style='margin-left:40px;margin-rigth:15px'><b><?php echo $semester['name']?></b>
				</a>				
				<script type="text/javascript">
					$("#semester<?php echo $semester['semid']?>").click(function(){
						var perid="<?php echo $this->perid?>";
						$this=$(this);
						semid=$this.attr('semid');
						var url='/horary/semester/horarysemester/semid/'+semid+'/perid/'+perid;
						$('#changehorary').html("<img src='/img/spinner.gif'>Cargando....");
						$('#changehorary').load(url);
						});
				</script>
		<?php
		}	?>
		</div>
	<?php
	}else {  ?>
		<div class='alert alert-danger'>NO HAY REGISTRO.</div>
	<?php
	}	?>