<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-th-list"></span> REPORTE GENERAL');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left "></span> Regresar </a>');?>
<div class="row">
    <div class="col-md-12 text-right">
        <div class="col-md-1 col-md-offset-2"><b>Año: </b></div>
        <div class="col-md-2">
            <select id="anho" class="form-control">
                <option value="">- Año -</option>
                <?php
                for ($i=$this->anio;$i>=1965;$i--) { ?>
                    <option value="<?php echo $i;?>"><?php echo $i;?></option>
                <?php }
                ?>
            </select>
        </div>
        <div class="col-md-1"><b>Periodo: </b></div>
        <div class="col-md-2">
            <select id="periodo_c" class="form-control">
                <option value="">- Seleccione un Año -</option>
            </select>
        </div>
    </div>
</div><br>
<div class="row">
    <div class="col-md-12 text-right">
        <div class="col-md-1"><b>Facultad: </b></div>
        <div class="col-md-3">
            <select id="facid" class="form-control">
                <option>- Seleccione la Facultad -</option>
                <?php
                if ($this->facultades) {
                    foreach ($this->facultades as $facultades) { 
                        $str = ($this->facid==$facultades['facid'])?"selected ":""; ?>
                        <option <?php echo $str?>  value="<?php echo $facultades['facid']?>"><?php echo $facultades['name']?></option>
                    <?php
                    }
                } ?>
            </select>
        </div>

        <div class="col-md-1"><b>Escuela: </b></div>
        <div class="col-md-3">
           <select id="escid" class="form-control" style="width:260px">
                <option value="">- Seleccione la Escuela -</option>
            </select>
        </div>

        <div class="col-md-1"><b>Especialidad: </b></div>
        <div class="col-md-3">
            <select id="especialidad" class="form-control" style="width:260px">
                <option value="">- Seleccione la Especialidad -</option>
            </select>
        </div>        
    </div>
</div><br>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-1 col-md-offset-5">
            <center><a id="generar" href="#" class="btn btn-success"><span class="glyphicon glyphicon-arrow-down"></span> Ver Reportes</a></center>
        </div>
    </div>
</div>
<hr>
<div id="cargadatos"></div>

<script type="text/javascript">
var rid="<?php echo $this->rid ?>";
if (rid=="RF" || rid=="DIREC") {
    $("#facid").attr("disabled",true);
    var facid=$("#facid").val();
    // alert("/report/Consolidated/schools/facid/"+facid);
    $("#escid").load("/report/consolidated/schools/facid/"+facid);
        if (rid=="DIREC") {
            $("#escid").attr("disabled",true);
            var escid='<?php echo $this->escid?>';
            $("#especialidad").load("/report/consolidated/speciality/escid/"+escid);
        };
};
$(document).ready(function(){
    var anio="<?php echo $this->anio?>";
    $("#anho option[value="+anio+"]").attr('selected','selected');

    var anio = $("#anho").val();
    var url = "/report/consolidated/periods/anio/"+anio;
    $("#periodo_c").load(url);
}); 

$("#anho").change(function(){
    var anio = $(this).val();
    var url = "/report/consolidated/periods/anio/"+anio;
    $("#periodo_c").load(url);
});

$("#facid").change(function(){
    var facid=$(this).val();
    $("#escid").load("/report/consolidated/schools/facid/"+facid);
    if (facid=="TODO") {
        var escid="TODOEC";
        $("#especialidad").load("/report/consolidated/speciality/escid/"+escid);
    };
});

$("#escid").change(function(){
    var tescid = $("#escid").val();
    var xx1 = tescid.split(";--;");
    var escid = xx1[0];
    var subid = xx1[1];
    $("#especialidad").load("/report/consolidated/speciality/escid/"+escid);
});
$("#especialidad").change(function(){
    var facid=$(this).val();   
});


$("#generar").click(function(){
    var facid = $("#facid").val();
    var tescid = $("#escid").val();
    var xx1 = tescid.split(";--;");
    var escid = xx1[0];
    var subid = xx1[1];

    var espec = $("#especialidad").val();

    var anho = $("#anho").val();
    var periodo = $("#periodo_c").val();
    var xx = periodo.split(";--;");
    var perid = xx[0];
    var estado = xx[1];
    if (facid=='' || escid=='' || perid=='') {
        alert("Seleccione la Facultad, Escuela y el Periodo Académico.");
        return false;
    };
    var url="/report/consolidated/windows/facid/"+facid+"/escid/"+escid+"/espec/"+espec+"/perid/"+perid+"/subid/"+subid;
    // console.log(url);
    $('#cargadatos').html("<img src='/img/spinner.gif'>Cargando...");
    $("#cargadatos").load(url);
});
</script>