<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$tipo=$this->tipo;
if ($tipo=='1') { $a="REPORTES MATRICULADOS POR CURSO"; } 
else{ $a="REPORTE AVANCE DE NOTAS POR CURSO"; }

?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
    <div style="text-align: left;"><strong>Curso: </strong><?php echo strtoupper($this->courseid)?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Periodo: </strong><?php echo strtoupper($this->perid)?> </div>
    <div style="font-size:12px; text-align:center; margin-top:3%; margin-bottom:3%"><strong><?php echo strtoupper($a)?></strong></div>

    <table style="width:95%; margin-left:6%" border="1" >
        <thead>
          <tr>
            <th class='small'>#</th>
            <th class='small-100'>Codigo</th>
            <th>Apellido y Nombre</th>
            <?php
                $tipo=$this->tipo;
             if ($tipo=='2') { ?>
            <th class='small-70'>1º Parcial</th>
            <th class='small-70'>2º Parcial</th>
            
           <?php }?>
           
        </tr>
        </thead>
    <?php
    if ($this->data)
    {
       $i=1;
       foreach ($this->data as $datos)    
        {?>
        <tr>
          <td style="text-align:center"> <?php print $i?> </td>
          <td style="text-align:center"> <?php print $datos['uid']?> </td>
          <td> <?php print strtoupper($datos['last_name0'])." ".strtoupper($datos['last_name1'])." ".$datos['first_name']?> </td> 
          <?php if ($tipo=='2') { ?>
          <td style="text-align:center"> <?php print $datos['promedio1']?> </td>
          <td style="text-align:center"> <?php print $datos['promedio2']?> </td>
           <?php }?>
        </tr><?php
        $i++;
        }
    }
    ?>           
    </table>

<?php 

    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,33,18,5,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    // $mpdf->Output('Curso-'.$this->courseid.'.pdf','D');
    $mpdf->Output();
 
?>