 <?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$tipo=$this->tipo;
if ($tipo=='6') { $a="CONSOLIDADO POR SEMESTRE"; } 
else{ $a="REPORTES MATRICULADOS POR SEMESTRE"; }
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="text-align: left;"><strong>Semestre: </strong><?php echo strtoupper($this->semid)?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Periodo: </strong><?php echo strtoupper($this->perid)?> </div>
<div style="font-size:12px; text-align:center; margin-top:3%; margin-bottom:3%"><strong><?php echo strtoupper($a)?></strong></div>
<table style="width:100%; font-size: 9px;" border="1"  >
    <thead>
        <tr>
            <th class='small'>#</th>
            <th class='small-100'>Codigo</th>
            <th class='small-100'>Apellidos y Nombres</th>
            <?php
                $tipo=$this->tipo;
             if ($tipo=='6') { ?>
            <th style="width:50%;">Cursos</th>
            <th class='small'>Notas</th>
            <th style="width:20px;">Promedio</th>
                      
           <?php }?>
           
        </tr>
    </thead>
    <?php
    if ($this->data)
    {   
        $j=1;
        foreach ($this->data as $datos) {
            $name=strtoupper($datos['nombrecompleto']);  
            ?>
            <tr>
                <td style='text-align:center'><?php echo $j?></td>
                <td style='text-align:center'> <?php echo $datos['uid']?> </td>
                <td> <?php echo $name?> </td> 
                <?php if ($tipo=='6') { ?>
                <td>
                    <ol>
                        <?php
                            $len=$datos['cantidad'];
                            for ($i=0; $i < $len; $i++) { ?>
                                <li><?php echo $datos['cursos'][$i]['name']?></li>
                        <?php        
                            }
                        ?>    
                    </ol>
                </td> 
                <td style='text-align:center'>
                    <dl>
                        <?php
                            $len=$datos['cantidad'];
                            for ($i=0; $i < $len; $i++) { 
                                if ($datos['cursos'][$i]['notafinal']) {   ?>   
                                    <dt><?php echo $datos['cursos'][$i]['notafinal']?></dt>
                        <?php   
                                }     
                                else{ ?>
                                    <dt>-</dt>
                        <?php        
                                }
                            }
                        ?>    
                    </dl>
                </td> 
                <td style='text-align:center'><?php echo $datos['promedio']?></td> 
                <?php      
                }   
                ?>
            </tr>    
        <?php
        $j++;
        }
    }
    ?>
</table>    

<?php 

    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,33,18,5,5);
    $mpdf->SetWatermarkImage('/img/UNDAC.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer,'O');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    // $mpdf->Output('Semestre-'.$this->semid.'.pdf','D');
    $mpdf->Output();
 
?>
