<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$tipo=$this->tipo;
if ($tipo=='5') { 
    $a="REPORTES MATRICULADOS POR ESCUELA"; 
}   
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
    <div style="margin-bottom:1%; text-align:center;">
        <p><b><?php echo strtoupper($a)?></b></p>
        <h4><b><?php echo strtoupper("periodo - ".$this->perid)?></b></h4>
    </div>
    <table style="width:100%;" border="1" >
        <thead>
            <tr>
                <th>#</th>
                <th>Código</th>
                <th>Apellidos y Nombres</th>
            </tr>
        </thead>
        <?php
        if ($this->data){
            $i=1;
            foreach ($this->data as $datos){    ?>
                <tr>
                    <td style='text-align:center'> <?php print $i?> </td>
                    <td style='text-align:center'> <?php print $datos['uid']?> </td>
                    <td> <?php print strtoupper($datos['last_name0'])." ".strtoupper($datos['last_name1'])." ".$datos['first_name']?> </td> 
                    <?php 
                        if ($tipo=='2') { 
                        ?>
                        <td> <?php print $datos['promedio1']?> </td>
                        <td> <?php print $datos['promedio2']?> </td>
                    <?php }?>
                </tr><?php
                $i++;
            }
        }
    ?>           
    </table>
<?php 

    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,5,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->SetHTMLHeader($this->header);  
    $mpdf->SetHTMLFooter($this->footer);
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Escuela - '.$this->namesc.'.pdf','D');
    // $mpdf->Output();

?>