 <?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start(); 
$tipo=$this->tipo;
$a="REPORTE CANTIDAD MATRICULADOS POR CURSO";
?> 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div style="margin-bottom:1%; text-align:center;">
    <p><b><?php echo strtoupper($a)?></b></p>
    <h4><b><?php echo strtoupper("periodo - ".$this->perid)?></b></h4>
</div>
 <?php 
foreach ($this->semester as $sem){
    $cont=$sem['semid']?>

<table  style="width:100%; font-size: 9px; margin-bottom:3%;" border="1" >
   <thead>
    <tr style=" background:#E5E5E5">
        <th colspan="5"><h4><b> SEMESTRE <?php echo $cont;?>   </b></h4></th>  
    </tr>

    <tr >
        <th style="width:20px;">#</th>
        <!-- <th style="width:20px;">Sem.</th> -->
        <th style="width:20px;">Currícula</th>        
        <th>Curso</th>
        <th style="width:20px;">Turno</th>        
        <th style="width:20px;">Alumnos Matriculados</th>
    </tr>
    </thead>
<?php
$r=0;

if ($this->listacursos){  
    foreach ($this->listacursos as $curso){
        $cursoid=$curso['courseid'];
        $curid=$curso['curid'];
        $perid=$curso['perid'];
        $escid=$curso['escid'];
        $semid=$curso['semid'];       
        $turno =$curso['turno']; 
        $cantidad=$curso['matriculados'];   
          if ($curso['semid']==$cont){  
            $r++;?>    
            <tr >
                <td ><center><?php echo $r?></center></td>                    
                <td ><center><?php echo $curid?></center></td>                
                <td ><?php echo $curso['name']?></td>
                <td ><center><?php echo $turno?></center></td>
                <td ><center><?php echo $cantidad;?></center></td>           
            </tr>
            <?php
            }       
        }
        } 
?>
</table>
<?php }	

    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,5,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;

    $mpdf->setHTMLHeader($this->header);
    $mpdf->setHTMLFooter($this->footer);
  
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    if ($this->espec) {
        $mpdf->Output('Escuela -'.$this->espec.'.pdf','D');
    }
    else{
        $mpdf->Output('Escuela -'.$this->escid.'.pdf','D');
    }
    // $mpdf->Output();
  
?>

