<center><h5 >
  	<strong>FACULTAD DE <?php echo strtoupper($this->facultad)?> - </strong>
  	<strong>ESCUELA DE  <?php echo strtoupper($this->escuela)?> -</strong>
  	<?php if ($this->especialidad){ ?>
  	<strong>ESPECIALIDAD DE  <?php echo strtoupper($this->especialidad)?> -</strong>	
  	<?php }?>
  	<strong>PERIODO <?php echo strtoupper($this->perid)?></strong>
</center></h5>
<div>
	<div class="panel panel-primary">
  	<div class="panel-heading">
		<h5 class="panel-title">
	  	<span class='glyphicon glyphicon-list'></span>
       
 <strong>REPORTE MATRICULADOS POR ESCUELA</strong> 
	  	

	  	<div class='pull-right'>
	  		<a href="#" class='btn btn-xs btn-success'><span class='glyphicon glyphicon-print'></span></a>

	  	</div>
	  </h5>
  	</div><br>
<table class="table  table-condensed table-bordered table-striped" >

        <thead>
          <tr style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #D2F6F9;">
            <th>#</th>
            <th>Codigo</th>
            <th>Apellido y Nombre</th>
           
        </tr>
        </thead>
    <?php
    if ($this->data)
    {
       $i=1;
       foreach ($this->data as $datos)    
        {
          ?>
        <tr>
        <td> <?php print $i?> </td>
        <td> <?php print $datos['uid']?> </td>
        <td> <?php print strtoupper($datos['last_name0'])." ".strtoupper($datos['last_name1'])." ".$datos['first_name']?> </td>
        </tr><?php
        $i++;
        }
    }
    ?>           
    </table>
<div id='det'></div>
	</div>	

</div>
