           <table class="table  table-condensed table-bordered table-striped" >

        <thead>
          <tr style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #D2F6F9;">
            <th>#</th>
            <th>Codigo</th>
            <th>Apellido y Nombre</th>
            <?php
                $tipo=$this->tipo;
             if ($tipo=='2') { ?>
            <th>1º Parcial</th>
            <th>2º Parcial</th>
            
           <?php }?>
           
        </tr>
        </thead>
    <?php
    if ($this->data)
    {
       $i=1;
       foreach ($this->data as $datos)    
        {?>
        <tr>
        <td> <?php print $i?> </td>
        <td> <?php print $datos['uid']?> </td>
        <td> <?php print strtoupper($datos['last_name0'])." ".strtoupper($datos['last_name1'])." ".$datos['first_name']?> </td> 
        <?php if ($tipo=='2') { ?>
        <td> <?php print $datos['promedio1']?> </td>
        <td> <?php print $datos['promedio2']?> </td>
         <?php }?>
        </tr><?php
        $i++;
        }
    }
    ?>           
    </table>