           <table class="table  table-condensed table-bordered table-striped" >

        <thead>
          <tr style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #D2F6F9;">
            <th>#</th>
            <th>Codigo</th>
            <th>Apellido y Nombre</th>
            <?php
                $tipo=$this->tipo;
             if ($tipo=='6') { ?>
            <th>Cursos</th>
            <th>Notas</th>
            <th>Promedio</th>
                      
           <?php }?>
           
        </tr>
        </thead>
    <?php
    if ($this->data)
    {
       $i=1;
       foreach ($this->data as $datos)    
        {
          $where['eid']=$datos['eid'];
          $where['oid']=$datos['oid'];
          $where['escid']=$datos['escid'];
          $where['uid']=$datos['uid'];
          $where['perid']=$datos['perid'];
          ?>
        <tr>
        <td> <?php print $i?> </td>
        <td> <?php print $datos['uid']?> </td>
        <td> <?php print strtoupper($datos['nombrecompleto'])?> </td> 
        <?php if ($tipo=='6') { ?>
         <td>
         <?php $alumno= new Api_Model_DbTable_Registrationxcourse();
               $dataalu= $alumno->_getFilter($where);
               foreach ($dataalu as $dat) {
                 $where1['eid'] = $dat['eid'];
                 $where1['oid'] = $dat['oid'];
                 $where1['escid'] = $dat['escid'];
                 $where1['perid'] = $dat['perid'];
                 $where1['courseid'] = $dat['courseid'];
                 $where1['curid'] = $dat['curid'];
                 $where1['subid'] = $dat['subid'];
                 $cur= new Api_Model_DbTable_Course();
                 $datcur= $cur->_getOne($where1); ?>

                <li><?php echo $datcur['name']; ?></li>

         <?php      }

                ?>
        </td> 
        <td>
         <?php $alumno= new Api_Model_DbTable_Registrationxcourse();
               $dataalu= $alumno->_getFilter($where);
               foreach ($dataalu as $dat) { ?>

                <li><?php echo $dat['notafinal']; ?></li>

         <?php      }

                ?>
        </td> 
         <td>
        <?php 
            $where2['eid']=$datos['eid'];
            $where2['oid']=$datos['oid'];
            $where2['escid']=$datos['escid'];
            $where2['uid']=$datos['uid'];
            $where2['perid']=$datos['perid'];
            $where2['semid']=$this->semid; 
            $where2['curid'] = $dat['curid'];
            $alumnos= new Api_Model_DbTable_Curricula();
            $dataalus= $alumnos->_getPromedioPonderadoXUid($where2);
               foreach ($dataalus as $dat) {
                 $ponderado = $dat['prom_pon'];
                  echo round($ponderado,2); ?></br>

         <?php      } ?>
      </td>

         <?php }?>
        </tr><?php
        $i++;
        }
    }
    ?>           
    </table>