           <table class="table  table-condensed table-bordered table-striped" >

        <thead>
          <tr style="margin-left: 0px;margin-right: 15px; font-size: 12px; background: #428bca; color: #D2F6F9;">
            <th>#</th>
            <th>Codigo</th>
            <th>Apellido y Nombre</th>
            <?php
                $tipo = $this->tipo;
                $tcur = $this->tcur;
             if ($tipo=='2') { 
                if($tcur == 'O')  { ?>
                  <th>1º Parcial</th>
                  <th>2º Parcial</th>           
                  <?php }
             if($tcur == 'C')  { ?>
                 <th>1º Unidad</th>
                 <th>2º Unidad</th>
                 <th>3º Unidad</th>
                 <th>4º Unidad</th>            
           <?php }


         }?>
           
        </tr>
        </thead>
    <?php
    if ($this->data)
    {
       $i=1;
       foreach ($this->data as $datos)    
        {?>
        <tr>
        <td> <?php print $i?> </td>
        <td> <?php print $datos['uid']?> </td>
        <td> <?php print strtoupper($datos['last_name0'])." ".strtoupper($datos['last_name1'])." ".$datos['first_name']?> </td> 
        <?php if ($tipo=='2') {
            if($tcur == 'O')  { ?>
                <td> <?php print $datos['promedio1']?> </td>
                <td> <?php print $datos['promedio2']?> </td>
               <?php }
            if($tcur == 'C')  { ?>
               <td> <?php print $datos['nota4_i']?> </td>
               <td> <?php print $datos['nota9_i']?> </td>
               <td> <?php print $datos['nota4_ii']?> </td>
               <td> <?php print $datos['nota9_ii']?> </td>
                <?php }

       }?>
        </tr><?php
        $i++;
        }
    }
    ?>           
    </table>