<?php
$ldistri =$this->ldistribution;
?>
<div class="menu-botones">
	<div class="pull-left"><h4>Lista Distribuciones</h4></div>
	<div class="pull-right"><a href="/docente/distribution/new" class="btn btn-info">NUEVO</a></div>
</div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed"> 
	<tr>
		<th class="col-md-1">#</th>
		<th class="col-md-1">Periodo</th>
		<th >Numero</th>
		<th class="col-md-2">Fecha Aprobación</th>
		<th class="col-md-1">Estado</th>
		<th class="col-md-3">Operaciones</th>
	</tr>
	<?php 
	if ($ldistri)
	{		
		$i=0;
		foreach ($ldistri as $distri)
		{
		$periodo = $distri['perid'];
		$num = $distri['number'];
		$approv = $distri['dateaccept'];
		$distid = base64_encode($distri['distid']);
		$perid = base64_encode($distri['perid']);
		$state="";
		$state = ($distri['state']=='A')?"class='success'":"";
		$i++; 
	?>
	<tr <?php echo $state;?>>
		<td><?php echo $i;?></td>	
		<td><?php echo $periodo ;?></td>
		<td><?php echo $num;?></td>
		<td><?php echo $approv;?></td>
		<td><?php echo $state;?></td>
		<td><center>
			<a href="/docente/distribution/edit/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>">
			<span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="Modificar"></span>
			</a>
			<a href="/docente/distribution/delete/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>">
			<span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Eliminar"></span>
			</a>
			<a href="/docente/distribution/begin/distid/<?php echo $distid;?>/perid/<?php echo $perid;?>"
				<span class="glyphicon glyphicon-arrow-right" data-toggle="tooltip" title="Cargar Distribución"></span>
			</a>
		
			</center>
		</td>
	</tr>		
	<?php }
	}
	?>
</table>
</div>
<script>
$('.glyphicon').tooltip();

</script>