<div class="col-sm-12">
	<div class="col-sm-4">
		<br><br><br><br><br><br><br><br>
		<h1>Imagen Aqui</h1>
		<br><br><br><br>
	</div>
	<div class="col-sm-8">
		<br><br><br><br>
		<br><br><br><br>
		<h3>Aviso Importante  <span class="glyphicon glyphicon-pencil"></span></h3>
		<br>
		<h4>La prematricula via internet se <b>extendio</b> hasta el dia <b>Miercoles 18 de Septiembre.</b></h4>
		<br>
		<h4>Y la validacion de matricula hasta el dia <b>Viernes 20 de Septiembre.</b></h4>
		
		<br><br>
		<h6 class="pull-right"><b>Oficina de Informatica</b></h6>
	</div>
</div>
