<div class="col-sm-12">
	<div class="col-sm-4">
		<br><br><br><br><br><br><br><br>
		<h1>Imagen Aquí</h1>
		<br><br><br><br>
	</div>
	<div class="col-sm-8">
		<br><br><br><br>
		<br><br><br><br>
		<h3>Aviso Importante  <span class="glyphicon glyphicon-pencil"></span></h3>
		<br>
		<h4>La pre-matricula vía internet se <b>extendió</b> hasta el día <b>Miércoles 18 de Septiembre.</b></h4>
		<br>
		<h4>Y la validación de matrícula hasta el día <b>Viernes 20 de Septiembre.</b></h4>
		
		<br><br>
		<h6 class="pull-right"><b>Oficina de Informática</b></h6>
	</div>
</div>
