<?php
$dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
include_once($dir);
ob_start();   
?>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/print.css">
<div>
    <div style="text-align:left; font-size:12px;"><b>Codigo: </b><?php echo strtoupper($this->uid)?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <b>Alumno: </b><?php echo strtoupper($this->person[0]['last_name0']." ".$this->person[0]['last_name1'].", ".$this->person[0]['first_name'])?>
    </div>
</div>
    <div style="text-align: center; font-size:16px;margin-top:10px"><b> CURRÍCULA </b></div>
    <div style='margin-bottom:20px; margin-top:5px'>
        <img src="/img/circulo-verde.png"><b> Aprobado</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img src="/img/circulo-amarillo.png"><b> Llevando</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img src="/img/circulo-rojo.png"><b> Pendiente</b>
    </div>    
        <?php if($this->courpercur){
            //print_r($this->courpercur);?>
            <?php  
            $semid=0;
            $c=0;
            foreach ($this->courpercur as $sem) {
                if($sem['semid']<>$semid){?>
                    <table class="table" style='width:100%; margin-bottom:20px;'>
                        <tr style='background:#E5E5E5'>
                            <td colspan='7'><center style='font-size:15px'><b>SEMESTRE <?php echo $sem['semid']?></b></center></td>
                        </tr>
                        <tr>
                            <th class='small-70'><center>Código</center></th>
                            <th class='small-400'>Cursos</th>
                            <th class='small-50'><center>Créditos</center></th>
                            <th class='small-100'><center>Tipo</center></th>
                            <th class='small-70'><center>Requisito</center></th>
                            <th class='small-50'>Nota</th>
                            <th class='small-50'>Estado</th>
                        </tr>
                            
                <?php  $semid=$sem['semid'];
                    foreach ($this->courpercur as $courses) {
                        if($courses['semid']==$semid) { ?>
                            <tr>
                                <td align="center"><?php echo $courses['courseid']?></td>
                                <td><?php echo $courses['name']?></td>
                                <td align="center"><?php echo $courses['credits']?></td>
                                <td align="center"><?php if($courses['type']=='O'){
                                                            echo "Obligatorio";
                                                         }else{
                                                            echo "Electivo";
                                                         } ?>
                                </td>
                                <td align="center">
                                    <?php if($sem['semid']<>"1"){
                                        $exreq=0;
                                        for($i=1; $i<=3 ; $i++){
                                            if($courses['req_'.$i]){
                                                echo $courses['req_'.$i]." ";
                                                $exreq=1;
                                            }
                                        }
                                            if($exreq==0){
                                                echo "Ninguno";
                                            }
                                        }?>
                                </td>
                                <td align='center'><!-- Imprimir mayor nota -->
                                    <?php if($this->courlle[$c]){
                                            $notafinal=$this->courlle[$c]['notafinal'];
                                            $turno[$c]=1;
                                            foreach ($this->courlle[$c] as $notaf) {
                                                if($notaf['notafinal']>=$notafinal){
                                                    $notafinal=$notaf['notafinal'];
                                                    $turno[$c]=$notaf["turno"];
                                                    $perid[$c]=$notaf["perid"];
                                                }
                                            }
                                            echo $notafinal;
                                          }else{
                                            $est=1;
                                          }?>
                                </td>
                                <td align='center'>
                                    <?php if($est<>1){
                                            if($notafinal>=11){?>
                                                <img src="/img/circulo-verde.png">
                                            <?php }else{
                                                $pinto=0;
                                                foreach ($this->courlleact as $cact) {
                                                    if($this->courlle[$c][0]['courseid']==$cact['courseid']){
                                                        if($cact['state']=="M"){?>
                                                            <img src="/img/circulo-amarillo.png">
                                                        <?php $pinto=1;
                                                        }else{?>
                                                            <img src="/img/circulo-rojo.png">
                                                        <?php $pinto=1;
                                                        }
                                                    }
                                                }
                                                if($pinto==0){?>
                                                    <img src="/img/circulo-rojo.png">
                                                <?php }
                                            }
                                        }elseif($est==1){
                                            $est=0;?>
                                            <img src="/img/circulo-rojo.png">
                                        <?php } ?>
                                 </td>       
                                </tr>
                                <?php 
                            $c++;
                            }
                        }   ?>
                        </table>
                        <div style="margin-top:20px"></div>
                <?php } ?>
            <?php 
            }   ?>
        <?php 
        }
        else{
            ?>
            <h4 align="center">No Existen Datos</h4>
        <?php 
        }

    
    $html = ob_get_contents();
  
    $mpdf=new mPDF('win-1252','A4','','',15,15,40,18,8,5);
    $mpdf->SetWatermarkImage('/img/undac.png',0.07,'F');
    $mpdf->showWatermarkImage = true;
  
    $mpdf->SetHTMLHeader($this->header);
    $mpdf->SetHTMLFooter($this->footer,'O');  
  
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('Matriculas Por Curricula-'.$this->person[0]['pid'].'.pdf','D');
    // $mpdf->Output();  
?>