<div class="panel panel-default">
	<br>
	<div class="row container">
		<div class="col-md-8">
			<h4 class="text-muted">Ingrese una <span class="text-info">Nueva Institución</span></h4>
		</div>
		<div class="col-md-2">
			<a id="save" href="##" class="btn btn-info form-control">Guardar</a>
		</div>
		<div class="col-md-2">
			<a id="backeditBtn" href="##" class="btn btn-default form-control">Volver</a>
		</div>
	<hr><br>
	<form id="form" action="/profile/public/studentsaveacademic" method="post">
		<table class="table">
			<tr>
				<td><label>Nombre de la Institución</label><?php print $this->form->institution?></td>
				<td><label>Tipo</label><?php print $this->form->type?></td>
			</tr>
			<tr>
				<td><label>Localización: País | Departamento | Provincia | Distrito</label><?php print $this->form->location?></td>
			</tr>
			<tr>
				<td><label>Título</label><?php print $this->form->title?></td>
				<td><label>Año de Finalización</label><?php print $this->form->year_end?></td>
			</tr>
		</table>
	</form>
	</div>
</div><!--Panel Default-->
<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: "POST",
			url: $(this).attr("action"),
			data: $(this).serialize(),
			success: function(data){
				$("#datastudent").html(data);
            	$("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
            	$("#datastudent").fadeOut('fast', function(){
            		$("#datastudent").load('/profile/public/studentacademic', function(){
            			$("#datastudent").fadeIn('fast');
            		});
            	});
			}
		})
		return false;
	})
	
	$('#backeditBtn').click(function (e) {
      	$("#datastudent").fadeOut('fast', function(){
      		$('#datastudent').load('/profile/public/studentacademic', function(){
				$('#datastudent').fadeIn('fast');
			});
      	});
  	})
   
</script>