<div class="panel panel-info">

  <div class="panel-heading">
    <h4>Datos Laborales</h4>
  </div>

  <div class="panel-body">
  	<?php if($this->laboral){
  		foreach ($this->laboral as $lab) {?>
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		    		<h5>
		    			<b>Empresa <?echo $lab['company']?></b>
		    			<a class="pull-right" href="/profile/public/studentremovelaboral/eid/<?echo $this->data["eid"]?>/pid/<?echo $this->data["pid"]?>/lid/<?echo $lab["lid"]?>"><span class="glyphicon glyphicon-remove"></span></a>
		    		</h5>
		    	</div>
		    	<div class="panel-body">
		    		<table class="table">
		    			<tr>
		    				<td>Area <h5><b><?echo $lab['industry']?></b></h5></td>
		    				<td>Condicion <h5><b><?echo $lab['condition']?></b></h5></td>
		    				<td>Salario Mensual <h5><b>S/. <?echo $lab['salary']?></b></h5></td>
		    			</tr>
		    		</table>
		    	</div>
		    </div>
  		<?php }?>

  	<?php }else{?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?}?>
  </div>

</div>
