<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form id="form" action="/profile/public/studenteditlaboral/lid/<?php echo $this->lid?>" method="post">

<div class="col-sm-12">
	<table class="table">
		<tr>
			<td><label>Empresa</label><?php print $this->form->company?></td>
			<td><label>Area</label><?php print $this->form->industry?></td>
		</tr>
		<tr>
			<td><label>Salario Mensual</label><?php print $this->form->salary?></td>
			<td><label>Condición</label><?php print $this->form->condition?></td>
		</tr>
		<tr>
			<td></td>
			<td><a href="##" class="btn btn-info pull-right" id="save">Guardar</a></td>
		</tr>
	</table>
</div>


<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: "POST",
			url: $(this).attr("action"),
			data: $(this).serialize(),
			success: function(data){
				$("#datastudent").html(data);
            	$("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
            	$("#datastudent").fadeOut('fast', function(){
            		$("#datastudent").load('/profile/public/studentlaboral', function(){
            			$("#datastudent").fadeIn('fast');
            		});
            	});
			}
		})
		return false;
	})

	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#datastudent").fadeOut('fast', function(){
      		$('#datastudent').load('/profile/public/studentlaboral', function(){
				$('#datastudent').fadeIn('fast');
			});
      	});
  	})
   
</script>