<br>
<div class="row">
	<div class="col-md-8">
		<h4 class="text-muted">Ingrese una <span class="text-info">Nueva Institución</span></h4>
	</div>
	<div class="col-md-2">
		<a id="save" href="##" class="btn btn-info form-control">Guardar</a>
	</div>
	<div class="col-md-2">
		<a id="backAcademicBtn" href="##" class="btn btn-default form-control">Volver</a>
	</div>
</div>
<hr><br>
<form id="form" action="/profile/public/studentsaveacademic" method="post">
	<div class="row">
		<div class="col-md-8">
			<h5 class="text-muted">Nombre de la Institución</h5>
			<?php echo $this->form->institution ?><br>
		</div>
		<div class="col-md-4">
			<h5 class="text-muted">Tipo</h5>
			<?php echo $this->form->type?><br>
		</div>	
	</div>
	<div class="row">
		<div class="col-md-3">
			<h5 class="text-muted">País</h5>
			<?php echo $this->form->country?><br>
		</div>
		<div class="col-md-3">
			<h5 class="text-muted">Departamento</h5>
			<?php echo $this->form->country_s?><br>
		</div>
		<div class="col-md-3">
			<h5 class="text-muted">Provincia</h5>
			<?php echo $this->form->country_p ?><br>
		</div>
		<div class="col-md-3">
			<h5 class="text-muted">Distrito</h5>
			<?php echo $this->form->country_d?><br>
		</div>	
	</div>	
	<div class="row">
		<div class="col-md-8">
			<h5 class="text-muted">Título</h5>
			<?php echo $this->form->title?><br>
		</div>
		<div class="col-md-4">	
			<h5 class="text-muted">Año de Finalización</h5>
			<?php echo $this->form->year_end?><br>
		</div>	
	</div>
</form>

<script>
	$(function(){
		$("#country_s").attr('disabled','disabled');
		$("#country_p").attr('disabled','disabled');
		$("#country_d").attr('disabled','disabled');

		var veri="<?php echo $this->veri?>";
		if (veri=="1") {
			$('#country_s').removeAttr('disabled');
	        $('#country_p').removeAttr('disabled');
	        $('#country_d').removeAttr('disabled');
			// alert(veri);
			var valor="<?php echo $this->dataubigeo['coid']?>";
			$("#country option[value="+valor+"]").attr("selected",true);
		};

		if (veri=="0") {
			$('#country_s').removeAttr('disabled');
			var valor="PE";
			$("#country option[value="+valor+"]").attr("selected",true);
			var url="/profile/public/countrystate/coid/"+valor;
		 	$("#country_s").load(url);		
		};

		$("#save").click(function(){   
	        var url="/profile/public/studentsaveacademic";
	        $.ajax({
	            url: url,
	            type: 'POST',
	            data:$("#form").serialize(),
	            success: function (data){
	            	$("#editform").html(data);
	            }

	        });
	    });

		$('#backAcademicBtn').click(function(){
	 		$("#editform").addClass('hidden');
	  		$('#datastudent').removeClass('hidden');
	  	});

	  	var clave="<?php echo $this->clave?>";
	    if (clave==1) {
	        $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
			$('#datastudent, #editform').html('');
			$('#datastudent')
				.removeClass('hidden')
				.load('/profile/public/studentacademic', function(){
					$('#loadingDiv').html('');
				});
		};

	  	$("#country").change(function(){
	  		$('#country_s').removeAttr('disabled');
		    var coid=$(this).val();
	    	var url="/profile/public/countrystate/coid/"+coid;
	    	$("#country_s").load(url);
	    });

	    $("#country_s").change(function(){
	    	$('#country_p').removeAttr('disabled');
		    var cosid=$(this).val();
	    	var url="/profile/public/countryprovince/cosid/"+cosid;
	    	$("#country_p").load(url);
	    });

	    $("#country_p").change(function(){
	    	$('#country_d').removeAttr('disabled');
		    var proid=$(this).val();
	    	var url="/profile/public/countrydistrict/proid/"+proid;
	    	$("#country_d").load(url);
	    });
	});
</script>