<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form action="/profile/public/studenteditinfo" method="post" id="form">
<div class="col-sm-12">
	<h4>Informacion Principal</h4>
	<table class="table">
		<tr>
			<td><label>DNI </label><br><?php print $this->form->numdoc?></td>
			<td><label>Fecha de Nacimiento </label><br>
				<div class="row">
					<div class="col-sm-4">
						<?php print $this->form->year?>
					</div>
					<div class="col-sm-4">
						<?php print $this->form->month?>
					</div>
					<div class="col-sm-4">
						<?php print $this->form->day?>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td><label>Sexo <?php print $this->form->sex;?></label></td>
			<td><label>Estado Civil <?php print $this->form->civil;?></label></td>
		</tr>
		<tr>
			<td><label>E-mail </label><br><?php print $this->form->mail_person?></td>
			<td><label>E-mail de Trabajo </label><br><?php print $this->form->mail_work?></td>
		</tr>
		<tr>
			<td><label>Telefono Fijo </label><br><?php print $this->form->phone?></td>
			<td><label>Celular </label><br><?php print $this->form->cellular?></td>
		</tr>
		<tr>
			<td></td>
			<td><a href="#" id="save" class="btn btn-info pull-right">Guardar</a></td>
		</tr>
	</table>
</div>

<script>
	$("#save").click(function(){
		$("#form").submit()
	})



	$("#form").submit(function(){
		$.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function(data){ 
            	$("#editform").html(data);
       	   	}
        }); 
        return false;
	})

	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#editdata").removeClass("hidden")
      	$('#editpalBtns a:last').tab('show')
  	})
   
</script>