<div class="panel panel-info">
  <div class="panel-heading">
    <h2>Datos Familiares</h2>
  </div>

  <div class="panel-body">
    <table class="table">
    	<tr>
    		<td><h5>Nombre</h5></td>
    		<td><h5>DNI</h5></td>
    	</tr>
    	<tr>
    		<td><h5>Sex</h5></td>
    		<td><h5>Ocupacion</h5></td>
    	</tr>
    	<tr>
    		<td><h5>Vive?</h5></td>
    		<td><h5>Fecha de Nacimiento</h5></td>
    	</tr>
    	<tr>
    		<td><h5>Telefono/Celular</h5></td>
    		<td><h5>Direccion</h5></td>
    	</tr>
    </table>
  </div>

</div>
