<div class="row">
<div class="col-sm-9">
<div id="maininfo">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-1"><br></div>
      <div class="col-sm-10">
      <table class="table">
        <tr>
          <td>DNI <h5><b><?php echo $this->datos[3]['numdoc']?></b></h5></td>
          <td>Fecha de Nacimiento <h5><b><?php echo $this->datos[3]['birthday']?></b></h5></td>
        </tr>
        <tr>
          <td>Sexo <h5><b><?php echo $this->datos[3]['sex']?></b></h5></td>
          <td>Estado Civil <h5><b><?php echo $this->datos[3]['civil']?></b></h5></td>
        </tr>
        <tr>
          <td>Mail <h5><b><?php echo $this->datos[3]['mail_person']?></b></h5></td>
          <td>Work Mail <h5><b><?php echo $this->datos[3]['mail_work']?></b></h5></td>
        </tr>
        <tr>
          <td>Telefono <h5><b><?php echo $this->datos[3]['phone']?></b></h5></td>
          <td>Celular <h5><b><?php echo $this->datos[3]['cellular']?></b></h5></td>
        </tr>
      </table>
      </div>
      <div class="col-sm-1"><br></div>
    </div><!-- Row de Informacion Principal -->
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading"><h5>Datos de Ingreso</h5></div>
  <div class="panel-body">
    <div class="col-sm-4">
      <table class="table">
        <tr><td>Año de Ingreso <h5><b><?php echo $this->datos[4]['yearsignin']?></b></h5></td></tr>
        <tr><td>Proceso
          <h5><b>
          <?php if($this->datos[4]['process']=="0"){
            echo "Examen Extraordinario";
          }elseif($this->datos[4]['process']=="1"){
            echo "Centro Pre I";
          }elseif($this->datos[4]['process']=="2"){
            echo "Examen Ordinario 1er Periodo";
          }elseif($this->datos[4]['process']=="3"){
            echo "Profesionalizacion Docente";
          }elseif($this->datos[4]['process']=="4"){
            echo "Examen Ordinario 2do Periodo";
          }elseif($this->datos[4]['process']=="5"){
            echo "Centro Pre II";
          }elseif($this->datos[4]['process']=="6"){
            echo "Profesionalizacion Docente Enfermeria";
          }elseif($this->datos[4]['process']=="7"){
            echo "Complementacion Docente";
          }elseif($this->datos[4]['process']=="8"){
            echo "Escuela Post-Grado";
          }elseif($this->datos[4]['process']=="9"){
            echo "Centro Pre III";
          }?>
          </b></h5>
        </td></tr>
        <tr><td>Hara Traslado?
          <h5><b>
          <?php if($this->datos[4]['traslate']=="S"){
              echo "Si";
            }else{
              echo "No";
            }?> 
          </b></h5>
        </td></tr>
        <tr><td>La Carrera es de su Agrado?
          <h5><b>
          <?php if($this->datos[4]['eligio_carrera']=="S"){
              echo "Si";
            }else{
              echo "No";
            }?> 
          </b></h5>
        </td></tr>
      </table>
    </div>

    <div class="col-sm-4">
      <table class="table">
        <tr><td>Posicion <h5><b><?php echo $this->datos[4]['position']?></b></h5></td></tr>
        <tr><td>Modalidad
          <h5><b>
          <?php if($this->datos[4]['mod_signin']=="1"){
            echo "Exoneracion";
          }elseif($this->datos[4]['mod_signin']=="2"){
            echo "Convenio";
          }elseif($this->datos[4]['mod_signin']=="3"){
            echo "Concurso Admision";
          }elseif($this->datos[4]['mod_signin']=="4"){
            echo "Cobertura";
          }elseif($this->datos[4]['mod_signin']=="5"){
            echo "Segunda Opcion";
          }elseif($this->datos[4]['mod_signin']=="6"){
            echo "Traslado Externo";
          }elseif($this->datos[4]['mod_signin']=="7"){
            echo "Traslado Interno";
          }elseif($this->datos[4]['mod_signin']=="8"){
            echo "Segunda Carrera";
          }elseif($this->datos[4]['mod_signin']=="9"){
            echo "Otros";
          }?>
          </b></h5>
        </td></tr>
        <tr><td>Dedicacion a la Universidad <h5><b><?php echo $this->datos[4]['horas_permanece']." "?>Horas</b></h5></td></tr> 
        <tr><td>
          <?php if($this->datos[4]['eligio_carrera']=="N"){?>
            Carrera de Preferencia
            <h5><b><?php echo $this->datos[4]['carrera_preferencia']?></b></h5>
          <?php }?>
        </td></tr>     
      </table>
    </div>

    <div class="col-sm-4">
      <table class="table">
        <tr><td>Puntos <h5><b><?php echo $this->datos[4]['point_signin']?></b></h5></td></tr>
        <tr><td>Preparacion
          <h5><b>
          <?php if($this->datos[4]['tipo_prepa_uni']=="A"){
            echo "Autoestudio";
          }elseif($this->datos[4]['tipo_prepa_uni']=="D"){
            echo "Academias";
          }elseif($this->datos[4]['tipo_prepa_uni']=="C"){
            echo "Cepre";
          }elseif($this->datos[4]['tipo_prepa_uni']=="O"){
            echo "Otros";
          }?> 
          </b></h5>
        </td></tr>
        <tr><td>Por que Undac? <h5><b><?php echo $this->datos[4]['xq_undac']?></b></h5></td></tr>
      </table>
    </div>  
  </div><!-- panel body -->
</div><!--panel danger -->
</div><!-- main info -->

<div id="datastudent"></div>
<div id="editform"></div>

<div class="col-sm-9" align="center" id="editdata"><!-- Botones para Editar los datos -->
  <br><br>
  <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <table class="table">
            <tr>
                <th>Editar</th>
            </tr>
            <td>
                <ul class="nav nav-pills nav-stacked" id="editpalBtns">
                    <li><a href="#" id="editmaininfo" class="btn btn-block"><h5>Informacion Principal</h5></a></li>
                    <li><a href="" id="editacademic" class="btn btn-block"><h5>Datos Academicos</h5></a></li>
                     <li class="hidden"><a></a></li>
                </ul>
            </td>
            <td>
                <ul class="nav nav-pills nav-stacked" id="editpalBtns2">
                    <li><a href="" id="editfamily" class="btn btn-block"><h5>Familia</h5></a></li>
                    <li><a href="" id="" class="btn btn-block"><h5>Datos Estadisticos</h5></a></li>
                    <li class="hidden"><a></a></li>
                </ul>
            </td>
        </table>
    </div>
    <div class="col-sm-3"></div>
</div>

</div><!-- div col 9 -->

<div class="col-sm-3">
  <br>
  <ul class="nav nav-pills nav-stacked" id="backprofileTab">
    <li><a href="#" id="btnprofile">Volver al Perfil</a></li>
  </ul>
  <br>
  <ul class="nav nav-pills nav-stacked" id="masinfoTab">
    <li><a href="#" id="btnfamily" class="btn-xs">Familia</a></li>
    <li><a href="#" id="btnacademic" class="btn-xs">Datos Academico</a></li>
    <li><a href="#" id="btnstadistic" class="btn-xs">Datos Estadistico</a></li>
    <li><a href="#" id="btnlaboral" class="btn-xs">Datos Laborales</a></li>
    <li><a href="#" id="btninters" class="btn-xs">Intereses</a></li>
    <li class="hidden"><a></a></li>
  </ul>
  <br>
  <ul class="nav nav-pills nav-stacked" id="editprofileTab">
    <li><a href="#" id="btneditdata">Actualizar Perfil</a></li>
    <li class="hidden"><a></a></li>
  </ul>
</div>
</div><!-- div row -->

<script>
  $("#btnprofile").addClass("hidden")
  $("#editdata").addClass("hidden")

  $('#masinfoTab a').click(function (e) {
    e.preventDefault()
    $("#maininfo").addClass("hidden")
    $('#editprofileTab a:last').tab('show')
    $('#editpalBtns a:last').tab('show')
    $('#editpalBtns2 a:last').tab('show')
    $("#datastudent").removeClass("hidden")
    $("#editdata").addClass("hidden")
    $("#editform").html("")
    $("#btnprofile").removeClass("hidden")
    $(this).tab('show')
  })

  $('#backprofileTab a').click(function (e) {
    e.preventDefault()
    $("#editdata").addClass("hidden")
    $("#editform").html("")
    $('#masinfoTab a:last').tab('show')
    $('#editpalBtns a:last').tab('show')
    $('#editpalBtns2 a:last').tab('show')
    $('#editprofileTab a:last').tab('show')
  })

  $('#editprofileTab a').click(function (e) {
    e.preventDefault()
    $("#btnprofile").removeClass("hidden")
    $('#masinfoTab a:last').tab('show')
    $("#maininfo").addClass("hidden")
    $("#datastudent").html("")
    $("#editdata").removeClass("hidden")
    $(this).tab('show')
  })


  $("#btnfamily").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentfamily");
  })

  $("#btnacademic").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentacademic");
  })

  $("#btnstadistic").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentstatistic");
  })

  $("#btnlaboral").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentlaboral");
  })

  $("#btninters").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentinterest");
  })

  $("#btnprofile").click(function(){
    $("#datastudent").addClass("hidden")
    $("#maininfo").removeClass("hidden")
    $("#btnprofile").addClass("hidden")
  })

  //Editar Informacion

  $('#editpalBtns a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
  $('#editpalBtns2 a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })

 

  $("#editmaininfo").click(function(){
    $("#editdata").addClass("hidden")
    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#editform").load("/profile/public/studenteditinfo")
  })

  $("#editfamily").click(function(){
    $("#editdata").addClass("hidden")
    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#editform").load("/profile/public/studentsavefamily")
  })

  $("#editacademic").click(function(){
    $("#editdata").addClass("hidden")
    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#editform").load("/profile/public/studentsaveacademic")
  })

</script>