<div class="panel panel-default">
	<br>
	<div class="row container">
		<div class="col-md-8">
			<h4 class="text-muted">Ingrese una <span class="text-info">Nueva Institución</span></h4>
		</div>
		<div class="col-md-2">
			<a id="save" href="##" class="btn btn-success form-control">Guardar</a>
		</div>
		<div class="col-md-2">
			<a id="backAcademicBtn" href="##" class="btn btn-default form-control">Volver</a>
		</div>
	<hr><br>
	<form id="form" action="/profile/public/studentsaveacademic" method="post">
		<div class="row container">
			<div class="col-md-8">
				<h5 class="text-muted">Nombre de la Institución</h5>
				<?php echo $this->form->institution ?><br>
			</div>
			<div class="col-md-4">
				<h5 class="text-muted">Tipo</h5>
				<?php echo $this->form->type?><br>
			</div>	
		</div>
		<div class="row container">
			<div class="col-md-3">
				<h5 class="text-muted">País</span></h5>
				<?php echo $this->form->country?><br>
			</div>
			<div class="col-md-3">
				<h5 class="text-muted">Departamento</span></h5>
				<?php echo $this->form->country_s?><br>
			</div>
			<div class="col-md-3">
				<h5 class="text-muted">Provincia</span></h5>
				<?php echo $this->form->country_p ?><br>
			</div>
			<div class="col-md-3">
				<h5 class="text-muted">Distrito</span></h5>
				<?php echo $this->form->country_d?><br>
			</div>	
		</div>	
		<div class="row container">
			<div class="col-md-8">
				<h5 class="text-muted">Título</h5>
				<?php echo $this->form->title?><br>
			</div>
			<div class="col-md-4">	
				<h5 class="text-muted">Año de Finalización</h5>
				<?php echo $this->form->year_end?><br>
			</div>	
		</div>
		<!-- <table class="table">
			<tr>
				<td><label>Nombre de la Institución</label><?php print $this->form->institution?></td>
				<td><label>Tipo</label><?php print $this->form->type?></td>
			</tr>
			<tr>
				<td><label>Localización: País | Departamento | Provincia | Distrito</label><?php print $this->form->location?></td>
			</tr>
			<tr>
				<td><label>Título</label><?php print $this->form->title?></td>
				<td><label>Año de Finalización</label><?php print $this->form->year_end?></td>
			</tr>
		</table> -->
	</form>
	</div>
</div><!--Panel Default-->
<script>
	$("#country_s").attr('disabled','disabled');
	$("#country_p").attr('disabled','disabled');
	$("#country_d").attr('disabled','disabled');

	var veri="<?php echo $this->veri?>";
	if (veri=="1") {
		$('#country_s').removeAttr('disabled');
        $('#country_p').removeAttr('disabled');
        $('#country_d').removeAttr('disabled');
		// alert(veri);
		var valor="<?php echo $this->dataubigeo['coid']?>";
		$("#country option[value="+valor+"]").attr("selected",true);
		// var url="/profile/public/countrystate/coid/"+valor;
	 // 	$("#country_s").load(url);

	 // 	var valors="<?php echo $this->dataubigeo['cosid']?>";
		// $("#country_s option[value="+valors+"]").attr("selected",true);
		// var url="/profile/public/countryprovince/cosid/"+valors;
	 // 	$("#country_p").load(url);
	};

	if (veri=="0") {
		$('#country_s').removeAttr('disabled');
		// alert(veri);
		var valor="PE";
		$("#country option[value="+valor+"]").attr("selected",true);
		var url="/profile/public/countrystate/coid/"+valor;
	 	$("#country_s").load(url);		
	};

	$("#save").click(function(){   
        var url="/profile/public/studentsaveacademic";
        $.ajax({
            url: url,
            type: 'POST',
            data:$("#form").serialize(),
            success: function (data){
            	$("#datastudent").html(data);
            }

        });
    });

	// $("#save").click(function(){
	// 	$("#form").submit()
	// })
	// $("#form").submit(function(){
	// 	$.ajax({
	// 		type: "POST",
	// 		url: $(this).attr("action"),
	// 		data: $(this).serialize(),
	// 		success: function(data){
	// 			$("#datastudent").html(data);
 //            	$("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
 //            	$("#datastudent").fadeOut('fast', function(){
 //            		$("#datastudent").load('/profile/public/studentacademic', function(){
 //            			$("#datastudent").fadeIn('fast');
 //            		});
 //            	});
	// 		}
	// 	})
	// 	return false;
	// })
	
	$('#backAcademicBtn').click(function(){
 		$('#editform').addClass('hidden');
 		$("#datastudent").fadeOut('fast', function(){
			$("#datastudent").load('/profile/public/studentacademic', function(){
				$("#datastudent").fadeIn('fast');
			});
		});
  	});

  	var clave="<?php echo $this->clave?>";
    if (clave==1) {
        $("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
        $("#datastudent").fadeOut('fast', function(){
	        $("#datastudent").load('/profile/public/studentacademic', function(){
	        	$("#datastudent").fadeIn('fast');
    			$('#loadingDiv').addClass('hidden');
	        });
        });
	};
  //   	$('#editform').addClass('hidden');
  //   	$("#info").fadeOut('fast', function(){
		// 	$("#info").load('/profile/public/studentacademic', function(){
		// 		$("#info").fadeIn('fast');
		// 	});
		// });    	
    // };
	
	// $('#backeditBtn').click(function (e) {
 //      	$("#datastudent").fadeOut('fast', function(){
 //      		$('#datastudent').load('/profile/public/studentacademic', function(){
	// 			$('#datastudent').fadeIn('fast');
	// 		});
 //      	});
 //  	})

  	$("#country").change(function(){
  		$('#country_s').removeAttr('disabled');
	    var coid=$(this).val();
    	var url="/profile/public/countrystate/coid/"+coid;
    	$("#country_s").load(url);
    });

    $("#country_s").change(function(){
    	$('#country_p').removeAttr('disabled');
	    var cosid=$(this).val();
    	var url="/profile/public/countryprovince/cosid/"+cosid;
    	$("#country_p").load(url);
    });

    $("#country_p").change(function(){
    	$('#country_d').removeAttr('disabled');
	    var proid=$(this).val();
    	var url="/profile/public/countrydistrict/proid/"+proid;
    	$("#country_d").load(url);
    });
   
</script>