<div class="panel panel-default">
	<div class="panel-heading">
		<h4><b>Matriculas Realizadas</b></h4>
	</div>
	<div class="panel-body">

		<?if($this->namper){
			print_r($this->courname);?>
		<div class="panel panel-default">
			<?$c=0;
			foreach ($this->namper as $namper) {?>
			<div class="panel-heading">
				<?echo $namper[0]['name'];?>
			</div>
				
			<div class="panel-body">	
				<table class="table">
					<tr>
						<th>Cursos</th>
					</tr>
				<?foreach ($this->courname[$c] as $cour) {?>
					<tr>
						<td><?echo $cour[0]['name']?></td>
					</tr>
				<?}?>
				</table>
			</div>
			<?$c++;
			}?>


		</div>
		<?}?>
	</div
</div>