<div class="panel panel-info">
  <div class="panel-heading">
    <h4>Datos Familiares</h4>
  </div>

  <div class="panel-body">
    <?php if($this->famdata){
    	$c=0;?>
    	<?php foreach ($this->famdata as $fam) {?>
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			Nombre <h5><b><?php echo $fam[0]['lastname']." ".$fam[0]['firtsname']?></b></h5>
  			</div>
    		<div class="panel-body">
    		<table class="table">
		    	<tr>
		    		<td>Parentesco
		    		<h5><b>
		    		<?php if($this->famrel[$c]['type']=="PA"){
		    			echo "Padre";
		    		}elseif($this->famrel[$c]['type']=="MA"){
						echo "Madre";
		    		}elseif($this->famrel[$c]['type']=="HI"){
						echo "Hijo/a";
		    		}elseif($this->famrel[$c]['type']=="HE"){
						echo "Hermano/a";
		    		}
		    		$c++;?>
		    		</b></h5>
		    		</td>
		    		<?php if($fam[0]['typedoc']=="D"){?>
		    			<td>DNI <h5><b><?php echo $fam[0]['numdoc']?></b></h5></td>
		    		<?php }else{?>
						<td>Pasaporte <h5><b><?php echo $fam[0]['numdoc']?></b></h5></td>
		    		<?php }?>
		    	</tr>
		    	<tr>
		    		<td>Fecha de Nacimiento <h5><b><?php echo $fam[0]['birthday']?></b></h5></td>
		    		<td id="live">
		    			Vive?
		    			<h5><b>
		    			<?php if($fam[0]['live']=="S"){
		    				echo "Si";
		    			}else{
							echo "No";
		    			}?>
		    			</b></h5>
		    		</td>
		    	</tr>
		    	<tr id="moreinfo1">
		    		<td>Apoderado? <h5><b>
		    			<?php if($this->famrel[0]['assignee']=="S"){
		    				echo "Si";
		    			}else{
							echo "No";
		    			}?>
		    			</b></h5></td>
		    		<td>Telefono/Celular <h5><b><?php echo $fam[0]['phone']?></b></h5></td>
		    	</tr>
		    	<tr id="moreinfo2">
		    		<td>Direccion <h5><b><?php echo $fam[0]['address']?></b></h5></td>
		    		<td>Ocupacion <h5><b><?php echo $fam[0]['ocupacy']?></b></h5></td>
		    	</tr>
    		</table>

    		</div>
		</div>
		<script>
			var live="<?echo $fam[0]['live']?>"
			if(live=="N"){
				$("#moreinfo1").addClass("hidden")
				$("#moreinfo2").addClass("hidden")
			}
		</script>
		<?php }?>
    <?php }else{?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?}?>
  </div>

</div>

