<ul class="nav nav-pills nav-stacked" id="backFamilyBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form id="form" action="/profile/public/studentsavefamily" method="post">

<div class="col-sm-12">
	<h4>Agregar Familiar</h4>
	<table class="table">
		<tr>
			<td><label>Parentesco</label><?php print $this->form->type?></td>
		</tr>
		<tr>
			<td><label>Apellidos </label><br><?php print $this->form->lastname?></td>_
			<td><label>Nombres </label><br><?php print $this->form->firtsname?></td>
		</tr>
		<tr>
			<td><label>Tipo de Documento</label><?php print $this->form->typedoc?></td>
			<td><label>Num Documento</label><br><?php print $this->form->numdoc?></td>
		</tr>
		<tr>
			<td><label>Fecha de Nacimiento</label><br>
				<div class="row">
					<div class="col-sm-4">
						<?php print $this->form->year?>
					</div>
					<div class="col-sm-4">
						<?php print $this->form->month?>
					</div>
					<div class="col-sm-4">
						<?php print $this->form->day?>
					</div>
				</div></td>
			<td id="sex"><label>Sexo</label><?php print $this->form->sex?></td>
		</tr>
		<tr>
			<td><label>Vive?</label><?php print $this->form->live?></td>
		</tr>
	</table>
	<table class="table" id="moreinfo">
	<?php if ($this->assignee == 0): ?>
		<td><label>Esta persona es su Apoderado/a? </label><?php print $this->form->assignee?></td>
	<?php endif ?>
		<tr>
			<td><label>Dirección</label><?php print $this->form->address?></td>
			<td><label>Telefono/Celular</label><br><?php print $this->form->phone?></td>
		</tr>
		<tr>
			<td><label>Ocupacion</label><br><?php print $this->form->ocupacy?></td>
			<td><label>Sufre de Alguna Enfermedad?</label><?php print $this->form->health?></td>
		</tr>
	</table>
	<tr>
		<td></td>
		<td><a class="btn btn-info pull-right" href="#" id="save">Guardar</a></td>
	</tr>
			
</div>

<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: "POST",
			url: $(this).attr("action"),
			data: $(this).serialize(),
			success: function(data){
				$("#editform").html(data);
				$('#editform').html("");
				$("#datastudent").load("/profile/public/studentfamily");
				$('#datastudent').removeClass('hidden');
			}
		})
		return false;
	})

	$("#type").change(function(){
		$("#type option:selected").each(function(){
			var vartype=$(this).val()
			if(vartype=="PA" || vartype=="MA"){
				$("#sex").addClass("hidden")
			}else{
				$("#sex").removeClass("hidden")
			}
		})
	})


	$("#moreinfo").addClass("hidden")
	$("#live").change(function(){
		$("#live option:selected").each(function(){
			var varlive=$(this).val()
			if(varlive=="S"){
				$("#moreinfo").removeClass("hidden")
			}else{
				$("#moreinfo").addClass("hidden")
			}
		})
	})
	
	$('#backFamilyBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#datastudent").removeClass("hidden")
  	})
   
</script>