<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<h4 class="text-muted">Editar <span class="text-info">Informacion Principal</span></h4><br>
<form id="form">
	<div class="row">
		<div class="col-md-6">
			<h5 class="text-muted">Tipo de Documento</h5>
			<?php echo $this->form->typedoc ?><br>

			<h5 class="text-muted">Fecha de Nacimiento</h5>
			<div class="row">
				<div class="col-md-4"><?php print $this->form->year ?></div>
				<div class="col-md-4"><?php print $this->form->month ?></div>
				<div class="col-md-4"><?php print $this->form->day ?></div>
			</div><br>
			
			<h5 class="text-muted">Email Personal</h5>
			<?php echo $this->form->mail_person ?><br>

			<h5 class="text-muted">Celular</h5>
			<?php echo $this->form->cellular ?>	
		</div>
		<div class="col-md-6">
			<h5 class="text-muted">Numero de Documento</h5>
			<?php echo $this->form->numdoc?><br>
		
			<div class="row">
				<div class="col-md-6">
					<h5 class="text-muted">Sexo</h5>
					<?php echo $this->form->sex?>
				</div>
				<div class="col-md-6">
					<h5 class="text-muted">Estado Civil</h5>
					<?php echo $this->form->civil?>
				</div>
			</div><br>

			<h5 class="text-muted">Email de Trabajo</h5>
			<?php echo $this->form->mail_work ?><br>

			<h5 class="text-muted">Telefono Fijo</h5>
			<?php echo $this->form->phone ?><br>

			<input type="submit" value="Guardar" class="btn btn-info pull-right"></td>
		</div>
	</div>
</form>

<script>
	$('#mail_person, #mail_work').attr('type', 'email');
	$('input').attr('required', 'true');

	$("#save").click(function(){
		$('#form').submit();
	})
	$("#form").submit(function(){
		$.ajax({
	        type: 'POST',
	        url: "/profile/public/studentupdate",
	        data: $(this).serialize(),
	        success: function(data){ 
	        	if (data == 1) {
	        		$("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
	        		$("#datastudent").fadeOut('fast', function(){
	        			$("#datastudent").load('/profile/public/studentinfo', function(){
	        				$("#datastudent").fadeIn('fast');
	        			});
	    			});
	        	}else{
	        		alert("Error!");
	        	}
   	   		}
    	});
        return false;
	})


	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#datastudent").fadeOut('fast', function(){
      		$('#datastudent').load('/profile/public/studentinfo', function(){
				$('#datastudent').fadeIn('fast');
			});
      	});
  	})
   
</script>