<div class="panel panel-info">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h3 class="text-muted"><span class="glyphicon glyphicon-briefcase"> </span> Datos Academicos</h3>
    </div>
    <div class="col-md-2 ">
      <br>
      <a href="#" id="newAcademic" class="btn btn-default" title="Nuevo"><span class="text-muted">Nuevo</span></a>
    </div>
  </div>

  <div class="panel-body">
    <?php 
    if($this->acadata) 
      { 
      foreach ($this->acadata as $academic) 
        { 
        ?>
        <div class="panel panel-warning">
          <div class="panel-body">

            <div class="row">
              <div class="col-md-6">
                <a class="text-muted" id="remove<?php echo $academic['acid']?>" href="#" title="Eliminar"><span class="glyphicon glyphicon-remove"></span></a>
                <script>
                  $("#remove<?php echo $academic['acid']?>").click(function(){
                    bootbox.confirm("Seguro que desea eliminar <?php echo $academic['institution']?>", function(result) {
                        if (result)
                          $("#editform").load("/profile/public/studentremoveacademic/eid/<?php echo $this->data['eid']?>/pid/<?php echo $this->data['pid']?>/acid/<?php echo $academic['acid']?>");
                          $('#editform').html("");
                          $("#datastudent").load("/profile/public/studentacademic");
                      })  
                  })
                </script>
              </div>
              <div class="col-md-1 pull-right">
                <a id="delete<?php echo $academic['acid']?>" class="text-muted" href="#" title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
                  <script>
                    $("#delete<?php echo $academic['acid']?>").click(function(){
                      $("#datastudent").addClass("hidden")
                      $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
                      $("#editform").load("/profile/public/studenteditacademic/acid/<?php echo $academic['acid']?>")
                    })
                  </script>
              </div>
            </div>

            <br>
            <blockquote>
              <h4><?php echo $academic['institution']?> <span class="glyphicon glyphicon-link text-muted"></span> </h4>
            </blockquote>
            <hr class="featurette-divider">

            <div class="row">
              <div class="col-md-4 col-md-offset-2">
                <h4><span class="text-muted">Tipo de Institución </span>
                  <?php echo $fam[0]['numdoc']?>
                    <?php if($academic['type']=="E"){
                      echo "Estatal";
                    }elseif($academic['type']=="P"){
                      echo "Particular";
                    }elseif($academic['type']=="PA"){
                      echo "Parroquial";
                    }?></h4>
                <h4><span class="text-muted">Año de Finalización </span><?php echo $academic['year_end']?></h4>
              </div>
              <div class="col-md-4">
                <h4><span class="text-muted">Nivel de Estudio</span>
                  <?php if($academic['title']=="SE"){
                      echo "Secundaria";
                    }elseif($academic['title']=="SU"){
                      echo "Superior";
                    }elseif($academic['title']=="DI"){
                      echo "Diplomado";
                    }elseif($academic['title']=="PT"){
                      echo "Post Grado";
                    }elseif($academic['title']=="PH"){
                      echo "PHD";
                    }elseif($academic['title']=="O"){
                      echo "Otros";
                    }
                    ?></h4>
                <h4><span class="text-muted">Localización </span></h4>
              </div>
            </div>
          </div>        
        </div>
      <?php }
    }
    else{
    ?>
      <center><h5 class="text-muted">No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?php  
    }
    ?>
  </div>

</div>

<script>
  $("#newAcademic").click(function(){
    $("#datastudent").addClass("hidden")
    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#editform").load("/profile/public/studentsaveacademic")
  })
</script>