<div class="panel panel-info">
  <div class="row">
	<div class="col-md-9 col-md-offset-1">
	  	<h3 class="text-muted"><span class="glyphicon glyphicon-credit-card"></span> Intereses</h3>
	</div>
	<div class="col-md-2 ">
  		<br>
  		<a href="##" id="newInterest" class="btn btn-default" title="Nuevo"><span class="text-muted">Nuevo</span></a>
	</div>
</div>
<hr class="featurette-divider">

<input type="hidden" id="eid" value="<?php echo $this->data['eid'] ?>">
<input type="hidden" id="oid" value="<?php echo $this->data['oid'] ?>">
<input type="hidden" id="pid" value="<?php echo $this->data['pid'] ?>">
  <div class="panel-body">
    <?php if($this->interes){
    	$c=1;
    	$interruptor = 0;?>
    		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-warning">
					<table class="table table-hover">
						<tr>
							<th><h5><strong>#</strong></h5></th>
							<th><h5><strong>Interes</strong></h5></th>
							<th class="text-center"><h5><strong>Dedicación</strong></h5></th>
							<th class="text-center"><h5><strong>Tiene Club?</strong></h5></th>
						</tr>

  					<?php $c = 0;
  					foreach ($this->interes as $int) {?>
						<tr>
							<td><h5><?php echo $c + 1?></h5></td>
							<td><h5><?php echo $int['title']?></h5></td>
							<td align="center"><h5><?php if($int['discipline']=="H"){
									echo "Como Hobby";
								}elseif($int['discipline']=="D"){
									echo "Deportiva";
								}elseif($int['discipline']=="R"){
									echo "Religiosa";
								}else{
									echo "Otros";
									}?></h5></td>
							<td align="center"><h5><?php if($int['club']=="S") {
										echo "Si";
									}else{
										echo "No";
									}
								?></h5></td>
							<td align="center"><h5><a class="text-warning" id="edit<?php echo $int['iid']?>" href="##" title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
			                	<script>
								  $("#edit<?php echo $int['iid']?>").click(function(){
								    $('#datastudent').fadeOut('fast', function(){
										$('#datastudent').load("/profile/public/studenteditinterest/iid/<?php echo $int['iid']?>", function(){
											$('#datastudent').fadeIn('fast');
										});
									});
								  });
								</script></h5></td>
							<td align="center"><h5><a class="text-warning" id="remove<?php echo $int['iid']?>" href="##" title="Eliminar"><span class="glyphicon glyphicon-remove"></span></a>
								<script>
								  $("#remove<?php echo $int['iid']?>").click(function(){
								    bootbox.confirm("Seguro que desea eliminar <?php echo $int['title']?>", function(result) {
								        if (result)
								          $("#editform").load("/profile/public/studentremoveinterest/eid/<?php echo $this->data['eid']?>/pid/<?php echo $this->data['pid']?>/iid/<?php echo $int['iid']?>");
								          $('#editform').html("");
								          $("#datastudent").load("/profile/public/studentinterest");
								      });
								  });
								</script></h5></td>
						</tr>
		  			<?php  $c++;
		  			}?>
					</table>
				</div>
			</div>
			</div>
	</div>
  	<?php }else{?>
      <center><h5>No tiene Datos Por favor Agregue un Interes</h5></center>
    <?php
	}
	?>
</div>


<script>

	$('a').hover(function(){
    	$(this).tooltip('toggle');
  	});
  	
	$("#newInterest").click(function(){
    	$('#datastudent').fadeOut('fast', function(){
			$('#datastudent').load('/profile/public/studentnewinterest', function(){
				$('#datastudent').fadeIn('fast');
			});
		});
  	})

	var eid = $('#eid').val();
	var oid = $('#oid').val();
  	var pid = $('#pid').val();

	$.ajax({
		url : '/profile/public/validatefullprofile',
		data : { 	eid : eid,
					oid : oid,
					pid : pid },
		success: function(data){
			$('#alertCompleteProfile').addClass('hidden');
		},
	});
</script>

