<input type="hidden" id="successProfile" value="<?php echo $this->success ?>">
<div class="row">
  <br>
  <div class="col-md-10">

    <div id="maininfo"></div>

    <div id="loadingDiv"></div>
    
      <div id="datastudent"></div>
    
    <div id="editform" class="panel panel-default"></div>
    

  </div>
  <div class="col-md-2">
    <div id="divBtnProfile" class="panel panel-default">
      <ul class="nav nav-pills nav-stacked" id="backprofileTab">
        <li><a href="##" id="btnProfile">Volver al Perfil</a></li>
      </ul>
    </div>
    <div class="panel panel-default">
      <ul class="nav nav-pills nav-stacked" id="masinfoTab">
        <li><a href="##" id="btnfamily" class="">1. Datos Familiares</a></li>
        <li><a href="##" id="btnacademic" class="">2. Datos Académico</a></li>
        <li><a href="##" id="btnlaboral" class="">3. Datos Laborales</a></li>
        <li><a href="##" id="btnstadistic" class="">4. Datos Estadístico</a></li>
        <li><a href="##" id="btninters" class="">5. Intereses</a></li>
        
        <li class="hidden"><a></a></li>
      </ul>
        <?php 
        $urlPrintFicha = '/profile/public/printficha'.  '/eid/'.$this->dataStudent['eid'].
                                                        '/oid/'.$this->dataStudent['oid'].
                                                        '/pid/'.$this->dataStudent['pid'].
                                                        '/uid/'.$this->dataStudent['uid'].
                                                        '/escid/'.$this->dataStudent['escid'].
                                                        '/subid/'.$this->dataStudent['subid'];
        ?>
      <ul id='printficha' class="nav nav-pills nav-stacked"></ul>
      <!-- <a href="#" class='btn btn-success btn-lg'><span class="glyphicon glyphicon-print"></span> Imprimir Ficha</a> -->
    </div>
        <button id='veri' class="form-class text-center btn btn-success btn-sm" style="width:170px"><span class="glyphicon glyphicon-refresh"></span> Si llenó todo pulse aquí</button>
    <div class="panel panel-default">
      <ul class="nav nav-pills nav-stacked">
      <li class="text-center">
        <a href="##" id="btnpassword" class="">Cambio de contraseña</a>
      </li>
    </ul>  
    </div>
    

  </div>
</div><!-- div row -->




<script>
    $("#printficha").hide();
    var $url ="<?php echo $urlPrintFicha?>";
    var clave="<?php echo $this->clave?>";
    if (clave==1) {
        var state="<?php echo $this->state?>";
            if (state!="C") {
                $('#profileTab li:eq(3) a').tab('show');            
            };
        $("#printficha").show();
        $("#veri").hide();
        $("#printficha").append('<li><a href="<?php echo $urlPrintFicha ?>" class="form-class text-center"><span class="glyphicon glyphicon-print"></span> Imprimir Ficha</a></li>');
    };

    $("#veri").click(function(){
        window.location.reload();
        // var successProfile = $('#successProfile').val();
        // if (successProfile == 'no') {
        
    });

  $("#datastudent").load("/profile/public/studentmaininfo");
  $("#divBtnProfile").fadeOut("fast");


  $('#masinfoTab a').click(function (e) {
    e.preventDefault()
    $('#datastudent').html('');
    $('#datastudent').removeClass('hidden');
    $("#divBtnProfile").fadeIn("fast");
    $("#editform").html("");
    /*$("#datastudent").removeClass("hidden")*/
    $(this).tab('show')
  })

  $('#backprofileTab a').click(function (e) {
    e.preventDefault()
    $('#editform, #datastudent').html('');
    $('#datastudent').removeClass('hidden');
    $('#editform').addClass('hidden');
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $("#datastudent").load("/profile/public/studentmaininfo", function(){
      $('#loadingDiv').html('');
    });
    $('#masinfoTab a:last').tab('show');
    $("#divBtnProfile").fadeOut("fast");
    /*$("#editform").html("")*/
  })


  $("#btnfamily").click(function(){
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $('#datastudent').html('');
    $("#datastudent").load("/profile/public/studentfamily", function(){
      $('#loadingDiv').html('');
    });
  })

  $("#btnacademic").click(function(){
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $('#datastudent').html('');
    $("#datastudent").load("/profile/public/studentacademic", function(){
      $('#loadingDiv').html('');
    });
  })

  $("#btnstadistic").click(function(){
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $('#datastudent').html('');
    $("#datastudent").load("/profile/public/studentstatistic", function(){
      $('#loadingDiv').html('');
    });
  })

  $("#btnlaboral").click(function(){
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $('#datastudent').html('');
    $("#datastudent").load("/profile/public/studentlaboral", function(){
      $('#loadingDiv').html('');
    });
  })

  $("#btninters").click(function(){
    $('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
    $('#datastudent').html('');
    $("#datastudent").load("/profile/public/studentinterest", function(){
      $('#loadingDiv').html('');
    });
  })
  
  $("#btnpassword").click(function(e){
    e.preventDefault()
    $('#masinfoTab a:last').tab('show');
    $("#divBtnProfile").fadeOut("fast");
    $("#datastudent").load("/profile/public/changepassword", function(){
      $('#loadingDiv').html('');
    });
  })

</script>