<link rel="stylesheet" href="/css/profile.css">
<?php
    $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-user"></span> Mi Perfil');
    $this->placeholder('Btnnav')->append('<a href="/alumno" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');
?>
<input type="hidden" id="successProfile" value="<?php echo $this->success ?>">
<!-- <div id="alertCompleteProfile" class="alert alert-danger hidden">
	<h4><span class="glyphicon glyphicon-exclamation-sign"></span> ACTUALIZA TU PERFIL : Información Estadística y Socio-Económica</h4>
	<p>Por favor lee las siguientes instrucciones :</p>
	<ol>
		<li>Para empezar tiene los siguientes datos para rellenar :</li>
		<ul>
			<li>Información Principal <strong>(obligatorio)</strong></li>
			<li>Datos Familiares <strong>(obligatorio)</strong></li>
			<li>Datos Académicos <strong>(obligatorio)</strong></li>
			<li>Datos Estadísticos <strong>(obligatorio)</strong></li>
			<li>Datos Laborales (opcional, si es que ya trabajaste o hiciste prácticas en algun lugar)</li>
			<li>Intereses <strong>(Obligatorio, todo tenemos hobbies)</strong></li>
		</ul>
		<li>En la parte derecha existe todo un <strong>Menú de Navegación</strong> dale click a cualquiera para empezar.</li>
		<li>Ahora, existen <strong>3 botones escenciales </strong> en todo el Perfil que le ayudarán a interactuar con este:</li>
			<ul>
				<li>El boton "Nuevo" <a href="##" class="btn btn-default btn-sm">Nuevo</a>, sirve para <strong>ingresar</strong> nuevos datos.</li>
				<li>El boton "Editar" <span class="glyphicon glyphicon-pencil"></span> que esta representado por un lápiz, sirve para <strong>editar</strong> datos ya existentes.</li>
				<li>Por ultimo el boton "Eliminar" <span class="glyphicon glyphicon-remove"></span>, que obviamente <strong>elimina</strong> datos que considera usted no deberían estar en su perfil.</li>
			</ul>
	</ol>
	<br>
	<p class="pull-right"><a id="btnCompleteProfile" href="##" class="btn btn-default"><span class="text-success">Actualizar Perfil</span></a></p>
	<br><br>
</div> -->

<section class="container">
	<div class="studentProfile_main">
		<figure class="ObO"><img class='img-avatar' src="/fotos/<?php echo $this->datos[0]['uid']?>.jpg" onerror="imgError(this);" alt="Foto de Perfil" align="center" ></figure>
		<div class="ObO dataStudent">
			<p class="fullName"><?php echo $this->datos[0]['fullname']?></p>
			<p>DNI <strong><?php 
								if ($this->datos[0]['numdoc']) {
									echo $this->datos[0]['numdoc'];						
								}
								else{
									echo $this->datos[0]['pid'];
								}
			
			?></strong></p>
			<p>Código <strong><?php echo $this->datos[0]['uid']?></strong></p>
		</div>
		<div class="ObO dataSchool">
			<p>Facultad de <?php echo $this->datos[1][0]['nomfac']?></p>
			<p>Escuela de <?php echo $this->datos[1][0]['nomesc']?></p>
		</div>
		<div class="ObO divRecord">
			<span class="iconSpan glyphicon glyphicon-bookmark"></span>
			<a class="btnRecordNotas" href="/report/recordnotas/print/uid/<?php echo base64_encode($this->datos[0]['uid'])?>/escid/<?php echo base64_encode($this->datos[0]['escid'])?>/eid/<?php echo base64_encode($this->datos[0]['eid'])?>/oid/<?php echo base64_encode($this->datos[0]['oid'])?>/subid/<?php echo base64_encode($this->datos[0]['subid'])?>/pid/<?php echo base64_encode($this->datos[0]['pid'])?>">Record de Notas</a>
		</div>
	</div>
	<?php if ($this->rol=="EG") { ?>
		<div class="studentProfile_buttonsSide">
			<a href="##" class="btnObO btnCurrent" goto="signinCurrent">Matricula Actual</a>
			<a href="##" class="btnObO btnCurricula btnActive" goto="signinCurriculum">Matrículas por Currícula</a>
			<a href="##" class="btnObO btnRealized" goto="signinRealized">Matrículas Realizadas</a>
			<a href="##" class="btnObO btnMoreAboutMe" goto="info">Mas Acerca de Mi</a>
		</div>

		<div class="studentProfile_dataButtonsSide">
			<div id="signinCurrent" class="dataContainer"></div>
			<div id="signinCurriculum" class="dataContainer dataContainerActive"></div>
			<div id="signinRealized" class="dataContainer"></div>
			<div id="info" class="dataContainer"></div>
		</div>

	<?php } elseif($this->rol=="AL") { ?>
		<div class="studentProfile_buttonsSide">
			<a href="##" class="btnObO btnCurrent btnActive" goto="signinCurrent">Matricula Actual</a>
			<a href="##" class="btnObO btnCurricula" goto="signinCurriculum">Matrículas por Currícula</a>
			<a href="##" class="btnObO btnRealized" goto="signinRealized">Matrículas Realizadas</a>
			<a href="##" class="btnObO btnMoreAboutMe" goto="info">Mas Acerca de Mi</a>
		</div>

		<div class="studentProfile_dataButtonsSide">
			<div id="signinCurrent" class="dataContainer dataContainerActive"></div>
			<div id="signinCurriculum" class="dataContainer"></div>
			<div id="signinRealized" class="dataContainer"></div>
			<div id="info" class="dataContainer"></div>
		</div>
	<?php } ?>
</section>


<script>
	function imgError(image) {
		var avatar = '<?php echo $this->avatar_default?>'; 
	    image.onerror = "";
	    image.src = "/img/default_avatar_"+avatar+".jpg";
	    return true;
	}
	$(function () {
		//Actualizar perfil
		/*var successProfile = $('#successProfile').val();
		if (successProfile == 'no') {
			$('#alertCompleteProfile').removeClass('hidden');
	    	$('#profileTab li:eq(3) a').tab('show');
		};
		$('#btnCompleteProfile').click(function(){
			$('html,body').animate({
		        scrollTop: $("#profileTab").offset().top
		    }, 500);
		});*/
		//--------------------------------------------------------------------------------------------------

		//loadData
		$("#signinCurrent").load("/profile/public/studentsigncurrent");

		$('#signinCurriculum').load('/profile/public/studentsignpercur');

	    $("#signinRealized").load("/register/registerealized/index/pid/<?php echo $this->data['pid']?>/uid/<?php echo $this->data['uid']?>/escid/<?php echo $this->data['escid']?>/subid/<?php echo $this->data['subid']?>/perid/<?php echo $this->data['perid']?>/rid/<?php echo $this->data['rid']?>");

		$("#info").load("/profile/public/studentinfo");
		//-------------------------------------------------------------------------------------------------

		//Change Data
		var goTo = '';
		$('.btnObO').on('click', function(){
			$('.btnObO').removeClass('btnActive');
			$(this).addClass('btnActive');
			goTo = $(this).attr('goto');
			$('.dataContainer').removeClass('dataContainerActive');
			$('#' + goTo).addClass('dataContainerActive');
		});
		//---------------------------------------------------
	});
</script>

