<div class="panel panel-default">
	<!-- <div class="panel-heading"> -->
		<!-- <h4><b>Matricula Por Curricula</b></h4> -->
		<div align="right">
			<br>
			<a href="/profile/public/printpercur/" class='btn btn-success btn-lg'><span class='glyphicon glyphicon-print'></span> Imprimir</a>
		</div>
	</br>
	<!-- </div> -->
	<div class="panel-body">
		<div class="row">
			<div class="col-sm-4">
				<center><img src="/img/circulo-verde.png">Aprobado</center>
			</div>
			<div class="col-sm-4">
				<center><img src="/img/circulo-amarillo.png">Llevando</center>
			</div>
			<div class="col-sm-4">
				<center><img src="/img/circulo-rojo.png">Pendiente</center>
			</div>
		</div>
		<br>
		<?php if($this->courpercur){
			//print_r($this->courpercur);?>
		<div class="panel panel-primary">
			<?php  $semid=0;
			$c=0;
			foreach ($this->courpercur as $sem) {
				if($sem['semid']<>$semid){?>
					<div class="panel-heading">
						<b>SEMESTRE <?php echo $sem['semid']?></b>
					</div>
					<div class="panel-body">
						<table class="table">
							<tr>
								<th><center>Codigo</center></th>
								<th>Cursos</th>
								<th><center>Creditos</center></th>
								<th><center>Tipo</center></th>
								<th><center>Requisito</center></th>
								<th class="text-center">Nota</th>
								<th class="text-center">Estado</th>
								<th class="text-center">Sílabo</th>
							</tr>
							
					<?php  $semid=$sem['semid'];
						foreach ($this->courpercur as $courses) {
							if($courses['semid']==$semid) { ?>
								<tr>
									<td class="text-center"><?php echo $courses['courseid']?></td>
									<td><?php echo $courses['name']?></td>
									<td class="text-center"><?php echo $courses['credits']?></td>
									<td class="text-center"><?php if($courses['type']=='O'){
											echo "Obligatorio";
										}else{
											echo "Electivo";
										} ?>
									</td>
									<td class="text-center">
										<?php if($sem['semid']<>"1"){
											$exreq=0;
											for($i=1; $i<=3 ; $i++){
												if($courses['req_'.$i]){
													echo $courses['req_'.$i]." ";
													$exreq=1;
												}
											}
											if($exreq==0){
												echo "Ninguno";
											}
										}?>
									</td>
									<td class="text-center"><!-- Imprimir mayor nota -->
										<?php if($this->courlle[$c]){
											$notafinal=$this->courlle[$c]['notafinal'];
											$turno[$c]=1;
											foreach ($this->courlle[$c] as $notaf) {
												if($notaf['notafinal']>=$notafinal){
													$notafinal=$notaf['notafinal'];
													$turno[$c]=$notaf["turno"];
													$perid[$c]=$notaf["perid"];
												}
											}
										echo $notafinal;
										}else{
											$est=1;
										}?>
									</td>
									<td class="text-center">
										<?php if($est<>1){
											if($notafinal>=11){?>
												<img src="/img/circulo-verde.png">
											<?php }else{
												$pinto=0;
												foreach ($this->courlleact as $cact) {
													if($this->courlle[$c][0]['courseid']==$cact['courseid']){
														if($cact['state']=="M"){?>
															<img src="/img/circulo-amarillo.png">
														<?php $pinto=1;
														}else{?>
															<img src="/img/circulo-rojo.png">
														<?php $pinto=1;
														}
													}
												}
												if($pinto==0){?>
													<img src="/img/circulo-rojo.png">
												<?php }
											}
										}elseif($est==1){
											$est=0;?>
											<img src="/img/circulo-rojo.png">
										<?php }?>
									</td>
									<td class="text-center">
										<?php if($turno[$c]){?>
											<a title="Imprimir Syllabu" href="/syllabus/print/index/courseid/<?php echo base64_encode($courses['courseid'])?>/curid/<?php echo base64_encode($courses['curid'])?>/escid/<?php echo base64_encode($courses['escid'])?>/turno/<?php echo base64_encode($turno[$c])?>/perid/<?php echo base64_encode($perid[$c])?>/subid/<?php echo base64_encode($courses['subid'])?>"><span class="glyphicon glyphicon-book"></span></a>
										<?php }	?>
									</td>
								</tr>
								<?php 
							$c++;
							}
						}	?>
						</table>
					</div>
				<?php }	?>
			<?php 
			}	?>
		</div><!-- Panel de Semestres -->
		<?php 
		}
		else{
			?>
			<h4 class="text-center">No Existen Datos</h4>
		<?php 
		}
		?>
	</div>
</div>