<div class="panel panel-info">

  <div class="panel-heading">
    <h2>Datos Laborales</h2>
  </div>

  <div class="panel-body">
  	<?php if($this->laboral){
  		foreach ($this->laboral as $lab) {?>
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		    		<h4><b><?echo $lab['company']?></b></h4>
		    	</div>
		    	<div class="panel-body">
		    		<table class="table">
		    			<tr>
		    				<th><h5>Area</h5> <h4><b><?echo $lab['industry']?></b></h4></th>
		    				<th><h5>Condicion</h5> <h4><b><?echo $lab['condition']?></b></h4></th>
		    				<th><h5>Salario Mensual</h5> <h4><b>S/. <?echo $lab['salary']?></b></h4></th>
		    			</tr>
		    		</table>
		    	</div>
		    </div>
  		<?php }?>

  	<?php }else{?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?}?>
  </div>

</div>
