<div class="row">
  <div class="col-md-10">

    <div id="maininfo"></div>

    <div id="datastudent"></div>

    <div id="editform"></div>

  </div>
  <div class="col-md-2">
    <br>
    <ul class="nav nav-pills nav-stacked" id="backprofileTab">
      <li><a href="#" id="btnprofile">Volver al Perfil</a></li>
    </ul>
    <br>
    <ul class="nav nav-pills nav-stacked" id="masinfoTab">
      <li><a href="#" id="btnfamily" class="btn-xs">Datos Familiares</a></li>
      <li><a href="#" id="btnacademic" class="btn-xs">Datos Academico</a></li>
      <li><a href="#" id="btnlaboral" class="btn-xs">Datos Laborales</a></li>
      <li><a href="#" id="btnstadistic" class="btn-xs">Datos Estadistico</a></li>
      <li><a href="#" id="btninters" class="btn-xs">Intereses</a></li>
      <li class="hidden"><a></a></li>
    </ul>
  </div>
</div><!-- div row -->




<script>
  $("#maininfo").load("/profile/public/studentmaininfo")
  $("#btnprofile").addClass("hidden")
  $("#editdata").addClass("hidden")

  $('#masinfoTab a').click(function (e) {
    e.preventDefault()
    $("#maininfo").html("")
    $("#datastudent").removeClass("hidden")
    $("#editdata").addClass("hidden")
    $("#editform").html("")
    $("#btnprofile").removeClass("hidden")
    $(this).tab('show')
  })

  $('#backprofileTab a').click(function (e) {
    e.preventDefault()
    $("#editdata").addClass("hidden")
    $("#editform").html("")
    $('#masinfoTab a:last').tab('show')
  })


  $("#btnfamily").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentfamily");
  })

  $("#btnacademic").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentacademic");
  })

  $("#btnstadistic").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentstatistic");
  })

  $("#btnlaboral").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentlaboral");
  })

  $("#btninters").click(function(){
    $("#datastudent").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#datastudent").load("/profile/public/studentinterest");
  })

  $("#btnprofile").click(function(){
    $("#datastudent").addClass("hidden")
    $("#maininfo").load("/profile/public/studentmaininfo")
    $("#btnprofile").addClass("hidden")
  })

</script>