<div class="panel panel-warning">

  <div class="row">
	<div class="col-md-9 col-md-offset-1">
	  	<h3 class="text-muted"><span class="glyphicon glyphicon-list-alt"></span> Datos Estadisticos</h3>
	</div>
	<div class="col-md-2 ">
		<?php if ($this->statistic): ?>
			<h3><a href="##" id="editStatistic" class="text-muted" title="Editar Datos Estadisticos"><span class="glyphicon glyphicon-pencil"></span></a></h3>
		<?php else: ?>
	  		<br>
	  		<a href="##" id="newStatistic" class="btn btn-default" title="Editar"><span class="text-muted">Nuevo</span></a>
		<?php endif ?>
	</div>
</div>
<input type="hidden" id="eid" value="<?php echo $this->dataStudent['eid'] ?>">
<input type="hidden" id="oid" value="<?php echo $this->dataStudent['oid'] ?>">
<input type="hidden" id="pid" value="<?php echo $this->dataStudent['pid'] ?>">

  <div class="panel-body">
  	<?php if($this->statistic){?>
	
	<hr class="featurette-divider">

	
	
	<div class="row">
		<div class="col-md-2">
			<br><br><br>
			<h5 class="text-muted text-right"><strong>Datos Economicos</strong></h5>
		</div>
		<div class="col-md-4">
			<br><br>
			<blockquote>
			<h5><span class="text-muted">Depende Economicamente de </span>
				<?php if($this->statistic["dependencia"]=="P"){
					echo "Padres";
				}elseif($this->statistic["dependencia"]=="SP"){
					echo "Solo Padre";
				}elseif($this->statistic["dependencia"]=="SM"){
					echo "Solo Madre";
				}elseif($this->statistic["dependencia"]=="H"){
					echo "Hermanos";
				}elseif($this->statistic["dependencia"]=="T"){
					echo "Tios";
				}elseif($this->statistic["dependencia"]=="C"){
					echo "Conyuge";
				}elseif($this->statistic["dependencia"]=="O"){
					echo "Otros";
				}elseif($this->statistic["dependencia"]=="N"){
					echo "Ninguno";
				}?></h5>

			<h5><span class="text-muted">Denpenden de Usted? </span>
				<?php if($this->statistic["dependen_ud"]=="S"){
					echo "Si, ".$this->statistic["num_dep_ud"]." personas";
				}else{
					echo "No";
				}?></h5>
			</blockquote>
		</div>

		<div class="col-md-1">
			<br><br><br><br>
			<h5 class="text-muted text-right"><strong>Vivienda</strong></h5>
		</div>
		<div class="col-md-5">
			<blockquote>
			<h5><span class="text-muted">La Vivienda es </span>
				<?php if($this->statistic["vivienda"]=="P"){
					echo "Propia";
				}elseif($this->statistic["vivienda"]=="A"){
					echo "Alquilada";
				}elseif($this->statistic["vivienda"]=="H"){
					echo "Hipotecada";
				}elseif($this->statistic["vivienda"]=="PH"){
					echo "Prestada";
				}elseif($this->statistic["vivienda"]=="O"){
					echo "Otros";
				}?></h5>
			
			<h5><span class="text-muted">Numero de Habitantes </span><?php echo $this->statistic["num_personas"]?></h5>

			<h5><span class="text-muted">Tipo de Vivienda </span>
				<?php if($this->statistic["tipo_vivienda"]=="CI"){
					echo "Casa Independiente";
				}elseif($this->statistic["tipo_vivienda"]=="CA"){
					echo "Campamento";
				}elseif($this->statistic["tipo_vivienda"]=="D"){
					echo "Departamento";
				}elseif($this->statistic["tipo_vivienda"]=="C"){
					echo "Cuarto";
				}elseif($this->statistic["tipo_vivienda"]=="CC"){
					echo "Cuarto Compartido";
				}elseif($this->statistic["tipo_vivienda"]=="O"){
					echo "Otro";
				}?></h5>

			<h5><span class="text-muted">Material </span>
				<?php if($this->statistic["mat_vivienda"]=="NA"){
					echo "Ladrillo o Bloque de Cemento Acabado";
				}elseif($this->statistic["mat_vivienda"]=="NI"){
					echo "Ladrillo o Bloque de Cemento Inconcluso";
				}elseif($this->statistic["mat_vivienda"]=="TA"){
					echo "Adobe o Tapia Acabado";
				}elseif($this->statistic["mat_vivienda"]=="TI"){
					echo "Adobe o Tapia Inconcluso";
				}elseif($this->statistic["mat_vivienda"]=="PA"){
					echo "Precario Acabado";
				}elseif($this->statistic["mat_vivienda"]=="PI"){
					echo "Precario Inconcluso";
				}?></h5>

			<h5><span class="text-muted">Numero de Habitaciones </span><?php echo $this->statistic["num_habitacion"]?></h5>

			<h5><span class="text-muted">Servicio con los que Cuenta </span>
				<?php if($this->statistic["servicios"]=="ALD"){
					echo "Agua, Luz y Desagüe";
				}elseif($this->statistic["servicios"]=="LD"){
					echo "Solo Luz y Desagüe";
				}elseif($this->statistic["servicios"]=="AL"){
					echo "Solo Agua y Luz";
				}elseif($this->statistic["servicios"]=="S"){
					echo "Solo Agua";
				}elseif($this->statistic["servicios"]=="L"){
					echo "Solo Luz";
				}elseif($this->statistic["servicios"]=="N"){
					echo "Ninguno";
				}?></h5>
			</blockquote>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			<br><br><br>
			<h5 class="text-muted text-right"><strong>Personal</strong></h5>
		</div>
		<div class="col-md-5">
			<blockquote>
			<h5><span class="text-muted">Vive con </span>
				<?php if($this->statistic["vive_con"]=="PD"){
					echo "Padres";
				}elseif($this->statistic["vive_con"]=="P"){
					echo "Solo Padre";
				}elseif($this->statistic["vive_con"]=="M"){
					echo "Solo Madre";
				}elseif($this->statistic["vive_con"]=="H"){
					echo "Hermanos";
				}elseif($this->statistic["vive_con"]=="C"){
					echo "Conyugue";
				}elseif($this->statistic["vive_con"]=="P"){
					echo "Parientes";
				}elseif($this->statistic["vive_con"]=="S"){
					echo "Solo";
				}?></h5>

			<h5><span class="text-muted">Lugar de Alimentacion </span>
				<?php if($this->statistic["lugar_alimentacion"]=="CU"){
					echo "Comedor Universitario";
				}elseif($this->statistic["lugar_alimentacion"]=="P"){
					echo "Pensión";
				}elseif($this->statistic["lugar_alimentacion"]=="S"){
					echo "Hogar";
				}elseif($this->statistic["lugar_alimentacion"]=="S"){
					echo "Se Prepara";
				}elseif($this->statistic["lugar_alimentacion"]=="O"){
					echo "Otros";
				}?></h5>

			<h5><span class="text-muted">Costo de Alimentacion </span>S/. <?php echo $this->statistic["costo_alimento"]?></h5>
				
			<h5><span class="text-muted">Tiene Problemas con su Alimentación </span>
				<?php if($this->statistic["prob_alimento"]=="N"){
					echo "Ninguno";
				}elseif($this->statistic["prob_alimento"]=="DP"){
					echo "Sus padres le envian dinero";
				}elseif($this->statistic["prob_alimento"]=="HG"){
					echo "Sus padres no cuentan con dinero";
				}elseif($this->statistic["prob_alimento"]=="AD"){
					echo "Vive muy lejos de la Universidad";
				}elseif($this->statistic["prob_alimento"]=="VP"){
					echo "Sus padres no lo apoyan economicamente";
				}elseif($this->statistic["prob_alimento"]=="O"){
					echo "Otros";
				}?></h5>
			</blockquote>
		</div>
		<div class="col-md-4">
			<br><br><br><br>
			<h4 class="text-right"><span class="text-muted">Conocimiento en Computación</span>
				<?php if($this->statistic["cono_comp"]=="S"){
					echo "Si";
				}else{
					echo "No";
				}?></h4>
		</div>
	</div>
    <?php }
    else{
    	?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?php }?>
  </div>

</div>

<script>
	$('a').hover(function(){
    	$(this).tooltip('toggle');
  	});
  	
	$("#newStatistic").click(function(){
		$('#datastudent').fadeOut('fast', function(){
			$('#datastudent').load('/profile/public/studentnewstatistic', function(){
				$('#datastudent').fadeIn('fast');
			});
		});
	})

	$("#editStatistic").click(function(){
		$('#datastudent').fadeOut('fast', function(){
			$('#datastudent').load('/profile/public/studenteditstatistic', function(){
				$('#datastudent').fadeIn('fast');
			});
		});
	})

	var eid = $('#eid').val();
	var oid = $('#oid').val();
  	var pid = $('#pid').val();

  	$.ajax({
    	url : '/profile/public/validatefullprofile',
	    data : {  	eid : eid,
	    			oid : oid,
	              	pid : pid },
	    success: function(data){
	      	$('#alertCompleteProfile').addClass('hidden');
	    },
  	});
</script>