<div class="panel panel-info">

  <div class="panel-heading">
    <h4>Intereses</h4>
  </div>

  <div class="panel-body">
    <?php if($this->interes){
  		foreach ($this->interes as $int) {?>
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		    		<h5>
		    			<b><?echo $int['title']?></b>
	    				<a class="pull-right" title="Eliminar" href="/profile/public/studentremoveinterest/eid/<?echo $this->data['eid']?>/pid/<?echo $this->data['pid']?>/iid/<?echo $int['iid']?>?>"><span class="glyphicon glyphicon-remove"></span></a>
		    		</h5>
		    	</div>
		    	<div class="panel-body">
		    		<table class="table">
		    			<tr>
		    				<td>Dedicacion <h5><b>
		    					<?if($int['discipline']=="H"){
		    						echo "Hobby";
		    					}elseif($int['discipline']=="D"){
		    						echo "Deportiva";
		    					}elseif($int['discipline']=="R"){
		    						echo "Religiosa";
		    					}else{
		    						echo "Otros";
		    						}?>
		    				</b></h5></td>
		    				<td>Club <h5><b>
		    					<?if($int['club']=="S") {
		    						echo "Si";
		    					}else{
		    						echo "No";
		    					}
		    					?>
		    				</b></h5></td>
		    			</tr>
		    		</table>
		    	</div>
		    </div>
  		<?php }?>
  	<?php }else{?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?}?>
  </div>

</div>
