<br>
<div class="row">
	<div class="col-md-1 col-md-offset-10">
		<a href="/profile/public/printpercur/" class='btn btn-success'><span class='glyphicon glyphicon-print'></span> Imprimir</a>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-3">
				<h4 class="text-center text-muted"><b>Leyenda</b></h4>
			</div>
			<div class="col-md-3">
				<h5 class="text-center text-success"><img src="/img/circulo-verde.png"> Aprobado</h5>
			</div>
			<div class="col-md-3">
				<h5 class="text-center text-danger"><img src="/img/circulo-rojo.png">  Falta/Desaprobado</h5>
			</div>
			<div class="col-md-3">
				<h5 class="text-center text-warning"><img src="/img/circulo-amarillo.png">  Llevando</h5>
			</div>
		</div>
		<br>
		<?php if($this->courpercur){
			//print_r($this->courpercur);?>
		<div class="panel panel-primary">
			<?php  $semid=0;
			$c=0;
			foreach ($this->courpercur as $sem) {
				if($sem['semid']<>$semid){?>
					<div class="panel-heading">
						<b>SEMESTRE <?php echo $sem['semid']?></b>
					</div>
					<div class="panel-body">
						<table class="table table-hover/fotos/<?php echo $this->datos[0]['uid']?>.jpg">
							<tr class="active">
								<th class="text-center col-md-1">Código</th>
								<th class="col-md-4">Cursos</th>
								<th class="text-center col-md-1">Créditos</th>
								<th class="text-center col-md-2">Tipo</th>
								<th class="text-center col-md-1">Requisito</th>
								<th class="text-center col-md-1">Nota</th>
								<th class="text-center col-md-1">Estado</th>
								<th class="text-center col-md-1">Sílabo</th>
							</tr>
							
					<?php  $semid=$sem['semid'];
						foreach ($this->courpercur as $courses) {
							if($courses['semid']==$semid) { ?>
								<tr>
									<td class="text-center"><?php echo $courses['courseid']?></td>
									<td><?php echo $courses['name']?></td>
									<td class="text-center"><?php echo $courses['credits']?></td>
									<td class="text-center"><?php if($courses['type']=='O'){
											echo "Obligatorio";
										}else{
											echo "Electivo";
										} ?>
									</td>
									<td class="text-center">
										<?php if($sem['semid']<>"1"){
											$exreq=0;
											for($i=1; $i<=3 ; $i++){
												if($courses['req_'.$i]){
													echo $courses['req_'.$i]." ";
													$exreq=1;
												}
											}
											if($exreq==0){
												echo "Ninguno";
											}
										}?>
									</td>
									<td class="text-center"><!-- Imprimir mayor nota -->
										<?php if($this->courlle[$c]){
											$notafinal=$this->courlle[$c]['notafinal'];
											$turno[$c]=1;
											foreach ($this->courlle[$c] as $notaf) {
												if($notaf['notafinal']>=$notafinal){
													$notafinal=$notaf['notafinal'];
													$turno[$c]=$notaf["turno"];
													$perid[$c]=$notaf["perid"];
												}
											}
										echo $notafinal;
										}else{
											$est=1;
										}?>
									</td>
									<td class="text-center">
										<?php 
										if($est<>1){
											if($notafinal>=11){
												$img = 'verde';
												$color = 'success';
												$stateCourse = 'Aprobado';
											}else{
												$pinto=0;
												foreach ($this->courlleact as $cact) {
													if($this->courlle[$c][0]['courseid']==$cact['courseid']){
														if($cact['state']=="M"){
															$img = 'amarillo';
															$color = 'warning';
															$stateCourse = 'Llevando';
															$pinto=1;
														}else{
															$img = 'rojo';
															$color = 'danger';
															$stateCourse = 'Desaprobado';
															$pinto=1;
														}
													}
												}
												if($pinto==0){
													$img = 'rojo';
													$color = 'danger';
													$stateCourse = 'Desaprobado';
												}
											}
										}elseif($est==1){
											$est=0;
											$img = 'rojo';
											$color = 'danger';
											$stateCourse = 'Aún No Llevas';
										} ?>
										<span title="<?php echo $stateCourse ?>" class=" text-<?php echo $color ?>"><img src="/img/circulo-<?php echo $img?>.png"></span>
									</td>
									<td class="text-center">
										<?php if($turno[$c]){?>
											<a title="Imprimir Syllabu" href="/syllabus/print/index/courseid/<?php echo base64_encode($courses['courseid'])?>/curid/<?php echo base64_encode($courses['curid'])?>/escid/<?php echo base64_encode($courses['escid'])?>/turno/<?php echo base64_encode($turno[$c])?>/perid/<?php echo base64_encode($perid[$c])?>/subid/<?php echo base64_encode($courses['subid'])?>"><span class="glyphicon glyphicon-book"></span></a>
										<?php }	?>
									</td>
								</tr>
								<?php 
							$c++;
							}
						}	?>
						</table>
					</div>
				<?php }	?>
			<?php 
			}	?>
		</div><!-- Panel de Semestres -->
		<script>
			$('span, a').hover(function(){
				$(this).tooltip('toggle');
			});
		</script>
		<?php 
		}
		else{
			?>
			<h4 class="text-center">No Existen Datos</h4>
		<?php 
		}
		?>
	</div>
</div>