<div class="panel panel-default">
	<br>
	<div class="row container">
		<div class="col-md-8">
			<h4 class="text-muted">Ingrese sus <span class="text-info">Datos Estadisticos</span></h4>
		</div>
		<div class="col-md-2">
			<a id="save" href="##" class="btn btn-info form-control">Guardar</a>
		</div>
		<div class="col-md-2">
			<a id="backeditBtn" href="##" class="btn btn-default form-control">Volver</a>
		</div>
	</div>
		<hr><br>
	<div class="row container">
		<form id="form" action="/profile/public/studentnewinterest" method="post">
			<div class="col-sm-12">
			<h4>Intereses</h4>
				<table class="table">
					<tr>
						<td><label>Dedicación</label><?php print $this->form->discipline?></td>
					</tr>
					<tr>
						<td><label>Nombre</label><?php print $this->form->title?></td>
						<td><label>Tiene Club?</label><?php print $this->form->club?></td>
					</tr>
				</table>
			</div>
		</form>
	</div>
</div>
<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: 'POST',
			url: $(this).attr('action'),
			data: $(this).serialize(),
			success: function(data){
				$("#datastudent").html(data);
            	$("#datastudent").html('<br><br><center><img src="/img/spinner.gif" alt="" /></center>');
            	$("#datastudent").fadeOut('fast', function(){
            		$("#datastudent").load('/profile/public/studentinterest', function(){
            			$("#datastudent").fadeIn('fast');
            		});
            	});
			}
		})
		return false;
	})

	$('#backeditBtn').click(function () {
    	$("#datastudent").fadeOut('fast', function(){
      		$('#datastudent').load('/profile/public/studentinterest', function(){
				$('#datastudent').fadeIn('fast');
			});
      	});
  	})
   
</script>