<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form id="form" action="/profile/public/studenteditinterest/iid/<?php echo $this->iid?>" method="post">
<div class="col-sm-12">
<h4>Intereses</h4>
	<table class="table">
		<tr>
			<td><label>Dedicación</label><?php print $this->form->discipline?></td>
		</tr>
		<tr>
			<td><label>Nombre</label><?php print $this->form->title?></td>
			<td><label>Tiene Club?</label><?php print $this->form->club?></td>
		</tr>
		<tr>
			<td></td>
			<td><a href="#" class="btn btn-info pull-right" id="save">Guardar</a></td>
		</tr>

	</table>
</div>

<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: 'POST',
			url: $(this).attr('action'),
			data: $(this).serialize(),
			success: function(data){
				$("#editform").html(data)
				$('#editform').html('');
				$('#datastudent').removeClass('hidden');
				$('#datastudent').load('/profile/public/studentinterest');
			}
		})
		return false;
	})

	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
    	$("#editform").html("");
      	$("#datastudent").removeClass('hidden');;
  	})
   
</script>