<div class="col-sm-12">
  <div class="col-sm-3">
    <img src="/img/img_03.jpg" title="">
  </div>
  <div class="col-sm-7">
    <h4><?php echo $this->datos[0]['fullname']?></h4>
    <h5>Codigo <?php echo $this->datos[0]['uid']?></h5>
    <h5>Facultad de <?php echo $this->datos[1][0]['nomfac']." Escuela de ".$this->datos[1][0]['nomesc']?></h5>
    </div>
    <div class="col-sm-1">
      <a href="#" class="btn btn-info">Record</a>
    </div>
</div>

