<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form id="form" action="/profile/public/studenteditacademic/acid/<?php echo $this->acid?>" method="post">

<div class="col-sm-12">
	<h4>Informacion Academica</h4>
	<table class="table">
		<tr>
			<td><label>Nombre de la Institucion</label><?php print $this->form->institution?></td>
			<td><label>Tipo</label><?php print $this->form->type?></td>
		</tr>
		<tr>
			<td><label>Localizacion: Pais | Departamento | Provincia | Distrito</label><?php print $this->form->location?></td>
		</tr>
		<tr>
			<td><label>Titulo</label><?php print $this->form->title?></td>
			<td><label>Año de Finalización</label><?php print $this->form->year_end?></td>
		</tr>
		<tr>
			<td></td>
			<td><a id="save" href="##" class="btn btn-info pull-right">Guardar</a></td>
		</tr>
	</table>
</div>

<script>
	$("#save").click(function(){
		$("#form").submit()
	})
	$("#form").submit(function(){
		$.ajax({
			type: 'POST',
			url: $(this).attr('action'),
			data: $(this).serialize(),
			success: function(data){
				$("#editform").html(data);
				$("#editform").html("");
				$("#datastudent").removeClass("hidden");
				$("#datastudent").load("/profile/public/studentacademic");
			}
		})
		return false;
	})

	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#datastudent").removeClass("hidden")
  	})
   
</script>