<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form name="<?php echo $this->form->getName(); ?>" action="/profile/public/studentsaveinterest" method="post" enctype="application/x-www-form-urlencoded">
<div class="col-sm-12">
<h4>Intereses</h4>
	<table class="table">
		<tr>
			<td><label>Dedicación</label><?print $this->form->discipline?></td>
		</tr>
		<tr>
			<td><label>Nombre</label><?print $this->form->title?></td>
			<td><label>Tiene Club?</label><?print $this->form->club?></td>
		</tr>
		<tr>
			<td></td>
			<td><?print $this->form->save?></td>
		</tr>

	</table>
</div>

<script>
	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#editdata").removeClass("hidden")
      	$('#editpalBtns a:last').tab('show')
      	$('#editpalBtns2 a:last').tab('show')
  	})
   
</script>