<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form name="<?php echo $this->form->getName(); ?>" action="/profile/public/studenteditfamily" method="post" enctype="application/x-www-form-urlencoded">

<div class="col-sm-12">
	<h4>Informacion Familiar</h4>
	<table class="table">
		<tr>
			<td><label>Parentesco</label><?php print $this->form->type?></td>
		</tr>
		<tr>
			<td><label>Apellidos </label><br><?php print $this->form->last_name?></td>_
			<td><label>Nombres </label><br><?php print $this->form->first_name?></td>
		</tr>
		<tr>
			<td><label>Tipo de Documento</label><?php print $this->form->typedoc?></td>
			<td><label>Num Documento</label><br><?php print $this->form->numdoc?></td>
		</tr>
		<tr>
			<td><label>Fecha de Nacimiento</label><br><?php print $this->form->birthday?></td>
			<td><label>Sexo</label><?php print $this->form->sex?></td>
		</tr>
		<tr>
			<td><label>Vive?</label><?php print $this->form->live?></td>
		</tr>
	</table>
	<table class="table" id="moreinfo">
		<td><label>Esta persona es su Apoderado/a? </label><?php print $this->form->assignee?></td>
		<tr>
			<td><label>Dirección</label><?php print $this->form->address?></td>
			<td><label>Telefono/Celular</label><br><?php print $this->form->phone?></td>
		</tr>
		<tr>
			<td><label>Ocupacion</label><br><?php print $this->form->ocupacy?></td>
			<td><label>Sufre de Alguna Enfermedad?</label><?php print $this->form->health?></td>
		</tr>
	</table>
	<tr>
		<td></td>
		<td><?php print $this->form->save?></td>
	</tr>
			
</div>

<script>
	$("#moreinfo").addClass("hidden");
	$("#live").change(function(){
		$("#live option:selected").each(function(){
			var livevar=$(this).val();
		if (livevar=="S") {
			$("#moreinfo").removeClass("hidden");
		};
		if (livevar=="N") {
			$("#moreinfo").addClass("hidden");
		};
		})
	})
	
	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#editdata").removeClass("hidden")
      	$('#editpalBtns a:last').tab('show')
      	$('#editpalBtns2 a:last').tab('show')
  	})
   
</script>