<div class="panel panel-info">

  <div class="panel-heading">
    <h2>Datos Estadisticos</h2>
  </div>

  <div class="panel-body">
  	<?if($this->statistic){?>
    <table class="table">
    	<tr>
			<td><h4>Conocimiento en Computacion</h4></td>
		</tr>
    	<tr>
			<td><h4>Depende Economicamente de</h4></td>
			<td><h4>Denpenden de Usted</h4></td>
		</tr>    	
		<tr>
			<td><h4>Vivienda</h4></td>
			<td><h4>Tipo</h4></td>
		</tr>    	
		<tr>
			<td><h4>Tipo de Material</h4></td>
			<td><h4>Numero de Habitaciones</h4></td>
		</tr>
		<tr>
			<td><h4>Servicios</h4></td>
			<td><h4>Personas que Habitan en su Hogar</h4></td>
		</tr>
		<tr>
			<td><h4>Problemas Con la Necesidad de Alimentos</h4></td>
			<td><h4>Lugar de Alimentacion</h4></td>
		</tr>
		<tr>
			<td><h4>Costo Diario de Alimentos</h4></td>
		</tr>
    </table>
    <?php }else{?>
      <center><h5>No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?}?>
  </div>

</div>
