<div class="panel panel-default">
<br>
<div class="row container">
	<div class="col-md-8">
		<h4 class="text-muted">Editar a <span class="text-info"><?php echo $this->nameFamily ?></span></h4>
	</div>
	<div class="col-md-2">
		<a id="save" href="##" class="btn btn-info form-control">Guardar</a>
	</div>
	<div class="col-md-2">
		<a id="backFamilyBtn" href="##" class="btn btn-default form-control">Volver</a>
	</div>
</div>
<hr>
<div class="container">
	<div id="emptyForm" class="alert alert-warning hidden">
		<h4>Asegurese que todo esta en orden</h4>
		<p>No se pudo guardar los datos, asegurese de haber rellenado el formulario correctamente...</p>
	</div>
</div>
<br>
<form id="formFamily">
	<input type="hidden" name="whySend" value="Update">
	<input type="hidden" name="eid" value="<?php echo $this->dataFamiliar['eid'] ?>">
	<input type="hidden" name="pid" value="<?php echo $this->dataFamiliar['pid'] ?>">
	<input type="hidden" name="famid" value="<?php echo $this->dataFamiliar['famid'] ?>">
	<div class="row container">
		<div class="col-md-2">
			<p class="text-muted">Parentesco</p>
			<?php echo $this->form->type?>
		</div>
		<div class="col-md-5">
			<p class="text-muted">Apellidos</p>
			<?php echo $this->form->lastname?>
		</div>
		<div class="col-md-5">
			<p class="text-muted">Nombres</p>
			<?php echo $this->form->firtsname?>
		</div>
	</div>
	<br>
	<div class="row container">
		<div class="col-md-2">
			<p class="text-muted">Tipo de Documento</p>
			<?php echo $this->form->typedoc ?>
		</div>
		<div class="col-md-5">
			<div class="row">
				<div class="col-md-7">
					<p class="text-muted">Número de Documento</p>
					<?php echo $this->form->numdoc ?>
				</div>
				<div class="col-md-5">
					<p class="text-muted">Sexo</p>
					<?php echo $this->form->sex ?>
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<p class="text-muted">Fecha de Nacimientos</p>
			<div class="row">
				<div class="col-md-4">
					<?php echo $this->form->year ?>
				</div>
				<div class="col-md-4">
					<?php echo $this->form->month ?>
				</div>
				<div class="col-md-4">
					<?php echo $this->form->day ?>
				</div>
			</div>
		</div>
	</div>
	<br>
	<hr>
	<div class="row container">
		<div class="col-md-2">
			<p class="text-muted">Vive?</p>
			<?php echo $this->form->live ?>
		</div>
		<div class="col-md-5">
			<p class="text-muted liveOptions">Dirección</p>
			<?php echo $this->form->address ?>
		</div>
		<div class="col-md-5">
			<p class="text-muted liveOptions">Teléfono o Celular</p>
			<?php echo $this->form->phone ?>
		</div>
		<div id="noLive" class="col-md-10 hidden">
			<br>
			<h4 class="text-muted pull-right">:( Lo sentimos mucho.....</h4>
		</div>
	</div>
	<br>
	<div class="row container">
		<div class="col-md-2">
			<p class="text-muted liveOptions">Es tu Apoderado/a?</p>
			<?php echo $this->form->assignee ?>
		</div>
		<div class="col-md-5">
			<p class="text-muted liveOptions">Ocupación</p>
			<?php echo $this->form->ocupacy ?>
		</div>
		<div class="col-md-5">
			<p class="text-muted liveOptions">Sufre de alguna Enfermedad?</p>
			<?php echo $this->form->health ?>
		</div>
	</div>
</form>
<script>
	//Navegación
	var live = $('#live').val();
	if (live == 'N') {
		$('.liveOptions').addClass('hidden');
		$('.liveOptions').val('0');
		$('#assignee, #health').val('N');
		$('#noLive').removeClass('hidden');
	}

	$('#month, #year').change(function(){
		appendDays();
	});


	$('#type').change(function(){
		var type = $(this).val();
		if (type == 'MA') {
			$('#sex').val('F');
			$('#sex').attr('disabled', 'true');
		}else if (type == 'PA'){
			$('#sex').val('M');
			$('#sex').attr('disabled', 'true');
		}else{
			$('#sex').removeAttr('disabled');
		};	
	});

	$('#live').change(function(){
		var live = $(this).val();
		if (live == 'N') {
			$('.liveOptions').addClass('hidden');
			$('.liveOptions').val('0');
			$('#assignee, #health').val('N');
			$('#noLive').removeClass('hidden');
		}else{
			$('.liveOptions').removeClass('hidden');
			$('#noLive').addClass('hidden');
			$('.liveOptions').val('');
			$('#assignee, #health').val('N');
		};
	});

  	$('#backFamilyBtn').click(function(){
      	$("#editform").addClass('hidden');
  		$('#datastudent').removeClass('hidden');
  	})


	//Mandar el Form
	$('#save').click(function(){
		$.ajax({
			type   : 'post',
			url    : '/profile/public/studentsavefamily/',
			data   : $('#formFamily').serialize(),
			success: function(data){
				if (data == 'true') {
					$('#loadingDiv').html('<br><center><img src="/img/spinner.gif" alt="Loading" /></center>');
					$('#datastudent, #editform').html('');
					$('#datastudent').removeClass('hidden');
					$('#datastudent').load('/profile/public/studentfamily', function(){
						$('#loadingDiv').html('');
					});
				}else{
					$('#emptyForm').removeClass('hidden');
				};
			}
		});
	});


	//Funciones
	function appendDays(){
		var year  = $('#year').val();
		var month = $('#month').val();
		var days  = 30;
		if (year && month) {
			$('#day').html('');
			$('#day').append("<option value=''>Día</option>");
			if (month <= 07 && month % 2 != 0) {
				days++;
			}else if (month == 02) {
				days = 28;
				if (year % 4 == 0) {
						days++;
				};
			};
			if (month >= 08 && month % 2 == 0) {
				days++;
			}
			for (var i = 1; i <= days; i++) {
				$('#day').append("<option value=" + i + ">" + i + "</option>");
			};
		};
	}

</script>