<ul class="nav nav-pills nav-stacked" id="backeditBtn">
	<li><a href="#" id="backedit"><h5>Volver</h5></a></li>
</ul>

<form name="<?php echo $this->form->getName(); ?>" action="/profile/public/studentsavefamily" method="post" enctype="application/x-www-form-urlencoded">

<div class="col-sm-12">
	<h4>Agregar Familiar</h4>
	<table class="table">
		<tr>
			<td><label>Parentesco</label><?print $this->form->type?></td>
		</tr>
		<tr>
			<td><label>Apellidos </label><br><?print $this->form->lastname?></td>_
			<td><label>Nombres </label><br><?print $this->form->firtsname?></td>
		</tr>
		<tr>
			<td><label>Tipo de Documento</label><?print $this->form->typedoc?></td>
			<td><label>Num Documento</label><br><?print $this->form->numdoc?></td>
		</tr>
		<tr>
			<td><label>Fecha de Nacimiento</label><br><?print $this->form->birthday?></td>
			<td><label>Sexo</label><?print $this->form->sex?></td>
		</tr>
		<tr>
			<td><label>Vive?</label><?print $this->form->live?></td>
		</tr>
	</table>
	<table class="table" id="moreinfo">
		<td><label>Esta persona es su Apoderado/a? </label><?print $this->form->assignee?></td>
		<tr>
			<td><label>Dirección</label><?print $this->form->address?></td>
			<td><label>Telefono/Celular</label><br><?print $this->form->phone?></td>
		</tr>
		<tr>
			<td><label>Ocupacion</label><br><?print $this->form->ocupacy?></td>
			<td><label>Sufre de Alguna Enfermedad?</label><?print $this->form->health?></td>
		</tr>
	</table>
	<tr>
		<td></td>
		<td><a class="btn btn-info pull-right" href="#" id="save">Guardar</a></td>
	</tr>
			
</div>

<script>
	$("#save").click(function(){
		
	})
	
	$('#backeditBtn a').click(function (e) {
    	e.preventDefault()
      	$("#editform").html("")
      	$("#editdata").removeClass("hidden")
      	$('#editpalBtns a:last').tab('show')
      	$('#editpalBtns2 a:last').tab('show')
  	})
   
</script>