<div class="panel panel-info">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h3 class="text-muted"><span class="glyphicon glyphicon-briefcase"> </span> Datos Academicos</h3>
    </div>
    <div class="col-md-2 ">
      <br>
      <a href="#" id="newAcademic" class="btn btn-default" title="Nuevo"><span class="text-muted">Nuevo</span></a>
    </div>
  </div>

  <div class="panel-body">
    <?php 
    if($this->acadata) 
      {?> 
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-warning">
        <div class="panel-body">
          <table class="table table-hover">
            <tr>
              <th><h5><strong>#</strong></h5></th>
              <th><h5><strong>Institución</strong></h5></th>
              <th><h5><strong>Tipo</strong></h5></th>
              <th class="text-center"><h5><strong>Nivel de Estudio</strong></h5></th>
              <th class="text-center"><h5><strong>Año de Finalización</strong></h5></th>
            </tr>
      <?php $c = 1;
      foreach ($this->acadata as $academic) {?>
            <tr>
              <td><h5><?php echo $c?></h5></td>
              <td><h5><?php echo $academic['institution']?></h5></td>
              <td><h5>
                <?php if($academic['type']=="E"){
                  echo "Estatal";
                }elseif($academic['type']=="P"){
                  echo "Particular";
                }elseif($academic['type']=="PA"){
                  echo "Parroquial";
                }?></h5></td>
              <td align="center"><h5>
                <?php if($academic['title']=="SE"){
                  echo "Secundaria";
                }elseif($academic['title']=="SU"){
                  echo "Superior";
                }elseif($academic['title']=="DI"){
                  echo "Diplomado";
                }elseif($academic['title']=="PT"){
                  echo "Post Grado";
                }elseif($academic['title']=="PH"){
                  echo "PHD";
                }elseif($academic['title']=="O"){
                  echo "Otros";
                }
                ?></h5></td>
              <td align="center"><h5><?php echo $academic['year_end']?></h5></td>
              <td><h5><a id="delete<?php echo $academic['acid']?>" class="text-warning" href="#" title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
                <script>
                  $("#delete<?php echo $academic['acid']?>").click(function(){
                    $("#datastudent").addClass("hidden")
                    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
                    $("#editform").load("/profile/public/studenteditacademic/acid/<?php echo $academic['acid']?>")
                  })
                </script></h5></td>
                <td><h5><a class="text-warning" id="remove<?php echo $academic['acid']?>" href="#" title="Eliminar"><span class="glyphicon glyphicon-remove"></span></a>
                <script>
                  $("#remove<?php echo $academic['acid']?>").click(function(){
                    bootbox.confirm("Seguro que desea eliminar <?php echo $academic['institution']?>", function(result) {
                        if (result)
                          $("#editform").load("/profile/public/studentremoveacademic/eid/<?php echo $this->data['eid']?>/pid/<?php echo $this->data['pid']?>/acid/<?php echo $academic['acid']?>");
                          $('#editform').html("");
                          $("#datastudent").load("/profile/public/studentacademic");
                      })  
                  })
                </script></h5></td>
            </tr>
                <!--
              </div>
              <div class="col-md-1 pull-right">
                
              </div>
            </div>

            <br>
            <blockquote>
              <h4> <span class="glyphicon glyphicon-link text-muted"></span> </h4>
            </blockquote>
            <hr class="featurette-divider">

            <div class="row">
              <div class="col-md-4 col-md-offset-2">
                <h4><span class="text-muted">Tipo de Institución </span>
                  </h4>
                <h4><span class="text-muted">Año de Finalización </span></h4>
              </div>
              <div class="col-md-4">
                <h4><span class="text-muted">Nivel de Estudio</span>
                  </h4>
                <h4><span class="text-muted">Localización </span></h4>-->
      <?php $c++;
      }?>
          </table>
        </div>
      </div>
    </div>        
  </div>
    <?php }else{
    ?>
      <center><h5 class="text-muted">No tiene Datos Por favor Actualize su Perfil</h5></center>
    <?php  
    }
    ?>
  </div>

</div>

<script>
  $("#newAcademic").click(function(){
    $("#datastudent").addClass("hidden")
    $("#editform").html("<center><br><br><br><br><img src='/img/spinner.gif'></center>");
    $("#editform").load("/profile/public/studentsaveacademic")
  })
</script>