<?php if ($this->form) {?>
    <form id='form_new_project' >
        <div class="modal-dialog modal-ls">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Modificar Proyecto</h4>
                </div>
                <div class="modal-body">
                    <?php echo $this->form->name ?>
                    <label>Tipo:</label>
                    <?php echo $this->form->type ?>
                    <label>Cronograma:</label>
                    <select class="form-control" id='cronogram_proj' name="id_cronogram">
                        <option>Seleccione Cronograma</option>
                    </select>
                    <?php echo $this->form->id_open ?>
                    <label>Estado:</label>
                    <?php echo $this->form->state?>
                    <label>Modalidad:</label>
                    <?php echo $this->form->modality?>
                    <?php echo $this->form->f_presentation?>
                    <?php echo $this->form->f_ini?>
                    <?php echo $this->form->f_fin?>
                    <?php echo $this->form->place ?>
                    <?php echo $this->form->num_horas ?>
                    <?php echo $this->form->min_student ?>
                    <?php echo $this->form->max_student ?>
                    <?php echo $this->form->description ?>
                    <?php echo $this->form->comment ?>
                    <input type='hidden' id='uid_openerp' name='uid_openerp' >
                    <input type='hidden' id = "subid_openerp" name='subid_openerp' >
                    <input type='hidden' id="escid_openerp" name='escid_openerp' >
                    <!-- <div class="upload">
                        <span class="glyphicon glyphicon-file"></span> -->
                        <?php echo $this->form->project ?>
                    <!-- </div> -->
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="button"  id='btn_modified_project'class="btn btn-primary">Guardar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
    <script type="text/javascript">
        var data_cronograma = <?php echo $this->data_cronograman?>,data_project = <?php echo $this->data_project?>

    </script>

<?php }else{
    echo $this->json;
}?>
