<?php if ($this->form) {?>
    <form id='form_new_project' >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Nuevo Proyecto</h4>
                </div>
                <div class="modal-body">
                    <?php echo $this->form->name ?>
                    <label>Tipo:</label>
                    <?php echo $this->form->type ?>
                    <label>Cronograma:</label>
                    <select data-index='' class="form-control" id='cronogram_proj' name="id_cronogram">
                        <option>Seleccione Cronograma</option>
                    </select>
                    <div id='contet_conogram'>
                        <p>
                            <span></span>   
                            <span></span>
                            <span></span>
                        </p>
                    </div>
                    <label>Estado:</label>
                    <?php echo $this->form->state?>
                    <?php echo $this->form->num_horas ?>
                    <?php echo $this->form->min_student ?>
                    <?php echo $this->form->max_student ?>
                    <?php echo $this->form->description ?>
                    <?php echo $this->form->comment ?>
                    <input type='hidden' id='uid_openerp' name='uid_openerp' >
                    <input type='hidden' id = "subid_openerp" name='subid_openerp' >
                    <input type='hidden' id="escid_openerp" name='escid_openerp' >
                    <!-- <div class="upload">
                        <span class="glyphicon glyphicon-file"></span> -->
                        <?php echo $this->form->project ?>
                    <!-- </div> -->
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="button" id='save_project'class="btn btn-primary">Guardar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
<?php }else{
    echo $this->json;
}?>
