<?php
    $hora=array();
    $hour_begin=array();
    if ($this->valhorasm or $this->valhorast) {
        $j=1;
        $hour_begin=$this->valhorasm;
        $hour_begin_afternoon=$this->valhorast;
        $len1= count($hour_begin);
        $len2= count($hour_begin_afternoon);
        $lentotal = $len1+$len2;

        for ($i=0; $i < $len1; $i++) {
            $hourm[$i]=substr($hour_begin[$i],0,2);
            $minutem[$i]=substr($hour_begin[$i],3,2);
        }
        for ($i=0; $i < $len2; $i++) {
            $hourt[$i]=substr($hour_begin_afternoon[$i],0,2);
            $minutet[$i]=substr($hour_begin_afternoon[$i],3,2);
        }
        for ($i=0; $i < $len1-1; $i++) {
            if ($hourm[$i] && $j<$len1) {
                if ($hourm[$i]<12) {
                    if ($hourm[$j]<12) {
                        $hora[$i]['hora']=$hourm[$i].":".$minutem[$i]." am - ".$hourm[$j].":".$minutem[$j]." am";
                    }
                    else{
                        $hora[$i]['hora']=$hourm[$i].":".$minutem[$i]." am - ".$hourm[$j].":".$minutem[$j]." pm";
                    }
                }
                else{
                    $hora[$i]['hora']=$hourm[$i].":".$minutem[$i]." pm - ".$hourm[$j].":".$minutem[$j]." pm";
                }
                $hora[$i]['h_ini']=$hourm[$i];
                $hora[$i]['h_fin']=$hourm[$j];
                $hora[$i]['m_ini']=$minutem[$i];
                $hora[$i]['m_fin']=$minutem[$j];
                $j++;
            }

        }

        $q=1;
        for ($p=0; $p < $len2; $p++) {
            if ($hourt[$p] && $q<$len2) {
                if ($hourt[$p]<12) {
                    if ($hourt[$q]<12) {
                        $hora[$i]['hora']=$hourt[$p].":".$minutet[$p]." am - ".$hourt[$q].":".$minutet[$q]." am";
                    }
                    else{
                        $hora[$i]['hora']=$hourt[$p].":".$minutet[$p]." am - ".$hourt[$q].":".$minutet[$q]." pm";
                    }
                }
                else{
                    $hora[$i]['hora']=$hourt[$p].":".$minutet[$p]." pm - ".$hourt[$q].":".$minutet[$q]." pm";
                }
                $hora[$i]['h_ini']=$hourt[$p];
                $hora[$i]['h_fin']=$hourt[$q];
                $hora[$i]['m_ini']=$minutet[$p];
                $hora[$i]['m_fin']=$minutet[$q];
                $q++;
                $i++;
            }
        }
    }
    else{
        $j=1;
        $hour_begin=$this->valhoras;
        $len= count($hour_begin);
        $lentotal=$len;
        for ($i=0; $i < $len; $i++) {
            $hour[$i]=substr($hour_begin[$i],0,2);
            $minute[$i]=substr($hour_begin[$i],3,2);
        }
        for ($i=0; $i < $len; $i++) {
            if ($hour[$i] && $j<$len) {
                if ($hour[$i]<12) {
                    if ($hour[$j]<12) {
                        $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." am";
                    }
                    else{
                        $hora[$i]['hora']=$hour[$i].":".$minute[$i]." am - ".$hour[$j].":".$minute[$j]." pm";
                    }
                }
                else{
                    $hora[$i]['hora']=$hour[$i].":".$minute[$i]." pm - ".$hour[$j].":".$minute[$j]." pm";
                }
                $hora[$i]['h_ini']=$hour[$i];
                $hora[$i]['h_fin']=$hour[$j];
                $hora[$i]['m_ini']=$minute[$i];
                $hora[$i]['m_fin']=$minute[$j];
                $j++;
            }
        }
    }

    $listacolores = array();
    $listacolores[0] = "#FA8D74";
    $listacolores[1] = "#A3CFE0";
    $listacolores[2] = "#CBE487";
    $listacolores[3] = "#FAF48D";
    $listacolores[4] = "#FCB16B";
    $listacolores[5] = "#CCF0EE";
    $listacolores[6] = "#DFDFDF";
    $listacolores[7] = "#81FF86";
    $listacolores[8] = "#CD88FD";
    $listacolores[9] = "#F59FFC";
    $listacolores[10] = "#A58CFF";
    $listacolores[11] = "#F2BBBB";
    $listacolores[12] = "#D8BADA";
    $listacolores[13] = "#C4E6CE";
    $listacolores[14] = "#B4DAA1";

if ($this->horarios) {
    $len=count($this->horarios);
    $cco=0;
    $hmen=13;
    $hmay=13;
    $n=new Api_Model_DbTable_Course();
    for ($i=0; $i < $len; $i++) {
        $where['eid']=$this->horarios[$i]['eid'];
        $where['oid']=$this->horarios[$i]['oid'];
        $where['escid']=$this->horarios[$i]['escid'];
        $where['curid']=$this->horarios[$i]['curid'];
        $where['subid']=$this->horarios[$i]['subid'];
        $where['courseid']=$this->horarios[$i]['courseid'];
        $ncur=$n->_getOne($where);
        $this->horarios[$i]['namec']=$ncur['name'];
        $this->horarios[$i]['abbreviation']=$ncur['abbreviation'];
        $this->horarios[$i]['credits']=$ncur['credits'];

        if ($this->horarios[$i]['type_class']=="P") $this->horarios[$i]['type_class']="(P)";
        else $this->horarios[$i]['type_class']="";

        $codcurso=$this->horarios[$i]['courseid'];
        $tturno=$this->horarios[$i]['turno'];
        $eescid=$this->horarios[$i]['escid'];
        $codcursodes=(isset($this->horarios[$i+1]['courseid']))?$this->horarios[$i+1]['courseid']:null;
        $tturnodes=(isset($this->horarios[$i+1]['turno']))?$this->horarios[$i+1]['turno']:null;
        $eescids=(isset($this->horarios[$i+1]['escid']))?$this->horarios[$i+1]['escid']:null;
        // $tturnodes=$this->horarios[$i+1]['turno'];
        // $eescids=$this->horarios[$i+1]['escid'];
            if ($codcurso==$codcursodes && $tturno==$tturnodes && $eescid==$eescids){
                $this->horarios[$i]['color']=$listacolores[$cco];
            }
            else {
                $this->horarios[$i]['color']=$listacolores[$cco];
                $cco++;
            }
        $hsplit=split(":", $this->horarios[$i]['hora_ini']);
        $hi=$hsplit[0];
        $hsplit=split(":", $this->horarios[$i]['hora_fin']);
        $hf=$hsplit[0];
        if ($hi<=$hmen) $hmen=$hi;
        if ($hf>=$hmay) $hmay=$hf;
    }
    $k=0;
    for ($z=0; $z < 20; $z++) {
        if ($hmen==$hora[$z]['h_ini'] && $k==0) {
            $inih=$z;
            $k=1;
        }
        if ($hmay==$hora[$z]['h_fin']) $finh=$z;
    }
    $horaoriginal=$this->horarios;
?>
<div class="row col-md-12" style="margin:0px">
    <div class="nomdoc col-md-10" style="font-size:20px; margin-top:20px">
        <b>HORARIO DOCENTE</b>
    </div>
    <div class="col-md-2 pull-rigth" style="margin-top:20px">
        <center><a href="/horary/seehorary/print/perid/<?php echo $this->perid?>" class="btn btn-success" ><i class="glyphicon glyphicon-print"></i> Imprimir</a></center>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Hora:</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Lunes</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Martes</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Miércoles</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Jueves</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Viernes</b></div>
        </div>
        <div class='arreglo pull-left'>
            <div class='cajadia'><b>Sábado</b></div>
        </div>
    </div>
    <div class='col-md-12'>
        <div class='pull-left' style='width:14%'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) { ?>
                <div class="cajadentro"><?php echo $hora[$i]['hora'] ?></div>
            <?php
            }
            ?>
        </div>

        <div class='pull-left' style='width:14%'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) {
                $band=0;
                $c=0;
                $dat=$this->horarios;
                for ($s=0; $s < $len; $s++) {
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                        if ($dia==1) {
                            if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                    $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                    <?php
                                    $c++;
                                } else {
                                    $band=1;
                                }
                            }
                        } else {
                            $band=1;
                        }
                }
                    if ($band==1 && $c==0) { ?>
                        <div class="cajadentro"></div>
                    <?php
                   }
            }
            ?>
            </div>

        <div class='pull-left' style='width:14%'>
            <?php
            for ($i=$inih; $i <= $finh; $i++) {
                $band=0;
                $c=0;
                $dat=$this->horarios;
                for ($s=0; $s < $len; $s++) {
                    $hsplit=split(":", $dat[$s]['hora_ini']);
                    $h=$hsplit[0];
                    $m=$hsplit[1];
                    $dia=$dat[$s]['day'];

                        if ($dia==2) {
                            if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                    $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                    ?>
                                    <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                    <?php
                                    $c++;
                                } else {
                                    $band=1;
                                }
                            }
                        } else {
                            $band=1;
                        }
                }
                    if ($band==1 && $c==0) { ?>
                        <div class="cajadentro"></div>
                    <?php
                    }
            }
                ?>
            </div>

            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh; $i++) {
                        $band=0;
                        $c=0;
                        $dat=$this->horarios;
                        for ($s=0; $s < $len; $s++) {
                            $hsplit=split(":", $dat[$s]['hora_ini']);
                            $h=$hsplit[0];
                            $m=$hsplit[1];
                            $dia=$dat[$s]['day'];

                            if ($dia==3) {
                                if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                   // echo $hora[$i]['m_ini'];
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                        $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                        <?php
                                        $c++;
                                    } else {
                                        $band=1;
                                    }
                                }
                            } else {
                                $band=1;
                            }
                        }
                        if ($band==1 && $c==0) { ?>
                            <div class="cajadentro"></div>
                        <?php
                        }
                }
                ?>
            </div>

            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh; $i++) {
                        $band=0;
                        $c=0;
                        $dat=$this->horarios;
                        for ($s=0; $s < $len; $s++) {
                            $hsplit=split(":", $dat[$s]['hora_ini']);
                            $h=$hsplit[0];
                            $m=$hsplit[1];
                            $dia=$dat[$s]['day'];

                            if ($dia==4) {
                                if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                        $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                        <?php
                                        $c++;
                                    } else {
                                        $band=1;
                                    }
                                }
                            } else {
                                $band=1;
                            }
                        }
                        if ($band==1 && $c==0) { ?>
                            <div class="cajadentro"></div>
                        <?php
                        }
                }
                ?>
            </div>

            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh; $i++) {
                        $band=0;
                        $c=0;
                        $dat=$this->horarios;
                        for ($s=0; $s < $len; $s++) {
                            $hsplit=split(":", $dat[$s]['hora_ini']);
                            $h=$hsplit[0];
                            $m=$hsplit[1];
                            $dia=$dat[$s]['day'];

                            if ($dia==5) {
                                if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                        $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                        <?php
                                        $c++;
                                    } else {
                                        $band=1;
                                    }
                                }
                            } else {
                                $band=1;
                            }
                        }
                        if ($band==1 && $c==0) { ?>
                            <div class="cajadentro"></div>
                        <?php
                        }
                }
                ?>
            </div>

            <div class='pull-left' style='width:14%'>
                <?php
                for ($i=$inih; $i <= $finh; $i++) {
                        $band=0;
                        $c=0;
                        $dat=$this->horarios;
                        for ($s=0; $s < $len; $s++) {
                            $hsplit=split(":", $dat[$s]['hora_ini']);
                            $h=$hsplit[0];
                            $m=$hsplit[1];
                            $dia=$dat[$s]['day'];

                            if ($dia==6) {
                                if ($this->horarios[$s]['hora_ini']!=$this->horarios[$s]['hora_fin']){
                                    if ($hora[$i]['h_ini']==$h && $hora[$i]['m_ini']==$m) {
                                        $this->horarios[$s]['hora_ini']= $hora[$i]['h_fin'].":".$hora[$i]['m_fin'].":00";
                                        ?>
                                        <div class="cajadentro" style="background-color:<?php echo $dat[$s]["color"] ?>"><?php echo $dat[$s]['abbreviation'].$dat[$s]['type_class'] ?><span class="pull-right" style="margin-right:1%">( <?php echo $dat[$s]['turno']?> )</span></div>
                                        <?php
                                        $c++;
                                    } else {
                                        $band=1;
                                    }
                                }
                            } else {
                                $band=1;
                            }
                        }
                        if ($band==1 && $c==0) { ?>
                            <div class="cajadentro"></div>
                        <?php
                        }
                }
                ?>
            </div>
        </div>
    <div class="row">
        <div class='col-md-12' style="margin-bottom:1%; margin-left:5%">
            <div class='cajadia' style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>#</b></div>
            <div class="cajadia" style='width:10%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Cod. Curso</b></div>
            <div class="cajadia" style='width:50%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Nombre Curso</b></div>
            <div class="cajadia" style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Créditos</b></div>
            <div class="cajadia" style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Turno</b></div>
            <div class="cajadia" style='width:5%; margin-right:1%; margin-top:3%; box-shadow: 0px 0px 4px #343434'><b>Semestre</b></div>
        </div>
            <?php
            $n=1;
            for ($d=0; $d < count($this->cursos); $d++) {

                for ($f=0; $f < count($horaoriginal); $f++) {

                    if ($this->cursos[$d]['courseid']==$horaoriginal[$f]['courseid'] && $this->cursos[$d]['turno']==$horaoriginal[$f]['turno'] && $this->cursos[$d]['escid']==$horaoriginal[$f]['escid']){
                    ?>
                    <div class='col-md-12' style="margin-left:5%">
                        <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $n ?></div>
                        <div class="cajacursos" style="width:10%; margin-right:1%;background-color:<?php echo $horaoriginal[$f]["color"] ?>"><?php echo $horaoriginal[$f]['courseid'] ?></div>
                        <div class="cajacursos" style="width:50%; margin-right:1%;">
                            <?php
                            echo $horaoriginal[$f]['name']=(isset($horaoriginal[$f]['name']))?$horaoriginal[$f]['namec']."---".$horaoriginal[$f]['name']:$horaoriginal[$f]['namec'];
                            /*if (isset($horaoriginal[$f]['name'])) {
                                echo $horaoriginal[$f]['namec']."---".$horaoriginal[$f]['name'];
                            }
                            else{
                                echo $horaoriginal[$f]['namec'];
                            }*/
                        ?>
                        </div>
                        <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $horaoriginal[$f]['credits'] ?></div>
                        <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $horaoriginal[$f]['turno'] ?></div>
                        <div class="cajacursos" style="width:5%; margin-right:1%;"><?php echo $horaoriginal[$f]['semid'] ?></div>
                    </div>
                    <?php
                    $n++;
                    $f = count($horaoriginal);
                    }
                }
            }
            ?>
    </div>
</div>
<?php
}
else {
    ?>
    <div class="alert alert-success col-md-10">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <b>No hay registro de horario.</b>
    </div>
    <?php
    }
    ?>